import type { ContentBlock } from '../types'

/**
 * B2 Level Content — Week 2
 * Topic: B2 · Semana 2 – Ideas, ideología y sociedad
 * Curated from institutional curriculum (Zero AI)
 */
export const week02: ContentBlock = {
  "level": "B2",
  "week": 2,
  "topic": "B2 · Semana 2 – Ideas, ideología y sociedad",
  "vocabulary": [
    {
      "id": "voc_b2_ideology_019",
      "word": "ideology",
      "translation": "ideología",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 2,
      "topic": "ideas_society",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_philosophy_020",
      "word": "philosophy",
      "translation": "filosofía",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 2,
      "topic": "ideas_society",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_ethics_021",
      "word": "ethics",
      "translation": "ética",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 2,
      "topic": "ideas_society",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_morality_022",
      "word": "morality",
      "translation": "moralidad",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 2,
      "topic": "ideas_society",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_autonomy_023",
      "word": "autonomy",
      "translation": "autonomía",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 2,
      "topic": "ideas_society",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_sovereignty_024",
      "word": "sovereignty",
      "translation": "soberanía",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 2,
      "topic": "ideas_society",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_legislation_025",
      "word": "legislation",
      "translation": "legislación",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 2,
      "topic": "ideas_society",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_jurisdiction_026",
      "word": "jurisdiction",
      "translation": "jurisdicción",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 2,
      "topic": "ideas_society",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_advocacy_027",
      "word": "advocacy",
      "translation": "apoyo/defensa de una causa",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 2,
      "topic": "ideas_society",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_activism_028",
      "word": "activism",
      "translation": "activismo",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 2,
      "topic": "ideas_society",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_discrimination_029",
      "word": "discrimination",
      "translation": "discriminación",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 2,
      "topic": "ideas_society",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_prejudice_030",
      "word": "prejudice",
      "translation": "prejuicio",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 2,
      "topic": "ideas_society",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_stereotype_031",
      "word": "stereotype",
      "translation": "estereotipo",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 2,
      "topic": "ideas_society",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_stigma_032",
      "word": "stigma",
      "translation": "estigma",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 2,
      "topic": "ideas_society",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_marginalization_033",
      "word": "marginalization",
      "translation": "marginación",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 2,
      "topic": "ideas_society",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_inequality_034",
      "word": "inequality",
      "translation": "desigualdad",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 2,
      "topic": "ideas_society",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_disparity_035",
      "word": "disparity",
      "translation": "disparidad",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 2,
      "topic": "ideas_society",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_privilege-noun_036",
      "word": "privilege (noun)",
      "translation": "privilegio",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 2,
      "topic": "ideas_society",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_empowerment_037",
      "word": "empowerment",
      "translation": "empoderamiento",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 2,
      "topic": "ideas_society",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_exploitation_038",
      "word": "exploitation",
      "translation": "explotación",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 2,
      "topic": "ideas_society",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_oppression_039",
      "word": "oppression",
      "translation": "opresión",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 2,
      "topic": "ideas_society",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    }
  ]
}
