import type { ContentBlock } from '../types'

/**
 * B2 Level Content — Week 3
 * Topic: Phrasal verbs avanzados e idioms esenciales
 * Curated from institutional curriculum (Zero AI)
 */
export const week03: ContentBlock = {
  level: 'B2',
  week: 3,
  topic: 'Phrasal verbs avanzados e idioms esenciales',
  vocabulary: [
    {
      id: 'voc_b2_look-forward-to_061',
      word: 'look forward to',
      translation: 'esperar con ilusión / anhelar',
      partOfSpeech: 'phrasal-verb',
      level: 'B2',
      week: 3,
      topic: 'phrasal-verbs-avanzados',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_get-along-with_062',
      word: 'get along with',
      translation: 'llevarse bien con alguien',
      partOfSpeech: 'phrasal-verb',
      level: 'B2',
      week: 3,
      topic: 'phrasal-verbs-avanzados',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_come-up-with_063',
      word: 'come up with',
      translation: 'idear / proponer una solución',
      partOfSpeech: 'phrasal-verb',
      level: 'B2',
      week: 3,
      topic: 'phrasal-verbs-avanzados',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_put-up-with_064',
      word: 'put up with',
      translation: 'tolerar / aguantar una situación',
      partOfSpeech: 'phrasal-verb',
      level: 'B2',
      week: 3,
      topic: 'phrasal-verbs-avanzados',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_run-out-of_065',
      word: 'run out of',
      translation: 'quedarse sin provisiones o tiempo',
      partOfSpeech: 'phrasal-verb',
      level: 'B2',
      week: 3,
      topic: 'phrasal-verbs-avanzados',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_cut-down-on_066',
      word: 'cut down on',
      translation: 'reducir el consumo de algo',
      partOfSpeech: 'phrasal-verb',
      level: 'B2',
      week: 3,
      topic: 'phrasal-verbs-avanzados',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_catch-up-with_067',
      word: 'catch up with',
      translation: 'ponerse al día con alguien',
      partOfSpeech: 'phrasal-verb',
      level: 'B2',
      week: 3,
      topic: 'phrasal-verbs-avanzados',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_look-down-on_068',
      word: 'look down on',
      translation: 'mirar por encima del hombro / despreciar',
      partOfSpeech: 'phrasal-verb',
      level: 'B2',
      week: 3,
      topic: 'phrasal-verbs-avanzados',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_look-up-to_069',
      word: 'look up to',
      translation: 'admirar y respetar a alguien',
      partOfSpeech: 'phrasal-verb',
      level: 'B2',
      week: 3,
      topic: 'phrasal-verbs-avanzados',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_stand-up-for_070',
      word: 'stand up for',
      translation: 'defender con firmeza una postura',
      partOfSpeech: 'phrasal-verb',
      level: 'B2',
      week: 3,
      topic: 'phrasal-verbs-avanzados',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_back-down_071',
      word: 'back down',
      translation: 'retractarse / ceder en una discusión',
      partOfSpeech: 'phrasal-verb',
      level: 'B2',
      week: 3,
      topic: 'phrasal-verbs-avanzados',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_bring-about_072',
      word: 'bring about',
      translation: 'provocar / ocasionar un cambio',
      partOfSpeech: 'phrasal-verb',
      level: 'B2',
      week: 3,
      topic: 'phrasal-verbs-avanzados',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_call-off_073',
      word: 'call off',
      translation: 'cancelar definitivamente',
      partOfSpeech: 'phrasal-verb',
      level: 'B2',
      week: 3,
      topic: 'phrasal-verbs-avanzados',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_carry-out_074',
      word: 'carry out',
      translation: 'llevar a cabo / ejecutar una tarea',
      partOfSpeech: 'phrasal-verb',
      level: 'B2',
      week: 3,
      topic: 'phrasal-verbs-avanzados',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_figure-out_075',
      word: 'figure out',
      translation: 'comprender / descifrar / resolver',
      partOfSpeech: 'phrasal-verb',
      level: 'B2',
      week: 3,
      topic: 'phrasal-verbs-avanzados',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_give-up_076',
      word: 'give up',
      translation: 'rendirse / abandonar un hábito',
      partOfSpeech: 'phrasal-verb',
      level: 'B2',
      week: 3,
      topic: 'phrasal-verbs-avanzados',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_point-out_077',
      word: 'point out',
      translation: 'señalar / recalcar un dato',
      partOfSpeech: 'phrasal-verb',
      level: 'B2',
      week: 3,
      topic: 'phrasal-verbs-avanzados',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_put-off_078',
      word: 'put off',
      translation: 'posponer / aplazar una fecha',
      partOfSpeech: 'phrasal-verb',
      level: 'B2',
      week: 3,
      topic: 'phrasal-verbs-avanzados',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_rule-out_079',
      word: 'rule out',
      translation: 'descartar una posibilidad',
      partOfSpeech: 'phrasal-verb',
      level: 'B2',
      week: 3,
      topic: 'phrasal-verbs-avanzados',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_take-over_080',
      word: 'take over',
      translation: 'asumir el control o mando',
      partOfSpeech: 'phrasal-verb',
      level: 'B2',
      week: 3,
      topic: 'phrasal-verbs-avanzados',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_turn-down_081',
      word: 'turn down',
      translation: 'rechazar una oferta o propuesta',
      partOfSpeech: 'phrasal-verb',
      level: 'B2',
      week: 3,
      topic: 'phrasal-verbs-avanzados',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_wind-up_082',
      word: 'wind up',
      translation: 'terminar o desembocar en una situación',
      partOfSpeech: 'phrasal-verb',
      level: 'B2',
      week: 3,
      topic: 'phrasal-verbs-avanzados',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_see-eye-to-eye_083',
      word: 'see eye to eye',
      translation: 'estar de pleno acuerdo con alguien',
      partOfSpeech: 'phrasal-verb',
      level: 'B2',
      week: 3,
      topic: 'phrasal-verbs-avanzados',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_bite-the-bullet_084',
      word: 'bite the bullet',
      translation: 'afrontar una situación difícil con valor',
      partOfSpeech: 'phrasal-verb',
      level: 'B2',
      week: 3,
      topic: 'phrasal-verbs-avanzados',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_beat-around-the-bush_085',
      word: 'beat around the bush',
      translation: 'irse por las ramas / evitar el punto',
      partOfSpeech: 'phrasal-verb',
      level: 'B2',
      week: 3,
      topic: 'phrasal-verbs-avanzados',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_read-between-the-lines_086',
      word: 'read between the lines',
      translation: 'leer entre líneas / captar el subtexto',
      partOfSpeech: 'phrasal-verb',
      level: 'B2',
      week: 3,
      topic: 'phrasal-verbs-avanzados',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
  ],
}
