import type { ContentBlock } from '../types'

/**
 * B2 Level Content — Week 1
 * Topic: Conceptos abstractos y registro formal
 * Curated from institutional curriculum (Zero AI)
 */
export const week01: ContentBlock = {
  level: 'B2',
  week: 1,
  topic: 'Conceptos abstractos y registro formal',
  vocabulary: [
    {
      id: 'voc_b2_abstract_001',
      word: 'abstract',
      translation: 'abstracto / conceptual',
      partOfSpeech: 'adjective',
      level: 'B2',
      week: 1,
      topic: 'conceptos-abstractos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_tangible_002',
      word: 'tangible',
      translation: 'tangible / palpable',
      partOfSpeech: 'adjective',
      level: 'B2',
      week: 1,
      topic: 'conceptos-abstractos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_nuance_003',
      word: 'nuance',
      translation: 'matiz / sutileza',
      partOfSpeech: 'noun',
      level: 'B2',
      week: 1,
      topic: 'conceptos-abstractos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_ambiguity_004',
      word: 'ambiguity',
      translation: 'ambigüedad',
      partOfSpeech: 'noun',
      level: 'B2',
      week: 1,
      topic: 'conceptos-abstractos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_paradox_005',
      word: 'paradox',
      translation: 'paradoja',
      partOfSpeech: 'noun',
      level: 'B2',
      week: 1,
      topic: 'conceptos-abstractos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_implication_006',
      word: 'implication',
      translation: 'implicación / repercusión',
      partOfSpeech: 'noun',
      level: 'B2',
      week: 1,
      topic: 'conceptos-abstractos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_phenomenon_007',
      word: 'phenomenon',
      translation: 'fenómeno',
      partOfSpeech: 'noun',
      level: 'B2',
      week: 1,
      topic: 'conceptos-abstractos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_perception_008',
      word: 'perception',
      translation: 'percepción',
      partOfSpeech: 'noun',
      level: 'B2',
      week: 1,
      topic: 'conceptos-abstractos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_insight_009',
      word: 'insight',
      translation: 'perspicacia / comprensión profunda',
      partOfSpeech: 'noun',
      level: 'B2',
      week: 1,
      topic: 'conceptos-abstractos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_premise_010',
      word: 'premise',
      translation: 'premisa de partida',
      partOfSpeech: 'noun',
      level: 'B2',
      week: 1,
      topic: 'conceptos-abstractos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_coherent_011',
      word: 'coherent',
      translation: 'coherente / articulado',
      partOfSpeech: 'adjective',
      level: 'B2',
      week: 1,
      topic: 'conceptos-abstractos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_contradictory_012',
      word: 'contradictory',
      translation: 'contradictorio',
      partOfSpeech: 'adjective',
      level: 'B2',
      week: 1,
      topic: 'conceptos-abstractos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_plausible_013',
      word: 'plausible',
      translation: 'plausible / verosímil',
      partOfSpeech: 'adjective',
      level: 'B2',
      week: 1,
      topic: 'conceptos-abstractos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_arbitrary_014',
      word: 'arbitrary',
      translation: 'arbitrario',
      partOfSpeech: 'adjective',
      level: 'B2',
      week: 1,
      topic: 'conceptos-abstractos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_inherent_015',
      word: 'inherent',
      translation: 'inherente / inseparable',
      partOfSpeech: 'adjective',
      level: 'B2',
      week: 1,
      topic: 'conceptos-abstractos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_intrinsic_016',
      word: 'intrinsic',
      translation: 'intrínseco / propio',
      partOfSpeech: 'adjective',
      level: 'B2',
      week: 1,
      topic: 'conceptos-abstractos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_profound_017',
      word: 'profound',
      translation: 'profundo / trascendental',
      partOfSpeech: 'adjective',
      level: 'B2',
      week: 1,
      topic: 'conceptos-abstractos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_superficial_018',
      word: 'superficial',
      translation: 'superficial / somero',
      partOfSpeech: 'adjective',
      level: 'B2',
      week: 1,
      topic: 'conceptos-abstractos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_discern_019',
      word: 'discern',
      translation: 'discernir / distinguir con claridad',
      partOfSpeech: 'verb',
      level: 'B2',
      week: 1,
      topic: 'conceptos-abstractos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_perceive_020',
      word: 'perceive',
      translation: 'percibir / notar',
      partOfSpeech: 'verb',
      level: 'B2',
      week: 1,
      topic: 'conceptos-abstractos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_interpret_021',
      word: 'interpret',
      translation: 'interpretar',
      partOfSpeech: 'verb',
      level: 'B2',
      week: 1,
      topic: 'conceptos-abstractos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_articulate_022',
      word: 'articulate',
      translation: 'articular / expresar con claridad',
      partOfSpeech: 'verb',
      level: 'B2',
      week: 1,
      topic: 'conceptos-abstractos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_deduce_023',
      word: 'deduce',
      translation: 'deducir',
      partOfSpeech: 'verb',
      level: 'B2',
      week: 1,
      topic: 'conceptos-abstractos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_infer_024',
      word: 'infer',
      translation: 'inferir / colegir',
      partOfSpeech: 'verb',
      level: 'B2',
      week: 1,
      topic: 'conceptos-abstractos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_synthesize_025',
      word: 'synthesize',
      translation: 'sintetizar ideas',
      partOfSpeech: 'verb',
      level: 'B2',
      week: 1,
      topic: 'conceptos-abstractos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_corroborate_026',
      word: 'corroborate',
      translation: 'corroborar / confirmar',
      partOfSpeech: 'verb',
      level: 'B2',
      week: 1,
      topic: 'conceptos-abstractos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_refute_027',
      word: 'refute',
      translation: 'refutar / rebatir',
      partOfSpeech: 'verb',
      level: 'B2',
      week: 1,
      topic: 'conceptos-abstractos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_rationalize_028',
      word: 'rationalize',
      translation: 'racionalizar',
      partOfSpeech: 'verb',
      level: 'B2',
      week: 1,
      topic: 'conceptos-abstractos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_contemplate_029',
      word: 'contemplate',
      translation: 'contemplar / meditar',
      partOfSpeech: 'verb',
      level: 'B2',
      week: 1,
      topic: 'conceptos-abstractos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_skepticism_030',
      word: 'skepticism',
      translation: 'escepticismo',
      partOfSpeech: 'noun',
      level: 'B2',
      week: 1,
      topic: 'conceptos-abstractos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
  ],
}
