import type { ContentBlock } from '../types'

/**
 * B2 Level Content — Week 1
 * Topic: B2 · Semana 1 – Matices de significado y registro
 * Curated from institutional curriculum (Zero AI)
 */
export const week01: ContentBlock = {
  level: "B2",
  week: 1,
  topic: "B2 · Semana 1 – Matices de significado y registro",
  vocabulary: [
    {
      "id": "voc_b2_nuance_001",
      word: "nuance",
      translation: "matiz",
      partOfSpeech: 'noun',
      level: "B2",
      week: 1,
      topic: "nuance_register",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈnuˌɑns/',
      example: 'There is a subtle nuance between these two words.',
      exampleTranslation: 'Hay un matiz sutil entre estas dos palabras.',
      status: 'approved',
    },
    {
      "id": "voc_b2_connotation_002",
      word: "connotation",
      translation: "connotación",
      partOfSpeech: 'noun',
      level: "B2",
      week: 1,
      topic: "nuance_register",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˌkɑnəˈteɪʃən/',
      example: 'The word has a negative connotation in this context.',
      exampleTranslation: 'La palabra tiene una connotación negativa en este contexto.',
      status: 'approved',
    },
    {
      "id": "voc_b2_implication_003",
      word: "implication",
      translation: "implicación",
      partOfSpeech: 'noun',
      level: "B2",
      week: 1,
      topic: "nuance_register",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˌɪmpləˈkeɪʃən/',
      example: 'The policy has serious implications for small businesses.',
      exampleTranslation: 'La política tiene implicaciones serias para las pequeñas empresas.',
      status: 'approved',
    },
    {
      "id": "voc_b2_subtlety_004",
      word: "subtlety",
      translation: "sutileza",
      partOfSpeech: 'noun',
      level: "B2",
      week: 1,
      topic: "nuance_register",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈsʌtəlti/',
      example: 'The subtlety of her argument impressed the judges.',
      exampleTranslation: 'La sutileza de su argumento impresionó a los jueces.',
      status: 'approved',
    },
    {
      "id": "voc_b2_rhetoric_005",
      word: "rhetoric",
      translation: "retórica",
      partOfSpeech: 'noun',
      level: "B2",
      week: 1,
      topic: "nuance_register",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈrɛtərɪk/',
      example: 'His speech was full of empty rhetoric.',
      exampleTranslation: 'Su discurso estaba lleno de retórica vacía.',
      status: 'approved',
    },
    {
      "id": "voc_b2_discourse_006",
      word: "discourse",
      translation: "discurso (análisis)",
      partOfSpeech: 'noun',
      level: "B2",
      week: 1,
      topic: "nuance_register",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈdɪsˌkɔrs/',
      example: 'Political discourse has become more polarized.',
      exampleTranslation: 'El discurso político se ha vuelto más polarizado.',
      status: 'approved',
    },
    {
      "id": "voc_b2_register-language_007",
      word: "register (language)",
      translation: "registro (lingüístico)",
      partOfSpeech: 'noun',
      level: "B2",
      week: 1,
      topic: "nuance_register",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈrɛdʒɪstər/',
      example: 'She switched to a more formal register during the interview.',
      exampleTranslation: 'Ella cambió a un registro más formal durante la entrevista.',
      status: 'approved',
    },
    {
      "id": "voc_b2_colloquial_008",
      word: "colloquial",
      translation: "coloquial",
      partOfSpeech: 'adjective',
      level: "B2",
      week: 1,
      topic: "nuance_register",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/kəˈloʊkwiəl/',
      example: 'That phrase is too colloquial for a business email.',
      exampleTranslation: 'Esa frase es demasiado coloquial para un correo de negocios.',
      status: 'approved',
    },
    {
      "id": "voc_b2_vernacular_009",
      word: "vernacular",
      translation: "vernáculo/habla local",
      partOfSpeech: 'noun',
      level: "B2",
      week: 1,
      topic: "nuance_register",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/vərˈnækjələr/',
      example: 'The novel is written in the local vernacular.',
      exampleTranslation: 'La novela está escrita en el habla local.',
      status: 'approved',
    },
    {
      "id": "voc_b2_jargon_010",
      word: "jargon",
      translation: "jerga (técnica)",
      partOfSpeech: 'noun',
      level: "B2",
      week: 1,
      topic: "nuance_register",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈdʒɑrgən/',
      example: 'The report was full of technical jargon.',
      exampleTranslation: 'El informe estaba lleno de jerga técnica.',
      status: 'approved',
    },
    {
      "id": "voc_b2_ambiguity_011",
      word: "ambiguity",
      translation: "ambigüedad",
      partOfSpeech: 'noun',
      level: "B2",
      week: 1,
      topic: "nuance_register",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˌæmbɪˈgjuəti/',
      example: 'The contract\'s ambiguity caused confusion.',
      exampleTranslation: 'La ambigüedad del contrato causó confusión.',
      status: 'approved',
    },
    {
      "id": "voc_b2_paradox_012",
      word: "paradox",
      translation: "paradoja",
      partOfSpeech: 'noun',
      level: "B2",
      week: 1,
      topic: "nuance_register",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈpɛrəˌdɑks/',
      example: 'It\'s a paradox that helping too much can hurt.',
      exampleTranslation: 'Es una paradoja que ayudar demasiado puede perjudicar.',
      status: 'approved',
    },
    {
      "id": "voc_b2_irony_013",
      word: "irony",
      translation: "ironía",
      partOfSpeech: 'noun',
      level: "B2",
      week: 1,
      topic: "nuance_register",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈaɪrəni/',
      example: 'The irony of the situation wasn\'t lost on anyone.',
      exampleTranslation: 'Nadie pasó por alto la ironía de la situación.',
      status: 'approved',
    },
    {
      "id": "voc_b2_cynicism_014",
      word: "cynicism",
      translation: "cinismo",
      partOfSpeech: 'noun',
      level: "B2",
      week: 1,
      topic: "nuance_register",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈsɪnɪˌsɪzəm/',
      example: 'His cynicism made it hard to trust his advice.',
      exampleTranslation: 'Su cinismo dificultaba confiar en su consejo.',
      status: 'approved',
    },
    {
      "id": "voc_b2_skepticism_015",
      word: "skepticism",
      translation: "escepticismo",
      partOfSpeech: 'noun',
      level: "B2",
      week: 1,
      topic: "nuance_register",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈskɛptɪˌsɪzəm/',
      example: 'She approached the claim with healthy skepticism.',
      exampleTranslation: 'Ella abordó la afirmación con un sano escepticismo.',
      status: 'approved',
    },
    {
      "id": "voc_b2_euphemism_016",
      word: "euphemism",
      translation: "eufemismo",
      partOfSpeech: 'noun',
      level: "B2",
      week: 1,
      topic: "nuance_register",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈjufəˌmɪzəm/',
      example: '"Letting someone go" is a euphemism for firing.',
      exampleTranslation: '"Dejar ir a alguien" es un eufemismo para despedir.',
      status: 'approved',
    },
    {
      "id": "voc_b2_understatement_017",
      word: "understatement",
      translation: "subestimación/decir menos de lo que es",
      partOfSpeech: 'noun',
      level: "B2",
      week: 1,
      topic: "nuance_register",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈʌndərˌsteɪtmənt/',
      example: 'Calling it a challenge was an understatement.',
      exampleTranslation: 'Llamarlo un reto fue quedarse corto.',
      status: 'approved',
    },
    {
      "id": "voc_b2_overstatement_018",
      word: "overstatement",
      translation: "exageración",
      partOfSpeech: 'noun',
      level: "B2",
      week: 1,
      topic: "nuance_register",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈoʊvərˌsteɪtmənt/',
      example: 'Saying it changed everything is an overstatement.',
      exampleTranslation: 'Decir que cambió todo es una exageración.',
      status: 'approved',
    }
  ]
}
