import type { ContentBlock } from '../types'

/**
 * B2 Level Content — Week 1
 * Topic: B2 · Semana 1 – Matices de significado y registro
 * Curated from institutional curriculum (Zero AI)
 */
export const week01: ContentBlock = {
  "level": "B2",
  "week": 1,
  "topic": "B2 · Semana 1 – Matices de significado y registro",
  "vocabulary": [
    {
      "id": "voc_b2_nuance_001",
      "word": "nuance",
      "translation": "matiz",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 1,
      "topic": "nuance_register",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_connotation_002",
      "word": "connotation",
      "translation": "connotación",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 1,
      "topic": "nuance_register",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_implication_003",
      "word": "implication",
      "translation": "implicación",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 1,
      "topic": "nuance_register",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_subtlety_004",
      "word": "subtlety",
      "translation": "sutileza",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 1,
      "topic": "nuance_register",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_rhetoric_005",
      "word": "rhetoric",
      "translation": "retórica",
      "partOfSpeech": "adjective",
      "level": "B2",
      "week": 1,
      "topic": "nuance_register",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_discourse_006",
      "word": "discourse",
      "translation": "discurso (análisis)",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 1,
      "topic": "nuance_register",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_register-language_007",
      "word": "register (language)",
      "translation": "registro (lingüístico)",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 1,
      "topic": "nuance_register",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_colloquial_008",
      "word": "colloquial",
      "translation": "coloquial",
      "partOfSpeech": "adjective",
      "level": "B2",
      "week": 1,
      "topic": "nuance_register",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_vernacular_009",
      "word": "vernacular",
      "translation": "vernáculo/habla local",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 1,
      "topic": "nuance_register",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_jargon_010",
      "word": "jargon",
      "translation": "jerga (técnica)",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 1,
      "topic": "nuance_register",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_ambiguity_011",
      "word": "ambiguity",
      "translation": "ambigüedad",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 1,
      "topic": "nuance_register",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_paradox_012",
      "word": "paradox",
      "translation": "paradoja",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 1,
      "topic": "nuance_register",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_irony_013",
      "word": "irony",
      "translation": "ironía",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 1,
      "topic": "nuance_register",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_cynicism_014",
      "word": "cynicism",
      "translation": "cinismo",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 1,
      "topic": "nuance_register",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_skepticism_015",
      "word": "skepticism",
      "translation": "escepticismo",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 1,
      "topic": "nuance_register",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_euphemism_016",
      "word": "euphemism",
      "translation": "eufemismo",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 1,
      "topic": "nuance_register",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_understatement_017",
      "word": "understatement",
      "translation": "subestimación/decir menos de lo que es",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 1,
      "topic": "nuance_register",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_overstatement_018",
      "word": "overstatement",
      "translation": "exageración",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 1,
      "topic": "nuance_register",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    }
  ]
}
