import type { ContentBlock } from '../types'

/**
 * B2 Level Content — Week 3
 * Topic: B2 · Semana 3 – Cambio, tecnología y procesos globales
 * Curated from institutional curriculum (Zero AI)
 */
export const week03: ContentBlock = {
  "level": "B2",
  "week": 3,
  "topic": "B2 · Semana 3 – Cambio, tecnología y procesos globales",
  "vocabulary": [
    {
      "id": "voc_b2_globalization_040",
      "word": "globalization",
      "translation": "globalización",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 3,
      "topic": "change_technology",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_urbanization_041",
      "word": "urbanization",
      "translation": "urbanización",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 3,
      "topic": "change_technology",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_industrialization_042",
      "word": "industrialization",
      "translation": "industrialización",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 3,
      "topic": "change_technology",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_digitalization_043",
      "word": "digitalization",
      "translation": "digitalización",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 3,
      "topic": "change_technology",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_automation_044",
      "word": "automation",
      "translation": "automatización",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 3,
      "topic": "change_technology",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_disruption_045",
      "word": "disruption",
      "translation": "disrupción",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 3,
      "topic": "change_technology",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_innovation_046",
      "word": "innovation",
      "translation": "innovación",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 3,
      "topic": "change_technology",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_obsolete_047",
      "word": "obsolete",
      "translation": "obsoleto",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 3,
      "topic": "change_technology",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_paradigm_048",
      "word": "paradigm",
      "translation": "paradigma",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 3,
      "topic": "change_technology",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_hypothesis_049",
      "word": "hypothesis",
      "translation": "hipótesis",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 3,
      "topic": "change_technology",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_methodology_050",
      "word": "methodology",
      "translation": "metodología",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 3,
      "topic": "change_technology",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_correlation_051",
      "word": "correlation",
      "translation": "correlación",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 3,
      "topic": "change_technology",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_causation_052",
      "word": "causation",
      "translation": "causalidad",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 3,
      "topic": "change_technology",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_variable-noun_053",
      "word": "variable (noun)",
      "translation": "variable",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 3,
      "topic": "change_technology",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_empirical_054",
      "word": "empirical",
      "translation": "empírico",
      "partOfSpeech": "adjective",
      "level": "B2",
      "week": 3,
      "topic": "change_technology",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_qualitative_055",
      "word": "qualitative",
      "translation": "cualitativo",
      "partOfSpeech": "adjective",
      "level": "B2",
      "week": 3,
      "topic": "change_technology",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_quantitative_056",
      "word": "quantitative",
      "translation": "cuantitativo",
      "partOfSpeech": "adjective",
      "level": "B2",
      "week": 3,
      "topic": "change_technology",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b2_synthesis_057",
      "word": "synthesis",
      "translation": "síntesis",
      "partOfSpeech": "noun",
      "level": "B2",
      "week": 3,
      "topic": "change_technology",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    }
  ]
}
