import type { ContentBlock } from '../types'

/**
 * B2 Level Content — Week 2
 * Topic: Negocios internacionales, liderazgo y estrategia
 * Curated from institutional curriculum (Zero AI)
 */
export const week02: ContentBlock = {
  level: 'B2',
  week: 2,
  topic: 'Negocios internacionales, liderazgo y estrategia',
  vocabulary: [
    {
      id: 'voc_b2_leadership_031',
      word: 'leadership',
      translation: 'liderazgo',
      partOfSpeech: 'noun',
      level: 'B2',
      week: 2,
      topic: 'negocios-y-liderazgo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_strategy_032',
      word: 'strategy',
      translation: 'estrategia',
      partOfSpeech: 'noun',
      level: 'B2',
      week: 2,
      topic: 'negocios-y-liderazgo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_stakeholder_033',
      word: 'stakeholder',
      translation: 'parte interesada / actor clave',
      partOfSpeech: 'noun',
      level: 'B2',
      week: 2,
      topic: 'negocios-y-liderazgo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_shareholder_034',
      word: 'shareholder',
      translation: 'accionista',
      partOfSpeech: 'noun',
      level: 'B2',
      week: 2,
      topic: 'negocios-y-liderazgo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_negotiation_035',
      word: 'negotiation',
      translation: 'negociación',
      partOfSpeech: 'noun',
      level: 'B2',
      week: 2,
      topic: 'negocios-y-liderazgo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_compromise_036',
      word: 'compromise',
      translation: 'acuerdo mutuo / cesión negociada',
      partOfSpeech: 'noun',
      level: 'B2',
      week: 2,
      topic: 'negocios-y-liderazgo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_milestone_037',
      word: 'milestone',
      translation: 'hito / etapa clave',
      partOfSpeech: 'noun',
      level: 'B2',
      week: 2,
      topic: 'negocios-y-liderazgo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_benchmark_038',
      word: 'benchmark',
      translation: 'estándar de referencia',
      partOfSpeech: 'noun',
      level: 'B2',
      week: 2,
      topic: 'negocios-y-liderazgo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_merger_039',
      word: 'merger',
      translation: 'fusión empresarial',
      partOfSpeech: 'noun',
      level: 'B2',
      week: 2,
      topic: 'negocios-y-liderazgo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_acquisition_040',
      word: 'acquisition',
      translation: 'adquisición corporativa',
      partOfSpeech: 'noun',
      level: 'B2',
      week: 2,
      topic: 'negocios-y-liderazgo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_entrepreneurship_041',
      word: 'entrepreneurship',
      translation: 'emprendimiento',
      partOfSpeech: 'noun',
      level: 'B2',
      week: 2,
      topic: 'negocios-y-liderazgo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_accountability_042',
      word: 'accountability',
      translation: 'responsabilidad / rendición de cuentas',
      partOfSpeech: 'noun',
      level: 'B2',
      week: 2,
      topic: 'negocios-y-liderazgo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_transparency_043',
      word: 'transparency',
      translation: 'transparencia corporativa',
      partOfSpeech: 'noun',
      level: 'B2',
      week: 2,
      topic: 'negocios-y-liderazgo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_compliance_044',
      word: 'compliance',
      translation: 'cumplimiento normativo y legal',
      partOfSpeech: 'noun',
      level: 'B2',
      week: 2,
      topic: 'negocios-y-liderazgo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_delegation_045',
      word: 'delegation',
      translation: 'delegación de funciones',
      partOfSpeech: 'noun',
      level: 'B2',
      week: 2,
      topic: 'negocios-y-liderazgo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_productivity_046',
      word: 'productivity',
      translation: 'productividad',
      partOfSpeech: 'noun',
      level: 'B2',
      week: 2,
      topic: 'negocios-y-liderazgo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_efficiency_047',
      word: 'efficiency',
      translation: 'eficiencia operativa',
      partOfSpeech: 'noun',
      level: 'B2',
      week: 2,
      topic: 'negocios-y-liderazgo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_optimize_048',
      word: 'optimize',
      translation: 'optimizar recursos',
      partOfSpeech: 'verb',
      level: 'B2',
      week: 2,
      topic: 'negocios-y-liderazgo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_execute_049',
      word: 'execute',
      translation: 'ejecutar un plan de acción',
      partOfSpeech: 'verb',
      level: 'B2',
      week: 2,
      topic: 'negocios-y-liderazgo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_negotiate_050',
      word: 'negotiate',
      translation: 'negociar acuerdos',
      partOfSpeech: 'verb',
      level: 'B2',
      week: 2,
      topic: 'negocios-y-liderazgo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_implement_051',
      word: 'implement',
      translation: 'implementar cambios',
      partOfSpeech: 'verb',
      level: 'B2',
      week: 2,
      topic: 'negocios-y-liderazgo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_facilitate_052',
      word: 'facilitate',
      translation: 'facilitar procesos',
      partOfSpeech: 'verb',
      level: 'B2',
      week: 2,
      topic: 'negocios-y-liderazgo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_streamline_053',
      word: 'streamline',
      translation: 'agilizar / simplificar',
      partOfSpeech: 'verb',
      level: 'B2',
      week: 2,
      topic: 'negocios-y-liderazgo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_oversee_054',
      word: 'oversee',
      translation: 'supervisar / vigilar la gestión',
      partOfSpeech: 'verb',
      level: 'B2',
      week: 2,
      topic: 'negocios-y-liderazgo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_empower_055',
      word: 'empower',
      translation: 'empoderar / dar autonomía',
      partOfSpeech: 'verb',
      level: 'B2',
      week: 2,
      topic: 'negocios-y-liderazgo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_strategic_056',
      word: 'strategic',
      translation: 'estratégico',
      partOfSpeech: 'adjective',
      level: 'B2',
      week: 2,
      topic: 'negocios-y-liderazgo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_competitive_057',
      word: 'competitive',
      translation: 'competitivo',
      partOfSpeech: 'adjective',
      level: 'B2',
      week: 2,
      topic: 'negocios-y-liderazgo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_profitable_058',
      word: 'profitable',
      translation: 'rentable / lucrativo',
      partOfSpeech: 'adjective',
      level: 'B2',
      week: 2,
      topic: 'negocios-y-liderazgo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_visionary_059',
      word: 'visionary',
      translation: 'visionario',
      partOfSpeech: 'adjective',
      level: 'B2',
      week: 2,
      topic: 'negocios-y-liderazgo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_pragmatic_060',
      word: 'pragmatic',
      translation: 'pragmático / práctico',
      partOfSpeech: 'adjective',
      level: 'B2',
      week: 2,
      topic: 'negocios-y-liderazgo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
  ],
}
