import type { ContentBlock } from '../types'

/**
 * B2 Level Content — Week 5
 * Topic: B2 · Semana 5 – Liderazgo, estrategia y conceptos académicos
 * Curated from institutional curriculum (Zero AI)
 */
export const week05: ContentBlock = {
  level: "B2",
  week: 5,
  topic: "B2 · Semana 5 – Liderazgo, estrategia y conceptos académicos",
  vocabulary: [
    {
      "id": "voc_b2_abstract_073",
      word: "abstract",
      translation: "abstracto / teórico",
      partOfSpeech: 'adjective',
      level: "B2",
      week: 5,
      topic: "liderazgo-y-estrategia-empresarial",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈæbˌstrækt/',
      example: 'The concept is too abstract for beginners.',
      exampleTranslation: 'El concepto es demasiado abstracto para principiantes.',
      status: 'approved',
    },
    {
      "id": "voc_b2_inherent_074",
      word: "inherent",
      translation: "inherente / intrínseco",
      partOfSpeech: 'adjective',
      level: "B2",
      week: 5,
      topic: "liderazgo-y-estrategia-empresarial",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ɪnˈhɪrənt/',
      example: 'There is an inherent risk in this strategy.',
      exampleTranslation: 'Hay un riesgo inherente en esta estrategia.',
      status: 'approved',
    },
    {
      "id": "voc_b2_scrutinise_075",
      word: "scrutinise",
      translation: "examinar detalladamente / escudriñar",
      partOfSpeech: 'verb',
      level: "B2",
      week: 5,
      topic: "liderazgo-y-estrategia-empresarial",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈskrutəˌnaɪz/',
      example: 'Investors will scrutinise the company\'s financial reports.',
      exampleTranslation: 'Los inversores escudriñarán los informes financieros de la empresa.',
      status: 'approved',
    },
    {
      "id": "voc_b2_unprecedented_076",
      word: "unprecedented",
      translation: "sin precedentes",
      partOfSpeech: 'adjective',
      level: "B2",
      week: 5,
      topic: "liderazgo-y-estrategia-empresarial",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ʌnˈprɛsəˌdɛntɪd/',
      example: 'The company achieved unprecedented growth this year.',
      exampleTranslation: 'La empresa logró un crecimiento sin precedentes este año.',
      status: 'approved',
    },
    {
      "id": "voc_b2_ethical_077",
      word: "ethical",
      translation: "ético / moral",
      partOfSpeech: 'adjective',
      level: "B2",
      week: 5,
      topic: "liderazgo-y-estrategia-empresarial",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈɛθɪkəl/',
      example: 'The board discussed the ethical implications.',
      exampleTranslation: 'La junta discutió las implicaciones éticas.',
      status: 'approved',
    },
    {
      "id": "voc_b2_leadership_078",
      word: "leadership",
      translation: "liderazgo / dirección",
      partOfSpeech: 'noun',
      level: "B2",
      week: 5,
      topic: "liderazgo-y-estrategia-empresarial",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈlidərˌʃɪp/',
      example: 'Strong leadership guided the company through the crisis.',
      exampleTranslation: 'Un liderazgo fuerte guió a la empresa durante la crisis.',
      status: 'approved',
    },
    {
      "id": "voc_b2_strategy_079",
      word: "strategy",
      translation: "estrategia",
      partOfSpeech: 'noun',
      level: "B2",
      week: 5,
      topic: "liderazgo-y-estrategia-empresarial",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈstrætədʒi/',
      example: 'Their marketing strategy was very effective.',
      exampleTranslation: 'Su estrategia de marketing fue muy efectiva.',
      status: 'approved',
    },
    {
      "id": "voc_b2_merger_080",
      word: "merger",
      translation: "fusión empresarial",
      partOfSpeech: 'noun',
      level: "B2",
      week: 5,
      topic: "liderazgo-y-estrategia-empresarial",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈmɜrdʒər/',
      example: 'The merger created the largest company in the sector.',
      exampleTranslation: 'La fusión creó la empresa más grande del sector.',
      status: 'approved',
    },
    {
      "id": "voc_b2_acquisition_081",
      word: "acquisition",
      translation: "adquisición empresarial",
      partOfSpeech: 'noun',
      level: "B2",
      week: 5,
      topic: "liderazgo-y-estrategia-empresarial",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˌækwəˈzɪʃən/',
      example: 'The acquisition doubled the company\'s size.',
      exampleTranslation: 'La adquisición duplicó el tamaño de la empresa.',
      status: 'approved',
    },
    {
      "id": "voc_b2_accountability_082",
      word: "accountability",
      translation: "rendición de cuentas / responsabilidad",
      partOfSpeech: 'noun',
      level: "B2",
      week: 5,
      topic: "liderazgo-y-estrategia-empresarial",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/əˌkaʊntəˈbɪləti/',
      example: 'Leaders must show accountability for their decisions.',
      exampleTranslation: 'Los líderes deben mostrar responsabilidad por sus decisiones.',
      status: 'approved',
    },
    {
      "id": "voc_b2_transparency_083",
      word: "transparency",
      translation: "transparencia",
      partOfSpeech: 'noun',
      level: "B2",
      week: 5,
      topic: "liderazgo-y-estrategia-empresarial",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/trænsˈpɛrənsi/',
      example: 'The company promised more transparency with investors.',
      exampleTranslation: 'La empresa prometió más transparencia con los inversores.',
      status: 'approved',
    },
    {
      "id": "voc_b2_compliance_084",
      word: "compliance",
      translation: "cumplimiento normativo",
      partOfSpeech: 'noun',
      level: "B2",
      week: 5,
      topic: "liderazgo-y-estrategia-empresarial",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/kəmˈplaɪəns/',
      example: 'The department ensures compliance with regulations.',
      exampleTranslation: 'El departamento asegura el cumplimiento de las regulaciones.',
      status: 'approved',
    }
  ]
}
