import type { ContentBlock } from '../types'

/**
 * B2 Level Content — Week 4
 * Topic: B2 · Semana 4 – Conectores formales de escritura académica
 * Curated from institutional curriculum (Zero AI)
 */
export const week04: ContentBlock = {
  level: "B2",
  week: 4,
  topic: "B2 · Semana 4 – Conectores formales de escritura académica",
  vocabulary: [
    {
      "id": "voc_b2_notwithstanding_058",
      word: "notwithstanding",
      translation: "no obstante",
      partOfSpeech: 'adverb',
      level: "B2",
      week: 4,
      topic: "formal_connectors",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˌnɑtwɪθˈstændɪŋ/',
      example: 'Notwithstanding the risks, they proceeded with the plan.',
      exampleTranslation: 'No obstante los riesgos, procedieron con el plan.',
      status: 'approved',
    },
    {
      "id": "voc_b2_albeit_059",
      word: "albeit",
      translation: "aunque/si bien",
      partOfSpeech: 'conjunction',
      level: "B2",
      week: 4,
      topic: "formal_connectors",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ɔlˈbiɪt/',
      example: 'The project succeeded, albeit with some delays.',
      exampleTranslation: 'El proyecto tuvo éxito, aunque con algunos retrasos.',
      status: 'approved',
    },
    {
      "id": "voc_b2_thereby_060",
      word: "thereby",
      translation: "de ese modo",
      partOfSpeech: 'conjunction',
      level: "B2",
      week: 4,
      topic: "formal_connectors",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ðɛrˈbaɪ/',
      example: 'They cut costs, thereby increasing profits.',
      exampleTranslation: 'Redujeron costos, de ese modo aumentando las ganancias.',
      status: 'approved',
    },
    {
      "id": "voc_b2_hitherto_061",
      word: "hitherto",
      translation: "hasta ahora",
      partOfSpeech: 'conjunction',
      level: "B2",
      week: 4,
      topic: "formal_connectors",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈhɪðərˌtu/',
      example: 'Hitherto, no one had studied this phenomenon.',
      exampleTranslation: 'Hasta ahora, nadie había estudiado este fenómeno.',
      status: 'approved',
    },
    {
      "id": "voc_b2_henceforth_062",
      word: "henceforth",
      translation: "de aquí en adelante",
      partOfSpeech: 'conjunction',
      level: "B2",
      week: 4,
      topic: "formal_connectors",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˌhɛnsˈfɔrθ/',
      example: 'Henceforth, all reports must be submitted digitally.',
      exampleTranslation: 'De aquí en adelante, todos los informes deben enviarse digitalmente.',
      status: 'approved',
    },
    {
      "id": "voc_b2_insofar-as_063",
      word: "insofar as",
      translation: "en la medida en que",
      partOfSpeech: 'conjunction',
      level: "B2",
      week: 4,
      topic: "formal_connectors",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˌɪnsoʊˈfɑr æz/',
      example: 'The plan is good insofar as it saves money.',
      exampleTranslation: 'El plan es bueno en la medida en que ahorra dinero.',
      status: 'approved',
    },
    {
      "id": "voc_b2_to-the-extent-that_064",
      word: "to the extent that",
      translation: "en la medida en que",
      partOfSpeech: 'conjunction',
      level: "B2",
      week: 4,
      topic: "formal_connectors",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/tu ði ɪkˈstɛnt ðæt/',
      example: 'The policy failed to the extent that it was ignored.',
      exampleTranslation: 'La política fracasó en la medida en que fue ignorada.',
      status: 'approved',
    },
    {
      "id": "voc_b2_in-light-of_065",
      word: "in light of",
      translation: "a la luz de",
      partOfSpeech: 'conjunction',
      level: "B2",
      week: 4,
      topic: "formal_connectors",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ɪn laɪt əv/',
      example: 'In light of recent events, we changed our plans.',
      exampleTranslation: 'A la luz de los eventos recientes, cambiamos nuestros planes.',
      status: 'approved',
    },
    {
      "id": "voc_b2_with-regard-to_066",
      word: "with regard to",
      translation: "con respecto a",
      partOfSpeech: 'conjunction',
      level: "B2",
      week: 4,
      topic: "formal_connectors",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/wɪð rɪˈgɑrd tu/',
      example: 'With regard to the budget, we need more details.',
      exampleTranslation: 'Con respecto al presupuesto, necesitamos más detalles.',
      status: 'approved',
    },
    {
      "id": "voc_b2_in-relation-to_067",
      word: "in relation to",
      translation: "en relación con",
      partOfSpeech: 'conjunction',
      level: "B2",
      week: 4,
      topic: "formal_connectors",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ɪn rɪˈleɪʃən tu/',
      example: 'Sales grew in relation to last year.',
      exampleTranslation: 'Las ventas crecieron en relación con el año pasado.',
      status: 'approved',
    },
    {
      "id": "voc_b2_by-virtue-of_068",
      word: "by virtue of",
      translation: "en virtud de",
      partOfSpeech: 'conjunction',
      level: "B2",
      week: 4,
      topic: "formal_connectors",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/baɪ ˈvɜrtʃu əv/',
      example: 'She got the job by virtue of her experience.',
      exampleTranslation: 'Ella obtuvo el trabajo en virtud de su experiencia.',
      status: 'approved',
    },
    {
      "id": "voc_b2_for-the-sake-of_069",
      word: "for the sake of",
      translation: "por el bien de",
      partOfSpeech: 'conjunction',
      level: "B2",
      week: 4,
      topic: "formal_connectors",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/fɔr ðə seɪk əv/',
      example: 'Let\'s simplify this for the sake of clarity.',
      exampleTranslation: 'Simplifiquemos esto por el bien de la claridad.',
      status: 'approved',
    },
    {
      "id": "voc_b2_as-a-consequence-of_070",
      word: "as a consequence of",
      translation: "como consecuencia de",
      partOfSpeech: 'conjunction',
      level: "B2",
      week: 4,
      topic: "formal_connectors",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/æz ə ˈkɑnsəˌkwɛns əv/',
      example: 'Prices rose as a consequence of the shortage.',
      exampleTranslation: 'Los precios subieron como consecuencia de la escasez.',
      status: 'approved',
    },
    {
      "id": "voc_b2_conversely_071",
      word: "conversely",
      translation: "por el contrario",
      partOfSpeech: 'conjunction',
      level: "B2",
      week: 4,
      topic: "formal_connectors",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/kənˈvɜrsli/',
      example: 'Conversely, smaller companies adapted more quickly.',
      exampleTranslation: 'Por el contrario, las empresas más pequeñas se adaptaron más rápido.',
      status: 'approved',
    },
    {
      "id": "voc_b2_notably_072",
      word: "notably",
      translation: "notablemente",
      partOfSpeech: 'adverb',
      level: "B2",
      week: 4,
      topic: "formal_connectors",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈnoʊtəbli/',
      example: 'Several sectors improved, most notably technology.',
      exampleTranslation: 'Varios sectores mejoraron, notablemente el tecnológico.',
      status: 'approved',
    }
  ]
}
