import type { ContentBlock } from '../types'

/**
 * B2 Level Content — Week 2
 * Topic: B2 · Semana 2 – Ideas, ideología y sociedad
 * Curated from institutional curriculum (Zero AI)
 */
export const week02: ContentBlock = {
  level: "B2",
  week: 2,
  topic: "B2 · Semana 2 – Ideas, ideología y sociedad",
  vocabulary: [
    {
      "id": "voc_b2_ideology_019",
      word: "ideology",
      translation: "ideología",
      partOfSpeech: 'noun',
      level: "B2",
      week: 2,
      topic: "ideas_society",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˌaɪdiˈɑlədʒi/',
      example: 'Their political ideology shapes every decision.',
      exampleTranslation: 'Su ideología política moldea cada decisión.',
      status: 'approved',
    },
    {
      "id": "voc_b2_philosophy_020",
      word: "philosophy",
      translation: "filosofía",
      partOfSpeech: 'noun',
      level: "B2",
      week: 2,
      topic: "ideas_society",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/fəˈlɑsəfi/',
      example: 'Her philosophy of life is simple: be kind.',
      exampleTranslation: 'Su filosofía de vida es simple: sé amable.',
      status: 'approved',
    },
    {
      "id": "voc_b2_ethics_021",
      word: "ethics",
      translation: "ética",
      partOfSpeech: 'noun',
      level: "B2",
      week: 2,
      topic: "ideas_society",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈɛθɪks/',
      example: 'The committee reviews the ethics of each study.',
      exampleTranslation: 'El comité revisa la ética de cada estudio.',
      status: 'approved',
    },
    {
      "id": "voc_b2_morality_022",
      word: "morality",
      translation: "moralidad",
      partOfSpeech: 'noun',
      level: "B2",
      week: 2,
      topic: "ideas_society",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/mɔˈræləti/',
      example: 'The film raises questions about morality and choice.',
      exampleTranslation: 'La película plantea preguntas sobre la moralidad y la elección.',
      status: 'approved',
    },
    {
      "id": "voc_b2_autonomy_023",
      word: "autonomy",
      translation: "autonomía",
      partOfSpeech: 'noun',
      level: "B2",
      week: 2,
      topic: "ideas_society",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ɔˈtɑnəmi/',
      example: 'Employees value autonomy in their work.',
      exampleTranslation: 'Los empleados valoran la autonomía en su trabajo.',
      status: 'approved',
    },
    {
      "id": "voc_b2_sovereignty_024",
      word: "sovereignty",
      translation: "soberanía",
      partOfSpeech: 'noun',
      level: "B2",
      week: 2,
      topic: "ideas_society",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈsɑvrənti/',
      example: 'The nation defended its sovereignty.',
      exampleTranslation: 'La nación defendió su soberanía.',
      status: 'approved',
    },
    {
      "id": "voc_b2_legislation_025",
      word: "legislation",
      translation: "legislación",
      partOfSpeech: 'noun',
      level: "B2",
      week: 2,
      topic: "ideas_society",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˌlɛdʒəsˈleɪʃən/',
      example: 'New legislation will regulate the industry.',
      exampleTranslation: 'Una nueva legislación regulará la industria.',
      status: 'approved',
    },
    {
      "id": "voc_b2_jurisdiction_026",
      word: "jurisdiction",
      translation: "jurisdicción",
      partOfSpeech: 'noun',
      level: "B2",
      week: 2,
      topic: "ideas_society",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˌdʒʊrɪsˈdɪkʃən/',
      example: 'This case falls under federal jurisdiction.',
      exampleTranslation: 'Este caso cae bajo jurisdicción federal.',
      status: 'approved',
    },
    {
      "id": "voc_b2_advocacy_027",
      word: "advocacy",
      translation: "apoyo/defensa de una causa",
      partOfSpeech: 'noun',
      level: "B2",
      week: 2,
      topic: "ideas_society",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈædvəkəsi/',
      example: 'She works in advocacy for children\'s rights.',
      exampleTranslation: 'Ella trabaja en la defensa de los derechos de los niños.',
      status: 'approved',
    },
    {
      "id": "voc_b2_activism_028",
      word: "activism",
      translation: "activismo",
      partOfSpeech: 'noun',
      level: "B2",
      week: 2,
      topic: "ideas_society",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈæktɪˌvɪzəm/',
      example: 'His activism inspired an entire generation.',
      exampleTranslation: 'Su activismo inspiró a toda una generación.',
      status: 'approved',
    },
    {
      "id": "voc_b2_discrimination_029",
      word: "discrimination",
      translation: "discriminación",
      partOfSpeech: 'noun',
      level: "B2",
      week: 2,
      topic: "ideas_society",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/dɪˌskrɪməˈneɪʃən/',
      example: 'The law protects against workplace discrimination.',
      exampleTranslation: 'La ley protege contra la discriminación laboral.',
      status: 'approved',
    },
    {
      "id": "voc_b2_prejudice_030",
      word: "prejudice",
      translation: "prejuicio",
      partOfSpeech: 'noun',
      level: "B2",
      week: 2,
      topic: "ideas_society",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈprɛdʒədɪs/',
      example: 'The program aims to reduce prejudice.',
      exampleTranslation: 'El programa busca reducir el prejuicio.',
      status: 'approved',
    },
    {
      "id": "voc_b2_stereotype_031",
      word: "stereotype",
      translation: "estereotipo",
      partOfSpeech: 'noun',
      level: "B2",
      week: 2,
      topic: "ideas_society",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈstɛriəˌtaɪp/',
      example: 'The movie challenges a common stereotype.',
      exampleTranslation: 'La película desafía un estereotipo común.',
      status: 'approved',
    },
    {
      "id": "voc_b2_stigma_032",
      word: "stigma",
      translation: "estigma",
      partOfSpeech: 'noun',
      level: "B2",
      week: 2,
      topic: "ideas_society",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈstɪgmə/',
      example: 'There is still stigma around mental illness.',
      exampleTranslation: 'Todavía hay estigma alrededor de la enfermedad mental.',
      status: 'approved',
    },
    {
      "id": "voc_b2_marginalization_033",
      word: "marginalization",
      translation: "marginación",
      partOfSpeech: 'noun',
      level: "B2",
      week: 2,
      topic: "ideas_society",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˌmɑrdʒənələˈzeɪʃən/',
      example: 'The report addresses the marginalization of rural communities.',
      exampleTranslation: 'El informe aborda la marginación de las comunidades rurales.',
      status: 'approved',
    },
    {
      "id": "voc_b2_inequality_034",
      word: "inequality",
      translation: "desigualdad",
      partOfSpeech: 'noun',
      level: "B2",
      week: 2,
      topic: "ideas_society",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˌɪnɪˈkwɑləti/',
      example: 'Income inequality has increased in recent years.',
      exampleTranslation: 'La desigualdad de ingresos ha aumentado en los últimos años.',
      status: 'approved',
    },
    {
      "id": "voc_b2_disparity_035",
      word: "disparity",
      translation: "disparidad",
      partOfSpeech: 'noun',
      level: "B2",
      week: 2,
      topic: "ideas_society",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/dɪˈspɛrəti/',
      example: 'There is a wide disparity between the two regions.',
      exampleTranslation: 'Hay una gran disparidad entre las dos regiones.',
      status: 'approved',
    },
    {
      "id": "voc_b2_privilege-noun_036",
      word: "privilege (noun)",
      translation: "privilegio",
      partOfSpeech: 'noun',
      level: "B2",
      week: 2,
      topic: "ideas_society",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈprɪvəlɪdʒ/',
      example: 'It\'s important to recognize your own privilege.',
      exampleTranslation: 'Es importante reconocer tu propio privilegio.',
      status: 'approved',
    },
    {
      "id": "voc_b2_empowerment_037",
      word: "empowerment",
      translation: "empoderamiento",
      partOfSpeech: 'noun',
      level: "B2",
      week: 2,
      topic: "ideas_society",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ɪmˈpaʊərmənt/',
      example: 'The workshop focuses on women\'s empowerment.',
      exampleTranslation: 'El taller se enfoca en el empoderamiento de las mujeres.',
      status: 'approved',
    },
    {
      "id": "voc_b2_exploitation_038",
      word: "exploitation",
      translation: "explotación",
      partOfSpeech: 'noun',
      level: "B2",
      week: 2,
      topic: "ideas_society",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˌɛksplɔɪˈteɪʃən/',
      example: 'The report exposed the exploitation of workers.',
      exampleTranslation: 'El informe expuso la explotación de los trabajadores.',
      status: 'approved',
    },
    {
      "id": "voc_b2_oppression_039",
      word: "oppression",
      translation: "opresión",
      partOfSpeech: 'noun',
      level: "B2",
      week: 2,
      topic: "ideas_society",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/əˈprɛʃən/',
      example: 'The book describes decades of oppression.',
      exampleTranslation: 'El libro describe décadas de opresión.',
      status: 'approved',
    }
  ]
}
