import type { ContentBlock } from '../types'

/**
 * B2 Level Content — Week 3
 * Topic: B2 · Semana 3 – Cambio, tecnología y procesos globales
 * Curated from institutional curriculum (Zero AI)
 */
export const week03: ContentBlock = {
  level: "B2",
  week: 3,
  topic: "B2 · Semana 3 – Cambio, tecnología y procesos globales",
  vocabulary: [
    {
      "id": "voc_b2_globalization_040",
      word: "globalization",
      translation: "globalización",
      partOfSpeech: 'noun',
      level: "B2",
      week: 3,
      topic: "change_technology",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈgloʊbələˈzeɪʃən/',
      example: 'Globalization has changed how businesses operate.',
      exampleTranslation: 'La globalización ha cambiado cómo operan las empresas.',
      status: 'approved',
    },
    {
      "id": "voc_b2_urbanization_041",
      word: "urbanization",
      translation: "urbanización",
      partOfSpeech: 'noun',
      level: "B2",
      week: 3,
      topic: "change_technology",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈɜrbənəˈzeɪʃən/',
      example: 'Rapid urbanization put pressure on housing.',
      exampleTranslation: 'La urbanización acelerada presionó la vivienda.',
      status: 'approved',
    },
    {
      "id": "voc_b2_industrialization_042",
      word: "industrialization",
      translation: "industrialización",
      partOfSpeech: 'noun',
      level: "B2",
      week: 3,
      topic: "change_technology",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ɪnˌdʌstriələˈzeɪʃən/',
      example: 'Industrialization transformed the country\'s economy.',
      exampleTranslation: 'La industrialización transformó la economía del país.',
      status: 'approved',
    },
    {
      "id": "voc_b2_digitalization_043",
      word: "digitalization",
      translation: "digitalización",
      partOfSpeech: 'noun',
      level: "B2",
      week: 3,
      topic: "change_technology",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈdɪdʒɪtələˈzeɪʃən/',
      example: 'Digitalization improved efficiency across departments.',
      exampleTranslation: 'La digitalización mejoró la eficiencia en todos los departamentos.',
      status: 'approved',
    },
    {
      "id": "voc_b2_automation_044",
      word: "automation",
      translation: "automatización",
      partOfSpeech: 'noun',
      level: "B2",
      week: 3,
      topic: "change_technology",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈɔtəˈmeɪʃən/',
      example: 'Automation reduced production costs.',
      exampleTranslation: 'La automatización redujo los costos de producción.',
      status: 'approved',
    },
    {
      "id": "voc_b2_disruption_045",
      word: "disruption",
      translation: "disrupción",
      partOfSpeech: 'noun',
      level: "B2",
      week: 3,
      topic: "change_technology",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/dɪsˈrʌpʃən/',
      example: 'The new app caused massive disruption in the market.',
      exampleTranslation: 'La nueva aplicación causó una gran disrupción en el mercado.',
      status: 'approved',
    },
    {
      "id": "voc_b2_innovation_046",
      word: "innovation",
      translation: "innovación",
      partOfSpeech: 'noun',
      level: "B2",
      week: 3,
      topic: "change_technology",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈɪnəˈveɪʃən/',
      example: 'The company is known for its innovation.',
      exampleTranslation: 'La empresa es conocida por su innovación.',
      status: 'approved',
    },
    {
      "id": "voc_b2_obsolete_047",
      word: "obsolete",
      translation: "obsoleto",
      partOfSpeech: 'noun',
      level: "B2",
      week: 3,
      topic: "change_technology",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈɑbsəˌlit/',
      example: 'This technology quickly became obsolete.',
      exampleTranslation: 'Esta tecnología rápidamente se volvió obsoleta.',
      status: 'approved',
    },
    {
      "id": "voc_b2_paradigm_048",
      word: "paradigm",
      translation: "paradigma",
      partOfSpeech: 'noun',
      level: "B2",
      week: 3,
      topic: "change_technology",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈpɛrəˌdaɪm/',
      example: 'This discovery shifted the scientific paradigm.',
      exampleTranslation: 'Este descubrimiento cambió el paradigma científico.',
      status: 'approved',
    },
    {
      "id": "voc_b2_hypothesis_049",
      word: "hypothesis",
      translation: "hipótesis",
      partOfSpeech: 'noun',
      level: "B2",
      week: 3,
      topic: "change_technology",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/haɪˈpɑθəsɪs/',
      example: 'The researchers tested their hypothesis carefully.',
      exampleTranslation: 'Los investigadores probaron su hipótesis con cuidado.',
      status: 'approved',
    },
    {
      "id": "voc_b2_methodology_050",
      word: "methodology",
      translation: "metodología",
      partOfSpeech: 'noun',
      level: "B2",
      week: 3,
      topic: "change_technology",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈmɛθəˈdɑlədʒi/',
      example: 'The study uses a clear methodology.',
      exampleTranslation: 'El estudio usa una metodología clara.',
      status: 'approved',
    },
    {
      "id": "voc_b2_correlation_051",
      word: "correlation",
      translation: "correlación",
      partOfSpeech: 'noun',
      level: "B2",
      week: 3,
      topic: "change_technology",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈkɔrəˈleɪʃən/',
      example: 'There is a strong correlation between the two variables.',
      exampleTranslation: 'Hay una fuerte correlación entre las dos variables.',
      status: 'approved',
    },
    {
      "id": "voc_b2_causation_052",
      word: "causation",
      translation: "causalidad",
      partOfSpeech: 'noun',
      level: "B2",
      week: 3,
      topic: "change_technology",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/kɔˈzeɪʃən/',
      example: 'Correlation doesn\'t always imply causation.',
      exampleTranslation: 'La correlación no siempre implica causalidad.',
      status: 'approved',
    },
    {
      "id": "voc_b2_variable-noun_053",
      word: "variable (noun)",
      translation: "variable",
      partOfSpeech: 'noun',
      level: "B2",
      week: 3,
      topic: "change_technology",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈvɛriəbəl/',
      example: 'Age is an important variable in this study.',
      exampleTranslation: 'La edad es una variable importante en este estudio.',
      status: 'approved',
    },
    {
      "id": "voc_b2_empirical_054",
      word: "empirical",
      translation: "empírico",
      partOfSpeech: 'adjective',
      level: "B2",
      week: 3,
      topic: "change_technology",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ɛmˈpɪrɪkəl/',
      example: 'The theory is based on empirical evidence.',
      exampleTranslation: 'La teoría se basa en evidencia empírica.',
      status: 'approved',
    },
    {
      "id": "voc_b2_qualitative_055",
      word: "qualitative",
      translation: "cualitativo",
      partOfSpeech: 'adjective',
      level: "B2",
      week: 3,
      topic: "change_technology",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈkwɑləˌteɪtɪv/',
      example: 'We conducted qualitative interviews with users.',
      exampleTranslation: 'Realizamos entrevistas cualitativas con usuarios.',
      status: 'approved',
    },
    {
      "id": "voc_b2_quantitative_056",
      word: "quantitative",
      translation: "cuantitativo",
      partOfSpeech: 'adjective',
      level: "B2",
      week: 3,
      topic: "change_technology",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈkwɑntəˌteɪtɪv/',
      example: 'The report includes quantitative data.',
      exampleTranslation: 'El informe incluye datos cuantitativos.',
      status: 'approved',
    },
    {
      "id": "voc_b2_synthesis_057",
      word: "synthesis",
      translation: "síntesis",
      partOfSpeech: 'noun',
      level: "B2",
      week: 3,
      topic: "change_technology",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈsɪnθəsɪs/',
      example: 'The essay is a synthesis of several theories.',
      exampleTranslation: 'El ensayo es una síntesis de varias teorías.',
      status: 'approved',
    }
  ]
}
