import type { ContentBlock } from '../types'

/**
 * B2 Level Content — Week 4
 * Topic: Análisis social, medios y pensamiento crítico
 * Curated from institutional curriculum (Zero AI)
 */
export const week04: ContentBlock = {
  level: 'B2',
  week: 4,
  topic: 'Análisis social, medios y pensamiento crítico',
  vocabulary: [
    {
      id: 'voc_b2_journalism_087',
      word: 'journalism',
      translation: 'periodismo',
      partOfSpeech: 'noun',
      level: 'B2',
      week: 4,
      topic: 'analisis-social-y-medios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_editorial_088',
      word: 'editorial',
      translation: 'artículo editorial / de opinión institucional',
      partOfSpeech: 'noun',
      level: 'B2',
      week: 4,
      topic: 'analisis-social-y-medios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_censorship_089',
      word: 'censorship',
      translation: 'censura informativa',
      partOfSpeech: 'noun',
      level: 'B2',
      week: 4,
      topic: 'analisis-social-y-medios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_propaganda_090',
      word: 'propaganda',
      translation: 'propaganda / manipulación de masas',
      partOfSpeech: 'noun',
      level: 'B2',
      week: 4,
      topic: 'analisis-social-y-medios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_misinformation_091',
      word: 'misinformation',
      translation: 'desinformación / noticias falsas',
      partOfSpeech: 'noun',
      level: 'B2',
      week: 4,
      topic: 'analisis-social-y-medios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_bias_092',
      word: 'bias',
      translation: 'sesgo / parcialidad',
      partOfSpeech: 'noun',
      level: 'B2',
      week: 4,
      topic: 'analisis-social-y-medios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_impartial_093',
      word: 'impartial',
      translation: 'imparcial / ecuánime',
      partOfSpeech: 'adjective',
      level: 'B2',
      week: 4,
      topic: 'analisis-social-y-medios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_credibility_094',
      word: 'credibility',
      translation: 'credibilidad / solvencia',
      partOfSpeech: 'noun',
      level: 'B2',
      week: 4,
      topic: 'analisis-social-y-medios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_freedom-of-speech_095',
      word: 'freedom of speech',
      translation: 'libertad de expresión',
      partOfSpeech: 'noun',
      level: 'B2',
      week: 4,
      topic: 'analisis-social-y-medios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_demographic_096',
      word: 'demographic',
      translation: 'demográfico / sector poblacional',
      partOfSpeech: 'noun',
      level: 'B2',
      week: 4,
      topic: 'analisis-social-y-medios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_inequality_097',
      word: 'inequality',
      translation: 'desigualdad socioeconómica',
      partOfSpeech: 'noun',
      level: 'B2',
      week: 4,
      topic: 'analisis-social-y-medios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_integration_098',
      word: 'integration',
      translation: 'integración social',
      partOfSpeech: 'noun',
      level: 'B2',
      week: 4,
      topic: 'analisis-social-y-medios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_polarization_099',
      word: 'polarization',
      translation: 'polarización de opiniones',
      partOfSpeech: 'noun',
      level: 'B2',
      week: 4,
      topic: 'analisis-social-y-medios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_discourse_100',
      word: 'discourse',
      translation: 'discurso / debate público',
      partOfSpeech: 'noun',
      level: 'B2',
      week: 4,
      topic: 'analisis-social-y-medios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_influence_101',
      word: 'influence',
      translation: 'influencia / repercusión',
      partOfSpeech: 'noun',
      level: 'B2',
      week: 4,
      topic: 'analisis-social-y-medios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_manipulate_102',
      word: 'manipulate',
      translation: 'manipular información',
      partOfSpeech: 'verb',
      level: 'B2',
      week: 4,
      topic: 'analisis-social-y-medios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_scrutinize_103',
      word: 'scrutinize',
      translation: 'escudriñar / examinar críticamente',
      partOfSpeech: 'verb',
      level: 'B2',
      week: 4,
      topic: 'analisis-social-y-medios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_undermine_104',
      word: 'undermine',
      translation: 'socavar / minar la confianza',
      partOfSpeech: 'verb',
      level: 'B2',
      week: 4,
      topic: 'analisis-social-y-medios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_perpetuate_105',
      word: 'perpetuate',
      translation: 'perpetuar una situación',
      partOfSpeech: 'verb',
      level: 'B2',
      week: 4,
      topic: 'analisis-social-y-medios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_reinforce_106',
      word: 'reinforce',
      translation: 'reforzar argumentos o ideas',
      partOfSpeech: 'verb',
      level: 'B2',
      week: 4,
      topic: 'analisis-social-y-medios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_widespread_107',
      word: 'widespread',
      translation: 'generalizado / de amplia difusión',
      partOfSpeech: 'adjective',
      level: 'B2',
      week: 4,
      topic: 'analisis-social-y-medios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_pervasive_108',
      word: 'pervasive',
      translation: 'omnipresente / penetrante',
      partOfSpeech: 'adjective',
      level: 'B2',
      week: 4,
      topic: 'analisis-social-y-medios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_ethical_109',
      word: 'ethical',
      translation: 'ético / moral',
      partOfSpeech: 'adjective',
      level: 'B2',
      week: 4,
      topic: 'analisis-social-y-medios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_contemporary_110',
      word: 'contemporary',
      translation: 'contemporáneo / actual',
      partOfSpeech: 'adjective',
      level: 'B2',
      week: 4,
      topic: 'analisis-social-y-medios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b2_unprecedented_111',
      word: 'unprecedented',
      translation: 'sin precedentes / insólito',
      partOfSpeech: 'adjective',
      level: 'B2',
      week: 4,
      topic: 'analisis-social-y-medios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
  ],
}
