/**
 * A2 Level Content — Week 12
 * Topic: Mantenimiento del hogar y reparaciones
 * Curated from institutional curriculum (Zero AI)
 */
import type { ContentBlock } from '../types'

export const week12: ContentBlock = {
  level: 'A2',
  week: 12,
  topic: 'Mantenimiento del hogar y reparaciones',
  vocabulary: [
    {
      id: 'voc_a2_repair_555',
      word: 'repair',
      translation: 'reparar',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_leak_556',
      word: 'leak',
      translation: 'fuga',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_clog_557',
      word: 'clog',
      translation: 'atascar/atasco',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_broken-pipe_558',
      word: 'broken pipe',
      translation: 'tubería rota',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_renovate_559',
      word: 'renovate',
      translation: 'renovar',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_remodel_560',
      word: 'remodel',
      translation: 'remodelar',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_diy_561',
      word: 'DIY (do it yourself)',
      translation: 'hazlo tú mismo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_blueprint_562',
      word: 'blueprint',
      translation: 'plano',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_contractor_563',
      word: 'contractor',
      translation: 'contratista',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_handyman_564',
      word: 'handyman',
      translation: 'manitas/reparador',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_maintenance_565',
      word: 'maintenance',
      translation: 'mantenimiento',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_inspection_566',
      word: 'inspection',
      translation: 'inspección',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_electrical-outlet_567',
      word: 'electrical outlet',
      translation: 'tomacorriente',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_circuit-breaker_568',
      word: 'circuit breaker',
      translation: 'interruptor automático',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_fuse_569',
      word: 'fuse',
      translation: 'fusible',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_wiring_570',
      word: 'wiring',
      translation: 'cableado',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_plumbing_571',
      word: 'plumbing',
      translation: 'plomería',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_drain_572',
      word: 'drain',
      translation: 'desagüe',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_faucet-tap_573',
      word: 'faucet / tap',
      translation: 'grifo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_thermostat_574',
      word: 'thermostat',
      translation: 'termostato',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_insulation_575',
      word: 'insulation',
      translation: 'aislamiento',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_ventilation_576',
      word: 'ventilation',
      translation: 'ventilación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_mold_577',
      word: 'mold',
      translation: 'moho',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_pest-control_578',
      word: 'pest control',
      translation: 'control de plagas',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_termite_579',
      word: 'termite',
      translation: 'termita',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_rust_580',
      word: 'rust',
      translation: 'óxido',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_crack_581',
      word: 'crack (wall)',
      translation: 'grieta',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_dent_582',
      word: 'dent',
      translation: 'abolladura',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_scratch_583',
      word: 'scratch',
      translation: 'rayón',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_stain_584',
      word: 'stain',
      translation: 'mancha',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_paint-roller_585',
      word: 'paint roller',
      translation: 'rodillo de pintura',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_sandpaper_586',
      word: 'sandpaper',
      translation: 'papel de lija',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_nail-gun_587',
      word: 'nail gun',
      translation: 'pistola de clavos',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_power-drill_588',
      word: 'power drill',
      translation: 'taladro eléctrico',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_toolbox_589',
      word: 'toolbox',
      translation: 'caja de herramientas',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_measuring-tape_590',
      word: 'measuring tape',
      translation: 'cinta métrica',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_level_591',
      word: 'level (tool)',
      translation: 'nivel (herramienta)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_wrench_592',
      word: 'wrench',
      translation: 'llave inglesa',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_pliers_593',
      word: 'pliers',
      translation: 'alicates',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_safety-goggles_594',
      word: 'safety goggles',
      translation: 'gafas de seguridad',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_estimate_595',
      word: 'estimate (cost)',
      translation: 'presupuesto/estimado',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_quote_596',
      word: 'quote (price)',
      translation: 'cotización',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_appliance-repair_597',
      word: 'appliance repair',
      translation: 'reparación de electrodomésticos',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_gutter_598',
      word: 'gutter',
      translation: 'canaleta',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_chimney_599',
      word: 'chimney',
      translation: 'chimenea',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_foundation_600',
      word: 'foundation (house)',
      translation: 'cimientos',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_structural-damage_601',
      word: 'structural damage',
      translation: 'daño estructural',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_home-inspection_602',
      word: 'home inspection',
      translation: 'inspección de vivienda',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_recyclable_603',
      word: 'recyclable',
      translation: 'reciclable',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_waste-disposal_604',
      word: 'waste disposal',
      translation: 'eliminación de residuos',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
  ] as const,
}
