/**
 * A2 Level Content — Week 11
 * Topic: Cocina y recetas
 * Curated from institutional curriculum (Zero AI)
 */
import type { ContentBlock } from '../types'

export const week11: ContentBlock = {
  level: 'A2',
  week: 11,
  topic: 'Cocina y recetas',
  vocabulary: [
    {
      id: 'voc_a2_recipe_496',
      word: 'recipe',
      translation: 'receta',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈrɛsəpi/',
      example: 'This recipe is very easy.',
      exampleTranslation: 'Esta receta es muy fácil.',
      status: 'approved',
    },
    {
      id: 'voc_a2_ingredient_497',
      word: 'ingredient',
      translation: 'ingrediente',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪnˈgridiənt/',
      example: 'Check if you have all the ingredients.',
      exampleTranslation: 'Revisa si tienes todos los ingredientes.',
      status: 'approved',
    },
    {
      id: 'voc_a2_chop_498',
      word: 'chop',
      translation: 'picar',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tʃɑp/',
      example: 'Chop the onion finely.',
      exampleTranslation: 'Pica la cebolla finamente.',
      status: 'approved',
    },
    {
      id: 'voc_a2_slice_499',
      word: 'slice',
      translation: 'cortar en rodajas',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/slaɪs/',
      example: 'Slice the bread, please.',
      exampleTranslation: 'Corta el pan en rebanadas, por favor.',
      status: 'approved',
    },
    {
      id: 'voc_a2_grate_500',
      word: 'grate',
      translation: 'rallar',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/greɪt/',
      example: 'Grate some cheese on top.',
      exampleTranslation: 'Ralla un poco de queso encima.',
      status: 'approved',
    },
    {
      id: 'voc_a2_peel_501',
      word: 'peel',
      translation: 'pelar',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pil/',
      example: 'Peel the potatoes first.',
      exampleTranslation: 'Pela las papas primero.',
      status: 'approved',
    },
    {
      id: 'voc_a2_whisk_502',
      word: 'whisk',
      translation: 'batir',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/wɪsk/',
      example: 'Whisk the eggs until smooth.',
      exampleTranslation: 'Bate los huevos hasta que queden suaves.',
      status: 'approved',
    },
    {
      id: 'voc_a2_stir_503',
      word: 'stir',
      translation: 'revolver',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/stɜr/',
      example: 'Stir the soup slowly.',
      exampleTranslation: 'Revuelve la sopa lentamente.',
      status: 'approved',
    },
    {
      id: 'voc_a2_boil_504',
      word: 'boil',
      translation: 'hervir',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bɔɪl/',
      example: 'Boil the water first.',
      exampleTranslation: 'Hierve el agua primero.',
      status: 'approved',
    },
    {
      id: 'voc_a2_simmer_505',
      word: 'simmer',
      translation: 'cocinar a fuego lento',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsɪmər/',
      example: 'Let the sauce simmer for ten minutes.',
      exampleTranslation: 'Deja que la salsa se cocine a fuego lento diez minutos.',
      status: 'approved',
    },
    {
      id: 'voc_a2_roast_506',
      word: 'roast',
      translation: 'asar (horno)',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/roʊst/',
      example: 'We roasted the chicken for an hour.',
      exampleTranslation: 'Asamos el pollo durante una hora.',
      status: 'approved',
    },
    {
      id: 'voc_a2_grill_507',
      word: 'grill',
      translation: 'asar a la parrilla',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/grɪl/',
      example: 'We grilled vegetables for dinner.',
      exampleTranslation: 'Asamos verduras a la parrilla para la cena.',
      status: 'approved',
    },
    {
      id: 'voc_a2_bake_508',
      word: 'bake',
      translation: 'hornear',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/beɪk/',
      example: 'I baked a cake for her birthday.',
      exampleTranslation: 'Horneé un pastel para su cumpleaños.',
      status: 'approved',
    },
    {
      id: 'voc_a2_fry_509',
      word: 'fry',
      translation: 'freír',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fraɪ/',
      example: 'Fry the eggs in a little oil.',
      exampleTranslation: 'Fríe los huevos en un poco de aceite.',
      status: 'approved',
    },
    {
      id: 'voc_a2_steam_510',
      word: 'steam',
      translation: 'cocinar al vapor',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/stim/',
      example: 'Steam the vegetables for five minutes.',
      exampleTranslation: 'Cocina las verduras al vapor cinco minutos.',
      status: 'approved',
    },
    {
      id: 'voc_a2_marinate_511',
      word: 'marinate',
      translation: 'marinar',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmɛrəˌneɪt/',
      example: 'Marinate the chicken overnight.',
      exampleTranslation: 'Marina el pollo durante la noche.',
      status: 'approved',
    },
    {
      id: 'voc_a2_garnish_512',
      word: 'garnish',
      translation: 'decorar (plato)',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈgɑrnɪʃ/',
      example: 'Garnish the plate with parsley.',
      exampleTranslation: 'Decora el plato con perejil.',
      status: 'approved',
    },
    {
      id: 'voc_a2_portion_513',
      word: 'portion',
      translation: 'porción',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpɔrʃən/',
      example: 'This is a large portion.',
      exampleTranslation: 'Esta es una porción grande.',
      status: 'approved',
    },
    {
      id: 'voc_a2_serving_514',
      word: 'serving',
      translation: 'porción/ración',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsɜrvɪŋ/',
      example: 'One serving has 300 calories.',
      exampleTranslation: 'Una porción tiene 300 calorías.',
      status: 'approved',
    },
    {
      id: 'voc_a2_leftovers_515',
      word: 'leftovers',
      translation: 'sobras',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈlɛftˌoʊvərz/',
      example: 'We ate the leftovers for lunch.',
      exampleTranslation: 'Comimos las sobras en el almuerzo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_preheat_516',
      word: 'preheat',
      translation: 'precalentar',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpriˌhit/',
      example: 'Preheat the oven to 180 degrees.',
      exampleTranslation: 'Precalienta el horno a 180 grados.',
      status: 'approved',
    },
    {
      id: 'voc_a2_blend_517',
      word: 'blend',
      translation: 'licuar',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/blɛnd/',
      example: 'Blend the fruit with some water.',
      exampleTranslation: 'Licúa la fruta con un poco de agua.',
      status: 'approved',
    },
    {
      id: 'voc_a2_mash_518',
      word: 'mash',
      translation: 'triturar/hacer puré',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/mæʃ/',
      example: 'Mash the potatoes with butter.',
      exampleTranslation: 'Haz puré de las papas con mantequilla.',
      status: 'approved',
    },
    {
      id: 'voc_a2_dice_519',
      word: 'dice',
      translation: 'cortar en cubos',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/daɪs/',
      example: 'Dice the tomatoes small.',
      exampleTranslation: 'Corta los tomates en cubos pequeños.',
      status: 'approved',
    },
    {
      id: 'voc_a2_sprinkle_520',
      word: 'sprinkle',
      translation: 'espolvorear',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsprɪŋkəl/',
      example: 'Sprinkle some sugar on top.',
      exampleTranslation: 'Espolvorea un poco de azúcar encima.',
      status: 'approved',
    },
    {
      id: 'voc_a2_drizzle_521',
      word: 'drizzle',
      translation: 'rociar (líquido)',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdrɪzəl/',
      example: 'Drizzle olive oil over the salad.',
      exampleTranslation: 'Rocía aceite de oliva sobre la ensalada.',
      status: 'approved',
    },
    {
      id: 'voc_a2_sauce_522',
      word: 'sauce',
      translation: 'salsa',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/sɔs/',
      example: 'The pasta has tomato sauce.',
      exampleTranslation: 'La pasta tiene salsa de tomate.',
      status: 'approved',
    },
    {
      id: 'voc_a2_broth-stock_523',
      word: 'broth / stock',
      translation: 'caldo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/brɔθ/',
      example: 'Use chicken broth for this soup.',
      exampleTranslation: 'Usa caldo de pollo para esta sopa.',
      status: 'approved',
    },
    {
      id: 'voc_a2_dough_524',
      word: 'dough',
      translation: 'masa',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/doʊ/',
      example: 'The dough needs to rest.',
      exampleTranslation: 'La masa necesita reposar.',
      status: 'approved',
    },
    {
      id: 'voc_a2_batter_525',
      word: 'batter',
      translation: 'masa líquida',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbætər/',
      example: 'Mix the batter well.',
      exampleTranslation: 'Mezcla bien la masa líquida.',
      status: 'approved',
    },
    {
      id: 'voc_a2_yeast_526',
      word: 'yeast',
      translation: 'levadura',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/jist/',
      example: 'Add yeast to the flour.',
      exampleTranslation: 'Agrega levadura a la harina.',
      status: 'approved',
    },
    {
      id: 'voc_a2_flour_527',
      word: 'flour',
      translation: 'harina',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/flaʊər/',
      example: 'We need two cups of flour.',
      exampleTranslation: 'Necesitamos dos tazas de harina.',
      status: 'approved',
    },
    {
      id: 'voc_a2_baking-powder_528',
      word: 'baking powder',
      translation: 'polvo de hornear',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbeɪkɪŋ ˈpaʊdər/',
      example: 'Don\'t forget the baking powder.',
      exampleTranslation: 'No olvides el polvo de hornear.',
      status: 'approved',
    },
    {
      id: 'voc_a2_vanilla_529',
      word: 'vanilla',
      translation: 'vainilla',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/vəˈnɪlə/',
      example: 'Add a little vanilla to the cake.',
      exampleTranslation: 'Agrega un poco de vainilla al pastel.',
      status: 'approved',
    },
    {
      id: 'voc_a2_cinnamon_530',
      word: 'cinnamon',
      translation: 'canela',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsɪnəmən/',
      example: 'Sprinkle cinnamon on the coffee.',
      exampleTranslation: 'Espolvorea canela sobre el café.',
      status: 'approved',
    },
    {
      id: 'voc_a2_herbs_531',
      word: 'herbs',
      translation: 'hierbas',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɜrbz/',
      example: 'Fresh herbs improve the flavor.',
      exampleTranslation: 'Las hierbas frescas mejoran el sabor.',
      status: 'approved',
    },
    {
      id: 'voc_a2_spices_532',
      word: 'spices',
      translation: 'especias',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈspaɪsɪz/',
      example: 'This dish has many spices.',
      exampleTranslation: 'Este platillo tiene muchas especias.',
      status: 'approved',
    },
    {
      id: 'voc_a2_recipe-book-cookbook_533',
      word: 'recipe book / cookbook',
      translation: 'libro de cocina',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈrɛsəpi bʊk/',
      example: 'She has a huge recipe book.',
      exampleTranslation: 'Ella tiene un enorme libro de cocina.',
      status: 'approved',
    },
    {
      id: 'voc_a2_nutrition-label_534',
      word: 'nutrition label',
      translation: 'etiqueta nutricional',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/nuˈtrɪʃən ˈleɪbəl/',
      example: 'Read the nutrition label first.',
      exampleTranslation: 'Lee la etiqueta nutricional primero.',
      status: 'approved',
    },
    {
      id: 'voc_a2_expiration-date_535',
      word: 'expiration date',
      translation: 'fecha de caducidad',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌɛkspəˈreɪʃən deɪt/',
      example: 'Check the expiration date.',
      exampleTranslation: 'Revisa la fecha de caducidad.',
      status: 'approved',
    },
    {
      id: 'voc_a2_organic_536',
      word: 'organic',
      translation: 'orgánico',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɔrˈgænɪk/',
      example: 'We buy organic vegetables.',
      exampleTranslation: 'Compramos verduras orgánicas.',
      status: 'approved',
    },
    {
      id: 'voc_a2_homemade_537',
      word: 'homemade',
      translation: 'casero',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈhoʊmˈmeɪd/',
      example: 'This bread is homemade.',
      exampleTranslation: 'Este pan es casero.',
      status: 'approved',
    },
    {
      id: 'voc_a2_store-bought_538',
      word: 'store-bought',
      translation: 'comprado en tienda',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/stɔr bɔt/',
      example: 'I prefer homemade over store-bought.',
      exampleTranslation: 'Prefiero lo casero antes que lo comprado en tienda.',
      status: 'approved',
    },
    {
      id: 'voc_a2_vegetarian_539',
      word: 'vegetarian',
      translation: 'vegetariano',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌvɛdʒəˈtɛriən/',
      example: 'My sister is vegetarian.',
      exampleTranslation: 'Mi hermana es vegetariana.',
      status: 'approved',
    },
    {
      id: 'voc_a2_vegan_540',
      word: 'vegan',
      translation: 'vegano',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈvigən/',
      example: 'This restaurant has vegan options.',
      exampleTranslation: 'Este restaurante tiene opciones veganas.',
      status: 'approved',
    },
    {
      id: 'voc_a2_gluten-free_541',
      word: 'gluten-free',
      translation: 'sin gluten',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈglutənˈfri/',
      example: 'This bread is gluten-free.',
      exampleTranslation: 'Este pan es sin gluten.',
      status: 'approved',
    },
    {
      id: 'voc_a2_dairy-free_542',
      word: 'dairy-free',
      translation: 'sin lácteos',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdɛriˈfri/',
      example: 'She drinks dairy-free milk.',
      exampleTranslation: 'Ella bebe leche sin lácteos.',
      status: 'approved',
    },
    {
      id: 'voc_a2_food-processor_543',
      word: 'food processor',
      translation: 'procesador de alimentos',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fud ˈprɑˌsɛsər/',
      example: 'Use the food processor for the sauce.',
      exampleTranslation: 'Usa el procesador de alimentos para la salsa.',
      status: 'approved',
    },
    {
      id: 'voc_a2_blender_544',
      word: 'blender',
      translation: 'licuadora',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈblɛndər/',
      example: 'I use the blender every morning.',
      exampleTranslation: 'Uso la licuadora todas las mañanas.',
      status: 'approved',
    },
    {
      id: 'voc_a2_mixing-bowl_545',
      word: 'mixing bowl',
      translation: 'tazón para mezclar',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmɪksɪŋ boʊl/',
      example: 'Put the flour in the mixing bowl.',
      exampleTranslation: 'Pon la harina en el tazón para mezclar.',
      status: 'approved',
    },
    {
      id: 'voc_a2_cutting-board_546',
      word: 'cutting board',
      translation: 'tabla de cortar',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkʌtɪŋ bɔrd/',
      example: 'Use a clean cutting board.',
      exampleTranslation: 'Usa una tabla de cortar limpia.',
      status: 'approved',
    },
    {
      id: 'voc_a2_measuring-cup_547',
      word: 'measuring cup',
      translation: 'taza medidora',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmɛʒərɪŋ kʌp/',
      example: 'I need the measuring cup for this.',
      exampleTranslation: 'Necesito la taza medidora para esto.',
      status: 'approved',
    },
    {
      id: 'voc_a2_colander_548',
      word: 'colander',
      translation: 'colador',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkɑləndər/',
      example: 'Drain the pasta in a colander.',
      exampleTranslation: 'Escurre la pasta en un colador.',
      status: 'approved',
    },
    {
      id: 'voc_a2_apron_549',
      word: 'apron',
      translation: 'delantal',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈeɪprən/',
      example: 'Put on your apron before cooking.',
      exampleTranslation: 'Ponte el delantal antes de cocinar.',
      status: 'approved',
    },
    {
      id: 'voc_a2_recipe-card_550',
      word: 'recipe card',
      translation: 'tarjeta de receta',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈrɛsəpi kɑrd/',
      example: 'She wrote it on a recipe card.',
      exampleTranslation: 'Ella lo escribió en una tarjeta de receta.',
      status: 'approved',
    },
    {
      id: 'voc_a2_side-dish_551',
      word: 'side dish',
      translation: 'guarnición',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/saɪd dɪʃ/',
      example: 'Rice is a good side dish.',
      exampleTranslation: 'El arroz es una buena guarnición.',
      status: 'approved',
    },
    {
      id: 'voc_a2_main-course_552',
      word: 'main course',
      translation: 'plato principal',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/meɪn kɔrs/',
      example: 'The main course was fish.',
      exampleTranslation: 'El plato principal fue pescado.',
      status: 'approved',
    },
    {
      id: 'voc_a2_appetizer_553',
      word: 'appetizer',
      translation: 'aperitivo',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈæpəˌtaɪzər/',
      example: 'We ordered an appetizer first.',
      exampleTranslation: 'Pedimos un aperitivo primero.',
      status: 'approved',
    },
    {
      id: 'voc_a2_dessert_554',
      word: 'dessert',
      translation: 'postre',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dɪˈzɜrt/',
      example: 'What\'s for dessert?',
      exampleTranslation: '¿Qué hay de postre?',
      status: 'approved',
    },
  ] as const,
}
