/**
 * A2 Level Content — Week 05
 * Topic: Conectores narrativos para contar historias
 * Curated from institutional curriculum (Zero AI)
 */
import type { ContentBlock } from '../types'

export const week05: ContentBlock = {
  level: 'A2',
  week: 5,
  topic: 'Conectores narrativos para contar historias',
  vocabulary: [
    {
      id: 'voc_a2_once-upon-a-time_241',
      word: 'once upon a time',
      translation: 'érase una vez',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/wʌns əˈpɑn ə taɪm/',
      example: 'Once upon a time, there was a small village.',
      exampleTranslation: 'Érase una vez, había un pueblo pequeño.',
      status: 'approved',
    },
    {
      id: 'voc_a2_meanwhile_242',
      word: 'meanwhile',
      translation: 'mientras tanto',
      partOfSpeech: 'adverb',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈminˌwaɪl/',
      example: 'Meanwhile, her brother was cooking dinner.',
      exampleTranslation: 'Mientras tanto, su hermano estaba cocinando la cena.',
      status: 'approved',
    },
    {
      id: 'voc_a2_afterward_243',
      word: 'afterward',
      translation: 'después/luego',
      partOfSpeech: 'adverb',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈæftərwərd/',
      example: 'We had lunch and afterward went for a walk.',
      exampleTranslation: 'Almorzamos y después salimos a caminar.',
      status: 'approved',
    },
    {
      id: 'voc_a2_eventually_244',
      word: 'eventually',
      translation: 'finalmente/con el tiempo',
      partOfSpeech: 'adverb',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪˈvɛntʃuəli/',
      example: 'Eventually, she found a new job.',
      exampleTranslation: 'Finalmente, ella encontró un nuevo trabajo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_in-the-end_245',
      word: 'in the end',
      translation: 'al final',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪn ði ɛnd/',
      example: 'In the end, everything worked out fine.',
      exampleTranslation: 'Al final, todo salió bien.',
      status: 'approved',
    },
    {
      id: 'voc_a2_at-first_246',
      word: 'at first',
      translation: 'al principio',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/æt fɜrst/',
      example: 'At first, I didn\'t understand the lesson.',
      exampleTranslation: 'Al principio, no entendí la lección.',
      status: 'approved',
    },
    {
      id: 'voc_a2_later-on_247',
      word: 'later on',
      translation: 'más adelante',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈleɪtər ɑn/',
      example: 'Later on, we became good friends.',
      exampleTranslation: 'Más adelante, nos hicimos buenos amigos.',
      status: 'approved',
    },
    {
      id: 'voc_a2_as-soon-as_248',
      word: 'as soon as',
      translation: 'tan pronto como',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/æz sun æz/',
      example: 'Call me as soon as you arrive.',
      exampleTranslation: 'Llámame tan pronto como llegues.',
      status: 'approved',
    },
    {
      id: 'voc_a2_by-the-time_249',
      word: 'by the time',
      translation: 'para cuando',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/baɪ ðə taɪm/',
      example: 'By the time we arrived, the show had started.',
      exampleTranslation: 'Para cuando llegamos, el espectáculo ya había empezado.',
      status: 'approved',
    },
    {
      id: 'voc_a2_used-to_250',
      word: 'used to',
      translation: 'solía',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈjuzd tu/',
      example: 'I used to live in another city.',
      exampleTranslation: 'Yo solía vivir en otra ciudad.',
      status: 'approved',
    },
    {
      id: 'voc_a2_previously_251',
      word: 'previously',
      translation: 'previamente',
      partOfSpeech: 'adverb',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpriviəsli/',
      example: 'Previously, she worked as a teacher.',
      exampleTranslation: 'Previamente, ella trabajaba como maestra.',
      status: 'approved',
    },
    {
      id: 'voc_a2_formerly_252',
      word: 'formerly',
      translation: 'anteriormente',
      partOfSpeech: 'adverb',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfɔrmərli/',
      example: 'This building was formerly a school.',
      exampleTranslation: 'Este edificio fue anteriormente una escuela.',
      status: 'approved',
    },
    {
      id: 'voc_a2_ever-since_253',
      word: 'ever since',
      translation: 'desde entonces',
      partOfSpeech: 'adverb',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɛvər sɪns/',
      example: 'Ever since that day, we\'ve been close friends.',
      exampleTranslation: 'Desde ese día, hemos sido amigos cercanos.',
      status: 'approved',
    },
    {
      id: 'voc_a2_from-then-on_254',
      word: 'from then on',
      translation: 'desde ese momento',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/frʌm ðɛn ɑn/',
      example: 'From then on, he studied every night.',
      exampleTranslation: 'Desde ese momento, él estudió todas las noches.',
      status: 'approved',
    },
    {
      id: 'voc_a2_at-that-moment_255',
      word: 'at that moment',
      translation: 'en ese momento',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/æt ðæt ˈmoʊmənt/',
      example: 'At that moment, the phone rang.',
      exampleTranslation: 'En ese momento, sonó el teléfono.',
      status: 'approved',
    },
    {
      id: 'voc_a2_right-after_256',
      word: 'right after',
      translation: 'justo después',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/raɪt ˈæftər/',
      example: 'We left right after the meeting.',
      exampleTranslation: 'Nos fuimos justo después de la reunión.',
      status: 'approved',
    },
    {
      id: 'voc_a2_shortly-after_257',
      word: 'shortly after',
      translation: 'poco después',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈʃɔrtli ˈæftər/',
      example: 'Shortly after, it started to rain.',
      exampleTranslation: 'Poco después, empezó a llover.',
      status: 'approved',
    },
    {
      id: 'voc_a2_in-the-meantime_258',
      word: 'in the meantime',
      translation: 'mientras tanto',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪn ðə ˈminˌtaɪm/',
      example: 'In the meantime, please wait here.',
      exampleTranslation: 'Mientras tanto, por favor espera aquí.',
      status: 'approved',
    },
    {
      id: 'voc_a2_all-of-a-sudden_259',
      word: 'all of a sudden',
      translation: 'de repente',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɔl əv ə ˈsʌdən/',
      example: 'All of a sudden, the lights went out.',
      exampleTranslation: 'De repente, se fueron las luces.',
      status: 'approved',
    },
    {
      id: 'voc_a2_little-by-little_260',
      word: 'little by little',
      translation: 'poco a poco',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈlɪtəl baɪ ˈlɪtəl/',
      example: 'Little by little, she learned to speak English.',
      exampleTranslation: 'Poco a poco, ella aprendió a hablar inglés.',
      status: 'approved',
    },
    {
      id: 'voc_a2_one-day_261',
      word: 'one day',
      translation: 'un día',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/wʌn deɪ/',
      example: 'One day, he decided to change his life.',
      exampleTranslation: 'Un día, él decidió cambiar su vida.',
      status: 'approved',
    },
    {
      id: 'voc_a2_years-ago_262',
      word: 'years ago',
      translation: 'hace años',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/jɪrz əˈgoʊ/',
      example: 'Years ago, this street looked different.',
      exampleTranslation: 'Hace años, esta calle se veía diferente.',
      status: 'approved',
    },
    {
      id: 'voc_a2_back-then_263',
      word: 'back then',
      translation: 'en aquel entonces',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bæk ðɛn/',
      example: 'Back then, we didn\'t have cell phones.',
      exampleTranslation: 'En aquel entonces, no teníamos celulares.',
      status: 'approved',
    },
    {
      id: 'voc_a2_during-that-time_264',
      word: 'during that time',
      translation: 'durante ese tiempo',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdʊrɪŋ ðæt taɪm/',
      example: 'During that time, she lived abroad.',
      exampleTranslation: 'Durante ese tiempo, ella vivió en el extranjero.',
      status: 'approved',
    },
    {
      id: 'voc_a2_at-the-same-time_265',
      word: 'at the same time',
      translation: 'al mismo tiempo',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/æt ðə seɪm taɪm/',
      example: 'At the same time, he was studying and working.',
      exampleTranslation: 'Al mismo tiempo, él estudiaba y trabajaba.',
      status: 'approved',
    },
    {
      id: 'voc_a2_in-those-days_266',
      word: 'in those days',
      translation: 'en aquellos días',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪn ðoʊz deɪz/',
      example: 'In those days, life was simpler.',
      exampleTranslation: 'En aquellos días, la vida era más sencilla.',
      status: 'approved',
    },
    {
      id: 'voc_a2_as-a-result_267',
      word: 'as a result',
      translation: 'como resultado',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/æz ə rɪˈzʌlt/',
      example: 'As a result, sales increased.',
      exampleTranslation: 'Como resultado, las ventas aumentaron.',
      status: 'approved',
    },
    {
      id: 'voc_a2_consequently_268',
      word: 'consequently',
      translation: 'en consecuencia',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkɑnsəˌkwɛntli/',
      example: 'Consequently, the project was delayed.',
      exampleTranslation: 'En consecuencia, el proyecto se retrasó.',
      status: 'approved',
    },
    {
      id: 'voc_a2_thus_269',
      word: 'thus',
      translation: 'así/por lo tanto',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ðʌs/',
      example: 'Thus, we decided to cancel the trip.',
      exampleTranslation: 'Así, decidimos cancelar el viaje.',
      status: 'approved',
    },
    {
      id: 'voc_a2_for-this-reason_270',
      word: 'for this reason',
      translation: 'por esta razón',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fɔr ðɪs ˈrizən/',
      example: 'For this reason, we changed our plans.',
      exampleTranslation: 'Por esta razón, cambiamos nuestros planes.',
      status: 'approved',
    },
    {
      id: 'voc_a2_due-to_271',
      word: 'due to',
      translation: 'debido a',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/du tu/',
      example: 'The flight was delayed due to weather.',
      exampleTranslation: 'El vuelo se retrasó debido al clima.',
      status: 'approved',
    },
    {
      id: 'voc_a2_because-of_272',
      word: 'because of',
      translation: 'a causa de',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bɪˈkɔz əv/',
      example: 'We stayed home because of the storm.',
      exampleTranslation: 'Nos quedamos en casa a causa de la tormenta.',
      status: 'approved',
    },
    {
      id: 'voc_a2_thats-why_273',
      word: "that's why",
      translation: 'por eso',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ðæts waɪ/',
      example: 'That\'s why I called you.',
      exampleTranslation: 'Por eso te llamé.',
      status: 'approved',
    },
    {
      id: 'voc_a2_in-contrast_274',
      word: 'in contrast',
      translation: 'en contraste',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪn ˈkɑntræst/',
      example: 'In contrast, her sister loves the city.',
      exampleTranslation: 'En contraste, a su hermana le encanta la ciudad.',
      status: 'approved',
    },
    {
      id: 'voc_a2_instead_275',
      word: 'instead',
      translation: 'en cambio',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪnˈstɛd/',
      example: 'Let\'s have tea instead.',
      exampleTranslation: 'Tomemos té en cambio.',
      status: 'approved',
    },
    {
      id: 'voc_a2_nevertheless_276',
      word: 'nevertheless',
      translation: 'sin embargo/no obstante',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌnɛvərðəˈlɛs/',
      example: 'It was raining; nevertheless, we went out.',
      exampleTranslation: 'Estaba lloviendo; sin embargo, salimos.',
      status: 'approved',
    },
    {
      id: 'voc_a2_nonetheless_277',
      word: 'nonetheless',
      translation: 'no obstante',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌnʌnðəˈlɛs/',
      example: 'The task was hard; nonetheless, she finished it.',
      exampleTranslation: 'La tarea fue difícil; no obstante, ella la terminó.',
      status: 'approved',
    },
    {
      id: 'voc_a2_moreover_278',
      word: 'moreover',
      translation: 'además',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/mɔrˈoʊvər/',
      example: 'The hotel is cheap; moreover, it\'s very clean.',
      exampleTranslation: 'El hotel es barato; además, está muy limpio.',
      status: 'approved',
    },
    {
      id: 'voc_a2_furthermore_279',
      word: 'furthermore',
      translation: 'además/asimismo',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfɜrðərˌmɔr/',
      example: 'Furthermore, the staff was very kind.',
      exampleTranslation: 'Además, el personal fue muy amable.',
      status: 'approved',
    },
    {
      id: 'voc_a2_in-addition_280',
      word: 'in addition',
      translation: 'adicionalmente',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪn əˈdɪʃən/',
      example: 'In addition, we offer free delivery.',
      exampleTranslation: 'Adicionalmente, ofrecemos envío gratis.',
      status: 'approved',
    },
    {
      id: 'voc_a2_besides_281',
      word: 'besides',
      translation: 'además',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bɪˈsaɪdz/',
      example: 'Besides, I don\'t have time today.',
      exampleTranslation: 'Además, no tengo tiempo hoy.',
      status: 'approved',
    },
    {
      id: 'voc_a2_apart-from_282',
      word: 'apart from',
      translation: 'aparte de',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈpɑrt frʌm/',
      example: 'Apart from the price, everything was perfect.',
      exampleTranslation: 'Aparte del precio, todo estuvo perfecto.',
      status: 'approved',
    },
    {
      id: 'voc_a2_in-conclusion_283',
      word: 'in conclusion',
      translation: 'en conclusión',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪn kənˈkluʒən/',
      example: 'In conclusion, the plan was a success.',
      exampleTranslation: 'En conclusión, el plan fue un éxito.',
      status: 'approved',
    },
    {
      id: 'voc_a2_to-sum-up_284',
      word: 'to sum up',
      translation: 'en resumen',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tu sʌm ʌp/',
      example: 'To sum up, we need more time.',
      exampleTranslation: 'En resumen, necesitamos más tiempo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_overall_285',
      word: 'overall',
      translation: 'en general',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈoʊvərˌɔl/',
      example: 'Overall, it was a great trip.',
      exampleTranslation: 'En general, fue un gran viaje.',
      status: 'approved',
    },
    {
      id: 'voc_a2_in-general_286',
      word: 'in general',
      translation: 'en general',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪn ˈdʒɛnərəl/',
      example: 'In general, people were friendly.',
      exampleTranslation: 'En general, la gente fue amigable.',
      status: 'approved',
    },
    {
      id: 'voc_a2_such-as_287',
      word: 'such as',
      translation: 'tal como',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/sʌtʃ æz/',
      example: 'I like fruits such as mango and papaya.',
      exampleTranslation: 'Me gustan frutas como el mango y la papaya.',
      status: 'approved',
    },
    {
      id: 'voc_a2_in-particular_288',
      word: 'in particular',
      translation: 'en particular',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪn pərˈtɪkjələr/',
      example: 'I liked one dish in particular.',
      exampleTranslation: 'Me gustó un platillo en particular.',
      status: 'approved',
    },
  ] as const,
}
