/**
 * A2 Level Content — Week 11
 * Topic: Cocina y recetas
 * Curated from institutional curriculum (Zero AI)
 */
import type { ContentBlock } from '../types'

export const week11: ContentBlock = {
  level: 'A2',
  week: 11,
  topic: 'Cocina y recetas',
  vocabulary: [
    {
      id: 'voc_a2_recipe_496',
      word: 'recipe',
      translation: 'receta',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_ingredient_497',
      word: 'ingredient',
      translation: 'ingrediente',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_chop_498',
      word: 'chop',
      translation: 'picar',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_slice_499',
      word: 'slice',
      translation: 'cortar en rodajas',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_grate_500',
      word: 'grate',
      translation: 'rallar',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_peel_501',
      word: 'peel',
      translation: 'pelar',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_whisk_502',
      word: 'whisk',
      translation: 'batir',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_stir_503',
      word: 'stir',
      translation: 'revolver',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_boil_504',
      word: 'boil',
      translation: 'hervir',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_simmer_505',
      word: 'simmer',
      translation: 'cocinar a fuego lento',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_roast_506',
      word: 'roast',
      translation: 'asar (horno)',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_grill_507',
      word: 'grill',
      translation: 'asar a la parrilla',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_bake_508',
      word: 'bake',
      translation: 'hornear',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_fry_509',
      word: 'fry',
      translation: 'freír',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_steam_510',
      word: 'steam',
      translation: 'cocinar al vapor',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_marinate_511',
      word: 'marinate',
      translation: 'marinar',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_garnish_512',
      word: 'garnish',
      translation: 'decorar (plato)',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_portion_513',
      word: 'portion',
      translation: 'porción',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_serving_514',
      word: 'serving',
      translation: 'porción/ración',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_leftovers_515',
      word: 'leftovers',
      translation: 'sobras',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_preheat_516',
      word: 'preheat',
      translation: 'precalentar',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_blend_517',
      word: 'blend',
      translation: 'licuar',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_mash_518',
      word: 'mash',
      translation: 'triturar/hacer puré',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_dice_519',
      word: 'dice',
      translation: 'cortar en cubos',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_sprinkle_520',
      word: 'sprinkle',
      translation: 'espolvorear',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_drizzle_521',
      word: 'drizzle',
      translation: 'rociar (líquido)',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_sauce_522',
      word: 'sauce',
      translation: 'salsa',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_broth-stock_523',
      word: 'broth / stock',
      translation: 'caldo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_dough_524',
      word: 'dough',
      translation: 'masa',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_batter_525',
      word: 'batter',
      translation: 'masa líquida',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_yeast_526',
      word: 'yeast',
      translation: 'levadura',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_flour_527',
      word: 'flour',
      translation: 'harina',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_baking-powder_528',
      word: 'baking powder',
      translation: 'polvo de hornear',
      partOfSpeech: 'phrasal-verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_vanilla_529',
      word: 'vanilla',
      translation: 'vainilla',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_cinnamon_530',
      word: 'cinnamon',
      translation: 'canela',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_herbs_531',
      word: 'herbs',
      translation: 'hierbas',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_spices_532',
      word: 'spices',
      translation: 'especias',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_recipe-book-cookbook_533',
      word: 'recipe book / cookbook',
      translation: 'libro de cocina',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_nutrition-label_534',
      word: 'nutrition label',
      translation: 'etiqueta nutricional',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_expiration-date_535',
      word: 'expiration date',
      translation: 'fecha de caducidad',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_organic_536',
      word: 'organic',
      translation: 'orgánico',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_homemade_537',
      word: 'homemade',
      translation: 'casero',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_store-bought_538',
      word: 'store-bought',
      translation: 'comprado en tienda',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_vegetarian_539',
      word: 'vegetarian',
      translation: 'vegetariano',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_vegan_540',
      word: 'vegan',
      translation: 'vegano',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_gluten-free_541',
      word: 'gluten-free',
      translation: 'sin gluten',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_dairy-free_542',
      word: 'dairy-free',
      translation: 'sin lácteos',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_food-processor_543',
      word: 'food processor',
      translation: 'procesador de alimentos',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_blender_544',
      word: 'blender',
      translation: 'licuadora',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_mixing-bowl_545',
      word: 'mixing bowl',
      translation: 'tazón para mezclar',
      partOfSpeech: 'phrasal-verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_cutting-board_546',
      word: 'cutting board',
      translation: 'tabla de cortar',
      partOfSpeech: 'phrasal-verb',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_measuring-cup_547',
      word: 'measuring cup',
      translation: 'taza medidora',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_colander_548',
      word: 'colander',
      translation: 'colador',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_apron_549',
      word: 'apron',
      translation: 'delantal',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_recipe-card_550',
      word: 'recipe card',
      translation: 'tarjeta de receta',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_side-dish_551',
      word: 'side dish',
      translation: 'guarnición',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_main-course_552',
      word: 'main course',
      translation: 'plato principal',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_appetizer_553',
      word: 'appetizer',
      translation: 'aperitivo',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_dessert_554',
      word: 'dessert',
      translation: 'postre',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 11,
      topic: 'cocina-y-recetas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
  ] as const,
}
