/**
 * A2 Level Content — Week 07
 * Topic: Clima y desastres naturales
 * Curated from institutional curriculum (Zero AI)
 */
import type { ContentBlock } from '../types'

export const week07: ContentBlock = {
  level: 'A2',
  week: 7,
  topic: 'Clima y desastres naturales',
  vocabulary: [
    {
      id: 'voc_a2_heatwave_333',
      word: 'heatwave',
      translation: 'ola de calor',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_wildfire_334',
      word: 'wildfire',
      translation: 'incendio forestal',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_hurricane_335',
      word: 'hurricane',
      translation: 'huracán',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_tornado_336',
      word: 'tornado',
      translation: 'tornado',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_tsunami_337',
      word: 'tsunami',
      translation: 'tsunami',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_avalanche_338',
      word: 'avalanche',
      translation: 'avalancha',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_landslide_339',
      word: 'landslide',
      translation: 'deslizamiento de tierra',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_blizzard_340',
      word: 'blizzard',
      translation: 'ventisca',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_hailstorm_341',
      word: 'hailstorm',
      translation: 'granizada',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_thunderstorm_342',
      word: 'thunderstorm',
      translation: 'tormenta eléctrica',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_temperature-drop_343',
      word: 'temperature drop',
      translation: 'descenso de temperatura',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_climate-change_344',
      word: 'climate change',
      translation: 'cambio climático',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_global-warming_345',
      word: 'global warming',
      translation: 'calentamiento global',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_greenhouse-effect_346',
      word: 'greenhouse effect',
      translation: 'efecto invernadero',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_carbon-footprint_347',
      word: 'carbon footprint',
      translation: 'huella de carbono',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_renewable-energy_348',
      word: 'renewable energy',
      translation: 'energía renovable',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_deforestation_349',
      word: 'deforestation',
      translation: 'deforestación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_extinction_350',
      word: 'extinction',
      translation: 'extinción',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_endangered-species_351',
      word: 'endangered species',
      translation: 'especie en peligro',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_natural-disaster_352',
      word: 'natural disaster',
      translation: 'desastre natural',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_shelter_353',
      word: 'shelter (emergency)',
      translation: 'refugio',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_relief-effort_354',
      word: 'relief effort',
      translation: 'esfuerzo de ayuda',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_damage_355',
      word: 'damage',
      translation: 'daño',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_destruction_356',
      word: 'destruction',
      translation: 'destrucción',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_rebuild_357',
      word: 'rebuild',
      translation: 'reconstruir',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_warning-system_358',
      word: 'warning system',
      translation: 'sistema de alerta',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_meteorologist_359',
      word: 'meteorologist',
      translation: 'meteorólogo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_atmosphere_360',
      word: 'atmosphere',
      translation: 'atmósfera',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_ozone-layer_361',
      word: 'ozone layer',
      translation: 'capa de ozono',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_ecosystem_362',
      word: 'ecosystem',
      translation: 'ecosistema',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_biodiversity_363',
      word: 'biodiversity',
      translation: 'biodiversidad',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_sustainability_364',
      word: 'sustainability',
      translation: 'sostenibilidad',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_emission_365',
      word: 'emission',
      translation: 'emisión',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_fossil-fuel_366',
      word: 'fossil fuel',
      translation: 'combustible fósil',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
  ] as const,
}
