/**
 * A2 Level Content — Week 13
 * Topic: Deportes y vida activa
 * Curated from institutional curriculum (Zero AI)
 */
import type { ContentBlock } from '../types'

export const week13: ContentBlock = {
  level: 'A2',
  week: 13,
  topic: 'Deportes y vida activa',
  vocabulary: [
    {
      id: 'voc_a2_tournament_605',
      word: 'tournament',
      translation: 'torneo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_league_606',
      word: 'league',
      translation: 'liga',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_teammate_607',
      word: 'teammate',
      translation: 'compañero de equipo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_opponent_608',
      word: 'opponent',
      translation: 'oponente',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_warm-up_609',
      word: 'warm-up',
      translation: 'calentamiento',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_stretch_610',
      word: 'stretch',
      translation: 'estirar',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_stamina_611',
      word: 'stamina',
      translation: 'resistencia',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_cardio_612',
      word: 'cardio',
      translation: 'cardio',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_strength-training_613',
      word: 'strength training',
      translation: 'entrenamiento de fuerza',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_personal-trainer_614',
      word: 'personal trainer',
      translation: 'entrenador personal',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_workout_615',
      word: 'workout',
      translation: 'rutina de ejercicio',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_set_616',
      word: 'set (exercise)',
      translation: 'serie (ejercicio)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_rep-repetition_617',
      word: 'rep / repetition',
      translation: 'repetición',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_marathon_618',
      word: 'marathon',
      translation: 'maratón',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_sprint_619',
      word: 'sprint',
      translation: 'carrera corta/esprintar',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_finish-line_620',
      word: 'finish line',
      translation: 'línea de meta',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_medal_621',
      word: 'medal',
      translation: 'medalla',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_trophy_622',
      word: 'trophy',
      translation: 'trofeo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_record_623',
      word: 'record (sports)',
      translation: 'récord',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_draw_624',
      word: 'draw (tie)',
      translation: 'empate',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_penalty_625',
      word: 'penalty',
      translation: 'penalti',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_foul_626',
      word: 'foul',
      translation: 'falta',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_injury-time_627',
      word: 'injury time',
      translation: 'tiempo de descuento',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_substitute_628',
      word: 'substitute (player)',
      translation: 'suplente',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_spectator_629',
      word: 'spectator',
      translation: 'espectador',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_scoreboard_630',
      word: 'scoreboard',
      translation: 'marcador',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_halftime_631',
      word: 'halftime',
      translation: 'medio tiempo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_locker-room_632',
      word: 'locker room',
      translation: 'vestuario',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_equipment_633',
      word: 'equipment (sports)',
      translation: 'equipo (deportivo)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_helmet_634',
      word: 'helmet',
      translation: 'casco',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_mat_635',
      word: 'mat (exercise)',
      translation: 'colchoneta',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_treadmill_636',
      word: 'treadmill',
      translation: 'cinta de correr',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_dumbbell_637',
      word: 'dumbbell',
      translation: 'mancuerna',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_flexibility_638',
      word: 'flexibility',
      translation: 'flexibilidad',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_endurance_639',
      word: 'endurance',
      translation: 'resistencia (física)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_posture_640',
      word: 'posture',
      translation: 'postura',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_physical-fitness_641',
      word: 'physical fitness',
      translation: 'aptitud física',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_recreational_642',
      word: 'recreational',
      translation: 'recreativo',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_outdoor-activity_643',
      word: 'outdoor activity',
      translation: 'actividad al aire libre',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_adventure-sport_644',
      word: 'adventure sport',
      translation: 'deporte de aventura',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
  ] as const,
}
