/**
 * A2 Level Content — Week 15
 * Topic: Personalidad y carácter
 * Curated from institutional curriculum (Zero AI)
 */
import type { ContentBlock } from '../types'

export const week15: ContentBlock = {
  level: 'A2',
  week: 15,
  topic: 'Personalidad y carácter',
  vocabulary: [
    {
      id: 'voc_a2_ambitious_687',
      word: 'ambitious',
      translation: 'ambicioso',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_stubborn_688',
      word: 'stubborn',
      translation: 'terco',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_arrogant_689',
      word: 'arrogant',
      translation: 'arrogante',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_humble_690',
      word: 'humble',
      translation: 'humilde',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_reliable_691',
      word: 'reliable',
      translation: 'confiable',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_trustworthy_692',
      word: 'trustworthy',
      translation: 'digno de confianza',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_sociable_693',
      word: 'sociable',
      translation: 'sociable',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_introverted_694',
      word: 'introverted',
      translation: 'introvertido',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_extroverted_695',
      word: 'extroverted',
      translation: 'extrovertido',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_open-minded_696',
      word: 'open-minded',
      translation: 'de mente abierta',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_closed-minded_697',
      word: 'closed-minded',
      translation: 'cerrado de mente',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_judgmental_698',
      word: 'judgmental',
      translation: 'crítico/juzgón',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_optimistic_699',
      word: 'optimistic',
      translation: 'optimista',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_pessimistic_700',
      word: 'pessimistic',
      translation: 'pesimista',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_realistic_701',
      word: 'realistic',
      translation: 'realista',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_idealistic_702',
      word: 'idealistic',
      translation: 'idealista',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_assertive_703',
      word: 'assertive',
      translation: 'asertivo',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_passive_704',
      word: 'passive',
      translation: 'pasivo',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_aggressive_705',
      word: 'aggressive',
      translation: 'agresivo',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_competitive_706',
      word: 'competitive',
      translation: 'competitivo',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_cooperative_707',
      word: 'cooperative',
      translation: 'cooperativo',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_independent_708',
      word: 'independent',
      translation: 'independiente',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_dependent_709',
      word: 'dependent',
      translation: 'dependiente',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_mature_710',
      word: 'mature',
      translation: 'maduro',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_immature_711',
      word: 'immature',
      translation: 'inmaduro',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_responsible_712',
      word: 'responsible',
      translation: 'responsable',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_irresponsible_713',
      word: 'irresponsible',
      translation: 'irresponsable',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_disciplined_714',
      word: 'disciplined',
      translation: 'disciplinado',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_spontaneous_715',
      word: 'spontaneous',
      translation: 'espontáneo',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_cautious_716',
      word: 'cautious',
      translation: 'cauteloso',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_adventurous_717',
      word: 'adventurous',
      translation: 'aventurero',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_creative_718',
      word: 'creative',
      translation: 'creativo',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_logical_719',
      word: 'logical',
      translation: 'lógico',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_analytical_720',
      word: 'analytical',
      translation: 'analítico',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_intuitive_721',
      word: 'intuitive',
      translation: 'intuitivo',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_perceptive_722',
      word: 'perceptive',
      translation: 'perceptivo',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_charismatic_723',
      word: 'charismatic',
      translation: 'carismático',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_witty_724',
      word: 'witty',
      translation: 'ingenioso',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_sarcastic_725',
      word: 'sarcastic',
      translation: 'sarcástico',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_blunt_726',
      word: 'blunt',
      translation: 'directo/franco',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_diplomatic_727',
      word: 'diplomatic',
      translation: 'diplomático',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_tactful_728',
      word: 'tactful',
      translation: 'con tacto',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_insensitive_729',
      word: 'insensitive',
      translation: 'insensible',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_thoughtful_730',
      word: 'thoughtful',
      translation: 'considerado',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_forgetful_731',
      word: 'forgetful',
      translation: 'olvidadizo',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_punctual_732',
      word: 'punctual',
      translation: 'puntual',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_easygoing_733',
      word: 'easygoing',
      translation: 'de trato fácil',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_demanding_734',
      word: 'demanding',
      translation: 'exigente',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
  ] as const,
}
