/**
 * A2 Level Content — Week 04
 * Topic: Salud y cuerpo (síntomas y citas médicas)
 * Curated from institutional curriculum (Zero AI)
 */
import type { ContentBlock } from '../types'

export const week04: ContentBlock = {
  level: 'A2',
  week: 4,
  topic: 'Salud y cuerpo (síntomas y citas médicas)',
  vocabulary: [
    {
      id: 'voc_a2_symptom_182',
      word: 'symptom',
      translation: 'síntoma',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsɪmptəm/',
      example: 'What symptoms do you have?',
      exampleTranslation: '¿Qué síntomas tienes?',
      status: 'approved',
    },
    {
      id: 'voc_a2_diagnosis_183',
      word: 'diagnosis',
      translation: 'diagnóstico',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌdaɪəgˈnoʊsɪs/',
      example: 'The doctor gave a clear diagnosis.',
      exampleTranslation: 'El médico dio un diagnóstico claro.',
      status: 'approved',
    },
    {
      id: 'voc_a2_prescription_184',
      word: 'prescription',
      translation: 'receta médica',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/prɪˈskrɪpʃən/',
      example: 'The doctor wrote a prescription.',
      exampleTranslation: 'El médico escribió una receta.',
      status: 'approved',
    },
    {
      id: 'voc_a2_dosage_185',
      word: 'dosage',
      translation: 'dosis',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdoʊsɪdʒ/',
      example: 'Follow the correct dosage.',
      exampleTranslation: 'Sigue la dosis correcta.',
      status: 'approved',
    },
    {
      id: 'voc_a2_side-effect_186',
      word: 'side effect',
      translation: 'efecto secundario',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/saɪd ɪˈfɛkt/',
      example: 'This medicine has few side effects.',
      exampleTranslation: 'Esta medicina tiene pocos efectos secundarios.',
      status: 'approved',
    },
    {
      id: 'voc_a2_allergy_187',
      word: 'allergy',
      translation: 'alergia',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈælərdʒi/',
      example: 'I have a food allergy.',
      exampleTranslation: 'Tengo una alergia alimentaria.',
      status: 'approved',
    },
    {
      id: 'voc_a2_allergic-reaction_188',
      word: 'allergic reaction',
      translation: 'reacción alérgica',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈlɜrdʒɪk riˈækʃən/',
      example: 'She had an allergic reaction.',
      exampleTranslation: 'Ella tuvo una reacción alérgica.',
      status: 'approved',
    },
    {
      id: 'voc_a2_infection_189',
      word: 'infection',
      translation: 'infección',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪnˈfɛkʃən/',
      example: 'He has an ear infection.',
      exampleTranslation: 'Él tiene una infección de oído.',
      status: 'approved',
    },
    {
      id: 'voc_a2_inflammation_190',
      word: 'inflammation',
      translation: 'inflamación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌɪnfləˈmeɪʃən/',
      example: 'There is inflammation in his knee.',
      exampleTranslation: 'Hay inflamación en su rodilla.',
      status: 'approved',
    },
    {
      id: 'voc_a2_rash_191',
      word: 'rash',
      translation: 'sarpullido',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ræʃ/',
      example: 'She has a rash on her arm.',
      exampleTranslation: 'Ella tiene un sarpullido en el brazo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_swelling_192',
      word: 'swelling',
      translation: 'hinchazón',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈswɛlɪŋ/',
      example: 'The swelling went down quickly.',
      exampleTranslation: 'La hinchazón bajó rápido.',
      status: 'approved',
    },
    {
      id: 'voc_a2_bruise_193',
      word: 'bruise',
      translation: 'moretón',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bruz/',
      example: 'He has a bruise on his leg.',
      exampleTranslation: 'Él tiene un moretón en la pierna.',
      status: 'approved',
    },
    {
      id: 'voc_a2_wound_194',
      word: 'wound',
      translation: 'herida',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/wund/',
      example: 'Clean the wound carefully.',
      exampleTranslation: 'Limpia la herida con cuidado.',
      status: 'approved',
    },
    {
      id: 'voc_a2_stitches_195',
      word: 'stitches',
      translation: 'puntos de sutura',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈstɪtʃɪz/',
      example: 'He needed five stitches.',
      exampleTranslation: 'Él necesitó cinco puntos de sutura.',
      status: 'approved',
    },
    {
      id: 'voc_a2_cast_196',
      word: 'cast (medical)',
      translation: 'yeso',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kæst/',
      example: 'She has a cast on her arm.',
      exampleTranslation: 'Ella tiene un yeso en el brazo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_crutches_197',
      word: 'crutches',
      translation: 'muletas',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkrʌtʃɪz/',
      example: 'He is using crutches now.',
      exampleTranslation: 'Él está usando muletas ahora.',
      status: 'approved',
    },
    {
      id: 'voc_a2_wheelchair_198',
      word: 'wheelchair',
      translation: 'silla de ruedas',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈwilˌtʃɛr/',
      example: 'She uses a wheelchair.',
      exampleTranslation: 'Ella usa una silla de ruedas.',
      status: 'approved',
    },
    {
      id: 'voc_a2_blood-pressure_199',
      word: 'blood pressure',
      translation: 'presión arterial',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/blʌd ˈprɛʃər/',
      example: 'The nurse checked my blood pressure.',
      exampleTranslation: 'La enfermera revisó mi presión arterial.',
      status: 'approved',
    },
    {
      id: 'voc_a2_heart-rate_200',
      word: 'heart rate',
      translation: 'ritmo cardíaco',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/hɑrt reɪt/',
      example: 'His heart rate is normal.',
      exampleTranslation: 'Su ritmo cardíaco es normal.',
      status: 'approved',
    },
    {
      id: 'voc_a2_pulse_201',
      word: 'pulse',
      translation: 'pulso',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pʌls/',
      example: 'The doctor checked my pulse.',
      exampleTranslation: 'El médico revisó mi pulso.',
      status: 'approved',
    },
    {
      id: 'voc_a2_x-ray_202',
      word: 'x-ray',
      translation: 'radiografía',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɛksˌreɪ/',
      example: 'They took an x-ray of my arm.',
      exampleTranslation: 'Me tomaron una radiografía del brazo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_surgery-operation_203',
      word: 'surgery / operation',
      translation: 'cirugía',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsɜrdʒəri/',
      example: 'She needs surgery next month.',
      exampleTranslation: 'Ella necesita cirugía el próximo mes.',
      status: 'approved',
    },
    {
      id: 'voc_a2_anesthesia_204',
      word: 'anesthesia',
      translation: 'anestesia',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌænəsˈθiʒə/',
      example: 'He was under anesthesia for an hour.',
      exampleTranslation: 'Él estuvo bajo anestesia por una hora.',
      status: 'approved',
    },
    {
      id: 'voc_a2_recovery_205',
      word: 'recovery',
      translation: 'recuperación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rɪˈkʌvəri/',
      example: 'Her recovery is going well.',
      exampleTranslation: 'Su recuperación va bien.',
      status: 'approved',
    },
    {
      id: 'voc_a2_checkup_206',
      word: 'checkup',
      translation: 'chequeo médico',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtʃɛkˌʌp/',
      example: 'I have a checkup next week.',
      exampleTranslation: 'Tengo un chequeo médico la próxima semana.',
      status: 'approved',
    },
    {
      id: 'voc_a2_specialist_207',
      word: 'specialist',
      translation: 'especialista',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈspɛʃəlɪst/',
      example: 'She saw a specialist yesterday.',
      exampleTranslation: 'Ella vio a un especialista ayer.',
      status: 'approved',
    },
    {
      id: 'voc_a2_physical-therapy_208',
      word: 'physical therapy',
      translation: 'fisioterapia',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfɪzɪkəl ˈθɛrəpi/',
      example: 'He goes to physical therapy twice a week.',
      exampleTranslation: 'Él va a fisioterapia dos veces por semana.',
      status: 'approved',
    },
    {
      id: 'voc_a2_mental-health_209',
      word: 'mental health',
      translation: 'salud mental',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmɛntəl hɛlθ/',
      example: 'Mental health matters too.',
      exampleTranslation: 'La salud mental también importa.',
      status: 'approved',
    },
    {
      id: 'voc_a2_anxiety_210',
      word: 'anxiety',
      translation: 'ansiedad',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/æŋˈzaɪəti/',
      example: 'She feels anxiety before exams.',
      exampleTranslation: 'Ella siente ansiedad antes de los exámenes.',
      status: 'approved',
    },
    {
      id: 'voc_a2_depression_211',
      word: 'depression',
      translation: 'depresión',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dɪˈprɛʃən/',
      example: 'He is being treated for depression.',
      exampleTranslation: 'Él está siendo tratado por depresión.',
      status: 'approved',
    },
    {
      id: 'voc_a2_sleep-disorder_212',
      word: 'sleep disorder',
      translation: 'trastorno del sueño',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/slip dɪsˈɔrdər/',
      example: 'He was diagnosed with a sleep disorder.',
      exampleTranslation: 'Le diagnosticaron un trastorno del sueño.',
      status: 'approved',
    },
    {
      id: 'voc_a2_chronic_213',
      word: 'chronic',
      translation: 'crónico',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkrɑnɪk/',
      example: 'She has a chronic condition.',
      exampleTranslation: 'Ella tiene una condición crónica.',
      status: 'approved',
    },
    {
      id: 'voc_a2_acute_214',
      word: 'acute',
      translation: 'agudo',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈkjut/',
      example: 'He had an acute pain in his chest.',
      exampleTranslation: 'Él tuvo un dolor agudo en el pecho.',
      status: 'approved',
    },
    {
      id: 'voc_a2_contagious_215',
      word: 'contagious',
      translation: 'contagioso',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kənˈteɪdʒəs/',
      example: 'The flu is very contagious.',
      exampleTranslation: 'La gripe es muy contagiosa.',
      status: 'approved',
    },
    {
      id: 'voc_a2_immune-system_216',
      word: 'immune system',
      translation: 'sistema inmunológico',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪˈmjun ˈsɪstəm/',
      example: 'Vitamin C helps the immune system.',
      exampleTranslation: 'La vitamina C ayuda al sistema inmunológico.',
      status: 'approved',
    },
    {
      id: 'voc_a2_lungs_217',
      word: 'lungs',
      translation: 'pulmones',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/lʌŋz/',
      example: 'Smoking damages your lungs.',
      exampleTranslation: 'Fumar daña tus pulmones.',
      status: 'approved',
    },
    {
      id: 'voc_a2_liver_218',
      word: 'liver',
      translation: 'hígado',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈlɪvər/',
      example: 'Alcohol affects the liver.',
      exampleTranslation: 'El alcohol afecta el hígado.',
      status: 'approved',
    },
    {
      id: 'voc_a2_kidney_219',
      word: 'kidney',
      translation: 'riñón',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkɪdni/',
      example: 'He donated a kidney to his brother.',
      exampleTranslation: 'Él donó un riñón a su hermano.',
      status: 'approved',
    },
    {
      id: 'voc_a2_intestine_220',
      word: 'intestine',
      translation: 'intestino',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪnˈtɛstɪn/',
      example: 'The doctor examined his intestine.',
      exampleTranslation: 'El médico examinó su intestino.',
      status: 'approved',
    },
    {
      id: 'voc_a2_joint_221',
      word: 'joint',
      translation: 'articulación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dʒɔɪnt/',
      example: 'My knee joint hurts.',
      exampleTranslation: 'Me duele la articulación de la rodilla.',
      status: 'approved',
    },
    {
      id: 'voc_a2_spine_222',
      word: 'spine',
      translation: 'columna vertebral',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/spaɪn/',
      example: 'She injured her spine.',
      exampleTranslation: 'Ella se lesionó la columna vertebral.',
      status: 'approved',
    },
    {
      id: 'voc_a2_artery_223',
      word: 'artery',
      translation: 'arteria',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɑrtəri/',
      example: 'The artery was blocked.',
      exampleTranslation: 'La arteria estaba obstruida.',
      status: 'approved',
    },
    {
      id: 'voc_a2_vein_224',
      word: 'vein',
      translation: 'vena',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/veɪn/',
      example: 'The nurse found a vein easily.',
      exampleTranslation: 'La enfermera encontró una vena fácilmente.',
      status: 'approved',
    },
    {
      id: 'voc_a2_nervous-system_225',
      word: 'nervous system',
      translation: 'sistema nervioso',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈnɜrvəs ˈsɪstəm/',
      example: 'Stress affects the nervous system.',
      exampleTranslation: 'El estrés afecta el sistema nervioso.',
      status: 'approved',
    },
    {
      id: 'voc_a2_digestive-system_226',
      word: 'digestive system',
      translation: 'sistema digestivo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/daɪˈdʒɛstɪv ˈsɪstəm/',
      example: 'Fiber helps the digestive system.',
      exampleTranslation: 'La fibra ayuda al sistema digestivo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_hormone_227',
      word: 'hormone',
      translation: 'hormona',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈhɔrˌmoʊn/',
      example: 'This hormone controls growth.',
      exampleTranslation: 'Esta hormona controla el crecimiento.',
      status: 'approved',
    },
    {
      id: 'voc_a2_metabolism_228',
      word: 'metabolism',
      translation: 'metabolismo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/məˈtæbəˌlɪzəm/',
      example: 'Exercise speeds up your metabolism.',
      exampleTranslation: 'El ejercicio acelera tu metabolismo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_nutrient_229',
      word: 'nutrient',
      translation: 'nutriente',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈnutriənt/',
      example: 'Vegetables are full of nutrients.',
      exampleTranslation: 'Las verduras están llenas de nutrientes.',
      status: 'approved',
    },
    {
      id: 'voc_a2_vitamin_230',
      word: 'vitamin',
      translation: 'vitamina',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈvaɪtəmɪn/',
      example: 'I take a vitamin every morning.',
      exampleTranslation: 'Tomo una vitamina cada mañana.',
      status: 'approved',
    },
    {
      id: 'voc_a2_protein_231',
      word: 'protein',
      translation: 'proteína',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈproʊˌtin/',
      example: 'Chicken has a lot of protein.',
      exampleTranslation: 'El pollo tiene mucha proteína.',
      status: 'approved',
    },
    {
      id: 'voc_a2_carbohydrate_232',
      word: 'carbohydrate',
      translation: 'carbohidrato',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌkɑrboʊˈhaɪˌdreɪt/',
      example: 'Rice is high in carbohydrates.',
      exampleTranslation: 'El arroz es alto en carbohidratos.',
      status: 'approved',
    },
    {
      id: 'voc_a2_fiber_233',
      word: 'fiber',
      translation: 'fibra',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfaɪbər/',
      example: 'This bread has a lot of fiber.',
      exampleTranslation: 'Este pan tiene mucha fibra.',
      status: 'approved',
    },
    {
      id: 'voc_a2_calorie_234',
      word: 'calorie',
      translation: 'caloría',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkæləri/',
      example: 'This snack has pocas calorías.',
      exampleTranslation: 'Esta merienda tiene pocas calorías.',
      status: 'approved',
    },
    {
      id: 'voc_a2_overweight_235',
      word: 'overweight',
      translation: 'sobrepeso',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌoʊvərˈweɪt/',
      example: 'The doctor said he was overweight.',
      exampleTranslation: 'El médico dijo que él tenía sobrepeso.',
      status: 'approved',
    },
    {
      id: 'voc_a2_underweight_236',
      word: 'underweight',
      translation: 'bajo peso',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈʌndərˌweɪt/',
      example: 'The baby was slightly underweight.',
      exampleTranslation: 'El bebé tenía un poco de bajo peso.',
      status: 'approved',
    },
    {
      id: 'voc_a2_obesity_237',
      word: 'obesity',
      translation: 'obesidad',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/oʊˈbisəti/',
      example: 'Obesity is a growing health issue.',
      exampleTranslation: 'La obesidad es un problema de salud creciente.',
      status: 'approved',
    },
    {
      id: 'voc_a2_wellness_238',
      word: 'wellness',
      translation: 'bienestar',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈwɛlnəs/',
      example: 'The company offers wellness programs.',
      exampleTranslation: 'La empresa ofrece programas de bienestar.',
      status: 'approved',
    },
    {
      id: 'voc_a2_hygiene_239',
      word: 'hygiene',
      translation: 'higiene',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈhaɪdʒin/',
      example: 'Good hygiene prevents illness.',
      exampleTranslation: 'La buena higiene previene enfermedades.',
      status: 'approved',
    },
    {
      id: 'voc_a2_first-aid-kit_240',
      word: 'first aid kit',
      translation: 'botiquín de primeros auxilios',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fɜrst eɪd kɪt/',
      example: 'We keep a first aid kit at home.',
      exampleTranslation: 'Tenemos un botiquín de primeros auxilios en casa.',
      status: 'approved',
    },
  ] as const,
}
