/**
 * A2 Level Content — Week 09
 * Topic: Relaciones y emociones complejas
 * Curated from institutional curriculum (Zero AI)
 */
import type { ContentBlock } from '../types'

export const week09: ContentBlock = {
  level: 'A2',
  week: 9,
  topic: 'Relaciones y emociones complejas',
  vocabulary: [
    {
      id: 'voc_a2_trust-issues_413',
      word: 'trust issues',
      translation: 'problemas de confianza',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_commitment_414',
      word: 'commitment',
      translation: 'compromiso',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_breakup_415',
      word: 'breakup',
      translation: 'ruptura',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_reconciliation_416',
      word: 'reconciliation',
      translation: 'reconciliación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_betrayal_417',
      word: 'betrayal',
      translation: 'traición',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_forgiveness_418',
      word: 'forgiveness',
      translation: 'perdón',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_empathy_419',
      word: 'empathy',
      translation: 'empatía',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_sympathy_420',
      word: 'sympathy',
      translation: 'compasión/comprensión',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_compassion_421',
      word: 'compassion',
      translation: 'compasión',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_resentment_422',
      word: 'resentment',
      translation: 'resentimiento',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_heartbreak_423',
      word: 'heartbreak',
      translation: 'desamor',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_infatuation_424',
      word: 'infatuation',
      translation: 'enamoramiento pasajero',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_attraction_425',
      word: 'attraction',
      translation: 'atracción',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_compatibility_426',
      word: 'compatibility',
      translation: 'compatibilidad',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_conflict-resolution_427',
      word: 'conflict resolution',
      translation: 'resolución de conflictos',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_compromise_428',
      word: 'compromise',
      translation: 'compromiso/acuerdo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_mutual-respect_429',
      word: 'mutual respect',
      translation: 'respeto mutuo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_boundaries_430',
      word: 'boundaries',
      translation: 'límites (emocionales)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_codependency_431',
      word: 'codependency',
      translation: 'codependencia',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_long-distance-relati_432',
      word: 'long-distance relationship',
      translation: 'relación a distancia',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_soulmate_433',
      word: 'soulmate',
      translation: 'alma gemela',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_companionship_434',
      word: 'companionship',
      translation: 'compañerismo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_intimacy_435',
      word: 'intimacy',
      translation: 'intimidad',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_vulnerability_436',
      word: 'vulnerability',
      translation: 'vulnerabilidad',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_self-esteem_437',
      word: 'self-esteem',
      translation: 'autoestima',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_self-doubt_438',
      word: 'self-doubt',
      translation: 'inseguridad/duda de uno mismo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_insecurity_439',
      word: 'insecurity',
      translation: 'inseguridad',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_overwhelmed_440',
      word: 'overwhelmed',
      translation: 'abrumado',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_burnout_441',
      word: 'burnout',
      translation: 'agotamiento (laboral/emocional)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_frustration_442',
      word: 'frustration',
      translation: 'frustración',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_irritation_443',
      word: 'irritation',
      translation: 'irritación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_resentful_444',
      word: 'resentful',
      translation: 'resentido',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_heartfelt_445',
      word: 'heartfelt',
      translation: 'sincero/de corazón',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_overjoyed_446',
      word: 'overjoyed',
      translation: 'muy feliz',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_devastated_447',
      word: 'devastated',
      translation: 'devastado',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_humiliated_448',
      word: 'humiliated',
      translation: 'humillado',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_ashamed_449',
      word: 'ashamed',
      translation: 'avergonzado',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_guilty_450',
      word: 'guilty',
      translation: 'culpable',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_remorse_451',
      word: 'remorse',
      translation: 'remordimiento',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_regret_452',
      word: 'regret',
      translation: 'arrepentimiento',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_longing_453',
      word: 'longing',
      translation: 'anhelo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_nostalgia_454',
      word: 'nostalgia',
      translation: 'nostalgia',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_contentment_455',
      word: 'contentment',
      translation: 'satisfacción/contento',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_fulfillment_456',
      word: 'fulfillment',
      translation: 'realización personal',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
  ] as const,
}
