/**
 * A2 Level Content — Week 01
 * Topic: Compras y devoluciones
 * Curated from institutional curriculum (Zero AI)
 */
import type { ContentBlock } from '../types'

export const week01: ContentBlock = {
  level: 'A2',
  week: 1,
  topic: 'Compras y devoluciones',
  vocabulary: [
    {
      id: 'voc_a2_refund_001',
      word: 'refund',
      translation: 'reembolso',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_exchange_002',
      word: 'exchange (product)',
      translation: 'cambio (producto)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_return_003',
      word: 'return (product)',
      translation: 'devolución',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_warranty_004',
      word: 'warranty',
      translation: 'garantía',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_guarantee_005',
      word: 'guarantee',
      translation: 'garantía (verbo/promesa)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_complaint_006',
      word: 'complaint',
      translation: 'queja',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_customer-service_007',
      word: 'customer service',
      translation: 'servicio al cliente',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_fitting-room_008',
      word: 'fitting room',
      translation: 'probador',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_barcode_009',
      word: 'barcode',
      translation: 'código de barras',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_discount-code_010',
      word: 'discount code',
      translation: 'código de descuento',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_clearance_011',
      word: 'clearance',
      translation: 'liquidación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_bargain_012',
      word: 'bargain',
      translation: 'ganga',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_brand-new_013',
      word: 'brand new',
      translation: 'totalmente nuevo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_secondhand_014',
      word: 'secondhand',
      translation: 'de segunda mano',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_quality-control_015',
      word: 'quality control',
      translation: 'control de calidad',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_damaged_016',
      word: 'damaged',
      translation: 'dañado',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_broken_017',
      word: 'broken (thing)',
      translation: 'roto',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_defective_018',
      word: 'defective',
      translation: 'defectuoso',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_missing-part_019',
      word: 'missing part',
      translation: 'pieza faltante',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_instructions-manual_020',
      word: 'instructions manual',
      translation: 'manual de instrucciones',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_assemble_021',
      word: 'assemble',
      translation: 'ensamblar',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_gift-receipt_022',
      word: 'gift receipt',
      translation: 'recibo de regalo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_loyalty-card_023',
      word: 'loyalty card',
      translation: 'tarjeta de fidelidad',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_membership_024',
      word: 'membership',
      translation: 'membresía',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_catalog_025',
      word: 'catalog',
      translation: 'catálogo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_order-online_026',
      word: 'order online',
      translation: 'pedir en línea',
      partOfSpeech: 'phrasal-verb',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_shipping_027',
      word: 'shipping',
      translation: 'envío',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_delivery_028',
      word: 'delivery',
      translation: 'entrega',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_package-parcel_029',
      word: 'package / parcel',
      translation: 'paquete',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_tracking-number_030',
      word: 'tracking number',
      translation: 'número de rastreo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_courier_031',
      word: 'courier',
      translation: 'mensajero',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_express-delivery_032',
      word: 'express delivery',
      translation: 'envío exprés',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_standard-delivery_033',
      word: 'standard delivery',
      translation: 'envío estándar',
      partOfSpeech: 'phrasal-verb',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_out-of-stock_034',
      word: 'out of stock',
      translation: 'agotado',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_in-stock_035',
      word: 'in stock',
      translation: 'en existencia',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_available_036',
      word: 'available',
      translation: 'disponible',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_unavailable_037',
      word: 'unavailable',
      translation: 'no disponible',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_color-option_038',
      word: 'color option',
      translation: 'opción de color',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_model_039',
      word: 'model (product)',
      translation: 'modelo (producto)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_version_040',
      word: 'version',
      translation: 'versión',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_upgrade_041',
      word: 'upgrade',
      translation: 'mejora/actualización',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_downgrade_042',
      word: 'downgrade',
      translation: 'reducir (plan/versión)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_subscription_043',
      word: 'subscription',
      translation: 'suscripción',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_cancel_044',
      word: 'cancel',
      translation: 'cancelar',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_renew_045',
      word: 'renew',
      translation: 'renovar',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_invoice_046',
      word: 'invoice',
      translation: 'factura',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_payment-method_047',
      word: 'payment method',
      translation: 'método de pago',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_installment_048',
      word: 'installment',
      translation: 'cuota/pago a plazos',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_negotiate_049',
      word: 'negotiate',
      translation: 'negociar',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_haggle_050',
      word: 'haggle',
      translation: 'regatear',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_overpriced_051',
      word: 'overpriced',
      translation: 'sobrevalorado',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_affordable_052',
      word: 'affordable',
      translation: 'asequible',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_worth-it_053',
      word: 'worth it',
      translation: 'que vale la pena',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_satisfied_054',
      word: 'satisfied',
      translation: 'satisfecho',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_dissatisfied_055',
      word: 'dissatisfied',
      translation: 'insatisfecho',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_store-credit_056',
      word: 'store credit',
      translation: 'crédito de tienda',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_gift-card_057',
      word: 'gift card',
      translation: 'tarjeta de regalo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_coupon_058',
      word: 'coupon',
      translation: 'cupón',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_promo-code_059',
      word: 'promo code',
      translation: 'código promocional',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_limited-offer_060',
      word: 'limited offer',
      translation: 'oferta limitada',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_best-seller_061',
      word: 'best seller',
      translation: 'más vendido',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_customer-review_062',
      word: 'customer review',
      translation: 'reseña de cliente',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_rating_063',
      word: 'rating',
      translation: 'calificación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_feedback_064',
      word: 'feedback',
      translation: 'retroalimentación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
  ] as const,
}
