/**
 * A2 Level Content — Week 03
 * Topic: Trabajo y oficina
 * Curated from institutional curriculum (Zero AI)
 */
import type { ContentBlock } from '../types'

export const week03: ContentBlock = {
  level: 'A2',
  week: 3,
  topic: 'Trabajo y oficina',
  vocabulary: [
    {
      id: 'voc_a2_resume-cv_121',
      word: 'resume / CV',
      translation: 'currículum',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈrɛzəˌmeɪ/',
      example: 'I updated my resume last week.',
      exampleTranslation: 'Actualicé mi currículum la semana pasada.',
      status: 'approved',
    },
    {
      id: 'voc_a2_cover-letter_122',
      word: 'cover letter',
      translation: 'carta de presentación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkʌvər ˈlɛtər/',
      example: 'Attach a cover letter to your application.',
      exampleTranslation: 'Adjunta una carta de presentación a tu solicitud.',
      status: 'approved',
    },
    {
      id: 'voc_a2_job-interview_123',
      word: 'job interview',
      translation: 'entrevista de trabajo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dʒɑb ˈɪntərˌvju/',
      example: 'I have a job interview tomorrow.',
      exampleTranslation: 'Tengo una entrevista de trabajo mañana.',
      status: 'approved',
    },
    {
      id: 'voc_a2_job-offer_124',
      word: 'job offer',
      translation: 'oferta de trabajo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dʒɑb ˈɔfər/',
      example: 'She accepted the job offer.',
      exampleTranslation: 'Ella aceptó la oferta de trabajo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_position_125',
      word: 'position',
      translation: 'puesto',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pəˈzɪʃən/',
      example: 'This position requires experience.',
      exampleTranslation: 'Este puesto requiere experiencia.',
      status: 'approved',
    },
    {
      id: 'voc_a2_department_126',
      word: 'department',
      translation: 'departamento',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dɪˈpɑrtmənt/',
      example: 'He works in the sales department.',
      exampleTranslation: 'Él trabaja en el departamento de ventas.',
      status: 'approved',
    },
    {
      id: 'voc_a2_colleague_127',
      word: 'colleague',
      translation: 'colega',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkɑlig/',
      example: 'My colleague helped me with the report.',
      exampleTranslation: 'Mi colega me ayudó con el informe.',
      status: 'approved',
    },
    {
      id: 'voc_a2_supervisor_128',
      word: 'supervisor',
      translation: 'supervisor',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsupərˌvaɪzər/',
      example: 'My supervisor approved my request.',
      exampleTranslation: 'Mi supervisor aprobó mi solicitud.',
      status: 'approved',
    },
    {
      id: 'voc_a2_deadline_129',
      word: 'deadline',
      translation: 'fecha límite',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdɛdˌlaɪn/',
      example: 'The deadline is next Friday.',
      exampleTranslation: 'La fecha límite es el próximo viernes.',
      status: 'approved',
    },
    {
      id: 'voc_a2_meeting-room_130',
      word: 'meeting room',
      translation: 'sala de reuniones',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmitɪŋ rum/',
      example: 'We are in the meeting room.',
      exampleTranslation: 'Estamos en la sala de reuniones.',
      status: 'approved',
    },
    {
      id: 'voc_a2_conference-call_131',
      word: 'conference call',
      translation: 'llamada de conferencia',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkɑnfərəns kɔl/',
      example: 'We have a conference call at noon.',
      exampleTranslation: 'Tenemos una llamada de conferencia al mediodía.',
      status: 'approved',
    },
    {
      id: 'voc_a2_presentation_132',
      word: 'presentation',
      translation: 'presentación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌprɛzənˈteɪʃən/',
      example: 'She gave a great presentation.',
      exampleTranslation: 'Ella dio una excelente presentación.',
      status: 'approved',
    },
    {
      id: 'voc_a2_agenda_133',
      word: 'agenda',
      translation: 'agenda/orden del día',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈdʒɛndə/',
      example: 'Let\'s follow the agenda today.',
      exampleTranslation: 'Sigamos la agenda hoy.',
      status: 'approved',
    },
    {
      id: 'voc_a2_minutes_134',
      word: 'minutes (meeting)',
      translation: 'acta (de reunión)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmɪnəts/',
      example: 'Who is taking the minutes?',
      exampleTranslation: '¿Quién está tomando el acta?',
      status: 'approved',
    },
    {
      id: 'voc_a2_memo_135',
      word: 'memo',
      translation: 'memorando',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmɛmoʊ/',
      example: 'I sent a memo to the team.',
      exampleTranslation: 'Envié un memorando al equipo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_report_136',
      word: 'report',
      translation: 'informe',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rɪˈpɔrt/',
      example: 'The report is due on Monday.',
      exampleTranslation: 'El informe debe entregarse el lunes.',
      status: 'approved',
    },
    {
      id: 'voc_a2_spreadsheet_137',
      word: 'spreadsheet',
      translation: 'hoja de cálculo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsprɛdˌʃit/',
      example: 'Open the spreadsheet, please.',
      exampleTranslation: 'Abre la hoja de cálculo, por favor.',
      status: 'approved',
    },
    {
      id: 'voc_a2_attachment_138',
      word: 'attachment',
      translation: 'archivo adjunto',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈtætʃmənt/',
      example: 'I forgot the attachment.',
      exampleTranslation: 'Olvidé el archivo adjunto.',
      status: 'approved',
    },
    {
      id: 'voc_a2_reply_139',
      word: 'reply',
      translation: 'responder',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rɪˈplaɪ/',
      example: 'Please reply to this email.',
      exampleTranslation: 'Por favor responde a este correo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_forward_140',
      word: 'forward (email)',
      translation: 'reenviar',
      partOfSpeech: 'phrasal-verb',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfɔrwərd/',
      example: 'Can you forward me that message?',
      exampleTranslation: '¿Me reenvías ese mensaje?',
      status: 'approved',
    },
    {
      id: 'voc_a2_inbox_141',
      word: 'inbox',
      translation: 'bandeja de entrada',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɪnˌbɑks/',
      example: 'My inbox is full of emails.',
      exampleTranslation: 'Mi bandeja de entrada está llena de correos.',
      status: 'approved',
    },
    {
      id: 'voc_a2_out-of-office_142',
      word: 'out of office',
      translation: 'fuera de la oficina',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/aʊt əv ˈɔfəs/',
      example: 'I\'ll be out of office next week.',
      exampleTranslation: 'Estaré fuera de la oficina la próxima semana.',
      status: 'approved',
    },
    {
      id: 'voc_a2_sick-leave_143',
      word: 'sick leave',
      translation: 'permiso por enfermedad',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/sɪk liv/',
      example: 'She is on sick leave today.',
      exampleTranslation: 'Ella está de permiso por enfermedad hoy.',
      status: 'approved',
    },
    {
      id: 'voc_a2_vacation-days_144',
      word: 'vacation days',
      translation: 'días de vacaciones',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/veɪˈkeɪʃən deɪz/',
      example: 'I have five vacation days left.',
      exampleTranslation: 'Me quedan cinco días de vacaciones.',
      status: 'approved',
    },
    {
      id: 'voc_a2_overtime_145',
      word: 'overtime',
      translation: 'horas extra',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈoʊvərˌtaɪm/',
      example: 'We worked overtime this week.',
      exampleTranslation: 'Trabajamos horas extra esta semana.',
      status: 'approved',
    },
    {
      id: 'voc_a2_part-time_146',
      word: 'part-time',
      translation: 'medio tiempo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpɑrtˈtaɪm/',
      example: 'She has a part-time job.',
      exampleTranslation: 'Ella tiene un trabajo de medio tiempo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_full-time_147',
      word: 'full-time',
      translation: 'tiempo completo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfʊlˌtaɪm/',
      example: 'He works full-time now.',
      exampleTranslation: 'Él trabaja tiempo completo ahora.',
      status: 'approved',
    },
    {
      id: 'voc_a2_remote-work_148',
      word: 'remote work',
      translation: 'trabajo remoto',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rɪˈmoʊt wɜrk/',
      example: 'Remote work is common now.',
      exampleTranslation: 'El trabajo remoto es común ahora.',
      status: 'approved',
    },
    {
      id: 'voc_a2_freelance_149',
      word: 'freelance',
      translation: 'trabajo independiente',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfriˌlæns/',
      example: 'She does freelance writing.',
      exampleTranslation: 'Ella hace escritura independiente.',
      status: 'approved',
    },
    {
      id: 'voc_a2_promotion_150',
      word: 'promotion',
      translation: 'ascenso',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/prəˈmoʊʃən/',
      example: 'He got a promotion last month.',
      exampleTranslation: 'A él le dieron un ascenso el mes pasado.',
      status: 'approved',
    },
    {
      id: 'voc_a2_raise_151',
      word: 'raise (salary)',
      translation: 'aumento de sueldo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/reɪz/',
      example: 'She asked for a raise.',
      exampleTranslation: 'Ella pidió un aumento de sueldo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_resign_152',
      word: 'resign',
      translation: 'renunciar',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rɪˈzaɪn/',
      example: 'He decided to resign.',
      exampleTranslation: 'Él decidió renunciar.',
      status: 'approved',
    },
    {
      id: 'voc_a2_lay-off_153',
      word: 'lay off',
      translation: 'despedir (recorte)',
      partOfSpeech: 'phrasal-verb',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/leɪ ɔf/',
      example: 'The company had to lay off staff.',
      exampleTranslation: 'La empresa tuvo que despedir personal.',
      status: 'approved',
    },
    {
      id: 'voc_a2_retire_154',
      word: 'retire',
      translation: 'jubilarse',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rɪˈtaɪər/',
      example: 'My father will retire next year.',
      exampleTranslation: 'Mi padre se jubilará el próximo año.',
      status: 'approved',
    },
    {
      id: 'voc_a2_teamwork_155',
      word: 'teamwork',
      translation: 'trabajo en equipo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtimˌwɜrk/',
      example: 'Teamwork made the project possible.',
      exampleTranslation: 'El trabajo en equipo hizo posible el proyecto.',
      status: 'approved',
    },
    {
      id: 'voc_a2_brainstorm_156',
      word: 'brainstorm',
      translation: 'lluvia de ideas',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbreɪnˌstɔrm/',
      example: 'We had a brainstorm session.',
      exampleTranslation: 'Tuvimos una sesión de lluvia de ideas.',
      status: 'approved',
    },
    {
      id: 'voc_a2_performance-review_157',
      word: 'performance review',
      translation: 'evaluación de desempeño',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pərˈfɔrməns rɪˈvju/',
      example: 'My performance review is tomorrow.',
      exampleTranslation: 'Mi evaluación de desempeño es mañana.',
      status: 'approved',
    },
    {
      id: 'voc_a2_workload_158',
      word: 'workload',
      translation: 'carga de trabajo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈwɜrkˌloʊd/',
      example: 'My workload is very heavy this month.',
      exampleTranslation: 'Mi carga de trabajo es muy pesada este mes.',
      status: 'approved',
    },
    {
      id: 'voc_a2_multitask_159',
      word: 'multitask',
      translation: 'hacer varias cosas a la vez',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmʌltiˌtæsk/',
      example: 'It\'s hard to multitask at work.',
      exampleTranslation: 'Es difícil hacer varias cosas a la vez en el trabajo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_prioritize_160',
      word: 'prioritize',
      translation: 'priorizar',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/praɪˈɔrəˌtaɪz/',
      example: 'You need to prioritize your tasks.',
      exampleTranslation: 'Necesitas priorizar tus tareas.',
      status: 'approved',
    },
    {
      id: 'voc_a2_negotiation_161',
      word: 'negotiation',
      translation: 'negociación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/nɪˌgoʊʃiˈeɪʃən/',
      example: 'The negotiation took two hours.',
      exampleTranslation: 'La negociación tomó dos horas.',
      status: 'approved',
    },
    {
      id: 'voc_a2_client_162',
      word: 'client',
      translation: 'cliente (negocio)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈklaɪənt/',
      example: 'Our client is happy with the results.',
      exampleTranslation: 'Nuestro cliente está contento con los resultados.',
      status: 'approved',
    },
    {
      id: 'voc_a2_stakeholder_163',
      word: 'stakeholder',
      translation: 'parte interesada',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsteɪkˌhoʊldər/',
      example: 'We informed all the stakeholders.',
      exampleTranslation: 'Informamos a todas las partes interesadas.',
      status: 'approved',
    },
    {
      id: 'voc_a2_quarterly_164',
      word: 'quarterly',
      translation: 'trimestral',
      partOfSpeech: 'adverb',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkwɔrtərli/',
      example: 'We review sales quarterly.',
      exampleTranslation: 'Revisamos las ventas trimestralmente.',
      status: 'approved',
    },
    {
      id: 'voc_a2_annual_165',
      word: 'annual',
      translation: 'anual',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈænjuəl/',
      example: 'We have an annual meeting in June.',
      exampleTranslation: 'Tenemos una reunión anual en junio.',
      status: 'approved',
    },
    {
      id: 'voc_a2_target_166',
      word: 'target (goal)',
      translation: 'meta',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtɑrgɪt/',
      example: 'We reached our sales target.',
      exampleTranslation: 'Alcanzamos nuestra meta de ventas.',
      status: 'approved',
    },
    {
      id: 'voc_a2_achieve_167',
      word: 'achieve',
      translation: 'lograr',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈtʃiv/',
      example: 'She achieved her goals this year.',
      exampleTranslation: 'Ella logró sus metas este año.',
      status: 'approved',
    },
    {
      id: 'voc_a2_accomplish_168',
      word: 'accomplish',
      translation: 'cumplir/lograr',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈkɑmplɪʃ/',
      example: 'We accomplished a lot this week.',
      exampleTranslation: 'Logramos mucho esta semana.',
      status: 'approved',
    },
    {
      id: 'voc_a2_project-manager_169',
      word: 'project manager',
      translation: 'gerente de proyecto',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈprɑdʒɛkt ˈmænɪdʒər/',
      example: 'The project manager called a meeting.',
      exampleTranslation: 'El gerente de proyecto convocó una reunión.',
      status: 'approved',
    },
    {
      id: 'voc_a2_human-resources_170',
      word: 'human resources',
      translation: 'recursos humanos',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈhjumən ˈrisɔrsɪz/',
      example: 'Contact human resources for that.',
      exampleTranslation: 'Contacta a recursos humanos para eso.',
      status: 'approved',
    },
    {
      id: 'voc_a2_headquarters_171',
      word: 'headquarters',
      translation: 'sede central',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈhɛdˌkwɔrtərz/',
      example: 'The headquarters are in New York.',
      exampleTranslation: 'La sede central está en Nueva York.',
      status: 'approved',
    },
    {
      id: 'voc_a2_branch-office_172',
      word: 'branch office',
      translation: 'sucursal',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bræntʃ ˈɔfəs/',
      example: 'There is a branch office downtown.',
      exampleTranslation: 'Hay una sucursal en el centro.',
      status: 'approved',
    },
    {
      id: 'voc_a2_shift_173',
      word: 'shift (work)',
      translation: 'turno',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ʃɪft/',
      example: 'I work the night shift.',
      exampleTranslation: 'Trabajo el turno nocturno.',
      status: 'approved',
    },
    {
      id: 'voc_a2_commute_174',
      word: 'commute',
      translation: 'desplazarse al trabajo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kəˈmjut/',
      example: 'My commute takes forty minutes.',
      exampleTranslation: 'Mi desplazamiento al trabajo toma cuarenta minutos.',
      status: 'approved',
    },
    {
      id: 'voc_a2_paperwork_175',
      word: 'paperwork',
      translation: 'papeleo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpeɪpərˌwɜrk/',
      example: 'I have a lot of paperwork today.',
      exampleTranslation: 'Tengo mucho papeleo hoy.',
      status: 'approved',
    },
    {
      id: 'voc_a2_signature_176',
      word: 'signature',
      translation: 'firma',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsɪgnətʃər/',
      example: 'I need your signature here.',
      exampleTranslation: 'Necesito tu firma aquí.',
      status: 'approved',
    },
    {
      id: 'voc_a2_approval_177',
      word: 'approval',
      translation: 'aprobación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈpruvəl/',
      example: 'We are waiting for approval.',
      exampleTranslation: 'Estamos esperando la aprobación.',
      status: 'approved',
    },
    {
      id: 'voc_a2_policy_178',
      word: 'policy (company)',
      translation: 'política (empresa)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpɑləsi/',
      example: 'Please read the company policy.',
      exampleTranslation: 'Por favor lee la política de la empresa.',
      status: 'approved',
    },
    {
      id: 'voc_a2_training_179',
      word: 'training',
      translation: 'capacitación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtreɪnɪŋ/',
      example: 'New employees need training.',
      exampleTranslation: 'Los nuevos empleados necesitan capacitación.',
      status: 'approved',
    },
    {
      id: 'voc_a2_onboarding_180',
      word: 'onboarding',
      translation: 'proceso de incorporación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɑnˌbɔrdɪŋ/',
      example: 'Onboarding lasts one week.',
      exampleTranslation: 'El proceso de incorporación dura una semana.',
      status: 'approved',
    },
    {
      id: 'voc_a2_networking-event_181',
      word: 'networking event',
      translation: 'evento de networking',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈnɛtˌwɜrkɪŋ ɪˈvɛnt/',
      example: 'I met her at a networking event.',
      exampleTranslation: 'La conocí en un evento de networking.',
      status: 'approved',
    },
  ] as const,
}
