/**
 * A2 Level Content — Week 10
 * Topic: Tecnología intermedia: redes y seguridad
 * Curated from institutional curriculum (Zero AI)
 */
import type { ContentBlock } from '../types'

export const week10: ContentBlock = {
  level: 'A2',
  week: 10,
  topic: 'Tecnología intermedia: redes y seguridad',
  vocabulary: [
    {
      id: 'voc_a2_firewall_457',
      word: 'firewall',
      translation: 'cortafuegos',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfaɪərˌwɔl/',
      example: 'The firewall blocked the attack.',
      exampleTranslation: 'El cortafuegos bloqueó el ataque.',
      status: 'approved',
    },
    {
      id: 'voc_a2_antivirus_458',
      word: 'antivirus',
      translation: 'antivirus',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌæntiˈvaɪrəs/',
      example: 'Install antivirus on your computer.',
      exampleTranslation: 'Instala antivirus en tu computadora.',
      status: 'approved',
    },
    {
      id: 'voc_a2_malware_459',
      word: 'malware',
      translation: 'malware',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmælˌwɛr/',
      example: 'The email contained malware.',
      exampleTranslation: 'El correo contenía malware.',
      status: 'approved',
    },
    {
      id: 'voc_a2_phishing_460',
      word: 'phishing',
      translation: 'phishing (fraude en línea)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfɪʃɪŋ/',
      example: 'Be careful with phishing emails.',
      exampleTranslation: 'Ten cuidado con los correos de phishing.',
      status: 'approved',
    },
    {
      id: 'voc_a2_hacker_461',
      word: 'hacker',
      translation: 'hacker',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈhækər/',
      example: 'A hacker stole the data.',
      exampleTranslation: 'Un hacker robó los datos.',
      status: 'approved',
    },
    {
      id: 'voc_a2_cybersecurity_462',
      word: 'cybersecurity',
      translation: 'ciberseguridad',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌsaɪbərsɪˈkjʊrəti/',
      example: 'The company invests in cybersecurity.',
      exampleTranslation: 'La empresa invierte en ciberseguridad.',
      status: 'approved',
    },
    {
      id: 'voc_a2_encryption_463',
      word: 'encryption',
      translation: 'cifrado',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɛnˈkrɪpʃən/',
      example: 'This app uses strong encryption.',
      exampleTranslation: 'Esta aplicación usa cifrado fuerte.',
      status: 'approved',
    },
    {
      id: 'voc_a2_two-factor-authentic_464',
      word: 'two-factor authentication',
      translation: 'autenticación de dos factores',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtuˌfæktər ɔˌθɛntɪˈkeɪʃən/',
      example: 'Turn on two-factor authentication.',
      exampleTranslation: 'Activa la autenticación de dos factores.',
      status: 'approved',
    },
    {
      id: 'voc_a2_backup_465',
      word: 'backup',
      translation: 'copia de seguridad',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbækˌʌp/',
      example: 'I made a backup of my files.',
      exampleTranslation: 'Hice una copia de seguridad de mis archivos.',
      status: 'approved',
    },
    {
      id: 'voc_a2_cloud-storage_466',
      word: 'cloud storage',
      translation: 'almacenamiento en la nube',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/klaʊd ˈstɔrɪdʒ/',
      example: 'I use cloud storage for photos.',
      exampleTranslation: 'Uso almacenamiento en la nube para las fotos.',
      status: 'approved',
    },
    {
      id: 'voc_a2_server_467',
      word: 'server',
      translation: 'servidor',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsɜrvər/',
      example: 'The server is down right now.',
      exampleTranslation: 'El servidor está caído en este momento.',
      status: 'approved',
    },
    {
      id: 'voc_a2_database_468',
      word: 'database',
      translation: 'base de datos',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdeɪtəˌbeɪs/',
      example: 'We updated the customer database.',
      exampleTranslation: 'Actualizamos la base de datos de clientes.',
      status: 'approved',
    },
    {
      id: 'voc_a2_browser_469',
      word: 'browser',
      translation: 'navegador',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbraʊzər/',
      example: 'Open a new browser tab.',
      exampleTranslation: 'Abre una nueva pestaña del navegador.',
      status: 'approved',
    },
    {
      id: 'voc_a2_cookie_470',
      word: 'cookie (internet)',
      translation: 'cookie (internet)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkʊki/',
      example: 'The site asks to accept cookies.',
      exampleTranslation: 'El sitio pide aceptar cookies.',
      status: 'approved',
    },
    {
      id: 'voc_a2_cache_471',
      word: 'cache',
      translation: 'caché',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kæʃ/',
      example: 'Clear your browser cache.',
      exampleTranslation: 'Limpia la caché de tu navegador.',
      status: 'approved',
    },
    {
      id: 'voc_a2_bandwidth_472',
      word: 'bandwidth',
      translation: 'ancho de banda',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbændˌwɪdθ/',
      example: 'We need more bandwidth for video calls.',
      exampleTranslation: 'Necesitamos más ancho de banda para videollamadas.',
      status: 'approved',
    },
    {
      id: 'voc_a2_router_473',
      word: 'router',
      translation: 'router',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈraʊtər/',
      example: 'Restart the router if it\'s slow.',
      exampleTranslation: 'Reinicia el router si está lento.',
      status: 'approved',
    },
    {
      id: 'voc_a2_bluetooth_474',
      word: 'bluetooth',
      translation: 'bluetooth',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbluˌtuθ/',
      example: 'Connect your headphones via bluetooth.',
      exampleTranslation: 'Conecta tus audífonos por bluetooth.',
      status: 'approved',
    },
    {
      id: 'voc_a2_hotspot_475',
      word: 'hotspot',
      translation: 'punto de acceso',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈhɑtˌspɑt/',
      example: 'I used my phone as a hotspot.',
      exampleTranslation: 'Usé mi teléfono como punto de acceso.',
      status: 'approved',
    },
    {
      id: 'voc_a2_streaming_476',
      word: 'streaming',
      translation: 'transmisión en línea',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈstrimɪŋ/',
      example: 'We watched the game via streaming.',
      exampleTranslation: 'Vimos el partido por transmisión en línea.',
      status: 'approved',
    },
    {
      id: 'voc_a2_notification_477',
      word: 'notification',
      translation: 'notificación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌnoʊtəfɪˈkeɪʃən/',
      example: 'I got a notification about the meeting.',
      exampleTranslation: 'Recibí una notificación sobre la reunión.',
      status: 'approved',
    },
    {
      id: 'voc_a2_settings_478',
      word: 'settings',
      translation: 'configuración',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsɛtɪŋz/',
      example: 'Check your privacy settings.',
      exampleTranslation: 'Revisa tu configuración de privacidad.',
      status: 'approved',
    },
    {
      id: 'voc_a2_factory-reset_479',
      word: 'factory reset',
      translation: 'restablecer de fábrica',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfæktəri ˈrisɛt/',
      example: 'I did a factory reset on my phone.',
      exampleTranslation: 'Le hice un restablecimiento de fábrica a mi teléfono.',
      status: 'approved',
    },
    {
      id: 'voc_a2_screenshot_480',
      word: 'screenshot',
      translation: 'captura de pantalla',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈskrinˌʃɑt/',
      example: 'Can you send me a screenshot?',
      exampleTranslation: '¿Me envías una captura de pantalla?',
      status: 'approved',
    },
    {
      id: 'voc_a2_hashtag_481',
      word: 'hashtag',
      translation: 'hashtag',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈhæʃˌtæg/',
      example: 'The hashtag went viral.',
      exampleTranslation: 'El hashtag se volvió viral.',
      status: 'approved',
    },
    {
      id: 'voc_a2_algorithm_482',
      word: 'algorithm',
      translation: 'algoritmo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈælgəˌrɪðəm/',
      example: 'The algorithm suggests videos for you.',
      exampleTranslation: 'El algoritmo te sugiere videos.',
      status: 'approved',
    },
    {
      id: 'voc_a2_artificial-intellige_483',
      word: 'artificial intelligence',
      translation: 'inteligencia artificial',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌɑrtəˈfɪʃəl ɪnˈtɛlədʒəns/',
      example: 'Artificial intelligence is changing many jobs.',
      exampleTranslation: 'La inteligencia artificial está cambiando muchos trabajos.',
      status: 'approved',
    },
    {
      id: 'voc_a2_virtual-reality_484',
      word: 'virtual reality',
      translation: 'realidad virtual',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈvɜrtʃuəl riˈæləti/',
      example: 'We tried virtual reality at the fair.',
      exampleTranslation: 'Probamos realidad virtual en la feria.',
      status: 'approved',
    },
    {
      id: 'voc_a2_augmented-reality_485',
      word: 'augmented reality',
      translation: 'realidad aumentada',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɔgˈmɛntɪd riˈæləti/',
      example: 'The app uses augmented reality.',
      exampleTranslation: 'La aplicación usa realidad aumentada.',
      status: 'approved',
    },
    {
      id: 'voc_a2_e-commerce_486',
      word: 'e-commerce',
      translation: 'comercio electrónico',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈiˌkɑmərs/',
      example: 'E-commerce has grown a lot.',
      exampleTranslation: 'El comercio electrónico ha crecido mucho.',
      status: 'approved',
    },
    {
      id: 'voc_a2_online-banking_487',
      word: 'online banking',
      translation: 'banca en línea',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɔnˌlaɪn ˈbæŋkɪŋ/',
      example: 'I use online banking every week.',
      exampleTranslation: 'Uso la banca en línea cada semana.',
      status: 'approved',
    },
    {
      id: 'voc_a2_digital-signature_488',
      word: 'digital signature',
      translation: 'firma digital',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdɪdʒɪtəl ˈsɪgnətʃər/',
      example: 'Sign the document with a digital signature.',
      exampleTranslation: 'Firma el documento con una firma digital.',
      status: 'approved',
    },
    {
      id: 'voc_a2_biometric_489',
      word: 'biometric',
      translation: 'biométrico',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌbaɪoʊˈmɛtrɪk/',
      example: 'The phone uses biometric security.',
      exampleTranslation: 'El teléfono usa seguridad biométrica.',
      status: 'approved',
    },
    {
      id: 'voc_a2_fingerprint-scanner_490',
      word: 'fingerprint scanner',
      translation: 'lector de huellas',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfɪŋgərˌprɪnt ˈskænər/',
      example: 'Unlock your phone with the fingerprint scanner.',
      exampleTranslation: 'Desbloquea tu teléfono con el lector de huellas.',
      status: 'approved',
    },
    {
      id: 'voc_a2_facial-recognition_491',
      word: 'facial recognition',
      translation: 'reconocimiento facial',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfeɪʃəl ˌrɛkəgˈnɪʃən/',
      example: 'The airport uses facial recognition.',
      exampleTranslation: 'El aeropuerto usa reconocimiento facial.',
      status: 'approved',
    },
    {
      id: 'voc_a2_smart-home_492',
      word: 'smart home',
      translation: 'hogar inteligente',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/smɑrt hoʊm/',
      example: 'We installed a smart home system.',
      exampleTranslation: 'Instalamos un sistema de hogar inteligente.',
      status: 'approved',
    },
    {
      id: 'voc_a2_wearable-device_493',
      word: 'wearable device',
      translation: 'dispositivo portátil',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈwɛrəbəl dɪˈvaɪs/',
      example: 'She wears a wearable device to track sleep.',
      exampleTranslation: 'Ella usa un dispositivo portátil para monitorear el sueño.',
      status: 'approved',
    },
    {
      id: 'voc_a2_drone_494',
      word: 'drone',
      translation: 'dron',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/droʊn/',
      example: 'He flew a drone over the beach.',
      exampleTranslation: 'Él voló un dron sobre la playa.',
      status: 'approved',
    },
    {
      id: 'voc_a2_d-printing_495',
      word: '3D printing',
      translation: 'impresión 3D',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈθriˈdi ˈprɪntɪŋ/',
      example: '3D printing is used in medicine now.',
      exampleTranslation: 'La impresión 3D se usa en medicina ahora.',
      status: 'approved',
    },
  ] as const,
}
