/**
 * A2 Level Content — Week 01
 * Topic: Compras y devoluciones
 * Curated from institutional curriculum (Zero AI)
 */
import type { ContentBlock } from '../types'

export const week01: ContentBlock = {
  level: 'A2',
  week: 1,
  topic: 'Compras y devoluciones',
  vocabulary: [
    {
      id: 'voc_a2_refund_001',
      word: 'refund',
      translation: 'reembolso',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈriˌfʌnd/',
      example: 'I want a refund for this item.',
      exampleTranslation: 'Quiero un reembolso por este artículo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_exchange_002',
      word: 'exchange (product)',
      translation: 'cambio (producto)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪksˈtʃeɪndʒ/',
      example: 'Can I get an exchange instead?',
      exampleTranslation: '¿Puedo hacer un cambio en su lugar?',
      status: 'approved',
    },
    {
      id: 'voc_a2_return_003',
      word: 'return (product)',
      translation: 'devolución',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rɪˈtɜrn/',
      example: 'The store accepted my return.',
      exampleTranslation: 'La tienda aceptó mi devolución.',
      status: 'approved',
    },
    {
      id: 'voc_a2_warranty_004',
      word: 'warranty',
      translation: 'garantía',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈwɔrənti/',
      example: 'This laptop has a two-year warranty.',
      exampleTranslation: 'Esta laptop tiene garantía de dos años.',
      status: 'approved',
    },
    {
      id: 'voc_a2_guarantee_005',
      word: 'guarantee',
      translation: 'garantía (verbo/promesa)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌgɛrənˈti/',
      example: 'We offer a money-back guarantee.',
      exampleTranslation: 'Ofrecemos garantía de devolución de dinero.',
      status: 'approved',
    },
    {
      id: 'voc_a2_complaint_006',
      word: 'complaint',
      translation: 'queja',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kəmˈpleɪnt/',
      example: 'I filed a complaint about the service.',
      exampleTranslation: 'Presenté una queja sobre el servicio.',
      status: 'approved',
    },
    {
      id: 'voc_a2_customer-service_007',
      word: 'customer service',
      translation: 'servicio al cliente',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkʌstəmər ˈsɜrvɪs/',
      example: 'Customer service was very helpful.',
      exampleTranslation: 'El servicio al cliente fue muy útil.',
      status: 'approved',
    },
    {
      id: 'voc_a2_fitting-room_008',
      word: 'fitting room',
      translation: 'probador',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfɪtɪŋ rum/',
      example: 'The fitting room is over there.',
      exampleTranslation: 'El probador está allá.',
      status: 'approved',
    },
    {
      id: 'voc_a2_barcode_009',
      word: 'barcode',
      translation: 'código de barras',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbɑrˌkoʊd/',
      example: 'Scan the barcode, please.',
      exampleTranslation: 'Escanea el código de barras, por favor.',
      status: 'approved',
    },
    {
      id: 'voc_a2_discount-code_010',
      word: 'discount code',
      translation: 'código de descuento',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdɪskaʊnt koʊd/',
      example: 'Do you have a discount code?',
      exampleTranslation: '¿Tienes un código de descuento?',
      status: 'approved',
    },
    {
      id: 'voc_a2_clearance_011',
      word: 'clearance',
      translation: 'liquidación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈklɪrəns/',
      example: 'These shoes are on clearance.',
      exampleTranslation: 'Estos zapatos están en liquidación.',
      status: 'approved',
    },
    {
      id: 'voc_a2_bargain_012',
      word: 'bargain',
      translation: 'ganga',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbɑrgɪn/',
      example: 'This jacket was a real bargain.',
      exampleTranslation: 'Esta chaqueta fue una verdadera ganga.',
      status: 'approved',
    },
    {
      id: 'voc_a2_brand-new_013',
      word: 'brand new',
      translation: 'totalmente nuevo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/brænd nu/',
      example: 'My phone is brand new.',
      exampleTranslation: 'Mi teléfono es totalmente nuevo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_secondhand_014',
      word: 'secondhand',
      translation: 'de segunda mano',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsɛkəndˌhænd/',
      example: 'I bought a secondhand bike.',
      exampleTranslation: 'Compré una bicicleta de segunda mano.',
      status: 'approved',
    },
    {
      id: 'voc_a2_quality-control_015',
      word: 'quality control',
      translation: 'control de calidad',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkwɑləti kənˈtroʊl/',
      example: 'Quality control checks every product.',
      exampleTranslation: 'El control de calidad revisa cada producto.',
      status: 'approved',
    },
    {
      id: 'voc_a2_damaged_016',
      word: 'damaged',
      translation: 'dañado',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdæmɪdʒd/',
      example: 'The box arrived damaged.',
      exampleTranslation: 'La caja llegó dañada.',
      status: 'approved',
    },
    {
      id: 'voc_a2_broken_017',
      word: 'broken (thing)',
      translation: 'roto',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbroʊkən/',
      example: 'The screen is broken.',
      exampleTranslation: 'La pantalla está rota.',
      status: 'approved',
    },
    {
      id: 'voc_a2_defective_018',
      word: 'defective',
      translation: 'defectuoso',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dɪˈfɛktɪv/',
      example: 'This charger is defective.',
      exampleTranslation: 'Este cargador es defectuoso.',
      status: 'approved',
    },
    {
      id: 'voc_a2_missing-part_019',
      word: 'missing part',
      translation: 'pieza faltante',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmɪsɪŋ pɑrt/',
      example: 'The box has a missing part.',
      exampleTranslation: 'A la caja le falta una pieza.',
      status: 'approved',
    },
    {
      id: 'voc_a2_instructions-manual_020',
      word: 'instructions manual',
      translation: 'manual de instrucciones',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪnˈstrʌkʃənz ˈmænjuəl/',
      example: 'Read the instructions manual first.',
      exampleTranslation: 'Lee el manual de instrucciones primero.',
      status: 'approved',
    },
    {
      id: 'voc_a2_assemble_021',
      word: 'assemble',
      translation: 'ensamblar',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈsɛmbəl/',
      example: 'We assembled the furniture together.',
      exampleTranslation: 'Ensamblamos el mueble juntos.',
      status: 'approved',
    },
    {
      id: 'voc_a2_gift-receipt_022',
      word: 'gift receipt',
      translation: 'recibo de regalo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/gɪft rɪˈsit/',
      example: 'Would you like a gift receipt?',
      exampleTranslation: '¿Quieres un recibo de regalo?',
      status: 'approved',
    },
    {
      id: 'voc_a2_loyalty-card_023',
      word: 'loyalty card',
      translation: 'tarjeta de fidelidad',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈlɔɪəlti kɑrd/',
      example: 'Scan your loyalty card, please.',
      exampleTranslation: 'Escanea tu tarjeta de fidelidad, por favor.',
      status: 'approved',
    },
    {
      id: 'voc_a2_membership_024',
      word: 'membership',
      translation: 'membresía',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmɛmbərˌʃɪp/',
      example: 'I renewed my gym membership.',
      exampleTranslation: 'Renové mi membresía del gimnasio.',
      status: 'approved',
    },
    {
      id: 'voc_a2_catalog_025',
      word: 'catalog',
      translation: 'catálogo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkætəˌlɔg/',
      example: 'Look in the catalog for prices.',
      exampleTranslation: 'Busca los precios en el catálogo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_order-online_026',
      word: 'order online',
      translation: 'pedir en línea',
      partOfSpeech: 'phrasal-verb',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɔrdər ˈɔnˌlaɪn/',
      example: 'I usually order online.',
      exampleTranslation: 'Normalmente pido en línea.',
      status: 'approved',
    },
    {
      id: 'voc_a2_shipping_027',
      word: 'shipping',
      translation: 'envío',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈʃɪpɪŋ/',
      example: 'Shipping takes five days.',
      exampleTranslation: 'El envío tarda cinco días.',
      status: 'approved',
    },
    {
      id: 'voc_a2_delivery_028',
      word: 'delivery',
      translation: 'entrega',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dɪˈlɪvəri/',
      example: 'The delivery arrived on time.',
      exampleTranslation: 'La entrega llegó a tiempo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_package-parcel_029',
      word: 'package / parcel',
      translation: 'paquete',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpækɪdʒ/',
      example: 'I\'m waiting for a package.',
      exampleTranslation: 'Estoy esperando un paquete.',
      status: 'approved',
    },
    {
      id: 'voc_a2_tracking-number_030',
      word: 'tracking number',
      translation: 'número de rastreo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtrækɪŋ ˈnʌmbər/',
      example: 'Here is your tracking number.',
      exampleTranslation: 'Aquí está tu número de rastreo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_courier_031',
      word: 'courier',
      translation: 'mensajero',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkʊriər/',
      example: 'The courier left it at the door.',
      exampleTranslation: 'El mensajero lo dejó en la puerta.',
      status: 'approved',
    },
    {
      id: 'voc_a2_express-delivery_032',
      word: 'express delivery',
      translation: 'envío exprés',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪkˈsprɛs dɪˈlɪvəri/',
      example: 'I paid for express delivery.',
      exampleTranslation: 'Pagué por envío exprés.',
      status: 'approved',
    },
    {
      id: 'voc_a2_standard-delivery_033',
      word: 'standard delivery',
      translation: 'envío estándar',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈstændərd dɪˈlɪvəri/',
      example: 'Standard delivery is free.',
      exampleTranslation: 'El envío estándar es gratis.',
      status: 'approved',
    },
    {
      id: 'voc_a2_out-of-stock_034',
      word: 'out of stock',
      translation: 'agotado',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/aʊt əv stɑk/',
      example: 'That size is out of stock.',
      exampleTranslation: 'Esa talla está agotada.',
      status: 'approved',
    },
    {
      id: 'voc_a2_in-stock_035',
      word: 'in stock',
      translation: 'en existencia',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪn stɑk/',
      example: 'The blue one is in stock.',
      exampleTranslation: 'El azul está disponible en existencia.',
      status: 'approved',
    },
    {
      id: 'voc_a2_available_036',
      word: 'available',
      translation: 'disponible',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈveɪləbəl/',
      example: 'Is this color available?',
      exampleTranslation: '¿Está disponible este color?',
      status: 'approved',
    },
    {
      id: 'voc_a2_unavailable_037',
      word: 'unavailable',
      translation: 'no disponible',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌʌnəˈveɪləbəl/',
      example: 'The item is currently unavailable.',
      exampleTranslation: 'El artículo no está disponible actualmente.',
      status: 'approved',
    },
    {
      id: 'voc_a2_color-option_038',
      word: 'color option',
      translation: 'opción de color',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkʌlər ˈɑpʃən/',
      example: 'There is only one color option.',
      exampleTranslation: 'Solo hay una opción de color.',
      status: 'approved',
    },
    {
      id: 'voc_a2_model_039',
      word: 'model (product)',
      translation: 'modelo (producto)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmɑdəl/',
      example: 'This is the newest model.',
      exampleTranslation: 'Este es el modelo más reciente.',
      status: 'approved',
    },
    {
      id: 'voc_a2_version_040',
      word: 'version',
      translation: 'versión',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈvɜrʒən/',
      example: 'I have an old version of this app.',
      exampleTranslation: 'Tengo una versión vieja de esta aplicación.',
      status: 'approved',
    },
    {
      id: 'voc_a2_upgrade_041',
      word: 'upgrade',
      translation: 'mejora/actualización',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈʌpˌgreɪd/',
      example: 'I bought an upgrade for my phone.',
      exampleTranslation: 'Compré una mejora para mi teléfono.',
      status: 'approved',
    },
    {
      id: 'voc_a2_downgrade_042',
      word: 'downgrade',
      translation: 'reducir (plan/versión)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdaʊnˌgreɪd/',
      example: 'I decided to downgrade my plan.',
      exampleTranslation: 'Decidí bajar mi plan.',
      status: 'approved',
    },
    {
      id: 'voc_a2_subscription_043',
      word: 'subscription',
      translation: 'suscripción',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/səbˈskrɪpʃən/',
      example: 'I canceled my subscription.',
      exampleTranslation: 'Cancelé mi suscripción.',
      status: 'approved',
    },
    {
      id: 'voc_a2_cancel_044',
      word: 'cancel',
      translation: 'cancelar',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkænsəl/',
      example: 'Can I cancel my order?',
      exampleTranslation: '¿Puedo cancelar mi pedido?',
      status: 'approved',
    },
    {
      id: 'voc_a2_renew_045',
      word: 'renew',
      translation: 'renovar',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rɪˈnu/',
      example: 'I need to renew my membership.',
      exampleTranslation: 'Necesito renovar mi membresía.',
      status: 'approved',
    },
    {
      id: 'voc_a2_invoice_046',
      word: 'invoice',
      translation: 'factura',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɪnvɔɪs/',
      example: 'Please send me the invoice.',
      exampleTranslation: 'Por favor envíame la factura.',
      status: 'approved',
    },
    {
      id: 'voc_a2_payment-method_047',
      word: 'payment method',
      translation: 'método de pago',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpeɪmənt ˈmɛθəd/',
      example: 'Choose your payment method.',
      exampleTranslation: 'Elige tu método de pago.',
      status: 'approved',
    },
    {
      id: 'voc_a2_installment_048',
      word: 'installment',
      translation: 'cuota/pago a plazos',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪnˈstɔlmənt/',
      example: 'I paid in three installments.',
      exampleTranslation: 'Pagué en tres cuotas.',
      status: 'approved',
    },
    {
      id: 'voc_a2_negotiate_049',
      word: 'negotiate',
      translation: 'negociar',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/nɪˈgoʊʃiˌeɪt/',
      example: 'We negotiated a better price.',
      exampleTranslation: 'Negociamos un mejor precio.',
      status: 'approved',
    },
    {
      id: 'voc_a2_haggle_050',
      word: 'haggle',
      translation: 'regatear',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈhægəl/',
      example: 'People haggle a lot at this market.',
      exampleTranslation: 'La gente regatea mucho en este mercado.',
      status: 'approved',
    },
    {
      id: 'voc_a2_overpriced_051',
      word: 'overpriced',
      translation: 'sobrevalorado',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌoʊvərˈpraɪst/',
      example: 'This restaurant is overpriced.',
      exampleTranslation: 'Este restaurante está sobrevalorado.',
      status: 'approved',
    },
    {
      id: 'voc_a2_affordable_052',
      word: 'affordable',
      translation: 'asequible',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈfɔrdəbəl/',
      example: 'I found an affordable hotel.',
      exampleTranslation: 'Encontré un hotel asequible.',
      status: 'approved',
    },
    {
      id: 'voc_a2_worth-it_053',
      word: 'worth it',
      translation: 'que vale la pena',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/wɜrθ ɪt/',
      example: 'The trip was worth it.',
      exampleTranslation: 'El viaje valió la pena.',
      status: 'approved',
    },
    {
      id: 'voc_a2_satisfied_054',
      word: 'satisfied',
      translation: 'satisfecho',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsætɪsˌfaɪd/',
      example: 'I am satisfied with my purchase.',
      exampleTranslation: 'Estoy satisfecho con mi compra.',
      status: 'approved',
    },
    {
      id: 'voc_a2_dissatisfied_055',
      word: 'dissatisfied',
      translation: 'insatisfecho',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dɪsˈsætɪsˌfaɪd/',
      example: 'She was dissatisfied with the service.',
      exampleTranslation: 'Ella estaba insatisfecha con el servicio.',
      status: 'approved',
    },
    {
      id: 'voc_a2_store-credit_056',
      word: 'store credit',
      translation: 'crédito de tienda',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/stɔr ˈkrɛdɪt/',
      example: 'They gave me store credit.',
      exampleTranslation: 'Me dieron crédito de tienda.',
      status: 'approved',
    },
    {
      id: 'voc_a2_gift-card_057',
      word: 'gift card',
      translation: 'tarjeta de regalo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/gɪft kɑrd/',
      example: 'I received a gift card for my birthday.',
      exampleTranslation: 'Recibí una tarjeta de regalo por mi cumpleaños.',
      status: 'approved',
    },
    {
      id: 'voc_a2_coupon_058',
      word: 'coupon',
      translation: 'cupón',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkupɑn/',
      example: 'Do you have a coupon?',
      exampleTranslation: '¿Tienes un cupón?',
      status: 'approved',
    },
    {
      id: 'voc_a2_promo-code_059',
      word: 'promo code',
      translation: 'código promocional',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈproʊmoʊ koʊd/',
      example: 'Enter the promo code at checkout.',
      exampleTranslation: 'Ingresa el código promocional al pagar.',
      status: 'approved',
    },
    {
      id: 'voc_a2_limited-offer_060',
      word: 'limited offer',
      translation: 'oferta limitada',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈlɪmɪtɪd ˈɔfər/',
      example: 'This is a limited offer.',
      exampleTranslation: 'Esta es una oferta limitada.',
      status: 'approved',
    },
    {
      id: 'voc_a2_best-seller_061',
      word: 'best seller',
      translation: 'más vendido',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bɛst ˈsɛlər/',
      example: 'This book is a best seller.',
      exampleTranslation: 'Este libro es el más vendido.',
      status: 'approved',
    },
    {
      id: 'voc_a2_customer-review_062',
      word: 'customer review',
      translation: 'reseña de cliente',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkʌstəmər rɪˈvju/',
      example: 'Read the customer reviews first.',
      exampleTranslation: 'Lee las reseñas de clientes primero.',
      status: 'approved',
    },
    {
      id: 'voc_a2_rating_063',
      word: 'rating',
      translation: 'calificación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈreɪtɪŋ/',
      example: 'This product has a high rating.',
      exampleTranslation: 'Este producto tiene una calificación alta.',
      status: 'approved',
    },
    {
      id: 'voc_a2_feedback_064',
      word: 'feedback',
      translation: 'retroalimentación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 1,
      topic: 'compras-y-devolucion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfidˌbæk/',
      example: 'Thank you for your feedback.',
      exampleTranslation: 'Gracias por tu retroalimentación.',
      status: 'approved',
    },
  ] as const,
}
