/**
 * A2 Level Content — Week 10
 * Topic: Tecnología intermedia: redes y seguridad
 * Curated from institutional curriculum (Zero AI)
 */
import type { ContentBlock } from '../types'

export const week10: ContentBlock = {
  level: 'A2',
  week: 10,
  topic: 'Tecnología intermedia: redes y seguridad',
  vocabulary: [
    {
      id: 'voc_a2_firewall_457',
      word: 'firewall',
      translation: 'cortafuegos',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_antivirus_458',
      word: 'antivirus',
      translation: 'antivirus',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_malware_459',
      word: 'malware',
      translation: 'malware',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_phishing_460',
      word: 'phishing',
      translation: 'phishing (fraude en línea)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_hacker_461',
      word: 'hacker',
      translation: 'hacker',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_cybersecurity_462',
      word: 'cybersecurity',
      translation: 'ciberseguridad',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_encryption_463',
      word: 'encryption',
      translation: 'cifrado',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_two-factor-authentic_464',
      word: 'two-factor authentication',
      translation: 'autenticación de dos factores',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_backup_465',
      word: 'backup',
      translation: 'copia de seguridad',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_cloud-storage_466',
      word: 'cloud storage',
      translation: 'almacenamiento en la nube',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_server_467',
      word: 'server',
      translation: 'servidor',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_database_468',
      word: 'database',
      translation: 'base de datos',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_browser_469',
      word: 'browser',
      translation: 'navegador',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_cookie_470',
      word: 'cookie (internet)',
      translation: 'cookie (internet)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_cache_471',
      word: 'cache',
      translation: 'caché',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_bandwidth_472',
      word: 'bandwidth',
      translation: 'ancho de banda',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_router_473',
      word: 'router',
      translation: 'router',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_bluetooth_474',
      word: 'bluetooth',
      translation: 'bluetooth',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_hotspot_475',
      word: 'hotspot',
      translation: 'punto de acceso',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_streaming_476',
      word: 'streaming',
      translation: 'transmisión en línea',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_notification_477',
      word: 'notification',
      translation: 'notificación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_settings_478',
      word: 'settings',
      translation: 'configuración',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_factory-reset_479',
      word: 'factory reset',
      translation: 'restablecer de fábrica',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_screenshot_480',
      word: 'screenshot',
      translation: 'captura de pantalla',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_hashtag_481',
      word: 'hashtag',
      translation: 'hashtag',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_algorithm_482',
      word: 'algorithm',
      translation: 'algoritmo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_artificial-intellige_483',
      word: 'artificial intelligence',
      translation: 'inteligencia artificial',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_virtual-reality_484',
      word: 'virtual reality',
      translation: 'realidad virtual',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_augmented-reality_485',
      word: 'augmented reality',
      translation: 'realidad aumentada',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_e-commerce_486',
      word: 'e-commerce',
      translation: 'comercio electrónico',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_online-banking_487',
      word: 'online banking',
      translation: 'banca en línea',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_digital-signature_488',
      word: 'digital signature',
      translation: 'firma digital',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_biometric_489',
      word: 'biometric',
      translation: 'biométrico',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_fingerprint-scanner_490',
      word: 'fingerprint scanner',
      translation: 'lector de huellas',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_facial-recognition_491',
      word: 'facial recognition',
      translation: 'reconocimiento facial',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_smart-home_492',
      word: 'smart home',
      translation: 'hogar inteligente',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_wearable-device_493',
      word: 'wearable device',
      translation: 'dispositivo portátil',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_drone_494',
      word: 'drone',
      translation: 'dron',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_d-printing_495',
      word: '3D printing',
      translation: 'impresión 3D',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 10,
      topic: 'tecnolog-a-intermedi',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
  ] as const,
}
