/**
 * A2 Level Content — Week 05
 * Topic: Conectores narrativos para contar historias
 * Curated from institutional curriculum (Zero AI)
 */
import type { ContentBlock } from '../types'

export const week05: ContentBlock = {
  level: 'A2',
  week: 5,
  topic: 'Conectores narrativos para contar historias',
  vocabulary: [
    {
      id: 'voc_a2_once-upon-a-time_241',
      word: 'once upon a time',
      translation: 'érase una vez',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_meanwhile_242',
      word: 'meanwhile',
      translation: 'mientras tanto',
      partOfSpeech: 'adverb',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_afterward_243',
      word: 'afterward',
      translation: 'después/luego',
      partOfSpeech: 'adverb',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_eventually_244',
      word: 'eventually',
      translation: 'finalmente/con el tiempo',
      partOfSpeech: 'adverb',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_in-the-end_245',
      word: 'in the end',
      translation: 'al final',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_at-first_246',
      word: 'at first',
      translation: 'al principio',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_later-on_247',
      word: 'later on',
      translation: 'más adelante',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_as-soon-as_248',
      word: 'as soon as',
      translation: 'tan pronto como',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_by-the-time_249',
      word: 'by the time',
      translation: 'para cuando',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_used-to_250',
      word: 'used to',
      translation: 'solía',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_previously_251',
      word: 'previously',
      translation: 'previamente',
      partOfSpeech: 'adverb',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_formerly_252',
      word: 'formerly',
      translation: 'anteriormente',
      partOfSpeech: 'adverb',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_ever-since_253',
      word: 'ever since',
      translation: 'desde entonces',
      partOfSpeech: 'adverb',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_from-then-on_254',
      word: 'from then on',
      translation: 'desde ese momento',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_at-that-moment_255',
      word: 'at that moment',
      translation: 'en ese momento',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_right-after_256',
      word: 'right after',
      translation: 'justo después',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_shortly-after_257',
      word: 'shortly after',
      translation: 'poco después',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_in-the-meantime_258',
      word: 'in the meantime',
      translation: 'mientras tanto',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_all-of-a-sudden_259',
      word: 'all of a sudden',
      translation: 'de repente',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_little-by-little_260',
      word: 'little by little',
      translation: 'poco a poco',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_one-day_261',
      word: 'one day',
      translation: 'un día',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_years-ago_262',
      word: 'years ago',
      translation: 'hace años',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_back-then_263',
      word: 'back then',
      translation: 'en aquel entonces',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_during-that-time_264',
      word: 'during that time',
      translation: 'durante ese tiempo',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_at-the-same-time_265',
      word: 'at the same time',
      translation: 'al mismo tiempo',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_in-those-days_266',
      word: 'in those days',
      translation: 'en aquellos días',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_as-a-result_267',
      word: 'as a result',
      translation: 'como resultado',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_consequently_268',
      word: 'consequently',
      translation: 'en consecuencia',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_thus_269',
      word: 'thus',
      translation: 'así/por lo tanto',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_for-this-reason_270',
      word: 'for this reason',
      translation: 'por esta razón',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_due-to_271',
      word: 'due to',
      translation: 'debido a',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_because-of_272',
      word: 'because of',
      translation: 'a causa de',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_thats-why_273',
      word: "that's why",
      translation: 'por eso',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_in-contrast_274',
      word: 'in contrast',
      translation: 'en contraste',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_instead_275',
      word: 'instead',
      translation: 'en cambio',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_nevertheless_276',
      word: 'nevertheless',
      translation: 'sin embargo/no obstante',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_nonetheless_277',
      word: 'nonetheless',
      translation: 'no obstante',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_moreover_278',
      word: 'moreover',
      translation: 'además',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_furthermore_279',
      word: 'furthermore',
      translation: 'además/asimismo',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_in-addition_280',
      word: 'in addition',
      translation: 'adicionalmente',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_besides_281',
      word: 'besides',
      translation: 'además',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_apart-from_282',
      word: 'apart from',
      translation: 'aparte de',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_in-conclusion_283',
      word: 'in conclusion',
      translation: 'en conclusión',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_to-sum-up_284',
      word: 'to sum up',
      translation: 'en resumen',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_overall_285',
      word: 'overall',
      translation: 'en general',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_in-general_286',
      word: 'in general',
      translation: 'en general',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_such-as_287',
      word: 'such as',
      translation: 'tal como',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_in-particular_288',
      word: 'in particular',
      translation: 'en particular',
      partOfSpeech: 'conjunction',
      level: 'A2',
      week: 5,
      topic: 'conectores-narrativo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
  ] as const,
}
