/**
 * A2 Level Content — Week 09
 * Topic: Relaciones y emociones complejas
 * Curated from institutional curriculum (Zero AI)
 */
import type { ContentBlock } from '../types'

export const week09: ContentBlock = {
  level: 'A2',
  week: 9,
  topic: 'Relaciones y emociones complejas',
  vocabulary: [
    {
      id: 'voc_a2_trust-issues_413',
      word: 'trust issues',
      translation: 'problemas de confianza',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/trʌst ˈɪʃuz/',
      example: 'He has trust issues after the breakup.',
      exampleTranslation: 'Él tiene problemas de confianza después de la ruptura.',
      status: 'approved',
    },
    {
      id: 'voc_a2_commitment_414',
      word: 'commitment',
      translation: 'compromiso',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kəˈmɪtmənt/',
      example: 'Marriage requires real commitment.',
      exampleTranslation: 'El matrimonio requiere compromiso real.',
      status: 'approved',
    },
    {
      id: 'voc_a2_breakup_415',
      word: 'breakup',
      translation: 'ruptura',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbreɪˌkʌp/',
      example: 'Their breakup was difficult for both.',
      exampleTranslation: 'Su ruptura fue difícil para ambos.',
      status: 'approved',
    },
    {
      id: 'voc_a2_reconciliation_416',
      word: 'reconciliation',
      translation: 'reconciliación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌrɛkənˌsɪliˈeɪʃən/',
      example: 'Their reconciliation surprised everyone.',
      exampleTranslation: 'Su reconciliación sorprendió a todos.',
      status: 'approved',
    },
    {
      id: 'voc_a2_betrayal_417',
      word: 'betrayal',
      translation: 'traición',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bɪˈtreɪəl/',
      example: 'She never forgot his betrayal.',
      exampleTranslation: 'Ella nunca olvidó su traición.',
      status: 'approved',
    },
    {
      id: 'voc_a2_forgiveness_418',
      word: 'forgiveness',
      translation: 'perdón',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fərˈgɪvnəs/',
      example: 'Forgiveness takes time.',
      exampleTranslation: 'El perdón toma tiempo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_empathy_419',
      word: 'empathy',
      translation: 'empatía',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɛmpəθi/',
      example: 'She showed great empathy toward him.',
      exampleTranslation: 'Ella mostró gran empatía hacia él.',
      status: 'approved',
    },
    {
      id: 'voc_a2_sympathy_420',
      word: 'sympathy',
      translation: 'compasión/comprensión',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsɪmpəθi/',
      example: 'I have sympathy for her situation.',
      exampleTranslation: 'Siento comprensión por su situación.',
      status: 'approved',
    },
    {
      id: 'voc_a2_compassion_421',
      word: 'compassion',
      translation: 'compasión',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kəmˈpæʃən/',
      example: 'He treated the patients with compassion.',
      exampleTranslation: 'Él trató a los pacientes con compasión.',
      status: 'approved',
    },
    {
      id: 'voc_a2_resentment_422',
      word: 'resentment',
      translation: 'resentimiento',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rɪˈzɛntmənt/',
      example: 'There was resentment between the brothers.',
      exampleTranslation: 'Había resentimiento entre los hermanos.',
      status: 'approved',
    },
    {
      id: 'voc_a2_heartbreak_423',
      word: 'heartbreak',
      translation: 'desamor',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈhɑrtˌbreɪk/',
      example: 'She wrote a song about heartbreak.',
      exampleTranslation: 'Ella escribió una canción sobre el desamor.',
      status: 'approved',
    },
    {
      id: 'voc_a2_infatuation_424',
      word: 'infatuation',
      translation: 'enamoramiento pasajero',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪnˌfætʃuˈeɪʃən/',
      example: 'It was just an infatuation, not love.',
      exampleTranslation: 'Era solo un enamoramiento pasajero, no amor.',
      status: 'approved',
    },
    {
      id: 'voc_a2_attraction_425',
      word: 'attraction',
      translation: 'atracción',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈtrækʃən/',
      example: 'There was instant attraction between them.',
      exampleTranslation: 'Hubo atracción instantánea entre ellos.',
      status: 'approved',
    },
    {
      id: 'voc_a2_compatibility_426',
      word: 'compatibility',
      translation: 'compatibilidad',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kəmˌpætəˈbɪləti/',
      example: 'Compatibility is important in a relationship.',
      exampleTranslation: 'La compatibilidad es importante en una relación.',
      status: 'approved',
    },
    {
      id: 'voc_a2_conflict-resolution_427',
      word: 'conflict resolution',
      translation: 'resolución de conflictos',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkɑnflɪkt ˌrɛzəˈluʃən/',
      example: 'We practiced conflict resolution at work.',
      exampleTranslation: 'Practicamos la resolución de conflictos en el trabajo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_compromise_428',
      word: 'compromise',
      translation: 'compromiso/acuerdo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkɑmprəˌmaɪz/',
      example: 'They reached a compromise.',
      exampleTranslation: 'Llegaron a un acuerdo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_mutual-respect_429',
      word: 'mutual respect',
      translation: 'respeto mutuo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmjutʃuəl rɪˈspɛkt/',
      example: 'Their friendship is based on mutual respect.',
      exampleTranslation: 'Su amistad se basa en respeto mutuo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_boundaries_430',
      word: 'boundaries',
      translation: 'límites (emocionales)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbaʊndəriz/',
      example: 'It\'s healthy to set boundaries.',
      exampleTranslation: 'Es saludable poner límites.',
      status: 'approved',
    },
    {
      id: 'voc_a2_codependency_431',
      word: 'codependency',
      translation: 'codependencia',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌkoʊdɪˈpɛndənsi/',
      example: 'The therapist talked about codependency.',
      exampleTranslation: 'El terapeuta habló sobre la codependencia.',
      status: 'approved',
    },
    {
      id: 'voc_a2_long-distance-relati_432',
      word: 'long-distance relationship',
      translation: 'relación a distancia',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌlɔŋˈdɪstəns rɪˈleɪʃənˌʃɪp/',
      example: 'They are in a long-distance relationship.',
      exampleTranslation: 'Están en una relación a distancia.',
      status: 'approved',
    },
    {
      id: 'voc_a2_soulmate_433',
      word: 'soulmate',
      translation: 'alma gemela',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsoʊlˌmeɪt/',
      example: 'She believes he is her soulmate.',
      exampleTranslation: 'Ella cree que él es su alma gemela.',
      status: 'approved',
    },
    {
      id: 'voc_a2_companionship_434',
      word: 'companionship',
      translation: 'compañerismo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kəmˈpænjənˌʃɪp/',
      example: 'Pets provide great companionship.',
      exampleTranslation: 'Las mascotas brindan un gran compañerismo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_intimacy_435',
      word: 'intimacy',
      translation: 'intimidad',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɪntəməsi/',
      example: 'Intimacy grows with time and trust.',
      exampleTranslation: 'La intimidad crece con el tiempo y la confianza.',
      status: 'approved',
    },
    {
      id: 'voc_a2_vulnerability_436',
      word: 'vulnerability',
      translation: 'vulnerabilidad',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌvʌlnərəˈbɪləti/',
      example: 'Sharing feelings takes vulnerability.',
      exampleTranslation: 'Compartir sentimientos requiere vulnerabilidad.',
      status: 'approved',
    },
    {
      id: 'voc_a2_self-esteem_437',
      word: 'self-esteem',
      translation: 'autoestima',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌsɛlfɪˈstim/',
      example: 'Exercise can improve self-esteem.',
      exampleTranslation: 'El ejercicio puede mejorar la autoestima.',
      status: 'approved',
    },
    {
      id: 'voc_a2_self-doubt_438',
      word: 'self-doubt',
      translation: 'inseguridad/duda de uno mismo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌsɛlfˈdaʊt/',
      example: 'She struggled with self-doubt before the interview.',
      exampleTranslation: 'Ella luchó con inseguridad antes de la entrevista.',
      status: 'approved',
    },
    {
      id: 'voc_a2_insecurity_439',
      word: 'insecurity',
      translation: 'inseguridad',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌɪnsɪˈkjʊrəti/',
      example: 'His insecurity affected the relationship.',
      exampleTranslation: 'Su inseguridad afectó la relación.',
      status: 'approved',
    },
    {
      id: 'voc_a2_overwhelmed_440',
      word: 'overwhelmed',
      translation: 'abrumado',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌoʊvərˈwɛlmd/',
      example: 'She felt overwhelmed by all the work.',
      exampleTranslation: 'Ella se sintió abrumada por todo el trabajo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_burnout_441',
      word: 'burnout',
      translation: 'agotamiento (laboral/emocional)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbɜrnˌaʊt/',
      example: 'He is suffering from burnout.',
      exampleTranslation: 'Él está sufriendo de agotamiento.',
      status: 'approved',
    },
    {
      id: 'voc_a2_frustration_442',
      word: 'frustration',
      translation: 'frustración',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/frʌˈstreɪʃən/',
      example: 'I could see her frustration.',
      exampleTranslation: 'Pude ver su frustración.',
      status: 'approved',
    },
    {
      id: 'voc_a2_irritation_443',
      word: 'irritation',
      translation: 'irritación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌɪrɪˈteɪʃən/',
      example: 'There was a bit of irritation in his voice.',
      exampleTranslation: 'Había un poco de irritación en su voz.',
      status: 'approved',
    },
    {
      id: 'voc_a2_resentful_444',
      word: 'resentful',
      translation: 'resentido',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rɪˈzɛntfəl/',
      example: 'She felt resentful after the argument.',
      exampleTranslation: 'Ella se sintió resentida después de la discusión.',
      status: 'approved',
    },
    {
      id: 'voc_a2_heartfelt_445',
      word: 'heartfelt',
      translation: 'sincero/de corazón',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈhɑrtˌfɛlt/',
      example: 'He wrote a heartfelt letter.',
      exampleTranslation: 'Él escribió una carta sincera.',
      status: 'approved',
    },
    {
      id: 'voc_a2_overjoyed_446',
      word: 'overjoyed',
      translation: 'muy feliz',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌoʊvərˈdʒɔɪd/',
      example: 'We were overjoyed at the news.',
      exampleTranslation: 'Estábamos muy felices con la noticia.',
      status: 'approved',
    },
    {
      id: 'voc_a2_devastated_447',
      word: 'devastated',
      translation: 'devastado',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdɛvəˌsteɪtɪd/',
      example: 'She was devastated after the loss.',
      exampleTranslation: 'Ella quedó devastada después de la pérdida.',
      status: 'approved',
    },
    {
      id: 'voc_a2_humiliated_448',
      word: 'humiliated',
      translation: 'humillado',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/hjuˈmɪliˌeɪtɪd/',
      example: 'He felt humiliated in front of everyone.',
      exampleTranslation: 'Él se sintió humillado frente a todos.',
      status: 'approved',
    },
    {
      id: 'voc_a2_ashamed_449',
      word: 'ashamed',
      translation: 'avergonzado',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈʃeɪmd/',
      example: 'I felt ashamed of my mistake.',
      exampleTranslation: 'Me sentí avergonzado de mi error.',
      status: 'approved',
    },
    {
      id: 'voc_a2_guilty_450',
      word: 'guilty',
      translation: 'culpable',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈgɪlti/',
      example: 'She felt guilty for forgetting his birthday.',
      exampleTranslation: 'Ella se sintió culpable por olvidar su cumpleaños.',
      status: 'approved',
    },
    {
      id: 'voc_a2_remorse_451',
      word: 'remorse',
      translation: 'remordimiento',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rɪˈmɔrs/',
      example: 'He showed real remorse.',
      exampleTranslation: 'Él mostró un remordimiento real.',
      status: 'approved',
    },
    {
      id: 'voc_a2_regret_452',
      word: 'regret',
      translation: 'arrepentimiento',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rɪˈgrɛt/',
      example: 'I have no regret about my decision.',
      exampleTranslation: 'No tengo arrepentimiento por mi decisión.',
      status: 'approved',
    },
    {
      id: 'voc_a2_longing_453',
      word: 'longing',
      translation: 'anhelo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈlɔŋɪŋ/',
      example: 'She felt a longing for her hometown.',
      exampleTranslation: 'Ella sintió un anhelo por su ciudad natal.',
      status: 'approved',
    },
    {
      id: 'voc_a2_nostalgia_454',
      word: 'nostalgia',
      translation: 'nostalgia',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/nɑˈstældʒə/',
      example: 'The song brought back nostalgia.',
      exampleTranslation: 'La canción trajo nostalgia.',
      status: 'approved',
    },
    {
      id: 'voc_a2_contentment_455',
      word: 'contentment',
      translation: 'satisfacción/contento',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kənˈtɛntmənt/',
      example: 'He felt contentment after the trip.',
      exampleTranslation: 'Él sintió satisfacción después del viaje.',
      status: 'approved',
    },
    {
      id: 'voc_a2_fulfillment_456',
      word: 'fulfillment',
      translation: 'realización personal',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 9,
      topic: 'relaciones-y-emocion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fʊlˈfɪlmənt/',
      example: 'Her job gives her real fulfillment.',
      exampleTranslation: 'Su trabajo le da una verdadera realización.',
      status: 'approved',
    },
  ] as const,
}
