/**
 * A2 Level Content — Week 12
 * Topic: Mantenimiento del hogar y reparaciones
 * Curated from institutional curriculum (Zero AI)
 */
import type { ContentBlock } from '../types'

export const week12: ContentBlock = {
  level: 'A2',
  week: 12,
  topic: 'Mantenimiento del hogar y reparaciones',
  vocabulary: [
    {
      id: 'voc_a2_repair_555',
      word: 'repair',
      translation: 'reparar',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rɪˈpɛr/',
      example: 'We need to repair the roof.',
      exampleTranslation: 'Necesitamos reparar el techo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_leak_556',
      word: 'leak',
      translation: 'fuga',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/lik/',
      example: 'There is a leak in the kitchen.',
      exampleTranslation: 'Hay una fuga en la cocina.',
      status: 'approved',
    },
    {
      id: 'voc_a2_clog_557',
      word: 'clog',
      translation: 'atascar/atasco',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/klɑg/',
      example: 'The sink is clogged again.',
      exampleTranslation: 'El fregadero está atascado otra vez.',
      status: 'approved',
    },
    {
      id: 'voc_a2_broken-pipe_558',
      word: 'broken pipe',
      translation: 'tubería rota',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbroʊkən paɪp/',
      example: 'A broken pipe flooded the bathroom.',
      exampleTranslation: 'Una tubería rota inundó el baño.',
      status: 'approved',
    },
    {
      id: 'voc_a2_renovate_559',
      word: 'renovate',
      translation: 'renovar',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈrɛnəˌveɪt/',
      example: 'We plan to renovate the kitchen.',
      exampleTranslation: 'Planeamos renovar la cocina.',
      status: 'approved',
    },
    {
      id: 'voc_a2_remodel_560',
      word: 'remodel',
      translation: 'remodelar',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/riˈmɑdəl/',
      example: 'They remodeled the whole house.',
      exampleTranslation: 'Ellos remodelaron toda la casa.',
      status: 'approved',
    },
    {
      id: 'voc_a2_diy_561',
      word: 'DIY (do it yourself)',
      translation: 'hazlo tú mismo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌdiˌaɪˈwaɪ/',
      example: 'This is a fun DIY project.',
      exampleTranslation: 'Este es un divertido proyecto de hazlo tú mismo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_blueprint_562',
      word: 'blueprint',
      translation: 'plano',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbluˌprɪnt/',
      example: 'The architect showed us the blueprint.',
      exampleTranslation: 'El arquitecto nos mostró el plano.',
      status: 'approved',
    },
    {
      id: 'voc_a2_contractor_563',
      word: 'contractor',
      translation: 'contratista',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkɑnˌtræktər/',
      example: 'We hired a good contractor.',
      exampleTranslation: 'Contratamos a un buen contratista.',
      status: 'approved',
    },
    {
      id: 'voc_a2_handyman_564',
      word: 'handyman',
      translation: 'manitas/reparador',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈhændiˌmæn/',
      example: 'The handyman fixed the door.',
      exampleTranslation: 'El manitas arregló la puerta.',
      status: 'approved',
    },
    {
      id: 'voc_a2_maintenance_565',
      word: 'maintenance',
      translation: 'mantenimiento',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmeɪntənəns/',
      example: 'The building needs maintenance.',
      exampleTranslation: 'El edificio necesita mantenimiento.',
      status: 'approved',
    },
    {
      id: 'voc_a2_inspection_566',
      word: 'inspection',
      translation: 'inspección',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪnˈspɛkʃən/',
      example: 'We scheduled an inspection.',
      exampleTranslation: 'Programamos una inspección.',
      status: 'approved',
    },
    {
      id: 'voc_a2_electrical-outlet_567',
      word: 'electrical outlet',
      translation: 'tomacorriente',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪˈlɛktrɪkəl ˈaʊtlɛt/',
      example: 'This electrical outlet doesn\'t work.',
      exampleTranslation: 'Este tomacorriente no funciona.',
      status: 'approved',
    },
    {
      id: 'voc_a2_circuit-breaker_568',
      word: 'circuit breaker',
      translation: 'interruptor automático',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsɜrkət ˈbreɪkər/',
      example: 'The circuit breaker tripped.',
      exampleTranslation: 'El interruptor automático se disparó.',
      status: 'approved',
    },
    {
      id: 'voc_a2_fuse_569',
      word: 'fuse',
      translation: 'fusible',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fjuz/',
      example: 'A fuse blew during the storm.',
      exampleTranslation: 'Un fusible se quemó durante la tormenta.',
      status: 'approved',
    },
    {
      id: 'voc_a2_wiring_570',
      word: 'wiring',
      translation: 'cableado',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈwaɪrɪŋ/',
      example: 'The wiring in this house is old.',
      exampleTranslation: 'El cableado de esta casa es viejo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_plumbing_571',
      word: 'plumbing',
      translation: 'plomería',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈplʌmɪŋ/',
      example: 'The plumbing needs to be checked.',
      exampleTranslation: 'La plomería necesita revisarse.',
      status: 'approved',
    },
    {
      id: 'voc_a2_drain_572',
      word: 'drain',
      translation: 'desagüe',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dreɪn/',
      example: 'The drain is clogged with hair.',
      exampleTranslation: 'El desagüe está tapado con pelo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_faucet-tap_573',
      word: 'faucet / tap',
      translation: 'grifo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfɔsət/',
      example: 'The faucet is dripping.',
      exampleTranslation: 'El grifo está goteando.',
      status: 'approved',
    },
    {
      id: 'voc_a2_thermostat_574',
      word: 'thermostat',
      translation: 'termostato',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈθɜrməˌstæt/',
      example: 'Set the thermostat to 22 degrees.',
      exampleTranslation: 'Ajusta el termostato a 22 grados.',
      status: 'approved',
    },
    {
      id: 'voc_a2_insulation_575',
      word: 'insulation',
      translation: 'aislamiento',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌɪnsəˈleɪʃən/',
      example: 'We added insulation in the attic.',
      exampleTranslation: 'Agregamos aislamiento en el ático.',
      status: 'approved',
    },
    {
      id: 'voc_a2_ventilation_576',
      word: 'ventilation',
      translation: 'ventilación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌvɛntəˈleɪʃən/',
      example: 'The bathroom needs better ventilation.',
      exampleTranslation: 'El baño necesita mejor ventilación.',
      status: 'approved',
    },
    {
      id: 'voc_a2_mold_577',
      word: 'mold',
      translation: 'moho',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/moʊld/',
      example: 'There is mold on the wall.',
      exampleTranslation: 'Hay moho en la pared.',
      status: 'approved',
    },
    {
      id: 'voc_a2_pest-control_578',
      word: 'pest control',
      translation: 'control de plagas',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pɛst kənˈtroʊl/',
      example: 'We called a pest control company.',
      exampleTranslation: 'Llamamos a una empresa de control de plagas.',
      status: 'approved',
    },
    {
      id: 'voc_a2_termite_579',
      word: 'termite',
      translation: 'termita',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtɜrmaɪt/',
      example: 'Termites damaged the wooden floor.',
      exampleTranslation: 'Las termitas dañaron el piso de madera.',
      status: 'approved',
    },
    {
      id: 'voc_a2_rust_580',
      word: 'rust',
      translation: 'óxido',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rʌst/',
      example: 'The gate has some rust.',
      exampleTranslation: 'El portón tiene un poco de óxido.',
      status: 'approved',
    },
    {
      id: 'voc_a2_crack_581',
      word: 'crack (wall)',
      translation: 'grieta',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kræk/',
      example: 'There\'s a crack in the wall.',
      exampleTranslation: 'Hay una grieta en la pared.',
      status: 'approved',
    },
    {
      id: 'voc_a2_dent_582',
      word: 'dent',
      translation: 'abolladura',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dɛnt/',
      example: 'The car has a small dent.',
      exampleTranslation: 'El carro tiene una pequeña abolladura.',
      status: 'approved',
    },
    {
      id: 'voc_a2_scratch_583',
      word: 'scratch',
      translation: 'rayón',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/skrætʃ/',
      example: 'There\'s a scratch on the table.',
      exampleTranslation: 'Hay un rayón en la mesa.',
      status: 'approved',
    },
    {
      id: 'voc_a2_stain_584',
      word: 'stain',
      translation: 'mancha',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/steɪn/',
      example: 'This stain won\'t come out.',
      exampleTranslation: 'Esta mancha no sale.',
      status: 'approved',
    },
    {
      id: 'voc_a2_paint-roller_585',
      word: 'paint roller',
      translation: 'rodillo de pintura',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/peɪnt ˈroʊlər/',
      example: 'Use a paint roller for the walls.',
      exampleTranslation: 'Usa un rodillo de pintura para las paredes.',
      status: 'approved',
    },
    {
      id: 'voc_a2_sandpaper_586',
      word: 'sandpaper',
      translation: 'papel de lija',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsændˌpeɪpər/',
      example: 'Smooth the wood with sandpaper.',
      exampleTranslation: 'Alisa la madera con papel de lija.',
      status: 'approved',
    },
    {
      id: 'voc_a2_nail-gun_587',
      word: 'nail gun',
      translation: 'pistola de clavos',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/neɪl gʌn/',
      example: 'He used a nail gun for the fence.',
      exampleTranslation: 'Él usó una pistola de clavos para la cerca.',
      status: 'approved',
    },
    {
      id: 'voc_a2_power-drill_588',
      word: 'power drill',
      translation: 'taladro eléctrico',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpaʊər drɪl/',
      example: 'I borrowed a power drill.',
      exampleTranslation: 'Pedí prestado un taladro eléctrico.',
      status: 'approved',
    },
    {
      id: 'voc_a2_toolbox_589',
      word: 'toolbox',
      translation: 'caja de herramientas',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtulˌbɑks/',
      example: 'The toolbox is in the garage.',
      exampleTranslation: 'La caja de herramientas está en el garaje.',
      status: 'approved',
    },
    {
      id: 'voc_a2_measuring-tape_590',
      word: 'measuring tape',
      translation: 'cinta métrica',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmɛʒərɪŋ teɪp/',
      example: 'Use the measuring tape for the window.',
      exampleTranslation: 'Usa la cinta métrica para la ventana.',
      status: 'approved',
    },
    {
      id: 'voc_a2_level_591',
      word: 'level (tool)',
      translation: 'nivel (herramienta)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈlɛvəl/',
      example: 'Check it with a level.',
      exampleTranslation: 'Revísalo con un nivel.',
      status: 'approved',
    },
    {
      id: 'voc_a2_wrench_592',
      word: 'wrench',
      translation: 'llave inglesa',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rɛntʃ/',
      example: 'Pass me the wrench, please.',
      exampleTranslation: 'Pásame la llave inglesa, por favor.',
      status: 'approved',
    },
    {
      id: 'voc_a2_pliers_593',
      word: 'pliers',
      translation: 'alicates',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈplaɪərz/',
      example: 'I need pliers for this wire.',
      exampleTranslation: 'Necesito alicates para este cable.',
      status: 'approved',
    },
    {
      id: 'voc_a2_safety-goggles_594',
      word: 'safety goggles',
      translation: 'gafas de seguridad',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈseɪfti ˈgɑgəlz/',
      example: 'Wear safety goggles when you cut wood.',
      exampleTranslation: 'Usa gafas de seguridad cuando cortes madera.',
      status: 'approved',
    },
    {
      id: 'voc_a2_estimate_595',
      word: 'estimate (cost)',
      translation: 'presupuesto/estimado',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɛstəmət/',
      example: 'We got an estimate from the plumber.',
      exampleTranslation: 'Recibimos un presupuesto del plomero.',
      status: 'approved',
    },
    {
      id: 'voc_a2_quote_596',
      word: 'quote (price)',
      translation: 'cotización',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kwoʊt/',
      example: 'The quote seems reasonable.',
      exampleTranslation: 'La cotización parece razonable.',
      status: 'approved',
    },
    {
      id: 'voc_a2_appliance-repair_597',
      word: 'appliance repair',
      translation: 'reparación de electrodomésticos',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈplaɪəns rɪˈpɛr/',
      example: 'We called for appliance repair.',
      exampleTranslation: 'Llamamos para reparación de electrodomésticos.',
      status: 'approved',
    },
    {
      id: 'voc_a2_gutter_598',
      word: 'gutter',
      translation: 'canaleta',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈgʌtər/',
      example: 'Clean the gutters before winter.',
      exampleTranslation: 'Limpia las canaletas antes del invierno.',
      status: 'approved',
    },
    {
      id: 'voc_a2_chimney_599',
      word: 'chimney',
      translation: 'chimenea',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtʃɪmni/',
      example: 'The chimney needs cleaning.',
      exampleTranslation: 'La chimenea necesita limpieza.',
      status: 'approved',
    },
    {
      id: 'voc_a2_foundation_600',
      word: 'foundation (house)',
      translation: 'cimientos',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/faʊnˈdeɪʃən/',
      example: 'There\'s a crack in the foundation.',
      exampleTranslation: 'Hay una grieta en los cimientos.',
      status: 'approved',
    },
    {
      id: 'voc_a2_structural-damage_601',
      word: 'structural damage',
      translation: 'daño estructural',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈstrʌktʃərəl ˈdæmɪdʒ/',
      example: 'The storm caused structural damage.',
      exampleTranslation: 'La tormenta causó daño estructural.',
      status: 'approved',
    },
    {
      id: 'voc_a2_home-inspection_602',
      word: 'home inspection',
      translation: 'inspección de vivienda',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/hoʊm ɪnˈspɛkʃən/',
      example: 'We scheduled a home inspection.',
      exampleTranslation: 'Programamos una inspección de vivienda.',
      status: 'approved',
    },
    {
      id: 'voc_a2_recyclable_603',
      word: 'recyclable',
      translation: 'reciclable',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/riˈsaɪkləbəl/',
      example: 'This packaging is recyclable.',
      exampleTranslation: 'Este empaque es reciclable.',
      status: 'approved',
    },
    {
      id: 'voc_a2_waste-disposal_604',
      word: 'waste disposal',
      translation: 'eliminación de residuos',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 12,
      topic: 'mantenimiento-del-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/weɪst dɪˈspoʊzəl/',
      example: 'Follow the city\'s waste disposal rules.',
      exampleTranslation: 'Sigue las reglas de eliminación de residuos de la ciudad.',
      status: 'approved',
    },
  ] as const,
}
