/**
 * A2 Level Content — Week 03
 * Topic: Trabajo y oficina
 * Curated from institutional curriculum (Zero AI)
 */
import type { ContentBlock } from '../types'

export const week03: ContentBlock = {
  level: 'A2',
  week: 3,
  topic: 'Trabajo y oficina',
  vocabulary: [
    {
      id: 'voc_a2_resume-cv_121',
      word: 'resume / CV',
      translation: 'currículum',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_cover-letter_122',
      word: 'cover letter',
      translation: 'carta de presentación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_job-interview_123',
      word: 'job interview',
      translation: 'entrevista de trabajo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_job-offer_124',
      word: 'job offer',
      translation: 'oferta de trabajo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_position_125',
      word: 'position',
      translation: 'puesto',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_department_126',
      word: 'department',
      translation: 'departamento',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_colleague_127',
      word: 'colleague',
      translation: 'colega',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_supervisor_128',
      word: 'supervisor',
      translation: 'supervisor',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_deadline_129',
      word: 'deadline',
      translation: 'fecha límite',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_meeting-room_130',
      word: 'meeting room',
      translation: 'sala de reuniones',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_conference-call_131',
      word: 'conference call',
      translation: 'llamada de conferencia',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_presentation_132',
      word: 'presentation',
      translation: 'presentación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_agenda_133',
      word: 'agenda',
      translation: 'agenda/orden del día',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_minutes_134',
      word: 'minutes (meeting)',
      translation: 'acta (de reunión)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_memo_135',
      word: 'memo',
      translation: 'memorando',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_report_136',
      word: 'report',
      translation: 'informe',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_spreadsheet_137',
      word: 'spreadsheet',
      translation: 'hoja de cálculo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_attachment_138',
      word: 'attachment',
      translation: 'archivo adjunto',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_reply_139',
      word: 'reply',
      translation: 'responder',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_forward_140',
      word: 'forward (email)',
      translation: 'reenviar',
      partOfSpeech: 'phrasal-verb',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_inbox_141',
      word: 'inbox',
      translation: 'bandeja de entrada',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_out-of-office_142',
      word: 'out of office',
      translation: 'fuera de la oficina',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_sick-leave_143',
      word: 'sick leave',
      translation: 'permiso por enfermedad',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_vacation-days_144',
      word: 'vacation days',
      translation: 'días de vacaciones',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_overtime_145',
      word: 'overtime',
      translation: 'horas extra',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_part-time_146',
      word: 'part-time',
      translation: 'medio tiempo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_full-time_147',
      word: 'full-time',
      translation: 'tiempo completo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_remote-work_148',
      word: 'remote work',
      translation: 'trabajo remoto',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_freelance_149',
      word: 'freelance',
      translation: 'trabajo independiente',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_promotion_150',
      word: 'promotion',
      translation: 'ascenso',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_raise_151',
      word: 'raise (salary)',
      translation: 'aumento de sueldo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_resign_152',
      word: 'resign',
      translation: 'renunciar',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_lay-off_153',
      word: 'lay off',
      translation: 'despedir (recorte)',
      partOfSpeech: 'phrasal-verb',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_retire_154',
      word: 'retire',
      translation: 'jubilarse',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_teamwork_155',
      word: 'teamwork',
      translation: 'trabajo en equipo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_brainstorm_156',
      word: 'brainstorm',
      translation: 'lluvia de ideas',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_performance-review_157',
      word: 'performance review',
      translation: 'evaluación de desempeño',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_workload_158',
      word: 'workload',
      translation: 'carga de trabajo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_multitask_159',
      word: 'multitask',
      translation: 'hacer varias cosas a la vez',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_prioritize_160',
      word: 'prioritize',
      translation: 'priorizar',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_negotiation_161',
      word: 'negotiation',
      translation: 'negociación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_client_162',
      word: 'client',
      translation: 'cliente (negocio)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_stakeholder_163',
      word: 'stakeholder',
      translation: 'parte interesada',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_quarterly_164',
      word: 'quarterly',
      translation: 'trimestral',
      partOfSpeech: 'adverb',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_annual_165',
      word: 'annual',
      translation: 'anual',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_target_166',
      word: 'target (goal)',
      translation: 'meta',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_achieve_167',
      word: 'achieve',
      translation: 'lograr',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_accomplish_168',
      word: 'accomplish',
      translation: 'cumplir/lograr',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_project-manager_169',
      word: 'project manager',
      translation: 'gerente de proyecto',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_human-resources_170',
      word: 'human resources',
      translation: 'recursos humanos',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_headquarters_171',
      word: 'headquarters',
      translation: 'sede central',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_branch-office_172',
      word: 'branch office',
      translation: 'sucursal',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_shift_173',
      word: 'shift (work)',
      translation: 'turno',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_commute_174',
      word: 'commute',
      translation: 'desplazarse al trabajo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_paperwork_175',
      word: 'paperwork',
      translation: 'papeleo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_signature_176',
      word: 'signature',
      translation: 'firma',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_approval_177',
      word: 'approval',
      translation: 'aprobación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_policy_178',
      word: 'policy (company)',
      translation: 'política (empresa)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_training_179',
      word: 'training',
      translation: 'capacitación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_onboarding_180',
      word: 'onboarding',
      translation: 'proceso de incorporación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_networking-event_181',
      word: 'networking event',
      translation: 'evento de networking',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 3,
      topic: 'trabajo-y-oficina',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
  ] as const,
}
