/**
 * A2 Level Content — Week 08
 * Topic: Educación y estudios superiores
 * Curated from institutional curriculum (Zero AI)
 */
import type { ContentBlock } from '../types'

export const week08: ContentBlock = {
  level: 'A2',
  week: 8,
  topic: 'Educación y estudios superiores',
  vocabulary: [
    {
      id: 'voc_a2_enroll_367',
      word: 'enroll',
      translation: 'inscribirse',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪnˈroʊl/',
      example: 'I want to enroll in this course.',
      exampleTranslation: 'Quiero inscribirme en este curso.',
      status: 'approved',
    },
    {
      id: 'voc_a2_tuition_368',
      word: 'tuition',
      translation: 'matrícula (costo)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tuˈɪʃən/',
      example: 'Tuition increased this year.',
      exampleTranslation: 'La matrícula subió este año.',
      status: 'approved',
    },
    {
      id: 'voc_a2_scholarship_369',
      word: 'scholarship',
      translation: 'beca',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈskɑlərˌʃɪp/',
      example: 'She received a full scholarship.',
      exampleTranslation: 'Ella recibió una beca completa.',
      status: 'approved',
    },
    {
      id: 'voc_a2_semester_370',
      word: 'semester',
      translation: 'semestre',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/səˈmɛstər/',
      example: 'The semester ends in May.',
      exampleTranslation: 'El semestre termina en mayo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_syllabus_371',
      word: 'syllabus',
      translation: 'programa del curso',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsɪləbəs/',
      example: 'Check the syllabus for the dates.',
      exampleTranslation: 'Revisa el programa del curso para las fechas.',
      status: 'approved',
    },
    {
      id: 'voc_a2_lecture_372',
      word: 'lecture',
      translation: 'clase magistral',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈlɛktʃər/',
      example: 'The lecture lasted two hours.',
      exampleTranslation: 'La clase magistral duró dos horas.',
      status: 'approved',
    },
    {
      id: 'voc_a2_seminar_373',
      word: 'seminar',
      translation: 'seminario',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsɛməˌnɑr/',
      example: 'We attended a seminar on writing.',
      exampleTranslation: 'Asistimos a un seminario de escritura.',
      status: 'approved',
    },
    {
      id: 'voc_a2_thesis_374',
      word: 'thesis',
      translation: 'tesis',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈθisɪs/',
      example: 'She is writing her thesis.',
      exampleTranslation: 'Ella está escribiendo su tesis.',
      status: 'approved',
    },
    {
      id: 'voc_a2_dissertation_375',
      word: 'dissertation',
      translation: 'tesis doctoral',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌdɪsərˈteɪʃən/',
      example: 'His dissertation took two years.',
      exampleTranslation: 'Su tesis doctoral tomó dos años.',
      status: 'approved',
    },
    {
      id: 'voc_a2_major_376',
      word: 'major (field of study)',
      translation: 'carrera principal',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmeɪdʒər/',
      example: 'My major is computer science.',
      exampleTranslation: 'Mi carrera principal es ciencias de la computación.',
      status: 'approved',
    },
    {
      id: 'voc_a2_minor_377',
      word: 'minor (field of study)',
      translation: 'especialización secundaria',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmaɪnər/',
      example: 'She has a minor in art.',
      exampleTranslation: 'Ella tiene una especialización secundaria en arte.',
      status: 'approved',
    },
    {
      id: 'voc_a2_gpa_378',
      word: 'GPA',
      translation: 'promedio académico',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌdʒiˌpiˈeɪ/',
      example: 'His GPA is very high.',
      exampleTranslation: 'Su promedio académico es muy alto.',
      status: 'approved',
    },
    {
      id: 'voc_a2_transcript_379',
      word: 'transcript',
      translation: 'historial académico',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtrænˌskrɪpt/',
      example: 'I need my official transcript.',
      exampleTranslation: 'Necesito mi historial académico oficial.',
      status: 'approved',
    },
    {
      id: 'voc_a2_diploma_380',
      word: 'diploma',
      translation: 'diploma',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dɪˈploʊmə/',
      example: 'He received his diploma last week.',
      exampleTranslation: 'Él recibió su diploma la semana pasada.',
      status: 'approved',
    },
    {
      id: 'voc_a2_certificate_381',
      word: 'certificate',
      translation: 'certificado',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/sərˈtɪfɪkɪt/',
      example: 'She got a certificate in marketing.',
      exampleTranslation: 'Ella obtuvo un certificado en marketing.',
      status: 'approved',
    },
    {
      id: 'voc_a2_campus_382',
      word: 'campus',
      translation: 'campus',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkæmpəs/',
      example: 'The campus is very large.',
      exampleTranslation: 'El campus es muy grande.',
      status: 'approved',
    },
    {
      id: 'voc_a2_dormitory_383',
      word: 'dormitory',
      translation: 'residencia estudiantil',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdɔrməˌtɔri/',
      example: 'He lives in a dormitory.',
      exampleTranslation: 'Él vive en una residencia estudiantil.',
      status: 'approved',
    },
    {
      id: 'voc_a2_faculty_384',
      word: 'faculty',
      translation: 'facultad/cuerpo docente',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfækəlti/',
      example: 'The faculty meets every Friday.',
      exampleTranslation: 'El cuerpo docente se reúne todos los viernes.',
      status: 'approved',
    },
    {
      id: 'voc_a2_professor_385',
      word: 'professor',
      translation: 'profesor universitario',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/prəˈfɛsər/',
      example: 'My professor is very demanding.',
      exampleTranslation: 'Mi profesor es muy exigente.',
      status: 'approved',
    },
    {
      id: 'voc_a2_academic-advisor_386',
      word: 'academic advisor',
      translation: 'asesor académico',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌækəˈdɛmɪk ædˈvaɪzər/',
      example: 'Talk to your academic advisor.',
      exampleTranslation: 'Habla con tu asesor académico.',
      status: 'approved',
    },
    {
      id: 'voc_a2_plagiarism_387',
      word: 'plagiarism',
      translation: 'plagio',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpleɪdʒəˌrɪzəm/',
      example: 'Plagiarism is not allowed.',
      exampleTranslation: 'El plagio no está permitido.',
      status: 'approved',
    },
    {
      id: 'voc_a2_assignment_388',
      word: 'assignment',
      translation: 'tarea/trabajo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈsaɪnmənt/',
      example: 'The assignment is due tomorrow.',
      exampleTranslation: 'La tarea se entrega mañana.',
      status: 'approved',
    },
    {
      id: 'voc_a2_essay_389',
      word: 'essay',
      translation: 'ensayo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɛˌseɪ/',
      example: 'I wrote an essay about climate change.',
      exampleTranslation: 'Escribí un ensayo sobre el cambio climático.',
      status: 'approved',
    },
    {
      id: 'voc_a2_research-paper_390',
      word: 'research paper',
      translation: 'trabajo de investigación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈrisɜrtʃ ˈpeɪpər/',
      example: 'Her research paper was published.',
      exampleTranslation: 'Su trabajo de investigación fue publicado.',
      status: 'approved',
    },
    {
      id: 'voc_a2_citation_391',
      word: 'citation',
      translation: 'cita bibliográfica',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/saɪˈteɪʃən/',
      example: 'Add the citation at the end.',
      exampleTranslation: 'Agrega la cita bibliográfica al final.',
      status: 'approved',
    },
    {
      id: 'voc_a2_bibliography_392',
      word: 'bibliography',
      translation: 'bibliografía',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌbɪbliˈɑgrəfi/',
      example: 'Check the bibliography for sources.',
      exampleTranslation: 'Revisa la bibliografía para ver las fuentes.',
      status: 'approved',
    },
    {
      id: 'voc_a2_peer-review_393',
      word: 'peer review',
      translation: 'revisión por pares',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pɪr rɪˈvju/',
      example: 'The article went through peer review.',
      exampleTranslation: 'El artículo pasó por revisión por pares.',
      status: 'approved',
    },
    {
      id: 'voc_a2_graduate_394',
      word: 'graduate',
      translation: 'graduado',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈgrædʒuət/',
      example: 'She is a graduate student now.',
      exampleTranslation: 'Ella es estudiante de posgrado ahora.',
      status: 'approved',
    },
    {
      id: 'voc_a2_undergraduate_395',
      word: 'undergraduate',
      translation: 'estudiante de pregrado',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌʌndərˈgrædʒuət/',
      example: 'He is an undergraduate at this university.',
      exampleTranslation: 'Él es estudiante de pregrado en esta universidad.',
      status: 'approved',
    },
    {
      id: 'voc_a2_postgraduate_396',
      word: 'postgraduate',
      translation: 'posgrado',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/poʊstˈgrædʒuət/',
      example: 'She started a postgraduate program.',
      exampleTranslation: 'Ella empezó un programa de posgrado.',
      status: 'approved',
    },
    {
      id: 'voc_a2_internship_397',
      word: 'internship',
      translation: 'pasantía',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɪntərnˌʃɪp/',
      example: 'I did an internship last summer.',
      exampleTranslation: 'Hice una pasantía el verano pasado.',
      status: 'approved',
    },
    {
      id: 'voc_a2_apprenticeship_398',
      word: 'apprenticeship',
      translation: 'aprendizaje (oficio)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈprɛntɪsˌʃɪp/',
      example: 'He completed his apprenticeship.',
      exampleTranslation: 'Él completó su aprendizaje.',
      status: 'approved',
    },
    {
      id: 'voc_a2_vocational-training_399',
      word: 'vocational training',
      translation: 'formación profesional',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/voʊˈkeɪʃənəl ˈtreɪnɪŋ/',
      example: 'She chose vocational training instead.',
      exampleTranslation: 'Ella eligió formación profesional en su lugar.',
      status: 'approved',
    },
    {
      id: 'voc_a2_distance-learning_400',
      word: 'distance learning',
      translation: 'educación a distancia',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdɪstəns ˈlɜrnɪŋ/',
      example: 'Distance learning is very flexible.',
      exampleTranslation: 'La educación a distancia es muy flexible.',
      status: 'approved',
    },
    {
      id: 'voc_a2_online-course_401',
      word: 'online course',
      translation: 'curso en línea',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɔnˌlaɪn kɔrs/',
      example: 'I signed up for an online course.',
      exampleTranslation: 'Me inscribí en un curso en línea.',
      status: 'approved',
    },
    {
      id: 'voc_a2_tutor_402',
      word: 'tutor',
      translation: 'tutor',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtutər/',
      example: 'I hired a math tutor.',
      exampleTranslation: 'Contraté a un tutor de matemáticas.',
      status: 'approved',
    },
    {
      id: 'voc_a2_mentor_403',
      word: 'mentor',
      translation: 'mentor',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmɛnˌtɔr/',
      example: 'She has a great mentor at work.',
      exampleTranslation: 'Ella tiene un gran mentor en el trabajo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_extracurricular_404',
      word: 'extracurricular',
      translation: 'extracurricular',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌɛkstrəkəˈrɪkjələr/',
      example: 'He joined an extracurricular club.',
      exampleTranslation: 'Él se unió a un club extracurricular.',
      status: 'approved',
    },
    {
      id: 'voc_a2_student-loan_405',
      word: 'student loan',
      translation: 'préstamo estudiantil',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈstudənt loʊn/',
      example: 'She is still paying her student loan.',
      exampleTranslation: 'Ella todavía está pagando su préstamo estudiantil.',
      status: 'approved',
    },
    {
      id: 'voc_a2_financial-aid_406',
      word: 'financial aid',
      translation: 'ayuda financiera',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/faɪˈnænʃəl eɪd/',
      example: 'I applied for financial aid.',
      exampleTranslation: 'Solicité ayuda financiera.',
      status: 'approved',
    },
    {
      id: 'voc_a2_dropout_407',
      word: 'dropout',
      translation: 'abandono escolar',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdrɑpˌaʊt/',
      example: 'The dropout rate decreased this year.',
      exampleTranslation: 'La tasa de abandono escolar bajó este año.',
      status: 'approved',
    },
    {
      id: 'voc_a2_literacy_408',
      word: 'literacy',
      translation: 'alfabetización',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈlɪtərəsi/',
      example: 'Literacy programs help many adults.',
      exampleTranslation: 'Los programas de alfabetización ayudan a muchos adultos.',
      status: 'approved',
    },
    {
      id: 'voc_a2_curriculum_409',
      word: 'curriculum',
      translation: 'plan de estudios',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kəˈrɪkjələm/',
      example: 'The school updated its curriculum.',
      exampleTranslation: 'La escuela actualizó su plan de estudios.',
      status: 'approved',
    },
    {
      id: 'voc_a2_elective_410',
      word: 'elective',
      translation: 'materia electiva',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪˈlɛktɪv/',
      example: 'I chose an elective in photography.',
      exampleTranslation: 'Elegí una materia electiva de fotografía.',
      status: 'approved',
    },
    {
      id: 'voc_a2_credit-hour_411',
      word: 'credit hour',
      translation: 'hora crédito',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkrɛdɪt aʊər/',
      example: 'This class is worth three credit hours.',
      exampleTranslation: 'Esta clase vale tres horas crédito.',
      status: 'approved',
    },
    {
      id: 'voc_a2_exam-period_412',
      word: 'exam period',
      translation: 'periodo de exámenes',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪgˈzæm ˈpɪriəd/',
      example: 'The library is full during exam period.',
      exampleTranslation: 'La biblioteca está llena durante el periodo de exámenes.',
      status: 'approved',
    },
  ] as const,
}
