/**
 * A2 Level Content — Week 14
 * Topic: Cultura, medios y entretenimiento
 * Curated from institutional curriculum (Zero AI)
 */
import type { ContentBlock } from '../types'

export const week14: ContentBlock = {
  level: 'A2',
  week: 14,
  topic: 'Cultura, medios y entretenimiento',
  vocabulary: [
    {
      id: 'voc_a2_headline_645',
      word: 'headline',
      translation: 'titular',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈhɛˌdlaɪn/',
      example: 'The headline caught my attention.',
      exampleTranslation: 'El titular llamó mi atención.',
      status: 'approved',
    },
    {
      id: 'voc_a2_breaking-news_646',
      word: 'breaking news',
      translation: 'noticia de última hora',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbreɪkɪŋ nuz/',
      example: 'This is breaking news.',
      exampleTranslation: 'Esta es una noticia de última hora.',
      status: 'approved',
    },
    {
      id: 'voc_a2_editorial_647',
      word: 'editorial',
      translation: 'editorial',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌɛdəˈtɔriəl/',
      example: 'I read the editorial this morning.',
      exampleTranslation: 'Leí el editorial esta mañana.',
      status: 'approved',
    },
    {
      id: 'voc_a2_celebrity_648',
      word: 'celebrity',
      translation: 'celebridad',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/səˈlɛbrəti/',
      example: 'The celebrity attended the event.',
      exampleTranslation: 'La celebridad asistió al evento.',
      status: 'approved',
    },
    {
      id: 'voc_a2_plot_649',
      word: 'plot (story)',
      translation: 'trama',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/plɑt/',
      example: 'The plot was very confusing.',
      exampleTranslation: 'La trama fue muy confusa.',
      status: 'approved',
    },
    {
      id: 'voc_a2_character_650',
      word: 'character (story)',
      translation: 'personaje',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkɛrɪktər/',
      example: 'My favorite character is the villain.',
      exampleTranslation: 'Mi personaje favorito es el villano.',
      status: 'approved',
    },
    {
      id: 'voc_a2_genre_651',
      word: 'genre',
      translation: 'género',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈʒɑnrə/',
      example: 'What is your favorite movie genre?',
      exampleTranslation: '¿Cuál es tu género de película favorito?',
      status: 'approved',
    },
    {
      id: 'voc_a2_soundtrack_652',
      word: 'soundtrack',
      translation: 'banda sonora',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsaʊndˌtræk/',
      example: 'I love the movie\'s soundtrack.',
      exampleTranslation: 'Me encanta la banda sonora de la película.',
      status: 'approved',
    },
    {
      id: 'voc_a2_subtitle_653',
      word: 'subtitle',
      translation: 'subtítulo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsʌbˌtaɪtəl/',
      example: 'I watched it with subtitles.',
      exampleTranslation: 'Lo vi con subtítulos.',
      status: 'approved',
    },
    {
      id: 'voc_a2_box-office_654',
      word: 'box office',
      translation: 'taquilla',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bɑks ˈɔfəs/',
      example: 'The film broke box office records.',
      exampleTranslation: 'La película rompió récords de taquilla.',
      status: 'approved',
    },
    {
      id: 'voc_a2_streaming-platform_655',
      word: 'streaming platform',
      translation: 'plataforma de streaming',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈstrimɪŋ ˈplætˌfɔrm/',
      example: 'Which streaming platform do you use?',
      exampleTranslation: '¿Qué plataforma de streaming usas?',
      status: 'approved',
    },
    {
      id: 'voc_a2_premiere_656',
      word: 'premiere',
      translation: 'estreno',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/prɪˈmɪr/',
      example: 'We went to the movie premiere.',
      exampleTranslation: 'Fuimos al estreno de la película.',
      status: 'approved',
    },
    {
      id: 'voc_a2_sequel_657',
      word: 'sequel',
      translation: 'secuela',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsikwəl/',
      example: 'The sequel was better than the original.',
      exampleTranslation: 'La secuela fue mejor que la original.',
      status: 'approved',
    },
    {
      id: 'voc_a2_remake_658',
      word: 'remake',
      translation: 'nueva versión',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈriˌmeɪk/',
      example: 'They released a remake of the classic.',
      exampleTranslation: 'Lanzaron una nueva versión del clásico.',
      status: 'approved',
    },
    {
      id: 'voc_a2_script_659',
      word: 'script',
      translation: 'guion',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/skrɪpt/',
      example: 'She wrote the script herself.',
      exampleTranslation: 'Ella escribió el guion ella misma.',
      status: 'approved',
    },
    {
      id: 'voc_a2_director_660',
      word: 'director',
      translation: 'director',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dɪˈrɛktər/',
      example: 'The director won an award.',
      exampleTranslation: 'El director ganó un premio.',
      status: 'approved',
    },
    {
      id: 'voc_a2_producer_661',
      word: 'producer',
      translation: 'productor',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/prəˈdusər/',
      example: 'The producer funded the whole film.',
      exampleTranslation: 'El productor financió toda la película.',
      status: 'approved',
    },
    {
      id: 'voc_a2_audience_662',
      word: 'audience',
      translation: 'audiencia',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɔdiəns/',
      example: 'The audience loved the show.',
      exampleTranslation: 'Al público le encantó el espectáculo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_review_663',
      word: 'review (critique)',
      translation: 'crítica/reseña',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rɪˈvju/',
      example: 'The review was very positive.',
      exampleTranslation: 'La reseña fue muy positiva.',
      status: 'approved',
    },
    {
      id: 'voc_a2_critic_664',
      word: 'critic',
      translation: 'crítico',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkrɪtɪk/',
      example: 'The critic gave it five stars.',
      exampleTranslation: 'El crítico le dio cinco estrellas.',
      status: 'approved',
    },
    {
      id: 'voc_a2_bestselling_665',
      word: 'bestselling',
      translation: 'más vendido (libro)',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bɛstˈsɛlɪŋ/',
      example: 'This is a bestselling novel.',
      exampleTranslation: 'Esta es una novela más vendida.',
      status: 'approved',
    },
    {
      id: 'voc_a2_author_666',
      word: 'author',
      translation: 'autor',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɔθər/',
      example: 'The author signed my book.',
      exampleTranslation: 'El autor firmó mi libro.',
      status: 'approved',
    },
    {
      id: 'voc_a2_publisher_667',
      word: 'publisher',
      translation: 'editorial (empresa)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpʌblɪʃər/',
      example: 'The publisher rejected the manuscript.',
      exampleTranslation: 'La editorial rechazó el manuscrito.',
      status: 'approved',
    },
    {
      id: 'voc_a2_edition_668',
      word: 'edition',
      translation: 'edición',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪˈdɪʃən/',
      example: 'I have the first edition.',
      exampleTranslation: 'Tengo la primera edición.',
      status: 'approved',
    },
    {
      id: 'voc_a2_chapter_669',
      word: 'chapter',
      translation: 'capítulo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtʃæptər/',
      example: 'I finished the last chapter.',
      exampleTranslation: 'Terminé el último capítulo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_plot-twist_670',
      word: 'plot twist',
      translation: 'giro de la trama',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/plɑt twɪst/',
      example: 'The plot twist surprised everyone.',
      exampleTranslation: 'El giro de la trama sorprendió a todos.',
      status: 'approved',
    },
    {
      id: 'voc_a2_cliffhanger_671',
      word: 'cliffhanger',
      translation: 'final en suspenso',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈklɪfˌhæŋər/',
      example: 'The episode ended in a cliffhanger.',
      exampleTranslation: 'El episodio terminó en suspenso.',
      status: 'approved',
    },
    {
      id: 'voc_a2_fan-base_672',
      word: 'fan base',
      translation: 'base de fanáticos',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fæn beɪs/',
      example: 'The band has a huge fan base.',
      exampleTranslation: 'La banda tiene una enorme base de fanáticos.',
      status: 'approved',
    },
    {
      id: 'voc_a2_influencer_673',
      word: 'influencer',
      translation: 'influencer',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɪnfluənsər/',
      example: 'She works as an influencer.',
      exampleTranslation: 'Ella trabaja como influencer.',
      status: 'approved',
    },
    {
      id: 'voc_a2_viral_674',
      word: 'viral',
      translation: 'viral',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈvaɪrəl/',
      example: 'The video went viral overnight.',
      exampleTranslation: 'El video se volvió viral de la noche a la mañana.',
      status: 'approved',
    },
    {
      id: 'voc_a2_trending_675',
      word: 'trending',
      translation: 'en tendencia',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtrɛndɪŋ/',
      example: 'This topic is trending today.',
      exampleTranslation: 'Este tema está en tendencia hoy.',
      status: 'approved',
    },
    {
      id: 'voc_a2_content-creator_676',
      word: 'content creator',
      translation: 'creador de contenido',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkɑnˌtɛnt kriˈeɪtər/',
      example: 'She is a full-time content creator.',
      exampleTranslation: 'Ella es creadora de contenido de tiempo completo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_live-stream_677',
      word: 'live stream',
      translation: 'transmisión en vivo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/laɪv strim/',
      example: 'We watched the live stream at home.',
      exampleTranslation: 'Vimos la transmisión en vivo desde casa.',
      status: 'approved',
    },
    {
      id: 'voc_a2_podcast_678',
      word: 'podcast',
      translation: 'podcast',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpɑdˌkæst/',
      example: 'I listen to a podcast every morning.',
      exampleTranslation: 'Escucho un podcast todas las mañanas.',
      status: 'approved',
    },
    {
      id: 'voc_a2_exhibit-exhibition_679',
      word: 'exhibit / exhibition',
      translation: 'exhibición',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪgˈzɪbɪt/',
      example: 'We visited the art exhibit.',
      exampleTranslation: 'Visitamos la exhibición de arte.',
      status: 'approved',
    },
    {
      id: 'voc_a2_gallery_680',
      word: 'gallery',
      translation: 'galería',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈgæləri/',
      example: 'The gallery has modern art.',
      exampleTranslation: 'La galería tiene arte moderno.',
      status: 'approved',
    },
    {
      id: 'voc_a2_performance_681',
      word: 'performance (show)',
      translation: 'actuación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pərˈfɔrməns/',
      example: 'The dance performance was amazing.',
      exampleTranslation: 'La actuación de baile fue increíble.',
      status: 'approved',
    },
    {
      id: 'voc_a2_stand-up-comedy_682',
      word: 'stand-up comedy',
      translation: 'comedia en vivo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈstændˌʌp ˈkɑmədi/',
      example: 'We watched a stand-up comedy show.',
      exampleTranslation: 'Vimos un show de comedia en vivo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_orchestra_683',
      word: 'orchestra',
      translation: 'orquesta',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɔrkɪstrə/',
      example: 'The orchestra played beautifully.',
      exampleTranslation: 'La orquesta tocó hermosamente.',
      status: 'approved',
    },
    {
      id: 'voc_a2_choir_684',
      word: 'choir',
      translation: 'coro',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kwaɪər/',
      example: 'She sings in the school choir.',
      exampleTranslation: 'Ella canta en el coro de la escuela.',
      status: 'approved',
    },
    {
      id: 'voc_a2_album_685',
      word: 'album',
      translation: 'álbum',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈælbəm/',
      example: 'Their new album is excellent.',
      exampleTranslation: 'Su nuevo álbum es excelente.',
      status: 'approved',
    },
    {
      id: 'voc_a2_lyrics_686',
      word: 'lyrics',
      translation: 'letra de canción',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈlɪrɪks/',
      example: 'I don\'t know the lyrics of this song.',
      exampleTranslation: 'No conozco la letra de esta canción.',
      status: 'approved',
    },
  ] as const,
}
