/**
 * A2 Level Content — Week 14
 * Topic: Cultura, medios y entretenimiento
 * Curated from institutional curriculum (Zero AI)
 */
import type { ContentBlock } from '../types'

export const week14: ContentBlock = {
  level: 'A2',
  week: 14,
  topic: 'Cultura, medios y entretenimiento',
  vocabulary: [
    {
      id: 'voc_a2_headline_645',
      word: 'headline',
      translation: 'titular',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_breaking-news_646',
      word: 'breaking news',
      translation: 'noticia de última hora',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_editorial_647',
      word: 'editorial',
      translation: 'editorial',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_celebrity_648',
      word: 'celebrity',
      translation: 'celebridad',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_plot_649',
      word: 'plot (story)',
      translation: 'trama',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_character_650',
      word: 'character (story)',
      translation: 'personaje',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_genre_651',
      word: 'genre',
      translation: 'género',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_soundtrack_652',
      word: 'soundtrack',
      translation: 'banda sonora',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_subtitle_653',
      word: 'subtitle',
      translation: 'subtítulo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_box-office_654',
      word: 'box office',
      translation: 'taquilla',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_streaming-platform_655',
      word: 'streaming platform',
      translation: 'plataforma de streaming',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_premiere_656',
      word: 'premiere',
      translation: 'estreno',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_sequel_657',
      word: 'sequel',
      translation: 'secuela',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_remake_658',
      word: 'remake',
      translation: 'nueva versión',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_script_659',
      word: 'script',
      translation: 'guion',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_director_660',
      word: 'director',
      translation: 'director',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_producer_661',
      word: 'producer',
      translation: 'productor',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_audience_662',
      word: 'audience',
      translation: 'audiencia',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_review_663',
      word: 'review (critique)',
      translation: 'crítica/reseña',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_critic_664',
      word: 'critic',
      translation: 'crítico',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_bestselling_665',
      word: 'bestselling',
      translation: 'más vendido (libro)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_author_666',
      word: 'author',
      translation: 'autor',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_publisher_667',
      word: 'publisher',
      translation: 'editorial (empresa)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_edition_668',
      word: 'edition',
      translation: 'edición',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_chapter_669',
      word: 'chapter',
      translation: 'capítulo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_plot-twist_670',
      word: 'plot twist',
      translation: 'giro de la trama',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_cliffhanger_671',
      word: 'cliffhanger',
      translation: 'final en suspenso',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_fan-base_672',
      word: 'fan base',
      translation: 'base de fanáticos',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_influencer_673',
      word: 'influencer',
      translation: 'influencer',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_viral_674',
      word: 'viral',
      translation: 'viral',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_trending_675',
      word: 'trending',
      translation: 'en tendencia',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_content-creator_676',
      word: 'content creator',
      translation: 'creador de contenido',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_live-stream_677',
      word: 'live stream',
      translation: 'transmisión en vivo',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_podcast_678',
      word: 'podcast',
      translation: 'podcast',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_exhibit-exhibition_679',
      word: 'exhibit / exhibition',
      translation: 'exhibición',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_gallery_680',
      word: 'gallery',
      translation: 'galería',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_performance_681',
      word: 'performance (show)',
      translation: 'actuación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_stand-up-comedy_682',
      word: 'stand-up comedy',
      translation: 'comedia en vivo',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_orchestra_683',
      word: 'orchestra',
      translation: 'orquesta',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_choir_684',
      word: 'choir',
      translation: 'coro',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_album_685',
      word: 'album',
      translation: 'álbum',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_lyrics_686',
      word: 'lyrics',
      translation: 'letra de canción',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 14,
      topic: 'cultura-medios-y-ent',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
  ] as const,
}
