/**
 * A2 Level Content — Week 06
 * Topic: Expresar opiniones
 * Curated from institutional curriculum (Zero AI)
 */
import type { ContentBlock } from '../types'

export const week06: ContentBlock = {
  level: 'A2',
  week: 6,
  topic: 'Expresar opiniones',
  vocabulary: [
    {
      id: 'voc_a2_in-my-opinion_289',
      word: 'in my opinion',
      translation: 'en mi opinión',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_i-believe-that_290',
      word: 'I believe that',
      translation: 'creo que',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_i-feel-that_291',
      word: 'I feel that',
      translation: 'siento que',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_personally_292',
      word: 'personally',
      translation: 'personalmente',
      partOfSpeech: 'adverb',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_from-my-point-of-vie_293',
      word: 'from my point of view',
      translation: 'desde mi punto de vista',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_i-agree_294',
      word: 'I agree',
      translation: 'estoy de acuerdo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_i-disagree_295',
      word: 'I disagree',
      translation: 'no estoy de acuerdo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_im-not-sure_296',
      word: "I'm not sure",
      translation: 'no estoy seguro',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_it-seems-to-me_297',
      word: 'it seems to me',
      translation: 'me parece que',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_as-far-as-i-know_298',
      word: 'as far as I know',
      translation: 'que yo sepa',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_i-suppose_299',
      word: 'I suppose',
      translation: 'supongo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_i-guess_300',
      word: 'I guess (opinion)',
      translation: 'supongo/creo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_to-be-honest_301',
      word: 'to be honest',
      translation: 'para ser honesto',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_in-fact_302',
      word: 'in fact',
      translation: 'de hecho',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_definitely_303',
      word: 'definitely',
      translation: 'definitivamente',
      partOfSpeech: 'adverb',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_absolutely_304',
      word: 'absolutely',
      translation: 'absolutamente',
      partOfSpeech: 'adverb',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_of-course_305',
      word: 'of course',
      translation: 'por supuesto',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_no-way_306',
      word: 'no way',
      translation: 'de ninguna manera',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_thats-true_307',
      word: "that's true",
      translation: 'eso es cierto',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_thats-not-true_308',
      word: "that's not true",
      translation: 'eso no es cierto',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_i-doubt-it_309',
      word: 'I doubt it',
      translation: 'lo dudo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_it-depends_310',
      word: 'it depends',
      translation: 'depende',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_on-one-hand_311',
      word: 'on one hand',
      translation: 'por un lado',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_on-the-other-hand_312',
      word: 'on the other hand',
      translation: 'por otro lado',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_its-obvious_313',
      word: "it's obvious",
      translation: 'es obvio',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_clearly_314',
      word: 'clearly',
      translation: 'claramente',
      partOfSpeech: 'adverb',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_apparently_315',
      word: 'apparently',
      translation: 'aparentemente',
      partOfSpeech: 'adverb',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_allegedly_316',
      word: 'allegedly',
      translation: 'supuestamente',
      partOfSpeech: 'adverb',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_presumably_317',
      word: 'presumably',
      translation: 'presumiblemente',
      partOfSpeech: 'adverb',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_undoubtedly_318',
      word: 'undoubtedly',
      translation: 'sin duda',
      partOfSpeech: 'adverb',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_arguably_319',
      word: 'arguably',
      translation: 'posiblemente/se podría decir',
      partOfSpeech: 'adverb',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_in-my-experience_320',
      word: 'in my experience',
      translation: 'en mi experiencia',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_based-on_321',
      word: 'based on',
      translation: 'basado en',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_according-to_322',
      word: 'according to',
      translation: 'según',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_evidence_323',
      word: 'evidence',
      translation: 'evidencia',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_argument_324',
      word: 'argument',
      translation: 'argumento',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_viewpoint-standpoint_325',
      word: 'viewpoint / standpoint',
      translation: 'punto de vista',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_counterargument_326',
      word: 'counterargument',
      translation: 'contraargumento',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_valid-point_327',
      word: 'valid point',
      translation: 'punto válido',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_convince_328',
      word: 'convince',
      translation: 'convencer',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_persuade_329',
      word: 'persuade',
      translation: 'persuadir',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_debate_330',
      word: 'debate',
      translation: 'debate',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_controversy_331',
      word: 'controversy',
      translation: 'controversia',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_agree-to-disagree_332',
      word: 'agree to disagree',
      translation: 'acordar estar en desacuerdo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
  ] as const,
}
