/**
 * A2 Level Content — Week 02
 * Topic: Viajes: aeropuerto, hotel y emergencias
 * Curated from institutional curriculum (Zero AI)
 */
import type { ContentBlock } from '../types'

export const week02: ContentBlock = {
  level: 'A2',
  week: 2,
  topic: 'Viajes: aeropuerto, hotel y emergencias',
  vocabulary: [
    {
      id: 'voc_a2_check-in_065',
      word: 'check-in',
      translation: 'registro de entrada',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtʃɛkˌɪn/',
      example: 'Check-in starts at three.',
      exampleTranslation: 'El registro de entrada empieza a las tres.',
      status: 'approved',
    },
    {
      id: 'voc_a2_check-out_066',
      word: 'check-out',
      translation: 'salida (hotel)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtʃɛkˌaʊt/',
      example: 'Check-out is at eleven.',
      exampleTranslation: 'La salida es a las once.',
      status: 'approved',
    },
    {
      id: 'voc_a2_room-service_067',
      word: 'room service',
      translation: 'servicio a la habitación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rum ˈsɜrvɪs/',
      example: 'We ordered room service last night.',
      exampleTranslation: 'Pedimos servicio a la habitación anoche.',
      status: 'approved',
    },
    {
      id: 'voc_a2_single-room_068',
      word: 'single room',
      translation: 'habitación individual',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsɪŋgəl rum/',
      example: 'I booked a single room.',
      exampleTranslation: 'Reservé una habitación individual.',
      status: 'approved',
    },
    {
      id: 'voc_a2_double-room_069',
      word: 'double room',
      translation: 'habitación doble',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdʌbəl rum/',
      example: 'We need a double room.',
      exampleTranslation: 'Necesitamos una habitación doble.',
      status: 'approved',
    },
    {
      id: 'voc_a2_suite_070',
      word: 'suite',
      translation: 'suite',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/swit/',
      example: 'They stayed in a suite.',
      exampleTranslation: 'Se hospedaron en una suite.',
      status: 'approved',
    },
    {
      id: 'voc_a2_lobby_071',
      word: 'lobby',
      translation: 'vestíbulo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈlɑbi/',
      example: 'Let\'s meet in the lobby.',
      exampleTranslation: 'Reunámonos en el vestíbulo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_concierge_072',
      word: 'concierge',
      translation: 'conserje',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌkɑnsiˈɛrʒ/',
      example: 'The concierge gave us a map.',
      exampleTranslation: 'El conserje nos dio un mapa.',
      status: 'approved',
    },
    {
      id: 'voc_a2_housekeeping_073',
      word: 'housekeeping',
      translation: 'limpieza (hotel)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈhaʊsˌkipɪŋ/',
      example: 'Housekeeping cleaned our room.',
      exampleTranslation: 'La limpieza aseó nuestra habitación.',
      status: 'approved',
    },
    {
      id: 'voc_a2_do-not-disturb_074',
      word: 'do not disturb',
      translation: 'no molestar',
      partOfSpeech: 'phrasal-verb',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/du nɑt dɪˈstɜrb/',
      example: 'Put the do not disturb sign on the door.',
      exampleTranslation: 'Cuelga el letrero de no molestar en la puerta.',
      status: 'approved',
    },
    {
      id: 'voc_a2_key-card_075',
      word: 'key card',
      translation: 'tarjeta llave',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ki kɑrd/',
      example: 'I lost my key card.',
      exampleTranslation: 'Perdí mi tarjeta llave.',
      status: 'approved',
    },
    {
      id: 'voc_a2_wake-up-call_076',
      word: 'wake-up call',
      translation: 'llamada para despertar',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈweɪkʌp kɔl/',
      example: 'I need a wake-up call at six.',
      exampleTranslation: 'Necesito una llamada para despertar a las seis.',
      status: 'approved',
    },
    {
      id: 'voc_a2_mini-bar_077',
      word: 'mini bar',
      translation: 'minibar',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmɪni bɑr/',
      example: 'The mini bar has snacks and drinks.',
      exampleTranslation: 'El minibar tiene botanas y bebidas.',
      status: 'approved',
    },
    {
      id: 'voc_a2_complimentary_078',
      word: 'complimentary',
      translation: 'gratuito/cortesía',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌkɑmpləˈmɛntəri/',
      example: 'Breakfast is complimentary.',
      exampleTranslation: 'El desayuno es gratuito.',
      status: 'approved',
    },
    {
      id: 'voc_a2_amenities_079',
      word: 'amenities',
      translation: 'comodidades',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈmɛnətiz/',
      example: 'The hotel has great amenities.',
      exampleTranslation: 'El hotel tiene excelentes comodidades.',
      status: 'approved',
    },
    {
      id: 'voc_a2_spa_080',
      word: 'spa',
      translation: 'spa',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/spɑ/',
      example: 'We relaxed at the spa.',
      exampleTranslation: 'Nos relajamos en el spa.',
      status: 'approved',
    },
    {
      id: 'voc_a2_laundry-service_081',
      word: 'laundry service',
      translation: 'servicio de lavandería',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈlɔndri ˈsɜrvɪs/',
      example: 'Does the hotel offer laundry service?',
      exampleTranslation: '¿El hotel ofrece servicio de lavandería?',
      status: 'approved',
    },
    {
      id: 'voc_a2_front-desk_082',
      word: 'front desk',
      translation: 'recepción',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/frʌnt dɛsk/',
      example: 'Ask the front desk for towels.',
      exampleTranslation: 'Pide toallas en la recepción.',
      status: 'approved',
    },
    {
      id: 'voc_a2_overbooked_083',
      word: 'overbooked',
      translation: 'con sobreventa',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌoʊvərˈbʊkt/',
      example: 'The hotel was overbooked.',
      exampleTranslation: 'El hotel tenía sobreventa.',
      status: 'approved',
    },
    {
      id: 'voc_a2_cancellation_084',
      word: 'cancellation',
      translation: 'cancelación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌkænsəˈleɪʃən/',
      example: 'There was a last-minute cancellation.',
      exampleTranslation: 'Hubo una cancelación de última hora.',
      status: 'approved',
    },
    {
      id: 'voc_a2_non-refundable_085',
      word: 'non-refundable',
      translation: 'no reembolsable',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌnɑnrɪˈfʌndəbəl/',
      example: 'This ticket is non-refundable.',
      exampleTranslation: 'Este boleto no es reembolsable.',
      status: 'approved',
    },
    {
      id: 'voc_a2_itinerary_086',
      word: 'itinerary',
      translation: 'itinerario',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/aɪˈtɪnəˌrɛri/',
      example: 'Here is our travel itinerary.',
      exampleTranslation: 'Aquí está nuestro itinerario de viaje.',
      status: 'approved',
    },
    {
      id: 'voc_a2_layover_087',
      word: 'layover',
      translation: 'escala',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈleɪˌoʊvər/',
      example: 'We have a two-hour layover.',
      exampleTranslation: 'Tenemos una escala de dos horas.',
      status: 'approved',
    },
    {
      id: 'voc_a2_connecting-flight_088',
      word: 'connecting flight',
      translation: 'vuelo de conexión',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kəˈnɛktɪŋ flaɪt/',
      example: 'I almost missed my connecting flight.',
      exampleTranslation: 'Casi pierdo mi vuelo de conexión.',
      status: 'approved',
    },
    {
      id: 'voc_a2_delayed-flight_089',
      word: 'delayed flight',
      translation: 'vuelo retrasado',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dɪˈleɪd flaɪt/',
      example: 'Our delayed flight caused problems.',
      exampleTranslation: 'Nuestro vuelo retrasado causó problemas.',
      status: 'approved',
    },
    {
      id: 'voc_a2_cancelled-flight_090',
      word: 'cancelled flight',
      translation: 'vuelo cancelado',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkænsəld flaɪt/',
      example: 'The cancelled flight was rescheduled.',
      exampleTranslation: 'El vuelo cancelado fue reprogramado.',
      status: 'approved',
    },
    {
      id: 'voc_a2_boarding-time_091',
      word: 'boarding time',
      translation: 'hora de embarque',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbɔrdɪŋ taɪm/',
      example: 'Check the boarding time on your ticket.',
      exampleTranslation: 'Revisa la hora de embarque en tu boleto.',
      status: 'approved',
    },
    {
      id: 'voc_a2_overhead-bin_092',
      word: 'overhead bin',
      translation: 'compartimento superior',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈoʊvərˌhɛd bɪn/',
      example: 'Put your bag in the overhead bin.',
      exampleTranslation: 'Pon tu bolsa en el compartimento superior.',
      status: 'approved',
    },
    {
      id: 'voc_a2_carry-on_093',
      word: 'carry-on',
      translation: 'equipaje de mano',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkæriˌɑn/',
      example: 'I only brought a carry-on.',
      exampleTranslation: 'Solo traje equipaje de mano.',
      status: 'approved',
    },
    {
      id: 'voc_a2_baggage-claim_094',
      word: 'baggage claim',
      translation: 'reclamo de equipaje',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbægɪdʒ kleɪm/',
      example: 'Meet me at baggage claim.',
      exampleTranslation: 'Encuéntrame en el reclamo de equipaje.',
      status: 'approved',
    },
    {
      id: 'voc_a2_lost-luggage_095',
      word: 'lost luggage',
      translation: 'equipaje perdido',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/lɔst ˈlʌgɪdʒ/',
      example: 'We reported our lost luggage.',
      exampleTranslation: 'Reportamos nuestro equipaje perdido.',
      status: 'approved',
    },
    {
      id: 'voc_a2_customs-declaration_096',
      word: 'customs declaration',
      translation: 'declaración de aduana',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkʌstəmz ˌdɛkləˈreɪʃən/',
      example: 'Fill out the customs declaration.',
      exampleTranslation: 'Llena la declaración de aduana.',
      status: 'approved',
    },
    {
      id: 'voc_a2_duty-free_097',
      word: 'duty-free',
      translation: 'libre de impuestos',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdutiˈfri/',
      example: 'I bought perfume at duty-free.',
      exampleTranslation: 'Compré perfume libre de impuestos.',
      status: 'approved',
    },
    {
      id: 'voc_a2_embassy_098',
      word: 'embassy',
      translation: 'embajada',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɛmbəsi/',
      example: 'We visited the embassy for a visa.',
      exampleTranslation: 'Visitamos la embajada por una visa.',
      status: 'approved',
    },
    {
      id: 'voc_a2_consulate_099',
      word: 'consulate',
      translation: 'consulado',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkɑnsələt/',
      example: 'The consulate can help with documents.',
      exampleTranslation: 'El consulado puede ayudar con documentos.',
      status: 'approved',
    },
    {
      id: 'voc_a2_emergency-exit_100',
      word: 'emergency exit',
      translation: 'salida de emergencia',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪˈmɜrdʒənsi ˈɛgzɪt/',
      example: 'The emergency exit is at the back.',
      exampleTranslation: 'La salida de emergencia está atrás.',
      status: 'approved',
    },
    {
      id: 'voc_a2_fire-alarm_101',
      word: 'fire alarm',
      translation: 'alarma de incendio',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/faɪər əˈlɑrm/',
      example: 'The fire alarm went off.',
      exampleTranslation: 'Sonó la alarma de incendio.',
      status: 'approved',
    },
    {
      id: 'voc_a2_first-aid_102',
      word: 'first aid',
      translation: 'primeros auxilios',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fɜrst eɪd/',
      example: 'She knows basic first aid.',
      exampleTranslation: 'Ella sabe primeros auxilios básicos.',
      status: 'approved',
    },
    {
      id: 'voc_a2_evacuation_103',
      word: 'evacuation',
      translation: 'evacuación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪˌvækjuˈeɪʃən/',
      example: 'The evacuation was calm and organized.',
      exampleTranslation: 'La evacuación fue tranquila y organizada.',
      status: 'approved',
    },
    {
      id: 'voc_a2_emergency-contact_104',
      word: 'emergency contact',
      translation: 'contacto de emergencia',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪˈmɜrdʒənsi ˈkɑnˌtækt/',
      example: 'Write down your emergency contact.',
      exampleTranslation: 'Anota tu contacto de emergencia.',
      status: 'approved',
    },
    {
      id: 'voc_a2_insurance-claim_105',
      word: 'insurance claim',
      translation: 'reclamo de seguro',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪnˈʃʊrəns kleɪm/',
      example: 'I filed an insurance claim.',
      exampleTranslation: 'Presenté un reclamo de seguro.',
      status: 'approved',
    },
    {
      id: 'voc_a2_stolen_106',
      word: 'stolen',
      translation: 'robado',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈstoʊlən/',
      example: 'My phone was stolen.',
      exampleTranslation: 'Me robaron el teléfono.',
      status: 'approved',
    },
    {
      id: 'voc_a2_robbery_107',
      word: 'robbery',
      translation: 'robo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈrɑbəri/',
      example: 'There was a robbery downtown.',
      exampleTranslation: 'Hubo un robo en el centro.',
      status: 'approved',
    },
    {
      id: 'voc_a2_pickpocket_108',
      word: 'pickpocket',
      translation: 'carterista',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpɪkˌpɑkɪt/',
      example: 'Watch out for pickpockets.',
      exampleTranslation: 'Cuidado con los carteristas.',
      status: 'approved',
    },
    {
      id: 'voc_a2_police-report_109',
      word: 'police report',
      translation: 'reporte policial',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pəˈlis rɪˈpɔrt/',
      example: 'We filed a police report.',
      exampleTranslation: 'Presentamos un reporte policial.',
      status: 'approved',
    },
    {
      id: 'voc_a2_lost-and-found_110',
      word: 'lost and found',
      translation: 'objetos perdidos',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/lɔst ənd faʊnd/',
      example: 'Check the lost and found.',
      exampleTranslation: 'Revisa los objetos perdidos.',
      status: 'approved',
    },
    {
      id: 'voc_a2_replacement-passport_111',
      word: 'replacement passport',
      translation: 'pasaporte de reemplazo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rɪˈpleɪsmənt ˈpæˌspɔrt/',
      example: 'I need a replacement passport.',
      exampleTranslation: 'Necesito un pasaporte de reemplazo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_travel-advisory_112',
      word: 'travel advisory',
      translation: 'advertencia de viaje',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtrævəl ædˈvaɪzəri/',
      example: 'There is a travel advisory for that area.',
      exampleTranslation: 'Hay una advertencia de viaje para esa zona.',
      status: 'approved',
    },
    {
      id: 'voc_a2_vaccination-certific_113',
      word: 'vaccination certificate',
      translation: 'certificado de vacunación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌvæksəˈneɪʃən sərˈtɪfɪkət/',
      example: 'Bring your vaccination certificate.',
      exampleTranslation: 'Trae tu certificado de vacunación.',
      status: 'approved',
    },
    {
      id: 'voc_a2_jet-lag_114',
      word: 'jet lag',
      translation: 'descompensación horaria',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dʒɛt læg/',
      example: 'I have terrible jet lag.',
      exampleTranslation: 'Tengo un descompensación horaria terrible.',
      status: 'approved',
    },
    {
      id: 'voc_a2_time-zone_115',
      word: 'time zone',
      translation: 'zona horaria',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/taɪm zoʊn/',
      example: 'We are in a different time zone.',
      exampleTranslation: 'Estamos en una zona horaria diferente.',
      status: 'approved',
    },
    {
      id: 'voc_a2_local-currency_116',
      word: 'local currency',
      translation: 'moneda local',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈloʊkəl ˈkɜrənsi/',
      example: 'Exchange your money for local currency.',
      exampleTranslation: 'Cambia tu dinero por moneda local.',
      status: 'approved',
    },
    {
      id: 'voc_a2_tipping_117',
      word: 'tipping',
      translation: 'dar propina',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtɪpɪŋ/',
      example: 'Tipping is common here.',
      exampleTranslation: 'Dar propina es común aquí.',
      status: 'approved',
    },
    {
      id: 'voc_a2_guided-tour_118',
      word: 'guided tour',
      translation: 'tour guiado',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈgaɪdɪd tʊr/',
      example: 'We took a guided tour of the museum.',
      exampleTranslation: 'Hicimos un tour guiado del museo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_sightseeing_119',
      word: 'sightseeing',
      translation: 'hacer turismo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsaɪtˌsiɪŋ/',
      example: 'We went sightseeing all day.',
      exampleTranslation: 'Hicimos turismo todo el día.',
      status: 'approved',
    },
    {
      id: 'voc_a2_landmark_120',
      word: 'landmark',
      translation: 'punto de referencia/monumento',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈlændˌmɑrk/',
      example: 'The tower is a famous landmark.',
      exampleTranslation: 'La torre es un monumento famoso.',
      status: 'approved',
    },
  ] as const,
}
