/**
 * A2 Level Content — Week 06
 * Topic: Expresar opiniones
 * Curated from institutional curriculum (Zero AI)
 */
import type { ContentBlock } from '../types'

export const week06: ContentBlock = {
  level: 'A2',
  week: 6,
  topic: 'Expresar opiniones',
  vocabulary: [
    {
      id: 'voc_a2_in-my-opinion_289',
      word: 'in my opinion',
      translation: 'en mi opinión',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪn maɪ əˈpɪnjən/',
      example: 'In my opinion, this movie is excellent.',
      exampleTranslation: 'En mi opinión, esta película es excelente.',
      status: 'approved',
    },
    {
      id: 'voc_a2_i-believe-that_290',
      word: 'I believe that',
      translation: 'creo que',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/aɪ bɪˈliv ðæt/',
      example: 'I believe that honesty is important.',
      exampleTranslation: 'Creo que la honestidad es importante.',
      status: 'approved',
    },
    {
      id: 'voc_a2_i-feel-that_291',
      word: 'I feel that',
      translation: 'siento que',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/aɪ fil ðæt/',
      example: 'I feel that we should wait.',
      exampleTranslation: 'Siento que deberíamos esperar.',
      status: 'approved',
    },
    {
      id: 'voc_a2_personally_292',
      word: 'personally',
      translation: 'personalmente',
      partOfSpeech: 'adverb',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpɜrsənəli/',
      example: 'Personally, I prefer tea over coffee.',
      exampleTranslation: 'Personalmente, prefiero el té sobre el café.',
      status: 'approved',
    },
    {
      id: 'voc_a2_from-my-point-of-vie_293',
      word: 'from my point of view',
      translation: 'desde mi punto de vista',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/frʌm maɪ pɔɪnt əv vju/',
      example: 'From my point of view, it\'s a fair decision.',
      exampleTranslation: 'Desde mi punto de vista, es una decisión justa.',
      status: 'approved',
    },
    {
      id: 'voc_a2_i-agree_294',
      word: 'I agree',
      translation: 'estoy de acuerdo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/aɪ əˈgri/',
      example: 'I agree with your idea.',
      exampleTranslation: 'Estoy de acuerdo con tu idea.',
      status: 'approved',
    },
    {
      id: 'voc_a2_i-disagree_295',
      word: 'I disagree',
      translation: 'no estoy de acuerdo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/aɪ dɪsəˈgri/',
      example: 'I disagree with that plan.',
      exampleTranslation: 'No estoy de acuerdo con ese plan.',
      status: 'approved',
    },
    {
      id: 'voc_a2_im-not-sure_296',
      word: "I'm not sure",
      translation: 'no estoy seguro',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/aɪm nɑt ʃʊr/',
      example: 'I\'m not sure about the schedule.',
      exampleTranslation: 'No estoy seguro sobre el horario.',
      status: 'approved',
    },
    {
      id: 'voc_a2_it-seems-to-me_297',
      word: 'it seems to me',
      translation: 'me parece que',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪt simz tu mi/',
      example: 'It seems to me that he is right.',
      exampleTranslation: 'Me parece que él tiene razón.',
      status: 'approved',
    },
    {
      id: 'voc_a2_as-far-as-i-know_298',
      word: 'as far as I know',
      translation: 'que yo sepa',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/æz fɑr æz aɪ noʊ/',
      example: 'As far as I know, the store is open.',
      exampleTranslation: 'Que yo sepa, la tienda está abierta.',
      status: 'approved',
    },
    {
      id: 'voc_a2_i-suppose_299',
      word: 'I suppose',
      translation: 'supongo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/aɪ səˈpoʊz/',
      example: 'I suppose you\'re right.',
      exampleTranslation: 'Supongo que tienes razón.',
      status: 'approved',
    },
    {
      id: 'voc_a2_i-guess_300',
      word: 'I guess (opinion)',
      translation: 'supongo/creo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/aɪ gɛs/',
      example: 'I guess we can try it.',
      exampleTranslation: 'Supongo que podemos intentarlo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_to-be-honest_301',
      word: 'to be honest',
      translation: 'para ser honesto',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tu bi ˈɑnəst/',
      example: 'To be honest, I didn\'t like the food.',
      exampleTranslation: 'Para ser honesto, no me gustó la comida.',
      status: 'approved',
    },
    {
      id: 'voc_a2_in-fact_302',
      word: 'in fact',
      translation: 'de hecho',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪn fækt/',
      example: 'In fact, she already knew the answer.',
      exampleTranslation: 'De hecho, ella ya sabía la respuesta.',
      status: 'approved',
    },
    {
      id: 'voc_a2_definitely_303',
      word: 'definitely',
      translation: 'definitivamente',
      partOfSpeech: 'adverb',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdɛfənətli/',
      example: 'I will definitely come to the party.',
      exampleTranslation: 'Definitivamente iré a la fiesta.',
      status: 'approved',
    },
    {
      id: 'voc_a2_absolutely_304',
      word: 'absolutely',
      translation: 'absolutamente',
      partOfSpeech: 'adverb',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌæbsəˈlutli/',
      example: 'That\'s absolutely true.',
      exampleTranslation: 'Eso es absolutamente cierto.',
      status: 'approved',
    },
    {
      id: 'voc_a2_of-course_305',
      word: 'of course',
      translation: 'por supuesto',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ʌv kɔrs/',
      example: 'Of course, I can help you.',
      exampleTranslation: 'Por supuesto, puedo ayudarte.',
      status: 'approved',
    },
    {
      id: 'voc_a2_no-way_306',
      word: 'no way',
      translation: 'de ninguna manera',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/noʊ weɪ/',
      example: 'No way, that\'s impossible.',
      exampleTranslation: 'De ninguna manera, eso es imposible.',
      status: 'approved',
    },
    {
      id: 'voc_a2_thats-true_307',
      word: "that's true",
      translation: 'eso es cierto',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ðæts tru/',
      example: 'That\'s true, I hadn\'t thought of that.',
      exampleTranslation: 'Eso es cierto, no lo había pensado.',
      status: 'approved',
    },
    {
      id: 'voc_a2_thats-not-true_308',
      word: "that's not true",
      translation: 'eso no es cierto',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ðæts nɑt tru/',
      example: 'That\'s not true; I checked it myself.',
      exampleTranslation: 'Eso no es cierto; lo verifiqué yo mismo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_i-doubt-it_309',
      word: 'I doubt it',
      translation: 'lo dudo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/aɪ daʊt ɪt/',
      example: 'I doubt it will rain today.',
      exampleTranslation: 'Dudo que llueva hoy.',
      status: 'approved',
    },
    {
      id: 'voc_a2_it-depends_310',
      word: 'it depends',
      translation: 'depende',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪt dɪˈpɛndz/',
      example: 'It depends on the weather.',
      exampleTranslation: 'Depende del clima.',
      status: 'approved',
    },
    {
      id: 'voc_a2_on-one-hand_311',
      word: 'on one hand',
      translation: 'por un lado',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɑn wʌn hænd/',
      example: 'On one hand, it\'s expensive.',
      exampleTranslation: 'Por un lado, es caro.',
      status: 'approved',
    },
    {
      id: 'voc_a2_on-the-other-hand_312',
      word: 'on the other hand',
      translation: 'por otro lado',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɑn ði ˈʌðər hænd/',
      example: 'On the other hand, it\'s very useful.',
      exampleTranslation: 'Por otro lado, es muy útil.',
      status: 'approved',
    },
    {
      id: 'voc_a2_its-obvious_313',
      word: "it's obvious",
      translation: 'es obvio',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪts ˈɑbviəs/',
      example: 'It\'s obvious that she is tired.',
      exampleTranslation: 'Es obvio que ella está cansada.',
      status: 'approved',
    },
    {
      id: 'voc_a2_clearly_314',
      word: 'clearly',
      translation: 'claramente',
      partOfSpeech: 'adverb',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈklɪrli/',
      example: 'Clearly, we need a new plan.',
      exampleTranslation: 'Claramente, necesitamos un nuevo plan.',
      status: 'approved',
    },
    {
      id: 'voc_a2_apparently_315',
      word: 'apparently',
      translation: 'aparentemente',
      partOfSpeech: 'adverb',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈpɛrəntli/',
      example: 'Apparently, the store closed early.',
      exampleTranslation: 'Aparentemente, la tienda cerró temprano.',
      status: 'approved',
    },
    {
      id: 'voc_a2_allegedly_316',
      word: 'allegedly',
      translation: 'supuestamente',
      partOfSpeech: 'adverb',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈlɛdʒədli/',
      example: 'He allegedly missed the flight.',
      exampleTranslation: 'Supuestamente él perdió el vuelo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_presumably_317',
      word: 'presumably',
      translation: 'presumiblemente',
      partOfSpeech: 'adverb',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/prɪˈzuməbli/',
      example: 'Presumably, they took another route.',
      exampleTranslation: 'Presumiblemente, tomaron otra ruta.',
      status: 'approved',
    },
    {
      id: 'voc_a2_undoubtedly_318',
      word: 'undoubtedly',
      translation: 'sin duda',
      partOfSpeech: 'adverb',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ʌnˈdaʊtɪdli/',
      example: 'This is undoubtedly the best option.',
      exampleTranslation: 'Esta es sin duda la mejor opción.',
      status: 'approved',
    },
    {
      id: 'voc_a2_arguably_319',
      word: 'arguably',
      translation: 'posiblemente/se podría decir',
      partOfSpeech: 'adverb',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɑrgjuəbli/',
      example: 'This is arguably her best book.',
      exampleTranslation: 'Este es posiblemente su mejor libro.',
      status: 'approved',
    },
    {
      id: 'voc_a2_in-my-experience_320',
      word: 'in my experience',
      translation: 'en mi experiencia',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪn maɪ ɪkˈspɪriəns/',
      example: 'In my experience, patience helps a lot.',
      exampleTranslation: 'En mi experiencia, la paciencia ayuda mucho.',
      status: 'approved',
    },
    {
      id: 'voc_a2_based-on_321',
      word: 'based on',
      translation: 'basado en',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/beɪst ɑn/',
      example: 'Based on the data, sales are growing.',
      exampleTranslation: 'Basado en los datos, las ventas están creciendo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_according-to_322',
      word: 'according to',
      translation: 'según',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈkɔrdɪŋ tu/',
      example: 'According to the report, prices went up.',
      exampleTranslation: 'Según el informe, los precios subieron.',
      status: 'approved',
    },
    {
      id: 'voc_a2_evidence_323',
      word: 'evidence',
      translation: 'evidencia',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɛvɪdəns/',
      example: 'There is no evidence for that claim.',
      exampleTranslation: 'No hay evidencia para esa afirmación.',
      status: 'approved',
    },
    {
      id: 'voc_a2_argument_324',
      word: 'argument',
      translation: 'argumento',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɑrgjəmənt/',
      example: 'Her argument was very convincing.',
      exampleTranslation: 'Su argumento fue muy convincente.',
      status: 'approved',
    },
    {
      id: 'voc_a2_viewpoint-standpoint_325',
      word: 'viewpoint / standpoint',
      translation: 'punto de vista',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈvjuˌpɔɪnt/',
      example: 'Consider his viewpoint too.',
      exampleTranslation: 'Considera también su punto de vista.',
      status: 'approved',
    },
    {
      id: 'voc_a2_counterargument_326',
      word: 'counterargument',
      translation: 'contraargumento',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkaʊntərˌɑrgjəmənt/',
      example: 'He didn\'t have a good counterargument.',
      exampleTranslation: 'Él no tenía un buen contraargumento.',
      status: 'approved',
    },
    {
      id: 'voc_a2_valid-point_327',
      word: 'valid point',
      translation: 'punto válido',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈvælɪd pɔɪnt/',
      example: 'That\'s a valid point.',
      exampleTranslation: 'Ese es un punto válido.',
      status: 'approved',
    },
    {
      id: 'voc_a2_convince_328',
      word: 'convince',
      translation: 'convencer',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kənˈvɪns/',
      example: 'I tried to convince her to stay.',
      exampleTranslation: 'Traté de convencerla de quedarse.',
      status: 'approved',
    },
    {
      id: 'voc_a2_persuade_329',
      word: 'persuade',
      translation: 'persuadir',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pərˈsweɪd/',
      example: 'He persuaded us to try the new restaurant.',
      exampleTranslation: 'Él nos persuadió de probar el nuevo restaurante.',
      status: 'approved',
    },
    {
      id: 'voc_a2_debate_330',
      word: 'debate',
      translation: 'debate',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dɪˈbeɪt/',
      example: 'They debated the topic for an hour.',
      exampleTranslation: 'Debatieron el tema durante una hora.',
      status: 'approved',
    },
    {
      id: 'voc_a2_controversy_331',
      word: 'controversy',
      translation: 'controversia',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkɑntrəˌvɜrsi/',
      example: 'The decision caused a lot of controversy.',
      exampleTranslation: 'La decisión causó mucha controversia.',
      status: 'approved',
    },
    {
      id: 'voc_a2_agree-to-disagree_332',
      word: 'agree to disagree',
      translation: 'acordar estar en desacuerdo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 6,
      topic: 'expresar-opiniones',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈgri tu dɪsəˈgri/',
      example: 'We decided to agree to disagree.',
      exampleTranslation: 'Decidimos acordar estar en desacuerdo.',
      status: 'approved',
    },
  ] as const,
}
