/**
 * A2 Level Content — Week 15
 * Topic: Personalidad y carácter
 * Curated from institutional curriculum (Zero AI)
 */
import type { ContentBlock } from '../types'

export const week15: ContentBlock = {
  level: 'A2',
  week: 15,
  topic: 'Personalidad y carácter',
  vocabulary: [
    {
      id: 'voc_a2_ambitious_687',
      word: 'ambitious',
      translation: 'ambicioso',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/æmˈbɪʃəs/',
      example: 'She is very ambitious about her career.',
      exampleTranslation: 'Ella es muy ambiciosa con su carrera.',
      status: 'approved',
    },
    {
      id: 'voc_a2_stubborn_688',
      word: 'stubborn',
      translation: 'terco',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈstʌbərn/',
      example: 'My brother is really stubborn.',
      exampleTranslation: 'Mi hermano es muy terco.',
      status: 'approved',
    },
    {
      id: 'voc_a2_arrogant_689',
      word: 'arrogant',
      translation: 'arrogante',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɛrəgənt/',
      example: 'He seemed arrogant during the meeting.',
      exampleTranslation: 'Él pareció arrogante durante la reunión.',
      status: 'approved',
    },
    {
      id: 'voc_a2_humble_690',
      word: 'humble',
      translation: 'humilde',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈhʌmbəl/',
      example: 'She stayed humble after winning.',
      exampleTranslation: 'Ella se mantuvo humilde después de ganar.',
      status: 'approved',
    },
    {
      id: 'voc_a2_reliable_691',
      word: 'reliable',
      translation: 'confiable',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rɪˈlaɪəbəl/',
      example: 'He is a reliable friend.',
      exampleTranslation: 'Él es un amigo confiable.',
      status: 'approved',
    },
    {
      id: 'voc_a2_trustworthy_692',
      word: 'trustworthy',
      translation: 'digno de confianza',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtrʌstˌwɜrði/',
      example: 'She is a trustworthy person.',
      exampleTranslation: 'Ella es una persona digna de confianza.',
      status: 'approved',
    },
    {
      id: 'voc_a2_sociable_693',
      word: 'sociable',
      translation: 'sociable',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsoʊʃəbəl/',
      example: 'My cousin is very sociable.',
      exampleTranslation: 'Mi primo es muy sociable.',
      status: 'approved',
    },
    {
      id: 'voc_a2_introverted_694',
      word: 'introverted',
      translation: 'introvertido',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɪntroʊˌvɜrtɪd/',
      example: 'He is more introverted than his sister.',
      exampleTranslation: 'Él es más introvertido que su hermana.',
      status: 'approved',
    },
    {
      id: 'voc_a2_extroverted_695',
      word: 'extroverted',
      translation: 'extrovertido',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɛkstroʊˌvɜrtɪd/',
      example: 'She is extroverted and outgoing.',
      exampleTranslation: 'Ella es extrovertida y abierta.',
      status: 'approved',
    },
    {
      id: 'voc_a2_open-minded_696',
      word: 'open-minded',
      translation: 'de mente abierta',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈoʊpənˈmaɪndɪd/',
      example: 'My boss is very open-minded.',
      exampleTranslation: 'Mi jefe tiene mente muy abierta.',
      status: 'approved',
    },
    {
      id: 'voc_a2_closed-minded_697',
      word: 'closed-minded',
      translation: 'cerrado de mente',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkloʊzdˈmaɪndɪd/',
      example: 'Don\'t be closed-minded about new ideas.',
      exampleTranslation: 'No seas de mente cerrada con ideas nuevas.',
      status: 'approved',
    },
    {
      id: 'voc_a2_judgmental_698',
      word: 'judgmental',
      translation: 'crítico/juzgón',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dʒʌdʒˈmɛntəl/',
      example: 'Try not to be judgmental.',
      exampleTranslation: 'Trata de no ser crítico/juzgón.',
      status: 'approved',
    },
    {
      id: 'voc_a2_optimistic_699',
      word: 'optimistic',
      translation: 'optimista',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌɑptɪˈmɪstɪk/',
      example: 'She is always optimistic.',
      exampleTranslation: 'Ella siempre es optimista.',
      status: 'approved',
    },
    {
      id: 'voc_a2_pessimistic_700',
      word: 'pessimistic',
      translation: 'pesimista',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌpɛsəˈmɪstɪk/',
      example: 'He can be a bit pessimistic.',
      exampleTranslation: 'Él puede ser un poco pesimista.',
      status: 'approved',
    },
    {
      id: 'voc_a2_realistic_701',
      word: 'realistic',
      translation: 'realista',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌriəˈlɪstɪk/',
      example: 'Let\'s be realistic about the timeline.',
      exampleTranslation: 'Seamos realistas sobre el tiempo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_idealistic_702',
      word: 'idealistic',
      translation: 'idealista',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/aɪˌdiəˈlɪstɪk/',
      example: 'He has idealistic views on society.',
      exampleTranslation: 'Él tiene visiones idealistas sobre la sociedad.',
      status: 'approved',
    },
    {
      id: 'voc_a2_assertive_703',
      word: 'assertive',
      translation: 'asertivo',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈsɜrtɪv/',
      example: 'You need to be more assertive.',
      exampleTranslation: 'Necesitas ser más asertivo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_passive_704',
      word: 'passive',
      translation: 'pasivo',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpæsɪv/',
      example: 'He is too passive at work.',
      exampleTranslation: 'Él es demasiado pasivo en el trabajo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_aggressive_705',
      word: 'aggressive',
      translation: 'agresivo',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈgrɛsɪv/',
      example: 'Don\'t be aggressive during the debate.',
      exampleTranslation: 'No seas agresivo durante el debate.',
      status: 'approved',
    },
    {
      id: 'voc_a2_competitive_706',
      word: 'competitive',
      translation: 'competitivo',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kəmˈpɛtɪtɪv/',
      example: 'She is very competitive in sports.',
      exampleTranslation: 'Ella es muy competitiva en los deportes.',
      status: 'approved',
    },
    {
      id: 'voc_a2_cooperative_707',
      word: 'cooperative',
      translation: 'cooperativo',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/koʊˈɑpərətɪv/',
      example: 'The whole team was cooperative.',
      exampleTranslation: 'Todo el equipo fue cooperativo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_independent_708',
      word: 'independent',
      translation: 'independiente',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌɪndɪˈpɛndənt/',
      example: 'My daughter is very independent.',
      exampleTranslation: 'Mi hija es muy independiente.',
      status: 'approved',
    },
    {
      id: 'voc_a2_dependent_709',
      word: 'dependent',
      translation: 'dependiente',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dɪˈpɛndənt/',
      example: 'He is too dependent on his phone.',
      exampleTranslation: 'Él es demasiado dependiente de su teléfono.',
      status: 'approved',
    },
    {
      id: 'voc_a2_mature_710',
      word: 'mature',
      translation: 'maduro',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/məˈtʃʊr/',
      example: 'She is mature for her age.',
      exampleTranslation: 'Ella es madura para su edad.',
      status: 'approved',
    },
    {
      id: 'voc_a2_immature_711',
      word: 'immature',
      translation: 'inmaduro',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌɪməˈtʃʊr/',
      example: 'He acted immature at the party.',
      exampleTranslation: 'Él actuó de forma inmadura en la fiesta.',
      status: 'approved',
    },
    {
      id: 'voc_a2_responsible_712',
      word: 'responsible',
      translation: 'responsable',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rɪˈspɑnsəbəl/',
      example: 'She is a responsible employee.',
      exampleTranslation: 'Ella es una empleada responsable.',
      status: 'approved',
    },
    {
      id: 'voc_a2_irresponsible_713',
      word: 'irresponsible',
      translation: 'irresponsable',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌɪrɪˈspɑnsəbəl/',
      example: 'It was irresponsible to leave early.',
      exampleTranslation: 'Fue irresponsable irse temprano.',
      status: 'approved',
    },
    {
      id: 'voc_a2_disciplined_714',
      word: 'disciplined',
      translation: 'disciplinado',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdɪsəplɪnd/',
      example: 'He is very disciplined about studying.',
      exampleTranslation: 'Él es muy disciplinado con el estudio.',
      status: 'approved',
    },
    {
      id: 'voc_a2_spontaneous_715',
      word: 'spontaneous',
      translation: 'espontáneo',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/spɑnˈteɪniəs/',
      example: 'She is spontaneous and fun.',
      exampleTranslation: 'Ella es espontánea y divertida.',
      status: 'approved',
    },
    {
      id: 'voc_a2_cautious_716',
      word: 'cautious',
      translation: 'cauteloso',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkɔʃəs/',
      example: 'Be cautious near the edge.',
      exampleTranslation: 'Ten cuidado cerca del borde.',
      status: 'approved',
    },
    {
      id: 'voc_a2_adventurous_717',
      word: 'adventurous',
      translation: 'aventurero',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ædˈvɛntʃərəs/',
      example: 'My father is an adventurous person.',
      exampleTranslation: 'Mi padre es una persona aventurera.',
      status: 'approved',
    },
    {
      id: 'voc_a2_creative_718',
      word: 'creative',
      translation: 'creativo',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kriˈeɪtɪv/',
      example: 'She has a creative mind.',
      exampleTranslation: 'Ella tiene una mente creativa.',
      status: 'approved',
    },
    {
      id: 'voc_a2_logical_719',
      word: 'logical',
      translation: 'lógico',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈlɑdʒɪkəl/',
      example: 'His argument was very logical.',
      exampleTranslation: 'Su argumento fue muy lógico.',
      status: 'approved',
    },
    {
      id: 'voc_a2_analytical_720',
      word: 'analytical',
      translation: 'analítico',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌænəˈlɪtɪkəl/',
      example: 'She has an analytical approach to problems.',
      exampleTranslation: 'Ella tiene un enfoque analítico ante los problemas.',
      status: 'approved',
    },
    {
      id: 'voc_a2_intuitive_721',
      word: 'intuitive',
      translation: 'intuitivo',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪnˈtuɪtɪv/',
      example: 'He made an intuitive decision.',
      exampleTranslation: 'Él tomó una decisión intuitiva.',
      status: 'approved',
    },
    {
      id: 'voc_a2_perceptive_722',
      word: 'perceptive',
      translation: 'perceptivo',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pərˈsɛptɪv/',
      example: 'She is very perceptive about people.',
      exampleTranslation: 'Ella es muy perceptiva con las personas.',
      status: 'approved',
    },
    {
      id: 'voc_a2_charismatic_723',
      word: 'charismatic',
      translation: 'carismático',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌkɛrɪzˈmætɪk/',
      example: 'The speaker was charismatic and funny.',
      exampleTranslation: 'El orador fue carismático y gracioso.',
      status: 'approved',
    },
    {
      id: 'voc_a2_witty_724',
      word: 'witty',
      translation: 'ingenioso',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈwɪti/',
      example: 'He is known for his witty comments.',
      exampleTranslation: 'Él es conocido por sus comentarios ingeniosos.',
      status: 'approved',
    },
    {
      id: 'voc_a2_sarcastic_725',
      word: 'sarcastic',
      translation: 'sarcástico',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/sɑrˈkæstɪk/',
      example: 'Her tone was a bit sarcastic.',
      exampleTranslation: 'Su tono fue un poco sarcástico.',
      status: 'approved',
    },
    {
      id: 'voc_a2_blunt_726',
      word: 'blunt',
      translation: 'directo/franco',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/blʌnt/',
      example: 'He is very blunt with his opinions.',
      exampleTranslation: 'Él es muy directo con sus opiniones.',
      status: 'approved',
    },
    {
      id: 'voc_a2_diplomatic_727',
      word: 'diplomatic',
      translation: 'diplomático',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌdɪpləˈmætɪk/',
      example: 'She handled the situation in a diplomatic way.',
      exampleTranslation: 'Ella manejó la situación de forma diplomática.',
      status: 'approved',
    },
    {
      id: 'voc_a2_tactful_728',
      word: 'tactful',
      translation: 'con tacto',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtæktfəl/',
      example: 'He gave tactful feedback.',
      exampleTranslation: 'Él dio retroalimentación con tacto.',
      status: 'approved',
    },
    {
      id: 'voc_a2_insensitive_729',
      word: 'insensitive',
      translation: 'insensible',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪnˈsɛnsɪtɪv/',
      example: 'That comment was a bit insensitive.',
      exampleTranslation: 'Ese comentario fue un poco insensible.',
      status: 'approved',
    },
    {
      id: 'voc_a2_thoughtful_730',
      word: 'thoughtful',
      translation: 'considerado',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈθɔtfəl/',
      example: 'It was a thoughtful gift.',
      exampleTranslation: 'Fue un regalo considerado.',
      status: 'approved',
    },
    {
      id: 'voc_a2_forgetful_731',
      word: 'forgetful',
      translation: 'olvidadizo',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fərˈgɛtfəl/',
      example: 'My grandfather is a bit forgetful now.',
      exampleTranslation: 'Mi abuelo es un poco olvidadizo ahora.',
      status: 'approved',
    },
    {
      id: 'voc_a2_punctual_732',
      word: 'punctual',
      translation: 'puntual',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpʌŋktʃuəl/',
      example: 'She is always punctual.',
      exampleTranslation: 'Ella siempre es puntual.',
      status: 'approved',
    },
    {
      id: 'voc_a2_easygoing_733',
      word: 'easygoing',
      translation: 'de trato fácil',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈiziˌgoʊɪŋ/',
      example: 'He has an easygoing personality.',
      exampleTranslation: 'Él tiene una personalidad de trato fácil.',
      status: 'approved',
    },
    {
      id: 'voc_a2_demanding_734',
      word: 'demanding',
      translation: 'exigente',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 15,
      topic: 'personalidad-y-car-c',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dɪˈmændɪŋ/',
      example: 'Her job is very demanding.',
      exampleTranslation: 'Su trabajo es muy exigente.',
      status: 'approved',
    },
  ] as const,
}
