/**
 * A2 Level Content — Week 08
 * Topic: Educación y estudios superiores
 * Curated from institutional curriculum (Zero AI)
 */
import type { ContentBlock } from '../types'

export const week08: ContentBlock = {
  level: 'A2',
  week: 8,
  topic: 'Educación y estudios superiores',
  vocabulary: [
    {
      id: 'voc_a2_enroll_367',
      word: 'enroll',
      translation: 'inscribirse',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_tuition_368',
      word: 'tuition',
      translation: 'matrícula (costo)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_scholarship_369',
      word: 'scholarship',
      translation: 'beca',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_semester_370',
      word: 'semester',
      translation: 'semestre',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_syllabus_371',
      word: 'syllabus',
      translation: 'programa del curso',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_lecture_372',
      word: 'lecture',
      translation: 'clase magistral',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_seminar_373',
      word: 'seminar',
      translation: 'seminario',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_thesis_374',
      word: 'thesis',
      translation: 'tesis',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_dissertation_375',
      word: 'dissertation',
      translation: 'tesis doctoral',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_major_376',
      word: 'major (field of study)',
      translation: 'carrera principal',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_minor_377',
      word: 'minor (field of study)',
      translation: 'especialización secundaria',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_gpa_378',
      word: 'GPA',
      translation: 'promedio académico',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_transcript_379',
      word: 'transcript',
      translation: 'historial académico',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_diploma_380',
      word: 'diploma',
      translation: 'diploma',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_certificate_381',
      word: 'certificate',
      translation: 'certificado',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_campus_382',
      word: 'campus',
      translation: 'campus',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_dormitory_383',
      word: 'dormitory',
      translation: 'residencia estudiantil',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_faculty_384',
      word: 'faculty',
      translation: 'facultad/cuerpo docente',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_professor_385',
      word: 'professor',
      translation: 'profesor universitario',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_academic-advisor_386',
      word: 'academic advisor',
      translation: 'asesor académico',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_plagiarism_387',
      word: 'plagiarism',
      translation: 'plagio',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_assignment_388',
      word: 'assignment',
      translation: 'tarea/trabajo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_essay_389',
      word: 'essay',
      translation: 'ensayo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_research-paper_390',
      word: 'research paper',
      translation: 'trabajo de investigación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_citation_391',
      word: 'citation',
      translation: 'cita bibliográfica',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_bibliography_392',
      word: 'bibliography',
      translation: 'bibliografía',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_peer-review_393',
      word: 'peer review',
      translation: 'revisión por pares',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_graduate_394',
      word: 'graduate',
      translation: 'graduado',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_undergraduate_395',
      word: 'undergraduate',
      translation: 'estudiante de pregrado',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_postgraduate_396',
      word: 'postgraduate',
      translation: 'posgrado',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_internship_397',
      word: 'internship',
      translation: 'pasantía',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_apprenticeship_398',
      word: 'apprenticeship',
      translation: 'aprendizaje (oficio)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_vocational-training_399',
      word: 'vocational training',
      translation: 'formación profesional',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_distance-learning_400',
      word: 'distance learning',
      translation: 'educación a distancia',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_online-course_401',
      word: 'online course',
      translation: 'curso en línea',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_tutor_402',
      word: 'tutor',
      translation: 'tutor',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_mentor_403',
      word: 'mentor',
      translation: 'mentor',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_extracurricular_404',
      word: 'extracurricular',
      translation: 'extracurricular',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_student-loan_405',
      word: 'student loan',
      translation: 'préstamo estudiantil',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_financial-aid_406',
      word: 'financial aid',
      translation: 'ayuda financiera',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_dropout_407',
      word: 'dropout',
      translation: 'abandono escolar',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_literacy_408',
      word: 'literacy',
      translation: 'alfabetización',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_curriculum_409',
      word: 'curriculum',
      translation: 'plan de estudios',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_elective_410',
      word: 'elective',
      translation: 'materia electiva',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_credit-hour_411',
      word: 'credit hour',
      translation: 'hora crédito',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_exam-period_412',
      word: 'exam period',
      translation: 'periodo de exámenes',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 8,
      topic: 'educaci-n-y-estudios',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
  ] as const,
}
