/**
 * A2 Level Content — Week 13
 * Topic: Deportes y vida activa
 * Curated from institutional curriculum (Zero AI)
 */
import type { ContentBlock } from '../types'

export const week13: ContentBlock = {
  level: 'A2',
  week: 13,
  topic: 'Deportes y vida activa',
  vocabulary: [
    {
      id: 'voc_a2_tournament_605',
      word: 'tournament',
      translation: 'torneo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtʊrnəmənt/',
      example: 'Our team won the tournament.',
      exampleTranslation: 'Nuestro equipo ganó el torneo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_league_606',
      word: 'league',
      translation: 'liga',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/lig/',
      example: 'He plays in the local league.',
      exampleTranslation: 'Él juega en la liga local.',
      status: 'approved',
    },
    {
      id: 'voc_a2_teammate_607',
      word: 'teammate',
      translation: 'compañero de equipo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtiˌmeɪt/',
      example: 'My teammate passed me the ball.',
      exampleTranslation: 'Mi compañero de equipo me pasó la pelota.',
      status: 'approved',
    },
    {
      id: 'voc_a2_opponent_608',
      word: 'opponent',
      translation: 'oponente',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈpoʊnənt/',
      example: 'Our opponent played very well.',
      exampleTranslation: 'Nuestro oponente jugó muy bien.',
      status: 'approved',
    },
    {
      id: 'voc_a2_warm-up_609',
      word: 'warm-up',
      translation: 'calentamiento',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈwɔrmˌʌp/',
      example: 'Do a warm-up before running.',
      exampleTranslation: 'Haz un calentamiento antes de correr.',
      status: 'approved',
    },
    {
      id: 'voc_a2_stretch_610',
      word: 'stretch',
      translation: 'estirar',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/strɛtʃ/',
      example: 'Stretch your legs before exercise.',
      exampleTranslation: 'Estira las piernas antes de hacer ejercicio.',
      status: 'approved',
    },
    {
      id: 'voc_a2_stamina_611',
      word: 'stamina',
      translation: 'resistencia',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈstæmənə/',
      example: 'Running builds stamina.',
      exampleTranslation: 'Correr desarrolla resistencia.',
      status: 'approved',
    },
    {
      id: 'voc_a2_cardio_612',
      word: 'cardio',
      translation: 'cardio',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkɑrdioʊ/',
      example: 'I do cardio three times a week.',
      exampleTranslation: 'Hago cardio tres veces por semana.',
      status: 'approved',
    },
    {
      id: 'voc_a2_strength-training_613',
      word: 'strength training',
      translation: 'entrenamiento de fuerza',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/strɛŋθ ˈtreɪnɪŋ/',
      example: 'Strength training helps build muscle.',
      exampleTranslation: 'El entrenamiento de fuerza ayuda a formar músculo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_personal-trainer_614',
      word: 'personal trainer',
      translation: 'entrenador personal',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpɜrsənəl ˈtreɪnər/',
      example: 'She works with a personal trainer.',
      exampleTranslation: 'Ella trabaja con un entrenador personal.',
      status: 'approved',
    },
    {
      id: 'voc_a2_workout_615',
      word: 'workout',
      translation: 'rutina de ejercicio',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈwɜrˌkaʊt/',
      example: 'My workout takes an hour.',
      exampleTranslation: 'Mi rutina de ejercicio toma una hora.',
      status: 'approved',
    },
    {
      id: 'voc_a2_set_616',
      word: 'set (exercise)',
      translation: 'serie (ejercicio)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/sɛt/',
      example: 'Do three sets of ten.',
      exampleTranslation: 'Haz tres series de diez.',
      status: 'approved',
    },
    {
      id: 'voc_a2_rep-repetition_617',
      word: 'rep / repetition',
      translation: 'repetición',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rɛp/',
      example: 'Try to do more reps.',
      exampleTranslation: 'Intenta hacer más repeticiones.',
      status: 'approved',
    },
    {
      id: 'voc_a2_marathon_618',
      word: 'marathon',
      translation: 'maratón',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmɛrəˌθɑn/',
      example: 'She finished her first marathon.',
      exampleTranslation: 'Ella terminó su primer maratón.',
      status: 'approved',
    },
    {
      id: 'voc_a2_sprint_619',
      word: 'sprint',
      translation: 'carrera corta/esprintar',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/sprɪnt/',
      example: 'He sprinted to the finish line.',
      exampleTranslation: 'Él corrió a toda velocidad hasta la meta.',
      status: 'approved',
    },
    {
      id: 'voc_a2_finish-line_620',
      word: 'finish line',
      translation: 'línea de meta',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfɪnɪʃ laɪn/',
      example: 'She crossed the finish line first.',
      exampleTranslation: 'Ella cruzó la línea de meta primero.',
      status: 'approved',
    },
    {
      id: 'voc_a2_medal_621',
      word: 'medal',
      translation: 'medalla',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmɛdəl/',
      example: 'He won a gold medal.',
      exampleTranslation: 'Él ganó una medalla de oro.',
      status: 'approved',
    },
    {
      id: 'voc_a2_trophy_622',
      word: 'trophy',
      translation: 'trofeo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtroʊfi/',
      example: 'The team lifted the trophy.',
      exampleTranslation: 'El equipo levantó el trofeo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_record_623',
      word: 'record (sports)',
      translation: 'récord',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈrɛkərd/',
      example: 'She broke the school record.',
      exampleTranslation: 'Ella rompió el récord escolar.',
      status: 'approved',
    },
    {
      id: 'voc_a2_draw_624',
      word: 'draw (tie)',
      translation: 'empate',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/drɔ/',
      example: 'The match ended in a draw.',
      exampleTranslation: 'El partido terminó en empate.',
      status: 'approved',
    },
    {
      id: 'voc_a2_penalty_625',
      word: 'penalty',
      translation: 'penalti',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpɛnəlti/',
      example: 'The referee gave a penalty.',
      exampleTranslation: 'El árbitro marcó un penalti.',
      status: 'approved',
    },
    {
      id: 'voc_a2_foul_626',
      word: 'foul',
      translation: 'falta',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/faʊl/',
      example: 'That was a clear foul.',
      exampleTranslation: 'Esa fue una falta clara.',
      status: 'approved',
    },
    {
      id: 'voc_a2_injury-time_627',
      word: 'injury time',
      translation: 'tiempo de descuento',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɪndʒəri taɪm/',
      example: 'They scored during injury time.',
      exampleTranslation: 'Anotaron durante el tiempo de descuento.',
      status: 'approved',
    },
    {
      id: 'voc_a2_substitute_628',
      word: 'substitute (player)',
      translation: 'suplente',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsʌbstɪˌtut/',
      example: 'The substitute scored the winning goal.',
      exampleTranslation: 'El suplente anotó el gol de la victoria.',
      status: 'approved',
    },
    {
      id: 'voc_a2_spectator_629',
      word: 'spectator',
      translation: 'espectador',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈspɛkteɪtər/',
      example: 'Thousands of spectators watched the game.',
      exampleTranslation: 'Miles de espectadores vieron el partido.',
      status: 'approved',
    },
    {
      id: 'voc_a2_scoreboard_630',
      word: 'scoreboard',
      translation: 'marcador',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈskɔrˌbɔrd/',
      example: 'Check the scoreboard for the result.',
      exampleTranslation: 'Revisa el marcador para ver el resultado.',
      status: 'approved',
    },
    {
      id: 'voc_a2_halftime_631',
      word: 'halftime',
      translation: 'medio tiempo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈhæfˌtaɪm/',
      example: 'The coach talked to the team at halftime.',
      exampleTranslation: 'El entrenador habló con el equipo en el medio tiempo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_locker-room_632',
      word: 'locker room',
      translation: 'vestuario',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈlɑkər rum/',
      example: 'The players are in the locker room.',
      exampleTranslation: 'Los jugadores están en el vestuario.',
      status: 'approved',
    },
    {
      id: 'voc_a2_equipment_633',
      word: 'equipment (sports)',
      translation: 'equipo (deportivo)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪˈkwɪpmənt/',
      example: 'Bring your own equipment.',
      exampleTranslation: 'Trae tu propio equipo.',
      status: 'approved',
    },
    {
      id: 'voc_a2_helmet_634',
      word: 'helmet',
      translation: 'casco',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈhɛlmɪt/',
      example: 'Always wear a helmet.',
      exampleTranslation: 'Siempre usa casco.',
      status: 'approved',
    },
    {
      id: 'voc_a2_mat_635',
      word: 'mat (exercise)',
      translation: 'colchoneta',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/mæt/',
      example: 'Put your mat on the floor.',
      exampleTranslation: 'Pon tu colchoneta en el piso.',
      status: 'approved',
    },
    {
      id: 'voc_a2_treadmill_636',
      word: 'treadmill',
      translation: 'cinta de correr',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtrɛdˌmɪl/',
      example: 'I ran on the treadmill for thirty minutes.',
      exampleTranslation: 'Corrí en la cinta de correr treinta minutos.',
      status: 'approved',
    },
    {
      id: 'voc_a2_dumbbell_637',
      word: 'dumbbell',
      translation: 'mancuerna',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdʌmˌbɛl/',
      example: 'Lift the dumbbell slowly.',
      exampleTranslation: 'Levanta la mancuerna despacio.',
      status: 'approved',
    },
    {
      id: 'voc_a2_flexibility_638',
      word: 'flexibility',
      translation: 'flexibilidad',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌflɛksəˈbɪləti/',
      example: 'Yoga improves flexibility.',
      exampleTranslation: 'El yoga mejora la flexibilidad.',
      status: 'approved',
    },
    {
      id: 'voc_a2_endurance_639',
      word: 'endurance',
      translation: 'resistencia (física)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪnˈdʊrəns/',
      example: 'Cycling improves endurance.',
      exampleTranslation: 'El ciclismo mejora la resistencia.',
      status: 'approved',
    },
    {
      id: 'voc_a2_posture_640',
      word: 'posture',
      translation: 'postura',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpɑstʃər/',
      example: 'Fix your posture when you sit.',
      exampleTranslation: 'Corrige tu postura al sentarte.',
      status: 'approved',
    },
    {
      id: 'voc_a2_physical-fitness_641',
      word: 'physical fitness',
      translation: 'aptitud física',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfɪzɪkəl ˈfɪtnəs/',
      example: 'Physical fitness improves your health.',
      exampleTranslation: 'La aptitud física mejora tu salud.',
      status: 'approved',
    },
    {
      id: 'voc_a2_recreational_642',
      word: 'recreational',
      translation: 'recreativo',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌrɛkriˈeɪʃənəl/',
      example: 'We play recreational soccer on Sundays.',
      exampleTranslation: 'Jugamos fútbol recreativo los domingos.',
      status: 'approved',
    },
    {
      id: 'voc_a2_outdoor-activity_643',
      word: 'outdoor activity',
      translation: 'actividad al aire libre',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈaʊtˌdɔr ækˈtɪvəti/',
      example: 'Hiking is a great outdoor activity.',
      exampleTranslation: 'El senderismo es una gran actividad al aire libre.',
      status: 'approved',
    },
    {
      id: 'voc_a2_adventure-sport_644',
      word: 'adventure sport',
      translation: 'deporte de aventura',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 13,
      topic: 'deportes-y-vida-acti',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ædˈvɛntʃər spɔrt/',
      example: 'Rock climbing is an adventure sport.',
      exampleTranslation: 'La escalada es un deporte de aventura.',
      status: 'approved',
    },
  ] as const,
}
