/**
 * A2 Level Content — Week 07
 * Topic: Clima y desastres naturales
 * Curated from institutional curriculum (Zero AI)
 */
import type { ContentBlock } from '../types'

export const week07: ContentBlock = {
  level: 'A2',
  week: 7,
  topic: 'Clima y desastres naturales',
  vocabulary: [
    {
      id: 'voc_a2_heatwave_333',
      word: 'heatwave',
      translation: 'ola de calor',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈhitˌweɪv/',
      example: 'A heatwave hit the city last week.',
      exampleTranslation: 'Una ola de calor golpeó la ciudad la semana pasada.',
      status: 'approved',
    },
    {
      id: 'voc_a2_wildfire_334',
      word: 'wildfire',
      translation: 'incendio forestal',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈwaɪldˌfaɪər/',
      example: 'The wildfire destroyed many acres of forest.',
      exampleTranslation: 'El incendio forestal destruyó muchos acres de bosque.',
      status: 'approved',
    },
    {
      id: 'voc_a2_hurricane_335',
      word: 'hurricane',
      translation: 'huracán',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈhɜrəˌkeɪn/',
      example: 'The hurricane hit the coast at midnight.',
      exampleTranslation: 'El huracán golpeó la costa a medianoche.',
      status: 'approved',
    },
    {
      id: 'voc_a2_tornado_336',
      word: 'tornado',
      translation: 'tornado',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tɔrˈneɪˌdoʊ/',
      example: 'A tornado destroyed several houses.',
      exampleTranslation: 'Un tornado destruyó varias casas.',
      status: 'approved',
    },
    {
      id: 'voc_a2_tsunami_337',
      word: 'tsunami',
      translation: 'tsunami',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tsuˈnɑmi/',
      example: 'The tsunami warning was issued quickly.',
      exampleTranslation: 'La alerta de tsunami se emitió rápidamente.',
      status: 'approved',
    },
    {
      id: 'voc_a2_avalanche_338',
      word: 'avalanche',
      translation: 'avalancha',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈævəˌlæntʃ/',
      example: 'The avalanche blocked the mountain road.',
      exampleTranslation: 'La avalancha bloqueó el camino de la montaña.',
      status: 'approved',
    },
    {
      id: 'voc_a2_landslide_339',
      word: 'landslide',
      translation: 'deslizamiento de tierra',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈlændˌslaɪd/',
      example: 'The landslide damaged several homes.',
      exampleTranslation: 'El deslizamiento de tierra dañó varias casas.',
      status: 'approved',
    },
    {
      id: 'voc_a2_blizzard_340',
      word: 'blizzard',
      translation: 'ventisca',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈblɪzərd/',
      example: 'The blizzard closed all the schools.',
      exampleTranslation: 'La ventisca cerró todas las escuelas.',
      status: 'approved',
    },
    {
      id: 'voc_a2_hailstorm_341',
      word: 'hailstorm',
      translation: 'granizada',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈheɪlˌstɔrm/',
      example: 'The hailstorm damaged the crops.',
      exampleTranslation: 'La granizada dañó los cultivos.',
      status: 'approved',
    },
    {
      id: 'voc_a2_thunderstorm_342',
      word: 'thunderstorm',
      translation: 'tormenta eléctrica',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈθʌndərˌstɔrm/',
      example: 'A thunderstorm is coming tonight.',
      exampleTranslation: 'Una tormenta eléctrica se acerca esta noche.',
      status: 'approved',
    },
    {
      id: 'voc_a2_temperature-drop_343',
      word: 'temperature drop',
      translation: 'descenso de temperatura',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtɛmpərətʃər drɑp/',
      example: 'There was a sudden temperature drop.',
      exampleTranslation: 'Hubo un descenso repentino de temperatura.',
      status: 'approved',
    },
    {
      id: 'voc_a2_climate-change_344',
      word: 'climate change',
      translation: 'cambio climático',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈklaɪmɪt tʃeɪndʒ/',
      example: 'Climate change affects the whole planet.',
      exampleTranslation: 'El cambio climático afecta a todo el planeta.',
      status: 'approved',
    },
    {
      id: 'voc_a2_global-warming_345',
      word: 'global warming',
      translation: 'calentamiento global',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈgloʊbəl ˈwɔrmɪŋ/',
      example: 'Global warming is a serious issue.',
      exampleTranslation: 'El calentamiento global es un problema serio.',
      status: 'approved',
    },
    {
      id: 'voc_a2_greenhouse-effect_346',
      word: 'greenhouse effect',
      translation: 'efecto invernadero',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈgrinˌhaʊs ɪˈfɛkt/',
      example: 'The greenhouse effect traps heat in the atmosphere.',
      exampleTranslation: 'El efecto invernadero atrapa el calor en la atmósfera.',
      status: 'approved',
    },
    {
      id: 'voc_a2_carbon-footprint_347',
      word: 'carbon footprint',
      translation: 'huella de carbono',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkɑrbən ˈfʊtˌprɪnt/',
      example: 'We should reduce our carbon footprint.',
      exampleTranslation: 'Deberíamos reducir nuestra huella de carbono.',
      status: 'approved',
    },
    {
      id: 'voc_a2_renewable-energy_348',
      word: 'renewable energy',
      translation: 'energía renovable',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rɪˈnuəbəl ˈɛnərdʒi/',
      example: 'The country invests in renewable energy.',
      exampleTranslation: 'El país invierte en energía renovable.',
      status: 'approved',
    },
    {
      id: 'voc_a2_deforestation_349',
      word: 'deforestation',
      translation: 'deforestación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/diˌfɔrɪˈsteɪʃən/',
      example: 'Deforestation harms many animal species.',
      exampleTranslation: 'La deforestación daña a muchas especies animales.',
      status: 'approved',
    },
    {
      id: 'voc_a2_extinction_350',
      word: 'extinction',
      translation: 'extinción',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪkˈstɪŋkʃən/',
      example: 'This species is close to extinction.',
      exampleTranslation: 'Esta especie está cerca de la extinción.',
      status: 'approved',
    },
    {
      id: 'voc_a2_endangered-species_351',
      word: 'endangered species',
      translation: 'especie en peligro',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪnˈdeɪndʒərd ˈspiʃiz/',
      example: 'Pandas are an endangered species.',
      exampleTranslation: 'Los pandas son una especie en peligro.',
      status: 'approved',
    },
    {
      id: 'voc_a2_natural-disaster_352',
      word: 'natural disaster',
      translation: 'desastre natural',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈnætʃərəl dɪˈzæstər/',
      example: 'The government responded quickly to the natural disaster.',
      exampleTranslation: 'El gobierno respondió rápido al desastre natural.',
      status: 'approved',
    },
    {
      id: 'voc_a2_shelter_353',
      word: 'shelter (emergency)',
      translation: 'refugio',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈʃɛltər/',
      example: 'Families went to the shelter for safety.',
      exampleTranslation: 'Las familias fueron al refugio por seguridad.',
      status: 'approved',
    },
    {
      id: 'voc_a2_relief-effort_354',
      word: 'relief effort',
      translation: 'esfuerzo de ayuda',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rɪˈlif ˈɛfərt/',
      example: 'The relief effort helped thousands of people.',
      exampleTranslation: 'El esfuerzo de ayuda ayudó a miles de personas.',
      status: 'approved',
    },
    {
      id: 'voc_a2_damage_355',
      word: 'damage',
      translation: 'daño',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdæmɪdʒ/',
      example: 'The storm caused a lot of damage.',
      exampleTranslation: 'La tormenta causó mucho daño.',
      status: 'approved',
    },
    {
      id: 'voc_a2_destruction_356',
      word: 'destruction',
      translation: 'destrucción',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dɪˈstrʌkʃən/',
      example: 'The destruction was visible everywhere.',
      exampleTranslation: 'La destrucción era visible en todas partes.',
      status: 'approved',
    },
    {
      id: 'voc_a2_rebuild_357',
      word: 'rebuild',
      translation: 'reconstruir',
      partOfSpeech: 'verb',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/riˈbɪld/',
      example: 'They will rebuild the school next year.',
      exampleTranslation: 'Reconstruirán la escuela el próximo año.',
      status: 'approved',
    },
    {
      id: 'voc_a2_warning-system_358',
      word: 'warning system',
      translation: 'sistema de alerta',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈwɔrnɪŋ ˈsɪstəm/',
      example: 'The warning system saved many lives.',
      exampleTranslation: 'El sistema de alerta salvó muchas vidas.',
      status: 'approved',
    },
    {
      id: 'voc_a2_meteorologist_359',
      word: 'meteorologist',
      translation: 'meteorólogo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌmitiərˈɑlədʒɪst/',
      example: 'The meteorologist predicted heavy rain.',
      exampleTranslation: 'El meteorólogo predijo lluvia fuerte.',
      status: 'approved',
    },
    {
      id: 'voc_a2_atmosphere_360',
      word: 'atmosphere',
      translation: 'atmósfera',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈætməsˌfɪr/',
      example: 'Pollution affects the atmosphere.',
      exampleTranslation: 'La contaminación afecta la atmósfera.',
      status: 'approved',
    },
    {
      id: 'voc_a2_ozone-layer_361',
      word: 'ozone layer',
      translation: 'capa de ozono',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈoʊˌzoʊn ˈleɪər/',
      example: 'The ozone layer protects us from the sun.',
      exampleTranslation: 'La capa de ozono nos protege del sol.',
      status: 'approved',
    },
    {
      id: 'voc_a2_ecosystem_362',
      word: 'ecosystem',
      translation: 'ecosistema',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈikoʊˌsɪstəm/',
      example: 'This ecosystem has many species.',
      exampleTranslation: 'Este ecosistema tiene muchas especies.',
      status: 'approved',
    },
    {
      id: 'voc_a2_biodiversity_363',
      word: 'biodiversity',
      translation: 'biodiversidad',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌbaɪoʊdaɪˈvɜrsəti/',
      example: 'The rainforest has incredible biodiversity.',
      exampleTranslation: 'La selva tropical tiene una biodiversidad increíble.',
      status: 'approved',
    },
    {
      id: 'voc_a2_sustainability_364',
      word: 'sustainability',
      translation: 'sostenibilidad',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/səˌsteɪnəˈbɪləti/',
      example: 'The company focuses on sustainability.',
      exampleTranslation: 'La empresa se enfoca en la sostenibilidad.',
      status: 'approved',
    },
    {
      id: 'voc_a2_emission_365',
      word: 'emission',
      translation: 'emisión',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪˈmɪʃən/',
      example: 'We need to reduce carbon emissions.',
      exampleTranslation: 'Necesitamos reducir las emisiones de carbono.',
      status: 'approved',
    },
    {
      id: 'voc_a2_fossil-fuel_366',
      word: 'fossil fuel',
      translation: 'combustible fósil',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 7,
      topic: 'clima-y-desastres-na',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfɑsəl ˈfjuəl/',
      example: 'Fossil fuels pollute the air.',
      exampleTranslation: 'Los combustibles fósiles contaminan el aire.',
      status: 'approved',
    },
  ] as const,
}
