/**
 * A2 Level Content — Week 02
 * Topic: Viajes: aeropuerto, hotel y emergencias
 * Curated from institutional curriculum (Zero AI)
 */
import type { ContentBlock } from '../types'

export const week02: ContentBlock = {
  level: 'A2',
  week: 2,
  topic: 'Viajes: aeropuerto, hotel y emergencias',
  vocabulary: [
    {
      id: 'voc_a2_check-in_065',
      word: 'check-in',
      translation: 'registro de entrada',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_check-out_066',
      word: 'check-out',
      translation: 'salida (hotel)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_room-service_067',
      word: 'room service',
      translation: 'servicio a la habitación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_single-room_068',
      word: 'single room',
      translation: 'habitación individual',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_double-room_069',
      word: 'double room',
      translation: 'habitación doble',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_suite_070',
      word: 'suite',
      translation: 'suite',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_lobby_071',
      word: 'lobby',
      translation: 'vestíbulo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_concierge_072',
      word: 'concierge',
      translation: 'conserje',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_housekeeping_073',
      word: 'housekeeping',
      translation: 'limpieza (hotel)',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_do-not-disturb_074',
      word: 'do not disturb',
      translation: 'no molestar',
      partOfSpeech: 'phrasal-verb',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_key-card_075',
      word: 'key card',
      translation: 'tarjeta llave',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_wake-up-call_076',
      word: 'wake-up call',
      translation: 'llamada para despertar',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_mini-bar_077',
      word: 'mini bar',
      translation: 'minibar',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_complimentary_078',
      word: 'complimentary',
      translation: 'gratuito/cortesía',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_amenities_079',
      word: 'amenities',
      translation: 'comodidades',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_spa_080',
      word: 'spa',
      translation: 'spa',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_laundry-service_081',
      word: 'laundry service',
      translation: 'servicio de lavandería',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_front-desk_082',
      word: 'front desk',
      translation: 'recepción',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_overbooked_083',
      word: 'overbooked',
      translation: 'con sobreventa',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_cancellation_084',
      word: 'cancellation',
      translation: 'cancelación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_non-refundable_085',
      word: 'non-refundable',
      translation: 'no reembolsable',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_itinerary_086',
      word: 'itinerary',
      translation: 'itinerario',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_layover_087',
      word: 'layover',
      translation: 'escala',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_connecting-flight_088',
      word: 'connecting flight',
      translation: 'vuelo de conexión',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_delayed-flight_089',
      word: 'delayed flight',
      translation: 'vuelo retrasado',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_cancelled-flight_090',
      word: 'cancelled flight',
      translation: 'vuelo cancelado',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_boarding-time_091',
      word: 'boarding time',
      translation: 'hora de embarque',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_overhead-bin_092',
      word: 'overhead bin',
      translation: 'compartimento superior',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_carry-on_093',
      word: 'carry-on',
      translation: 'equipaje de mano',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_baggage-claim_094',
      word: 'baggage claim',
      translation: 'reclamo de equipaje',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_lost-luggage_095',
      word: 'lost luggage',
      translation: 'equipaje perdido',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_customs-declaration_096',
      word: 'customs declaration',
      translation: 'declaración de aduana',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_duty-free_097',
      word: 'duty-free',
      translation: 'libre de impuestos',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_embassy_098',
      word: 'embassy',
      translation: 'embajada',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_consulate_099',
      word: 'consulate',
      translation: 'consulado',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_emergency-exit_100',
      word: 'emergency exit',
      translation: 'salida de emergencia',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_fire-alarm_101',
      word: 'fire alarm',
      translation: 'alarma de incendio',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_first-aid_102',
      word: 'first aid',
      translation: 'primeros auxilios',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_evacuation_103',
      word: 'evacuation',
      translation: 'evacuación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_emergency-contact_104',
      word: 'emergency contact',
      translation: 'contacto de emergencia',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_insurance-claim_105',
      word: 'insurance claim',
      translation: 'reclamo de seguro',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_stolen_106',
      word: 'stolen',
      translation: 'robado',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_robbery_107',
      word: 'robbery',
      translation: 'robo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_pickpocket_108',
      word: 'pickpocket',
      translation: 'carterista',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_police-report_109',
      word: 'police report',
      translation: 'reporte policial',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_lost-and-found_110',
      word: 'lost and found',
      translation: 'objetos perdidos',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_replacement-passport_111',
      word: 'replacement passport',
      translation: 'pasaporte de reemplazo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_travel-advisory_112',
      word: 'travel advisory',
      translation: 'advertencia de viaje',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_vaccination-certific_113',
      word: 'vaccination certificate',
      translation: 'certificado de vacunación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_jet-lag_114',
      word: 'jet lag',
      translation: 'descompensación horaria',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_time-zone_115',
      word: 'time zone',
      translation: 'zona horaria',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_local-currency_116',
      word: 'local currency',
      translation: 'moneda local',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_tipping_117',
      word: 'tipping',
      translation: 'dar propina',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_guided-tour_118',
      word: 'guided tour',
      translation: 'tour guiado',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_sightseeing_119',
      word: 'sightseeing',
      translation: 'hacer turismo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_landmark_120',
      word: 'landmark',
      translation: 'punto de referencia/monumento',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 2,
      topic: 'viajes-aeropuerto-ho',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
  ] as const,
}
