/**
 * A2 Level Content — Week 04
 * Topic: Salud y cuerpo (síntomas y citas médicas)
 * Curated from institutional curriculum (Zero AI)
 */
import type { ContentBlock } from '../types'

export const week04: ContentBlock = {
  level: 'A2',
  week: 4,
  topic: 'Salud y cuerpo (síntomas y citas médicas)',
  vocabulary: [
    {
      id: 'voc_a2_symptom_182',
      word: 'symptom',
      translation: 'síntoma',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_diagnosis_183',
      word: 'diagnosis',
      translation: 'diagnóstico',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_prescription_184',
      word: 'prescription',
      translation: 'receta médica',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_dosage_185',
      word: 'dosage',
      translation: 'dosis',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_side-effect_186',
      word: 'side effect',
      translation: 'efecto secundario',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_allergy_187',
      word: 'allergy',
      translation: 'alergia',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_allergic-reaction_188',
      word: 'allergic reaction',
      translation: 'reacción alérgica',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_infection_189',
      word: 'infection',
      translation: 'infección',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_inflammation_190',
      word: 'inflammation',
      translation: 'inflamación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_rash_191',
      word: 'rash',
      translation: 'sarpullido',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_swelling_192',
      word: 'swelling',
      translation: 'hinchazón',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_bruise_193',
      word: 'bruise',
      translation: 'moretón',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_wound_194',
      word: 'wound',
      translation: 'herida',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_stitches_195',
      word: 'stitches',
      translation: 'puntos de sutura',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_cast_196',
      word: 'cast (medical)',
      translation: 'yeso',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_crutches_197',
      word: 'crutches',
      translation: 'muletas',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_wheelchair_198',
      word: 'wheelchair',
      translation: 'silla de ruedas',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_blood-pressure_199',
      word: 'blood pressure',
      translation: 'presión arterial',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_heart-rate_200',
      word: 'heart rate',
      translation: 'ritmo cardíaco',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_pulse_201',
      word: 'pulse',
      translation: 'pulso',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_x-ray_202',
      word: 'x-ray',
      translation: 'radiografía',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_surgery-operation_203',
      word: 'surgery / operation',
      translation: 'cirugía',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_anesthesia_204',
      word: 'anesthesia',
      translation: 'anestesia',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_recovery_205',
      word: 'recovery',
      translation: 'recuperación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_checkup_206',
      word: 'checkup',
      translation: 'chequeo médico',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_specialist_207',
      word: 'specialist',
      translation: 'especialista',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_physical-therapy_208',
      word: 'physical therapy',
      translation: 'fisioterapia',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_mental-health_209',
      word: 'mental health',
      translation: 'salud mental',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_anxiety_210',
      word: 'anxiety',
      translation: 'ansiedad',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_depression_211',
      word: 'depression',
      translation: 'depresión',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_sleep-disorder_212',
      word: 'sleep disorder',
      translation: 'trastorno del sueño',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_chronic_213',
      word: 'chronic',
      translation: 'crónico',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_acute_214',
      word: 'acute',
      translation: 'agudo',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_contagious_215',
      word: 'contagious',
      translation: 'contagioso',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_immune-system_216',
      word: 'immune system',
      translation: 'sistema inmunológico',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_lungs_217',
      word: 'lungs',
      translation: 'pulmones',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_liver_218',
      word: 'liver',
      translation: 'hígado',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_kidney_219',
      word: 'kidney',
      translation: 'riñón',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_intestine_220',
      word: 'intestine',
      translation: 'intestino',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_joint_221',
      word: 'joint',
      translation: 'articulación',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_spine_222',
      word: 'spine',
      translation: 'columna vertebral',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_artery_223',
      word: 'artery',
      translation: 'arteria',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_vein_224',
      word: 'vein',
      translation: 'vena',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_nervous-system_225',
      word: 'nervous system',
      translation: 'sistema nervioso',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_digestive-system_226',
      word: 'digestive system',
      translation: 'sistema digestivo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_hormone_227',
      word: 'hormone',
      translation: 'hormona',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_metabolism_228',
      word: 'metabolism',
      translation: 'metabolismo',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_nutrient_229',
      word: 'nutrient',
      translation: 'nutriente',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_vitamin_230',
      word: 'vitamin',
      translation: 'vitamina',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_protein_231',
      word: 'protein',
      translation: 'proteína',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_carbohydrate_232',
      word: 'carbohydrate',
      translation: 'carbohidrato',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_fiber_233',
      word: 'fiber',
      translation: 'fibra',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_calorie_234',
      word: 'calorie',
      translation: 'caloría',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_overweight_235',
      word: 'overweight',
      translation: 'sobrepeso',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_underweight_236',
      word: 'underweight',
      translation: 'bajo peso',
      partOfSpeech: 'adjective',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_obesity_237',
      word: 'obesity',
      translation: 'obesidad',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_wellness_238',
      word: 'wellness',
      translation: 'bienestar',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_hygiene_239',
      word: 'hygiene',
      translation: 'higiene',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a2_first-aid-kit_240',
      word: 'first aid kit',
      translation: 'botiquín de primeros auxilios',
      partOfSpeech: 'noun',
      level: 'A2',
      week: 4,
      topic: 'salud-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
  ] as const,
}
