import type { ContentBlock } from '../types'

/**
 * A1 Level — Week 13
 * Topic: Semana 13 – Emociones y adjetivos adicionales
 * Curated from: a.md
 * Total items: 59
 */
export const week13: ContentBlock = {
  level: 'A1',
  week: 13,
  topic: 'Semana 13 – Emociones y adjetivos adicionales',
  vocabulary: [
    {
      id: 'voc_a1_afraid_001',
      word: 'afraid',
      translation: 'asustado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈfreɪd/',
      example: 'I am afraid of the dark.',
      exampleTranslation: 'Tengo miedo a la oscuridad.',
      status: 'approved',
    },
    {
      id: 'voc_a1_scared_001',
      word: 'scared',
      translation: 'asustado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/skɛrd/',
      example: 'She was scared during the storm.',
      exampleTranslation: 'Ella estaba asustada durante la tormenta.',
      status: 'approved',
    },
    {
      id: 'voc_a1_worried_001',
      word: 'worried',
      translation: 'preocupado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈwɜrid/',
      example: 'I am worried about the exam.',
      exampleTranslation: 'Estoy preocupado por el examen.',
      status: 'approved',
    },
    {
      id: 'voc_a1_nervous_001',
      word: 'nervous',
      translation: 'nervioso',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈnɜrvəs/',
      example: 'He feels nervous before interviews.',
      exampleTranslation: 'Él se siente nervioso antes de las entrevistas.',
      status: 'approved',
    },
    {
      id: 'voc_a1_excited_001',
      word: 'excited',
      translation: 'emocionado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪkˈsaɪtɪd/',
      example: 'We are excited about the trip.',
      exampleTranslation: 'Estamos emocionados por el viaje.',
      status: 'approved',
    },
    {
      id: 'voc_a1_surprised_001',
      word: 'surprised',
      translation: 'sorprendido',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/sərˈpraɪzd/',
      example: 'I was surprised by the news.',
      exampleTranslation: 'Me sorprendió la noticia.',
      status: 'approved',
    },
    {
      id: 'voc_a1_bored_001',
      word: 'bored',
      translation: 'aburrido',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bɔrd/',
      example: 'The children are bored at home.',
      exampleTranslation: 'Los niños están aburridos en casa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_embarrassed_001',
      word: 'embarrassed',
      translation: 'avergonzado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪmˈbɛrəst/',
      example: 'I felt embarrassed after the mistake.',
      exampleTranslation: 'Me sentí avergonzado después del error.',
      status: 'approved',
    },
    {
      id: 'voc_a1_confused_001',
      word: 'confused',
      translation: 'confundido',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kənˈfjuzd/',
      example: 'I am confused about the instructions.',
      exampleTranslation: 'Estoy confundido con las instrucciones.',
      status: 'approved',
    },
    {
      id: 'voc_a1_proud_001',
      word: 'proud',
      translation: 'orgulloso',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/praʊd/',
      example: 'Her parents are very proud of her.',
      exampleTranslation: 'Sus padres están muy orgullosos de ella.',
      status: 'approved',
    },
    {
      id: 'voc_a1_jealous_001',
      word: 'jealous',
      translation: 'celoso',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdʒɛləs/',
      example: 'Don\'t be jealous of your sister.',
      exampleTranslation: 'No estés celoso de tu hermana.',
      status: 'approved',
    },
    {
      id: 'voc_a1_lonely_001',
      word: 'lonely',
      translation: 'solitario',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈloʊnli/',
      example: 'He feels lonely since he moved.',
      exampleTranslation: 'Él se siente solitario desde que se mudó.',
      status: 'approved',
    },
    {
      id: 'voc_a1_calm_001',
      word: 'calm',
      translation: 'tranquilo',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kɑm/',
      example: 'Stay calm, everything is fine.',
      exampleTranslation: 'Mantén la calma, todo está bien.',
      status: 'approved',
    },
    {
      id: 'voc_a1_relaxed_001',
      word: 'relaxed',
      translation: 'relajado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rɪˈlækst/',
      example: 'I feel relaxed after vacation.',
      exampleTranslation: 'Me siento relajado después de las vacaciones.',
      status: 'approved',
    },
    {
      id: 'voc_a1_stressed_001',
      word: 'stressed',
      translation: 'estresado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/strɛst/',
      example: 'She is stressed about work.',
      exampleTranslation: 'Ella está estresada por el trabajo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_sick-ill_001',
      word: 'sick / ill',
      translation: 'enfermo',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/sɪk/',
      example: 'My son is sick today.',
      exampleTranslation: 'Mi hijo está enfermo hoy.',
      status: 'approved',
    },
    {
      id: 'voc_a1_healthy_001',
      word: 'healthy',
      translation: 'saludable',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈhɛlθi/',
      example: 'We try to eat healthy food.',
      exampleTranslation: 'Tratamos de comer comida saludable.',
      status: 'approved',
    },
    {
      id: 'voc_a1_comfortable_001',
      word: 'comfortable',
      translation: 'cómodo',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkʌmfərtəbəl/',
      example: 'This chair is very comfortable.',
      exampleTranslation: 'Esta silla es muy cómoda.',
      status: 'approved',
    },
    {
      id: 'voc_a1_uncomfortable_001',
      word: 'uncomfortable',
      translation: 'incómodo',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ʌnˈkʌmfərtəbəl/',
      example: 'These shoes are uncomfortable.',
      exampleTranslation: 'Estos zapatos son incómodos.',
      status: 'approved',
    },
    {
      id: 'voc_a1_confident_001',
      word: 'confident',
      translation: 'seguro de sí mismo',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkɑnfədənt/',
      example: 'She is confident in her work.',
      exampleTranslation: 'Ella tiene confianza en su trabajo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_curious_001',
      word: 'curious',
      translation: 'curioso',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkjʊriəs/',
      example: 'My son is very curious about animals.',
      exampleTranslation: 'Mi hijo es muy curioso sobre los animales.',
      status: 'approved',
    },
    {
      id: 'voc_a1_patient_001',
      word: 'patient',
      translation: 'paciente',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpeɪʃənt/',
      example: 'Please be patient with him.',
      exampleTranslation: 'Por favor ten paciencia con él.',
      status: 'approved',
    },
    {
      id: 'voc_a1_impatient_001',
      word: 'impatient',
      translation: 'impaciente',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪmˈpeɪʃənt/',
      example: 'The children were impatient in line.',
      exampleTranslation: 'Los niños estaban impacientes en la fila.',
      status: 'approved',
    },
    {
      id: 'voc_a1_important_001',
      word: 'important',
      translation: 'importante',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪmˈpɔrtənt/',
      example: 'This meeting is very important.',
      exampleTranslation: 'Esta reunión es muy importante.',
      status: 'approved',
    },
    {
      id: 'voc_a1_necessary_001',
      word: 'necessary',
      translation: 'necesario',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈnɛsəˌsɛri/',
      example: 'Water is necessary for life.',
      exampleTranslation: 'El agua es necesaria para la vida.',
      status: 'approved',
    },
    {
      id: 'voc_a1_possible_001',
      word: 'possible',
      translation: 'posible',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpɑsəbəl/',
      example: 'It is possible to finish today.',
      exampleTranslation: 'Es posible terminar hoy.',
      status: 'approved',
    },
    {
      id: 'voc_a1_impossible_001',
      word: 'impossible',
      translation: 'imposible',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪmˈpɑsəbəl/',
      example: 'It is impossible to be there by six.',
      exampleTranslation: 'Es imposible llegar ahí para las seis.',
      status: 'approved',
    },
    {
      id: 'voc_a1_true_001',
      word: 'true',
      translation: 'verdadero',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tru/',
      example: 'Is this story true?',
      exampleTranslation: '¿Es verdadera esta historia?',
      status: 'approved',
    },
    {
      id: 'voc_a1_false_001',
      word: 'false',
      translation: 'falso',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fɔls/',
      example: 'That statement is false.',
      exampleTranslation: 'Esa afirmación es falsa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_real_001',
      word: 'real',
      translation: 'real',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ril/',
      example: 'This is a real diamond.',
      exampleTranslation: 'Este es un diamante real.',
      status: 'approved',
    },
    {
      id: 'voc_a1_fake_001',
      word: 'fake',
      translation: 'falso/imitación',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/feɪk/',
      example: 'That watch is fake.',
      exampleTranslation: 'Ese reloj es falso.',
      status: 'approved',
    },
    {
      id: 'voc_a1_correct_001',
      word: 'correct',
      translation: 'correcto',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kəˈrɛkt/',
      example: 'Your answer is correct.',
      exampleTranslation: 'Tu respuesta es correcta.',
      status: 'approved',
    },
    {
      id: 'voc_a1_incorrect_001',
      word: 'incorrect',
      translation: 'incorrecto',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌɪnkəˈrɛkt/',
      example: 'This answer is incorrect.',
      exampleTranslation: 'Esta respuesta es incorrecta.',
      status: 'approved',
    },
    {
      id: 'voc_a1_popular_001',
      word: 'popular',
      translation: 'popular',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpɑpjələr/',
      example: 'This song is very popular.',
      exampleTranslation: 'Esta canción es muy popular.',
      status: 'approved',
    },
    {
      id: 'voc_a1_famous_001',
      word: 'famous',
      translation: 'famoso',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfeɪməs/',
      example: 'She is a famous singer.',
      exampleTranslation: 'Ella es una cantante famosa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_normal_001',
      word: 'normal',
      translation: 'normal',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈnɔrməl/',
      example: 'It is normal to feel nervous.',
      exampleTranslation: 'Es normal sentirse nervioso.',
      status: 'approved',
    },
    {
      id: 'voc_a1_strange_001',
      word: 'strange',
      translation: 'extraño',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/streɪndʒ/',
      example: 'That was a strange sound.',
      exampleTranslation: 'Ese fue un sonido extraño.',
      status: 'approved',
    },
    {
      id: 'voc_a1_weird_001',
      word: 'weird',
      translation: 'raro',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/wɪrd/',
      example: 'This tastes a little weird.',
      exampleTranslation: 'Esto sabe un poco raro.',
      status: 'approved',
    },
    {
      id: 'voc_a1_special_001',
      word: 'special',
      translation: 'especial',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈspɛʃəl/',
      example: 'Today is a special day.',
      exampleTranslation: 'Hoy es un día especial.',
      status: 'approved',
    },
    {
      id: 'voc_a1_common_001',
      word: 'common',
      translation: 'común',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkɑmən/',
      example: 'This is a common mistake.',
      exampleTranslation: 'Este es un error común.',
      status: 'approved',
    },
    {
      id: 'voc_a1_rare_001',
      word: 'rare',
      translation: 'raro/poco común',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rɛr/',
      example: 'This bird is very rare.',
      exampleTranslation: 'Este pájaro es muy raro (poco común).',
      status: 'approved',
    },
    {
      id: 'voc_a1_modern_001',
      word: 'modern',
      translation: 'moderno',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmɑdərn/',
      example: 'They live in a modern building.',
      exampleTranslation: 'Ellos viven en un edificio moderno.',
      status: 'approved',
    },
    {
      id: 'voc_a1_traditional_001',
      word: 'traditional',
      translation: 'tradicional',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/trəˈdɪʃəl/',
      example: 'We had a traditional dinner.',
      exampleTranslation: 'Tuvimos una cena tradicional.',
      status: 'approved',
    },
    {
      id: 'voc_a1_similar_001',
      word: 'similar',
      translation: 'similar',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsɪmələr/',
      example: 'Our jackets are similar.',
      exampleTranslation: 'Nuestras chaquetas son similares.',
      status: 'approved',
    },
    {
      id: 'voc_a1_simple_001',
      word: 'simple',
      translation: 'simple',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsɪmpəl/',
      example: 'The recipe is very simple.',
      exampleTranslation: 'La receta es muy simple.',
      status: 'approved',
    },
    {
      id: 'voc_a1_complicated_001',
      word: 'complicated',
      translation: 'complicado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkɑmpləˌkeɪtɪd/',
      example: 'This problem is complicated.',
      exampleTranslation: 'Este problema es complicado.',
      status: 'approved',
    },
    {
      id: 'voc_a1_careful_001',
      word: 'careful',
      translation: 'cuidadoso',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkɛrfəl/',
      example: 'Be careful on the stairs.',
      exampleTranslation: 'Ten cuidado en las escaleras.',
      status: 'approved',
    },
    {
      id: 'voc_a1_careless_001',
      word: 'careless',
      translation: 'descuidado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkɛrləs/',
      example: 'He was careless with the glass.',
      exampleTranslation: 'Él fue descuidado con el vaso.',
      status: 'approved',
    },
    {
      id: 'voc_a1_honest_001',
      word: 'honest',
      translation: 'honesto',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɑnəst/',
      example: 'She is always honest with me.',
      exampleTranslation: 'Ella siempre es honesta conmigo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_polite_001',
      word: 'polite',
      translation: 'cortés',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pəˈlaɪt/',
      example: 'The waiter was very polite.',
      exampleTranslation: 'El mesero fue muy cortés.',
      status: 'approved',
    },
    {
      id: 'voc_a1_rude_001',
      word: 'rude',
      translation: 'grosero',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rud/',
      example: 'It is rude to interrupt.',
      exampleTranslation: 'Es de mala educación interrumpir.',
      status: 'approved',
    },
    {
      id: 'voc_a1_generous_001',
      word: 'generous',
      translation: 'generoso',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdʒɛnərəs/',
      example: 'My uncle is very generous.',
      exampleTranslation: 'Mi tío es muy generoso.',
      status: 'approved',
    },
    {
      id: 'voc_a1_selfish_001',
      word: 'selfish',
      translation: 'egoísta',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsɛlfɪʃ/',
      example: 'Don\'t be selfish with your toys.',
      exampleTranslation: 'No seas egoísta con tus juguetes.',
      status: 'approved',
    },
    {
      id: 'voc_a1_hopeful_001',
      word: 'hopeful',
      translation: 'esperanzado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈhoʊpfəl/',
      example: 'We are hopeful about the future.',
      exampleTranslation: 'Somos optimistas sobre el futuro.',
      status: 'approved',
    },
    {
      id: 'voc_a1_disappointed_001',
      word: 'disappointed',
      translation: 'decepcionado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌdɪsəˈpɔɪntɪd/',
      example: 'I was disappointed with the movie.',
      exampleTranslation: 'Me decepcionó la película.',
      status: 'approved',
    },
    {
      id: 'voc_a1_grateful_001',
      word: 'grateful',
      translation: 'agradecido',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈgreɪtfəl/',
      example: 'I am grateful for your help.',
      exampleTranslation: 'Estoy agradecido por tu ayuda.',
      status: 'approved',
    },
    {
      id: 'voc_a1_annoyed_001',
      word: 'annoyed',
      translation: 'molesto',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈnɔɪd/',
      example: 'She was annoyed by the noise.',
      exampleTranslation: 'Ella estaba molesta por el ruido.',
      status: 'approved',
    },
    {
      id: 'voc_a1_relieved_001',
      word: 'relieved',
      translation: 'aliviado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rɪˈlivd/',
      example: 'I was relieved to hear the news.',
      exampleTranslation: 'Me sentí aliviado al escuchar la noticia.',
      status: 'approved',
    },
    {
      id: 'voc_a1_amazed_001',
      word: 'amazed',
      translation: 'asombrado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈmeɪzd/',
      example: 'We were amazed by the view.',
      exampleTranslation: 'Nos asombró la vista.',
      status: 'approved',
    },
  ],
}
