import type { ContentBlock } from '../types'

/**
 * A1 Level — Week 10
 * Topic: Semana 10 – Animales y naturaleza
 * Curated from: a.md
 * Total items: 80
 */
export const week10: ContentBlock = {
  level: 'A1',
  week: 10,
  topic: 'Semana 10 – Animales y naturaleza',
  vocabulary: [
    {
      id: 'voc_a1_dog_001',
      word: 'dog',
      translation: 'perro',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_cat_001',
      word: 'cat',
      translation: 'gato',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_bird_001',
      word: 'bird',
      translation: 'pájaro',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_fish_002',
      word: 'fish (animal)',
      translation: 'pez',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_horse_001',
      word: 'horse',
      translation: 'caballo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_cow_001',
      word: 'cow',
      translation: 'vaca',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_pig_001',
      word: 'pig',
      translation: 'cerdo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_sheep_001',
      word: 'sheep',
      translation: 'oveja',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_goat_001',
      word: 'goat',
      translation: 'cabra',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_duck_001',
      word: 'duck',
      translation: 'pato',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_rabbit_001',
      word: 'rabbit',
      translation: 'conejo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_mouse_001',
      word: 'mouse',
      translation: 'ratón',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_lion_001',
      word: 'lion',
      translation: 'león',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_tiger_001',
      word: 'tiger',
      translation: 'tigre',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_elephant_001',
      word: 'elephant',
      translation: 'elefante',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_monkey_001',
      word: 'monkey',
      translation: 'mono',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_bear_001',
      word: 'bear',
      translation: 'oso',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_wolf_001',
      word: 'wolf',
      translation: 'lobo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_fox_001',
      word: 'fox',
      translation: 'zorro',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_deer_001',
      word: 'deer',
      translation: 'ciervo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_snake_001',
      word: 'snake',
      translation: 'serpiente',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_frog_001',
      word: 'frog',
      translation: 'rana',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_turtle_001',
      word: 'turtle',
      translation: 'tortuga',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_butterfly_001',
      word: 'butterfly',
      translation: 'mariposa',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_bee_001',
      word: 'bee',
      translation: 'abeja',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_spider_001',
      word: 'spider',
      translation: 'araña',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_ant_001',
      word: 'ant',
      translation: 'hormiga',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_fly_001',
      word: 'fly (insect)',
      translation: 'mosca',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_mosquito_001',
      word: 'mosquito',
      translation: 'mosquito',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_owl_001',
      word: 'owl',
      translation: 'búho',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_eagle_001',
      word: 'eagle',
      translation: 'águila',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_shark_001',
      word: 'shark',
      translation: 'tiburón',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_whale_001',
      word: 'whale',
      translation: 'ballena',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_dolphin_001',
      word: 'dolphin',
      translation: 'delfín',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_tree_001',
      word: 'tree',
      translation: 'árbol',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_flower_001',
      word: 'flower',
      translation: 'flor',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_grass_001',
      word: 'grass',
      translation: 'pasto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_leaf_001',
      word: 'leaf',
      translation: 'hoja',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_plant_001',
      word: 'plant',
      translation: 'planta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_sky_001',
      word: 'sky',
      translation: 'cielo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_star_002',
      word: 'star (sky)',
      translation: 'estrella',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_moon_001',
      word: 'moon',
      translation: 'luna',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_rock_001',
      word: 'rock',
      translation: 'roca',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_stone_001',
      word: 'stone',
      translation: 'piedra',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_sand_001',
      word: 'sand',
      translation: 'arena',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_earth_001',
      word: 'earth',
      translation: 'tierra',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_world_001',
      word: 'world',
      translation: 'mundo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_nature_001',
      word: 'nature',
      translation: 'naturaleza',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_animal_001',
      word: 'animal',
      translation: 'animal',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_pet_001',
      word: 'pet',
      translation: 'mascota',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_wild_001',
      word: 'wild',
      translation: 'salvaje',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_field_001',
      word: 'field',
      translation: 'campo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_island_001',
      word: 'island',
      translation: 'isla',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_desert_001',
      word: 'desert',
      translation: 'desierto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_jungle_001',
      word: 'jungle',
      translation: 'selva',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_valley_001',
      word: 'valley',
      translation: 'valle',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_hill_001',
      word: 'hill',
      translation: 'colina',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_wave_001',
      word: 'wave',
      translation: 'ola',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_rainbow_001',
      word: 'rainbow',
      translation: 'arcoíris',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_root_001',
      word: 'root',
      translation: 'raíz',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_branch_001',
      word: 'branch',
      translation: 'rama',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_seed_001',
      word: 'seed',
      translation: 'semilla',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_cage_001',
      word: 'cage',
      translation: 'jaula',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_zoo_001',
      word: 'zoo',
      translation: 'zoológico',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_aquarium_001',
      word: 'aquarium',
      translation: 'acuario',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_herd_001',
      word: 'herd',
      translation: 'manada',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_flock_001',
      word: 'flock',
      translation: 'bandada',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_nest_001',
      word: 'nest',
      translation: 'nido',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_den_001',
      word: 'den',
      translation: 'madriguera',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_feather_001',
      word: 'feather',
      translation: 'pluma',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_fur_001',
      word: 'fur',
      translation: 'pelaje',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_tail_001',
      word: 'tail',
      translation: 'cola',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_paw_001',
      word: 'paw',
      translation: 'pata',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_wing_001',
      word: 'wing',
      translation: 'ala',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_claw_001',
      word: 'claw',
      translation: 'garra',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_hoof_001',
      word: 'hoof',
      translation: 'pezuña',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_predator_001',
      word: 'predator',
      translation: 'depredador',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_prey_001',
      word: 'prey',
      translation: 'presa',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_species_001',
      word: 'species',
      translation: 'especie',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_wildlife_001',
      word: 'wildlife',
      translation: 'fauna silvestre',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
  ],
}
