import type { ContentBlock } from '../types'

/**
 * A1 Level — Week 8
 * Topic: Semana 8 – Verbos de la rutina diaria
 * Curated from: a.md
 * Total items: 85
 */
export const week08: ContentBlock = {
  level: 'A1',
  week: 8,
  topic: 'Semana 8 – Verbos de la rutina diaria',
  vocabulary: [
    {
      id: 'voc_a1_wake-up_001',
      word: 'wake up',
      translation: 'despertarse',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_get-up_001',
      word: 'get up',
      translation: 'levantarse',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_sleep_001',
      word: 'sleep',
      translation: 'dormir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_go-to-bed_001',
      word: 'go to bed',
      translation: 'irse a la cama',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_wash_001',
      word: 'wash',
      translation: 'lavar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_take-a-shower_001',
      word: 'take a shower',
      translation: 'ducharse',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_brush_001',
      word: 'brush (teeth)',
      translation: 'cepillarse',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_comb_001',
      word: 'comb',
      translation: 'peinar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_get-dressed_001',
      word: 'get dressed',
      translation: 'vestirse',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_have-breakfast_001',
      word: 'have breakfast',
      translation: 'desayunar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_go-to-work_001',
      word: 'go to work',
      translation: 'ir al trabajo',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_go-to-school_001',
      word: 'go to school',
      translation: 'ir a la escuela',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_study_001',
      word: 'study',
      translation: 'estudiar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_work_001',
      word: 'work',
      translation: 'trabajar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_read_001',
      word: 'read',
      translation: 'leer',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_write_001',
      word: 'write',
      translation: 'escribir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_listen_001',
      word: 'listen',
      translation: 'escuchar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_speak_001',
      word: 'speak',
      translation: 'hablar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_talk_001',
      word: 'talk',
      translation: 'conversar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_watch_001',
      word: 'watch',
      translation: 'mirar/ver',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_walk_001',
      word: 'walk',
      translation: 'caminar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_run_001',
      word: 'run',
      translation: 'correr',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_drive_001',
      word: 'drive',
      translation: 'conducir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_ride_001',
      word: 'ride',
      translation: 'montar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_travel_001',
      word: 'travel',
      translation: 'viajar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_arrive_001',
      word: 'arrive',
      translation: 'llegar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_leave_001',
      word: 'leave',
      translation: 'salir/irse',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_come_001',
      word: 'come',
      translation: 'venir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_go_001',
      word: 'go',
      translation: 'ir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_stay_001',
      word: 'stay',
      translation: 'quedarse',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_live_001',
      word: 'live',
      translation: 'vivir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_rest_001',
      word: 'rest',
      translation: 'descansar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_relax_001',
      word: 'relax',
      translation: 'relajarse',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_play_001',
      word: 'play',
      translation: 'jugar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_dance_001',
      word: 'dance',
      translation: 'bailar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_sing_001',
      word: 'sing',
      translation: 'cantar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_wash-dishes_001',
      word: 'wash dishes',
      translation: 'lavar platos',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_do-homework_001',
      word: 'do homework',
      translation: 'hacer tarea',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_exercise_001',
      word: 'exercise',
      translation: 'ejercitarse',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_swim_001',
      word: 'swim',
      translation: 'nadar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_jump_001',
      word: 'jump',
      translation: 'saltar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_sit_001',
      word: 'sit',
      translation: 'sentarse',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_stand_001',
      word: 'stand',
      translation: 'pararse',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_wait_001',
      word: 'wait',
      translation: 'esperar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_need_001',
      word: 'need',
      translation: 'necesitar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_want_001',
      word: 'want',
      translation: 'querer',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_like_001',
      word: 'like',
      translation: 'gustar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_know_001',
      word: 'know',
      translation: 'saber/conocer',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_think_001',
      word: 'think',
      translation: 'pensar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_remember_001',
      word: 'remember',
      translation: 'recordar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_forget_001',
      word: 'forget',
      translation: 'olvidar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_understand_001',
      word: 'understand',
      translation: 'entender',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_learn_001',
      word: 'learn',
      translation: 'aprender',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_teach_001',
      word: 'teach',
      translation: 'enseñar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_ask_001',
      word: 'ask',
      translation: 'preguntar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_answer_001',
      word: 'answer',
      translation: 'responder',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_say_001',
      word: 'say',
      translation: 'decir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_tell_001',
      word: 'tell',
      translation: 'contar/decir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_give_001',
      word: 'give',
      translation: 'dar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_take_001',
      word: 'take',
      translation: 'tomar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_bring_001',
      word: 'bring',
      translation: 'traer',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_send_001',
      word: 'send',
      translation: 'enviar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_receive_001',
      word: 'receive',
      translation: 'recibir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_sell_001',
      word: 'sell',
      translation: 'vender',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_pay_001',
      word: 'pay',
      translation: 'pagar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_spend_001',
      word: 'spend',
      translation: 'gastar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_save_001',
      word: 'save',
      translation: 'ahorrar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_lose_001',
      word: 'lose',
      translation: 'perder',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_find_001',
      word: 'find',
      translation: 'encontrar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_look-for_001',
      word: 'look for',
      translation: 'buscar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_look-at_001',
      word: 'look at',
      translation: 'mirar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_see_001',
      word: 'see',
      translation: 'ver',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_hear_001',
      word: 'hear',
      translation: 'oír',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_feel_001',
      word: 'feel',
      translation: 'sentir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_smell_001',
      word: 'smell',
      translation: 'oler',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_touch_001',
      word: 'touch',
      translation: 'tocar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_start_001',
      word: 'start',
      translation: 'empezar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_finish_001',
      word: 'finish',
      translation: 'terminar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_stop_001',
      word: 'stop',
      translation: 'parar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_continue_001',
      word: 'continue',
      translation: 'continuar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_try_001',
      word: 'try',
      translation: 'intentar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_use_001',
      word: 'use',
      translation: 'usar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_make_001',
      word: 'make',
      translation: 'hacer/fabricar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_fix_001',
      word: 'fix',
      translation: 'arreglar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_break_001',
      word: 'break',
      translation: 'romper',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
  ],
}
