import type { ContentBlock } from '../types'

/**
 * A1 Level — Week 11
 * Topic: Semana 11 – Profesiones y escuela
 * Curated from: a.md
 * Total items: 66
 */
export const week11: ContentBlock = {
  level: 'A1',
  week: 11,
  topic: 'Semana 11 – Profesiones y escuela',
  vocabulary: [
    {
      id: 'voc_a1_teacher_001',
      word: 'teacher',
      translation: 'maestro/a',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_student_001',
      word: 'student',
      translation: 'estudiante',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_doctor_001',
      word: 'doctor',
      translation: 'médico',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_nurse_001',
      word: 'nurse',
      translation: 'enfermero/a',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_dentist_001',
      word: 'dentist',
      translation: 'dentista',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_engineer_001',
      word: 'engineer',
      translation: 'ingeniero',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_lawyer_001',
      word: 'lawyer',
      translation: 'abogado',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_police-officer_001',
      word: 'police officer',
      translation: 'policía',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_firefighter_001',
      word: 'firefighter',
      translation: 'bombero',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_farmer_001',
      word: 'farmer',
      translation: 'granjero',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_driver_001',
      word: 'driver',
      translation: 'conductor',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_pilot_001',
      word: 'pilot',
      translation: 'piloto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_cashier_001',
      word: 'cashier',
      translation: 'cajero',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_manager_001',
      word: 'manager',
      translation: 'gerente',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_boss_001',
      word: 'boss',
      translation: 'jefe',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_employee_001',
      word: 'employee',
      translation: 'empleado',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_worker_001',
      word: 'worker',
      translation: 'trabajador',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_businessman-businesswoman_001',
      word: 'businessman / businesswoman',
      translation: 'empresario/a',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_artist_001',
      word: 'artist',
      translation: 'artista',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_musician_001',
      word: 'musician',
      translation: 'músico',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_actor-actress_001',
      word: 'actor / actress',
      translation: 'actor / actriz',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_writer_001',
      word: 'writer',
      translation: 'escritor',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_journalist_001',
      word: 'journalist',
      translation: 'periodista',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_scientist_001',
      word: 'scientist',
      translation: 'científico',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_athlete_001',
      word: 'athlete',
      translation: 'atleta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_soldier_001',
      word: 'soldier',
      translation: 'soldado',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_secretary_001',
      word: 'secretary',
      translation: 'secretario/a',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_receptionist_001',
      word: 'receptionist',
      translation: 'recepcionista',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_mechanic_001',
      word: 'mechanic',
      translation: 'mecánico',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_electrician_001',
      word: 'electrician',
      translation: 'electricista',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_plumber_001',
      word: 'plumber',
      translation: 'plomero',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_hairdresser_001',
      word: 'hairdresser',
      translation: 'peluquero',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_tailor_001',
      word: 'tailor',
      translation: 'sastre',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_baker_001',
      word: 'baker',
      translation: 'panadero',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_butcher_001',
      word: 'butcher',
      translation: 'carnicero',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_job_001',
      word: 'job',
      translation: 'trabajo/empleo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_career_001',
      word: 'career',
      translation: 'carrera',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_company_001',
      word: 'company',
      translation: 'empresa',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_office_001',
      word: 'office',
      translation: 'oficina',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_salary_001',
      word: 'salary',
      translation: 'salario',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_classroom_001',
      word: 'classroom',
      translation: 'salón de clases',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_class_001',
      word: 'class',
      translation: 'clase',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_lesson_001',
      word: 'lesson',
      translation: 'lección',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_subject_001',
      word: 'subject',
      translation: 'materia',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_math_001',
      word: 'math',
      translation: 'matemáticas',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_science_001',
      word: 'science',
      translation: 'ciencia',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_history_001',
      word: 'history',
      translation: 'historia',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_geography_001',
      word: 'geography',
      translation: 'geografía',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_art_001',
      word: 'art',
      translation: 'arte',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_music_001',
      word: 'music',
      translation: 'música',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_physical-education_001',
      word: 'physical education',
      translation: 'educación física',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_book_001',
      word: 'book',
      translation: 'libro',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_notebook_001',
      word: 'notebook',
      translation: 'cuaderno',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_pen_001',
      word: 'pen',
      translation: 'bolígrafo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_pencil_001',
      word: 'pencil',
      translation: 'lápiz',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_eraser_001',
      word: 'eraser',
      translation: 'borrador',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_ruler_001',
      word: 'ruler',
      translation: 'regla',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_backpack_001',
      word: 'backpack',
      translation: 'mochila',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_homework_001',
      word: 'homework',
      translation: 'tarea',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_exam-test_001',
      word: 'exam / test',
      translation: 'examen',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_grade_001',
      word: 'grade (school)',
      translation: 'calificación',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_question_001',
      word: 'question',
      translation: 'pregunta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_blackboard-whiteboard_001',
      word: 'blackboard / whiteboard',
      translation: 'pizarra',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_desk_002',
      word: 'desk (school)',
      translation: 'pupitre',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_principal_001',
      word: 'principal',
      translation: 'director/a',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_university_001',
      word: 'university',
      translation: 'universidad',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
  ],
}
