import type { ContentBlock } from '../types'

/**
 * A1 Level — Week 7
 * Topic: Semana 7 – Ropa y cuerpo
 * Curated from: a.md
 * Total items: 77
 */
export const week07: ContentBlock = {
  level: 'A1',
  week: 7,
  topic: 'Semana 7 – Ropa y cuerpo',
  vocabulary: [
    {
      id: 'voc_a1_shirt_001',
      word: 'shirt',
      translation: 'camisa',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_t-shirt_001',
      word: 't-shirt',
      translation: 'camiseta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_pants-trousers_001',
      word: 'pants / trousers',
      translation: 'pantalones',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_jeans_001',
      word: 'jeans',
      translation: 'jeans',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_dress_001',
      word: 'dress',
      translation: 'vestido',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_skirt_001',
      word: 'skirt',
      translation: 'falda',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_jacket_001',
      word: 'jacket',
      translation: 'chaqueta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_coat_001',
      word: 'coat',
      translation: 'abrigo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_sweater_001',
      word: 'sweater',
      translation: 'suéter',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_suit_001',
      word: 'suit',
      translation: 'traje',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_shoes_001',
      word: 'shoes',
      translation: 'zapatos',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_socks_001',
      word: 'socks',
      translation: 'calcetines',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_hat_001',
      word: 'hat',
      translation: 'sombrero',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_cap_001',
      word: 'cap',
      translation: 'gorra',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_gloves_001',
      word: 'gloves',
      translation: 'guantes',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_scarf_001',
      word: 'scarf',
      translation: 'bufanda',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_belt_001',
      word: 'belt',
      translation: 'cinturón',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_tie_001',
      word: 'tie',
      translation: 'corbata',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_underwear_001',
      word: 'underwear',
      translation: 'ropa interior',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_pajamas_001',
      word: 'pajamas',
      translation: 'pijama',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_shorts_001',
      word: 'shorts',
      translation: 'pantalones cortos',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_boots_001',
      word: 'boots',
      translation: 'botas',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_sandals_001',
      word: 'sandals',
      translation: 'sandalias',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_head_001',
      word: 'head',
      translation: 'cabeza',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_hair_001',
      word: 'hair',
      translation: 'cabello',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_face_001',
      word: 'face',
      translation: 'cara',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_eye_001',
      word: 'eye',
      translation: 'ojo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_ear_001',
      word: 'ear',
      translation: 'oreja',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_nose_001',
      word: 'nose',
      translation: 'nariz',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_mouth_001',
      word: 'mouth',
      translation: 'boca',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_teeth_001',
      word: 'teeth',
      translation: 'dientes',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_tongue_001',
      word: 'tongue',
      translation: 'lengua',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_neck_001',
      word: 'neck',
      translation: 'cuello',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_shoulder_001',
      word: 'shoulder',
      translation: 'hombro',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_arm_001',
      word: 'arm',
      translation: 'brazo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_elbow_001',
      word: 'elbow',
      translation: 'codo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_hand_001',
      word: 'hand',
      translation: 'mano',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_finger_001',
      word: 'finger',
      translation: 'dedo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_chest_001',
      word: 'chest',
      translation: 'pecho',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_back_001',
      word: 'back',
      translation: 'espalda',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_stomach_001',
      word: 'stomach',
      translation: 'estómago',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_leg_001',
      word: 'leg',
      translation: 'pierna',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_knee_001',
      word: 'knee',
      translation: 'rodilla',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_foot-feet_001',
      word: 'foot / feet',
      translation: 'pie / pies',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_toe_001',
      word: 'toe',
      translation: 'dedo del pie',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_skin_001',
      word: 'skin',
      translation: 'piel',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_heart_002',
      word: 'heart (body)',
      translation: 'corazón (órgano)',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_brain_001',
      word: 'brain',
      translation: 'cerebro',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_bone_001',
      word: 'bone',
      translation: 'hueso',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_blood_001',
      word: 'blood',
      translation: 'sangre',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_muscle_001',
      word: 'muscle',
      translation: 'músculo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_nail_001',
      word: 'nail',
      translation: 'uña',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_lip_001',
      word: 'lip',
      translation: 'labio',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_eyebrow_001',
      word: 'eyebrow',
      translation: 'ceja',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_eyelash_001',
      word: 'eyelash',
      translation: 'pestaña',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_chin_001',
      word: 'chin',
      translation: 'mentón',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_cheek_001',
      word: 'cheek',
      translation: 'mejilla',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_forehead_001',
      word: 'forehead',
      translation: 'frente',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_waist_001',
      word: 'waist',
      translation: 'cintura',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_wear_001',
      word: 'wear',
      translation: 'llevar puesto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_put-on_001',
      word: 'put on',
      translation: 'ponerse',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_take-off_001',
      word: 'take off',
      translation: 'quitarse',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_dress_002',
      word: 'dress (verb)',
      translation: 'vestirse',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_try-on_001',
      word: 'try on',
      translation: 'probarse',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_size_001',
      word: 'size',
      translation: 'talla',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_fashion_001',
      word: 'fashion',
      translation: 'moda',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_style_001',
      word: 'style',
      translation: 'estilo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_fabric_001',
      word: 'fabric',
      translation: 'tela',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_cotton_001',
      word: 'cotton',
      translation: 'algodón',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_wool_001',
      word: 'wool',
      translation: 'lana',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_leather_001',
      word: 'leather',
      translation: 'cuero',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_button_001',
      word: 'button',
      translation: 'botón',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_zipper_001',
      word: 'zipper',
      translation: 'cremallera',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_pocket_001',
      word: 'pocket',
      translation: 'bolsillo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_sleeve_001',
      word: 'sleeve',
      translation: 'manga',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_collar_001',
      word: 'collar',
      translation: 'cuello (ropa)',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_umbrella_001',
      word: 'umbrella',
      translation: 'paraguas',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
  ],
}
