import type { ContentBlock } from '../types'

/**
 * A1 Level — Week 5
 * Topic: Semana 5 – La casa y los muebles
 * Curated from: a.md
 * Total items: 81
 */
export const week05: ContentBlock = {
  level: 'A1',
  week: 5,
  topic: 'Semana 5 – La casa y los muebles',
  vocabulary: [
    {
      id: 'voc_a1_house_001',
      word: 'house',
      translation: 'casa',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/haʊs/',
      example: 'We bought a new house.',
      exampleTranslation: 'Compramos una casa nueva.',
      status: 'approved',
    },
    {
      id: 'voc_a1_home_001',
      word: 'home',
      translation: 'hogar',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/hoʊm/',
      example: 'I feel comfortable at home.',
      exampleTranslation: 'Me siento cómodo en casa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_apartment-flat_001',
      word: 'apartment / flat',
      translation: 'apartamento',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈpɑrtmənt/',
      example: 'She lives in a small apartment.',
      exampleTranslation: 'Ella vive en un apartamento pequeño.',
      status: 'approved',
    },
    {
      id: 'voc_a1_room_001',
      word: 'room',
      translation: 'habitación',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rum/',
      example: 'This room is very bright.',
      exampleTranslation: 'Esta habitación es muy luminosa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_bedroom_001',
      word: 'bedroom',
      translation: 'dormitorio',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbɛdˌrum/',
      example: 'My bedroom is upstairs.',
      exampleTranslation: 'Mi dormitorio está arriba.',
      status: 'approved',
    },
    {
      id: 'voc_a1_bathroom_001',
      word: 'bathroom',
      translation: 'baño',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbæθˌrum/',
      example: 'The bathroom is next to the kitchen.',
      exampleTranslation: 'El baño está junto a la cocina.',
      status: 'approved',
    },
    {
      id: 'voc_a1_kitchen_001',
      word: 'kitchen',
      translation: 'cocina',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkɪtʃən/',
      example: 'She is cooking in the kitchen.',
      exampleTranslation: 'Ella está cocinando en la cocina.',
      status: 'approved',
    },
    {
      id: 'voc_a1_living-room_001',
      word: 'living room',
      translation: 'sala',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈlɪvɪŋ rum/',
      example: 'We watch TV in the living room.',
      exampleTranslation: 'Vemos televisión en la sala.',
      status: 'approved',
    },
    {
      id: 'voc_a1_dining-room_001',
      word: 'dining room',
      translation: 'comedor',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdaɪnɪŋ rum/',
      example: 'We eat in the dining room.',
      exampleTranslation: 'Comemos en el comedor.',
      status: 'approved',
    },
    {
      id: 'voc_a1_garden_001',
      word: 'garden',
      translation: 'jardín',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈgɑrdən/',
      example: 'My mother loves her garden.',
      exampleTranslation: 'Mi madre ama su jardín.',
      status: 'approved',
    },
    {
      id: 'voc_a1_yard_001',
      word: 'yard',
      translation: 'patio',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/jɑrd/',
      example: 'The children play in the yard.',
      exampleTranslation: 'Los niños juegan en el patio.',
      status: 'approved',
    },
    {
      id: 'voc_a1_garage_001',
      word: 'garage',
      translation: 'garaje',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/gəˈrɑʒ/',
      example: 'The car is in the garage.',
      exampleTranslation: 'El carro está en el garaje.',
      status: 'approved',
    },
    {
      id: 'voc_a1_roof_001',
      word: 'roof',
      translation: 'techo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ruf/',
      example: 'The roof needs repair.',
      exampleTranslation: 'El techo necesita reparación.',
      status: 'approved',
    },
    {
      id: 'voc_a1_door_001',
      word: 'door',
      translation: 'puerta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dɔr/',
      example: 'Please close the door.',
      exampleTranslation: 'Por favor cierra la puerta.',
      status: 'approved',
    },
    {
      id: 'voc_a1_window_001',
      word: 'window',
      translation: 'ventana',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈwɪndoʊ/',
      example: 'Open the window, please.',
      exampleTranslation: 'Abre la ventana, por favor.',
      status: 'approved',
    },
    {
      id: 'voc_a1_wall_001',
      word: 'wall',
      translation: 'pared',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/wɔl/',
      example: 'There is a picture on the wall.',
      exampleTranslation: 'Hay un cuadro en la pared.',
      status: 'approved',
    },
    {
      id: 'voc_a1_floor_001',
      word: 'floor',
      translation: 'piso',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/flɔr/',
      example: 'The floor is very clean.',
      exampleTranslation: 'El piso está muy limpio.',
      status: 'approved',
    },
    {
      id: 'voc_a1_ceiling_001',
      word: 'ceiling',
      translation: 'cielo raso',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsilɪŋ/',
      example: 'There is a lamp on the ceiling.',
      exampleTranslation: 'Hay una lámpara en el techo (interior).',
      status: 'approved',
    },
    {
      id: 'voc_a1_stairs_001',
      word: 'stairs',
      translation: 'escaleras',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/stɛrz/',
      example: 'Be careful on the stairs.',
      exampleTranslation: 'Ten cuidado en las escaleras.',
      status: 'approved',
    },
    {
      id: 'voc_a1_table_001',
      word: 'table',
      translation: 'mesa',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈteɪbəl/',
      example: 'Put the plates on the table.',
      exampleTranslation: 'Pon los platos en la mesa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_chair_001',
      word: 'chair',
      translation: 'silla',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tʃɛr/',
      example: 'This chair is very comfortable.',
      exampleTranslation: 'Esta silla es muy cómoda.',
      status: 'approved',
    },
    {
      id: 'voc_a1_sofa-couch_001',
      word: 'sofa / couch',
      translation: 'sofá',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsoʊfə/',
      example: 'We sit on the sofa every night.',
      exampleTranslation: 'Nos sentamos en el sofá cada noche.',
      status: 'approved',
    },
    {
      id: 'voc_a1_bed_001',
      word: 'bed',
      translation: 'cama',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bɛd/',
      example: 'I make my bed every morning.',
      exampleTranslation: 'Hago mi cama todas las mañanas.',
      status: 'approved',
    },
    {
      id: 'voc_a1_desk_001',
      word: 'desk',
      translation: 'escritorio',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dɛsk/',
      example: 'The computer is on the desk.',
      exampleTranslation: 'La computadora está en el escritorio.',
      status: 'approved',
    },
    {
      id: 'voc_a1_shelf_001',
      word: 'shelf',
      translation: 'estante',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ʃɛlf/',
      example: 'The books are on the shelf.',
      exampleTranslation: 'Los libros están en el estante.',
      status: 'approved',
    },
    {
      id: 'voc_a1_wardrobe-closet_001',
      word: 'wardrobe / closet',
      translation: 'armario',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈwɔrˌdroʊb/',
      example: 'My clothes are in the wardrobe.',
      exampleTranslation: 'Mi ropa está en el armario.',
      status: 'approved',
    },
    {
      id: 'voc_a1_drawer_001',
      word: 'drawer',
      translation: 'cajón',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/drɔr/',
      example: 'The keys are in the drawer.',
      exampleTranslation: 'Las llaves están en el cajón.',
      status: 'approved',
    },
    {
      id: 'voc_a1_mirror_001',
      word: 'mirror',
      translation: 'espejo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmɪrər/',
      example: 'She looks in the mirror every day.',
      exampleTranslation: 'Ella se mira en el espejo todos los días.',
      status: 'approved',
    },
    {
      id: 'voc_a1_lamp_001',
      word: 'lamp',
      translation: 'lámpara',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/læmp/',
      example: 'Turn on the lamp, please.',
      exampleTranslation: 'Enciende la lámpara, por favor.',
      status: 'approved',
    },
    {
      id: 'voc_a1_curtain_001',
      word: 'curtain',
      translation: 'cortina',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkɜrtən/',
      example: 'Close the curtain, it\'s too bright.',
      exampleTranslation: 'Cierra la cortina, hay mucha luz.',
      status: 'approved',
    },
    {
      id: 'voc_a1_carpet-rug_001',
      word: 'carpet / rug',
      translation: 'alfombra',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkɑrpət/',
      example: 'The carpet is very soft.',
      exampleTranslation: 'La alfombra es muy suave.',
      status: 'approved',
    },
    {
      id: 'voc_a1_fridge-refrigerator_001',
      word: 'fridge / refrigerator',
      translation: 'refrigerador',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/frɪdʒ/',
      example: 'There is milk in the fridge.',
      exampleTranslation: 'Hay leche en el refrigerador.',
      status: 'approved',
    },
    {
      id: 'voc_a1_oven_001',
      word: 'oven',
      translation: 'horno',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈʌvən/',
      example: 'The bread is in the oven.',
      exampleTranslation: 'El pan está en el horno.',
      status: 'approved',
    },
    {
      id: 'voc_a1_stove_001',
      word: 'stove',
      translation: 'estufa',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/stoʊv/',
      example: 'She is cooking on the stove.',
      exampleTranslation: 'Ella está cocinando en la estufa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_microwave_001',
      word: 'microwave',
      translation: 'microondas',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmaɪkrəˌweɪv/',
      example: 'I heat my food in the microwave.',
      exampleTranslation: 'Caliento mi comida en el microondas.',
      status: 'approved',
    },
    {
      id: 'voc_a1_washing-machine_001',
      word: 'washing machine',
      translation: 'lavadora',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈwɑʃɪŋ məˌʃin/',
      example: 'The washing machine is broken.',
      exampleTranslation: 'La lavadora está descompuesta.',
      status: 'approved',
    },
    {
      id: 'voc_a1_dishwasher_001',
      word: 'dishwasher',
      translation: 'lavavajillas',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdɪʃˌwɑʃər/',
      example: 'Put the plates in the dishwasher.',
      exampleTranslation: 'Pon los platos en el lavavajillas.',
      status: 'approved',
    },
    {
      id: 'voc_a1_television-tv_001',
      word: 'television / TV',
      translation: 'televisor',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtɛləˌvɪʒən/',
      example: 'We watch the news on television.',
      exampleTranslation: 'Vemos las noticias en la televisión.',
      status: 'approved',
    },
    {
      id: 'voc_a1_computer_001',
      word: 'computer',
      translation: 'computadora',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kəmˈpjutər/',
      example: 'I work on my computer all day.',
      exampleTranslation: 'Trabajo en mi computadora todo el día.',
      status: 'approved',
    },
    {
      id: 'voc_a1_telephone-phone_001',
      word: 'telephone / phone',
      translation: 'teléfono',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtɛləˌfoʊn/',
      example: 'My phone is on the table.',
      exampleTranslation: 'Mi teléfono está en la mesa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_radio_001',
      word: 'radio',
      translation: 'radio',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈreɪdiˌoʊ/',
      example: 'I listen to the radio in the car.',
      exampleTranslation: 'Escucho la radio en el carro.',
      status: 'approved',
    },
    {
      id: 'voc_a1_clock_001',
      word: 'clock',
      translation: 'reloj',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/klɑk/',
      example: 'The clock says three o\'clock.',
      exampleTranslation: 'El reloj marca las tres.',
      status: 'approved',
    },
    {
      id: 'voc_a1_fan_001',
      word: 'fan',
      translation: 'ventilador',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fæn/',
      example: 'Turn on the fan, it\'s hot.',
      exampleTranslation: 'Enciende el ventilador, hace calor.',
      status: 'approved',
    },
    {
      id: 'voc_a1_heater_001',
      word: 'heater',
      translation: 'calentador',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈhitər/',
      example: 'We need a heater in winter.',
      exampleTranslation: 'Necesitamos un calentador en invierno.',
      status: 'approved',
    },
    {
      id: 'voc_a1_air-conditioner_001',
      word: 'air conditioner',
      translation: 'aire acondicionado',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɛr kənˈdɪʃənər/',
      example: 'The air conditioner is very cold.',
      exampleTranslation: 'El aire acondicionado está muy frío.',
      status: 'approved',
    },
    {
      id: 'voc_a1_plate_001',
      word: 'plate',
      translation: 'plato',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pleɪt/',
      example: 'Put the food on the plate.',
      exampleTranslation: 'Pon la comida en el plato.',
      status: 'approved',
    },
    {
      id: 'voc_a1_cup_001',
      word: 'cup',
      translation: 'taza',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kʌp/',
      example: 'She has a cup of tea.',
      exampleTranslation: 'Ella tiene una taza de té.',
      status: 'approved',
    },
    {
      id: 'voc_a1_glass_001',
      word: 'glass',
      translation: 'vaso',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/glæs/',
      example: 'Can I have a glass of water?',
      exampleTranslation: '¿Puedo tomar un vaso de agua?',
      status: 'approved',
    },
    {
      id: 'voc_a1_bowl_001',
      word: 'bowl',
      translation: 'tazón',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/boʊl/',
      example: 'I eat cereal in a bowl.',
      exampleTranslation: 'Como cereal en un tazón.',
      status: 'approved',
    },
    {
      id: 'voc_a1_spoon_001',
      word: 'spoon',
      translation: 'cuchara',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/spun/',
      example: 'I need a spoon for the soup.',
      exampleTranslation: 'Necesito una cuchara para la sopa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_fork_001',
      word: 'fork',
      translation: 'tenedor',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fɔrk/',
      example: 'Use a fork to eat the salad.',
      exampleTranslation: 'Usa un tenedor para comer la ensalada.',
      status: 'approved',
    },
    {
      id: 'voc_a1_knife_001',
      word: 'knife',
      translation: 'cuchillo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/naɪf/',
      example: 'Be careful with that knife.',
      exampleTranslation: 'Ten cuidado con ese cuchillo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_pan_001',
      word: 'pan',
      translation: 'sartén',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pæn/',
      example: 'She fries eggs in a pan.',
      exampleTranslation: 'Ella fríe huevos en un sartén.',
      status: 'approved',
    },
    {
      id: 'voc_a1_pot_001',
      word: 'pot',
      translation: 'olla',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pɑt/',
      example: 'The soup is in the pot.',
      exampleTranslation: 'La sopa está en la olla.',
      status: 'approved',
    },
    {
      id: 'voc_a1_kettle_001',
      word: 'kettle',
      translation: 'tetera',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkɛtəl/',
      example: 'I boil water in the kettle.',
      exampleTranslation: 'Hiervo agua en la tetera.',
      status: 'approved',
    },
    {
      id: 'voc_a1_key_001',
      word: 'key',
      translation: 'llave',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ki/',
      example: 'I lost my house key.',
      exampleTranslation: 'Perdí la llave de mi casa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_lock_001',
      word: 'lock',
      translation: 'cerradura',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/lɑk/',
      example: 'Check the lock before you leave.',
      exampleTranslation: 'Revisa la cerradura antes de salir.',
      status: 'approved',
    },
    {
      id: 'voc_a1_light_002',
      word: 'light (lamp)',
      translation: 'luz',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/laɪt/',
      example: 'Turn off the light, please.',
      exampleTranslation: 'Apaga la luz, por favor.',
      status: 'approved',
    },
    {
      id: 'voc_a1_switch_001',
      word: 'switch',
      translation: 'interruptor',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/swɪtʃ/',
      example: 'The light switch is next to the door.',
      exampleTranslation: 'El interruptor está junto a la puerta.',
      status: 'approved',
    },
    {
      id: 'voc_a1_towel_001',
      word: 'towel',
      translation: 'toalla',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtaʊəl/',
      example: 'Use this towel to dry your hands.',
      exampleTranslation: 'Usa esta toalla para secarte las manos.',
      status: 'approved',
    },
    {
      id: 'voc_a1_soap_001',
      word: 'soap',
      translation: 'jabón',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/soʊp/',
      example: 'Wash your hands with soap.',
      exampleTranslation: 'Lávate las manos con jabón.',
      status: 'approved',
    },
    {
      id: 'voc_a1_toothbrush_001',
      word: 'toothbrush',
      translation: 'cepillo de dientes',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtuθˌbrʌʃ/',
      example: 'I need a new toothbrush.',
      exampleTranslation: 'Necesito un cepillo de dientes nuevo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_pillow_001',
      word: 'pillow',
      translation: 'almohada',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpɪloʊ/',
      example: 'My pillow is very soft.',
      exampleTranslation: 'Mi almohada es muy suave.',
      status: 'approved',
    },
    {
      id: 'voc_a1_blanket_001',
      word: 'blanket',
      translation: 'manta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈblæŋkɪt/',
      example: 'I need a warm blanket.',
      exampleTranslation: 'Necesito una manta cálida.',
      status: 'approved',
    },
    {
      id: 'voc_a1_sheet_001',
      word: 'sheet',
      translation: 'sábana',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ʃit/',
      example: 'We changed the bed sheets today.',
      exampleTranslation: 'Cambiamos las sábanas hoy.',
      status: 'approved',
    },
    {
      id: 'voc_a1_basement_001',
      word: 'basement',
      translation: 'sótano',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbeɪsmənt/',
      example: 'We keep old boxes in the basement.',
      exampleTranslation: 'Guardamos cajas viejas en el sótano.',
      status: 'approved',
    },
    {
      id: 'voc_a1_attic_001',
      word: 'attic',
      translation: 'ático',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈætɪk/',
      example: 'The attic is full of old furniture.',
      exampleTranslation: 'El ático está lleno de muebles viejos.',
      status: 'approved',
    },
    {
      id: 'voc_a1_balcony_001',
      word: 'balcony',
      translation: 'balcón',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbælkəni/',
      example: 'We have coffee on the balcony.',
      exampleTranslation: 'Tomamos café en el balcón.',
      status: 'approved',
    },
    {
      id: 'voc_a1_fence_001',
      word: 'fence',
      translation: 'cerca',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fɛns/',
      example: 'There is a fence around the yard.',
      exampleTranslation: 'Hay una cerca alrededor del patio.',
      status: 'approved',
    },
    {
      id: 'voc_a1_driveway_001',
      word: 'driveway',
      translation: 'entrada de auto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdraɪvˌweɪ/',
      example: 'The car is parked in the driveway.',
      exampleTranslation: 'El carro está estacionado en la entrada.',
      status: 'approved',
    },
    {
      id: 'voc_a1_mailbox_001',
      word: 'mailbox',
      translation: 'buzón',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmeɪlˌbɑks/',
      example: 'Check the mailbox for letters.',
      exampleTranslation: 'Revisa el buzón por si hay cartas.',
      status: 'approved',
    },
    {
      id: 'voc_a1_furniture_001',
      word: 'furniture',
      translation: 'muebles',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfɜrnɪtʃər/',
      example: 'We need new furniture for the living room.',
      exampleTranslation: 'Necesitamos muebles nuevos para la sala.',
      status: 'approved',
    },
    {
      id: 'voc_a1_address_001',
      word: 'address',
      translation: 'dirección',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈdrɛs/',
      example: 'What is your address?',
      exampleTranslation: '¿Cuál es tu dirección?',
      status: 'approved',
    },
    {
      id: 'voc_a1_neighborhood_001',
      word: 'neighborhood',
      translation: 'vecindario',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈneɪbərˌhʊd/',
      example: 'This is a quiet neighborhood.',
      exampleTranslation: 'Este es un vecindario tranquilo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_upstairs_001',
      word: 'upstairs',
      translation: 'arriba',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ʌpˈstɛrz/',
      example: 'The bedrooms are upstairs.',
      exampleTranslation: 'Los dormitorios están arriba.',
      status: 'approved',
    },
    {
      id: 'voc_a1_downstairs_001',
      word: 'downstairs',
      translation: 'abajo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌdaʊnˈstɛrz/',
      example: 'The kitchen is downstairs.',
      exampleTranslation: 'La cocina está abajo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_move_001',
      word: 'move (house)',
      translation: 'mudarse',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/muv/',
      example: 'We are moving next month.',
      exampleTranslation: 'Nos mudamos el próximo mes.',
      status: 'approved',
    },
    {
      id: 'voc_a1_rent_001',
      word: 'rent',
      translation: 'alquilar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rɛnt/',
      example: 'We rent this apartment.',
      exampleTranslation: 'Alquilamos este apartamento.',
      status: 'approved',
    },
    {
      id: 'voc_a1_own_001',
      word: 'own',
      translation: 'poseer',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/oʊn/',
      example: 'They own a small house.',
      exampleTranslation: 'Ellos poseen una casa pequeña.',
      status: 'approved',
    },
    {
      id: 'voc_a1_decorate_001',
      word: 'decorate',
      translation: 'decorar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdɛkəˌreɪt/',
      example: 'We decorated the house for the party.',
      exampleTranslation: 'Decoramos la casa para la fiesta.',
      status: 'approved',
    },
    {
      id: 'voc_a1_paint_001',
      word: 'paint',
      translation: 'pintar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/peɪnt/',
      example: 'We painted the walls white.',
      exampleTranslation: 'Pintamos las paredes de blanco.',
      status: 'approved',
    },
  ],
}
