import type { ContentBlock } from '../types'

/**
 * A1 Level — Week 12
 * Topic: Semana 12 – Transporte y viajes
 * Curated from: a.md
 * Total items: 75
 */
export const week12: ContentBlock = {
  level: 'A1',
  week: 12,
  topic: 'Semana 12 – Transporte y viajes',
  vocabulary: [
    {
      id: 'voc_a1_car_001',
      word: 'car',
      translation: 'carro',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_bus_001',
      word: 'bus',
      translation: 'autobús',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_train_001',
      word: 'train',
      translation: 'tren',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_plane-airplane_001',
      word: 'plane / airplane',
      translation: 'avión',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_bike-bicycle_001',
      word: 'bike / bicycle',
      translation: 'bicicleta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_motorcycle_001',
      word: 'motorcycle',
      translation: 'motocicleta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_taxi_001',
      word: 'taxi',
      translation: 'taxi',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_truck_001',
      word: 'truck',
      translation: 'camión',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_boat_001',
      word: 'boat',
      translation: 'bote',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_ship_001',
      word: 'ship',
      translation: 'barco',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_subway-metro_001',
      word: 'subway / metro',
      translation: 'metro',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_trip_001',
      word: 'trip',
      translation: 'viaje',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_journey_001',
      word: 'journey',
      translation: 'travesía',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_tourist_001',
      word: 'tourist',
      translation: 'turista',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_passport_001',
      word: 'passport',
      translation: 'pasaporte',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_ticket_001',
      word: 'ticket',
      translation: 'boleto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_luggage_001',
      word: 'luggage',
      translation: 'equipaje',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_suitcase_001',
      word: 'suitcase',
      translation: 'maleta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_reservation_001',
      word: 'reservation',
      translation: 'reservación',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_flight_001',
      word: 'flight',
      translation: 'vuelo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_gate_001',
      word: 'gate (airport)',
      translation: 'puerta de embarque',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_arrival_001',
      word: 'arrival',
      translation: 'llegada',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_departure_001',
      word: 'departure',
      translation: 'salida',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_destination_001',
      word: 'destination',
      translation: 'destino',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_souvenir_001',
      word: 'souvenir',
      translation: 'recuerdo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_fly_002',
      word: 'fly (verb)',
      translation: 'volar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_park_002',
      word: 'park (verb)',
      translation: 'estacionar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_depart_001',
      word: 'depart',
      translation: 'partir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_book_002',
      word: 'book (verb)',
      translation: 'reservar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_pack_001',
      word: 'pack',
      translation: 'empacar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_traffic_001',
      word: 'traffic',
      translation: 'tráfico',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_highway_001',
      word: 'highway',
      translation: 'autopista',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_crossing_001',
      word: 'crossing',
      translation: 'cruce',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_seatbelt_001',
      word: 'seatbelt',
      translation: 'cinturón de seguridad',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_gas-station_001',
      word: 'gas station',
      translation: 'gasolinera',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_ticket-office_001',
      word: 'ticket office',
      translation: 'taquilla',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_platform_001',
      word: 'platform',
      translation: 'andén',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_terminal_001',
      word: 'terminal',
      translation: 'terminal',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_captain_001',
      word: 'captain',
      translation: 'capitán',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_passenger_001',
      word: 'passenger',
      translation: 'pasajero',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_drivers-license_001',
      word: "driver's license",
      translation: 'licencia de conducir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_fare_001',
      word: 'fare',
      translation: 'tarifa',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_route_001',
      word: 'route',
      translation: 'ruta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_schedule_001',
      word: 'schedule',
      translation: 'horario',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_delay_001',
      word: 'delay',
      translation: 'retraso',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_connection_001',
      word: 'connection (travel)',
      translation: 'conexión',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_customs_001',
      word: 'customs',
      translation: 'aduana',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_border_001',
      word: 'border',
      translation: 'frontera',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_visa_001',
      word: 'visa',
      translation: 'visa',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_guide_001',
      word: 'guide (tourist)',
      translation: 'guía',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_seat_001',
      word: 'seat',
      translation: 'asiento',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_aisle_001',
      word: 'aisle',
      translation: 'pasillo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_cabin_001',
      word: 'cabin',
      translation: 'cabina',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_crew_001',
      word: 'crew',
      translation: 'tripulación',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_roundtrip_001',
      word: 'roundtrip',
      translation: 'viaje redondo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_one-way_001',
      word: 'one-way',
      translation: 'de ida',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_boarding-pass_001',
      word: 'boarding pass',
      translation: 'tarjeta de embarque',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_security-check_001',
      word: 'security check',
      translation: 'control de seguridad',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_immigration_001',
      word: 'immigration',
      translation: 'inmigración',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_currency_001',
      word: 'currency',
      translation: 'moneda (divisa)',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_exchange-rate_001',
      word: 'exchange rate',
      translation: 'tipo de cambio',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_cruise_001',
      word: 'cruise',
      translation: 'crucero',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_ferry_001',
      word: 'ferry',
      translation: 'transbordador',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_cable-car_001',
      word: 'cable car',
      translation: 'teleférico',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_elevator_001',
      word: 'elevator',
      translation: 'ascensor',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_escalator_001',
      word: 'escalator',
      translation: 'escalera mecánica',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_carpool_001',
      word: 'carpool',
      translation: 'compartir auto',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_rush-hour_001',
      word: 'rush hour',
      translation: 'hora pico',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_parking-lot_001',
      word: 'parking lot',
      translation: 'estacionamiento',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_mileage_001',
      word: 'mileage',
      translation: 'kilometraje',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_license-plate_001',
      word: 'license plate',
      translation: 'placa de matrícula',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_wheel_001',
      word: 'wheel',
      translation: 'rueda',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_tire_001',
      word: 'tire',
      translation: 'llanta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_brake_001',
      word: 'brake',
      translation: 'freno',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_horn_001',
      word: 'horn (car)',
      translation: 'bocina',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
  ],
}
