import type { ContentBlock } from '../types'

/**
 * A1 Level — Week 16
 * Topic: Semana 16 – Tecnología, comunicación y entretenimiento
 * Curated from: a.md
 * Total items: 105
 */
export const week16: ContentBlock = {
  level: 'A1',
  week: 16,
  topic: 'Semana 16 – Tecnología, comunicación y entretenimiento',
  vocabulary: [
    {
      id: 'voc_a1_laptop_001',
      word: 'laptop',
      translation: 'laptop',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈlæpˌtɑp/',
      example: 'I work on my laptop every day.',
      exampleTranslation: 'Trabajo en mi laptop todos los días.',
      status: 'approved',
    },
    {
      id: 'voc_a1_tablet_001',
      word: 'tablet',
      translation: 'tableta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtæblət/',
      example: 'My daughter watches videos on her tablet.',
      exampleTranslation: 'Mi hija ve videos en su tableta.',
      status: 'approved',
    },
    {
      id: 'voc_a1_smartphone_001',
      word: 'smartphone',
      translation: 'teléfono inteligente',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsmɑrtˌfoʊn/',
      example: 'I lost my smartphone yesterday.',
      exampleTranslation: 'Perdí mi teléfono inteligente ayer.',
      status: 'approved',
    },
    {
      id: 'voc_a1_screen_001',
      word: 'screen',
      translation: 'pantalla',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/skrin/',
      example: 'The screen is very bright.',
      exampleTranslation: 'La pantalla es muy brillante.',
      status: 'approved',
    },
    {
      id: 'voc_a1_keyboard_001',
      word: 'keyboard',
      translation: 'teclado',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkiˌbɔrd/',
      example: 'My keyboard is not working.',
      exampleTranslation: 'Mi teclado no funciona.',
      status: 'approved',
    },
    {
      id: 'voc_a1_mouse_002',
      word: 'mouse (device)',
      translation: 'ratón (dispositivo)',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/maʊs/',
      example: 'I need a new mouse for my computer.',
      exampleTranslation: 'Necesito un ratón nuevo para mi computadora.',
      status: 'approved',
    },
    {
      id: 'voc_a1_password_001',
      word: 'password',
      translation: 'contraseña',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpæsˌwɜrd/',
      example: 'I forgot my password.',
      exampleTranslation: 'Olvidé mi contraseña.',
      status: 'approved',
    },
    {
      id: 'voc_a1_internet_001',
      word: 'internet',
      translation: 'internet',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɪntərˌnɛt/',
      example: 'The internet is very slow today.',
      exampleTranslation: 'El internet está muy lento hoy.',
      status: 'approved',
    },
    {
      id: 'voc_a1_website_001',
      word: 'website',
      translation: 'sitio web',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈwɛbˌsaɪt/',
      example: 'I found this recipe on a website.',
      exampleTranslation: 'Encontré esta receta en un sitio web.',
      status: 'approved',
    },
    {
      id: 'voc_a1_email_001',
      word: 'email',
      translation: 'correo electrónico',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈiˌmeɪl/',
      example: 'I sent you an email this morning.',
      exampleTranslation: 'Te envié un correo electrónico esta mañana.',
      status: 'approved',
    },
    {
      id: 'voc_a1_message_001',
      word: 'message',
      translation: 'mensaje',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmɛsɪdʒ/',
      example: 'She sent me a nice message.',
      exampleTranslation: 'Ella me envió un mensaje lindo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_text-message_001',
      word: 'text message',
      translation: 'mensaje de texto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tɛkst ˈmɛsɪdʒ/',
      example: 'I got your text message.',
      exampleTranslation: 'Recibí tu mensaje de texto.',
      status: 'approved',
    },
    {
      id: 'voc_a1_app-application_001',
      word: 'app / application',
      translation: 'aplicación',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/æp/',
      example: 'I use this app to learn English.',
      exampleTranslation: 'Uso esta aplicación para aprender inglés.',
      status: 'approved',
    },
    {
      id: 'voc_a1_social-media_001',
      word: 'social media',
      translation: 'redes sociales',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsoʊʃəl ˈmidiə/',
      example: 'She spends a lot of time on social media.',
      exampleTranslation: 'Ella pasa mucho tiempo en redes sociales.',
      status: 'approved',
    },
    {
      id: 'voc_a1_photo-picture_001',
      word: 'photo / picture',
      translation: 'foto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfoʊˌtoʊ/',
      example: 'Can you take a photo of us?',
      exampleTranslation: '¿Puedes tomarnos una foto?',
      status: 'approved',
    },
    {
      id: 'voc_a1_video_001',
      word: 'video',
      translation: 'video',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈvɪdioʊ/',
      example: 'We watched a funny video.',
      exampleTranslation: 'Vimos un video gracioso.',
      status: 'approved',
    },
    {
      id: 'voc_a1_camera_001',
      word: 'camera',
      translation: 'cámara',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkæmərə/',
      example: 'I bought a new camera.',
      exampleTranslation: 'Compré una cámara nueva.',
      status: 'approved',
    },
    {
      id: 'voc_a1_printer_001',
      word: 'printer',
      translation: 'impresora',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈprɪntər/',
      example: 'The printer is out of paper.',
      exampleTranslation: 'La impresora se quedó sin papel.',
      status: 'approved',
    },
    {
      id: 'voc_a1_charger_001',
      word: 'charger',
      translation: 'cargador',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtʃɑrdʒər/',
      example: 'Can I borrow your charger?',
      exampleTranslation: '¿Me prestas tu cargador?',
      status: 'approved',
    },
    {
      id: 'voc_a1_battery_001',
      word: 'battery',
      translation: 'batería',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbætəri/',
      example: 'My phone battery is low.',
      exampleTranslation: 'La batería de mi teléfono está baja.',
      status: 'approved',
    },
    {
      id: 'voc_a1_wifi_001',
      word: 'wifi',
      translation: 'wifi',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈwaɪˌfaɪ/',
      example: 'What is the wifi password?',
      exampleTranslation: '¿Cuál es la contraseña del wifi?',
      status: 'approved',
    },
    {
      id: 'voc_a1_download_001',
      word: 'download',
      translation: 'descargar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdaʊnˌloʊd/',
      example: 'I downloaded a new app.',
      exampleTranslation: 'Descargué una nueva aplicación.',
      status: 'approved',
    },
    {
      id: 'voc_a1_upload_001',
      word: 'upload',
      translation: 'subir (archivo)',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈʌpˌloʊd/',
      example: 'She uploaded the photos online.',
      exampleTranslation: 'Ella subió las fotos en línea.',
      status: 'approved',
    },
    {
      id: 'voc_a1_click_001',
      word: 'click',
      translation: 'hacer clic',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/klɪk/',
      example: 'Click here to continue.',
      exampleTranslation: 'Haz clic aquí para continuar.',
      status: 'approved',
    },
    {
      id: 'voc_a1_type_001',
      word: 'type (keyboard)',
      translation: 'escribir (teclado)',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/taɪp/',
      example: 'She types very fast.',
      exampleTranslation: 'Ella escribe muy rápido (en el teclado).',
      status: 'approved',
    },
    {
      id: 'voc_a1_search_001',
      word: 'search',
      translation: 'buscar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/sɜrtʃ/',
      example: 'I will search for the answer online.',
      exampleTranslation: 'Buscaré la respuesta en línea.',
      status: 'approved',
    },
    {
      id: 'voc_a1_save_002',
      word: 'save (file)',
      translation: 'guardar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      example: 'Don\'t forget to save your work.',
      pronunciation: '/seɪv/',
      example: 'Don\'t forget to save your work.',
      exampleTranslation: 'No olvides guardar tu trabajo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_delete_001',
      word: 'delete',
      translation: 'borrar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dɪˈlit/',
      example: 'I deleted the old photos.',
      exampleTranslation: 'Borré las fotos viejas.',
      status: 'approved',
    },
    {
      id: 'voc_a1_share_002',
      word: 'share (online)',
      translation: 'compartir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ʃɛr/',
      example: 'She shared the article with me.',
      exampleTranslation: 'Ella compartió el artículo conmigo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_post_001',
      word: 'post (verb)',
      translation: 'publicar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/poʊst/',
      example: 'He posted a photo of his trip.',
      exampleTranslation: 'Él publicó una foto de su viaje.',
      status: 'approved',
    },
    {
      id: 'voc_a1_comment_001',
      word: 'comment',
      translation: 'comentar/comentario',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkɑmɛnt/',
      example: 'Please leave a comment.',
      exampleTranslation: 'Por favor deja un comentario.',
      status: 'approved',
    },
    {
      id: 'voc_a1_like_002',
      word: 'like (social media)',
      translation: 'dar me gusta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      exampleTranslation: 'Le di "me gusta" a tu foto nueva.',
      pronunciation: '/laɪk/',
      example: 'I liked your new photo.',
      exampleTranslation: 'Le di "me gusta" a tu foto nueva.',
      status: 'approved',
    },
    {
      id: 'voc_a1_follow_001',
      word: 'follow (online)',
      translation: 'seguir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfɑloʊ/',
      example: 'I follow her on social media.',
      exampleTranslation: 'La sigo en redes sociales.',
      status: 'approved',
    },
    {
      id: 'voc_a1_network_001',
      word: 'network',
      translation: 'red',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈnɛtˌwɜrk/',
      example: 'Our home network is very fast.',
      exampleTranslation: 'Nuestra red de casa es muy rápida.',
      status: 'approved',
    },
    {
      id: 'voc_a1_file_001',
      word: 'file',
      translation: 'archivo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      example: 'I can\'t open this file.',
      pronunciation: '/faɪl/',
      example: 'I can\'t open this file.',
      exampleTranslation: 'No puedo abrir este archivo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_folder_001',
      word: 'folder',
      translation: 'carpeta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfoʊldər/',
      example: 'Put the photos in this folder.',
      exampleTranslation: 'Pon las fotos en esta carpeta.',
      status: 'approved',
    },
    {
      id: 'voc_a1_document_001',
      word: 'document',
      translation: 'documento',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdɑkjəmənt/',
      example: 'Please send me the document.',
      exampleTranslation: 'Por favor envíame el documento.',
      status: 'approved',
    },
    {
      id: 'voc_a1_software_001',
      word: 'software',
      translation: 'software',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsɔfˌwɛr/',
      example: 'We need to update the software.',
      exampleTranslation: 'Necesitamos actualizar el software.',
      status: 'approved',
    },
    {
      id: 'voc_a1_update_001',
      word: 'update',
      translation: 'actualizar/actualización',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈʌpˌdeɪt/',
      example: 'There is a new update for the app.',
      exampleTranslation: 'Hay una nueva actualización para la aplicación.',
      status: 'approved',
    },
    {
      id: 'voc_a1_install_001',
      word: 'install',
      translation: 'instalar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪnˈstɔl/',
      example: 'I installed a new program.',
      exampleTranslation: 'Instalé un programa nuevo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_soccer-football_001',
      word: 'soccer / football',
      translation: 'fútbol',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsɑkər/',
      example: 'The kids play soccer after school.',
      exampleTranslation: 'Los niños juegan fútbol después de la escuela.',
      status: 'approved',
    },
    {
      id: 'voc_a1_basketball_001',
      word: 'basketball',
      translation: 'baloncesto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbæskɪtˌbɔl/',
      example: 'He plays basketball every weekend.',
      exampleTranslation: 'Él juega baloncesto cada fin de semana.',
      status: 'approved',
    },
    {
      id: 'voc_a1_baseball_001',
      word: 'baseball',
      translation: 'béisbol',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbeɪsˌbɔl/',
      example: 'We watched a baseball game.',
      exampleTranslation: 'Vimos un partido de béisbol.',
      status: 'approved',
    },
    {
      id: 'voc_a1_tennis_001',
      word: 'tennis',
      translation: 'tenis',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtɛnɪs/',
      example: 'She plays tennis very well.',
      exampleTranslation: 'Ella juega tenis muy bien.',
      status: 'approved',
    },
    {
      id: 'voc_a1_volleyball_001',
      word: 'volleyball',
      translation: 'voleibol',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈvɑliˌbɔl/',
      example: 'We played volleyball on the beach.',
      exampleTranslation: 'Jugamos voleibol en la playa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_golf_001',
      word: 'golf',
      translation: 'golf',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/gɔlf/',
      example: 'My father plays golf on Sundays.',
      exampleTranslation: 'Mi padre juega golf los domingos.',
      status: 'approved',
    },
    {
      id: 'voc_a1_swimming_001',
      word: 'swimming',
      translation: 'natación',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈswɪmɪŋ/',
      example: 'Swimming is good exercise.',
      exampleTranslation: 'Nadar es buen ejercicio.',
      status: 'approved',
    },
    {
      id: 'voc_a1_running_001',
      word: 'running',
      translation: 'correr (actividad)',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈrʌnɪŋ/',
      example: 'Running helps me relax.',
      exampleTranslation: 'Correr me ayuda a relajarme.',
      status: 'approved',
    },
    {
      id: 'voc_a1_cycling_001',
      word: 'cycling',
      translation: 'ciclismo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsaɪklɪŋ/',
      example: 'We go cycling on weekends.',
      exampleTranslation: 'Salimos a andar en bicicleta los fines de semana.',
      status: 'approved',
    },
    {
      id: 'voc_a1_hiking_001',
      word: 'hiking',
      translation: 'senderismo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈhaɪkɪŋ/',
      example: 'We went hiking in the mountains.',
      exampleTranslation: 'Fuimos de senderismo a las montañas.',
      status: 'approved',
    },
    {
      id: 'voc_a1_dancing_001',
      word: 'dancing',
      translation: 'baile',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdænsɪŋ/',
      example: 'Dancing makes me happy.',
      exampleTranslation: 'Bailar me hace feliz.',
      status: 'approved',
    },
    {
      id: 'voc_a1_painting_001',
      word: 'painting (hobby)',
      translation: 'pintura (afición)',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpeɪntɪŋ/',
      example: 'She loves painting on weekends.',
      exampleTranslation: 'A ella le encanta pintar los fines de semana.',
      status: 'approved',
    },
    {
      id: 'voc_a1_drawing_001',
      word: 'drawing',
      translation: 'dibujo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdrɔɪŋ/',
      example: 'He is good at drawing.',
      exampleTranslation: 'Él es bueno para dibujar.',
      status: 'approved',
    },
    {
      id: 'voc_a1_photography_001',
      word: 'photography',
      translation: 'fotografía',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fəˈtɑgrəfi/',
      example: 'Photography is his passion.',
      exampleTranslation: 'La fotografía es su pasión.',
      status: 'approved',
    },
    {
      id: 'voc_a1_gardening_001',
      word: 'gardening',
      translation: 'jardinería',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈgɑrdənɪŋ/',
      example: 'My mother enjoys gardening.',
      exampleTranslation: 'A mi madre le gusta la jardinería.',
      status: 'approved',
    },
    {
      id: 'voc_a1_chess_001',
      word: 'chess',
      translation: 'ajedrez',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tʃɛs/',
      example: 'My father taught me to play chess.',
      exampleTranslation: 'Mi padre me enseñó a jugar ajedrez.',
      status: 'approved',
    },
    {
      id: 'voc_a1_cards_001',
      word: 'cards (game)',
      translation: 'cartas',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kɑrdz/',
      example: 'We played cards after dinner.',
      exampleTranslation: 'Jugamos cartas después de la cena.',
      status: 'approved',
    },
    {
      id: 'voc_a1_video-games_001',
      word: 'video games',
      translation: 'videojuegos',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈvɪdioʊ geɪmz/',
      example: 'My brother loves video games.',
      exampleTranslation: 'A mi hermano le encantan los videojuegos.',
      status: 'approved',
    },
    {
      id: 'voc_a1_board-games_001',
      word: 'board games',
      translation: 'juegos de mesa',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bɔrd geɪmz/',
      example: 'We play board games on family night.',
      exampleTranslation: 'Jugamos juegos de mesa en la noche familiar.',
      status: 'approved',
    },
    {
      id: 'voc_a1_fishing_001',
      word: 'fishing',
      translation: 'pesca',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfɪʃɪŋ/',
      example: 'My grandfather goes fishing every summer.',
      exampleTranslation: 'Mi abuelo va de pesca cada verano.',
      status: 'approved',
    },
    {
      id: 'voc_a1_camping_001',
      word: 'camping',
      translation: 'acampar',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkæmpɪŋ/',
      example: 'We went camping near the lake.',
      exampleTranslation: 'Fuimos a acampar cerca del lago.',
      status: 'approved',
    },
    {
      id: 'voc_a1_yoga_001',
      word: 'yoga',
      translation: 'yoga',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈjoʊgə/',
      example: 'She practices yoga every morning.',
      exampleTranslation: 'Ella practica yoga todas las mañanas.',
      status: 'approved',
    },
    {
      id: 'voc_a1_team_001',
      word: 'team',
      translation: 'equipo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tim/',
      example: 'Our team won the game.',
      exampleTranslation: 'Nuestro equipo ganó el partido.',
      status: 'approved',
    },
    {
      id: 'voc_a1_player_001',
      word: 'player',
      translation: 'jugador',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpleɪər/',
      example: 'He is the best player on the team.',
      exampleTranslation: 'Él es el mejor jugador del equipo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_coach_001',
      word: 'coach',
      translation: 'entrenador',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/koʊtʃ/',
      example: 'The coach trains us every week.',
      exampleTranslation: 'El entrenador nos entrena cada semana.',
      status: 'approved',
    },
    {
      id: 'voc_a1_referee_001',
      word: 'referee',
      translation: 'árbitro',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌrɛfəˈri/',
      example: 'The referee stopped the game.',
      exampleTranslation: 'El árbitro detuvo el partido.',
      status: 'approved',
    },
    {
      id: 'voc_a1_match_001',
      word: 'match',
      translation: 'partido',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/mætʃ/',
      example: 'We watched the match on TV.',
      exampleTranslation: 'Vimos el partido en la televisión.',
      status: 'approved',
    },
    {
      id: 'voc_a1_game_001',
      word: 'game',
      translation: 'juego/partido',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/geɪm/',
      example: 'The game starts at eight.',
      exampleTranslation: 'El juego empieza a las ocho.',
      status: 'approved',
    },
    {
      id: 'voc_a1_score_001',
      word: 'score',
      translation: 'puntuación',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/skɔr/',
      example: 'What is the score right now?',
      exampleTranslation: '¿Cuál es la puntuación ahora?',
      status: 'approved',
    },
    {
      id: 'voc_a1_win_001',
      word: 'win',
      translation: 'ganar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/wɪn/',
      example: 'I hope our team wins today.',
      exampleTranslation: 'Espero que nuestro equipo gane hoy.',
      status: 'approved',
    },
    {
      id: 'voc_a1_tie_002',
      word: 'tie (game)',
      translation: 'empate',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/taɪ/',
      example: 'The game ended in a tie.',
      exampleTranslation: 'El partido terminó en empate.',
      status: 'approved',
    },
    {
      id: 'voc_a1_championship_001',
      word: 'championship',
      translation: 'campeonato',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtʃæmpiənˌʃɪp/',
      example: 'They won the championship last year.',
      exampleTranslation: 'Ganaron el campeonato el año pasado.',
      status: 'approved',
    },
    {
      id: 'voc_a1_competition_001',
      word: 'competition',
      translation: 'competencia',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌkɑmpəˈtɪʃən/',
      example: 'She entered the swimming competition.',
      exampleTranslation: 'Ella participó en la competencia de natación.',
      status: 'approved',
    },
    {
      id: 'voc_a1_ball_001',
      word: 'ball',
      translation: 'pelota',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bɔl/',
      example: 'Throw me the ball.',
      exampleTranslation: 'Lánzame la pelota.',
      status: 'approved',
    },
    {
      id: 'voc_a1_goal_001',
      word: 'goal',
      translation: 'gol/meta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/goʊl/',
      example: 'He scored the winning goal.',
      exampleTranslation: 'Él anotó el gol de la victoria.',
      status: 'approved',
    },
    {
      id: 'voc_a1_court_001',
      word: 'court (sports)',
      translation: 'cancha',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kɔrt/',
      example: 'We play tennis on this court.',
      exampleTranslation: 'Jugamos tenis en esta cancha.',
      status: 'approved',
    },
    {
      id: 'voc_a1_stadium_001',
      word: 'stadium',
      translation: 'estadio',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsteɪdiəm/',
      example: 'The stadium was full of fans.',
      exampleTranslation: 'El estadio estaba lleno de aficionados.',
      status: 'approved',
    },
    {
      id: 'voc_a1_song_001',
      word: 'song',
      translation: 'canción',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/sɔŋ/',
      example: 'This is my favorite song.',
      exampleTranslation: 'Esta es mi canción favorita.',
      status: 'approved',
    },
    {
      id: 'voc_a1_instrument_001',
      word: 'instrument (music)',
      translation: 'instrumento musical',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɪnstrəmənt/',
      example: 'Do you play any instrument?',
      exampleTranslation: '¿Tocas algún instrumento?',
      status: 'approved',
    },
    {
      id: 'voc_a1_guitar_001',
      word: 'guitar',
      translation: 'guitarra',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/gɪˈtɑr/',
      example: 'He plays the guitar very well.',
      exampleTranslation: 'Él toca muy bien la guitarra.',
      status: 'approved',
    },
    {
      id: 'voc_a1_piano_001',
      word: 'piano',
      translation: 'piano',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/piˈænoʊ/',
      example: 'She has piano lessons on Tuesdays.',
      exampleTranslation: 'Ella tiene clases de piano los martes.',
      status: 'approved',
    },
    {
      id: 'voc_a1_drum_001',
      word: 'drum',
      translation: 'tambor',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/drʌm/',
      example: 'My son wants to play the drums.',
      exampleTranslation: 'Mi hijo quiere tocar la batería.',
      status: 'approved',
    },
    {
      id: 'voc_a1_violin_001',
      word: 'violin',
      translation: 'violín',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌvaɪəˈlɪn/',
      example: 'She learned to play the violin.',
      exampleTranslation: 'Ella aprendió a tocar el violín.',
      status: 'approved',
    },
    {
      id: 'voc_a1_band_001',
      word: 'band (music)',
      translation: 'banda',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bænd/',
      example: 'My brother is in a band.',
      exampleTranslation: 'Mi hermano está en una banda.',
      status: 'approved',
    },
    {
      id: 'voc_a1_concert_001',
      word: 'concert',
      translation: 'concierto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkɑnsərt/',
      example: 'We are going to a concert tonight.',
      exampleTranslation: 'Vamos a un concierto esta noche.',
      status: 'approved',
    },
    {
      id: 'voc_a1_movie-film_001',
      word: 'movie / film',
      translation: 'película',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmuvi/',
      example: 'We watched a great movie.',
      exampleTranslation: 'Vimos una gran película.',
      status: 'approved',
    },
    {
      id: 'voc_a1_tv-show_001',
      word: 'TV show',
      translation: 'programa de TV',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌtiˈvi ʃoʊ/',
      example: 'This is my favorite TV show.',
      exampleTranslation: 'Este es mi programa de TV favorito.',
      status: 'approved',
    },
    {
      id: 'voc_a1_series_001',
      word: 'series',
      translation: 'serie',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsɪriz/',
      example: 'We watched the whole series in a weekend.',
      exampleTranslation: 'Vimos toda la serie en un fin de semana.',
      status: 'approved',
    },
    {
      id: 'voc_a1_episode_001',
      word: 'episode',
      translation: 'episodio',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɛpəˌsoʊd/',
      example: 'I watched the last episode last night.',
      exampleTranslation: 'Vi el último episodio anoche.',
      status: 'approved',
    },
    {
      id: 'voc_a1_channel_001',
      word: 'channel',
      translation: 'canal',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtʃænəl/',
      example: 'Change the channel, please.',
      exampleTranslation: 'Cambia el canal, por favor.',
      status: 'approved',
    },
    {
      id: 'voc_a1_program_001',
      word: 'program',
      translation: 'programa',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈproʊˌgræm/',
      example: 'This program starts at nine.',
      exampleTranslation: 'Este programa empieza a las nueve.',
      status: 'approved',
    },
    {
      id: 'voc_a1_news_001',
      word: 'news',
      translation: 'noticias',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/nuz/',
      example: 'We watch the news every night.',
      exampleTranslation: 'Vemos las noticias todas las noches.',
      status: 'approved',
    },
    {
      id: 'voc_a1_cartoon_001',
      word: 'cartoon',
      translation: 'dibujos animados',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kɑrˈtun/',
      example: 'The kids love this cartoon.',
      exampleTranslation: 'A los niños les encantan estos dibujos animados.',
      status: 'approved',
    },
    {
      id: 'voc_a1_comedy_001',
      word: 'comedy',
      translation: 'comedia',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkɑmədi/',
      example: 'I love watching comedy movies.',
      exampleTranslation: 'Me encanta ver películas de comedia.',
      status: 'approved',
    },
    {
      id: 'voc_a1_drama_001',
      word: 'drama',
      translation: 'drama',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdrɑmə/',
      example: 'This series is a drama.',
      exampleTranslation: 'Esta serie es un drama.',
      status: 'approved',
    },
    {
      id: 'voc_a1_horror-movie_001',
      word: 'horror movie',
      translation: 'película de terror',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      example: 'She doesn\'t like horror movies.',
      pronunciation: '/ˈhɔrər ˈmuvi/',
      example: 'She doesn\'t like horror movies.',
      exampleTranslation: 'A ella no le gustan las películas de terror.',
      status: 'approved',
    },
    {
      id: 'voc_a1_hobby_001',
      word: 'hobby',
      translation: 'pasatiempo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈhɑbi/',
      example: 'Reading is my favorite hobby.',
      exampleTranslation: 'Leer es mi pasatiempo favorito.',
      status: 'approved',
    },
    {
      id: 'voc_a1_interest_001',
      word: 'interest (hobby)',
      translation: 'interés',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɪntrəst/',
      example: 'Photography is one of his interests.',
      exampleTranslation: 'La fotografía es uno de sus intereses.',
      status: 'approved',
    },
    {
      id: 'voc_a1_free-time_001',
      word: 'free time',
      translation: 'tiempo libre',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fri taɪm/',
      example: 'What do you do in your free time?',
      exampleTranslation: '¿Qué haces en tu tiempo libre?',
      status: 'approved',
    },
    {
      id: 'voc_a1_activity_001',
      word: 'activity',
      translation: 'actividad',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ækˈtɪvəti/',
      example: 'We planned an outdoor activity.',
      exampleTranslation: 'Planeamos una actividad al aire libre.',
      status: 'approved',
    },
    {
      id: 'voc_a1_club_001',
      word: 'club',
      translation: 'club',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/klʌb/',
      example: 'She joined a book club.',
      exampleTranslation: 'Ella se unió a un club de lectura.',
      status: 'approved',
    },
    {
      id: 'voc_a1_member_001',
      word: 'member',
      translation: 'miembro',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmɛmbər/',
      example: 'I am a member of the gym.',
      exampleTranslation: 'Soy miembro del gimnasio.',
      status: 'approved',
    },
    {
      id: 'voc_a1_event_001',
      word: 'event',
      translation: 'evento',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪˈvɛnt/',
      example: 'The event starts at seven.',
      exampleTranslation: 'El evento empieza a las siete.',
      status: 'approved',
    },
    {
      id: 'voc_a1_party_001',
      word: 'party',
      translation: 'fiesta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpɑrti/',
      example: 'We had a great party last night.',
      exampleTranslation: 'Tuvimos una gran fiesta anoche.',
      status: 'approved',
    },
    {
      id: 'voc_a1_festival_001',
      word: 'festival',
      translation: 'festival',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfɛstəvəl/',
      example: 'We went to a music festival.',
      exampleTranslation: 'Fuimos a un festival de música.',
      status: 'approved',
    },
  ],
}
