import type { ContentBlock } from '../types'

/**
 * A1 Level — Week 9
 * Topic: Semana 9 – Clima y lugares de la ciudad
 * Curated from: a.md
 * Total items: 69
 */
export const week09: ContentBlock = {
  level: 'A1',
  week: 9,
  topic: 'Semana 9 – Clima y lugares de la ciudad',
  vocabulary: [
    {
      id: 'voc_a1_sun_001',
      word: 'sun',
      translation: 'sol',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/sʌn/',
      example: 'The sun is very bright today.',
      exampleTranslation: 'El sol está muy brillante hoy.',
      status: 'approved',
    },
    {
      id: 'voc_a1_sunny_001',
      word: 'sunny',
      translation: 'soleado',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsʌni/',
      example: 'It is sunny this afternoon.',
      exampleTranslation: 'Está soleado esta tarde.',
      status: 'approved',
    },
    {
      id: 'voc_a1_rain_001',
      word: 'rain',
      translation: 'lluvia',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/reɪn/',
      example: 'I love the sound of rain.',
      exampleTranslation: 'Me encanta el sonido de la lluvia.',
      status: 'approved',
    },
    {
      id: 'voc_a1_rainy_001',
      word: 'rainy',
      translation: 'lluvioso',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈreɪni/',
      example: 'It is a rainy day.',
      exampleTranslation: 'Es un día lluvioso.',
      status: 'approved',
    },
    {
      id: 'voc_a1_cloud_001',
      word: 'cloud',
      translation: 'nube',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/klaʊd/',
      example: 'There is a big cloud in the sky.',
      exampleTranslation: 'Hay una nube grande en el cielo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_cloudy_001',
      word: 'cloudy',
      translation: 'nublado',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈklaʊdi/',
      example: 'It is cloudy this morning.',
      exampleTranslation: 'Está nublado esta mañana.',
      status: 'approved',
    },
    {
      id: 'voc_a1_wind_001',
      word: 'wind',
      translation: 'viento',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/wɪnd/',
      example: 'The wind is very strong today.',
      exampleTranslation: 'El viento está muy fuerte hoy.',
      status: 'approved',
    },
    {
      id: 'voc_a1_windy_001',
      word: 'windy',
      translation: 'ventoso',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈwɪndi/',
      example: 'It is windy near the beach.',
      exampleTranslation: 'Hace viento cerca de la playa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_snow_001',
      word: 'snow',
      translation: 'nieve',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/snoʊ/',
      example: 'The snow covers the mountains.',
      exampleTranslation: 'La nieve cubre las montañas.',
      status: 'approved',
    },
    {
      id: 'voc_a1_snowy_001',
      word: 'snowy',
      translation: 'nevado',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsnoʊi/',
      example: 'It was a snowy winter.',
      exampleTranslation: 'Fue un invierno nevado.',
      status: 'approved',
    },
    {
      id: 'voc_a1_storm_001',
      word: 'storm',
      translation: 'tormenta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/stɔrm/',
      example: 'A storm is coming tonight.',
      exampleTranslation: 'Una tormenta se acerca esta noche.',
      status: 'approved',
    },
    {
      id: 'voc_a1_fog_001',
      word: 'fog',
      translation: 'niebla',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fɔg/',
      example: 'There is a lot of fog this morning.',
      exampleTranslation: 'Hay mucha niebla esta mañana.',
      status: 'approved',
    },
    {
      id: 'voc_a1_temperature_001',
      word: 'temperature',
      translation: 'temperatura',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtɛmpərətʃər/',
      example: 'The temperature is very high today.',
      exampleTranslation: 'La temperatura está muy alta hoy.',
      status: 'approved',
    },
    {
      id: 'voc_a1_degree_001',
      word: 'degree',
      translation: 'grado',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dɪˈgri/',
      example: 'It is thirty degrees outside.',
      exampleTranslation: 'Hace treinta grados afuera.',
      status: 'approved',
    },
    {
      id: 'voc_a1_weather-forecast_001',
      word: 'weather forecast',
      translation: 'pronóstico del tiempo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈwɛðər ˈfɔrˌkæst/',
      example: 'The weather forecast says it will rain.',
      exampleTranslation: 'El pronóstico del tiempo dice que lloverá.',
      status: 'approved',
    },
    {
      id: 'voc_a1_weather_001',
      word: 'weather',
      translation: 'clima',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈwɛðər/',
      example: 'How is the weather today?',
      exampleTranslation: '¿Cómo está el clima hoy?',
      status: 'approved',
    },
    {
      id: 'voc_a1_city_001',
      word: 'city',
      translation: 'ciudad',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsɪti/',
      example: 'I live in a big city.',
      exampleTranslation: 'Vivo en una ciudad grande.',
      status: 'approved',
    },
    {
      id: 'voc_a1_town_001',
      word: 'town',
      translation: 'pueblo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/taʊn/',
      example: 'My grandparents live in a small town.',
      exampleTranslation: 'Mis abuelos viven en un pueblo pequeño.',
      status: 'approved',
    },
    {
      id: 'voc_a1_village_001',
      word: 'village',
      translation: 'aldea',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈvɪlɪdʒ/',
      example: 'They live in a quiet village.',
      exampleTranslation: 'Ellos viven en una aldea tranquila.',
      status: 'approved',
    },
    {
      id: 'voc_a1_street_001',
      word: 'street',
      translation: 'calle',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/strit/',
      example: 'My house is on this street.',
      exampleTranslation: 'Mi casa está en esta calle.',
      status: 'approved',
    },
    {
      id: 'voc_a1_road_001',
      word: 'road',
      translation: 'carretera',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/roʊd/',
      example: 'The road to the beach is long.',
      exampleTranslation: 'El camino a la playa es largo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_avenue_001',
      word: 'avenue',
      translation: 'avenida',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈævəˌnu/',
      example: 'The store is on Fifth Avenue.',
      exampleTranslation: 'La tienda está en la Quinta Avenida.',
      status: 'approved',
    },
    {
      id: 'voc_a1_park_001',
      word: 'park',
      translation: 'parque',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pɑrk/',
      example: 'We walk in the park every evening.',
      exampleTranslation: 'Caminamos en el parque cada tarde.',
      status: 'approved',
    },
    {
      id: 'voc_a1_square_002',
      word: 'square (place)',
      translation: 'plaza',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/skwɛr/',
      example: 'People meet in the town square.',
      exampleTranslation: 'La gente se reúne en la plaza del pueblo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_bridge_001',
      word: 'bridge',
      translation: 'puente',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/brɪdʒ/',
      example: 'We crossed the bridge on foot.',
      exampleTranslation: 'Cruzamos el puente a pie.',
      status: 'approved',
    },
    {
      id: 'voc_a1_building_001',
      word: 'building',
      translation: 'edificio',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbɪldɪŋ/',
      example: 'That building is very tall.',
      exampleTranslation: 'Ese edificio es muy alto.',
      status: 'approved',
    },
    {
      id: 'voc_a1_church_001',
      word: 'church',
      translation: 'iglesia',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tʃɜrtʃ/',
      example: 'We go to church on Sundays.',
      exampleTranslation: 'Vamos a la iglesia los domingos.',
      status: 'approved',
    },
    {
      id: 'voc_a1_school_001',
      word: 'school',
      translation: 'escuela',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/skul/',
      example: 'The school is near my house.',
      exampleTranslation: 'La escuela está cerca de mi casa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_hospital_001',
      word: 'hospital',
      translation: 'hospital',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈhɑˌspɪtəl/',
      example: 'My mother works at the hospital.',
      exampleTranslation: 'Mi madre trabaja en el hospital.',
      status: 'approved',
    },
    {
      id: 'voc_a1_bank_001',
      word: 'bank',
      translation: 'banco',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bæŋk/',
      example: 'I need to go to the bank.',
      exampleTranslation: 'Necesito ir al banco.',
      status: 'approved',
    },
    {
      id: 'voc_a1_supermarket_001',
      word: 'supermarket',
      translation: 'supermercado',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsupərˌmɑrkɪt/',
      example: 'We buy food at the supermarket.',
      exampleTranslation: 'Compramos comida en el supermercado.',
      status: 'approved',
    },
    {
      id: 'voc_a1_market_001',
      word: 'market',
      translation: 'mercado',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmɑrkɪt/',
      example: 'The fruit at the market is fresh.',
      exampleTranslation: 'La fruta en el mercado está fresca.',
      status: 'approved',
    },
    {
      id: 'voc_a1_store-shop_001',
      word: 'store / shop',
      translation: 'tienda',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/stɔr/',
      example: 'The store closes at nine.',
      exampleTranslation: 'La tienda cierra a las nueve.',
      status: 'approved',
    },
    {
      id: 'voc_a1_mall_001',
      word: 'mall',
      translation: 'centro comercial',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/mɔl/',
      example: 'We went shopping at the mall.',
      exampleTranslation: 'Fuimos de compras al centro comercial.',
      status: 'approved',
    },
    {
      id: 'voc_a1_museum_001',
      word: 'museum',
      translation: 'museo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/mjuˈziəm/',
      example: 'We visited the art museum.',
      exampleTranslation: 'Visitamos el museo de arte.',
      status: 'approved',
    },
    {
      id: 'voc_a1_library_001',
      word: 'library',
      translation: 'biblioteca',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈlaɪbrɛri/',
      example: 'I study at the library.',
      exampleTranslation: 'Estudio en la biblioteca.',
      status: 'approved',
    },
    {
      id: 'voc_a1_cinema-movie-theater_001',
      word: 'cinema / movie theater',
      translation: 'cine',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsɪnəmə/',
      example: 'We went to the cinema last night.',
      exampleTranslation: 'Fuimos al cine anoche.',
      status: 'approved',
    },
    {
      id: 'voc_a1_theater_001',
      word: 'theater',
      translation: 'teatro',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈθiətər/',
      example: 'The play is at the theater tonight.',
      exampleTranslation: 'La obra es en el teatro esta noche.',
      status: 'approved',
    },
    {
      id: 'voc_a1_hotel_001',
      word: 'hotel',
      translation: 'hotel',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/hoʊˈtɛl/',
      example: 'We stayed at a nice hotel.',
      exampleTranslation: 'Nos quedamos en un buen hotel.',
      status: 'approved',
    },
    {
      id: 'voc_a1_airport_001',
      word: 'airport',
      translation: 'aeropuerto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɛrˌpɔrt/',
      example: 'I will pick you up at the airport.',
      exampleTranslation: 'Te recogeré en el aeropuerto.',
      status: 'approved',
    },
    {
      id: 'voc_a1_station_001',
      word: 'station',
      translation: 'estación',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsteɪʃən/',
      example: 'The train station is very busy.',
      exampleTranslation: 'La estación de tren está muy concurrida.',
      status: 'approved',
    },
    {
      id: 'voc_a1_bus-stop_001',
      word: 'bus stop',
      translation: 'parada de bus',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bʌs stɑp/',
      example: 'I wait for the bus at this bus stop.',
      exampleTranslation: 'Espero el autobús en esta parada.',
      status: 'approved',
    },
    {
      id: 'voc_a1_caf_001',
      word: 'café',
      translation: 'cafetería',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kæˈfeɪ/',
      example: 'Let\'s meet at the café.',
      exampleTranslation: 'Reunámonos en la cafetería.',
      status: 'approved',
    },
    {
      id: 'voc_a1_gym_001',
      word: 'gym',
      translation: 'gimnasio',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dʒɪm/',
      example: 'I go to the gym every morning.',
      exampleTranslation: 'Voy al gimnasio todas las mañanas.',
      status: 'approved',
    },
    {
      id: 'voc_a1_pool_001',
      word: 'pool',
      translation: 'piscina',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pul/',
      example: 'The kids are swimming in the pool.',
      exampleTranslation: 'Los niños están nadando en la piscina.',
      status: 'approved',
    },
    {
      id: 'voc_a1_beach_001',
      word: 'beach',
      translation: 'playa',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bitʃ/',
      example: 'We spent the day at the beach.',
      exampleTranslation: 'Pasamos el día en la playa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_mountain_001',
      word: 'mountain',
      translation: 'montaña',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmaʊntən/',
      example: 'We climbed the mountain last summer.',
      exampleTranslation: 'Subimos la montaña el verano pasado.',
      status: 'approved',
    },
    {
      id: 'voc_a1_river_001',
      word: 'river',
      translation: 'río',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈrɪvər/',
      example: 'The river runs through the city.',
      exampleTranslation: 'El río atraviesa la ciudad.',
      status: 'approved',
    },
    {
      id: 'voc_a1_lake_001',
      word: 'lake',
      translation: 'lago',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/leɪk/',
      example: 'We swim in the lake in summer.',
      exampleTranslation: 'Nadamos en el lago en verano.',
      status: 'approved',
    },
    {
      id: 'voc_a1_sea_001',
      word: 'sea',
      translation: 'mar',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/si/',
      example: 'The sea is very calm today.',
      exampleTranslation: 'El mar está muy calmado hoy.',
      status: 'approved',
    },
    {
      id: 'voc_a1_ocean_001',
      word: 'ocean',
      translation: 'océano',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈoʊʃən/',
      example: 'The ocean is huge.',
      exampleTranslation: 'El océano es enorme.',
      status: 'approved',
    },
    {
      id: 'voc_a1_forest_001',
      word: 'forest',
      translation: 'bosque',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfɔrɪst/',
      example: 'We walked through the forest.',
      exampleTranslation: 'Caminamos por el bosque.',
      status: 'approved',
    },
    {
      id: 'voc_a1_farm_001',
      word: 'farm',
      translation: 'granja',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fɑrm/',
      example: 'My uncle has a small farm.',
      exampleTranslation: 'Mi tío tiene una pequeña granja.',
      status: 'approved',
    },
    {
      id: 'voc_a1_left_001',
      word: 'left',
      translation: 'izquierda',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/lɛft/',
      example: 'Turn left at the corner.',
      exampleTranslation: 'Gira a la izquierda en la esquina.',
      status: 'approved',
    },
    {
      id: 'voc_a1_right_002',
      word: 'right (direction)',
      translation: 'derecha',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/raɪt/',
      example: 'The bank is on the right.',
      exampleTranslation: 'El banco está a la derecha.',
      status: 'approved',
    },
    {
      id: 'voc_a1_near_001',
      word: 'near',
      translation: 'cerca',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/nɪr/',
      example: 'The school is near my house.',
      exampleTranslation: 'La escuela está cerca de mi casa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_far_001',
      word: 'far',
      translation: 'lejos',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fɑr/',
      example: 'The airport is far from here.',
      exampleTranslation: 'El aeropuerto está lejos de aquí.',
      status: 'approved',
    },
    {
      id: 'voc_a1_next-to_001',
      word: 'next to',
      translation: 'al lado de',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/nɛkst tu/',
      example: 'The bank is next to the store.',
      exampleTranslation: 'El banco está al lado de la tienda.',
      status: 'approved',
    },
    {
      id: 'voc_a1_in-front-of_001',
      word: 'in front of',
      translation: 'enfrente de',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪn frʌnt ʌv/',
      example: 'She is standing in front of the door.',
      exampleTranslation: 'Ella está parada enfrente de la puerta.',
      status: 'approved',
    },
    {
      id: 'voc_a1_behind_001',
      word: 'behind',
      translation: 'detrás de',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bɪˈhaɪnd/',
      example: 'The park is behind the school.',
      exampleTranslation: 'El parque está detrás de la escuela.',
      status: 'approved',
    },
    {
      id: 'voc_a1_between_001',
      word: 'between',
      translation: 'entre',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bɪˈtwin/',
      example: 'The bank is between the store and the café.',
      exampleTranslation: 'El banco está entre la tienda y la cafetería.',
      status: 'approved',
    },
    {
      id: 'voc_a1_corner_001',
      word: 'corner',
      translation: 'esquina',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkɔrnər/',
      example: 'The café is on the corner.',
      exampleTranslation: 'La cafetería está en la esquina.',
      status: 'approved',
    },
    {
      id: 'voc_a1_map_001',
      word: 'map',
      translation: 'mapa',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/mæp/',
      example: 'Can you show me on the map?',
      exampleTranslation: '¿Puedes mostrarme en el mapa?',
      status: 'approved',
    },
    {
      id: 'voc_a1_address_002',
      word: 'address (place)',
      translation: 'dirección',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈdrɛs/',
      example: 'I don\'t know this address.',
      exampleTranslation: 'No conozco esta dirección.',
      status: 'approved',
    },
    {
      id: 'voc_a1_downtown_001',
      word: 'downtown',
      translation: 'centro (de la ciudad)',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdaʊnˌtaʊn/',
      example: 'We work downtown.',
      exampleTranslation: 'Trabajamos en el centro.',
      status: 'approved',
    },
    {
      id: 'voc_a1_suburb_001',
      word: 'suburb',
      translation: 'suburbio',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsʌbɜrb/',
      example: 'They live in a quiet suburb.',
      exampleTranslation: 'Ellos viven en un suburbio tranquilo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_traffic-light_001',
      word: 'traffic light',
      translation: 'semáforo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtræfɪk laɪt/',
      example: 'Stop at the traffic light.',
      exampleTranslation: 'Detente en el semáforo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_sidewalk_001',
      word: 'sidewalk',
      translation: 'acera',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsaɪdˌwɔk/',
      example: 'Walk on the sidewalk, not the street.',
      exampleTranslation: 'Camina por la acera, no por la calle.',
      status: 'approved',
    },
    {
      id: 'voc_a1_crosswalk_001',
      word: 'crosswalk',
      translation: 'cruce peatonal',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkrɔsˌwɔk/',
      example: 'Cross the street at the crosswalk.',
      exampleTranslation: 'Cruza la calle por el cruce peatonal.',
      status: 'approved',
    },
  ],
}
