import type { ContentBlock } from '../types'

/**
 * A1 Level — Week 17
 * Topic: Semana 17 – Herramientas, cantidades, dinero y salud
 * Curated from: a.md
 * Total items: 109
 */
export const week17: ContentBlock = {
  level: 'A1',
  week: 17,
  topic: 'Semana 17 – Herramientas, cantidades, dinero y salud',
  vocabulary: [
    {
      id: 'voc_a1_tool_001',
      word: 'tool',
      translation: 'herramienta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_hammer_001',
      word: 'hammer',
      translation: 'martillo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_nail_002',
      word: 'nail (tool)',
      translation: 'clavo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_screwdriver_001',
      word: 'screwdriver',
      translation: 'destornillador',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_screw_001',
      word: 'screw',
      translation: 'tornillo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_saw_001',
      word: 'saw',
      translation: 'sierra',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_drill_001',
      word: 'drill',
      translation: 'taladro',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_ladder_001',
      word: 'ladder',
      translation: 'escalera (de mano)',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_rope_001',
      word: 'rope',
      translation: 'cuerda',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_tape_001',
      word: 'tape',
      translation: 'cinta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_glue_001',
      word: 'glue',
      translation: 'pegamento',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_scissors_001',
      word: 'scissors',
      translation: 'tijeras',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_needle_001',
      word: 'needle',
      translation: 'aguja',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_thread_001',
      word: 'thread',
      translation: 'hilo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_machine_001',
      word: 'machine',
      translation: 'máquina',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_engine_001',
      word: 'engine',
      translation: 'motor',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_wire_001',
      word: 'wire',
      translation: 'cable/alambre',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_pipe_001',
      word: 'pipe',
      translation: 'tubería',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_brick_001',
      word: 'brick',
      translation: 'ladrillo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_wood_001',
      word: 'wood',
      translation: 'madera',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_metal_001',
      word: 'metal',
      translation: 'metal',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_plastic_001',
      word: 'plastic',
      translation: 'plástico',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_glass_002',
      word: 'glass (material)',
      translation: 'vidrio',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_paper_001',
      word: 'paper',
      translation: 'papel',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_cardboard_001',
      word: 'cardboard',
      translation: 'cartón',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_rubber_001',
      word: 'rubber',
      translation: 'goma',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_material_001',
      word: 'material',
      translation: 'material',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_quantity-amount_001',
      word: 'quantity / amount',
      translation: 'cantidad',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_number_001',
      word: 'number',
      translation: 'número',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_pair_001',
      word: 'pair',
      translation: 'par',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_dozen_001',
      word: 'dozen',
      translation: 'docena',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_piece_001',
      word: 'piece',
      translation: 'pedazo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_part_001',
      word: 'part',
      translation: 'parte',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_whole_001',
      word: 'whole',
      translation: 'entero',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_percent_001',
      word: 'percent',
      translation: 'porcentaje',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_price_001',
      word: 'price',
      translation: 'precio',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_cost_001',
      word: 'cost',
      translation: 'costo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_discount_001',
      word: 'discount',
      translation: 'descuento',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_sale_001',
      word: 'sale',
      translation: 'oferta/venta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_receipt_001',
      word: 'receipt',
      translation: 'recibo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_cash_001',
      word: 'cash',
      translation: 'efectivo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_credit-card_001',
      word: 'credit card',
      translation: 'tarjeta de crédito',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_money_001',
      word: 'money',
      translation: 'dinero',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_coin_001',
      word: 'coin',
      translation: 'moneda',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_bill_002',
      word: 'bill (money)',
      translation: 'billete',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_change_001',
      word: 'change (money)',
      translation: 'cambio (dinero)',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_wallet_001',
      word: 'wallet',
      translation: 'billetera',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_purse_001',
      word: 'purse',
      translation: 'bolso',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_budget_001',
      word: 'budget',
      translation: 'presupuesto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_debt_001',
      word: 'debt',
      translation: 'deuda',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_loan_001',
      word: 'loan',
      translation: 'préstamo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_bank-account_001',
      word: 'bank account',
      translation: 'cuenta bancaria',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_tax_001',
      word: 'tax',
      translation: 'impuesto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_insurance_001',
      word: 'insurance',
      translation: 'seguro',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_contract_001',
      word: 'contract',
      translation: 'contrato',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_business_001',
      word: 'business',
      translation: 'negocio',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_customer_001',
      word: 'customer',
      translation: 'cliente',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_seller_001',
      word: 'seller',
      translation: 'vendedor',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_buyer_001',
      word: 'buyer',
      translation: 'comprador',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_product_001',
      word: 'product',
      translation: 'producto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_service_001',
      word: 'service',
      translation: 'servicio',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_quality_001',
      word: 'quality',
      translation: 'calidad',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_brand_001',
      word: 'brand',
      translation: 'marca',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_weight_001',
      word: 'weight',
      translation: 'peso',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_measure_001',
      word: 'measure',
      translation: 'medir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_length_001',
      word: 'length',
      translation: 'longitud',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_width_001',
      word: 'width',
      translation: 'ancho',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_height_001',
      word: 'height',
      translation: 'altura',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_depth_001',
      word: 'depth',
      translation: 'profundidad',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_volume_001',
      word: 'volume',
      translation: 'volumen',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_distance_001',
      word: 'distance',
      translation: 'distancia',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_speed_001',
      word: 'speed',
      translation: 'velocidad',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_direction_001',
      word: 'direction',
      translation: 'dirección (rumbo)',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_north_001',
      word: 'north',
      translation: 'norte',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_south_001',
      word: 'south',
      translation: 'sur',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_east_001',
      word: 'east',
      translation: 'este',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_west_001',
      word: 'west',
      translation: 'oeste',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_medicine_001',
      word: 'medicine',
      translation: 'medicina',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_pill_001',
      word: 'pill',
      translation: 'pastilla',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_pharmacy_001',
      word: 'pharmacy',
      translation: 'farmacia',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_appointment_001',
      word: 'appointment',
      translation: 'cita',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_injury_001',
      word: 'injury',
      translation: 'lesión',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_pain_001',
      word: 'pain',
      translation: 'dolor',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_headache_001',
      word: 'headache',
      translation: 'dolor de cabeza',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_fever_001',
      word: 'fever',
      translation: 'fiebre',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_cough_001',
      word: 'cough',
      translation: 'tos',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_cold_002',
      word: 'cold (illness)',
      translation: 'resfriado',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_flu_001',
      word: 'flu',
      translation: 'gripe',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_ambulance_001',
      word: 'ambulance',
      translation: 'ambulancia',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_emergency_001',
      word: 'emergency',
      translation: 'emergencia',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_accident_001',
      word: 'accident',
      translation: 'accidente',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_patient_002',
      word: 'patient (person)',
      translation: 'paciente',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_treatment_001',
      word: 'treatment',
      translation: 'tratamiento',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_vaccine_001',
      word: 'vaccine',
      translation: 'vacuna',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_health_001',
      word: 'health',
      translation: 'salud',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_diet_001',
      word: 'diet',
      translation: 'dieta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_humidity_001',
      word: 'humidity',
      translation: 'humedad',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_climate_001',
      word: 'climate',
      translation: 'clima (general)',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_thunder_001',
      word: 'thunder',
      translation: 'trueno',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_lightning_001',
      word: 'lightning',
      translation: 'relámpago',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_earthquake_001',
      word: 'earthquake',
      translation: 'terremoto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_flood_001',
      word: 'flood',
      translation: 'inundación',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_pollution_001',
      word: 'pollution',
      translation: 'contaminación',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_recycle_001',
      word: 'recycle',
      translation: 'reciclar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_environment_001',
      word: 'environment',
      translation: 'medio ambiente',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_energy_001',
      word: 'energy',
      translation: 'energía',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_electricity_001',
      word: 'electricity',
      translation: 'electricidad',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_fuel_001',
      word: 'fuel',
      translation: 'combustible',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_solar_001',
      word: 'solar',
      translation: 'solar',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 17,
      topic: 'herramientas-cantidades-dinero-y-salud',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
  ],
}
