import type { ContentBlock } from '../types'

/**
 * A1 Level — Week 1
 * Topic: Semana 1 – Pronombres, verbos SER/ESTAR/TENER/HACER y saludos
 * Curated from: a.md
 * Total items: 96
 */
export const week01: ContentBlock = {
  level: 'A1',
  week: 1,
  topic: 'Semana 1 – Pronombres, verbos SER/ESTAR/TENER/HACER y saludos',
  vocabulary: [
    {
      id: 'voc_a1_i_001',
      word: 'I',
      translation: 'yo',
      partOfSpeech: 'pronoun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_you_001',
      word: 'you',
      translation: 'tú / usted',
      partOfSpeech: 'pronoun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_he_001',
      word: 'he',
      translation: 'él',
      partOfSpeech: 'pronoun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_she_001',
      word: 'she',
      translation: 'ella',
      partOfSpeech: 'pronoun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_it_001',
      word: 'it',
      translation: 'eso / ello',
      partOfSpeech: 'pronoun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_we_001',
      word: 'we',
      translation: 'nosotros',
      partOfSpeech: 'pronoun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_they_001',
      word: 'they',
      translation: 'ellos',
      partOfSpeech: 'pronoun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_my_001',
      word: 'my',
      translation: 'mi',
      partOfSpeech: 'determiner',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_your_001',
      word: 'your',
      translation: 'tu',
      partOfSpeech: 'determiner',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_his_001',
      word: 'his',
      translation: 'su (de él)',
      partOfSpeech: 'pronoun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_her_001',
      word: 'her',
      translation: 'su (de ella)',
      partOfSpeech: 'determiner',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_its_001',
      word: 'its',
      translation: 'su (de eso)',
      partOfSpeech: 'determiner',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_our_001',
      word: 'our',
      translation: 'nuestro',
      partOfSpeech: 'determiner',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_their_001',
      word: 'their',
      translation: 'su (de ellos)',
      partOfSpeech: 'determiner',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_mine_001',
      word: 'mine',
      translation: 'mío',
      partOfSpeech: 'pronoun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_this_001',
      word: 'this',
      translation: 'este/esto',
      partOfSpeech: 'pronoun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_that_001',
      word: 'that',
      translation: 'ese/eso',
      partOfSpeech: 'pronoun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_these_001',
      word: 'these',
      translation: 'estos',
      partOfSpeech: 'pronoun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_those_001',
      word: 'those',
      translation: 'esos',
      partOfSpeech: 'pronoun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_am_001',
      word: 'am',
      translation: 'soy/estoy',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_is_001',
      word: 'is',
      translation: 'es/está',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_are_001',
      word: 'are',
      translation: 'son/están',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_was_001',
      word: 'was',
      translation: 'era/estaba',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_were_001',
      word: 'were',
      translation: 'eran/estaban',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_be_001',
      word: 'be',
      translation: 'ser/estar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_been_001',
      word: 'been',
      translation: 'sido/estado',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_being_001',
      word: 'being',
      translation: 'siendo',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_have_001',
      word: 'have',
      translation: 'tener',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_has_001',
      word: 'has',
      translation: 'tiene',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_had_001',
      word: 'had',
      translation: 'tenía/tuvo',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_having_001',
      word: 'having',
      translation: 'teniendo',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_do_001',
      word: 'do',
      translation: 'hacer',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_does_001',
      word: 'does',
      translation: 'hace',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_did_001',
      word: 'did',
      translation: 'hizo',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_doing_001',
      word: 'doing',
      translation: 'haciendo',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_done_001',
      word: 'done',
      translation: 'hecho',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_hello_001',
      word: 'hello',
      translation: 'hola',
      partOfSpeech: 'interjection',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_hi_001',
      word: 'hi',
      translation: 'hola',
      partOfSpeech: 'interjection',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_goodbye_001',
      word: 'goodbye',
      translation: 'adiós',
      partOfSpeech: 'interjection',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_bye_001',
      word: 'bye',
      translation: 'chao',
      partOfSpeech: 'interjection',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_good-morning_001',
      word: 'good morning',
      translation: 'buenos días',
      partOfSpeech: 'interjection',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_good-afternoon_001',
      word: 'good afternoon',
      translation: 'buenas tardes',
      partOfSpeech: 'interjection',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_good-evening_001',
      word: 'good evening',
      translation: 'buenas noches (saludo)',
      partOfSpeech: 'interjection',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_good-night_001',
      word: 'good night',
      translation: 'buenas noches (despedida)',
      partOfSpeech: 'interjection',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_please_001',
      word: 'please',
      translation: 'por favor',
      partOfSpeech: 'interjection',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_thank-you_001',
      word: 'thank you',
      translation: 'gracias',
      partOfSpeech: 'interjection',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_thanks_001',
      word: 'thanks',
      translation: 'gracias',
      partOfSpeech: 'interjection',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_sorry_001',
      word: 'sorry',
      translation: 'perdón',
      partOfSpeech: 'interjection',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_excuse-me_001',
      word: 'excuse me',
      translation: 'disculpe',
      partOfSpeech: 'interjection',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_yes_001',
      word: 'yes',
      translation: 'sí',
      partOfSpeech: 'interjection',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_no_001',
      word: 'no',
      translation: 'no',
      partOfSpeech: 'interjection',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_ok_001',
      word: 'ok',
      translation: 'de acuerdo',
      partOfSpeech: 'interjection',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_welcome_001',
      word: 'welcome',
      translation: 'bienvenido',
      partOfSpeech: 'interjection',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_nice-to-meet-you_001',
      word: 'nice to meet you',
      translation: 'mucho gusto',
      partOfSpeech: 'interjection',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_how-are-you_001',
      word: 'how are you',
      translation: '¿cómo estás?',
      partOfSpeech: 'interjection',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_fine_001',
      word: 'fine',
      translation: 'bien',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_one_001',
      word: 'one',
      translation: 'uno',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_two_001',
      word: 'two',
      translation: 'dos',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_three_001',
      word: 'three',
      translation: 'tres',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_four_001',
      word: 'four',
      translation: 'cuatro',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_five_001',
      word: 'five',
      translation: 'cinco',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_six_001',
      word: 'six',
      translation: 'seis',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_seven_001',
      word: 'seven',
      translation: 'siete',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_eight_001',
      word: 'eight',
      translation: 'ocho',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_nine_001',
      word: 'nine',
      translation: 'nueve',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_ten_001',
      word: 'ten',
      translation: 'diez',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_eleven_001',
      word: 'eleven',
      translation: 'once',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_twelve_001',
      word: 'twelve',
      translation: 'doce',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_thirteen_001',
      word: 'thirteen',
      translation: 'trece',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_fourteen_001',
      word: 'fourteen',
      translation: 'catorce',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_fifteen_001',
      word: 'fifteen',
      translation: 'quince',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_sixteen_001',
      word: 'sixteen',
      translation: 'dieciséis',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_seventeen_001',
      word: 'seventeen',
      translation: 'diecisiete',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_eighteen_001',
      word: 'eighteen',
      translation: 'dieciocho',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_nineteen_001',
      word: 'nineteen',
      translation: 'diecinueve',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_twenty_001',
      word: 'twenty',
      translation: 'veinte',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_what_001',
      word: 'what',
      translation: 'qué',
      partOfSpeech: 'pronoun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_who_001',
      word: 'who',
      translation: 'quién',
      partOfSpeech: 'pronoun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_where_001',
      word: 'where',
      translation: 'dónde',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_when_001',
      word: 'when',
      translation: 'cuándo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_why_001',
      word: 'why',
      translation: 'por qué',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_how_001',
      word: 'how',
      translation: 'cómo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_which_001',
      word: 'which',
      translation: 'cuál',
      partOfSpeech: 'pronoun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_name_001',
      word: 'name',
      translation: 'nombre',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_age_001',
      word: 'age',
      translation: 'edad',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_and_001',
      word: 'and',
      translation: 'y',
      partOfSpeech: 'conjunction',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_or_001',
      word: 'or',
      translation: 'o',
      partOfSpeech: 'conjunction',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_but_001',
      word: 'but',
      translation: 'pero',
      partOfSpeech: 'conjunction',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_a_001',
      word: 'a',
      translation: 'un/una',
      partOfSpeech: 'article',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_an_001',
      word: 'an',
      translation: 'un/una (ante vocal)',
      partOfSpeech: 'article',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_the_001',
      word: 'the',
      translation: 'el/la',
      partOfSpeech: 'article',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_not_001',
      word: 'not',
      translation: 'no',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_very_001',
      word: 'very',
      translation: 'muy',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_too_001',
      word: 'too',
      translation: 'también',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_here_001',
      word: 'here',
      translation: 'aquí',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_there_001',
      word: 'there',
      translation: 'allí',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
  ],
}
