import type { ContentBlock } from '../types'

/**
 * A1 Level — Week 4
 * Topic: Semana 4 – Colores, formas y adjetivos básicos
 * Curated from: a.md
 * Total items: 89
 */
export const week04: ContentBlock = {
  level: 'A1',
  week: 4,
  topic: 'Semana 4 – Colores, formas y adjetivos básicos',
  vocabulary: [
    {
      id: 'voc_a1_red_001',
      word: 'red',
      translation: 'rojo',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_blue_001',
      word: 'blue',
      translation: 'azul',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_green_001',
      word: 'green',
      translation: 'verde',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_yellow_001',
      word: 'yellow',
      translation: 'amarillo',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_orange_001',
      word: 'orange (color)',
      translation: 'naranja',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_purple_001',
      word: 'purple',
      translation: 'morado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_pink_001',
      word: 'pink',
      translation: 'rosado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_black_001',
      word: 'black',
      translation: 'negro',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_white_001',
      word: 'white',
      translation: 'blanco',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_brown_001',
      word: 'brown',
      translation: 'marrón',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_gray-grey_001',
      word: 'gray / grey',
      translation: 'gris',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_color-colour_001',
      word: 'color / colour',
      translation: 'color',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_circle_001',
      word: 'circle',
      translation: 'círculo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_square_001',
      word: 'square',
      translation: 'cuadrado',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_triangle_001',
      word: 'triangle',
      translation: 'triángulo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_rectangle_001',
      word: 'rectangle',
      translation: 'rectángulo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_star_001',
      word: 'star (shape)',
      translation: 'estrella',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_heart_001',
      word: 'heart (shape)',
      translation: 'corazón',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_shape_001',
      word: 'shape',
      translation: 'forma',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_big_001',
      word: 'big',
      translation: 'grande',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_small_001',
      word: 'small',
      translation: 'pequeño',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_large_001',
      word: 'large',
      translation: 'grande',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_tiny_001',
      word: 'tiny',
      translation: 'diminuto',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_long_001',
      word: 'long',
      translation: 'largo',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_short_002',
      word: 'short (length)',
      translation: 'corto',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_wide_001',
      word: 'wide',
      translation: 'ancho',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_narrow_001',
      word: 'narrow',
      translation: 'estrecho',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_thick_001',
      word: 'thick',
      translation: 'grueso',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_thin_001',
      word: 'thin',
      translation: 'delgado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_heavy_001',
      word: 'heavy',
      translation: 'pesado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_light_001',
      word: 'light (weight)',
      translation: 'ligero',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_high_001',
      word: 'high',
      translation: 'alto (altura)',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_low_001',
      word: 'low',
      translation: 'bajo',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_good_001',
      word: 'good',
      translation: 'bueno',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_bad_001',
      word: 'bad',
      translation: 'malo',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_nice_001',
      word: 'nice',
      translation: 'agradable',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_beautiful_001',
      word: 'beautiful',
      translation: 'hermoso',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_ugly_001',
      word: 'ugly',
      translation: 'feo',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_pretty_001',
      word: 'pretty',
      translation: 'bonito',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_new_001',
      word: 'new',
      translation: 'nuevo',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_old_002',
      word: 'old (thing)',
      translation: 'viejo/antiguo',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_clean_001',
      word: 'clean',
      translation: 'limpio',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_dirty_001',
      word: 'dirty',
      translation: 'sucio',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_easy_001',
      word: 'easy',
      translation: 'fácil',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_difficult-hard_001',
      word: 'difficult / hard',
      translation: 'difícil',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_hot_001',
      word: 'hot',
      translation: 'caliente',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_cold_001',
      word: 'cold',
      translation: 'frío',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_warm_001',
      word: 'warm',
      translation: 'cálido',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_cool_001',
      word: 'cool',
      translation: 'fresco',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_fast_001',
      word: 'fast',
      translation: 'rápido',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_slow_001',
      word: 'slow',
      translation: 'lento',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_strong_001',
      word: 'strong',
      translation: 'fuerte',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_weak_001',
      word: 'weak',
      translation: 'débil',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_rich_001',
      word: 'rich',
      translation: 'rico',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_poor_001',
      word: 'poor',
      translation: 'pobre',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_happy_001',
      word: 'happy',
      translation: 'feliz',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_sad_001',
      word: 'sad',
      translation: 'triste',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_angry_001',
      word: 'angry',
      translation: 'enojado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_tired_001',
      word: 'tired',
      translation: 'cansado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_hungry_001',
      word: 'hungry',
      translation: 'hambriento',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_thirsty_001',
      word: 'thirsty',
      translation: 'sediento',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_full_001',
      word: 'full',
      translation: 'lleno',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_empty_001',
      word: 'empty',
      translation: 'vacío',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_open_001',
      word: 'open',
      translation: 'abierto',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_closed_001',
      word: 'closed',
      translation: 'cerrado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_right_001',
      word: 'right (correct)',
      translation: 'correcto',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_wrong_001',
      word: 'wrong',
      translation: 'incorrecto',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_same_001',
      word: 'same',
      translation: 'mismo',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_different_001',
      word: 'different',
      translation: 'diferente',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_expensive_001',
      word: 'expensive',
      translation: 'caro',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_cheap_001',
      word: 'cheap',
      translation: 'barato',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_quiet_001',
      word: 'quiet',
      translation: 'silencioso',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_noisy_001',
      word: 'noisy',
      translation: 'ruidoso',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_safe_001',
      word: 'safe',
      translation: 'seguro',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_dangerous_001',
      word: 'dangerous',
      translation: 'peligroso',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_interesting_001',
      word: 'interesting',
      translation: 'interesante',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_boring_001',
      word: 'boring',
      translation: 'aburrido',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_funny_001',
      word: 'funny',
      translation: 'gracioso',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_serious_001',
      word: 'serious',
      translation: 'serio',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_kind_001',
      word: 'kind',
      translation: 'amable',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_friendly_001',
      word: 'friendly',
      translation: 'amistoso',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_shy_001',
      word: 'shy',
      translation: 'tímido',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_brave_001',
      word: 'brave',
      translation: 'valiente',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_lazy_001',
      word: 'lazy',
      translation: 'perezoso',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_busy_001',
      word: 'busy',
      translation: 'ocupado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_free_001',
      word: 'free (available)',
      translation: 'libre',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_round_001',
      word: 'round',
      translation: 'redondo',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_flat_001',
      word: 'flat',
      translation: 'plano',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_straight_001',
      word: 'straight',
      translation: 'recto',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
  ],
}
