import type { ContentBlock } from '../types'

/**
 * A1 Level — Week 19
 * Topic: Semana 19 – Verbos irregulares esenciales (base – pasado – participio)
 * Curated from: a.md
 * Total items: 50
 */
export const week19: ContentBlock = {
  level: 'A1',
  week: 19,
  topic: 'Semana 19 – Verbos irregulares esenciales (base – pasado – participio)',
  vocabulary: [
    {
      id: 'voc_a1_go-went-gone_001',
      word: 'go – went – gone',
      translation: 'ir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/goʊ/ /wɛnt/ /gɔn/',
      example: 'I go to work by bus.',
      exampleTranslation: 'Voy al trabajo en autobús.',
      status: 'approved',
    },
    {
      id: 'voc_a1_see-saw-seen_001',
      word: 'see – saw – seen',
      translation: 'ver',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/si/ /sɔ/ /sin/',
      example: 'I see my friends on weekends.',
      exampleTranslation: 'Veo a mis amigos los fines de semana.',
      status: 'approved',
    },
    {
      id: 'voc_a1_eat-ate-eaten_001',
      word: 'eat – ate – eaten',
      translation: 'comer',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/it/ /eɪt/ /ˈitən/',
      example: 'We eat dinner at eight.',
      exampleTranslation: 'Cenamos a las ocho.',
      status: 'approved',
    },
    {
      id: 'voc_a1_drink-drank-drunk_001',
      word: 'drink – drank – drunk',
      translation: 'beber',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/drɪŋk/ /dræŋk/ /drʌŋk/',
      example: 'I drink coffee every morning.',
      exampleTranslation: 'Bebo café todas las mañanas.',
      status: 'approved',
    },
    {
      id: 'voc_a1_come-came-come_001',
      word: 'come – came – come',
      translation: 'venir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kʌm/ /keɪm/ /kʌm/',
      example: 'Please come early tomorrow.',
      exampleTranslation: 'Por favor ven temprano mañana.',
      status: 'approved',
    },
    {
      id: 'voc_a1_take-took-taken_001',
      word: 'take – took – taken',
      translation: 'tomar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/teɪk/ /tʊk/ /ˈteɪkən/',
      example: 'I take the bus every day.',
      exampleTranslation: 'Tomo el autobús todos los días.',
      status: 'approved',
    },
    {
      id: 'voc_a1_give-gave-given_001',
      word: 'give – gave – given',
      translation: 'dar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/gɪv/ /geɪv/ /ˈgɪvən/',
      example: 'Give me your hand, please.',
      exampleTranslation: 'Dame tu mano, por favor.',
      status: 'approved',
    },
    {
      id: 'voc_a1_make-made-made_001',
      word: 'make – made – made',
      translation: 'hacer/fabricar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/meɪk/ /meɪd/ /meɪd/',
      example: 'She makes breakfast every morning.',
      exampleTranslation: 'Ella hace el desayuno cada mañana.',
      status: 'approved',
    },
    {
      id: 'voc_a1_get-got-gotten_001',
      word: 'get – got – gotten',
      translation: 'obtener',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/gɛt/ /gɑt/ /ˈgɑtən/',
      example: 'I get up at seven.',
      exampleTranslation: 'Me levanto a las siete.',
      status: 'approved',
    },
    {
      id: 'voc_a1_say-said-said_001',
      word: 'say – said – said',
      translation: 'decir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/seɪ/ /sɛd/ /sɛd/',
      example: 'What did she say?',
      exampleTranslation: '¿Qué dijo ella?',
      status: 'approved',
    },
    {
      id: 'voc_a1_know-knew-known_001',
      word: 'know – knew – known',
      translation: 'saber/conocer',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/noʊ/ /nu/ /noʊn/',
      example: 'I know the answer.',
      exampleTranslation: 'Sé la respuesta.',
      status: 'approved',
    },
    {
      id: 'voc_a1_think-thought-thought_001',
      word: 'think – thought – thought',
      translation: 'pensar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/θɪŋk/ /θɔt/ /θɔt/',
      example: 'I think it will rain.',
      exampleTranslation: 'Creo que va a llover.',
      status: 'approved',
    },
    {
      id: 'voc_a1_find-found-found_001',
      word: 'find – found – found',
      translation: 'encontrar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/faɪnd/ /faʊnd/ /faʊnd/',
      example: 'I can\'t find my keys.',
      exampleTranslation: 'No encuentro mis llaves.',
      status: 'approved',
    },
    {
      id: 'voc_a1_tell-told-told_001',
      word: 'tell – told – told',
      translation: 'contar/decir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tɛl/ /toʊld/ /toʊld/',
      example: 'Tell me the truth.',
      exampleTranslation: 'Dime la verdad.',
      status: 'approved',
    },
    {
      id: 'voc_a1_become-became-become_001',
      word: 'become – became – become',
      translation: 'convertirse',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bɪˈkʌm/ /bɪˈkeɪm/ /bɪˈkʌm/',
      example: 'She became a doctor.',
      exampleTranslation: 'Ella se convirtió en médica.',
      status: 'approved',
    },
    {
      id: 'voc_a1_leave-left-left_001',
      word: 'leave – left – left',
      translation: 'irse/dejar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/liv/ /lɛft/ /lɛft/',
      example: 'I leave home at eight.',
      exampleTranslation: 'Salgo de casa a las ocho.',
      status: 'approved',
    },
    {
      id: 'voc_a1_feel-felt-felt_001',
      word: 'feel – felt – felt',
      translation: 'sentir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fil/ /fɛlt/ /fɛlt/',
      example: 'I feel tired today.',
      exampleTranslation: 'Me siento cansado hoy.',
      status: 'approved',
    },
    {
      id: 'voc_a1_bring-brought-brought_001',
      word: 'bring – brought – brought',
      translation: 'traer',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/brɪŋ/ /brɔt/ /brɔt/',
      example: 'Bring your homework tomorrow.',
      exampleTranslation: 'Trae tu tarea mañana.',
      status: 'approved',
    },
    {
      id: 'voc_a1_begin-began-begun_001',
      word: 'begin – began – begun',
      translation: 'comenzar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bɪˈgɪn/ /bɪˈgæn/ /bɪˈgʌn/',
      example: 'The movie begins at eight.',
      exampleTranslation: 'La película empieza a las ocho.',
      status: 'approved',
    },
    {
      id: 'voc_a1_keep-kept-kept_001',
      word: 'keep – kept – kept',
      translation: 'mantener',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kip/ /kɛpt/ /kɛpt/',
      example: 'You can keep the change.',
      exampleTranslation: 'Puedes quedarte con el cambio.',
      status: 'approved',
    },
    {
      id: 'voc_a1_hold-held-held_001',
      word: 'hold – held – held',
      translation: 'sostener',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/hoʊld/ /hɛld/ /hɛld/',
      example: 'She held the baby gently.',
      exampleTranslation: 'Ella sostuvo al bebé con cuidado.',
      status: 'approved',
    },
    {
      id: 'voc_a1_write-wrote-written_001',
      word: 'write – wrote – written',
      translation: 'escribir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/raɪt/ /roʊt/ /ˈrɪtən/',
      example: 'He writes letters to his family.',
      exampleTranslation: 'Él le escribe cartas a su familia.',
      status: 'approved',
    },
    {
      id: 'voc_a1_stand-stood-stood_001',
      word: 'stand – stood – stood',
      translation: 'pararse',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/stænd/ /stʊd/ /stʊd/',
      example: 'We stood in line for an hour.',
      exampleTranslation: 'Estuvimos parados en la fila una hora.',
      status: 'approved',
    },
    {
      id: 'voc_a1_hear-heard-heard_001',
      word: 'hear – heard – heard',
      translation: 'oír',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/hɪr/ /hɜrd/ /hɜrd/',
      example: 'Can you hear the music?',
      exampleTranslation: '¿Puedes oír la música?',
      status: 'approved',
    },
    {
      id: 'voc_a1_let-let-let_001',
      word: 'let – let – let',
      translation: 'permitir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/lɛt/ /lɛt/ /lɛt/',
      example: 'Let me help you.',
      exampleTranslation: 'Déjame ayudarte.',
      status: 'approved',
    },
    {
      id: 'voc_a1_mean-meant-meant_001',
      word: 'mean – meant – meant',
      translation: 'significar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/min/ /mɛnt/ /mɛnt/',
      example: 'What does this word mean?',
      exampleTranslation: '¿Qué significa esta palabra?',
      status: 'approved',
    },
    {
      id: 'voc_a1_meet-met-met_001',
      word: 'meet – met – met',
      translation: 'conocer/encontrarse',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/mit/ /mɛt/ /mɛt/',
      example: 'Nice to meet you.',
      exampleTranslation: 'Mucho gusto en conocerte.',
      status: 'approved',
    },
    {
      id: 'voc_a1_pay-paid-paid_001',
      word: 'pay – paid – paid',
      translation: 'pagar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/peɪ/ /peɪd/ /peɪd/',
      example: 'I will pay for dinner.',
      exampleTranslation: 'Yo pagaré la cena.',
      status: 'approved',
    },
    {
      id: 'voc_a1_run-ran-run_001',
      word: 'run – ran – run',
      translation: 'correr',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rʌn/ /ræn/ /rʌn/',
      example: 'She runs in the park on Sundays.',
      exampleTranslation: 'Ella corre en el parque los domingos.',
      status: 'approved',
    },
    {
      id: 'voc_a1_sit-sat-sat_001',
      word: 'sit – sat – sat',
      translation: 'sentarse',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/sɪt/ /sæt/ /sæt/',
      example: 'Please sit here.',
      exampleTranslation: 'Por favor siéntate aquí.',
      status: 'approved',
    },
    {
      id: 'voc_a1_speak-spoke-spoken_001',
      word: 'speak – spoke – spoken',
      translation: 'hablar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/spik/ /spoʊk/ /ˈspoʊkən/',
      example: 'Do you speak English?',
      exampleTranslation: '¿Hablas inglés?',
      status: 'approved',
    },
    {
      id: 'voc_a1_read-read-read_001',
      word: 'read – read – read',
      translation: 'leer',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rid/ /rɛd/ /rɛd/',
      example: 'I read a book before sleeping.',
      exampleTranslation: 'Leo un libro antes de dormir.',
      status: 'approved',
    },
    {
      id: 'voc_a1_grow-grew-grown_001',
      word: 'grow – grew – grown',
      translation: 'crecer',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/groʊ/ /gru/ /groʊn/',
      example: 'Children grow very fast.',
      exampleTranslation: 'Los niños crecen muy rápido.',
      status: 'approved',
    },
    {
      id: 'voc_a1_lose-lost-lost_001',
      word: 'lose – lost – lost',
      translation: 'perder',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/luz/ /lɔst/ /lɔst/',
      example: 'Don\'t lose your ticket.',
      exampleTranslation: 'No pierdas tu boleto.',
      status: 'approved',
    },
    {
      id: 'voc_a1_fall-fell-fallen_001',
      word: 'fall – fell – fallen',
      translation: 'caer',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fɔl/ /fɛl/ /ˈfɔlən/',
      example: 'Leaves fall in autumn.',
      exampleTranslation: 'Las hojas caen en otoño.',
      status: 'approved',
    },
    {
      id: 'voc_a1_send-sent-sent_001',
      word: 'send – sent – sent',
      translation: 'enviar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/sɛnd/ /sɛnt/ /sɛnt/',
      example: 'I will send you an email.',
      exampleTranslation: 'Te enviaré un correo electrónico.',
      status: 'approved',
    },
    {
      id: 'voc_a1_build-built-built_001',
      word: 'build – built – built',
      translation: 'construir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bɪld/ /bɪlt/ /bɪlt/',
      example: 'They built a new house.',
      exampleTranslation: 'Construyeron una casa nueva.',
      status: 'approved',
    },
    {
      id: 'voc_a1_understand-understood-understood_001',
      word: 'understand – understood – understood',
      translation: 'entender',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌʌndərˈstænd/ /ˌʌndərˈstʊd/ /ˌʌndərˈstʊd/',
      example: 'Do you understand the question?',
      exampleTranslation: '¿Entiendes la pregunta?',
      status: 'approved',
    },
    {
      id: 'voc_a1_break-broke-broken_001',
      word: 'break – broke – broken',
      translation: 'romper',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/breɪk/ /broʊk/ /ˈbroʊkən/',
      example: 'Be careful, don\'t break the glass.',
      exampleTranslation: 'Ten cuidado, no rompas el vaso.',
      status: 'approved',
    },
    {
      id: 'voc_a1_spend-spent-spent_001',
      word: 'spend – spent – spent',
      translation: 'gastar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/spɛnd/ /spɛnt/ /spɛnt/',
      example: 'We spend a lot on rent.',
      exampleTranslation: 'Gastamos mucho en el alquiler.',
      status: 'approved',
    },
    {
      id: 'voc_a1_drive-drove-driven_001',
      word: 'drive – drove – driven',
      translation: 'conducir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/draɪv/ /droʊv/ /ˈdrɪvən/',
      example: 'He drives to the office.',
      exampleTranslation: 'Él conduce a la oficina.',
      status: 'approved',
    },
    {
      id: 'voc_a1_buy-bought-bought_001',
      word: 'buy – bought – bought',
      translation: 'comprar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/baɪ/ /bɔt/ /bɔt/',
      example: 'I need to buy some bread.',
      exampleTranslation: 'Necesito comprar pan.',
      status: 'approved',
    },
    {
      id: 'voc_a1_catch-caught-caught_001',
      word: 'catch – caught – caught',
      translation: 'atrapar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kætʃ/ /kɔt/ /kɔt/',
      example: 'Catch the ball!',
      exampleTranslation: '¡Atrapa la pelota!',
      status: 'approved',
    },
    {
      id: 'voc_a1_teach-taught-taught_001',
      word: 'teach – taught – taught',
      translation: 'enseñar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/titʃ/ /tɔt/ /tɔt/',
      example: 'She teaches math at school.',
      exampleTranslation: 'Ella enseña matemáticas en la escuela.',
      status: 'approved',
    },
    {
      id: 'voc_a1_fly-flew-flown_001',
      word: 'fly – flew – flown',
      translation: 'volar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/flaɪ/ /flu/ /floʊn/',
      example: 'We fly to Chicago tomorrow.',
      exampleTranslation: 'Volamos a Chicago mañana.',
      status: 'approved',
    },
    {
      id: 'voc_a1_choose-chose-chosen_001',
      word: 'choose – chose – chosen',
      translation: 'elegir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tʃuz/ /tʃoʊz/ /ˈtʃoʊzən/',
      example: 'Choose your favorite color.',
      exampleTranslation: 'Elige tu color favorito.',
      status: 'approved',
    },
    {
      id: 'voc_a1_wear-wore-worn_001',
      word: 'wear – wore – worn',
      translation: 'llevar puesto',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/wɛr/ /wɔr/ /wɔrn/',
      example: 'She wears jeans to work.',
      exampleTranslation: 'Ella usa jeans para trabajar.',
      status: 'approved',
    },
    {
      id: 'voc_a1_sell-sold-sold_001',
      word: 'sell – sold – sold',
      translation: 'vender',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/sɛl/ /soʊld/ /soʊld/',
      example: 'They sell fresh fruit here.',
      exampleTranslation: 'Aquí venden fruta fresca.',
      status: 'approved',
    },
    {
      id: 'voc_a1_forget-forgot-forgotten_001',
      word: 'forget – forgot – forgotten',
      translation: 'olvidar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fərˈgɛt/ /fərˈgɑt/ /fərˈgɑtən/',
      example: 'Don\'t forget your keys.',
      exampleTranslation: 'No olvides tus llaves.',
      status: 'approved',
    },
    {
      id: 'voc_a1_put-put-put_001',
      word: 'put – put – put',
      translation: 'poner',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pʊt/ /pʊt/ /pʊt/',
      example: 'Put the box on the table.',
      exampleTranslation: 'Pon la caja sobre la mesa.',
      status: 'approved',
    },
  ],
}
