import type { ContentBlock } from '../types'

/**
 * A1 Level — Week 14
 * Topic: Semana 14 – Preposiciones, palabras de pregunta y conectores
 * Curated from: a.md
 * Total items: 55
 */
export const week14: ContentBlock = {
  level: 'A1',
  week: 14,
  topic: 'Semana 14 – Preposiciones, palabras de pregunta y conectores',
  vocabulary: [
    {
      id: 'voc_a1_in_001',
      word: 'in',
      translation: 'en',
      partOfSpeech: 'preposition',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_on_001',
      word: 'on',
      translation: 'sobre/en',
      partOfSpeech: 'preposition',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_at_001',
      word: 'at',
      translation: 'en (lugar/hora)',
      partOfSpeech: 'preposition',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_under_001',
      word: 'under',
      translation: 'debajo de',
      partOfSpeech: 'preposition',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_over_001',
      word: 'over',
      translation: 'sobre/encima de',
      partOfSpeech: 'preposition',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_above_001',
      word: 'above',
      translation: 'arriba de',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_below_001',
      word: 'below',
      translation: 'debajo de',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_inside_001',
      word: 'inside',
      translation: 'dentro',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_outside_001',
      word: 'outside',
      translation: 'afuera',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_up_001',
      word: 'up',
      translation: 'arriba',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_down_001',
      word: 'down',
      translation: 'abajo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_into_001',
      word: 'into',
      translation: 'hacia dentro',
      partOfSpeech: 'preposition',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_onto_001',
      word: 'onto',
      translation: 'hacia encima',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_through_001',
      word: 'through',
      translation: 'a través de',
      partOfSpeech: 'preposition',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_across_001',
      word: 'across',
      translation: 'a través de / cruzando',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_along_001',
      word: 'along',
      translation: 'a lo largo de',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_around_001',
      word: 'around',
      translation: 'alrededor de',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_before_002',
      word: 'before (place/time)',
      translation: 'antes',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_during_001',
      word: 'during',
      translation: 'durante',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_for_001',
      word: 'for',
      translation: 'para/por',
      partOfSpeech: 'preposition',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_with_001',
      word: 'with',
      translation: 'con',
      partOfSpeech: 'preposition',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_without_001',
      word: 'without',
      translation: 'sin',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_about_001',
      word: 'about',
      translation: 'acerca de',
      partOfSpeech: 'preposition',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_against_001',
      word: 'against',
      translation: 'contra',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_toward_001',
      word: 'toward',
      translation: 'hacia',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_whom_001',
      word: 'whom',
      translation: 'a quién',
      partOfSpeech: 'pronoun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_whose_001',
      word: 'whose',
      translation: 'de quién',
      partOfSpeech: 'pronoun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_how-much_001',
      word: 'how much',
      translation: 'cuánto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_how-many_001',
      word: 'how many',
      translation: 'cuántos',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_how-often_001',
      word: 'how often',
      translation: 'con qué frecuencia',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_how-long_001',
      word: 'how long',
      translation: 'cuánto tiempo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_so_001',
      word: 'so',
      translation: 'así que',
      partOfSpeech: 'conjunction',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_because_001',
      word: 'because',
      translation: 'porque',
      partOfSpeech: 'conjunction',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_if_001',
      word: 'if',
      translation: 'si',
      partOfSpeech: 'conjunction',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_while_002',
      word: 'while (conj.)',
      translation: 'mientras',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_although_001',
      word: 'although',
      translation: 'aunque',
      partOfSpeech: 'conjunction',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_however_001',
      word: 'however',
      translation: 'sin embargo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_also_001',
      word: 'also',
      translation: 'también',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_either_001',
      word: 'either',
      translation: 'tampoco/o',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_neither_001',
      word: 'neither',
      translation: 'ni/tampoco',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_both_001',
      word: 'both',
      translation: 'ambos',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_all_001',
      word: 'all',
      translation: 'todo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_every_001',
      word: 'every',
      translation: 'cada',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_each_001',
      word: 'each',
      translation: 'cada uno',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_some_001',
      word: 'some',
      translation: 'algo/algunos',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_any_001',
      word: 'any',
      translation: 'alguno/ninguno',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_many_001',
      word: 'many',
      translation: 'muchos',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_much_001',
      word: 'much',
      translation: 'mucho',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_few_001',
      word: 'few',
      translation: 'pocos',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_little_001',
      word: 'little',
      translation: 'poco',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_several_001',
      word: 'several',
      translation: 'varios',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_other_001',
      word: 'other',
      translation: 'otro',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_another_001',
      word: 'another',
      translation: 'otro (adicional)',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_such_001',
      word: 'such',
      translation: 'tal',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_than_001',
      word: 'than',
      translation: 'que (comparación)',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
  ],
}
