import type { ContentBlock } from '../types'

/**
 * A1 Level — Week 2
 * Topic: Semana 2 – Números, días, meses y expresiones de tiempo
 * Curated from: a.md
 * Total items: 88
 */
export const week02: ContentBlock = {
  level: 'A1',
  week: 2,
  topic: 'Semana 2 – Números, días, meses y expresiones de tiempo',
  vocabulary: [
    {
      id: 'voc_a1_twenty-one_001',
      word: 'twenty-one',
      translation: 'veintiuno',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtwɛntiˌwʌn/',
      example: 'I am twenty-one years old.',
      exampleTranslation: 'Tengo veintiún años.',
      status: 'approved',
    },
    {
      id: 'voc_a1_thirty_001',
      word: 'thirty',
      translation: 'treinta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈθɜrti/',
      example: 'My mother is thirty years old.',
      exampleTranslation: 'Mi madre tiene treinta años.',
      status: 'approved',
    },
    {
      id: 'voc_a1_forty_001',
      word: 'forty',
      translation: 'cuarenta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfɔrti/',
      example: 'The trip takes forty minutes.',
      exampleTranslation: 'El viaje toma cuarenta minutos.',
      status: 'approved',
    },
    {
      id: 'voc_a1_fifty_001',
      word: 'fifty',
      translation: 'cincuenta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfɪfti/',
      example: 'There are fifty students in the school.',
      exampleTranslation: 'Hay cincuenta estudiantes en la escuela.',
      status: 'approved',
    },
    {
      id: 'voc_a1_sixty_001',
      word: 'sixty',
      translation: 'sesenta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsɪksti/',
      example: 'An hour has sixty minutes.',
      exampleTranslation: 'Una hora tiene sesenta minutos.',
      status: 'approved',
    },
    {
      id: 'voc_a1_seventy_001',
      word: 'seventy',
      translation: 'setenta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsɛvənti/',
      example: 'My grandfather is seventy years old.',
      exampleTranslation: 'Mi abuelo tiene setenta años.',
      status: 'approved',
    },
    {
      id: 'voc_a1_eighty_001',
      word: 'eighty',
      translation: 'ochenta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈeɪti/',
      example: 'She wants eighty dollars for the bike.',
      exampleTranslation: 'Ella quiere ochenta dólares por la bicicleta.',
      status: 'approved',
    },
    {
      id: 'voc_a1_ninety_001',
      word: 'ninety',
      translation: 'noventa',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈnaɪnti/',
      example: 'The book has ninety pages.',
      exampleTranslation: 'El libro tiene noventa páginas.',
      status: 'approved',
    },
    {
      id: 'voc_a1_hundred_001',
      word: 'hundred',
      translation: 'cien',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈhʌndrəd/',
      example: 'I have a hundred dollars.',
      exampleTranslation: 'Tengo cien dólares.',
      status: 'approved',
    },
    {
      id: 'voc_a1_thousand_001',
      word: 'thousand',
      translation: 'mil',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈθaʊzənd/',
      example: 'The city has a thousand houses.',
      exampleTranslation: 'La ciudad tiene mil casas.',
      status: 'approved',
    },
    {
      id: 'voc_a1_first_001',
      word: 'first',
      translation: 'primero',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fɜrst/',
      example: 'This is my first day at work.',
      exampleTranslation: 'Este es mi primer día de trabajo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_second_001',
      word: 'second',
      translation: 'segundo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsɛkənd/',
      example: 'Take the second door on the left.',
      exampleTranslation: 'Toma la segunda puerta a la izquierda.',
      status: 'approved',
    },
    {
      id: 'voc_a1_third_001',
      word: 'third',
      translation: 'tercero',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/θɜrd/',
      example: 'This is his third book.',
      exampleTranslation: 'Este es su tercer libro.',
      status: 'approved',
    },
    {
      id: 'voc_a1_fourth_001',
      word: 'fourth',
      translation: 'cuarto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fɔrθ/',
      example: 'We live on the fourth floor.',
      exampleTranslation: 'Vivimos en el cuarto piso.',
      status: 'approved',
    },
    {
      id: 'voc_a1_fifth_001',
      word: 'fifth',
      translation: 'quinto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fɪfθ/',
      example: 'Today is her fifth birthday.',
      exampleTranslation: 'Hoy es su quinto cumpleaños.',
      status: 'approved',
    },
    {
      id: 'voc_a1_last_001',
      word: 'last',
      translation: 'último',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/læst/',
      example: 'This is the last question.',
      exampleTranslation: 'Esta es la última pregunta.',
      status: 'approved',
    },
    {
      id: 'voc_a1_monday_001',
      word: 'Monday',
      translation: 'lunes',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmʌndeɪ/',
      example: 'I have class on Monday.',
      exampleTranslation: 'Tengo clase el lunes.',
      status: 'approved',
    },
    {
      id: 'voc_a1_tuesday_001',
      word: 'Tuesday',
      translation: 'martes',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtuzdeɪ/',
      example: 'We meet every Tuesday.',
      exampleTranslation: 'Nos reunimos todos los martes.',
      status: 'approved',
    },
    {
      id: 'voc_a1_wednesday_001',
      word: 'Wednesday',
      translation: 'miércoles',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈwɛnzdeɪ/',
      example: 'The store is closed on Wednesday.',
      exampleTranslation: 'La tienda está cerrada el miércoles.',
      status: 'approved',
    },
    {
      id: 'voc_a1_thursday_001',
      word: 'Thursday',
      translation: 'jueves',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈθɜrzdeɪ/',
      example: 'I work late on Thursday.',
      exampleTranslation: 'Trabajo hasta tarde el jueves.',
      status: 'approved',
    },
    {
      id: 'voc_a1_friday_001',
      word: 'Friday',
      translation: 'viernes',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfraɪdeɪ/',
      example: 'We go to the movies on Friday.',
      exampleTranslation: 'Vamos al cine el viernes.',
      status: 'approved',
    },
    {
      id: 'voc_a1_saturday_001',
      word: 'Saturday',
      translation: 'sábado',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsætərdeɪ/',
      example: 'I clean the house on Saturday.',
      exampleTranslation: 'Limpio la casa el sábado.',
      status: 'approved',
    },
    {
      id: 'voc_a1_sunday_001',
      word: 'Sunday',
      translation: 'domingo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsʌndeɪ/',
      example: 'We rest on Sunday.',
      exampleTranslation: 'Descansamos el domingo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_day_001',
      word: 'day',
      translation: 'día',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/deɪ/',
      example: 'Have a nice day!',
      exampleTranslation: '¡Que tengas un buen día!',
      status: 'approved',
    },
    {
      id: 'voc_a1_week_001',
      word: 'week',
      translation: 'semana',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/wik/',
      example: 'I see her once a week.',
      exampleTranslation: 'La veo una vez por semana.',
      status: 'approved',
    },
    {
      id: 'voc_a1_weekend_001',
      word: 'weekend',
      translation: 'fin de semana',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈwikˌɛnd/',
      example: 'What are your plans for the weekend?',
      exampleTranslation: '¿Cuáles son tus planes para el fin de semana?',
      status: 'approved',
    },
    {
      id: 'voc_a1_january_001',
      word: 'January',
      translation: 'enero',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdʒænjuˌɛri/',
      example: 'My birthday is in January.',
      exampleTranslation: 'Mi cumpleaños es en enero.',
      status: 'approved',
    },
    {
      id: 'voc_a1_february_001',
      word: 'February',
      translation: 'febrero',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfɛbruˌɛri/',
      example: 'It is very cold in February.',
      exampleTranslation: 'Hace mucho frío en febrero.',
      status: 'approved',
    },
    {
      id: 'voc_a1_march_001',
      word: 'March',
      translation: 'marzo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/mɑrtʃ/',
      example: 'Spring starts in March.',
      exampleTranslation: 'La primavera empieza en marzo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_april_001',
      word: 'April',
      translation: 'abril',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈeɪprəl/',
      example: 'It rains a lot in April.',
      exampleTranslation: 'Llueve mucho en abril.',
      status: 'approved',
    },
    {
      id: 'voc_a1_may_001',
      word: 'May',
      translation: 'mayo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/meɪ/',
      example: 'We got married in May.',
      exampleTranslation: 'Nos casamos en mayo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_june_001',
      word: 'June',
      translation: 'junio',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dʒun/',
      example: 'School finishes in June.',
      exampleTranslation: 'La escuela termina en junio.',
      status: 'approved',
    },
    {
      id: 'voc_a1_july_001',
      word: 'July',
      translation: 'julio',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dʒʊˈlaɪ/',
      example: 'We go to the beach in July.',
      exampleTranslation: 'Vamos a la playa en julio.',
      status: 'approved',
    },
    {
      id: 'voc_a1_august_001',
      word: 'August',
      translation: 'agosto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɔgəst/',
      example: 'August is the hottest month.',
      exampleTranslation: 'Agosto es el mes más caluroso.',
      status: 'approved',
    },
    {
      id: 'voc_a1_september_001',
      word: 'September',
      translation: 'septiembre',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/sɛpˈtɛmbər/',
      example: 'Classes start in September.',
      exampleTranslation: 'Las clases empiezan en septiembre.',
      status: 'approved',
    },
    {
      id: 'voc_a1_october_001',
      word: 'October',
      translation: 'octubre',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɑkˈtoʊbər/',
      example: 'The leaves fall in October.',
      exampleTranslation: 'Las hojas caen en octubre.',
      status: 'approved',
    },
    {
      id: 'voc_a1_november_001',
      word: 'November',
      translation: 'noviembre',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/noʊˈvɛmbər/',
      example: 'It gets dark early in November.',
      exampleTranslation: 'Oscurece temprano en noviembre.',
      status: 'approved',
    },
    {
      id: 'voc_a1_december_001',
      word: 'December',
      translation: 'diciembre',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dɪˈsɛmbər/',
      example: 'We celebrate the holidays in December.',
      exampleTranslation: 'Celebramos las fiestas en diciembre.',
      status: 'approved',
    },
    {
      id: 'voc_a1_spring_001',
      word: 'spring',
      translation: 'primavera',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/sprɪŋ/',
      example: 'The flowers grow in spring.',
      exampleTranslation: 'Las flores crecen en primavera.',
      status: 'approved',
    },
    {
      id: 'voc_a1_summer_001',
      word: 'summer',
      translation: 'verano',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsʌmər/',
      example: 'We swim a lot in summer.',
      exampleTranslation: 'Nadamos mucho en verano.',
      status: 'approved',
    },
    {
      id: 'voc_a1_autumn-fall_001',
      word: 'autumn / fall',
      translation: 'otoño',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɔtəm/',
      example: 'The weather is cool in autumn.',
      exampleTranslation: 'El clima es fresco en otoño.',
      status: 'approved',
    },
    {
      id: 'voc_a1_winter_001',
      word: 'winter',
      translation: 'invierno',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈwɪntər/',
      example: 'It snows every winter here.',
      exampleTranslation: 'Nieva todos los inviernos aquí.',
      status: 'approved',
    },
    {
      id: 'voc_a1_season_001',
      word: 'season',
      translation: 'estación',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsizən/',
      example: 'Which season do you like best?',
      exampleTranslation: '¿Cuál estación te gusta más?',
      status: 'approved',
    },
    {
      id: 'voc_a1_today_001',
      word: 'today',
      translation: 'hoy',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/təˈdeɪ/',
      example: 'Today is a sunny day.',
      exampleTranslation: 'Hoy es un día soleado.',
      status: 'approved',
    },
    {
      id: 'voc_a1_tomorrow_001',
      word: 'tomorrow',
      translation: 'mañana',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/təˈmɑroʊ/',
      example: 'I will call you tomorrow.',
      exampleTranslation: 'Te llamaré mañana.',
      status: 'approved',
    },
    {
      id: 'voc_a1_yesterday_001',
      word: 'yesterday',
      translation: 'ayer',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈjɛstərˌdeɪ/',
      example: 'I saw her yesterday.',
      exampleTranslation: 'La vi ayer.',
      status: 'approved',
    },
    {
      id: 'voc_a1_morning_001',
      word: 'morning',
      translation: 'mañana (parte del día)',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmɔrnɪŋ/',
      example: 'I drink coffee every morning.',
      exampleTranslation: 'Bebo café todas las mañanas.',
      status: 'approved',
    },
    {
      id: 'voc_a1_afternoon_001',
      word: 'afternoon',
      translation: 'tarde',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌæftərˈnun/',
      example: 'We have lunch in the afternoon.',
      exampleTranslation: 'Almorzamos por la tarde.',
      status: 'approved',
    },
    {
      id: 'voc_a1_evening_001',
      word: 'evening',
      translation: 'noche (temprana)',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈivnɪŋ/',
      example: 'I read books in the evening.',
      exampleTranslation: 'Leo libros por la noche (temprano).',
      status: 'approved',
    },
    {
      id: 'voc_a1_night_001',
      word: 'night',
      translation: 'noche',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/naɪt/',
      example: 'The stars are bright at night.',
      exampleTranslation: 'Las estrellas brillan de noche.',
      status: 'approved',
    },
    {
      id: 'voc_a1_oclock_001',
      word: "o'clock",
      translation: 'en punto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈklɑk/',
      example: 'It is three o\'clock.',
      exampleTranslation: 'Son las tres en punto.',
      status: 'approved',
    },
    {
      id: 'voc_a1_hour_001',
      word: 'hour',
      translation: 'hora',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈaʊər/',
      example: 'The movie lasts one hour.',
      exampleTranslation: 'La película dura una hora.',
      status: 'approved',
    },
    {
      id: 'voc_a1_minute_001',
      word: 'minute',
      translation: 'minuto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmɪnɪt/',
      example: 'Wait a minute, please.',
      exampleTranslation: 'Espera un minuto, por favor.',
      status: 'approved',
    },
    {
      id: 'voc_a1_second_002',
      word: 'second (time)',
      translation: 'segundo (tiempo)',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsɛkənd/',
      example: 'Give me one second.',
      exampleTranslation: 'Dame un segundo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_time_001',
      word: 'time',
      translation: 'tiempo/hora',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/taɪm/',
      example: 'What time is it?',
      exampleTranslation: '¿Qué hora es?',
      status: 'approved',
    },
    {
      id: 'voc_a1_early_001',
      word: 'early',
      translation: 'temprano',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɜrli/',
      example: 'I woke up early today.',
      exampleTranslation: 'Me desperté temprano hoy.',
      status: 'approved',
    },
    {
      id: 'voc_a1_late_001',
      word: 'late',
      translation: 'tarde',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/leɪt/',
      example: 'Sorry, I am late.',
      exampleTranslation: 'Perdón, llego tarde.',
      status: 'approved',
    },
    {
      id: 'voc_a1_always_001',
      word: 'always',
      translation: 'siempre',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɔlweɪz/',
      example: 'She always drinks tea.',
      exampleTranslation: 'Ella siempre bebe té.',
      status: 'approved',
    },
    {
      id: 'voc_a1_never_001',
      word: 'never',
      translation: 'nunca',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈnɛvər/',
      example: 'He never eats meat.',
      exampleTranslation: 'Él nunca come carne.',
      status: 'approved',
    },
    {
      id: 'voc_a1_sometimes_001',
      word: 'sometimes',
      translation: 'a veces',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsʌmˌtaɪmz/',
      example: 'Sometimes I walk to work.',
      exampleTranslation: 'A veces camino al trabajo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_often_001',
      word: 'often',
      translation: 'a menudo',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɔfən/',
      example: 'We often visit our grandmother.',
      exampleTranslation: 'A menudo visitamos a nuestra abuela.',
      status: 'approved',
    },
    {
      id: 'voc_a1_usually_001',
      word: 'usually',
      translation: 'usualmente',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈjuʒuəli/',
      example: 'I usually wake up at seven.',
      exampleTranslation: 'Usualmente me despierto a las siete.',
      status: 'approved',
    },
    {
      id: 'voc_a1_half_001',
      word: 'half',
      translation: 'medio/media',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/hæf/',
      example: 'It is half past two.',
      exampleTranslation: 'Son las dos y media.',
      status: 'approved',
    },
    {
      id: 'voc_a1_quarter_001',
      word: 'quarter',
      translation: 'cuarto (fracción)',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkwɔrtər/',
      example: 'It is a quarter to five.',
      exampleTranslation: 'Son las cinco menos cuarto.',
      status: 'approved',
    },
    {
      id: 'voc_a1_past_001',
      word: 'past',
      translation: 'pasado / y (hora)',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pæst/',
      example: 'It is ten past six.',
      exampleTranslation: 'Son las seis y diez.',
      status: 'approved',
    },
    {
      id: 'voc_a1_to_001',
      word: 'to (time)',
      translation: 'menos (hora)',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tu/',
      example: 'It is five to nine.',
      exampleTranslation: 'Son las nueve menos cinco.',
      status: 'approved',
    },
    {
      id: 'voc_a1_date_001',
      word: 'date',
      translation: 'fecha',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/deɪt/',
      example: 'What is today\'s date?',
      exampleTranslation: '¿Cuál es la fecha de hoy?',
      status: 'approved',
    },
    {
      id: 'voc_a1_year_001',
      word: 'year',
      translation: 'año',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/jɪr/',
      example: 'This year has been busy.',
      exampleTranslation: 'Este año ha estado ocupado.',
      status: 'approved',
    },
    {
      id: 'voc_a1_month_001',
      word: 'month',
      translation: 'mes',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/mʌnθ/',
      example: 'Next month is my birthday.',
      exampleTranslation: 'El próximo mes es mi cumpleaños.',
      status: 'approved',
    },
    {
      id: 'voc_a1_calendar_001',
      word: 'calendar',
      translation: 'calendario',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkæləndər/',
      example: 'I have a calendar on my desk.',
      exampleTranslation: 'Tengo un calendario en mi escritorio.',
      status: 'approved',
    },
    {
      id: 'voc_a1_birthday_001',
      word: 'birthday',
      translation: 'cumpleaños',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbɜrθˌdeɪ/',
      example: 'Happy birthday!',
      exampleTranslation: '¡Feliz cumpleaños!',
      status: 'approved',
    },
    {
      id: 'voc_a1_holiday_001',
      word: 'holiday',
      translation: 'día festivo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈhɑlɪˌdeɪ/',
      example: 'Christmas is my favorite holiday.',
      exampleTranslation: 'La Navidad es mi día festivo favorito.',
      status: 'approved',
    },
    {
      id: 'voc_a1_vacation_001',
      word: 'vacation',
      translation: 'vacaciones',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/veɪˈkeɪʃən/',
      example: 'We are on vacation this week.',
      exampleTranslation: 'Estamos de vacaciones esta semana.',
      status: 'approved',
    },
    {
      id: 'voc_a1_soon_001',
      word: 'soon',
      translation: 'pronto',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/sun/',
      example: 'See you soon!',
      exampleTranslation: '¡Nos vemos pronto!',
      status: 'approved',
    },
    {
      id: 'voc_a1_later_001',
      word: 'later',
      translation: 'más tarde',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈleɪtər/',
      example: 'I will finish it later.',
      exampleTranslation: 'Lo terminaré más tarde.',
      status: 'approved',
    },
    {
      id: 'voc_a1_before_001',
      word: 'before',
      translation: 'antes',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bɪˈfɔr/',
      example: 'Wash your hands before dinner.',
      exampleTranslation: 'Lávate las manos antes de cenar.',
      status: 'approved',
    },
    {
      id: 'voc_a1_after_001',
      word: 'after',
      translation: 'después',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈæftər/',
      example: 'We go home after work.',
      exampleTranslation: 'Vamos a casa después del trabajo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_still_001',
      word: 'still',
      translation: 'todavía',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/stɪl/',
      example: 'She is still sleeping.',
      exampleTranslation: 'Ella todavía está durmiendo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_already_001',
      word: 'already',
      translation: 'ya',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɔlˈrɛdi/',
      example: 'I have already finished my homework.',
      exampleTranslation: 'Ya terminé mi tarea.',
      status: 'approved',
    },
    {
      id: 'voc_a1_ago_001',
      word: 'ago',
      translation: 'hace (tiempo)',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈgoʊ/',
      example: 'I moved here two years ago.',
      exampleTranslation: 'Me mudé aquí hace dos años.',
      status: 'approved',
    },
    {
      id: 'voc_a1_since_001',
      word: 'since',
      translation: 'desde',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/sɪns/',
      example: 'I have lived here since 2020.',
      exampleTranslation: 'Vivo aquí desde 2020.',
      status: 'approved',
    },
    {
      id: 'voc_a1_until_001',
      word: 'until',
      translation: 'hasta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ənˈtɪl/',
      example: 'We waited until midnight.',
      exampleTranslation: 'Esperamos hasta la medianoche.',
      status: 'approved',
    },
    {
      id: 'voc_a1_while_001',
      word: 'while',
      translation: 'mientras',
      partOfSpeech: 'conjunction',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/waɪl/',
      example: 'She called while I was cooking.',
      exampleTranslation: 'Ella llamó mientras yo cocinaba.',
      status: 'approved',
    },
    {
      id: 'voc_a1_noon_001',
      word: 'noon',
      translation: 'mediodía',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/nun/',
      example: 'We eat lunch at noon.',
      exampleTranslation: 'Almorzamos al mediodía.',
      status: 'approved',
    },
    {
      id: 'voc_a1_midnight_001',
      word: 'midnight',
      translation: 'medianoche',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmɪdˌnaɪt/',
      example: 'The party ends at midnight.',
      exampleTranslation: 'La fiesta termina a medianoche.',
      status: 'approved',
    },
    {
      id: 'voc_a1_century_001',
      word: 'century',
      translation: 'siglo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsɛntʃəri/',
      example: 'This building is one century old.',
      exampleTranslation: 'Este edificio tiene un siglo de antigüedad.',
      status: 'approved',
    },
    {
      id: 'voc_a1_decade_001',
      word: 'decade',
      translation: 'década',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdɛkeɪd/',
      example: 'I have lived here for a decade.',
      exampleTranslation: 'He vivido aquí por una década.',
      status: 'approved',
    },
    {
      id: 'voc_a1_weekday_001',
      word: 'weekday',
      translation: 'día de semana',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈwikˌdeɪ/',
      example: 'I work every weekday.',
      exampleTranslation: 'Trabajo todos los días de la semana (laborales).',
      status: 'approved',
    },
  ],
}
