import type { ContentBlock } from '../types'

/**
 * A1 Level — Week 16
 * Topic: Semana 16 – Tecnología, comunicación y entretenimiento
 * Curated from: a.md
 * Total items: 105
 */
export const week16: ContentBlock = {
  level: 'A1',
  week: 16,
  topic: 'Semana 16 – Tecnología, comunicación y entretenimiento',
  vocabulary: [
    {
      id: 'voc_a1_laptop_001',
      word: 'laptop',
      translation: 'laptop',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_tablet_001',
      word: 'tablet',
      translation: 'tableta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_smartphone_001',
      word: 'smartphone',
      translation: 'teléfono inteligente',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_screen_001',
      word: 'screen',
      translation: 'pantalla',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_keyboard_001',
      word: 'keyboard',
      translation: 'teclado',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_mouse_002',
      word: 'mouse (device)',
      translation: 'ratón (dispositivo)',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_password_001',
      word: 'password',
      translation: 'contraseña',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_internet_001',
      word: 'internet',
      translation: 'internet',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_website_001',
      word: 'website',
      translation: 'sitio web',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_email_001',
      word: 'email',
      translation: 'correo electrónico',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_message_001',
      word: 'message',
      translation: 'mensaje',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_text-message_001',
      word: 'text message',
      translation: 'mensaje de texto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_app-application_001',
      word: 'app / application',
      translation: 'aplicación',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_social-media_001',
      word: 'social media',
      translation: 'redes sociales',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_photo-picture_001',
      word: 'photo / picture',
      translation: 'foto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_video_001',
      word: 'video',
      translation: 'video',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_camera_001',
      word: 'camera',
      translation: 'cámara',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_printer_001',
      word: 'printer',
      translation: 'impresora',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_charger_001',
      word: 'charger',
      translation: 'cargador',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_battery_001',
      word: 'battery',
      translation: 'batería',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_wifi_001',
      word: 'wifi',
      translation: 'wifi',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_download_001',
      word: 'download',
      translation: 'descargar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_upload_001',
      word: 'upload',
      translation: 'subir (archivo)',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_click_001',
      word: 'click',
      translation: 'hacer clic',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_type_001',
      word: 'type (keyboard)',
      translation: 'escribir (teclado)',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_search_001',
      word: 'search',
      translation: 'buscar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_save_002',
      word: 'save (file)',
      translation: 'guardar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_delete_001',
      word: 'delete',
      translation: 'borrar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_share_002',
      word: 'share (online)',
      translation: 'compartir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_post_001',
      word: 'post (verb)',
      translation: 'publicar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_comment_001',
      word: 'comment',
      translation: 'comentar/comentario',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_like_002',
      word: 'like (social media)',
      translation: 'dar me gusta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_follow_001',
      word: 'follow (online)',
      translation: 'seguir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_network_001',
      word: 'network',
      translation: 'red',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_file_001',
      word: 'file',
      translation: 'archivo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_folder_001',
      word: 'folder',
      translation: 'carpeta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_document_001',
      word: 'document',
      translation: 'documento',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_software_001',
      word: 'software',
      translation: 'software',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_update_001',
      word: 'update',
      translation: 'actualizar/actualización',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_install_001',
      word: 'install',
      translation: 'instalar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_soccer-football_001',
      word: 'soccer / football',
      translation: 'fútbol',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_basketball_001',
      word: 'basketball',
      translation: 'baloncesto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_baseball_001',
      word: 'baseball',
      translation: 'béisbol',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_tennis_001',
      word: 'tennis',
      translation: 'tenis',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_volleyball_001',
      word: 'volleyball',
      translation: 'voleibol',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_golf_001',
      word: 'golf',
      translation: 'golf',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_swimming_001',
      word: 'swimming',
      translation: 'natación',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_running_001',
      word: 'running',
      translation: 'correr (actividad)',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_cycling_001',
      word: 'cycling',
      translation: 'ciclismo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_hiking_001',
      word: 'hiking',
      translation: 'senderismo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_dancing_001',
      word: 'dancing',
      translation: 'baile',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_painting_001',
      word: 'painting (hobby)',
      translation: 'pintura (afición)',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_drawing_001',
      word: 'drawing',
      translation: 'dibujo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_photography_001',
      word: 'photography',
      translation: 'fotografía',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_gardening_001',
      word: 'gardening',
      translation: 'jardinería',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_chess_001',
      word: 'chess',
      translation: 'ajedrez',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_cards_001',
      word: 'cards (game)',
      translation: 'cartas',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_video-games_001',
      word: 'video games',
      translation: 'videojuegos',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_board-games_001',
      word: 'board games',
      translation: 'juegos de mesa',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_fishing_001',
      word: 'fishing',
      translation: 'pesca',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_camping_001',
      word: 'camping',
      translation: 'acampar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_yoga_001',
      word: 'yoga',
      translation: 'yoga',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_team_001',
      word: 'team',
      translation: 'equipo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_player_001',
      word: 'player',
      translation: 'jugador',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_coach_001',
      word: 'coach',
      translation: 'entrenador',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_referee_001',
      word: 'referee',
      translation: 'árbitro',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_match_001',
      word: 'match',
      translation: 'partido',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_game_001',
      word: 'game',
      translation: 'juego/partido',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_score_001',
      word: 'score',
      translation: 'puntuación',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_win_001',
      word: 'win',
      translation: 'ganar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_tie_002',
      word: 'tie (game)',
      translation: 'empate',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_championship_001',
      word: 'championship',
      translation: 'campeonato',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_competition_001',
      word: 'competition',
      translation: 'competencia',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_ball_001',
      word: 'ball',
      translation: 'pelota',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_goal_001',
      word: 'goal',
      translation: 'gol/meta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_court_001',
      word: 'court (sports)',
      translation: 'cancha',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_stadium_001',
      word: 'stadium',
      translation: 'estadio',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_song_001',
      word: 'song',
      translation: 'canción',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_instrument_001',
      word: 'instrument (music)',
      translation: 'instrumento musical',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_guitar_001',
      word: 'guitar',
      translation: 'guitarra',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_piano_001',
      word: 'piano',
      translation: 'piano',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_drum_001',
      word: 'drum',
      translation: 'tambor',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_violin_001',
      word: 'violin',
      translation: 'violín',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_band_001',
      word: 'band (music)',
      translation: 'banda',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_concert_001',
      word: 'concert',
      translation: 'concierto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_movie-film_001',
      word: 'movie / film',
      translation: 'película',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_tv-show_001',
      word: 'TV show',
      translation: 'programa de TV',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_series_001',
      word: 'series',
      translation: 'serie',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_episode_001',
      word: 'episode',
      translation: 'episodio',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_channel_001',
      word: 'channel',
      translation: 'canal',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_program_001',
      word: 'program',
      translation: 'programa',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_news_001',
      word: 'news',
      translation: 'noticias',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_cartoon_001',
      word: 'cartoon',
      translation: 'dibujos animados',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_comedy_001',
      word: 'comedy',
      translation: 'comedia',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_drama_001',
      word: 'drama',
      translation: 'drama',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_horror-movie_001',
      word: 'horror movie',
      translation: 'película de terror',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_hobby_001',
      word: 'hobby',
      translation: 'pasatiempo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_interest_001',
      word: 'interest (hobby)',
      translation: 'interés',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_free-time_001',
      word: 'free time',
      translation: 'tiempo libre',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_activity_001',
      word: 'activity',
      translation: 'actividad',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_club_001',
      word: 'club',
      translation: 'club',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_member_001',
      word: 'member',
      translation: 'miembro',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_event_001',
      word: 'event',
      translation: 'evento',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_party_001',
      word: 'party',
      translation: 'fiesta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_festival_001',
      word: 'festival',
      translation: 'festival',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 16,
      topic: 'tecnolog-a-comunicaci-n-y-entretenimiento',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
  ],
}
