import type { ContentBlock } from '../types'

/**
 * A1 Level — Week 9
 * Topic: Semana 9 – Clima y lugares de la ciudad
 * Curated from: a.md
 * Total items: 69
 */
export const week09: ContentBlock = {
  level: 'A1',
  week: 9,
  topic: 'Semana 9 – Clima y lugares de la ciudad',
  vocabulary: [
    {
      id: 'voc_a1_sun_001',
      word: 'sun',
      translation: 'sol',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_sunny_001',
      word: 'sunny',
      translation: 'soleado',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_rain_001',
      word: 'rain',
      translation: 'lluvia',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_rainy_001',
      word: 'rainy',
      translation: 'lluvioso',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_cloud_001',
      word: 'cloud',
      translation: 'nube',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_cloudy_001',
      word: 'cloudy',
      translation: 'nublado',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_wind_001',
      word: 'wind',
      translation: 'viento',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_windy_001',
      word: 'windy',
      translation: 'ventoso',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_snow_001',
      word: 'snow',
      translation: 'nieve',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_snowy_001',
      word: 'snowy',
      translation: 'nevado',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_storm_001',
      word: 'storm',
      translation: 'tormenta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_fog_001',
      word: 'fog',
      translation: 'niebla',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_temperature_001',
      word: 'temperature',
      translation: 'temperatura',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_degree_001',
      word: 'degree',
      translation: 'grado',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_weather-forecast_001',
      word: 'weather forecast',
      translation: 'pronóstico del tiempo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_weather_001',
      word: 'weather',
      translation: 'clima',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_city_001',
      word: 'city',
      translation: 'ciudad',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_town_001',
      word: 'town',
      translation: 'pueblo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_village_001',
      word: 'village',
      translation: 'aldea',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_street_001',
      word: 'street',
      translation: 'calle',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_road_001',
      word: 'road',
      translation: 'carretera',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_avenue_001',
      word: 'avenue',
      translation: 'avenida',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_park_001',
      word: 'park',
      translation: 'parque',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_square_002',
      word: 'square (place)',
      translation: 'plaza',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_bridge_001',
      word: 'bridge',
      translation: 'puente',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_building_001',
      word: 'building',
      translation: 'edificio',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_church_001',
      word: 'church',
      translation: 'iglesia',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_school_001',
      word: 'school',
      translation: 'escuela',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_hospital_001',
      word: 'hospital',
      translation: 'hospital',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_bank_001',
      word: 'bank',
      translation: 'banco',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_supermarket_001',
      word: 'supermarket',
      translation: 'supermercado',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_market_001',
      word: 'market',
      translation: 'mercado',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_store-shop_001',
      word: 'store / shop',
      translation: 'tienda',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_mall_001',
      word: 'mall',
      translation: 'centro comercial',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_museum_001',
      word: 'museum',
      translation: 'museo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_library_001',
      word: 'library',
      translation: 'biblioteca',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_cinema-movie-theater_001',
      word: 'cinema / movie theater',
      translation: 'cine',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_theater_001',
      word: 'theater',
      translation: 'teatro',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_hotel_001',
      word: 'hotel',
      translation: 'hotel',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_airport_001',
      word: 'airport',
      translation: 'aeropuerto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_station_001',
      word: 'station',
      translation: 'estación',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_bus-stop_001',
      word: 'bus stop',
      translation: 'parada de bus',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_caf_001',
      word: 'café',
      translation: 'cafetería',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_gym_001',
      word: 'gym',
      translation: 'gimnasio',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_pool_001',
      word: 'pool',
      translation: 'piscina',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_beach_001',
      word: 'beach',
      translation: 'playa',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_mountain_001',
      word: 'mountain',
      translation: 'montaña',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_river_001',
      word: 'river',
      translation: 'río',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_lake_001',
      word: 'lake',
      translation: 'lago',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_sea_001',
      word: 'sea',
      translation: 'mar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_ocean_001',
      word: 'ocean',
      translation: 'océano',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_forest_001',
      word: 'forest',
      translation: 'bosque',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_farm_001',
      word: 'farm',
      translation: 'granja',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_left_001',
      word: 'left',
      translation: 'izquierda',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_right_002',
      word: 'right (direction)',
      translation: 'derecha',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_near_001',
      word: 'near',
      translation: 'cerca',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_far_001',
      word: 'far',
      translation: 'lejos',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_next-to_001',
      word: 'next to',
      translation: 'al lado de',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_in-front-of_001',
      word: 'in front of',
      translation: 'enfrente de',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_behind_001',
      word: 'behind',
      translation: 'detrás de',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_between_001',
      word: 'between',
      translation: 'entre',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_corner_001',
      word: 'corner',
      translation: 'esquina',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_map_001',
      word: 'map',
      translation: 'mapa',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_address_002',
      word: 'address (place)',
      translation: 'dirección',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_downtown_001',
      word: 'downtown',
      translation: 'centro (de la ciudad)',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_suburb_001',
      word: 'suburb',
      translation: 'suburbio',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_traffic-light_001',
      word: 'traffic light',
      translation: 'semáforo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_sidewalk_001',
      word: 'sidewalk',
      translation: 'acera',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_crosswalk_001',
      word: 'crosswalk',
      translation: 'cruce peatonal',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 9,
      topic: 'clima-y-lugares-de-la-ciudad',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
  ],
}
