import type { ContentBlock } from '../types'

/**
 * A1 Level — Week 10
 * Topic: Semana 10 – Animales y naturaleza
 * Curated from: a.md
 * Total items: 80
 */
export const week10: ContentBlock = {
  level: 'A1',
  week: 10,
  topic: 'Semana 10 – Animales y naturaleza',
  vocabulary: [
    {
      id: 'voc_a1_dog_001',
      word: 'dog',
      translation: 'perro',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dɔg/',
      example: 'My dog likes to play outside.',
      exampleTranslation: 'A mi perro le gusta jugar afuera.',
      status: 'approved',
    },
    {
      id: 'voc_a1_cat_001',
      word: 'cat',
      translation: 'gato',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kæt/',
      example: 'The cat is sleeping on the sofa.',
      exampleTranslation: 'El gato está durmiendo en el sofá.',
      status: 'approved',
    },
    {
      id: 'voc_a1_bird_001',
      word: 'bird',
      translation: 'pájaro',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bɜrd/',
      example: 'A bird is singing in the tree.',
      exampleTranslation: 'Un pájaro está cantando en el árbol.',
      status: 'approved',
    },
    {
      id: 'voc_a1_fish_002',
      word: 'fish (animal)',
      translation: 'pez',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fɪʃ/',
      example: 'We have three fish in the tank.',
      exampleTranslation: 'Tenemos tres peces en la pecera.',
      status: 'approved',
    },
    {
      id: 'voc_a1_horse_001',
      word: 'horse',
      translation: 'caballo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/hɔrs/',
      example: 'She rides a horse every weekend.',
      exampleTranslation: 'Ella monta a caballo cada fin de semana.',
      status: 'approved',
    },
    {
      id: 'voc_a1_cow_001',
      word: 'cow',
      translation: 'vaca',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kaʊ/',
      example: 'The cow gives fresh milk.',
      exampleTranslation: 'La vaca da leche fresca.',
      status: 'approved',
    },
    {
      id: 'voc_a1_pig_001',
      word: 'pig',
      translation: 'cerdo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pɪg/',
      example: 'The pig lives on the farm.',
      exampleTranslation: 'El cerdo vive en la granja.',
      status: 'approved',
    },
    {
      id: 'voc_a1_sheep_001',
      word: 'sheep',
      translation: 'oveja',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ʃip/',
      example: 'The sheep are in the field.',
      exampleTranslation: 'Las ovejas están en el campo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_goat_001',
      word: 'goat',
      translation: 'cabra',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/goʊt/',
      example: 'The goat eats grass all day.',
      exampleTranslation: 'La cabra come pasto todo el día.',
      status: 'approved',
    },
    {
      id: 'voc_a1_duck_001',
      word: 'duck',
      translation: 'pato',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dʌk/',
      example: 'The duck swims in the lake.',
      exampleTranslation: 'El pato nada en el lago.',
      status: 'approved',
    },
    {
      id: 'voc_a1_rabbit_001',
      word: 'rabbit',
      translation: 'conejo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈræbɪt/',
      example: 'The rabbit is hiding in the garden.',
      exampleTranslation: 'El conejo se esconde en el jardín.',
      status: 'approved',
    },
    {
      id: 'voc_a1_mouse_001',
      word: 'mouse',
      translation: 'ratón',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/maʊs/',
      example: 'A mouse ran under the table.',
      exampleTranslation: 'Un ratón corrió debajo de la mesa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_lion_001',
      word: 'lion',
      translation: 'león',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈlaɪən/',
      example: 'The lion is the king of the jungle.',
      exampleTranslation: 'El león es el rey de la selva.',
      status: 'approved',
    },
    {
      id: 'voc_a1_tiger_001',
      word: 'tiger',
      translation: 'tigre',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtaɪgər/',
      example: 'The tiger has orange and black stripes.',
      exampleTranslation: 'El tigre tiene rayas naranjas y negras.',
      status: 'approved',
    },
    {
      id: 'voc_a1_elephant_001',
      word: 'elephant',
      translation: 'elefante',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɛləfənt/',
      example: 'The elephant is very big and gentle.',
      exampleTranslation: 'El elefante es muy grande y gentil.',
      status: 'approved',
    },
    {
      id: 'voc_a1_monkey_001',
      word: 'monkey',
      translation: 'mono',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmʌŋki/',
      example: 'The monkey climbed the tree quickly.',
      exampleTranslation: 'El mono subió al árbol rápidamente.',
      status: 'approved',
    },
    {
      id: 'voc_a1_bear_001',
      word: 'bear',
      translation: 'oso',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bɛr/',
      example: 'We saw a bear in the forest.',
      exampleTranslation: 'Vimos un oso en el bosque.',
      status: 'approved',
    },
    {
      id: 'voc_a1_wolf_001',
      word: 'wolf',
      translation: 'lobo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/wʊlf/',
      example: 'The wolf howled at the moon.',
      exampleTranslation: 'El lobo aulló a la luna.',
      status: 'approved',
    },
    {
      id: 'voc_a1_fox_001',
      word: 'fox',
      translation: 'zorro',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fɑks/',
      example: 'A fox crossed the road.',
      exampleTranslation: 'Un zorro cruzó el camino.',
      status: 'approved',
    },
    {
      id: 'voc_a1_deer_001',
      word: 'deer',
      translation: 'ciervo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dɪr/',
      example: 'We saw a deer near the lake.',
      exampleTranslation: 'Vimos un ciervo cerca del lago.',
      status: 'approved',
    },
    {
      id: 'voc_a1_snake_001',
      word: 'snake',
      translation: 'serpiente',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/sneɪk/',
      example: 'Be careful, there is a snake there.',
      exampleTranslation: 'Ten cuidado, hay una serpiente ahí.',
      status: 'approved',
    },
    {
      id: 'voc_a1_frog_001',
      word: 'frog',
      translation: 'rana',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/frɑg/',
      example: 'The frog jumped into the pond.',
      exampleTranslation: 'La rana saltó al estanque.',
      status: 'approved',
    },
    {
      id: 'voc_a1_turtle_001',
      word: 'turtle',
      translation: 'tortuga',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtɜrtəl/',
      example: 'The turtle moves very slowly.',
      exampleTranslation: 'La tortuga se mueve muy lento.',
      status: 'approved',
    },
    {
      id: 'voc_a1_butterfly_001',
      word: 'butterfly',
      translation: 'mariposa',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbʌtərˌflaɪ/',
      example: 'A butterfly landed on the flower.',
      exampleTranslation: 'Una mariposa se posó en la flor.',
      status: 'approved',
    },
    {
      id: 'voc_a1_bee_001',
      word: 'bee',
      translation: 'abeja',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bi/',
      example: 'The bee flew from flower to flower.',
      exampleTranslation: 'La abeja voló de flor en flor.',
      status: 'approved',
    },
    {
      id: 'voc_a1_spider_001',
      word: 'spider',
      translation: 'araña',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈspaɪdər/',
      example: 'There is a spider on the wall.',
      exampleTranslation: 'Hay una araña en la pared.',
      status: 'approved',
    },
    {
      id: 'voc_a1_ant_001',
      word: 'ant',
      translation: 'hormiga',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ænt/',
      example: 'The ants are carrying food.',
      exampleTranslation: 'Las hormigas están cargando comida.',
      status: 'approved',
    },
    {
      id: 'voc_a1_fly_001',
      word: 'fly (insect)',
      translation: 'mosca',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/flaɪ/',
      example: 'A fly is on the table.',
      exampleTranslation: 'Hay una mosca en la mesa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_mosquito_001',
      word: 'mosquito',
      translation: 'mosquito',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/məˈskitoʊ/',
      example: 'The mosquito bit my arm.',
      exampleTranslation: 'El mosquito me picó el brazo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_owl_001',
      word: 'owl',
      translation: 'búho',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/aʊl/',
      example: 'The owl sleeps during the day.',
      exampleTranslation: 'El búho duerme durante el día.',
      status: 'approved',
    },
    {
      id: 'voc_a1_eagle_001',
      word: 'eagle',
      translation: 'águila',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈigəl/',
      example: 'The eagle flew high in the sky.',
      exampleTranslation: 'El águila voló alto en el cielo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_shark_001',
      word: 'shark',
      translation: 'tiburón',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ʃɑrk/',
      example: 'We saw a shark in the ocean.',
      exampleTranslation: 'Vimos un tiburón en el océano.',
      status: 'approved',
    },
    {
      id: 'voc_a1_whale_001',
      word: 'whale',
      translation: 'ballena',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/weɪl/',
      example: 'The whale is the biggest animal in the sea.',
      exampleTranslation: 'La ballena es el animal más grande del mar.',
      status: 'approved',
    },
    {
      id: 'voc_a1_dolphin_001',
      word: 'dolphin',
      translation: 'delfín',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdɑlfən/',
      example: 'Dolphins are very intelligent animals.',
      exampleTranslation: 'Los delfines son animales muy inteligentes.',
      status: 'approved',
    },
    {
      id: 'voc_a1_tree_001',
      word: 'tree',
      translation: 'árbol',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tri/',
      example: 'There is a big tree in the yard.',
      exampleTranslation: 'Hay un árbol grande en el patio.',
      status: 'approved',
    },
    {
      id: 'voc_a1_flower_001',
      word: 'flower',
      translation: 'flor',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈflaʊər/',
      example: 'She bought fresh flowers.',
      exampleTranslation: 'Ella compró flores frescas.',
      status: 'approved',
    },
    {
      id: 'voc_a1_grass_001',
      word: 'grass',
      translation: 'pasto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/græs/',
      example: 'The grass is very green.',
      exampleTranslation: 'El pasto está muy verde.',
      status: 'approved',
    },
    {
      id: 'voc_a1_leaf_001',
      word: 'leaf',
      translation: 'hoja',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/lif/',
      example: 'A leaf fell from the tree.',
      exampleTranslation: 'Una hoja cayó del árbol.',
      status: 'approved',
    },
    {
      id: 'voc_a1_plant_001',
      word: 'plant',
      translation: 'planta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/plænt/',
      example: 'I water my plants every day.',
      exampleTranslation: 'Riego mis plantas todos los días.',
      status: 'approved',
    },
    {
      id: 'voc_a1_sky_001',
      word: 'sky',
      translation: 'cielo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/skaɪ/',
      example: 'The sky is clear today.',
      exampleTranslation: 'El cielo está despejado hoy.',
      status: 'approved',
    },
    {
      id: 'voc_a1_star_002',
      word: 'star (sky)',
      translation: 'estrella',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/stɑr/',
      example: 'You can see many stars at night.',
      exampleTranslation: 'Se pueden ver muchas estrellas de noche.',
      status: 'approved',
    },
    {
      id: 'voc_a1_moon_001',
      word: 'moon',
      translation: 'luna',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/mun/',
      example: 'The moon is very bright tonight.',
      exampleTranslation: 'La luna está muy brillante esta noche.',
      status: 'approved',
    },
    {
      id: 'voc_a1_rock_001',
      word: 'rock',
      translation: 'roca',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rɑk/',
      example: 'Be careful of the rocks on the path.',
      exampleTranslation: 'Ten cuidado con las rocas en el camino.',
      status: 'approved',
    },
    {
      id: 'voc_a1_stone_001',
      word: 'stone',
      translation: 'piedra',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/stoʊn/',
      example: 'The house is made of stone.',
      exampleTranslation: 'La casa está hecha de piedra.',
      status: 'approved',
    },
    {
      id: 'voc_a1_sand_001',
      word: 'sand',
      translation: 'arena',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/sænd/',
      example: 'The sand is very hot at noon.',
      exampleTranslation: 'La arena está muy caliente al mediodía.',
      status: 'approved',
    },
    {
      id: 'voc_a1_earth_001',
      word: 'earth',
      translation: 'tierra',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɜrθ/',
      example: 'The Earth is our home.',
      exampleTranslation: 'La Tierra es nuestro hogar.',
      status: 'approved',
    },
    {
      id: 'voc_a1_world_001',
      word: 'world',
      translation: 'mundo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/wɜrld/',
      example: 'I want to travel around the world.',
      exampleTranslation: 'Quiero viajar por el mundo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_nature_001',
      word: 'nature',
      translation: 'naturaleza',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈneɪtʃər/',
      example: 'I love spending time in nature.',
      exampleTranslation: 'Me encanta pasar tiempo en la naturaleza.',
      status: 'approved',
    },
    {
      id: 'voc_a1_animal_001',
      word: 'animal',
      translation: 'animal',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈænəməl/',
      example: 'This is my favorite animal.',
      exampleTranslation: 'Este es mi animal favorito.',
      status: 'approved',
    },
    {
      id: 'voc_a1_pet_001',
      word: 'pet',
      translation: 'mascota',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pɛt/',
      example: 'Do you have a pet at home?',
      exampleTranslation: '¿Tienes una mascota en casa?',
      status: 'approved',
    },
    {
      id: 'voc_a1_wild_001',
      word: 'wild',
      translation: 'salvaje',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/waɪld/',
      example: 'These are wild animals.',
      exampleTranslation: 'Estos son animales salvajes.',
      status: 'approved',
    },
    {
      id: 'voc_a1_field_001',
      word: 'field',
      translation: 'campo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fild/',
      example: 'The children play in the field.',
      exampleTranslation: 'Los niños juegan en el campo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_island_001',
      word: 'island',
      translation: 'isla',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈaɪlənd/',
      example: 'We spent our vacation on an island.',
      exampleTranslation: 'Pasamos nuestras vacaciones en una isla.',
      status: 'approved',
    },
    {
      id: 'voc_a1_desert_001',
      word: 'desert',
      translation: 'desierto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdɛzərt/',
      example: 'It doesn\'t rain much in the desert.',
      exampleTranslation: 'No llueve mucho en el desierto.',
      status: 'approved',
    },
    {
      id: 'voc_a1_jungle_001',
      word: 'jungle',
      translation: 'selva',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdʒʌŋgəl/',
      example: 'Many animals live in the jungle.',
      exampleTranslation: 'Muchos animales viven en la selva.',
      status: 'approved',
    },
    {
      id: 'voc_a1_valley_001',
      word: 'valley',
      translation: 'valle',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈvæli/',
      example: 'The valley is full of flowers.',
      exampleTranslation: 'El valle está lleno de flores.',
      status: 'approved',
    },
    {
      id: 'voc_a1_hill_001',
      word: 'hill',
      translation: 'colina',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/hɪl/',
      example: 'We walked up the hill.',
      exampleTranslation: 'Subimos la colina caminando.',
      status: 'approved',
    },
    {
      id: 'voc_a1_wave_001',
      word: 'wave',
      translation: 'ola',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/weɪv/',
      example: 'The waves are very big today.',
      exampleTranslation: 'Las olas están muy grandes hoy.',
      status: 'approved',
    },
    {
      id: 'voc_a1_rainbow_001',
      word: 'rainbow',
      translation: 'arcoíris',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈreɪnˌboʊ/',
      example: 'We saw a rainbow after the rain.',
      exampleTranslation: 'Vimos un arcoíris después de la lluvia.',
      status: 'approved',
    },
    {
      id: 'voc_a1_root_001',
      word: 'root',
      translation: 'raíz',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rut/',
      example: 'The tree\'s roots are very deep.',
      exampleTranslation: 'Las raíces del árbol son muy profundas.',
      status: 'approved',
    },
    {
      id: 'voc_a1_branch_001',
      word: 'branch',
      translation: 'rama',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bræntʃ/',
      example: 'A bird landed on the branch.',
      exampleTranslation: 'Un pájaro se posó en la rama.',
      status: 'approved',
    },
    {
      id: 'voc_a1_seed_001',
      word: 'seed',
      translation: 'semilla',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/sid/',
      example: 'We planted a seed in the garden.',
      exampleTranslation: 'Plantamos una semilla en el jardín.',
      status: 'approved',
    },
    {
      id: 'voc_a1_cage_001',
      word: 'cage',
      translation: 'jaula',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/keɪdʒ/',
      example: 'The bird is inside a cage.',
      exampleTranslation: 'El pájaro está dentro de una jaula.',
      status: 'approved',
    },
    {
      id: 'voc_a1_zoo_001',
      word: 'zoo',
      translation: 'zoológico',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/zu/',
      example: 'We took the kids to the zoo.',
      exampleTranslation: 'Llevamos a los niños al zoológico.',
      status: 'approved',
    },
    {
      id: 'voc_a1_aquarium_001',
      word: 'aquarium',
      translation: 'acuario',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈkwɛriəm/',
      example: 'We saw many fish at the aquarium.',
      exampleTranslation: 'Vimos muchos peces en el acuario.',
      status: 'approved',
    },
    {
      id: 'voc_a1_herd_001',
      word: 'herd',
      translation: 'manada',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/hɜrd/',
      example: 'A herd of cows crossed the road.',
      exampleTranslation: 'Una manada de vacas cruzó el camino.',
      status: 'approved',
    },
    {
      id: 'voc_a1_flock_001',
      word: 'flock',
      translation: 'bandada',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/flɑk/',
      example: 'A flock of birds flew south.',
      exampleTranslation: 'Una bandada de pájaros voló hacia el sur.',
      status: 'approved',
    },
    {
      id: 'voc_a1_nest_001',
      word: 'nest',
      translation: 'nido',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/nɛst/',
      example: 'The bird built a nest in the tree.',
      exampleTranslation: 'El pájaro hizo un nido en el árbol.',
      status: 'approved',
    },
    {
      id: 'voc_a1_den_001',
      word: 'den',
      translation: 'madriguera',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dɛn/',
      example: 'The fox has its den in the forest.',
      exampleTranslation: 'El zorro tiene su madriguera en el bosque.',
      status: 'approved',
    },
    {
      id: 'voc_a1_feather_001',
      word: 'feather',
      translation: 'pluma',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfɛðər/',
      example: 'I found a feather on the ground.',
      exampleTranslation: 'Encontré una pluma en el suelo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_fur_001',
      word: 'fur',
      translation: 'pelaje',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fɜr/',
      example: 'The cat has soft fur.',
      exampleTranslation: 'El gato tiene el pelaje suave.',
      status: 'approved',
    },
    {
      id: 'voc_a1_tail_001',
      word: 'tail',
      translation: 'cola',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/teɪl/',
      example: 'The dog wags its tail when happy.',
      exampleTranslation: 'El perro mueve la cola cuando está feliz.',
      status: 'approved',
    },
    {
      id: 'voc_a1_paw_001',
      word: 'paw',
      translation: 'pata',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pɔ/',
      example: 'The dog hurt its paw.',
      exampleTranslation: 'El perro se lastimó la pata.',
      status: 'approved',
    },
    {
      id: 'voc_a1_wing_001',
      word: 'wing',
      translation: 'ala',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/wɪŋ/',
      example: 'The bird spread its wings.',
      exampleTranslation: 'El pájaro extendió sus alas.',
      status: 'approved',
    },
    {
      id: 'voc_a1_claw_001',
      word: 'claw',
      translation: 'garra',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/klɔ/',
      example: 'The cat has sharp claws.',
      exampleTranslation: 'El gato tiene garras afiladas.',
      status: 'approved',
    },
    {
      id: 'voc_a1_hoof_001',
      word: 'hoof',
      translation: 'pezuña',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/hʊf/',
      example: 'The horse has strong hooves.',
      exampleTranslation: 'El caballo tiene pezuñas fuertes.',
      status: 'approved',
    },
    {
      id: 'voc_a1_predator_001',
      word: 'predator',
      translation: 'depredador',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈprɛdətər/',
      example: 'The lion is a dangerous predator.',
      exampleTranslation: 'El león es un depredador peligroso.',
      status: 'approved',
    },
    {
      id: 'voc_a1_prey_001',
      word: 'prey',
      translation: 'presa',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/preɪ/',
      example: 'The rabbit is prey for the fox.',
      exampleTranslation: 'El conejo es presa del zorro.',
      status: 'approved',
    },
    {
      id: 'voc_a1_species_001',
      word: 'species',
      translation: 'especie',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈspiʃiz/',
      example: 'This is a rare species of bird.',
      exampleTranslation: 'Esta es una especie rara de pájaro.',
      status: 'approved',
    },
    {
      id: 'voc_a1_wildlife_001',
      word: 'wildlife',
      translation: 'fauna silvestre',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 10,
      topic: 'animales-y-naturaleza',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈwaɪldˌlaɪf/',
      example: 'The park protects the local wildlife.',
      exampleTranslation: 'El parque protege la fauna silvestre local.',
      status: 'approved',
    },
  ],
}
