import type { ContentBlock } from '../types'

/**
 * A1 Level — Week 18
 * Topic: Semana 18 – Verbos de acción, ideas y repaso general
 * Curated from: a.md
 * Total items: 104
 */
export const week18: ContentBlock = {
  level: 'A1',
  week: 18,
  topic: 'Semana 18 – Verbos de acción, ideas y repaso general',
  vocabulary: [
    {
      id: 'voc_a1_put_001',
      word: 'put',
      translation: 'poner',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pʊt/',
      example: 'Put the box on the table.',
      exampleTranslation: 'Pon la caja sobre la mesa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_keep_001',
      word: 'keep',
      translation: 'mantener/guardar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kip/',
      example: 'You can keep the book.',
      exampleTranslation: 'Puedes quedarte con el libro.',
      status: 'approved',
    },
    {
      id: 'voc_a1_hold_001',
      word: 'hold',
      translation: 'sostener',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/hoʊld/',
      example: 'Can you hold my bag?',
      exampleTranslation: '¿Puedes sostener mi bolsa?',
      status: 'approved',
    },
    {
      id: 'voc_a1_carry_001',
      word: 'carry (object)',
      translation: 'llevar/cargar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkæri/',
      example: 'She carries her laptop every day.',
      exampleTranslation: 'Ella carga su laptop todos los días.',
      status: 'approved',
    },
    {
      id: 'voc_a1_pull_001',
      word: 'pull',
      translation: 'jalar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pʊl/',
      example: 'Pull the door to open it.',
      exampleTranslation: 'Jala la puerta para abrirla.',
      status: 'approved',
    },
    {
      id: 'voc_a1_push_001',
      word: 'push',
      translation: 'empujar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pʊʃ/',
      example: 'Push the button to start.',
      exampleTranslation: 'Presiona el botón para empezar.',
      status: 'approved',
    },
    {
      id: 'voc_a1_throw_001',
      word: 'throw',
      translation: 'lanzar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/θroʊ/',
      example: 'Throw the ball to me.',
      exampleTranslation: 'Lánzame la pelota.',
      status: 'approved',
    },
    {
      id: 'voc_a1_catch_001',
      word: 'catch',
      translation: 'atrapar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kætʃ/',
      example: 'Catch the ball!',
      exampleTranslation: '¡Atrapa la pelota!',
      status: 'approved',
    },
    {
      id: 'voc_a1_hit_001',
      word: 'hit',
      translation: 'golpear',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/hɪt/',
      example: 'He hit the ball hard.',
      exampleTranslation: 'Él golpeó la pelota fuerte.',
      status: 'approved',
    },
    {
      id: 'voc_a1_kick_001',
      word: 'kick',
      translation: 'patear',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kɪk/',
      example: 'The player kicked the ball.',
      exampleTranslation: 'El jugador pateó la pelota.',
      status: 'approved',
    },
    {
      id: 'voc_a1_tear_001',
      word: 'tear',
      translation: 'rasgar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tɛr/',
      example: 'Be careful, don\'t tear the paper.',
      exampleTranslation: 'Ten cuidado, no rasgues el papel.',
      status: 'approved',
    },
    {
      id: 'voc_a1_fold_001',
      word: 'fold',
      translation: 'doblar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/foʊld/',
      example: 'Fold the clothes, please.',
      exampleTranslation: 'Dobla la ropa, por favor.',
      status: 'approved',
    },
    {
      id: 'voc_a1_wrap_001',
      word: 'wrap',
      translation: 'envolver',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ræp/',
      example: 'I need to wrap this gift.',
      exampleTranslation: 'Necesito envolver este regalo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_cover_001',
      word: 'cover',
      translation: 'cubrir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkʌvər/',
      example: 'Cover the food with a towel.',
      exampleTranslation: 'Cubre la comida con una toalla.',
      status: 'approved',
    },
    {
      id: 'voc_a1_hide_001',
      word: 'hide',
      translation: 'esconder',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/haɪd/',
      example: 'The cat likes to hide under the bed.',
      exampleTranslation: 'Al gato le gusta esconderse bajo la cama.',
      status: 'approved',
    },
    {
      id: 'voc_a1_show_001',
      word: 'show',
      translation: 'mostrar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ʃoʊ/',
      example: 'Show me your notebook.',
      exampleTranslation: 'Muéstrame tu cuaderno.',
      status: 'approved',
    },
    {
      id: 'voc_a1_point_001',
      word: 'point',
      translation: 'señalar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pɔɪnt/',
      example: 'She pointed at the map.',
      exampleTranslation: 'Ella señaló el mapa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_turn_001',
      word: 'turn',
      translation: 'girar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tɜrn/',
      example: 'Turn left at the corner.',
      exampleTranslation: 'Gira a la izquierda en la esquina.',
      status: 'approved',
    },
    {
      id: 'voc_a1_turn-on_001',
      word: 'turn on',
      translation: 'encender',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tɜrn ɑn/',
      example: 'Turn on the light, please.',
      exampleTranslation: 'Enciende la luz, por favor.',
      status: 'approved',
    },
    {
      id: 'voc_a1_turn-off_001',
      word: 'turn off',
      translation: 'apagar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tɜrn ɔf/',
      example: 'Turn off your phone in class.',
      exampleTranslation: 'Apaga tu teléfono en clase.',
      status: 'approved',
    },
    {
      id: 'voc_a1_mix_001',
      word: 'mix',
      translation: 'mezclar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/mɪks/',
      example: 'Mix the eggs and the flour.',
      exampleTranslation: 'Mezcla los huevos y la harina.',
      status: 'approved',
    },
    {
      id: 'voc_a1_add_001',
      word: 'add',
      translation: 'agregar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/æd/',
      example: 'Add a little salt.',
      exampleTranslation: 'Agrega un poco de sal.',
      status: 'approved',
    },
    {
      id: 'voc_a1_remove_001',
      word: 'remove',
      translation: 'quitar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rɪˈmuv/',
      example: 'Remove your shoes, please.',
      exampleTranslation: 'Quítate los zapatos, por favor.',
      status: 'approved',
    },
    {
      id: 'voc_a1_fill_001',
      word: 'fill',
      translation: 'llenar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fɪl/',
      example: 'Fill the glass with water.',
      exampleTranslation: 'Llena el vaso con agua.',
      status: 'approved',
    },
    {
      id: 'voc_a1_pour_001',
      word: 'pour',
      translation: 'verter',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pɔr/',
      example: 'Pour the juice into the cup.',
      exampleTranslation: 'Vierte el jugo en la taza.',
      status: 'approved',
    },
    {
      id: 'voc_a1_press_001',
      word: 'press',
      translation: 'presionar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/prɛs/',
      example: 'Press the button twice.',
      exampleTranslation: 'Presiona el botón dos veces.',
      status: 'approved',
    },
    {
      id: 'voc_a1_lift_001',
      word: 'lift',
      translation: 'levantar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/lɪft/',
      example: 'Lift the box carefully.',
      exampleTranslation: 'Levanta la caja con cuidado.',
      status: 'approved',
    },
    {
      id: 'voc_a1_drop_001',
      word: 'drop',
      translation: 'dejar caer',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/drɑp/',
      example: 'Don\'t drop the plate.',
      exampleTranslation: 'No dejes caer el plato.',
      status: 'approved',
    },
    {
      id: 'voc_a1_pick-up_001',
      word: 'pick up',
      translation: 'recoger',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pɪk ʌp/',
      example: 'Pick up your toys, please.',
      exampleTranslation: 'Recoge tus juguetes, por favor.',
      status: 'approved',
    },
    {
      id: 'voc_a1_set-up_001',
      word: 'set up',
      translation: 'instalar/organizar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/sɛt ʌp/',
      example: 'We set up the tent quickly.',
      exampleTranslation: 'Instalamos la tienda de campaña rápido.',
      status: 'approved',
    },
    {
      id: 'voc_a1_rise_001',
      word: 'rise',
      translation: 'subir/aumentar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/raɪz/',
      example: 'Prices rise every year.',
      exampleTranslation: 'Los precios suben cada año.',
      status: 'approved',
    },
    {
      id: 'voc_a1_fall_001',
      word: 'fall',
      translation: 'caer',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fɔl/',
      example: 'Leaves fall in autumn.',
      exampleTranslation: 'Las hojas caen en otoño.',
      status: 'approved',
    },
    {
      id: 'voc_a1_grow_001',
      word: 'grow',
      translation: 'crecer',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/groʊ/',
      example: 'Children grow very fast.',
      exampleTranslation: 'Los niños crecen muy rápido.',
      status: 'approved',
    },
    {
      id: 'voc_a1_increase_001',
      word: 'increase',
      translation: 'aumentar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪnˈkris/',
      example: 'The company will increase salaries.',
      exampleTranslation: 'La empresa aumentará los salarios.',
      status: 'approved',
    },
    {
      id: 'voc_a1_decrease_001',
      word: 'decrease',
      translation: 'disminuir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/diˈkris/',
      example: 'Sales decreased this month.',
      exampleTranslation: 'Las ventas disminuyeron este mes.',
      status: 'approved',
    },
    {
      id: 'voc_a1_change_002',
      word: 'change (verb)',
      translation: 'cambiar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tʃeɪndʒ/',
      example: 'I need to change my schedule.',
      exampleTranslation: 'Necesito cambiar mi horario.',
      status: 'approved',
    },
    {
      id: 'voc_a1_improve_001',
      word: 'improve',
      translation: 'mejorar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪmˈpruv/',
      example: 'She wants to improve her English.',
      exampleTranslation: 'Ella quiere mejorar su inglés.',
      status: 'approved',
    },
    {
      id: 'voc_a1_succeed_001',
      word: 'succeed',
      translation: 'tener éxito',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/səkˈsid/',
      example: 'He worked hard to succeed.',
      exampleTranslation: 'Él trabajó duro para tener éxito.',
      status: 'approved',
    },
    {
      id: 'voc_a1_fail_001',
      word: 'fail',
      translation: 'fallar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/feɪl/',
      example: 'I hope I don\'t fail the exam.',
      exampleTranslation: 'Espero no reprobar el examen.',
      status: 'approved',
    },
    {
      id: 'voc_a1_compete_001',
      word: 'compete',
      translation: 'competir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kəmˈpit/',
      example: 'Our team will compete this weekend.',
      exampleTranslation: 'Nuestro equipo competirá este fin de semana.',
      status: 'approved',
    },
    {
      id: 'voc_a1_practice_001',
      word: 'practice',
      translation: 'practicar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpræktɪs/',
      example: 'I practice English every day.',
      exampleTranslation: 'Practico inglés todos los días.',
      status: 'approved',
    },
    {
      id: 'voc_a1_prepare_001',
      word: 'prepare',
      translation: 'preparar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/prɪˈpɛr/',
      example: 'We need to prepare dinner.',
      exampleTranslation: 'Necesitamos preparar la cena.',
      status: 'approved',
    },
    {
      id: 'voc_a1_organize_001',
      word: 'organize',
      translation: 'organizar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɔrgəˌnaɪz/',
      example: 'Let\'s organize the closet.',
      exampleTranslation: 'Organicemos el armario.',
      status: 'approved',
    },
    {
      id: 'voc_a1_arrange_001',
      word: 'arrange',
      translation: 'arreglar/organizar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈreɪndʒ/',
      example: 'She arranged the flowers nicely.',
      exampleTranslation: 'Ella arregló las flores muy bien.',
      status: 'approved',
    },
    {
      id: 'voc_a1_collect_001',
      word: 'collect',
      translation: 'coleccionar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kəˈlɛkt/',
      example: 'He collects old coins.',
      exampleTranslation: 'Él colecciona monedas antiguas.',
      status: 'approved',
    },
    {
      id: 'voc_a1_gather_001',
      word: 'gather',
      translation: 'reunir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈgæðər/',
      example: 'We gathered around the table.',
      exampleTranslation: 'Nos reunimos alrededor de la mesa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_separate_001',
      word: 'separate',
      translation: 'separar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsɛpəˌreɪt/',
      example: 'Please separate the plastic and paper.',
      exampleTranslation: 'Por favor separa el plástico y el papel.',
      status: 'approved',
    },
    {
      id: 'voc_a1_connect_001',
      word: 'connect',
      translation: 'conectar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kəˈnɛkt/',
      example: 'Connect the cable to the TV.',
      exampleTranslation: 'Conecta el cable a la televisión.',
      status: 'approved',
    },
    {
      id: 'voc_a1_disconnect_001',
      word: 'disconnect',
      translation: 'desconectar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌdɪskəˈnɛkt/',
      example: 'Disconnect the printer before moving it.',
      exampleTranslation: 'Desconecta la impresora antes de moverla.',
      status: 'approved',
    },
    {
      id: 'voc_a1_join_001',
      word: 'join',
      translation: 'unirse',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dʒɔɪn/',
      example: 'Do you want to join our team?',
      exampleTranslation: '¿Quieres unirte a nuestro equipo?',
      status: 'approved',
    },
    {
      id: 'voc_a1_enter_001',
      word: 'enter',
      translation: 'entrar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɛntər/',
      example: 'Please enter through this door.',
      exampleTranslation: 'Por favor entra por esta puerta.',
      status: 'approved',
    },
    {
      id: 'voc_a1_exit_001',
      word: 'exit',
      translation: 'salir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɛgzɪt/',
      example: 'Exit through the back door.',
      exampleTranslation: 'Sal por la puerta trasera.',
      status: 'approved',
    },
    {
      id: 'voc_a1_idea_001',
      word: 'idea',
      translation: 'idea',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/aɪˈdiə/',
      example: 'That\'s a great idea.',
      exampleTranslation: 'Esa es una gran idea.',
      status: 'approved',
    },
    {
      id: 'voc_a1_opinion_001',
      word: 'opinion',
      translation: 'opinión',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈpɪnjən/',
      example: 'What is your opinion?',
      exampleTranslation: '¿Cuál es tu opinión?',
      status: 'approved',
    },
    {
      id: 'voc_a1_decision_001',
      word: 'decision',
      translation: 'decisión',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dɪˈsɪʒən/',
      example: 'It was a difficult decision.',
      exampleTranslation: 'Fue una decisión difícil.',
      status: 'approved',
    },
    {
      id: 'voc_a1_solution_001',
      word: 'solution',
      translation: 'solución',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/səˈluʃən/',
      example: 'We found a good solution.',
      exampleTranslation: 'Encontramos una buena solución.',
      status: 'approved',
    },
    {
      id: 'voc_a1_problem_001',
      word: 'problem',
      translation: 'problema',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈprɑbləm/',
      example: 'We have a small problem.',
      exampleTranslation: 'Tenemos un pequeño problema.',
      status: 'approved',
    },
    {
      id: 'voc_a1_reason_001',
      word: 'reason',
      translation: 'razón',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈrizən/',
      example: 'What is the reason for this?',
      exampleTranslation: '¿Cuál es la razón de esto?',
      status: 'approved',
    },
    {
      id: 'voc_a1_result_001',
      word: 'result',
      translation: 'resultado',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rɪˈzʌlt/',
      example: 'The result was excellent.',
      exampleTranslation: 'El resultado fue excelente.',
      status: 'approved',
    },
    {
      id: 'voc_a1_effect_001',
      word: 'effect',
      translation: 'efecto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪˈfɛkt/',
      example: 'The medicine had no effect.',
      exampleTranslation: 'La medicina no tuvo efecto.',
      status: 'approved',
    },
    {
      id: 'voc_a1_cause_001',
      word: 'cause',
      translation: 'causa',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kɔz/',
      example: 'We don\'t know the cause yet.',
      exampleTranslation: 'Todavía no sabemos la causa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_example_001',
      word: 'example',
      translation: 'ejemplo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪgˈzæmpəl/',
      example: 'Can you give me an example?',
      exampleTranslation: '¿Puedes darme un ejemplo?',
      status: 'approved',
    },
    {
      id: 'voc_a1_fact_001',
      word: 'fact',
      translation: 'hecho',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fækt/',
      example: 'That\'s an interesting fact.',
      exampleTranslation: 'Ese es un hecho interesante.',
      status: 'approved',
    },
    {
      id: 'voc_a1_information_001',
      word: 'information',
      translation: 'información',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌɪnfərˈmeɪʃən/',
      example: 'I need more information.',
      exampleTranslation: 'Necesito más información.',
      status: 'approved',
    },
    {
      id: 'voc_a1_rule_001',
      word: 'rule',
      translation: 'regla',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rul/',
      example: 'Every game has rules.',
      exampleTranslation: 'Todo juego tiene reglas.',
      status: 'approved',
    },
    {
      id: 'voc_a1_law_001',
      word: 'law',
      translation: 'ley',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/lɔ/',
      example: 'It\'s against the law.',
      exampleTranslation: 'Es contra la ley.',
      status: 'approved',
    },
    {
      id: 'voc_a1_permission_001',
      word: 'permission',
      translation: 'permiso',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pərˈmɪʃən/',
      example: 'I need your permission.',
      exampleTranslation: 'Necesito tu permiso.',
      status: 'approved',
    },
    {
      id: 'voc_a1_freedom_001',
      word: 'freedom',
      translation: 'libertad',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfridəm/',
      example: 'Freedom is important to me.',
      exampleTranslation: 'La libertad es importante para mí.',
      status: 'approved',
    },
    {
      id: 'voc_a1_responsibility_001',
      word: 'responsibility',
      translation: 'responsabilidad',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rɪˌspɑnsəˈbɪləti/',
      example: 'It\'s your responsibility now.',
      exampleTranslation: 'Es tu responsabilidad ahora.',
      status: 'approved',
    },
    {
      id: 'voc_a1_duty_001',
      word: 'duty',
      translation: 'deber',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈduti/',
      example: 'It\'s my duty to help.',
      exampleTranslation: 'Es mi deber ayudar.',
      status: 'approved',
    },
    {
      id: 'voc_a1_purpose_001',
      word: 'purpose',
      translation: 'propósito',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpɜrpəs/',
      example: 'What is the purpose of this meeting?',
      exampleTranslation: '¿Cuál es el propósito de esta reunión?',
      status: 'approved',
    },
    {
      id: 'voc_a1_project_001',
      word: 'project',
      translation: 'proyecto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈprɑdʒɛkt/',
      example: 'We finished the project on time.',
      exampleTranslation: 'Terminamos el proyecto a tiempo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_task_001',
      word: 'task',
      translation: 'tarea (labor)',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tæsk/',
      example: 'I have one more task to do.',
      exampleTranslation: 'Tengo una tarea más que hacer.',
      status: 'approved',
    },
    {
      id: 'voc_a1_effort_001',
      word: 'effort',
      translation: 'esfuerzo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɛfərt/',
      example: 'She made a big effort.',
      exampleTranslation: 'Ella hizo un gran esfuerzo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_chance_001',
      word: 'chance',
      translation: 'oportunidad/posibilidad',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tʃæns/',
      example: 'This is your chance.',
      exampleTranslation: 'Esta es tu oportunidad.',
      status: 'approved',
    },
    {
      id: 'voc_a1_opportunity_001',
      word: 'opportunity',
      translation: 'oportunidad',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌɑpərˈtunəti/',
      example: 'It was a great opportunity.',
      exampleTranslation: 'Fue una gran oportunidad.',
      status: 'approved',
    },
    {
      id: 'voc_a1_risk_001',
      word: 'risk',
      translation: 'riesgo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rɪsk/',
      example: 'There is a small risk.',
      exampleTranslation: 'Hay un pequeño riesgo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_success_001',
      word: 'success',
      translation: 'éxito',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/səkˈsɛs/',
      example: 'The event was a success.',
      exampleTranslation: 'El evento fue un éxito.',
      status: 'approved',
    },
    {
      id: 'voc_a1_failure_001',
      word: 'failure',
      translation: 'fracaso',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfeɪljər/',
      example: 'Failure taught him a lot.',
      exampleTranslation: 'El fracaso le enseñó mucho.',
      status: 'approved',
    },
    {
      id: 'voc_a1_mistake_001',
      word: 'mistake',
      translation: 'error',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/mɪˈsteɪk/',
      example: 'Everyone makes mistakes.',
      exampleTranslation: 'Todos cometemos errores.',
      status: 'approved',
    },
    {
      id: 'voc_a1_experience_001',
      word: 'experience',
      translation: 'experiencia',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪkˈspɪriəns/',
      example: 'It was a great experience.',
      exampleTranslation: 'Fue una gran experiencia.',
      status: 'approved',
    },
    {
      id: 'voc_a1_knowledge_001',
      word: 'knowledge',
      translation: 'conocimiento',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈnɑlɪdʒ/',
      example: 'She has a lot of knowledge.',
      exampleTranslation: 'Ella tiene mucho conocimiento.',
      status: 'approved',
    },
    {
      id: 'voc_a1_skill_001',
      word: 'skill',
      translation: 'habilidad',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/skɪl/',
      example: 'Cooking is a useful skill.',
      exampleTranslation: 'Cocinar es una habilidad útil.',
      status: 'approved',
    },
    {
      id: 'voc_a1_ability_001',
      word: 'ability',
      translation: 'capacidad',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈbɪləti/',
      example: 'He has the ability to lead.',
      exampleTranslation: 'Él tiene la capacidad de liderar.',
      status: 'approved',
    },
    {
      id: 'voc_a1_talent_001',
      word: 'talent',
      translation: 'talento',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtælənt/',
      example: 'She has real talent for music.',
      exampleTranslation: 'Ella tiene verdadero talento para la música.',
      status: 'approved',
    },
    {
      id: 'voc_a1_memory_001',
      word: 'memory',
      translation: 'memoria',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmɛməri/',
      example: 'I have a good memory.',
      exampleTranslation: 'Tengo buena memoria.',
      status: 'approved',
    },
    {
      id: 'voc_a1_imagination_001',
      word: 'imagination',
      translation: 'imaginación',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪˌmædʒəˈneɪʃən/',
      example: 'Children have great imagination.',
      exampleTranslation: 'Los niños tienen mucha imaginación.',
      status: 'approved',
    },
    {
      id: 'voc_a1_attention_001',
      word: 'attention',
      translation: 'atención',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈtɛnʃən/',
      example: 'Pay attention, please.',
      exampleTranslation: 'Presta atención, por favor.',
      status: 'approved',
    },
    {
      id: 'voc_a1_focus_001',
      word: 'focus',
      translation: 'concentración',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfoʊkəs/',
      example: 'I need more focus today.',
      exampleTranslation: 'Necesito más concentración hoy.',
      status: 'approved',
    },
    {
      id: 'voc_a1_courage_001',
      word: 'courage',
      translation: 'valentía',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkɜrɪdʒ/',
      example: 'It took courage to speak up.',
      exampleTranslation: 'Se necesitó valentía para hablar.',
      status: 'approved',
    },
    {
      id: 'voc_a1_fear_001',
      word: 'fear',
      translation: 'miedo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fɪr/',
      example: 'She has a fear of heights.',
      exampleTranslation: 'Ella tiene miedo a las alturas.',
      status: 'approved',
    },
    {
      id: 'voc_a1_faith_001',
      word: 'faith',
      translation: 'fe',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/feɪθ/',
      example: 'I have faith in you.',
      exampleTranslation: 'Tengo fe en ti.',
      status: 'approved',
    },
    {
      id: 'voc_a1_trust_001',
      word: 'trust',
      translation: 'confianza',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/trʌst/',
      example: 'Trust is important in a team.',
      exampleTranslation: 'La confianza es importante en un equipo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_doubt_001',
      word: 'doubt',
      translation: 'duda',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/daʊt/',
      example: 'I have some doubt about this.',
      exampleTranslation: 'Tengo algo de duda sobre esto.',
      status: 'approved',
    },
    {
      id: 'voc_a1_truth_001',
      word: 'truth',
      translation: 'verdad',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/truθ/',
      example: 'Please tell me the truth.',
      exampleTranslation: 'Por favor dime la verdad.',
      status: 'approved',
    },
    {
      id: 'voc_a1_lie_001',
      word: 'lie (noun)',
      translation: 'mentira',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/laɪ/',
      example: 'That was a lie.',
      exampleTranslation: 'Eso fue una mentira.',
      status: 'approved',
    },
    {
      id: 'voc_a1_secret_001',
      word: 'secret',
      translation: 'secreto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsikrɪt/',
      example: 'Can you keep a secret?',
      exampleTranslation: '¿Puedes guardar un secreto?',
      status: 'approved',
    },
    {
      id: 'voc_a1_agreement_001',
      word: 'agreement',
      translation: 'acuerdo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈgrimənt/',
      example: 'We reached an agreement.',
      exampleTranslation: 'Llegamos a un acuerdo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_conflict_001',
      word: 'conflict',
      translation: 'conflicto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkɑnflɪkt/',
      example: 'There was a conflict at work.',
      exampleTranslation: 'Hubo un conflicto en el trabajo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_peace_001',
      word: 'peace',
      translation: 'paz',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pis/',
      example: 'We want peace.',
      exampleTranslation: 'Queremos paz.',
      status: 'approved',
    },
    {
      id: 'voc_a1_war_001',
      word: 'war',
      translation: 'guerra',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/wɔr/',
      example: 'The war ended years ago.',
      exampleTranslation: 'La guerra terminó hace años.',
      status: 'approved',
    },
    {
      id: 'voc_a1_justice_001',
      word: 'justice',
      translation: 'justicia',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdʒʌstɪs/',
      example: 'They fought for justice.',
      exampleTranslation: 'Ellos lucharon por la justicia.',
      status: 'approved',
    },
    {
      id: 'voc_a1_equality_001',
      word: 'equality',
      translation: 'igualdad',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪˈkwɑləti/',
      example: 'Equality is a basic right.',
      exampleTranslation: 'La igualdad es un derecho básico.',
      status: 'approved',
    },
    {
      id: 'voc_a1_value_001',
      word: 'value',
      translation: 'valor',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈvælju/',
      example: 'Honesty is an important value.',
      exampleTranslation: 'La honestidad es un valor importante.',
      status: 'approved',
    },
  ],
}
