import type { ContentBlock } from '../types'

/**
 * A1 Level — Week 14
 * Topic: Semana 14 – Preposiciones, palabras de pregunta y conectores
 * Curated from: a.md
 * Total items: 55
 */
export const week14: ContentBlock = {
  level: 'A1',
  week: 14,
  topic: 'Semana 14 – Preposiciones, palabras de pregunta y conectores',
  vocabulary: [
    {
      id: 'voc_a1_in_001',
      word: 'in',
      translation: 'en',
      partOfSpeech: 'preposition',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪn/',
      example: 'The keys are in the drawer.',
      exampleTranslation: 'Las llaves están en el cajón.',
      status: 'approved',
    },
    {
      id: 'voc_a1_on_001',
      word: 'on',
      translation: 'sobre/en',
      partOfSpeech: 'preposition',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɔn/',
      example: 'The book is on the table.',
      exampleTranslation: 'El libro está sobre la mesa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_at_001',
      word: 'at',
      translation: 'en (lugar/hora)',
      partOfSpeech: 'preposition',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      example: 'We arrive at six o\'clock.',
      pronunciation: '/æt/',
      example: 'We arrive at six o\'clock.',
      exampleTranslation: 'Llegamos a las seis en punto.',
      status: 'approved',
    },
    {
      id: 'voc_a1_under_001',
      word: 'under',
      translation: 'debajo de',
      partOfSpeech: 'preposition',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈʌndər/',
      example: 'The cat is under the bed.',
      exampleTranslation: 'El gato está debajo de la cama.',
      status: 'approved',
    },
    {
      id: 'voc_a1_over_001',
      word: 'over',
      translation: 'sobre/encima de',
      partOfSpeech: 'preposition',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈoʊvər/',
      example: 'The bird flew over the house.',
      exampleTranslation: 'El pájaro voló sobre la casa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_above_001',
      word: 'above',
      translation: 'arriba de',
      partOfSpeech: 'preposition',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈbʌv/',
      example: 'The shelf is above the desk.',
      exampleTranslation: 'El estante está arriba del escritorio.',
      status: 'approved',
    },
    {
      id: 'voc_a1_below_001',
      word: 'below',
      translation: 'debajo de',
      partOfSpeech: 'preposition',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bɪˈloʊ/',
      example: 'The garage is below the apartment.',
      exampleTranslation: 'El garaje está debajo del apartamento.',
      status: 'approved',
    },
    {
      id: 'voc_a1_inside_001',
      word: 'inside',
      translation: 'dentro',
      partOfSpeech: 'preposition',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      example: 'Come inside, it\'s cold.',
      pronunciation: '/ɪnˈsaɪd/',
      example: 'Come inside, it\'s cold.',
      exampleTranslation: 'Entra, hace frío.',
      status: 'approved',
    },
    {
      id: 'voc_a1_outside_001',
      word: 'outside',
      translation: 'afuera',
      partOfSpeech: 'preposition',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈaʊtˈsaɪd/',
      example: 'The kids are playing outside.',
      exampleTranslation: 'Los niños están jugando afuera.',
      status: 'approved',
    },
    {
      id: 'voc_a1_up_001',
      word: 'up',
      translation: 'arriba',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ʌp/',
      example: 'Look up at the sky.',
      exampleTranslation: 'Mira hacia arriba, al cielo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_down_001',
      word: 'down',
      translation: 'abajo',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/daʊn/',
      example: 'Please sit down.',
      exampleTranslation: 'Por favor siéntate.',
      status: 'approved',
    },
    {
      id: 'voc_a1_into_001',
      word: 'into',
      translation: 'hacia dentro',
      partOfSpeech: 'preposition',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɪntu/',
      example: 'She walked into the room.',
      exampleTranslation: 'Ella entró a la habitación.',
      status: 'approved',
    },
    {
      id: 'voc_a1_onto_001',
      word: 'onto',
      translation: 'hacia encima',
      partOfSpeech: 'preposition',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɔntu/',
      example: 'The cat jumped onto the table.',
      exampleTranslation: 'El gato saltó sobre la mesa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_through_001',
      word: 'through',
      translation: 'a través de',
      partOfSpeech: 'preposition',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/θru/',
      example: 'We walked through the park.',
      exampleTranslation: 'Caminamos a través del parque.',
      status: 'approved',
    },
    {
      id: 'voc_a1_across_001',
      word: 'across',
      translation: 'a través de / cruzando',
      partOfSpeech: 'preposition',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈkrɔs/',
      example: 'The store is across the street.',
      exampleTranslation: 'La tienda está al otro lado de la calle.',
      status: 'approved',
    },
    {
      id: 'voc_a1_along_001',
      word: 'along',
      translation: 'a lo largo de',
      partOfSpeech: 'preposition',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈlɔŋ/',
      example: 'We walked along the beach.',
      exampleTranslation: 'Caminamos a lo largo de la playa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_around_001',
      word: 'around',
      translation: 'alrededor de',
      partOfSpeech: 'preposition',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈraʊnd/',
      example: 'We walked around the city.',
      exampleTranslation: 'Caminamos por toda la ciudad.',
      status: 'approved',
    },
    {
      id: 'voc_a1_during_001',
      word: 'during',
      translation: 'durante',
      partOfSpeech: 'preposition',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdʊrɪŋ/',
      example: 'It rained during the trip.',
      exampleTranslation: 'Llovió durante el viaje.',
      status: 'approved',
    },
    {
      id: 'voc_a1_for_001',
      word: 'for',
      translation: 'para/por',
      partOfSpeech: 'preposition',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fɔr/',
      example: 'This gift is for you.',
      exampleTranslation: 'Este regalo es para ti.',
      status: 'approved',
    },
    {
      id: 'voc_a1_with_001',
      word: 'with',
      translation: 'con',
      partOfSpeech: 'preposition',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/wɪθ/',
      example: 'I live with my family.',
      exampleTranslation: 'Vivo con mi familia.',
      status: 'approved',
    },
    {
      id: 'voc_a1_without_001',
      word: 'without',
      translation: 'sin',
      partOfSpeech: 'preposition',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      example: 'I can\'t sleep without music.',
      pronunciation: '/wɪˈθaʊt/',
      example: 'I can\'t sleep without music.',
      exampleTranslation: 'No puedo dormir sin música.',
      status: 'approved',
    },
    {
      id: 'voc_a1_about_001',
      word: 'about',
      translation: 'acerca de',
      partOfSpeech: 'preposition',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈbaʊt/',
      example: 'The movie is about a family.',
      exampleTranslation: 'La película es sobre una familia.',
      status: 'approved',
    },
    {
      id: 'voc_a1_against_001',
      word: 'against',
      translation: 'contra',
      partOfSpeech: 'preposition',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      example: 'Don\'t lean against the wall.',
      pronunciation: '/əˈgɛnst/',
      example: 'Don\'t lean against the wall.',
      exampleTranslation: 'No te recuestes contra la pared.',
      status: 'approved',
    },
    {
      id: 'voc_a1_toward_001',
      word: 'toward',
      translation: 'hacia',
      partOfSpeech: 'preposition',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tɔrd/',
      example: 'We walked toward the station.',
      exampleTranslation: 'Caminamos hacia la estación.',
      status: 'approved',
    },
    {
      id: 'voc_a1_whom_001',
      word: 'whom',
      translation: 'a quién',
      partOfSpeech: 'pronoun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/hum/',
      example: 'To whom did you give it?',
      exampleTranslation: '¿A quién se lo diste?',
      status: 'approved',
    },
    {
      id: 'voc_a1_whose_001',
      word: 'whose',
      translation: 'de quién',
      partOfSpeech: 'pronoun',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/huz/',
      example: 'Whose bag is this?',
      exampleTranslation: '¿De quién es esta bolsa?',
      status: 'approved',
    },
    {
      id: 'voc_a1_how-much_001',
      word: 'how much',
      translation: 'cuánto',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/haʊ mʌtʃ/',
      example: 'How much does this cost?',
      exampleTranslation: '¿Cuánto cuesta esto?',
      status: 'approved',
    },
    {
      id: 'voc_a1_how-many_001',
      word: 'how many',
      translation: 'cuántos',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/haʊ ˈmɛni/',
      example: 'How many people are coming?',
      exampleTranslation: '¿Cuántas personas vienen?',
      status: 'approved',
    },
    {
      id: 'voc_a1_how-often_001',
      word: 'how often',
      translation: 'con qué frecuencia',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/haʊ ˈɔfən/',
      example: 'How often do you exercise?',
      exampleTranslation: '¿Con qué frecuencia haces ejercicio?',
      status: 'approved',
    },
    {
      id: 'voc_a1_how-long_001',
      word: 'how long',
      translation: 'cuánto tiempo',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/haʊ lɔŋ/',
      example: 'How long is the movie?',
      exampleTranslation: '¿Cuánto dura la película?',
      status: 'approved',
    },
    {
      id: 'voc_a1_so_001',
      word: 'so',
      translation: 'así que',
      partOfSpeech: 'conjunction',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/soʊ/',
      example: 'It was late, so we went home.',
      exampleTranslation: 'Era tarde, así que nos fuimos a casa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_because_001',
      word: 'because',
      translation: 'porque',
      partOfSpeech: 'conjunction',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bɪˈkɔz/',
      example: 'I stayed home because I was sick.',
      exampleTranslation: 'Me quedé en casa porque estaba enfermo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_if_001',
      word: 'if',
      translation: 'si',
      partOfSpeech: 'conjunction',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪf/',
      example: 'If it rains, we will stay home.',
      exampleTranslation: 'Si llueve, nos quedaremos en casa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_although_001',
      word: 'although',
      translation: 'aunque',
      partOfSpeech: 'conjunction',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɔlˈðoʊ/',
      example: 'Although it was cold, we went out.',
      exampleTranslation: 'Aunque hacía frío, salimos.',
      status: 'approved',
    },
    {
      id: 'voc_a1_however_001',
      word: 'however',
      translation: 'sin embargo',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      example: 'I like the city; however, it\'s noisy.',
      pronunciation: '/haʊˈɛvər/',
      example: 'I like the city; however, it\'s noisy.',
      exampleTranslation: 'Me gusta la ciudad; sin embargo, es ruidosa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_also_001',
      word: 'also',
      translation: 'también',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɔlsoʊ/',
      example: 'She speaks English and also French.',
      exampleTranslation: 'Ella habla inglés y también francés.',
      status: 'approved',
    },
    {
      id: 'voc_a1_either_001',
      word: 'either',
      translation: 'tampoco/o',
      partOfSpeech: 'determiner',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      example: 'I don\'t like either option.',
      pronunciation: '/ˈiðər/',
      example: 'I don\'t like either option.',
      exampleTranslation: 'No me gusta ninguna de las dos opciones.',
      status: 'approved',
    },
    {
      id: 'voc_a1_neither_001',
      word: 'neither',
      translation: 'ni/tampoco',
      partOfSpeech: 'determiner',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈniðər/',
      example: 'Neither of us knew the answer.',
      exampleTranslation: 'Ninguno de los dos sabía la respuesta.',
      status: 'approved',
    },
    {
      id: 'voc_a1_both_001',
      word: 'both',
      translation: 'ambos',
      partOfSpeech: 'determiner',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/boʊθ/',
      example: 'Both of my brothers live here.',
      exampleTranslation: 'Mis dos hermanos viven aquí.',
      status: 'approved',
    },
    {
      id: 'voc_a1_all_001',
      word: 'all',
      translation: 'todo',
      partOfSpeech: 'determiner',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɔl/',
      example: 'All the students passed the exam.',
      exampleTranslation: 'Todos los estudiantes pasaron el examen.',
      status: 'approved',
    },
    {
      id: 'voc_a1_every_001',
      word: 'every',
      translation: 'cada',
      partOfSpeech: 'determiner',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɛvəri/',
      example: 'I brush my teeth every night.',
      exampleTranslation: 'Me cepillo los dientes todas las noches.',
      status: 'approved',
    },
    {
      id: 'voc_a1_each_001',
      word: 'each',
      translation: 'cada uno',
      partOfSpeech: 'determiner',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/itʃ/',
      example: 'Each student has a book.',
      exampleTranslation: 'Cada estudiante tiene un libro.',
      status: 'approved',
    },
    {
      id: 'voc_a1_some_001',
      word: 'some',
      translation: 'algo/algunos',
      partOfSpeech: 'determiner',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/sʌm/',
      example: 'I need some water.',
      exampleTranslation: 'Necesito un poco de agua.',
      status: 'approved',
    },
    {
      id: 'voc_a1_any_001',
      word: 'any',
      translation: 'alguno/ninguno',
      partOfSpeech: 'determiner',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɛni/',
      example: 'Do you have any questions?',
      exampleTranslation: '¿Tienes alguna pregunta?',
      status: 'approved',
    },
    {
      id: 'voc_a1_many_001',
      word: 'many',
      translation: 'muchos',
      partOfSpeech: 'determiner',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmɛni/',
      example: 'There are many people here.',
      exampleTranslation: 'Hay mucha gente aquí.',
      status: 'approved',
    },
    {
      id: 'voc_a1_much_001',
      word: 'much',
      translation: 'mucho',
      partOfSpeech: 'determiner',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      example: 'I don\'t have much time.',
      pronunciation: '/mʌtʃ/',
      example: 'I don\'t have much time.',
      exampleTranslation: 'No tengo mucho tiempo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_few_001',
      word: 'few',
      translation: 'pocos',
      partOfSpeech: 'determiner',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fju/',
      example: 'I have a few friends here.',
      exampleTranslation: 'Tengo algunos amigos aquí.',
      status: 'approved',
    },
    {
      id: 'voc_a1_little_001',
      word: 'little',
      translation: 'poco',
      partOfSpeech: 'determiner',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈlɪtəl/',
      example: 'There is little food left.',
      exampleTranslation: 'Queda poca comida.',
      status: 'approved',
    },
    {
      id: 'voc_a1_several_001',
      word: 'several',
      translation: 'varios',
      partOfSpeech: 'determiner',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsɛvərəl/',
      example: 'I have several ideas for the project.',
      exampleTranslation: 'Tengo varias ideas para el proyecto.',
      status: 'approved',
    },
    {
      id: 'voc_a1_other_001',
      word: 'other',
      translation: 'otro',
      partOfSpeech: 'determiner',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈʌðər/',
      example: 'I have no other choice.',
      exampleTranslation: 'No tengo otra opción.',
      status: 'approved',
    },
    {
      id: 'voc_a1_another_001',
      word: 'another',
      translation: 'otro (adicional)',
      partOfSpeech: 'determiner',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈnʌðər/',
      example: 'Can I have another coffee?',
      exampleTranslation: '¿Puedo tomar otro café?',
      status: 'approved',
    },
    {
      id: 'voc_a1_such_001',
      word: 'such',
      translation: 'tal',
      partOfSpeech: 'determiner',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/sʌtʃ/',
      example: 'It was such a good movie.',
      exampleTranslation: 'Fue una película tan buena.',
      status: 'approved',
    },
    {
      id: 'voc_a1_than_001',
      word: 'than',
      translation: 'que (comparación)',
      partOfSpeech: 'preposition',
      level: 'A1',
      week: 14,
      topic: 'preposiciones-palabras-de-pregunta-y-conector',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ðæn/',
      example: 'She is taller than me.',
      exampleTranslation: 'Ella es más alta que yo.',
      status: 'approved',
    },
  ],
}
