import type { ContentBlock } from '../types'

/**
 * A1 Level — Week 6
 * Topic: Semana 6 – Comida y bebidas
 * Curated from: a.md
 * Total items: 74
 */
export const week06: ContentBlock = {
  level: 'A1',
  week: 6,
  topic: 'Semana 6 – Comida y bebidas',
  vocabulary: [
    {
      id: 'voc_a1_bread_001',
      word: 'bread',
      translation: 'pan',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_rice_001',
      word: 'rice',
      translation: 'arroz',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_pasta_001',
      word: 'pasta',
      translation: 'pasta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_meat_001',
      word: 'meat',
      translation: 'carne',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_chicken_001',
      word: 'chicken',
      translation: 'pollo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_beef_001',
      word: 'beef',
      translation: 'carne de res',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_pork_001',
      word: 'pork',
      translation: 'cerdo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_fish_001',
      word: 'fish',
      translation: 'pescado',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_egg_001',
      word: 'egg',
      translation: 'huevo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_cheese_001',
      word: 'cheese',
      translation: 'queso',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_milk_001',
      word: 'milk',
      translation: 'leche',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_butter_001',
      word: 'butter',
      translation: 'mantequilla',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_sugar_001',
      word: 'sugar',
      translation: 'azúcar',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_salt_001',
      word: 'salt',
      translation: 'sal',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_pepper_001',
      word: 'pepper (spice)',
      translation: 'pimienta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_oil_001',
      word: 'oil',
      translation: 'aceite',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_water_001',
      word: 'water',
      translation: 'agua',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_juice_001',
      word: 'juice',
      translation: 'jugo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_coffee_001',
      word: 'coffee',
      translation: 'café',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_tea_001',
      word: 'tea',
      translation: 'té',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_wine_001',
      word: 'wine',
      translation: 'vino',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_beer_001',
      word: 'beer',
      translation: 'cerveza',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_soda_001',
      word: 'soda',
      translation: 'refresco',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_apple_001',
      word: 'apple',
      translation: 'manzana',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_banana_001',
      word: 'banana',
      translation: 'banana',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_orange_002',
      word: 'orange (fruit)',
      translation: 'naranja (fruta)',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_grape_001',
      word: 'grape',
      translation: 'uva',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_strawberry_001',
      word: 'strawberry',
      translation: 'fresa',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_lemon_001',
      word: 'lemon',
      translation: 'limón',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_watermelon_001',
      word: 'watermelon',
      translation: 'sandía',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_pineapple_001',
      word: 'pineapple',
      translation: 'piña',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_mango_001',
      word: 'mango',
      translation: 'mango',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_pear_001',
      word: 'pear',
      translation: 'pera',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_peach_001',
      word: 'peach',
      translation: 'durazno',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_cherry_001',
      word: 'cherry',
      translation: 'cereza',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_potato_001',
      word: 'potato',
      translation: 'papa',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_tomato_001',
      word: 'tomato',
      translation: 'tomate',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_onion_001',
      word: 'onion',
      translation: 'cebolla',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_carrot_001',
      word: 'carrot',
      translation: 'zanahoria',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_lettuce_001',
      word: 'lettuce',
      translation: 'lechuga',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_cucumber_001',
      word: 'cucumber',
      translation: 'pepino',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_corn_001',
      word: 'corn',
      translation: 'maíz',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_garlic_001',
      word: 'garlic',
      translation: 'ajo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_broccoli_001',
      word: 'broccoli',
      translation: 'brócoli',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_pea_001',
      word: 'pea',
      translation: 'guisante',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_breakfast_001',
      word: 'breakfast',
      translation: 'desayuno',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_lunch_001',
      word: 'lunch',
      translation: 'almuerzo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_dinner_001',
      word: 'dinner',
      translation: 'cena',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_snack_001',
      word: 'snack',
      translation: 'merienda',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_meal_001',
      word: 'meal',
      translation: 'comida',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_food_001',
      word: 'food',
      translation: 'comida/alimento',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_drink_001',
      word: 'drink',
      translation: 'bebida',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_delicious_001',
      word: 'delicious',
      translation: 'delicioso',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_tasty_001',
      word: 'tasty',
      translation: 'sabroso',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_sweet_001',
      word: 'sweet',
      translation: 'dulce',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_sour_001',
      word: 'sour',
      translation: 'agrio',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_bitter_001',
      word: 'bitter',
      translation: 'amargo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_spicy_001',
      word: 'spicy',
      translation: 'picante',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_fresh_001',
      word: 'fresh',
      translation: 'fresco',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_cooked_001',
      word: 'cooked',
      translation: 'cocinado',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_raw_001',
      word: 'raw',
      translation: 'crudo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_restaurant_001',
      word: 'restaurant',
      translation: 'restaurante',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_menu_001',
      word: 'menu',
      translation: 'menú',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_waiter-waitress_001',
      word: 'waiter / waitress',
      translation: 'mesero/a',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_bill_001',
      word: 'bill (check)',
      translation: 'cuenta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_order_001',
      word: 'order (food)',
      translation: 'pedir/pedido',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_cook_001',
      word: 'cook (person)',
      translation: 'cocinero',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_chef_001',
      word: 'chef',
      translation: 'chef',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_eat_001',
      word: 'eat',
      translation: 'comer',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_drink_002',
      word: 'drink (verb)',
      translation: 'beber',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_cook_002',
      word: 'cook (verb)',
      translation: 'cocinar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_buy_001',
      word: 'buy',
      translation: 'comprar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_cut_001',
      word: 'cut',
      translation: 'cortar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_taste_001',
      word: 'taste (verb)',
      translation: 'probar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
  ],
}
