import type { ContentBlock } from '../types'

/**
 * A1 Level — Week 1
 * Topic: Semana 1 – Pronombres, verbos SER/ESTAR/TENER/HACER y saludos
 * Curated from: a.md
 * Total items: 96
 */
export const week01: ContentBlock = {
  level: 'A1',
  week: 1,
  topic: 'Semana 1 – Pronombres, verbos SER/ESTAR/TENER/HACER y saludos',
  vocabulary: [
    {
      id: 'voc_a1_i_001',
      word: 'I',
      translation: 'yo',
      partOfSpeech: 'pronoun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/aɪ/',
      example: 'I am a student.',
      exampleTranslation: 'Yo soy estudiante.',
      status: 'approved',
    },
    {
      id: 'voc_a1_you_001',
      word: 'you',
      translation: 'tú / usted',
      partOfSpeech: 'pronoun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/juː/',
      example: 'You are my friend.',
      exampleTranslation: 'Tú eres mi amigo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_he_001',
      word: 'he',
      translation: 'él',
      partOfSpeech: 'pronoun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/hiː/',
      example: 'He is tall.',
      exampleTranslation: 'Él es alto.',
      status: 'approved',
    },
    {
      id: 'voc_a1_she_001',
      word: 'she',
      translation: 'ella',
      partOfSpeech: 'pronoun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ʃiː/',
      example: 'She lives in Mexico.',
      exampleTranslation: 'Ella vive en México.',
      status: 'approved',
    },
    {
      id: 'voc_a1_it_001',
      word: 'it',
      translation: 'eso / ello',
      partOfSpeech: 'pronoun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪt/',
      example: 'It is a sunny day.',
      exampleTranslation: 'Es un día soleado.',
      status: 'approved',
    },
    {
      id: 'voc_a1_we_001',
      word: 'we',
      translation: 'nosotros',
      partOfSpeech: 'pronoun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/wiː/',
      example: 'We are happy today.',
      exampleTranslation: 'Estamos felices hoy.',
      status: 'approved',
    },
    {
      id: 'voc_a1_they_001',
      word: 'they',
      translation: 'ellos',
      partOfSpeech: 'pronoun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ðeɪ/',
      example: 'They are my brothers.',
      exampleTranslation: 'Ellos son mis hermanos.',
      status: 'approved',
    },
    {
      id: 'voc_a1_my_001',
      word: 'my',
      translation: 'mi',
      partOfSpeech: 'determiner',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/maɪ/',
      example: 'This is my house.',
      exampleTranslation: 'Esta es mi casa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_your_001',
      word: 'your',
      translation: 'tu',
      partOfSpeech: 'determiner',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/jɔːr/',
      example: 'What is your name?',
      exampleTranslation: '¿Cuál es tu nombre?',
      status: 'approved',
    },
    {
      id: 'voc_a1_his_001',
      word: 'his',
      translation: 'su (de él)',
      partOfSpeech: 'pronoun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/hɪz/',
      example: 'His car is blue.',
      exampleTranslation: 'Su carro es azul.',
      status: 'approved',
    },
    {
      id: 'voc_a1_her_001',
      word: 'her',
      translation: 'su (de ella)',
      partOfSpeech: 'determiner',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/hɜːr/',
      example: 'Her sister is a teacher.',
      exampleTranslation: 'Su hermana es maestra.',
      status: 'approved',
    },
    {
      id: 'voc_a1_its_001',
      word: 'its',
      translation: 'su (de eso)',
      partOfSpeech: 'determiner',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪts/',
      example: 'The cat licked its paw.',
      exampleTranslation: 'El gato lamió su pata.',
      status: 'approved',
    },
    {
      id: 'voc_a1_our_001',
      word: 'our',
      translation: 'nuestro',
      partOfSpeech: 'determiner',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈaʊər/',
      example: 'Our house is near the school.',
      exampleTranslation: 'Nuestra casa está cerca de la escuela.',
      status: 'approved',
    },
    {
      id: 'voc_a1_their_001',
      word: 'their',
      translation: 'su (de ellos)',
      partOfSpeech: 'determiner',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ðɛr/',
      example: 'Their office is closed.',
      exampleTranslation: 'Su oficina está cerrada.',
      status: 'approved',
    },
    {
      id: 'voc_a1_mine_001',
      word: 'mine',
      translation: 'mío',
      partOfSpeech: 'pronoun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/maɪn/',
      example: 'This book is mine.',
      exampleTranslation: 'Este libro es mío.',
      status: 'approved',
    },
    {
      id: 'voc_a1_this_001',
      word: 'this',
      translation: 'este/esto',
      partOfSpeech: 'pronoun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ðɪs/',
      example: 'This is my brother.',
      exampleTranslation: 'Este es mi hermano.',
      status: 'approved',
    },
    {
      id: 'voc_a1_that_001',
      word: 'that',
      translation: 'ese/eso',
      partOfSpeech: 'pronoun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ðæt/',
      example: 'That house is very big.',
      exampleTranslation: 'Esa casa es muy grande.',
      status: 'approved',
    },
    {
      id: 'voc_a1_these_001',
      word: 'these',
      translation: 'estos',
      partOfSpeech: 'pronoun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ðiːz/',
      example: 'These shoes are comfortable.',
      exampleTranslation: 'Estos zapatos son cómodos.',
      status: 'approved',
    },
    {
      id: 'voc_a1_those_001',
      word: 'those',
      translation: 'esos',
      partOfSpeech: 'pronoun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ðoʊz/',
      example: 'Those trees are tall.',
      exampleTranslation: 'Esos árboles son altos.',
      status: 'approved',
    },
    {
      id: 'voc_a1_am_001',
      word: 'am',
      translation: 'soy/estoy',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/æm/',
      example: 'I am from Canada.',
      exampleTranslation: 'Soy de Canadá.',
      status: 'approved',
    },
    {
      id: 'voc_a1_is_001',
      word: 'is',
      translation: 'es/está',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪz/',
      example: 'She is a doctor.',
      exampleTranslation: 'Ella es médica.',
      status: 'approved',
    },
    {
      id: 'voc_a1_are_001',
      word: 'are',
      translation: 'son/están',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɑːr/',
      example: 'They are at home.',
      exampleTranslation: 'Ellos están en casa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_was_001',
      word: 'was',
      translation: 'era/estaba',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/wʌz/',
      example: 'He was happy yesterday.',
      exampleTranslation: 'Él estaba feliz ayer.',
      status: 'approved',
    },
    {
      id: 'voc_a1_were_001',
      word: 'were',
      translation: 'eran/estaban',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/wɜːr/',
      example: 'They were in the park.',
      exampleTranslation: 'Ellos estaban en el parque.',
      status: 'approved',
    },
    {
      id: 'voc_a1_be_001',
      word: 'be',
      translation: 'ser/estar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/biː/',
      example: 'You should be patient.',
      exampleTranslation: 'Deberías ser paciente.',
      status: 'approved',
    },
    {
      id: 'voc_a1_been_001',
      word: 'been',
      translation: 'sido/estado',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bɪn/',
      example: 'I have been busy today.',
      exampleTranslation: 'He estado ocupado hoy.',
      status: 'approved',
    },
    {
      id: 'voc_a1_being_001',
      word: 'being',
      translation: 'siendo',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbiːɪŋ/',
      example: 'She is being very polite.',
      exampleTranslation: 'Ella está siendo muy educada.',
      status: 'approved',
    },
    {
      id: 'voc_a1_have_001',
      word: 'have',
      translation: 'tener',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/hæv/',
      example: 'I have two brothers.',
      exampleTranslation: 'Tengo dos hermanos.',
      status: 'approved',
    },
    {
      id: 'voc_a1_has_001',
      word: 'has',
      translation: 'tiene',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/hæz/',
      example: 'She has two dogs.',
      exampleTranslation: 'Ella tiene dos perros.',
      status: 'approved',
    },
    {
      id: 'voc_a1_had_001',
      word: 'had',
      translation: 'tenía/tuvo',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/hæd/',
      example: 'We had a good time.',
      exampleTranslation: 'La pasamos bien.',
      status: 'approved',
    },
    {
      id: 'voc_a1_having_001',
      word: 'having',
      translation: 'teniendo',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈhævɪŋ/',
      example: 'They are having lunch.',
      exampleTranslation: 'Ellos están almorzando.',
      status: 'approved',
    },
    {
      id: 'voc_a1_do_001',
      word: 'do',
      translation: 'hacer',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/duː/',
      example: 'I do my homework every day.',
      exampleTranslation: 'Hago mi tarea todos los días.',
      status: 'approved',
    },
    {
      id: 'voc_a1_does_001',
      word: 'does',
      translation: 'hace',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dʌz/',
      example: 'He does his homework every evening.',
      exampleTranslation: 'Él hace su tarea cada noche.',
      status: 'approved',
    },
    {
      id: 'voc_a1_did_001',
      word: 'did',
      translation: 'hizo',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dɪd/',
      example: 'She did the dishes.',
      exampleTranslation: 'Ella lavó los platos.',
      status: 'approved',
    },
    {
      id: 'voc_a1_doing_001',
      word: 'doing',
      translation: 'haciendo',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈduːɪŋ/',
      example: 'What are you doing now?',
      exampleTranslation: '¿Qué estás haciendo ahora?',
      status: 'approved',
    },
    {
      id: 'voc_a1_done_001',
      word: 'done',
      translation: 'hecho',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dʌn/',
      example: 'The project is finally done.',
      exampleTranslation: 'El proyecto finalmente está terminado.',
      status: 'approved',
    },
    {
      id: 'voc_a1_hello_001',
      word: 'hello',
      translation: 'hola',
      partOfSpeech: 'interjection',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/həˈloʊ/',
      example: 'Hello, how are you?',
      exampleTranslation: 'Hola, ¿cómo estás?',
      status: 'approved',
    },
    {
      id: 'voc_a1_hi_001',
      word: 'hi',
      translation: 'hola',
      partOfSpeech: 'interjection',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/haɪ/',
      example: 'Hi, how can I help you?',
      exampleTranslation: 'Hola, ¿cómo te puedo ayudar?',
      status: 'approved',
    },
    {
      id: 'voc_a1_goodbye_001',
      word: 'goodbye',
      translation: 'adiós',
      partOfSpeech: 'interjection',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌɡʊdˈbaɪ/',
      example: 'Goodbye, see you tomorrow.',
      exampleTranslation: 'Adiós, nos vemos mañana.',
      status: 'approved',
    },
    {
      id: 'voc_a1_bye_001',
      word: 'bye',
      translation: 'chao',
      partOfSpeech: 'interjection',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/baɪ/',
      example: 'Bye, see you tomorrow!',
      exampleTranslation: '¡Chao, nos vemos mañana!',
      status: 'approved',
    },
    {
      id: 'voc_a1_good-morning_001',
      word: 'good morning',
      translation: 'buenos días',
      partOfSpeech: 'interjection',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɡʊd ˈmɔːrnɪŋ/',
      example: 'Good morning, everyone!',
      exampleTranslation: '¡Buenos días a todos!',
      status: 'approved',
    },
    {
      id: 'voc_a1_good-afternoon_001',
      word: 'good afternoon',
      translation: 'buenas tardes',
      partOfSpeech: 'interjection',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌɡʊd ˌæftərˈnuːn/',
      example: 'Good afternoon, Mr. Davis.',
      exampleTranslation: 'Buenas tardes, señor Davis.',
      status: 'approved',
    },
    {
      id: 'voc_a1_good-evening_001',
      word: 'good evening',
      translation: 'buenas noches (saludo)',
      partOfSpeech: 'interjection',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌɡʊd ˈiːvnɪŋ/',
      example: 'Good evening, welcome to our restaurant.',
      exampleTranslation: 'Buenas noches, bienvenidos a nuestro restaurante.',
      status: 'approved',
    },
    {
      id: 'voc_a1_good-night_001',
      word: 'good night',
      translation: 'buenas noches (despedida)',
      partOfSpeech: 'interjection',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌɡʊd ˈnaɪt/',
      example: 'Good night, sleep well.',
      exampleTranslation: 'Buenas noches, que duermas bien.',
      status: 'approved',
    },
    {
      id: 'voc_a1_please_001',
      word: 'please',
      translation: 'por favor',
      partOfSpeech: 'interjection',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pliːz/',
      example: 'Please, sit down.',
      exampleTranslation: 'Por favor, siéntate.',
      status: 'approved',
    },
    {
      id: 'voc_a1_thank-you_001',
      word: 'thank you',
      translation: 'gracias',
      partOfSpeech: 'interjection',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/θæŋk juː/',
      example: 'Thank you for your help.',
      exampleTranslation: 'Gracias por tu ayuda.',
      status: 'approved',
    },
    {
      id: 'voc_a1_thanks_001',
      word: 'thanks',
      translation: 'gracias',
      partOfSpeech: 'interjection',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/θæŋks/',
      example: 'Thanks for your assistance.',
      exampleTranslation: 'Gracias por tu ayuda.',
      status: 'approved',
    },
    {
      id: 'voc_a1_sorry_001',
      word: 'sorry',
      translation: 'perdón',
      partOfSpeech: 'interjection',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsɑːri/',
      example: 'Sorry, I am late.',
      exampleTranslation: 'Perdón, llego tarde.',
      status: 'approved',
    },
    {
      id: 'voc_a1_excuse-me_001',
      word: 'excuse me',
      translation: 'disculpe',
      partOfSpeech: 'interjection',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪkˈskjuːz miː/',
      example: 'Excuse me, where is the station?',
      exampleTranslation: 'Disculpe, ¿dónde está la estación?',
      status: 'approved',
    },
    {
      id: 'voc_a1_yes_001',
      word: 'yes',
      translation: 'sí',
      partOfSpeech: 'interjection',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/jɛs/',
      example: 'Yes, I understand.',
      exampleTranslation: 'Sí, entiendo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_no_001',
      word: 'no',
      translation: 'no',
      partOfSpeech: 'interjection',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/noʊ/',
      example: 'No, I don\'t have time.',
      exampleTranslation: 'No, no tengo tiempo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_ok_001',
      word: 'ok',
      translation: 'de acuerdo',
      partOfSpeech: 'interjection',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/oʊˈkeɪ/',
      example: 'Is it ok if I call you later?',
      exampleTranslation: '¿Está bien si te llamo más tarde?',
      status: 'approved',
    },
    {
      id: 'voc_a1_welcome_001',
      word: 'welcome',
      translation: 'bienvenido',
      partOfSpeech: 'interjection',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈwɛlkəm/',
      example: 'Welcome to our team.',
      exampleTranslation: 'Bienvenido a nuestro equipo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_nice-to-meet-you_001',
      word: 'nice to meet you',
      translation: 'mucho gusto',
      partOfSpeech: 'interjection',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌnaɪs tu ˈmiːt ju/',
      example: 'Hello Sarah, nice to meet you.',
      exampleTranslation: 'Hola Sarah, mucho gusto.',
      status: 'approved',
    },
    {
      id: 'voc_a1_how-are-you_001',
      word: 'how are you',
      translation: '¿cómo estás?',
      partOfSpeech: 'interjection',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌhaʊ ɑːr ˈjuː/',
      example: 'How are you feeling today?',
      exampleTranslation: '¿Cómo te sientes hoy?',
      status: 'approved',
    },
    {
      id: 'voc_a1_fine_001',
      word: 'fine',
      translation: 'bien',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/faɪn/',
      example: 'I am fine, thank you.',
      exampleTranslation: 'Estoy bien, gracias.',
      status: 'approved',
    },
    {
      id: 'voc_a1_one_001',
      word: 'one',
      translation: 'uno',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/wʌn/',
      example: 'I have one sister.',
      exampleTranslation: 'Tengo una hermana.',
      status: 'approved',
    },
    {
      id: 'voc_a1_two_001',
      word: 'two',
      translation: 'dos',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tuː/',
      example: 'I have two tickets for the concert.',
      exampleTranslation: 'Tengo dos boletos para el concierto.',
      status: 'approved',
    },
    {
      id: 'voc_a1_three_001',
      word: 'three',
      translation: 'tres',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/θriː/',
      example: 'We have three meetings today.',
      exampleTranslation: 'Tenemos tres reuniones hoy.',
      status: 'approved',
    },
    {
      id: 'voc_a1_four_001',
      word: 'four',
      translation: 'cuatro',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fɔːr/',
      example: 'There are four chairs around the table.',
      exampleTranslation: 'Hay cuatro sillas alrededor de la mesa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_five_001',
      word: 'five',
      translation: 'cinco',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/faɪv/',
      example: 'She works five days a week.',
      exampleTranslation: 'Ella trabaja cinco días a la semana.',
      status: 'approved',
    },
    {
      id: 'voc_a1_six_001',
      word: 'six',
      translation: 'seis',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/sɪks/',
      example: 'The store opens at six in the morning.',
      exampleTranslation: 'La tienda abre a las seis de la mañana.',
      status: 'approved',
    },
    {
      id: 'voc_a1_seven_001',
      word: 'seven',
      translation: 'siete',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsɛvən/',
      example: 'He has seven cousins in California.',
      exampleTranslation: 'Él tiene siete primos en California.',
      status: 'approved',
    },
    {
      id: 'voc_a1_eight_001',
      word: 'eight',
      translation: 'ocho',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/eɪt/',
      example: 'The train leaves at eight o\'clock.',
      exampleTranslation: 'El tren sale a las ocho en punto.',
      status: 'approved',
    },
    {
      id: 'voc_a1_nine_001',
      word: 'nine',
      translation: 'nueve',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/naɪn/',
      example: 'She bought nine apples at the market.',
      exampleTranslation: 'Ella compró nueve manzanas en el mercado.',
      status: 'approved',
    },
    {
      id: 'voc_a1_ten_001',
      word: 'ten',
      translation: 'diez',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tɛn/',
      example: 'The bus arrives in ten minutes.',
      exampleTranslation: 'El autobús llega en diez minutos.',
      status: 'approved',
    },
    {
      id: 'voc_a1_eleven_001',
      word: 'eleven',
      translation: 'once',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪˈlɛvən/',
      example: 'There are eleven players on each soccer team.',
      exampleTranslation: 'Hay once jugadores en cada equipo de fútbol.',
      status: 'approved',
    },
    {
      id: 'voc_a1_twelve_001',
      word: 'twelve',
      translation: 'doce',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/twɛlv/',
      example: 'A year has twelve months.',
      exampleTranslation: 'Un año tiene doce meses.',
      status: 'approved',
    },
    {
      id: 'voc_a1_thirteen_001',
      word: 'thirteen',
      translation: 'trece',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌθɜːrˈtiːn/',
      example: 'My daughter turns thirteen next month.',
      exampleTranslation: 'Mi hija cumple trece años el próximo mes.',
      status: 'approved',
    },
    {
      id: 'voc_a1_fourteen_001',
      word: 'fourteen',
      translation: 'catorce',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌfɔːrˈtiːn/',
      example: 'The trip lasted fourteen days.',
      exampleTranslation: 'El viaje duró catorce días.',
      status: 'approved',
    },
    {
      id: 'voc_a1_fifteen_001',
      word: 'fifteen',
      translation: 'quince',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌfɪfˈtiːn/',
      example: 'The bus arrives in fifteen minutes.',
      exampleTranslation: 'El autobús llega en quince minutos.',
      status: 'approved',
    },
    {
      id: 'voc_a1_sixteen_001',
      word: 'sixteen',
      translation: 'dieciséis',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌsɪksˈtiːn/',
      example: 'You can drive when you are sixteen.',
      exampleTranslation: 'Puedes conducir cuando tienes dieciséis años.',
      status: 'approved',
    },
    {
      id: 'voc_a1_seventeen_001',
      word: 'seventeen',
      translation: 'diecisiete',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌsɛvənˈtiːn/',
      example: 'There are seventeen students in the class.',
      exampleTranslation: 'Hay diecisiete estudiantes en la clase.',
      status: 'approved',
    },
    {
      id: 'voc_a1_eighteen_001',
      word: 'eighteen',
      translation: 'dieciocho',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌeɪˈtiːn/',
      example: 'He became an adult at eighteen.',
      exampleTranslation: 'Él se convirtió en adulto a los dieciocho años.',
      status: 'approved',
    },
    {
      id: 'voc_a1_nineteen_001',
      word: 'nineteen',
      translation: 'diecinueve',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌnaɪnˈtiːn/',
      example: 'Room nineteen is on the second floor.',
      exampleTranslation: 'La habitación diecinueve está en el segundo piso.',
      status: 'approved',
    },
    {
      id: 'voc_a1_twenty_001',
      word: 'twenty',
      translation: 'veinte',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtwɛnti/',
      example: 'I walked twenty blocks this morning.',
      exampleTranslation: 'Caminé veinte cuadras esta mañana.',
      status: 'approved',
    },
    {
      id: 'voc_a1_what_001',
      word: 'what',
      translation: 'qué',
      partOfSpeech: 'pronoun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/wʌt/',
      example: 'What is your name?',
      exampleTranslation: '¿Cómo te llamas?',
      status: 'approved',
    },
    {
      id: 'voc_a1_who_001',
      word: 'who',
      translation: 'quién',
      partOfSpeech: 'pronoun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/huː/',
      example: 'Who is the manager of this store?',
      exampleTranslation: '¿Quién es el gerente de esta tienda?',
      status: 'approved',
    },
    {
      id: 'voc_a1_where_001',
      word: 'where',
      translation: 'dónde',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/wɛr/',
      example: 'Where do you live?',
      exampleTranslation: '¿Dónde vives?',
      status: 'approved',
    },
    {
      id: 'voc_a1_when_001',
      word: 'when',
      translation: 'cuándo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/wɛn/',
      example: 'When does the class start?',
      exampleTranslation: '¿Cuándo empieza la clase?',
      status: 'approved',
    },
    {
      id: 'voc_a1_why_001',
      word: 'why',
      translation: 'por qué',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/waɪ/',
      example: 'Why is the door locked?',
      exampleTranslation: '¿Por qué está cerrada la puerta?',
      status: 'approved',
    },
    {
      id: 'voc_a1_how_001',
      word: 'how',
      translation: 'cómo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/haʊ/',
      example: 'How do you spell your last name?',
      exampleTranslation: '¿Cómo se escribe tu apellido?',
      status: 'approved',
    },
    {
      id: 'voc_a1_which_001',
      word: 'which',
      translation: 'cuál',
      partOfSpeech: 'pronoun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/wɪtʃ/',
      example: 'Which bus goes to downtown?',
      exampleTranslation: '¿Cuál autobús va al centro?',
      status: 'approved',
    },
    {
      id: 'voc_a1_name_001',
      word: 'name',
      translation: 'nombre',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/neɪm/',
      example: 'Please write your full name here.',
      exampleTranslation: 'Por favor escribe tu nombre completo aquí.',
      status: 'approved',
    },
    {
      id: 'voc_a1_age_001',
      word: 'age',
      translation: 'edad',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/eɪdʒ/',
      example: 'State your age on the application form.',
      exampleTranslation: 'Indica tu edad en el formulario de solicitud.',
      status: 'approved',
    },
    {
      id: 'voc_a1_and_001',
      word: 'and',
      translation: 'y',
      partOfSpeech: 'conjunction',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ænd/',
      example: 'She likes coffee and tea.',
      exampleTranslation: 'A ella le gusta el café y el té.',
      status: 'approved',
    },
    {
      id: 'voc_a1_or_001',
      word: 'or',
      translation: 'o',
      partOfSpeech: 'conjunction',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɔːr/',
      example: 'Do you prefer morning or afternoon?',
      exampleTranslation: '¿Prefieres la mañana o la tarde?',
      status: 'approved',
    },
    {
      id: 'voc_a1_but_001',
      word: 'but',
      translation: 'pero',
      partOfSpeech: 'conjunction',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bʌt/',
      example: 'The hotel was small but clean.',
      exampleTranslation: 'El hotel era pequeño pero limpio.',
      status: 'approved',
    },
    {
      id: 'voc_a1_a_001',
      word: 'a',
      translation: 'un/una',
      partOfSpeech: 'article',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ə/',
      example: 'He is reading a fascinating book.',
      exampleTranslation: 'Él está leyendo un libro fascinante.',
      status: 'approved',
    },
    {
      id: 'voc_a1_an_001',
      word: 'an',
      translation: 'un/una (ante vocal)',
      partOfSpeech: 'article',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/æn/',
      example: 'She ate an apple before working out.',
      exampleTranslation: 'Ella comió una manzana antes de entrenar.',
      status: 'approved',
    },
    {
      id: 'voc_a1_the_001',
      word: 'the',
      translation: 'el/la',
      partOfSpeech: 'article',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ðə/',
      example: 'The weather is great today.',
      exampleTranslation: 'El clima está excelente hoy.',
      status: 'approved',
    },
    {
      id: 'voc_a1_not_001',
      word: 'not',
      translation: 'no',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/nɑːt/',
      example: 'I am not available this afternoon.',
      exampleTranslation: 'No estoy disponible esta tarde.',
      status: 'approved',
    },
    {
      id: 'voc_a1_very_001',
      word: 'very',
      translation: 'muy',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈvɛri/',
      example: 'The coffee is very hot.',
      exampleTranslation: 'El café está muy caliente.',
      status: 'approved',
    },
    {
      id: 'voc_a1_too_001',
      word: 'too',
      translation: 'también',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tuː/',
      example: 'The shoes are too tight for me.',
      exampleTranslation: 'Los zapatos son demasiado apretados para mí.',
      status: 'approved',
    },
    {
      id: 'voc_a1_here_001',
      word: 'here',
      translation: 'aquí',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/hɪr/',
      example: 'Please sign your name right here.',
      exampleTranslation: 'Por favor firma tu nombre justo aquí.',
      status: 'approved',
    },
    {
      id: 'voc_a1_there_001',
      word: 'there',
      translation: 'allí',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 1,
      topic: 'pronombres-verbos-ser-estar-tener-hacer-y-sal',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ðɛr/',
      example: 'The library is over there.',
      exampleTranslation: 'La biblioteca está allá.',
      status: 'approved',
    },
  ],
}
