import type { ContentBlock } from '../types'

/**
 * A1 Level — Week 3
 * Topic: Semana 3 – Familia y personas
 * Curated from: a.md
 * Total items: 90
 */
export const week03: ContentBlock = {
  level: 'A1',
  week: 3,
  topic: 'Semana 3 – Familia y personas',
  vocabulary: [
    {
      id: 'voc_a1_mother-mom_001',
      word: 'mother / mom',
      translation: 'madre / mamá',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_father-dad_001',
      word: 'father / dad',
      translation: 'padre / papá',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_parents_001',
      word: 'parents',
      translation: 'padres',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_brother_001',
      word: 'brother',
      translation: 'hermano',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_sister_001',
      word: 'sister',
      translation: 'hermana',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_sibling_001',
      word: 'sibling',
      translation: 'hermano/a',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_son_001',
      word: 'son',
      translation: 'hijo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_daughter_001',
      word: 'daughter',
      translation: 'hija',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_child_001',
      word: 'child',
      translation: 'niño/a',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_children_001',
      word: 'children',
      translation: 'niños',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_baby_001',
      word: 'baby',
      translation: 'bebé',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_husband_001',
      word: 'husband',
      translation: 'esposo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_wife_001',
      word: 'wife',
      translation: 'esposa',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_grandmother-grandma_001',
      word: 'grandmother / grandma',
      translation: 'abuela',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_grandfather-grandpa_001',
      word: 'grandfather / grandpa',
      translation: 'abuelo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_grandparents_001',
      word: 'grandparents',
      translation: 'abuelos',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_aunt_001',
      word: 'aunt',
      translation: 'tía',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_uncle_001',
      word: 'uncle',
      translation: 'tío',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_cousin_001',
      word: 'cousin',
      translation: 'primo/a',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_nephew_001',
      word: 'nephew',
      translation: 'sobrino',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_niece_001',
      word: 'niece',
      translation: 'sobrina',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_family_001',
      word: 'family',
      translation: 'familia',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_friend_001',
      word: 'friend',
      translation: 'amigo/a',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_boyfriend_001',
      word: 'boyfriend',
      translation: 'novio',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_girlfriend_001',
      word: 'girlfriend',
      translation: 'novia',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_man_001',
      word: 'man',
      translation: 'hombre',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_woman_001',
      word: 'woman',
      translation: 'mujer',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_boy_001',
      word: 'boy',
      translation: 'niño',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_girl_001',
      word: 'girl',
      translation: 'niña',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_people_001',
      word: 'people',
      translation: 'gente',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_person_001',
      word: 'person',
      translation: 'persona',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_adult_001',
      word: 'adult',
      translation: 'adulto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_teenager_001',
      word: 'teenager',
      translation: 'adolescente',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_neighbor_001',
      word: 'neighbor',
      translation: 'vecino',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_guest_001',
      word: 'guest',
      translation: 'invitado',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_stranger_001',
      word: 'stranger',
      translation: 'desconocido',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_couple_001',
      word: 'couple',
      translation: 'pareja',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_twins_001',
      word: 'twins',
      translation: 'gemelos',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_married_001',
      word: 'married',
      translation: 'casado',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_single_001',
      word: 'single',
      translation: 'soltero',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_divorced_001',
      word: 'divorced',
      translation: 'divorciado',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_old_001',
      word: 'old',
      translation: 'viejo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_young_001',
      word: 'young',
      translation: 'joven',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_tall_001',
      word: 'tall',
      translation: 'alto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_short_001',
      word: 'short (person)',
      translation: 'bajo (estatura)',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_surname-last-name_001',
      word: 'surname / last name',
      translation: 'apellido',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_nickname_001',
      word: 'nickname',
      translation: 'apodo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_american_001',
      word: 'American',
      translation: 'estadounidense',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_english_001',
      word: 'English',
      translation: 'inglés/a',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_spanish_001',
      word: 'Spanish',
      translation: 'español/a',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_french_001',
      word: 'French',
      translation: 'francés/a',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_german_001',
      word: 'German',
      translation: 'alemán/a',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_chinese_001',
      word: 'Chinese',
      translation: 'chino/a',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_japanese_001',
      word: 'Japanese',
      translation: 'japonés/a',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_mexican_001',
      word: 'Mexican',
      translation: 'mexicano/a',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_canadian_001',
      word: 'Canadian',
      translation: 'canadiense',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_brazilian_001',
      word: 'Brazilian',
      translation: 'brasileño/a',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_country_001',
      word: 'country',
      translation: 'país',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_nationality_001',
      word: 'nationality',
      translation: 'nacionalidad',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_language_001',
      word: 'language',
      translation: 'idioma',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_introduce_001',
      word: 'introduce',
      translation: 'presentar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_meet_001',
      word: 'meet',
      translation: 'conocer/encontrarse',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_relative_001',
      word: 'relative',
      translation: 'pariente',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_only-child_001',
      word: 'only child',
      translation: 'hijo único',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_widow_001',
      word: 'widow',
      translation: 'viuda',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_widower_001',
      word: 'widower',
      translation: 'viudo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_engaged_001',
      word: 'engaged',
      translation: 'comprometido',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_wedding_001',
      word: 'wedding',
      translation: 'boda',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_love_001',
      word: 'love',
      translation: 'amor',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_hate_001',
      word: 'hate',
      translation: 'odio',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_kiss_001',
      word: 'kiss',
      translation: 'beso',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_hug_001',
      word: 'hug',
      translation: 'abrazo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_smile_001',
      word: 'smile',
      translation: 'sonrisa',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_laugh_001',
      word: 'laugh',
      translation: 'risa',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_cry_001',
      word: 'cry',
      translation: 'llorar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_care_001',
      word: 'care',
      translation: 'cuidar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_help_001',
      word: 'help',
      translation: 'ayudar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_visit_001',
      word: 'visit',
      translation: 'visitar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_call_001',
      word: 'call (phone)',
      translation: 'llamar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_invite_001',
      word: 'invite',
      translation: 'invitar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_everyone_001',
      word: 'everyone',
      translation: 'todos',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_someone_001',
      word: 'someone',
      translation: 'alguien',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_no-one_001',
      word: 'no one',
      translation: 'nadie',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_anybody_001',
      word: 'anybody',
      translation: 'alguien/nadie',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_myself_001',
      word: 'myself',
      translation: 'yo mismo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_yourself_001',
      word: 'yourself',
      translation: 'tú mismo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_himself_001',
      word: 'himself',
      translation: 'él mismo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_herself_001',
      word: 'herself',
      translation: 'ella misma',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_ourselves_001',
      word: 'ourselves',
      translation: 'nosotros mismos',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_themselves_001',
      word: 'themselves',
      translation: 'ellos mismos',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
  ],
}
