import type { ContentBlock } from '../types'

/**
 * A1 Level — Week 12
 * Topic: Semana 12 – Transporte y viajes
 * Curated from: a.md
 * Total items: 75
 */
export const week12: ContentBlock = {
  level: 'A1',
  week: 12,
  topic: 'Semana 12 – Transporte y viajes',
  vocabulary: [
    {
      id: 'voc_a1_car_001',
      word: 'car',
      translation: 'carro',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kɑr/',
      example: 'We travel by car on weekends.',
      exampleTranslation: 'Viajamos en carro los fines de semana.',
      status: 'approved',
    },
    {
      id: 'voc_a1_bus_001',
      word: 'bus',
      translation: 'autobús',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bʌs/',
      example: 'I take the bus to work.',
      exampleTranslation: 'Tomo el autobús para ir al trabajo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_train_001',
      word: 'train',
      translation: 'tren',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/treɪn/',
      example: 'The train arrives at nine.',
      exampleTranslation: 'El tren llega a las nueve.',
      status: 'approved',
    },
    {
      id: 'voc_a1_plane-airplane_001',
      word: 'plane / airplane',
      translation: 'avión',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pleɪn/',
      example: 'We took a plane to Mexico.',
      exampleTranslation: 'Tomamos un avión a México.',
      status: 'approved',
    },
    {
      id: 'voc_a1_bike-bicycle_001',
      word: 'bike / bicycle',
      translation: 'bicicleta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/baɪk/',
      example: 'I ride my bike every morning.',
      exampleTranslation: 'Monto mi bicicleta todas las mañanas.',
      status: 'approved',
    },
    {
      id: 'voc_a1_motorcycle_001',
      word: 'motorcycle',
      translation: 'motocicleta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmoʊtərˌsaɪkəl/',
      example: 'He drives a motorcycle to work.',
      exampleTranslation: 'Él conduce una motocicleta al trabajo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_taxi_001',
      word: 'taxi',
      translation: 'taxi',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtæksi/',
      example: 'We took a taxi to the airport.',
      exampleTranslation: 'Tomamos un taxi al aeropuerto.',
      status: 'approved',
    },
    {
      id: 'voc_a1_truck_001',
      word: 'truck',
      translation: 'camión',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/trʌk/',
      example: 'The truck delivers food to stores.',
      exampleTranslation: 'El camión entrega comida a las tiendas.',
      status: 'approved',
    },
    {
      id: 'voc_a1_boat_001',
      word: 'boat',
      translation: 'bote',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/boʊt/',
      example: 'We rode a small boat on the lake.',
      exampleTranslation: 'Paseamos en un bote pequeño en el lago.',
      status: 'approved',
    },
    {
      id: 'voc_a1_ship_001',
      word: 'ship',
      translation: 'barco',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ʃɪp/',
      example: 'The ship left the port at noon.',
      exampleTranslation: 'El barco salió del puerto al mediodía.',
      status: 'approved',
    },
    {
      id: 'voc_a1_subway-metro_001',
      word: 'subway / metro',
      translation: 'metro',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsʌbˌweɪ/',
      example: 'I take the subway every day.',
      exampleTranslation: 'Tomo el metro todos los días.',
      status: 'approved',
    },
    {
      id: 'voc_a1_trip_001',
      word: 'trip',
      translation: 'viaje',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/trɪp/',
      example: 'We had a great trip to the coast.',
      exampleTranslation: 'Tuvimos un gran viaje a la costa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_journey_001',
      word: 'journey',
      translation: 'travesía',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdʒɜrni/',
      example: 'The journey took ten hours.',
      exampleTranslation: 'La travesía duró diez horas.',
      status: 'approved',
    },
    {
      id: 'voc_a1_tourist_001',
      word: 'tourist',
      translation: 'turista',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtʊrɪst/',
      example: 'Many tourists visit this city.',
      exampleTranslation: 'Muchos turistas visitan esta ciudad.',
      status: 'approved',
    },
    {
      id: 'voc_a1_passport_001',
      word: 'passport',
      translation: 'pasaporte',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpæˌspɔrt/',
      example: 'Don\'t forget your passport.',
      exampleTranslation: 'No olvides tu pasaporte.',
      status: 'approved',
    },
    {
      id: 'voc_a1_ticket_001',
      word: 'ticket',
      translation: 'boleto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtɪkɪt/',
      example: 'I bought two tickets for the concert.',
      exampleTranslation: 'Compré dos boletos para el concierto.',
      status: 'approved',
    },
    {
      id: 'voc_a1_luggage_001',
      word: 'luggage',
      translation: 'equipaje',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈlʌgɪdʒ/',
      example: 'Please check your luggage.',
      exampleTranslation: 'Por favor revisa tu equipaje.',
      status: 'approved',
    },
    {
      id: 'voc_a1_suitcase_001',
      word: 'suitcase',
      translation: 'maleta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsutˌkeɪs/',
      example: 'She packed her suitcase quickly.',
      exampleTranslation: 'Ella empacó su maleta rápidamente.',
      status: 'approved',
    },
    {
      id: 'voc_a1_reservation_001',
      word: 'reservation',
      translation: 'reservación',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌrɛzərˈveɪʃən/',
      example: 'I made a reservation for two.',
      exampleTranslation: 'Hice una reservación para dos personas.',
      status: 'approved',
    },
    {
      id: 'voc_a1_flight_001',
      word: 'flight',
      translation: 'vuelo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/flaɪt/',
      example: 'Our flight leaves at six.',
      exampleTranslation: 'Nuestro vuelo sale a las seis.',
      status: 'approved',
    },
    {
      id: 'voc_a1_gate_001',
      word: 'gate (airport)',
      translation: 'puerta de embarque',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/geɪt/',
      example: 'The gate closes in ten minutes.',
      exampleTranslation: 'La puerta de embarque cierra en diez minutos.',
      status: 'approved',
    },
    {
      id: 'voc_a1_arrival_001',
      word: 'arrival',
      translation: 'llegada',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈraɪvəl/',
      example: 'The arrival time is eight thirty.',
      exampleTranslation: 'La hora de llegada es las ocho y media.',
      status: 'approved',
    },
    {
      id: 'voc_a1_departure_001',
      word: 'departure',
      translation: 'salida',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dɪˈpɑrtʃər/',
      example: 'Check the departure board.',
      exampleTranslation: 'Revisa el tablero de salidas.',
      status: 'approved',
    },
    {
      id: 'voc_a1_destination_001',
      word: 'destination',
      translation: 'destino',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌdɛstɪˈneɪʃən/',
      example: 'Our final destination is Rome.',
      exampleTranslation: 'Nuestro destino final es Roma.',
      status: 'approved',
    },
    {
      id: 'voc_a1_souvenir_001',
      word: 'souvenir',
      translation: 'recuerdo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌsuvəˈnɪr/',
      example: 'I bought a souvenir for my mom.',
      exampleTranslation: 'Compré un recuerdo para mi mamá.',
      status: 'approved',
    },
    {
      id: 'voc_a1_fly_002',
      word: 'fly (verb)',
      translation: 'volar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/flaɪ/',
      example: 'We fly to Chicago tomorrow.',
      exampleTranslation: 'Volamos a Chicago mañana.',
      status: 'approved',
    },
    {
      id: 'voc_a1_park_002',
      word: 'park (verb)',
      translation: 'estacionar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pɑrk/',
      example: 'You can park here.',
      exampleTranslation: 'Puedes estacionar aquí.',
      status: 'approved',
    },
    {
      id: 'voc_a1_depart_001',
      word: 'depart',
      translation: 'partir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dɪˈpɑrt/',
      example: 'The bus will depart soon.',
      exampleTranslation: 'El autobús partirá pronto.',
      status: 'approved',
    },
    {
      id: 'voc_a1_book_002',
      word: 'book (verb)',
      translation: 'reservar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bʊk/',
      example: 'I booked a hotel online.',
      exampleTranslation: 'Reservé un hotel en línea.',
      status: 'approved',
    },
    {
      id: 'voc_a1_pack_001',
      word: 'pack',
      translation: 'empacar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pæk/',
      example: 'I need to pack my bag tonight.',
      exampleTranslation: 'Necesito empacar mi bolsa esta noche.',
      status: 'approved',
    },
    {
      id: 'voc_a1_traffic_001',
      word: 'traffic',
      translation: 'tráfico',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtræfɪk/',
      example: 'There is a lot of traffic today.',
      exampleTranslation: 'Hay mucho tráfico hoy.',
      status: 'approved',
    },
    {
      id: 'voc_a1_highway_001',
      word: 'highway',
      translation: 'autopista',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈhaɪˌweɪ/',
      example: 'We took the highway to the city.',
      exampleTranslation: 'Tomamos la autopista hacia la ciudad.',
      status: 'approved',
    },
    {
      id: 'voc_a1_crossing_001',
      word: 'crossing',
      translation: 'cruce',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkrɔsɪŋ/',
      example: 'Be careful at the crossing.',
      exampleTranslation: 'Ten cuidado en el cruce.',
      status: 'approved',
    },
    {
      id: 'voc_a1_seatbelt_001',
      word: 'seatbelt',
      translation: 'cinturón de seguridad',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsitˌbɛlt/',
      example: 'Please wear your seatbelt.',
      exampleTranslation: 'Por favor usa el cinturón de seguridad.',
      status: 'approved',
    },
    {
      id: 'voc_a1_gas-station_001',
      word: 'gas station',
      translation: 'gasolinera',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/gæs ˈsteɪʃən/',
      example: 'We stopped at a gas station.',
      exampleTranslation: 'Paramos en una gasolinera.',
      status: 'approved',
    },
    {
      id: 'voc_a1_ticket-office_001',
      word: 'ticket office',
      translation: 'taquilla',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtɪkɪt ˈɔfəs/',
      example: 'Buy your ticket at the ticket office.',
      exampleTranslation: 'Compra tu boleto en la taquilla.',
      status: 'approved',
    },
    {
      id: 'voc_a1_platform_001',
      word: 'platform',
      translation: 'andén',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈplætˌfɔrm/',
      example: 'The train is on platform two.',
      exampleTranslation: 'El tren está en el andén dos.',
      status: 'approved',
    },
    {
      id: 'voc_a1_terminal_001',
      word: 'terminal',
      translation: 'terminal',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtɜrmənəl/',
      example: 'The flight leaves from terminal one.',
      exampleTranslation: 'El vuelo sale de la terminal uno.',
      status: 'approved',
    },
    {
      id: 'voc_a1_captain_001',
      word: 'captain',
      translation: 'capitán',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkæptən/',
      example: 'The captain welcomed the passengers.',
      exampleTranslation: 'El capitán dio la bienvenida a los pasajeros.',
      status: 'approved',
    },
    {
      id: 'voc_a1_passenger_001',
      word: 'passenger',
      translation: 'pasajero',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpæsəndʒər/',
      example: 'The bus has twenty passengers.',
      exampleTranslation: 'El autobús tiene veinte pasajeros.',
      status: 'approved',
    },
    {
      id: 'voc_a1_drivers-license_001',
      word: "driver's license",
      translation: 'licencia de conducir',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdraɪvərz ˈlaɪsəns/',
      example: 'I got my driver\'s license last year.',
      exampleTranslation: 'Obtuve mi licencia de conducir el año pasado.',
      status: 'approved',
    },
    {
      id: 'voc_a1_fare_001',
      word: 'fare',
      translation: 'tarifa',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fɛr/',
      example: 'The bus fare is two dollars.',
      exampleTranslation: 'La tarifa del autobús es dos dólares.',
      status: 'approved',
    },
    {
      id: 'voc_a1_route_001',
      word: 'route',
      translation: 'ruta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rut/',
      example: 'This route is faster.',
      exampleTranslation: 'Esta ruta es más rápida.',
      status: 'approved',
    },
    {
      id: 'voc_a1_schedule_001',
      word: 'schedule',
      translation: 'horario',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈskɛdʒʊl/',
      example: 'Check the train schedule.',
      exampleTranslation: 'Revisa el horario del tren.',
      status: 'approved',
    },
    {
      id: 'voc_a1_delay_001',
      word: 'delay',
      translation: 'retraso',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dɪˈleɪ/',
      example: 'Our flight has a delay.',
      exampleTranslation: 'Nuestro vuelo tiene un retraso.',
      status: 'approved',
    },
    {
      id: 'voc_a1_connection_001',
      word: 'connection (travel)',
      translation: 'conexión',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kəˈnɛkʃən/',
      example: 'We have a connection in Miami.',
      exampleTranslation: 'Tenemos una conexión en Miami.',
      status: 'approved',
    },
    {
      id: 'voc_a1_customs_001',
      word: 'customs',
      translation: 'aduana',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkʌstəmz/',
      example: 'We waited at customs for an hour.',
      exampleTranslation: 'Esperamos en la aduana una hora.',
      status: 'approved',
    },
    {
      id: 'voc_a1_border_001',
      word: 'border',
      translation: 'frontera',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbɔrdər/',
      example: 'We crossed the border by car.',
      exampleTranslation: 'Cruzamos la frontera en carro.',
      status: 'approved',
    },
    {
      id: 'voc_a1_visa_001',
      word: 'visa',
      translation: 'visa',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈvizə/',
      example: 'I need a visa to travel there.',
      exampleTranslation: 'Necesito una visa para viajar allá.',
      status: 'approved',
    },
    {
      id: 'voc_a1_guide_001',
      word: 'guide (tourist)',
      translation: 'guía',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/gaɪd/',
      example: 'Our guide showed us the city.',
      exampleTranslation: 'Nuestro guía nos mostró la ciudad.',
      status: 'approved',
    },
    {
      id: 'voc_a1_seat_001',
      word: 'seat',
      translation: 'asiento',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/sit/',
      example: 'This is my seat.',
      exampleTranslation: 'Este es mi asiento.',
      status: 'approved',
    },
    {
      id: 'voc_a1_aisle_001',
      word: 'aisle',
      translation: 'pasillo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/aɪl/',
      example: 'I prefer an aisle seat.',
      exampleTranslation: 'Prefiero un asiento de pasillo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_cabin_001',
      word: 'cabin',
      translation: 'cabina',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkæbɪn/',
      example: 'The cabin has small windows.',
      exampleTranslation: 'La cabina tiene ventanas pequeñas.',
      status: 'approved',
    },
    {
      id: 'voc_a1_crew_001',
      word: 'crew',
      translation: 'tripulación',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kru/',
      example: 'The crew was very friendly.',
      exampleTranslation: 'La tripulación fue muy amable.',
      status: 'approved',
    },
    {
      id: 'voc_a1_roundtrip_001',
      word: 'roundtrip',
      translation: 'viaje redondo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌraʊndˈtrɪp/',
      example: 'I bought a roundtrip ticket.',
      exampleTranslation: 'Compré un boleto de viaje redondo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_one-way_001',
      word: 'one-way',
      translation: 'de ida',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈwʌnˈweɪ/',
      example: 'I need a one-way ticket.',
      exampleTranslation: 'Necesito un boleto de ida.',
      status: 'approved',
    },
    {
      id: 'voc_a1_boarding-pass_001',
      word: 'boarding pass',
      translation: 'tarjeta de embarque',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbɔrdɪŋ pæs/',
      example: 'Please show your boarding pass.',
      exampleTranslation: 'Por favor muestre su tarjeta de embarque.',
      status: 'approved',
    },
    {
      id: 'voc_a1_security-check_001',
      word: 'security check',
      translation: 'control de seguridad',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/sɪˈkjʊrəti tʃɛk/',
      example: 'We passed the security check quickly.',
      exampleTranslation: 'Pasamos el control de seguridad rápido.',
      status: 'approved',
    },
    {
      id: 'voc_a1_immigration_001',
      word: 'immigration',
      translation: 'inmigración',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌɪməˈgreɪʃən/',
      example: 'The line at immigration was long.',
      exampleTranslation: 'La fila en inmigración fue larga.',
      status: 'approved',
    },
    {
      id: 'voc_a1_currency_001',
      word: 'currency',
      translation: 'moneda (divisa)',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkɜrənsi/',
      example: 'I need to exchange my currency.',
      exampleTranslation: 'Necesito cambiar mi moneda.',
      status: 'approved',
    },
    {
      id: 'voc_a1_exchange-rate_001',
      word: 'exchange rate',
      translation: 'tipo de cambio',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪksˈtʃeɪndʒ reɪt/',
      example: 'The exchange rate changed today.',
      exampleTranslation: 'El tipo de cambio cambió hoy.',
      status: 'approved',
    },
    {
      id: 'voc_a1_cruise_001',
      word: 'cruise',
      translation: 'crucero',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kruz/',
      example: 'They went on a cruise last summer.',
      exampleTranslation: 'Ellos hicieron un crucero el verano pasado.',
      status: 'approved',
    },
    {
      id: 'voc_a1_ferry_001',
      word: 'ferry',
      translation: 'transbordador',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfɛri/',
      example: 'We took the ferry to the island.',
      exampleTranslation: 'Tomamos el transbordador a la isla.',
      status: 'approved',
    },
    {
      id: 'voc_a1_cable-car_001',
      word: 'cable car',
      translation: 'teleférico',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkeɪbəl kɑr/',
      example: 'We rode the cable car up the mountain.',
      exampleTranslation: 'Subimos la montaña en teleférico.',
      status: 'approved',
    },
    {
      id: 'voc_a1_elevator_001',
      word: 'elevator',
      translation: 'ascensor',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɛləˌveɪtər/',
      example: 'Take the elevator to the third floor.',
      exampleTranslation: 'Toma el ascensor al tercer piso.',
      status: 'approved',
    },
    {
      id: 'voc_a1_escalator_001',
      word: 'escalator',
      translation: 'escalera mecánica',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɛskəˌleɪtər/',
      example: 'The escalator is next to the stairs.',
      exampleTranslation: 'La escalera mecánica está junto a las escaleras.',
      status: 'approved',
    },
    {
      id: 'voc_a1_carpool_001',
      word: 'carpool',
      translation: 'compartir auto',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkɑrˌpul/',
      example: 'We carpool to work every day.',
      exampleTranslation: 'Compartimos auto para ir al trabajo todos los días.',
      status: 'approved',
    },
    {
      id: 'voc_a1_rush-hour_001',
      word: 'rush hour',
      translation: 'hora pico',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rʌʃ ˈaʊər/',
      example: 'Traffic is bad during rush hour.',
      exampleTranslation: 'El tráfico es malo en hora pico.',
      status: 'approved',
    },
    {
      id: 'voc_a1_parking-lot_001',
      word: 'parking lot',
      translation: 'estacionamiento',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpɑrkɪŋ lɑt/',
      example: 'My car is in the parking lot.',
      exampleTranslation: 'Mi carro está en el estacionamiento.',
      status: 'approved',
    },
    {
      id: 'voc_a1_mileage_001',
      word: 'mileage',
      translation: 'kilometraje',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmaɪlɪdʒ/',
      example: 'This car has low mileage.',
      exampleTranslation: 'Este carro tiene bajo kilometraje.',
      status: 'approved',
    },
    {
      id: 'voc_a1_license-plate_001',
      word: 'license plate',
      translation: 'placa de matrícula',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈlaɪsəns pleɪt/',
      example: 'I forgot my license plate number.',
      exampleTranslation: 'Olvidé el número de mi placa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_wheel_001',
      word: 'wheel',
      translation: 'rueda',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/wil/',
      example: 'The front wheel is broken.',
      exampleTranslation: 'La rueda delantera está rota.',
      status: 'approved',
    },
    {
      id: 'voc_a1_tire_001',
      word: 'tire',
      translation: 'llanta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/taɪər/',
      example: 'We need to change the tire.',
      exampleTranslation: 'Necesitamos cambiar la llanta.',
      status: 'approved',
    },
    {
      id: 'voc_a1_brake_001',
      word: 'brake',
      translation: 'freno',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/breɪk/',
      example: 'Press the brake slowly.',
      exampleTranslation: 'Presiona el freno despacio.',
      status: 'approved',
    },
    {
      id: 'voc_a1_horn_001',
      word: 'horn (car)',
      translation: 'bocina',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 12,
      topic: 'transporte-y-viajes',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/hɔrn/',
      example: 'Don\'t use the horn at night.',
      exampleTranslation: 'No uses la bocina de noche.',
      status: 'approved',
    },
  ],
}
