import type { ContentBlock } from '../types'

/**
 * A1 Level — Week 8
 * Topic: Semana 8 – Verbos de la rutina diaria
 * Curated from: a.md
 * Total items: 85
 */
export const week08: ContentBlock = {
  level: 'A1',
  week: 8,
  topic: 'Semana 8 – Verbos de la rutina diaria',
  vocabulary: [
    {
      id: 'voc_a1_wake-up_001',
      word: 'wake up',
      translation: 'despertarse',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/weɪk ʌp/',
      example: 'I wake up at seven every day.',
      exampleTranslation: 'Me despierto a las siete todos los días.',
      status: 'approved',
    },
    {
      id: 'voc_a1_get-up_001',
      word: 'get up',
      translation: 'levantarse',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/gɛt ʌp/',
      example: 'She gets up early on weekdays.',
      exampleTranslation: 'Ella se levanta temprano entre semana.',
      status: 'approved',
    },
    {
      id: 'voc_a1_sleep_001',
      word: 'sleep',
      translation: 'dormir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/slip/',
      example: 'I sleep eight hours a night.',
      exampleTranslation: 'Duermo ocho horas por noche.',
      status: 'approved',
    },
    {
      id: 'voc_a1_go-to-bed_001',
      word: 'go to bed',
      translation: 'irse a la cama',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/goʊ tu bɛd/',
      example: 'We go to bed at ten.',
      exampleTranslation: 'Nos vamos a la cama a las diez.',
      status: 'approved',
    },
    {
      id: 'voc_a1_wash_001',
      word: 'wash',
      translation: 'lavar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/wɑʃ/',
      example: 'I wash my hands before eating.',
      exampleTranslation: 'Me lavo las manos antes de comer.',
      status: 'approved',
    },
    {
      id: 'voc_a1_take-a-shower_001',
      word: 'take a shower',
      translation: 'ducharse',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/teɪk ə ˈʃaʊər/',
      example: 'He takes a shower every morning.',
      exampleTranslation: 'Él se ducha todas las mañanas.',
      status: 'approved',
    },
    {
      id: 'voc_a1_brush_001',
      word: 'brush (teeth)',
      translation: 'cepillarse',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/brʌʃ/',
      example: 'I brush my teeth twice a day.',
      exampleTranslation: 'Me cepillo los dientes dos veces al día.',
      status: 'approved',
    },
    {
      id: 'voc_a1_comb_001',
      word: 'comb',
      translation: 'peinar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/koʊm/',
      example: 'She combs her hair every morning.',
      exampleTranslation: 'Ella se peina todas las mañanas.',
      status: 'approved',
    },
    {
      id: 'voc_a1_get-dressed_001',
      word: 'get dressed',
      translation: 'vestirse',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/gɛt drɛst/',
      example: 'The children get dressed for school.',
      exampleTranslation: 'Los niños se visten para la escuela.',
      status: 'approved',
    },
    {
      id: 'voc_a1_have-breakfast_001',
      word: 'have breakfast',
      translation: 'desayunar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/hæv ˈbrɛkfəst/',
      example: 'We have breakfast at eight.',
      exampleTranslation: 'Desayunamos a las ocho.',
      status: 'approved',
    },
    {
      id: 'voc_a1_go-to-work_001',
      word: 'go to work',
      translation: 'ir al trabajo',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/goʊ tu wɜrk/',
      example: 'He goes to work by bus.',
      exampleTranslation: 'Él va al trabajo en autobús.',
      status: 'approved',
    },
    {
      id: 'voc_a1_go-to-school_001',
      word: 'go to school',
      translation: 'ir a la escuela',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/goʊ tu skul/',
      example: 'The kids go to school at seven thirty.',
      exampleTranslation: 'Los niños van a la escuela a las siete y media.',
      status: 'approved',
    },
    {
      id: 'voc_a1_study_001',
      word: 'study',
      translation: 'estudiar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈstʌdi/',
      example: 'I study English every night.',
      exampleTranslation: 'Estudio inglés todas las noches.',
      status: 'approved',
    },
    {
      id: 'voc_a1_work_001',
      word: 'work',
      translation: 'trabajar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/wɜrk/',
      example: 'She works in a hospital.',
      exampleTranslation: 'Ella trabaja en un hospital.',
      status: 'approved',
    },
    {
      id: 'voc_a1_read_001',
      word: 'read',
      translation: 'leer',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rid/',
      example: 'I read a book before sleeping.',
      exampleTranslation: 'Leo un libro antes de dormir.',
      status: 'approved',
    },
    {
      id: 'voc_a1_write_001',
      word: 'write',
      translation: 'escribir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/raɪt/',
      example: 'He writes letters to his family.',
      exampleTranslation: 'Él le escribe cartas a su familia.',
      status: 'approved',
    },
    {
      id: 'voc_a1_listen_001',
      word: 'listen',
      translation: 'escuchar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈlɪsən/',
      example: 'We listen to music in the car.',
      exampleTranslation: 'Escuchamos música en el carro.',
      status: 'approved',
    },
    {
      id: 'voc_a1_speak_001',
      word: 'speak',
      translation: 'hablar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/spik/',
      example: 'Do you speak English?',
      exampleTranslation: '¿Hablas inglés?',
      status: 'approved',
    },
    {
      id: 'voc_a1_talk_001',
      word: 'talk',
      translation: 'conversar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tɔk/',
      example: 'We talk on the phone every day.',
      exampleTranslation: 'Hablamos por teléfono todos los días.',
      status: 'approved',
    },
    {
      id: 'voc_a1_watch_001',
      word: 'watch',
      translation: 'mirar/ver',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/wɑtʃ/',
      example: 'They watch TV after dinner.',
      exampleTranslation: 'Ellos ven televisión después de cenar.',
      status: 'approved',
    },
    {
      id: 'voc_a1_walk_001',
      word: 'walk',
      translation: 'caminar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/wɔk/',
      example: 'I walk to work every day.',
      exampleTranslation: 'Camino al trabajo todos los días.',
      status: 'approved',
    },
    {
      id: 'voc_a1_run_001',
      word: 'run',
      translation: 'correr',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rʌn/',
      example: 'She runs in the park on Sundays.',
      exampleTranslation: 'Ella corre en el parque los domingos.',
      status: 'approved',
    },
    {
      id: 'voc_a1_drive_001',
      word: 'drive',
      translation: 'conducir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/draɪv/',
      example: 'He drives to the office.',
      exampleTranslation: 'Él conduce a la oficina.',
      status: 'approved',
    },
    {
      id: 'voc_a1_ride_001',
      word: 'ride',
      translation: 'montar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/raɪd/',
      example: 'I ride my bike to school.',
      exampleTranslation: 'Voy a la escuela en bicicleta.',
      status: 'approved',
    },
    {
      id: 'voc_a1_travel_001',
      word: 'travel',
      translation: 'viajar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtrævəl/',
      example: 'We travel every summer.',
      exampleTranslation: 'Viajamos cada verano.',
      status: 'approved',
    },
    {
      id: 'voc_a1_arrive_001',
      word: 'arrive',
      translation: 'llegar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈraɪv/',
      example: 'The train arrives at nine.',
      exampleTranslation: 'El tren llega a las nueve.',
      status: 'approved',
    },
    {
      id: 'voc_a1_leave_001',
      word: 'leave',
      translation: 'salir/irse',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/liv/',
      example: 'I leave home at eight.',
      exampleTranslation: 'Salgo de casa a las ocho.',
      status: 'approved',
    },
    {
      id: 'voc_a1_come_001',
      word: 'come',
      translation: 'venir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kʌm/',
      example: 'Can you come to the party?',
      exampleTranslation: '¿Puedes venir a la fiesta?',
      status: 'approved',
    },
    {
      id: 'voc_a1_go_001',
      word: 'go',
      translation: 'ir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/goʊ/',
      example: 'We go to the market on Saturdays.',
      exampleTranslation: 'Vamos al mercado los sábados.',
      status: 'approved',
    },
    {
      id: 'voc_a1_stay_001',
      word: 'stay',
      translation: 'quedarse',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/steɪ/',
      example: 'We stay home on Sundays.',
      exampleTranslation: 'Nos quedamos en casa los domingos.',
      status: 'approved',
    },
    {
      id: 'voc_a1_live_001',
      word: 'live',
      translation: 'vivir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/lɪv/',
      example: 'I live in a small apartment.',
      exampleTranslation: 'Vivo en un apartamento pequeño.',
      status: 'approved',
    },
    {
      id: 'voc_a1_rest_001',
      word: 'rest',
      translation: 'descansar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rɛst/',
      example: 'I need to rest after work.',
      exampleTranslation: 'Necesito descansar después del trabajo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_relax_001',
      word: 'relax',
      translation: 'relajarse',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rɪˈlæks/',
      example: 'We relax on the weekend.',
      exampleTranslation: 'Nos relajamos el fin de semana.',
      status: 'approved',
    },
    {
      id: 'voc_a1_play_001',
      word: 'play',
      translation: 'jugar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pleɪ/',
      example: 'The children play in the park.',
      exampleTranslation: 'Los niños juegan en el parque.',
      status: 'approved',
    },
    {
      id: 'voc_a1_dance_001',
      word: 'dance',
      translation: 'bailar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dæns/',
      example: 'We dance at every party.',
      exampleTranslation: 'Bailamos en cada fiesta.',
      status: 'approved',
    },
    {
      id: 'voc_a1_sing_001',
      word: 'sing',
      translation: 'cantar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/sɪŋ/',
      example: 'She sings in the shower.',
      exampleTranslation: 'Ella canta en la ducha.',
      status: 'approved',
    },
    {
      id: 'voc_a1_wash-dishes_001',
      word: 'wash dishes',
      translation: 'lavar platos',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/wɑʃ ˈdɪʃɪz/',
      example: 'I wash the dishes after dinner.',
      exampleTranslation: 'Lavo los platos después de la cena.',
      status: 'approved',
    },
    {
      id: 'voc_a1_do-homework_001',
      word: 'do homework',
      translation: 'hacer tarea',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/du ˈhoʊmˌwɜrk/',
      example: 'He does his homework after school.',
      exampleTranslation: 'Él hace su tarea después de la escuela.',
      status: 'approved',
    },
    {
      id: 'voc_a1_exercise_001',
      word: 'exercise',
      translation: 'ejercitarse',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɛksərˌsaɪz/',
      example: 'I exercise three times a week.',
      exampleTranslation: 'Hago ejercicio tres veces por semana.',
      status: 'approved',
    },
    {
      id: 'voc_a1_swim_001',
      word: 'swim',
      translation: 'nadar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/swɪm/',
      example: 'We swim in the summer.',
      exampleTranslation: 'Nadamos en el verano.',
      status: 'approved',
    },
    {
      id: 'voc_a1_jump_001',
      word: 'jump',
      translation: 'saltar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dʒʌmp/',
      example: 'The kids jump on the bed.',
      exampleTranslation: 'Los niños saltan en la cama.',
      status: 'approved',
    },
    {
      id: 'voc_a1_sit_001',
      word: 'sit',
      translation: 'sentarse',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/sɪt/',
      example: 'Please sit here.',
      exampleTranslation: 'Por favor siéntate aquí.',
      status: 'approved',
    },
    {
      id: 'voc_a1_stand_001',
      word: 'stand',
      translation: 'pararse',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/stænd/',
      example: 'We stood in line for an hour.',
      exampleTranslation: 'Estuvimos parados en la fila una hora.',
      status: 'approved',
    },
    {
      id: 'voc_a1_wait_001',
      word: 'wait',
      translation: 'esperar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/weɪt/',
      example: 'I am waiting for the bus.',
      exampleTranslation: 'Estoy esperando el autobús.',
      status: 'approved',
    },
    {
      id: 'voc_a1_need_001',
      word: 'need',
      translation: 'necesitar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/nid/',
      example: 'I need help with this box.',
      exampleTranslation: 'Necesito ayuda con esta caja.',
      status: 'approved',
    },
    {
      id: 'voc_a1_want_001',
      word: 'want',
      translation: 'querer',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/wɑnt/',
      example: 'She wants a new phone.',
      exampleTranslation: 'Ella quiere un teléfono nuevo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_like_001',
      word: 'like',
      translation: 'gustar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/laɪk/',
      example: 'I like this song.',
      exampleTranslation: 'Me gusta esta canción.',
      status: 'approved',
    },
    {
      id: 'voc_a1_know_001',
      word: 'know',
      translation: 'saber/conocer',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/noʊ/',
      example: 'I know the answer.',
      exampleTranslation: 'Sé la respuesta.',
      status: 'approved',
    },
    {
      id: 'voc_a1_think_001',
      word: 'think',
      translation: 'pensar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/θɪŋk/',
      example: 'I think it will rain.',
      exampleTranslation: 'Creo que va a llover.',
      status: 'approved',
    },
    {
      id: 'voc_a1_remember_001',
      word: 'remember',
      translation: 'recordar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rɪˈmɛmbər/',
      example: 'I don\'t remember his name.',
      exampleTranslation: 'No recuerdo su nombre.',
      status: 'approved',
    },
    {
      id: 'voc_a1_forget_001',
      word: 'forget',
      translation: 'olvidar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fərˈgɛt/',
      example: 'Don\'t forget your keys.',
      exampleTranslation: 'No olvides tus llaves.',
      status: 'approved',
    },
    {
      id: 'voc_a1_understand_001',
      word: 'understand',
      translation: 'entender',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌʌndərˈstænd/',
      example: 'Do you understand the question?',
      exampleTranslation: '¿Entiendes la pregunta?',
      status: 'approved',
    },
    {
      id: 'voc_a1_learn_001',
      word: 'learn',
      translation: 'aprender',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/lɜrn/',
      example: 'I want to learn English.',
      exampleTranslation: 'Quiero aprender inglés.',
      status: 'approved',
    },
    {
      id: 'voc_a1_teach_001',
      word: 'teach',
      translation: 'enseñar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/titʃ/',
      example: 'She teaches math at school.',
      exampleTranslation: 'Ella enseña matemáticas en la escuela.',
      status: 'approved',
    },
    {
      id: 'voc_a1_ask_001',
      word: 'ask',
      translation: 'preguntar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/æsk/',
      example: 'Can I ask you a question?',
      exampleTranslation: '¿Puedo hacerte una pregunta?',
      status: 'approved',
    },
    {
      id: 'voc_a1_answer_001',
      word: 'answer',
      translation: 'responder',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈænsər/',
      example: 'Please answer the phone.',
      exampleTranslation: 'Por favor contesta el teléfono.',
      status: 'approved',
    },
    {
      id: 'voc_a1_say_001',
      word: 'say',
      translation: 'decir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/seɪ/',
      example: 'What did she say?',
      exampleTranslation: '¿Qué dijo ella?',
      status: 'approved',
    },
    {
      id: 'voc_a1_tell_001',
      word: 'tell',
      translation: 'contar/decir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tɛl/',
      example: 'Tell me the truth.',
      exampleTranslation: 'Dime la verdad.',
      status: 'approved',
    },
    {
      id: 'voc_a1_give_001',
      word: 'give',
      translation: 'dar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/gɪv/',
      example: 'Give me your hand.',
      exampleTranslation: 'Dame tu mano.',
      status: 'approved',
    },
    {
      id: 'voc_a1_take_001',
      word: 'take',
      translation: 'tomar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/teɪk/',
      example: 'Take an umbrella, it\'s raining.',
      exampleTranslation: 'Lleva un paraguas, está lloviendo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_bring_001',
      word: 'bring',
      translation: 'traer',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/brɪŋ/',
      example: 'Bring your homework tomorrow.',
      exampleTranslation: 'Trae tu tarea mañana.',
      status: 'approved',
    },
    {
      id: 'voc_a1_send_001',
      word: 'send',
      translation: 'enviar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/sɛnd/',
      example: 'I will send you an email.',
      exampleTranslation: 'Te enviaré un correo electrónico.',
      status: 'approved',
    },
    {
      id: 'voc_a1_receive_001',
      word: 'receive',
      translation: 'recibir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rɪˈsiv/',
      example: 'I received a gift from her.',
      exampleTranslation: 'Recibí un regalo de ella.',
      status: 'approved',
    },
    {
      id: 'voc_a1_sell_001',
      word: 'sell',
      translation: 'vender',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/sɛl/',
      example: 'They sell fresh fruit here.',
      exampleTranslation: 'Aquí venden fruta fresca.',
      status: 'approved',
    },
    {
      id: 'voc_a1_pay_001',
      word: 'pay',
      translation: 'pagar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/peɪ/',
      example: 'I will pay for dinner.',
      exampleTranslation: 'Yo pagaré la cena.',
      status: 'approved',
    },
    {
      id: 'voc_a1_spend_001',
      word: 'spend',
      translation: 'gastar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/spɛnd/',
      example: 'We spend a lot on rent.',
      exampleTranslation: 'Gastamos mucho en el alquiler.',
      status: 'approved',
    },
    {
      id: 'voc_a1_save_001',
      word: 'save',
      translation: 'ahorrar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/seɪv/',
      example: 'I save money every month.',
      exampleTranslation: 'Ahorro dinero cada mes.',
      status: 'approved',
    },
    {
      id: 'voc_a1_lose_001',
      word: 'lose',
      translation: 'perder',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/luz/',
      example: 'Don\'t lose your ticket.',
      exampleTranslation: 'No pierdas tu boleto.',
      status: 'approved',
    },
    {
      id: 'voc_a1_find_001',
      word: 'find',
      translation: 'encontrar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/faɪnd/',
      example: 'I can\'t find my keys.',
      exampleTranslation: 'No encuentro mis llaves.',
      status: 'approved',
    },
    {
      id: 'voc_a1_look-for_001',
      word: 'look for',
      translation: 'buscar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/lʊk fɔr/',
      example: 'I am looking for my phone.',
      exampleTranslation: 'Estoy buscando mi teléfono.',
      status: 'approved',
    },
    {
      id: 'voc_a1_look-at_001',
      word: 'look at',
      translation: 'mirar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/lʊk æt/',
      example: 'Look at that beautiful sunset.',
      exampleTranslation: 'Mira ese hermoso atardecer.',
      status: 'approved',
    },
    {
      id: 'voc_a1_see_001',
      word: 'see',
      translation: 'ver',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/si/',
      example: 'I see a bird in the tree.',
      exampleTranslation: 'Veo un pájaro en el árbol.',
      status: 'approved',
    },
    {
      id: 'voc_a1_hear_001',
      word: 'hear',
      translation: 'oír',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/hɪr/',
      example: 'Can you hear the music?',
      exampleTranslation: '¿Puedes oír la música?',
      status: 'approved',
    },
    {
      id: 'voc_a1_feel_001',
      word: 'feel',
      translation: 'sentir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fil/',
      example: 'I feel tired today.',
      exampleTranslation: 'Me siento cansado hoy.',
      status: 'approved',
    },
    {
      id: 'voc_a1_smell_001',
      word: 'smell',
      translation: 'oler',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/smɛl/',
      example: 'This flower smells wonderful.',
      exampleTranslation: 'Esta flor huele maravilloso.',
      status: 'approved',
    },
    {
      id: 'voc_a1_touch_001',
      word: 'touch',
      translation: 'tocar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tʌtʃ/',
      example: 'Don\'t touch the wet paint.',
      exampleTranslation: 'No toques la pintura mojada.',
      status: 'approved',
    },
    {
      id: 'voc_a1_start_001',
      word: 'start',
      translation: 'empezar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/stɑrt/',
      example: 'The movie starts at eight.',
      exampleTranslation: 'La película empieza a las ocho.',
      status: 'approved',
    },
    {
      id: 'voc_a1_finish_001',
      word: 'finish',
      translation: 'terminar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfɪnɪʃ/',
      example: 'I finish work at five.',
      exampleTranslation: 'Termino de trabajar a las cinco.',
      status: 'approved',
    },
    {
      id: 'voc_a1_stop_001',
      word: 'stop',
      translation: 'parar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/stɑp/',
      example: 'The bus stops here.',
      exampleTranslation: 'El autobús para aquí.',
      status: 'approved',
    },
    {
      id: 'voc_a1_continue_001',
      word: 'continue',
      translation: 'continuar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kənˈtɪnju/',
      example: 'Please continue with the story.',
      exampleTranslation: 'Por favor continúa con la historia.',
      status: 'approved',
    },
    {
      id: 'voc_a1_try_001',
      word: 'try',
      translation: 'intentar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/traɪ/',
      example: 'Try this cake, it\'s delicious.',
      exampleTranslation: 'Prueba este pastel, está delicioso.',
      status: 'approved',
    },
    {
      id: 'voc_a1_use_001',
      word: 'use',
      translation: 'usar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/juz/',
      example: 'I use my phone every day.',
      exampleTranslation: 'Uso mi teléfono todos los días.',
      status: 'approved',
    },
    {
      id: 'voc_a1_make_001',
      word: 'make',
      translation: 'hacer/fabricar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/meɪk/',
      example: 'She makes breakfast every morning.',
      exampleTranslation: 'Ella hace el desayuno cada mañana.',
      status: 'approved',
    },
    {
      id: 'voc_a1_fix_001',
      word: 'fix',
      translation: 'arreglar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fɪks/',
      example: 'Can you fix my computer?',
      exampleTranslation: '¿Puedes arreglar mi computadora?',
      status: 'approved',
    },
    {
      id: 'voc_a1_break_001',
      word: 'break',
      translation: 'romper',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 8,
      topic: 'verbos-de-la-rutina-diaria',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/breɪk/',
      example: 'Be careful, don\'t break the glass.',
      exampleTranslation: 'Ten cuidado, no rompas el vaso.',
      status: 'approved',
    },
  ],
}
