import type { ContentBlock } from '../types'

/**
 * A1 Level — Week 18
 * Topic: Semana 18 – Verbos de acción, ideas y repaso general
 * Curated from: a.md
 * Total items: 104
 */
export const week18: ContentBlock = {
  level: 'A1',
  week: 18,
  topic: 'Semana 18 – Verbos de acción, ideas y repaso general',
  vocabulary: [
    {
      id: 'voc_a1_put_001',
      word: 'put',
      translation: 'poner',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_keep_001',
      word: 'keep',
      translation: 'mantener/guardar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_hold_001',
      word: 'hold',
      translation: 'sostener',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_carry_001',
      word: 'carry (object)',
      translation: 'llevar/cargar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_pull_001',
      word: 'pull',
      translation: 'jalar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_push_001',
      word: 'push',
      translation: 'empujar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_throw_001',
      word: 'throw',
      translation: 'lanzar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_catch_001',
      word: 'catch',
      translation: 'atrapar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_hit_001',
      word: 'hit',
      translation: 'golpear',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_kick_001',
      word: 'kick',
      translation: 'patear',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_tear_001',
      word: 'tear',
      translation: 'rasgar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_fold_001',
      word: 'fold',
      translation: 'doblar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_wrap_001',
      word: 'wrap',
      translation: 'envolver',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_cover_001',
      word: 'cover',
      translation: 'cubrir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_hide_001',
      word: 'hide',
      translation: 'esconder',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_show_001',
      word: 'show',
      translation: 'mostrar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_point_001',
      word: 'point',
      translation: 'señalar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_turn_001',
      word: 'turn',
      translation: 'girar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_turn-on_001',
      word: 'turn on',
      translation: 'encender',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_turn-off_001',
      word: 'turn off',
      translation: 'apagar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_mix_001',
      word: 'mix',
      translation: 'mezclar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_add_001',
      word: 'add',
      translation: 'agregar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_remove_001',
      word: 'remove',
      translation: 'quitar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_fill_001',
      word: 'fill',
      translation: 'llenar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_pour_001',
      word: 'pour',
      translation: 'verter',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_press_001',
      word: 'press',
      translation: 'presionar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_lift_001',
      word: 'lift',
      translation: 'levantar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_drop_001',
      word: 'drop',
      translation: 'dejar caer',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_pick-up_001',
      word: 'pick up',
      translation: 'recoger',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_set-up_001',
      word: 'set up',
      translation: 'instalar/organizar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_rise_001',
      word: 'rise',
      translation: 'subir/aumentar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_fall_001',
      word: 'fall',
      translation: 'caer',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_grow_001',
      word: 'grow',
      translation: 'crecer',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_increase_001',
      word: 'increase',
      translation: 'aumentar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_decrease_001',
      word: 'decrease',
      translation: 'disminuir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_change_002',
      word: 'change (verb)',
      translation: 'cambiar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_improve_001',
      word: 'improve',
      translation: 'mejorar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_succeed_001',
      word: 'succeed',
      translation: 'tener éxito',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_fail_001',
      word: 'fail',
      translation: 'fallar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_compete_001',
      word: 'compete',
      translation: 'competir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_practice_001',
      word: 'practice',
      translation: 'practicar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_prepare_001',
      word: 'prepare',
      translation: 'preparar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_organize_001',
      word: 'organize',
      translation: 'organizar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_arrange_001',
      word: 'arrange',
      translation: 'arreglar/organizar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_collect_001',
      word: 'collect',
      translation: 'coleccionar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_gather_001',
      word: 'gather',
      translation: 'reunir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_separate_001',
      word: 'separate',
      translation: 'separar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_connect_001',
      word: 'connect',
      translation: 'conectar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_disconnect_001',
      word: 'disconnect',
      translation: 'desconectar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_join_001',
      word: 'join',
      translation: 'unirse',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_enter_001',
      word: 'enter',
      translation: 'entrar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_exit_001',
      word: 'exit',
      translation: 'salir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_idea_001',
      word: 'idea',
      translation: 'idea',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_opinion_001',
      word: 'opinion',
      translation: 'opinión',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_decision_001',
      word: 'decision',
      translation: 'decisión',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_solution_001',
      word: 'solution',
      translation: 'solución',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_problem_001',
      word: 'problem',
      translation: 'problema',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_reason_001',
      word: 'reason',
      translation: 'razón',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_result_001',
      word: 'result',
      translation: 'resultado',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_effect_001',
      word: 'effect',
      translation: 'efecto',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_cause_001',
      word: 'cause',
      translation: 'causa',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_example_001',
      word: 'example',
      translation: 'ejemplo',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_fact_001',
      word: 'fact',
      translation: 'hecho',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_information_001',
      word: 'information',
      translation: 'información',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_rule_001',
      word: 'rule',
      translation: 'regla',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_law_001',
      word: 'law',
      translation: 'ley',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_permission_001',
      word: 'permission',
      translation: 'permiso',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_freedom_001',
      word: 'freedom',
      translation: 'libertad',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_responsibility_001',
      word: 'responsibility',
      translation: 'responsabilidad',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_duty_001',
      word: 'duty',
      translation: 'deber',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_purpose_001',
      word: 'purpose',
      translation: 'propósito',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_project_001',
      word: 'project',
      translation: 'proyecto',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_task_001',
      word: 'task',
      translation: 'tarea (labor)',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_effort_001',
      word: 'effort',
      translation: 'esfuerzo',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_chance_001',
      word: 'chance',
      translation: 'oportunidad/posibilidad',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_opportunity_001',
      word: 'opportunity',
      translation: 'oportunidad',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_risk_001',
      word: 'risk',
      translation: 'riesgo',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_success_001',
      word: 'success',
      translation: 'éxito',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_failure_001',
      word: 'failure',
      translation: 'fracaso',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_mistake_001',
      word: 'mistake',
      translation: 'error',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_experience_001',
      word: 'experience',
      translation: 'experiencia',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_knowledge_001',
      word: 'knowledge',
      translation: 'conocimiento',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_skill_001',
      word: 'skill',
      translation: 'habilidad',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_ability_001',
      word: 'ability',
      translation: 'capacidad',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_talent_001',
      word: 'talent',
      translation: 'talento',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_memory_001',
      word: 'memory',
      translation: 'memoria',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_imagination_001',
      word: 'imagination',
      translation: 'imaginación',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_attention_001',
      word: 'attention',
      translation: 'atención',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_focus_001',
      word: 'focus',
      translation: 'concentración',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_courage_001',
      word: 'courage',
      translation: 'valentía',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_fear_001',
      word: 'fear',
      translation: 'miedo',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_faith_001',
      word: 'faith',
      translation: 'fe',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_trust_001',
      word: 'trust',
      translation: 'confianza',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_doubt_001',
      word: 'doubt',
      translation: 'duda',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_truth_001',
      word: 'truth',
      translation: 'verdad',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_lie_001',
      word: 'lie (noun)',
      translation: 'mentira',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_secret_001',
      word: 'secret',
      translation: 'secreto',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_agreement_001',
      word: 'agreement',
      translation: 'acuerdo',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_conflict_001',
      word: 'conflict',
      translation: 'conflicto',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_peace_001',
      word: 'peace',
      translation: 'paz',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_war_001',
      word: 'war',
      translation: 'guerra',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_justice_001',
      word: 'justice',
      translation: 'justicia',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_equality_001',
      word: 'equality',
      translation: 'igualdad',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_value_001',
      word: 'value',
      translation: 'valor',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 18,
      topic: 'verbos-de-acci-n-ideas-y-repaso-general',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
  ],
}
