import type { ContentBlock } from '../types'

/**
 * A1 Level — Week 11
 * Topic: Semana 11 – Profesiones y escuela
 * Curated from: a.md
 * Total items: 66
 */
export const week11: ContentBlock = {
  level: 'A1',
  week: 11,
  topic: 'Semana 11 – Profesiones y escuela',
  vocabulary: [
    {
      id: 'voc_a1_teacher_001',
      word: 'teacher',
      translation: 'maestro/a',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtitʃər/',
      example: 'My teacher is very patient.',
      exampleTranslation: 'Mi maestra es muy paciente.',
      status: 'approved',
    },
    {
      id: 'voc_a1_student_001',
      word: 'student',
      translation: 'estudiante',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈstudənt/',
      example: 'I am a student at this school.',
      exampleTranslation: 'Soy estudiante en esta escuela.',
      status: 'approved',
    },
    {
      id: 'voc_a1_doctor_001',
      word: 'doctor',
      translation: 'médico',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdɑktər/',
      example: 'The doctor checked my throat.',
      exampleTranslation: 'El médico revisó mi garganta.',
      status: 'approved',
    },
    {
      id: 'voc_a1_nurse_001',
      word: 'nurse',
      translation: 'enfermero/a',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/nɜrs/',
      example: 'The nurse gave me my medicine.',
      exampleTranslation: 'La enfermera me dio mi medicina.',
      status: 'approved',
    },
    {
      id: 'voc_a1_dentist_001',
      word: 'dentist',
      translation: 'dentista',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdɛntɪst/',
      example: 'I have an appointment with the dentist.',
      exampleTranslation: 'Tengo una cita con el dentista.',
      status: 'approved',
    },
    {
      id: 'voc_a1_engineer_001',
      word: 'engineer',
      translation: 'ingeniero',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌɛndʒəˈnɪr/',
      example: 'My brother is an engineer.',
      exampleTranslation: 'Mi hermano es ingeniero.',
      status: 'approved',
    },
    {
      id: 'voc_a1_lawyer_001',
      word: 'lawyer',
      translation: 'abogado',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈlɔjər/',
      example: 'She works as a lawyer.',
      exampleTranslation: 'Ella trabaja como abogada.',
      status: 'approved',
    },
    {
      id: 'voc_a1_police-officer_001',
      word: 'police officer',
      translation: 'policía',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pəˈlis ˈɔfɪsər/',
      example: 'The police officer helped us find the way.',
      exampleTranslation: 'El policía nos ayudó a encontrar el camino.',
      status: 'approved',
    },
    {
      id: 'voc_a1_firefighter_001',
      word: 'firefighter',
      translation: 'bombero',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfaɪrˌfaɪtər/',
      example: 'The firefighter saved the family.',
      exampleTranslation: 'El bombero salvó a la familia.',
      status: 'approved',
    },
    {
      id: 'voc_a1_farmer_001',
      word: 'farmer',
      translation: 'granjero',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfɑrmər/',
      example: 'The farmer works from early morning.',
      exampleTranslation: 'El granjero trabaja desde temprano.',
      status: 'approved',
    },
    {
      id: 'voc_a1_driver_001',
      word: 'driver',
      translation: 'conductor',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdraɪvər/',
      example: 'The bus driver is very careful.',
      exampleTranslation: 'El conductor del autobús es muy cuidadoso.',
      status: 'approved',
    },
    {
      id: 'voc_a1_pilot_001',
      word: 'pilot',
      translation: 'piloto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpaɪlət/',
      example: 'My uncle is an airplane pilot.',
      exampleTranslation: 'Mi tío es piloto de avión.',
      status: 'approved',
    },
    {
      id: 'voc_a1_cashier_001',
      word: 'cashier',
      translation: 'cajero',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kæˈʃɪr/',
      example: 'The cashier gave me my change.',
      exampleTranslation: 'La cajera me dio mi cambio.',
      status: 'approved',
    },
    {
      id: 'voc_a1_manager_001',
      word: 'manager',
      translation: 'gerente',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmænɪdʒər/',
      example: 'The manager approved my vacation.',
      exampleTranslation: 'El gerente aprobó mis vacaciones.',
      status: 'approved',
    },
    {
      id: 'voc_a1_boss_001',
      word: 'boss',
      translation: 'jefe',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bɔs/',
      example: 'My boss is very kind.',
      exampleTranslation: 'Mi jefe es muy amable.',
      status: 'approved',
    },
    {
      id: 'voc_a1_employee_001',
      word: 'employee',
      translation: 'empleado',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪmˈplɔɪi/',
      example: 'She is a new employee.',
      exampleTranslation: 'Ella es una empleada nueva.',
      status: 'approved',
    },
    {
      id: 'voc_a1_worker_001',
      word: 'worker',
      translation: 'trabajador',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈwɜrkər/',
      example: 'The workers finished the project.',
      exampleTranslation: 'Los trabajadores terminaron el proyecto.',
      status: 'approved',
    },
    {
      id: 'voc_a1_businessman-businesswoman_001',
      word: 'businessman / businesswoman',
      translation: 'empresario/a',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbɪznɪsˌmæn/',
      example: 'He is a successful businessman.',
      exampleTranslation: 'Él es un empresario exitoso.',
      status: 'approved',
    },
    {
      id: 'voc_a1_artist_001',
      word: 'artist',
      translation: 'artista',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɑrtɪst/',
      example: 'She is a talented artist.',
      exampleTranslation: 'Ella es una artista talentosa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_musician_001',
      word: 'musician',
      translation: 'músico',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/mjuˈzɪʃən/',
      example: 'He is a musician in a band.',
      exampleTranslation: 'Él es músico en una banda.',
      status: 'approved',
    },
    {
      id: 'voc_a1_actor-actress_001',
      word: 'actor / actress',
      translation: 'actor / actriz',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈæktər/',
      example: 'He is a famous actor.',
      exampleTranslation: 'Él es un actor famoso.',
      status: 'approved',
    },
    {
      id: 'voc_a1_writer_001',
      word: 'writer',
      translation: 'escritor',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈraɪtər/',
      example: 'She is a writer of children\'s books.',
      exampleTranslation: 'Ella es escritora de libros infantiles.',
      status: 'approved',
    },
    {
      id: 'voc_a1_journalist_001',
      word: 'journalist',
      translation: 'periodista',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdʒɜrnəlɪst/',
      example: 'The journalist wrote an interesting article.',
      exampleTranslation: 'El periodista escribió un artículo interesante.',
      status: 'approved',
    },
    {
      id: 'voc_a1_scientist_001',
      word: 'scientist',
      translation: 'científico',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsaɪəntɪst/',
      example: 'The scientist works in a laboratory.',
      exampleTranslation: 'El científico trabaja en un laboratorio.',
      status: 'approved',
    },
    {
      id: 'voc_a1_athlete_001',
      word: 'athlete',
      translation: 'atleta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈæθˌlit/',
      example: 'She is a professional athlete.',
      exampleTranslation: 'Ella es una atleta profesional.',
      status: 'approved',
    },
    {
      id: 'voc_a1_soldier_001',
      word: 'soldier',
      translation: 'soldado',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsoʊldʒər/',
      example: 'The soldier serves his country.',
      exampleTranslation: 'El soldado sirve a su país.',
      status: 'approved',
    },
    {
      id: 'voc_a1_secretary_001',
      word: 'secretary',
      translation: 'secretario/a',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsɛkrəˌtɛri/',
      example: 'The secretary answered the phone.',
      exampleTranslation: 'La secretaria contestó el teléfono.',
      status: 'approved',
    },
    {
      id: 'voc_a1_receptionist_001',
      word: 'receptionist',
      translation: 'recepcionista',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rɪˈsɛpʃənɪst/',
      example: 'The receptionist welcomed us kindly.',
      exampleTranslation: 'La recepcionista nos recibió amablemente.',
      status: 'approved',
    },
    {
      id: 'voc_a1_mechanic_001',
      word: 'mechanic',
      translation: 'mecánico',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/mɪˈkænɪk/',
      example: 'The mechanic fixed my car.',
      exampleTranslation: 'El mecánico arregló mi carro.',
      status: 'approved',
    },
    {
      id: 'voc_a1_electrician_001',
      word: 'electrician',
      translation: 'electricista',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪlɛkˈtrɪʃən/',
      example: 'We called an electrician for the lights.',
      exampleTranslation: 'Llamamos a un electricista por las luces.',
      status: 'approved',
    },
    {
      id: 'voc_a1_plumber_001',
      word: 'plumber',
      translation: 'plomero',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈplʌmər/',
      example: 'The plumber fixed the leak.',
      exampleTranslation: 'El plomero arregló la fuga.',
      status: 'approved',
    },
    {
      id: 'voc_a1_hairdresser_001',
      word: 'hairdresser',
      translation: 'peluquero',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈhɛrˌdrɛsər/',
      example: 'My hairdresser cut my hair short.',
      exampleTranslation: 'Mi peluquero me cortó el cabello corto.',
      status: 'approved',
    },
    {
      id: 'voc_a1_tailor_001',
      word: 'tailor',
      translation: 'sastre',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈteɪlər/',
      example: 'The tailor made my suit.',
      exampleTranslation: 'El sastre hizo mi traje.',
      status: 'approved',
    },
    {
      id: 'voc_a1_baker_001',
      word: 'baker',
      translation: 'panadero',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbeɪkər/',
      example: 'The baker makes fresh bread every day.',
      exampleTranslation: 'El panadero hace pan fresco todos los días.',
      status: 'approved',
    },
    {
      id: 'voc_a1_butcher_001',
      word: 'butcher',
      translation: 'carnicero',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbʊtʃər/',
      example: 'We buy meat from the butcher.',
      exampleTranslation: 'Compramos carne en la carnicería (del carnicero).',
      status: 'approved',
    },
    {
      id: 'voc_a1_job_001',
      word: 'job',
      translation: 'trabajo/empleo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dʒɑb/',
      example: 'I like my new job.',
      exampleTranslation: 'Me gusta mi nuevo trabajo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_career_001',
      word: 'career',
      translation: 'carrera',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kəˈrɪr/',
      example: 'She is happy with her career.',
      exampleTranslation: 'Ella está feliz con su carrera.',
      status: 'approved',
    },
    {
      id: 'voc_a1_company_001',
      word: 'company',
      translation: 'empresa',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkʌmpəni/',
      example: 'He works for a big company.',
      exampleTranslation: 'Él trabaja para una gran empresa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_office_001',
      word: 'office',
      translation: 'oficina',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɔfɪs/',
      example: 'I go to the office every day.',
      exampleTranslation: 'Voy a la oficina todos los días.',
      status: 'approved',
    },
    {
      id: 'voc_a1_salary_001',
      word: 'salary',
      translation: 'salario',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsæləri/',
      example: 'Her salary increased this year.',
      exampleTranslation: 'Su salario aumentó este año.',
      status: 'approved',
    },
    {
      id: 'voc_a1_classroom_001',
      word: 'classroom',
      translation: 'salón de clases',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈklæsˌrum/',
      example: 'The classroom is very bright.',
      exampleTranslation: 'El salón de clases es muy luminoso.',
      status: 'approved',
    },
    {
      id: 'voc_a1_class_001',
      word: 'class',
      translation: 'clase',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/klæs/',
      example: 'Our class starts at nine.',
      exampleTranslation: 'Nuestra clase empieza a las nueve.',
      status: 'approved',
    },
    {
      id: 'voc_a1_lesson_001',
      word: 'lesson',
      translation: 'lección',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈlɛsən/',
      example: 'Today\'s lesson is about verbs.',
      exampleTranslation: 'La lección de hoy es sobre los verbos.',
      status: 'approved',
    },
    {
      id: 'voc_a1_subject_001',
      word: 'subject',
      translation: 'materia',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsʌbdʒɪkt/',
      example: 'Math is my favorite subject.',
      exampleTranslation: 'Matemáticas es mi materia favorita.',
      status: 'approved',
    },
    {
      id: 'voc_a1_math_001',
      word: 'math',
      translation: 'matemáticas',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/mæθ/',
      example: 'I have math class on Monday.',
      exampleTranslation: 'Tengo clase de matemáticas el lunes.',
      status: 'approved',
    },
    {
      id: 'voc_a1_science_001',
      word: 'science',
      translation: 'ciencia',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsaɪəns/',
      example: 'We do experiments in science class.',
      exampleTranslation: 'Hacemos experimentos en la clase de ciencias.',
      status: 'approved',
    },
    {
      id: 'voc_a1_history_001',
      word: 'history',
      translation: 'historia',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈhɪstəri/',
      example: 'I love learning about history.',
      exampleTranslation: 'Me encanta aprender sobre historia.',
      status: 'approved',
    },
    {
      id: 'voc_a1_geography_001',
      word: 'geography',
      translation: 'geografía',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dʒiˈɑgrəfi/',
      example: 'We study maps in geography class.',
      exampleTranslation: 'Estudiamos mapas en la clase de geografía.',
      status: 'approved',
    },
    {
      id: 'voc_a1_art_001',
      word: 'art',
      translation: 'arte',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɑrt/',
      example: 'She draws well in art class.',
      exampleTranslation: 'Ella dibuja bien en la clase de arte.',
      status: 'approved',
    },
    {
      id: 'voc_a1_music_001',
      word: 'music',
      translation: 'música',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmjuzɪk/',
      example: 'I play the guitar in music class.',
      exampleTranslation: 'Toco la guitarra en la clase de música.',
      status: 'approved',
    },
    {
      id: 'voc_a1_physical-education_001',
      word: 'physical education',
      translation: 'educación física',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfɪzɪkəl ˌɛdʒəˈkeɪʃən/',
      example: 'We play soccer in physical education.',
      exampleTranslation: 'Jugamos fútbol en educación física.',
      status: 'approved',
    },
    {
      id: 'voc_a1_book_001',
      word: 'book',
      translation: 'libro',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bʊk/',
      example: 'I am reading a good book.',
      exampleTranslation: 'Estoy leyendo un buen libro.',
      status: 'approved',
    },
    {
      id: 'voc_a1_notebook_001',
      word: 'notebook',
      translation: 'cuaderno',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈnoʊtˌbʊk/',
      example: 'I write notes in my notebook.',
      exampleTranslation: 'Escribo apuntes en mi cuaderno.',
      status: 'approved',
    },
    {
      id: 'voc_a1_pen_001',
      word: 'pen',
      translation: 'bolígrafo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pɛn/',
      example: 'Can I borrow your pen?',
      exampleTranslation: '¿Me prestas tu bolígrafo?',
      status: 'approved',
    },
    {
      id: 'voc_a1_pencil_001',
      word: 'pencil',
      translation: 'lápiz',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpɛnsəl/',
      example: 'I need a pencil to draw.',
      exampleTranslation: 'Necesito un lápiz para dibujar.',
      status: 'approved',
    },
    {
      id: 'voc_a1_eraser_001',
      word: 'eraser',
      translation: 'borrador',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪˈreɪsər/',
      example: 'Can I use your eraser?',
      exampleTranslation: '¿Puedo usar tu borrador?',
      status: 'approved',
    },
    {
      id: 'voc_a1_ruler_001',
      word: 'ruler',
      translation: 'regla',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈrulər/',
      example: 'Use a ruler to draw a straight line.',
      exampleTranslation: 'Usa una regla para dibujar una línea recta.',
      status: 'approved',
    },
    {
      id: 'voc_a1_backpack_001',
      word: 'backpack',
      translation: 'mochila',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbækˌpæk/',
      example: 'My backpack is very heavy.',
      exampleTranslation: 'Mi mochila pesa mucho.',
      status: 'approved',
    },
    {
      id: 'voc_a1_homework_001',
      word: 'homework',
      translation: 'tarea',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈhoʊmˌwɜrk/',
      example: 'I finished my homework early.',
      exampleTranslation: 'Terminé mi tarea temprano.',
      status: 'approved',
    },
    {
      id: 'voc_a1_exam-test_001',
      word: 'exam / test',
      translation: 'examen',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪgˈzæm/',
      example: 'We have an exam tomorrow.',
      exampleTranslation: 'Tenemos un examen mañana.',
      status: 'approved',
    },
    {
      id: 'voc_a1_grade_001',
      word: 'grade (school)',
      translation: 'calificación',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/greɪd/',
      example: 'She got a good grade on the test.',
      exampleTranslation: 'Ella sacó una buena calificación en el examen.',
      status: 'approved',
    },
    {
      id: 'voc_a1_question_001',
      word: 'question',
      translation: 'pregunta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkwɛstʃən/',
      example: 'I have a question about the homework.',
      exampleTranslation: 'Tengo una pregunta sobre la tarea.',
      status: 'approved',
    },
    {
      id: 'voc_a1_blackboard-whiteboard_001',
      word: 'blackboard / whiteboard',
      translation: 'pizarra',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈblækˌbɔrd/',
      example: 'The teacher wrote on the blackboard.',
      exampleTranslation: 'El maestro escribió en la pizarra.',
      status: 'approved',
    },
    {
      id: 'voc_a1_desk_002',
      word: 'desk (school)',
      translation: 'pupitre',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dɛsk/',
      example: 'Sit at your desk, please.',
      exampleTranslation: 'Siéntate en tu pupitre, por favor.',
      status: 'approved',
    },
    {
      id: 'voc_a1_principal_001',
      word: 'principal',
      translation: 'director/a',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈprɪnsəpəl/',
      example: 'The principal talked to the students.',
      exampleTranslation: 'El director habló con los estudiantes.',
      status: 'approved',
    },
    {
      id: 'voc_a1_university_001',
      word: 'university',
      translation: 'universidad',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 11,
      topic: 'profesiones-y-escuela',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌjunəˈvɜrsəti/',
      example: 'She studies at a good university.',
      exampleTranslation: 'Ella estudia en una buena universidad.',
      status: 'approved',
    },
  ],
}
