import type { ContentBlock } from '../types'

/**
 * A1 Level — Week 6
 * Topic: Semana 6 – Comida y bebidas
 * Curated from: a.md
 * Total items: 74
 */
export const week06: ContentBlock = {
  level: 'A1',
  week: 6,
  topic: 'Semana 6 – Comida y bebidas',
  vocabulary: [
    {
      id: 'voc_a1_bread_001',
      word: 'bread',
      translation: 'pan',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/brɛd/',
      example: 'I eat bread every morning.',
      exampleTranslation: 'Como pan todas las mañanas.',
      status: 'approved',
    },
    {
      id: 'voc_a1_rice_001',
      word: 'rice',
      translation: 'arroz',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/raɪs/',
      example: 'We cook rice for dinner.',
      exampleTranslation: 'Cocinamos arroz para la cena.',
      status: 'approved',
    },
    {
      id: 'voc_a1_pasta_001',
      word: 'pasta',
      translation: 'pasta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpɑstə/',
      example: 'She loves Italian pasta.',
      exampleTranslation: 'A ella le encanta la pasta italiana.',
      status: 'approved',
    },
    {
      id: 'voc_a1_meat_001',
      word: 'meat',
      translation: 'carne',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/mit/',
      example: 'He doesn\'t eat meat.',
      exampleTranslation: 'Él no come carne.',
      status: 'approved',
    },
    {
      id: 'voc_a1_chicken_001',
      word: 'chicken',
      translation: 'pollo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtʃɪkən/',
      example: 'We are having chicken tonight.',
      exampleTranslation: 'Vamos a comer pollo esta noche.',
      status: 'approved',
    },
    {
      id: 'voc_a1_beef_001',
      word: 'beef',
      translation: 'carne de res',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bif/',
      example: 'The soup has beef in it.',
      exampleTranslation: 'La sopa tiene carne de res.',
      status: 'approved',
    },
    {
      id: 'voc_a1_pork_001',
      word: 'pork',
      translation: 'cerdo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pɔrk/',
      example: 'This dish has pork and rice.',
      exampleTranslation: 'Este platillo tiene cerdo y arroz.',
      status: 'approved',
    },
    {
      id: 'voc_a1_fish_001',
      word: 'fish',
      translation: 'pescado',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fɪʃ/',
      example: 'We eat fish on Fridays.',
      exampleTranslation: 'Comemos pescado los viernes.',
      status: 'approved',
    },
    {
      id: 'voc_a1_egg_001',
      word: 'egg',
      translation: 'huevo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɛg/',
      example: 'I eat an egg for breakfast.',
      exampleTranslation: 'Como un huevo en el desayuno.',
      status: 'approved',
    },
    {
      id: 'voc_a1_cheese_001',
      word: 'cheese',
      translation: 'queso',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tʃiz/',
      example: 'I love cheese on my pizza.',
      exampleTranslation: 'Me encanta el queso en mi pizza.',
      status: 'approved',
    },
    {
      id: 'voc_a1_milk_001',
      word: 'milk',
      translation: 'leche',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/mɪlk/',
      example: 'The children drink milk every day.',
      exampleTranslation: 'Los niños beben leche todos los días.',
      status: 'approved',
    },
    {
      id: 'voc_a1_butter_001',
      word: 'butter',
      translation: 'mantequilla',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbʌtər/',
      example: 'Put some butter on the bread.',
      exampleTranslation: 'Pon un poco de mantequilla en el pan.',
      status: 'approved',
    },
    {
      id: 'voc_a1_sugar_001',
      word: 'sugar',
      translation: 'azúcar',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈʃʊgər/',
      example: 'I don\'t take sugar in my coffee.',
      exampleTranslation: 'No le pongo azúcar a mi café.',
      status: 'approved',
    },
    {
      id: 'voc_a1_salt_001',
      word: 'salt',
      translation: 'sal',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/sɔlt/',
      example: 'Add a little salt to the soup.',
      exampleTranslation: 'Agrega un poco de sal a la sopa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_pepper_001',
      word: 'pepper (spice)',
      translation: 'pimienta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpɛpər/',
      example: 'Can you pass the pepper?',
      exampleTranslation: '¿Me pasas la pimienta?',
      status: 'approved',
    },
    {
      id: 'voc_a1_oil_001',
      word: 'oil',
      translation: 'aceite',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɔɪl/',
      example: 'Cook the vegetables with a little oil.',
      exampleTranslation: 'Cocina las verduras con un poco de aceite.',
      status: 'approved',
    },
    {
      id: 'voc_a1_water_001',
      word: 'water',
      translation: 'agua',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈwɔtər/',
      example: 'I drink a lot of water.',
      exampleTranslation: 'Bebo mucha agua.',
      status: 'approved',
    },
    {
      id: 'voc_a1_juice_001',
      word: 'juice',
      translation: 'jugo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dʒus/',
      example: 'She drinks orange juice every morning.',
      exampleTranslation: 'Ella bebe jugo de naranja cada mañana.',
      status: 'approved',
    },
    {
      id: 'voc_a1_coffee_001',
      word: 'coffee',
      translation: 'café',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkɔfi/',
      example: 'I need a cup of coffee.',
      exampleTranslation: 'Necesito una taza de café.',
      status: 'approved',
    },
    {
      id: 'voc_a1_tea_001',
      word: 'tea',
      translation: 'té',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ti/',
      example: 'Would you like some tea?',
      exampleTranslation: '¿Quieres un poco de té?',
      status: 'approved',
    },
    {
      id: 'voc_a1_wine_001',
      word: 'wine',
      translation: 'vino',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/waɪn/',
      example: 'They drank wine at dinner.',
      exampleTranslation: 'Bebieron vino en la cena.',
      status: 'approved',
    },
    {
      id: 'voc_a1_beer_001',
      word: 'beer',
      translation: 'cerveza',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bɪr/',
      example: 'He ordered a cold beer.',
      exampleTranslation: 'Él pidió una cerveza fría.',
      status: 'approved',
    },
    {
      id: 'voc_a1_soda_001',
      word: 'soda',
      translation: 'refresco',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsoʊdə/',
      example: 'The kids want soda with lunch.',
      exampleTranslation: 'Los niños quieren refresco con el almuerzo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_apple_001',
      word: 'apple',
      translation: 'manzana',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈæpəl/',
      example: 'I eat an apple every day.',
      exampleTranslation: 'Como una manzana todos los días.',
      status: 'approved',
    },
    {
      id: 'voc_a1_banana_001',
      word: 'banana',
      translation: 'banana',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bəˈnænə/',
      example: 'Add a banana to the smoothie.',
      exampleTranslation: 'Agrega un plátano al licuado.',
      status: 'approved',
    },
    {
      id: 'voc_a1_orange_002',
      word: 'orange (fruit)',
      translation: 'naranja (fruta)',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɔrɪndʒ/',
      example: 'She peeled an orange.',
      exampleTranslation: 'Ella peló una naranja.',
      status: 'approved',
    },
    {
      id: 'voc_a1_grape_001',
      word: 'grape',
      translation: 'uva',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/greɪp/',
      example: 'The children love grapes.',
      exampleTranslation: 'A los niños les encantan las uvas.',
      status: 'approved',
    },
    {
      id: 'voc_a1_strawberry_001',
      word: 'strawberry',
      translation: 'fresa',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈstrɔˌbɛri/',
      example: 'I bought fresh strawberries.',
      exampleTranslation: 'Compré fresas frescas.',
      status: 'approved',
    },
    {
      id: 'voc_a1_lemon_001',
      word: 'lemon',
      translation: 'limón',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈlɛmən/',
      example: 'Add lemon to the tea.',
      exampleTranslation: 'Agrega limón al té.',
      status: 'approved',
    },
    {
      id: 'voc_a1_watermelon_001',
      word: 'watermelon',
      translation: 'sandía',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈwɔtərˌmɛlən/',
      example: 'Watermelon is perfect in summer.',
      exampleTranslation: 'La sandía es perfecta en verano.',
      status: 'approved',
    },
    {
      id: 'voc_a1_pineapple_001',
      word: 'pineapple',
      translation: 'piña',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpaɪˌnæpəl/',
      example: 'This juice has pineapple in it.',
      exampleTranslation: 'Este jugo tiene piña.',
      status: 'approved',
    },
    {
      id: 'voc_a1_mango_001',
      word: 'mango',
      translation: 'mango',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmæŋgoʊ/',
      example: 'The mango is very sweet.',
      exampleTranslation: 'El mango está muy dulce.',
      status: 'approved',
    },
    {
      id: 'voc_a1_pear_001',
      word: 'pear',
      translation: 'pera',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pɛr/',
      example: 'She ate a pear for a snack.',
      exampleTranslation: 'Ella comió una pera de merienda.',
      status: 'approved',
    },
    {
      id: 'voc_a1_peach_001',
      word: 'peach',
      translation: 'durazno',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pitʃ/',
      example: 'I bought some fresh peaches.',
      exampleTranslation: 'Compré unos duraznos frescos.',
      status: 'approved',
    },
    {
      id: 'voc_a1_cherry_001',
      word: 'cherry',
      translation: 'cereza',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtʃɛri/',
      example: 'The cake has cherries on top.',
      exampleTranslation: 'El pastel tiene cerezas encima.',
      status: 'approved',
    },
    {
      id: 'voc_a1_potato_001',
      word: 'potato',
      translation: 'papa',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pəˈteɪˌtoʊ/',
      example: 'We are cooking potatoes today.',
      exampleTranslation: 'Vamos a cocinar papas hoy.',
      status: 'approved',
    },
    {
      id: 'voc_a1_tomato_001',
      word: 'tomato',
      translation: 'tomate',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/təˈmeɪˌtoʊ/',
      example: 'Add a tomato to the salad.',
      exampleTranslation: 'Agrega un tomate a la ensalada.',
      status: 'approved',
    },
    {
      id: 'voc_a1_onion_001',
      word: 'onion',
      translation: 'cebolla',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈʌnjən/',
      example: 'Chop the onion first.',
      exampleTranslation: 'Pica la cebolla primero.',
      status: 'approved',
    },
    {
      id: 'voc_a1_carrot_001',
      word: 'carrot',
      translation: 'zanahoria',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkɛrət/',
      example: 'Rabbits love carrots.',
      exampleTranslation: 'A los conejos les encantan las zanahorias.',
      status: 'approved',
    },
    {
      id: 'voc_a1_lettuce_001',
      word: 'lettuce',
      translation: 'lechuga',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈlɛtəs/',
      example: 'The salad has fresh lettuce.',
      exampleTranslation: 'La ensalada tiene lechuga fresca.',
      status: 'approved',
    },
    {
      id: 'voc_a1_cucumber_001',
      word: 'cucumber',
      translation: 'pepino',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkjukʌmbər/',
      example: 'I add cucumber to my water.',
      exampleTranslation: 'Le agrego pepino a mi agua.',
      status: 'approved',
    },
    {
      id: 'voc_a1_corn_001',
      word: 'corn',
      translation: 'maíz',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kɔrn/',
      example: 'We grow corn on the farm.',
      exampleTranslation: 'Cultivamos maíz en la granja.',
      status: 'approved',
    },
    {
      id: 'voc_a1_garlic_001',
      word: 'garlic',
      translation: 'ajo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈgɑrlɪk/',
      example: 'The sauce needs more garlic.',
      exampleTranslation: 'La salsa necesita más ajo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_broccoli_001',
      word: 'broccoli',
      translation: 'brócoli',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbrɑkəli/',
      example: 'Eat your broccoli, please.',
      exampleTranslation: 'Come tu brócoli, por favor.',
      status: 'approved',
    },
    {
      id: 'voc_a1_pea_001',
      word: 'pea',
      translation: 'guisante',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pi/',
      example: 'The soup has peas in it.',
      exampleTranslation: 'La sopa tiene guisantes.',
      status: 'approved',
    },
    {
      id: 'voc_a1_breakfast_001',
      word: 'breakfast',
      translation: 'desayuno',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbrɛkfəst/',
      example: 'What do you eat for breakfast?',
      exampleTranslation: '¿Qué comes en el desayuno?',
      status: 'approved',
    },
    {
      id: 'voc_a1_lunch_001',
      word: 'lunch',
      translation: 'almuerzo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/lʌntʃ/',
      example: 'We have lunch at noon.',
      exampleTranslation: 'Almorzamos al mediodía.',
      status: 'approved',
    },
    {
      id: 'voc_a1_dinner_001',
      word: 'dinner',
      translation: 'cena',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdɪnər/',
      example: 'Dinner is ready.',
      exampleTranslation: 'La cena está lista.',
      status: 'approved',
    },
    {
      id: 'voc_a1_snack_001',
      word: 'snack',
      translation: 'merienda',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/snæk/',
      example: 'I want a snack before dinner.',
      exampleTranslation: 'Quiero una merienda antes de la cena.',
      status: 'approved',
    },
    {
      id: 'voc_a1_meal_001',
      word: 'meal',
      translation: 'comida',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/mil/',
      example: 'This was a delicious meal.',
      exampleTranslation: 'Esta fue una comida deliciosa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_food_001',
      word: 'food',
      translation: 'comida/alimento',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fud/',
      example: 'The food here is amazing.',
      exampleTranslation: 'La comida aquí es increíble.',
      status: 'approved',
    },
    {
      id: 'voc_a1_drink_001',
      word: 'drink',
      translation: 'bebida',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/drɪŋk/',
      example: 'Would you like a drink?',
      exampleTranslation: '¿Quieres una bebida?',
      status: 'approved',
    },
    {
      id: 'voc_a1_delicious_001',
      word: 'delicious',
      translation: 'delicioso',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dɪˈlɪʃəs/',
      example: 'This cake is delicious.',
      exampleTranslation: 'Este pastel está delicioso.',
      status: 'approved',
    },
    {
      id: 'voc_a1_tasty_001',
      word: 'tasty',
      translation: 'sabroso',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈteɪsti/',
      example: 'The soup is very tasty.',
      exampleTranslation: 'La sopa está muy sabrosa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_sweet_001',
      word: 'sweet',
      translation: 'dulce',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/swit/',
      example: 'This fruit is very sweet.',
      exampleTranslation: 'Esta fruta es muy dulce.',
      status: 'approved',
    },
    {
      id: 'voc_a1_sour_001',
      word: 'sour',
      translation: 'agrio',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsaʊər/',
      example: 'The lemon is too sour.',
      exampleTranslation: 'El limón está muy agrio.',
      status: 'approved',
    },
    {
      id: 'voc_a1_bitter_001',
      word: 'bitter',
      translation: 'amargo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbɪtər/',
      example: 'I don\'t like bitter coffee.',
      exampleTranslation: 'No me gusta el café amargo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_spicy_001',
      word: 'spicy',
      translation: 'picante',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈspaɪsi/',
      example: 'This dish is very spicy.',
      exampleTranslation: 'Este platillo es muy picante.',
      status: 'approved',
    },
    {
      id: 'voc_a1_fresh_001',
      word: 'fresh',
      translation: 'fresco',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/frɛʃ/',
      example: 'We buy fresh vegetables every week.',
      exampleTranslation: 'Compramos verduras frescas cada semana.',
      status: 'approved',
    },
    {
      id: 'voc_a1_cooked_001',
      word: 'cooked',
      translation: 'cocinado',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kʊkt/',
      example: 'I prefer cooked vegetables.',
      exampleTranslation: 'Prefiero las verduras cocinadas.',
      status: 'approved',
    },
    {
      id: 'voc_a1_raw_001',
      word: 'raw',
      translation: 'crudo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rɑ/',
      example: 'She eats raw carrots.',
      exampleTranslation: 'Ella come zanahorias crudas.',
      status: 'approved',
    },
    {
      id: 'voc_a1_restaurant_001',
      word: 'restaurant',
      translation: 'restaurante',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈrɛstrɑnt/',
      example: 'We ate at a nice restaurant.',
      exampleTranslation: 'Comimos en un buen restaurante.',
      status: 'approved',
    },
    {
      id: 'voc_a1_menu_001',
      word: 'menu',
      translation: 'menú',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmɛnju/',
      example: 'Can I see the menu, please?',
      exampleTranslation: '¿Puedo ver el menú, por favor?',
      status: 'approved',
    },
    {
      id: 'voc_a1_waiter-waitress_001',
      word: 'waiter / waitress',
      translation: 'mesero/a',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈweɪtər/',
      example: 'The waiter brought our food.',
      exampleTranslation: 'El mesero trajo nuestra comida.',
      status: 'approved',
    },
    {
      id: 'voc_a1_bill_001',
      word: 'bill (check)',
      translation: 'cuenta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bɪl/',
      example: 'Can we have the bill, please?',
      exampleTranslation: '¿Nos trae la cuenta, por favor?',
      status: 'approved',
    },
    {
      id: 'voc_a1_order_001',
      word: 'order (food)',
      translation: 'pedir/pedido',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɔrdər/',
      example: 'I would like to order the fish.',
      exampleTranslation: 'Quisiera pedir el pescado.',
      status: 'approved',
    },
    {
      id: 'voc_a1_cook_001',
      word: 'cook (person)',
      translation: 'cocinero',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kʊk/',
      example: 'My father is a great cook.',
      exampleTranslation: 'Mi padre es un gran cocinero.',
      status: 'approved',
    },
    {
      id: 'voc_a1_chef_001',
      word: 'chef',
      translation: 'chef',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ʃɛf/',
      example: 'The chef prepared a special dish.',
      exampleTranslation: 'El chef preparó un platillo especial.',
      status: 'approved',
    },
    {
      id: 'voc_a1_eat_001',
      word: 'eat',
      translation: 'comer',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/it/',
      example: 'We eat dinner at eight.',
      exampleTranslation: 'Cenamos a las ocho.',
      status: 'approved',
    },
    {
      id: 'voc_a1_drink_002',
      word: 'drink (verb)',
      translation: 'beber',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/drɪŋk/',
      example: 'Please drink some water.',
      exampleTranslation: 'Por favor bebe un poco de agua.',
      status: 'approved',
    },
    {
      id: 'voc_a1_cook_002',
      word: 'cook (verb)',
      translation: 'cocinar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kʊk/',
      example: 'I cook dinner every night.',
      exampleTranslation: 'Cocino la cena todas las noches.',
      status: 'approved',
    },
    {
      id: 'voc_a1_buy_001',
      word: 'buy',
      translation: 'comprar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/baɪ/',
      example: 'I need to buy some bread.',
      exampleTranslation: 'Necesito comprar pan.',
      status: 'approved',
    },
    {
      id: 'voc_a1_cut_001',
      word: 'cut',
      translation: 'cortar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kʌt/',
      example: 'Cut the tomatoes into small pieces.',
      exampleTranslation: 'Corta los tomates en trozos pequeños.',
      status: 'approved',
    },
    {
      id: 'voc_a1_taste_001',
      word: 'taste (verb)',
      translation: 'probar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 6,
      topic: 'comida-y-bebidas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/teɪst/',
      example: 'Can I taste the soup?',
      exampleTranslation: '¿Puedo probar la sopa?',
      status: 'approved',
    },
  ],
}
