import type { ContentBlock } from '../types'

/**
 * A1 Level — Week 3
 * Topic: Semana 3 – Familia y personas
 * Curated from: a.md
 * Total items: 90
 */
export const week03: ContentBlock = {
  level: 'A1',
  week: 3,
  topic: 'Semana 3 – Familia y personas',
  vocabulary: [
    {
      id: 'voc_a1_mother-mom_001',
      word: 'mother / mom',
      translation: 'madre / mamá',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmʌðər/',
      example: 'My mother cooks every day.',
      exampleTranslation: 'Mi madre cocina todos los días.',
      status: 'approved',
    },
    {
      id: 'voc_a1_father-dad_001',
      word: 'father / dad',
      translation: 'padre / papá',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfɑðər/',
      example: 'My father works in a bank.',
      exampleTranslation: 'Mi padre trabaja en un banco.',
      status: 'approved',
    },
    {
      id: 'voc_a1_parents_001',
      word: 'parents',
      translation: 'padres',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpɛrənts/',
      example: 'My parents live in Mexico.',
      exampleTranslation: 'Mis padres viven en México.',
      status: 'approved',
    },
    {
      id: 'voc_a1_brother_001',
      word: 'brother',
      translation: 'hermano',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbrʌðər/',
      example: 'I have one brother.',
      exampleTranslation: 'Tengo un hermano.',
      status: 'approved',
    },
    {
      id: 'voc_a1_sister_001',
      word: 'sister',
      translation: 'hermana',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsɪstər/',
      example: 'My sister is a doctor.',
      exampleTranslation: 'Mi hermana es médica.',
      status: 'approved',
    },
    {
      id: 'voc_a1_sibling_001',
      word: 'sibling',
      translation: 'hermano/a',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsɪblɪŋ/',
      example: 'Do you have any siblings?',
      exampleTranslation: '¿Tienes hermanos?',
      status: 'approved',
    },
    {
      id: 'voc_a1_son_001',
      word: 'son',
      translation: 'hijo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/sʌn/',
      example: 'Their son is ten years old.',
      exampleTranslation: 'Su hijo tiene diez años.',
      status: 'approved',
    },
    {
      id: 'voc_a1_daughter_001',
      word: 'daughter',
      translation: 'hija',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdɔtər/',
      example: 'Their daughter goes to this school.',
      exampleTranslation: 'Su hija va a esta escuela.',
      status: 'approved',
    },
    {
      id: 'voc_a1_child_001',
      word: 'child',
      translation: 'niño/a',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tʃaɪld/',
      example: 'She is a happy child.',
      exampleTranslation: 'Ella es una niña feliz.',
      status: 'approved',
    },
    {
      id: 'voc_a1_children_001',
      word: 'children',
      translation: 'niños',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtʃɪldrən/',
      example: 'They have three children.',
      exampleTranslation: 'Tienen tres hijos.',
      status: 'approved',
    },
    {
      id: 'voc_a1_baby_001',
      word: 'baby',
      translation: 'bebé',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbeɪbi/',
      example: 'The baby is sleeping.',
      exampleTranslation: 'El bebé está durmiendo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_husband_001',
      word: 'husband',
      translation: 'esposo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈhʌzbənd/',
      example: 'Her husband is a teacher.',
      exampleTranslation: 'Su esposo es maestro.',
      status: 'approved',
    },
    {
      id: 'voc_a1_wife_001',
      word: 'wife',
      translation: 'esposa',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/waɪf/',
      example: 'His wife works from home.',
      exampleTranslation: 'Su esposa trabaja desde casa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_grandmother-grandma_001',
      word: 'grandmother / grandma',
      translation: 'abuela',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈgrændˌmʌðər/',
      example: 'My grandmother tells great stories.',
      exampleTranslation: 'Mi abuela cuenta buenas historias.',
      status: 'approved',
    },
    {
      id: 'voc_a1_grandfather-grandpa_001',
      word: 'grandfather / grandpa',
      translation: 'abuelo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈgrændˌfɑðər/',
      example: 'My grandfather likes to fish.',
      exampleTranslation: 'A mi abuelo le gusta pescar.',
      status: 'approved',
    },
    {
      id: 'voc_a1_grandparents_001',
      word: 'grandparents',
      translation: 'abuelos',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈgrændˌpɛrənts/',
      example: 'We visit our grandparents on Sundays.',
      exampleTranslation: 'Visitamos a nuestros abuelos los domingos.',
      status: 'approved',
    },
    {
      id: 'voc_a1_aunt_001',
      word: 'aunt',
      translation: 'tía',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ænt/',
      example: 'My aunt lives in Canada.',
      exampleTranslation: 'Mi tía vive en Canadá.',
      status: 'approved',
    },
    {
      id: 'voc_a1_uncle_001',
      word: 'uncle',
      translation: 'tío',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈʌŋkəl/',
      example: 'My uncle has a farm.',
      exampleTranslation: 'Mi tío tiene una granja.',
      status: 'approved',
    },
    {
      id: 'voc_a1_cousin_001',
      word: 'cousin',
      translation: 'primo/a',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkʌzən/',
      example: 'My cousin is my best friend.',
      exampleTranslation: 'Mi primo es mi mejor amigo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_nephew_001',
      word: 'nephew',
      translation: 'sobrino',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈnɛfju/',
      example: 'My nephew is very smart.',
      exampleTranslation: 'Mi sobrino es muy inteligente.',
      status: 'approved',
    },
    {
      id: 'voc_a1_niece_001',
      word: 'niece',
      translation: 'sobrina',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/nis/',
      example: 'My niece loves to dance.',
      exampleTranslation: 'A mi sobrina le encanta bailar.',
      status: 'approved',
    },
    {
      id: 'voc_a1_family_001',
      word: 'family',
      translation: 'familia',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfæməli/',
      example: 'My family is small.',
      exampleTranslation: 'Mi familia es pequeña.',
      status: 'approved',
    },
    {
      id: 'voc_a1_friend_001',
      word: 'friend',
      translation: 'amigo/a',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/frɛnd/',
      example: 'She is my best friend.',
      exampleTranslation: 'Ella es mi mejor amiga.',
      status: 'approved',
    },
    {
      id: 'voc_a1_boyfriend_001',
      word: 'boyfriend',
      translation: 'novio',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbɔɪˌfrɛnd/',
      example: 'Her boyfriend is very kind.',
      exampleTranslation: 'Su novio es muy amable.',
      status: 'approved',
    },
    {
      id: 'voc_a1_girlfriend_001',
      word: 'girlfriend',
      translation: 'novia',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈgɜrlˌfrɛnd/',
      example: 'His girlfriend studies medicine.',
      exampleTranslation: 'Su novia estudia medicina.',
      status: 'approved',
    },
    {
      id: 'voc_a1_man_001',
      word: 'man',
      translation: 'hombre',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/mæn/',
      example: 'The man is waiting outside.',
      exampleTranslation: 'El hombre está esperando afuera.',
      status: 'approved',
    },
    {
      id: 'voc_a1_woman_001',
      word: 'woman',
      translation: 'mujer',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈwʊmən/',
      example: 'The woman is reading a book.',
      exampleTranslation: 'La mujer está leyendo un libro.',
      status: 'approved',
    },
    {
      id: 'voc_a1_boy_001',
      word: 'boy',
      translation: 'niño',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bɔɪ/',
      example: 'The boy is playing soccer.',
      exampleTranslation: 'El niño está jugando fútbol.',
      status: 'approved',
    },
    {
      id: 'voc_a1_girl_001',
      word: 'girl',
      translation: 'niña',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/gɜrl/',
      example: 'The girl likes to sing.',
      exampleTranslation: 'A la niña le gusta cantar.',
      status: 'approved',
    },
    {
      id: 'voc_a1_people_001',
      word: 'people',
      translation: 'gente',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpipəl/',
      example: 'There are many people here.',
      exampleTranslation: 'Hay mucha gente aquí.',
      status: 'approved',
    },
    {
      id: 'voc_a1_person_001',
      word: 'person',
      translation: 'persona',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpɜrsən/',
      example: 'She is a very kind person.',
      exampleTranslation: 'Ella es una persona muy amable.',
      status: 'approved',
    },
    {
      id: 'voc_a1_adult_001',
      word: 'adult',
      translation: 'adulto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈdʌlt/',
      example: 'This movie is for adults.',
      exampleTranslation: 'Esta película es para adultos.',
      status: 'approved',
    },
    {
      id: 'voc_a1_teenager_001',
      word: 'teenager',
      translation: 'adolescente',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtiˌneɪdʒər/',
      example: 'My teenager sleeps a lot.',
      exampleTranslation: 'Mi adolescente duerme mucho.',
      status: 'approved',
    },
    {
      id: 'voc_a1_neighbor_001',
      word: 'neighbor',
      translation: 'vecino',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈneɪbər/',
      example: 'Our neighbor is very friendly.',
      exampleTranslation: 'Nuestro vecino es muy amigable.',
      status: 'approved',
    },
    {
      id: 'voc_a1_guest_001',
      word: 'guest',
      translation: 'invitado',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/gɛst/',
      example: 'We have a guest tonight.',
      exampleTranslation: 'Tenemos un invitado esta noche.',
      status: 'approved',
    },
    {
      id: 'voc_a1_stranger_001',
      word: 'stranger',
      translation: 'desconocido',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈstreɪndʒər/',
      example: 'Don\'t talk to strangers.',
      exampleTranslation: 'No hables con extraños.',
      status: 'approved',
    },
    {
      id: 'voc_a1_couple_001',
      word: 'couple',
      translation: 'pareja',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkʌpəl/',
      example: 'That couple lives next door.',
      exampleTranslation: 'Esa pareja vive al lado.',
      status: 'approved',
    },
    {
      id: 'voc_a1_twins_001',
      word: 'twins',
      translation: 'gemelos',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/twɪnz/',
      example: 'They are twins.',
      exampleTranslation: 'Ellos son gemelos.',
      status: 'approved',
    },
    {
      id: 'voc_a1_married_001',
      word: 'married',
      translation: 'casado',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmɛrid/',
      example: 'They got married last year.',
      exampleTranslation: 'Se casaron el año pasado.',
      status: 'approved',
    },
    {
      id: 'voc_a1_single_001',
      word: 'single',
      translation: 'soltero',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsɪŋgəl/',
      example: 'My brother is still single.',
      exampleTranslation: 'Mi hermano todavía está soltero.',
      status: 'approved',
    },
    {
      id: 'voc_a1_divorced_001',
      word: 'divorced',
      translation: 'divorciado',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dɪˈvɔrst/',
      example: 'Her parents are divorced.',
      exampleTranslation: 'Sus padres están divorciados.',
      status: 'approved',
    },
    {
      id: 'voc_a1_old_001',
      word: 'old',
      translation: 'viejo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/oʊld/',
      example: 'My grandfather is very old.',
      exampleTranslation: 'Mi abuelo es muy viejo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_young_001',
      word: 'young',
      translation: 'joven',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/jʌŋ/',
      example: 'She looks very young.',
      exampleTranslation: 'Ella se ve muy joven.',
      status: 'approved',
    },
    {
      id: 'voc_a1_tall_001',
      word: 'tall',
      translation: 'alto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tɔl/',
      example: 'My brother is very tall.',
      exampleTranslation: 'Mi hermano es muy alto.',
      status: 'approved',
    },
    {
      id: 'voc_a1_short_001',
      word: 'short (person)',
      translation: 'bajo (estatura)',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ʃɔrt/',
      example: 'My sister is short.',
      exampleTranslation: 'Mi hermana es baja.',
      status: 'approved',
    },
    {
      id: 'voc_a1_surname-last-name_001',
      word: 'surname / last name',
      translation: 'apellido',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsɜrˌneɪm/',
      example: 'What is your surname?',
      exampleTranslation: '¿Cuál es tu apellido?',
      status: 'approved',
    },
    {
      id: 'voc_a1_nickname_001',
      word: 'nickname',
      translation: 'apodo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈnɪkˌneɪm/',
      example: 'His nickname is Tony.',
      exampleTranslation: 'Su apodo es Tony.',
      status: 'approved',
    },
    {
      id: 'voc_a1_american_001',
      word: 'American',
      translation: 'estadounidense',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈmɛrɪkən/',
      example: 'She is American.',
      exampleTranslation: 'Ella es estadounidense.',
      status: 'approved',
    },
    {
      id: 'voc_a1_english_001',
      word: 'English',
      translation: 'inglés/a',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɪŋglɪʃ/',
      example: 'He is English.',
      exampleTranslation: 'Él es inglés.',
      status: 'approved',
    },
    {
      id: 'voc_a1_spanish_001',
      word: 'Spanish',
      translation: 'español/a',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈspænɪʃ/',
      example: 'My mother is Spanish.',
      exampleTranslation: 'Mi madre es española.',
      status: 'approved',
    },
    {
      id: 'voc_a1_french_001',
      word: 'French',
      translation: 'francés/a',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/frɛntʃ/',
      example: 'They are French.',
      exampleTranslation: 'Ellos son franceses.',
      status: 'approved',
    },
    {
      id: 'voc_a1_german_001',
      word: 'German',
      translation: 'alemán/a',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdʒɜrmən/',
      example: 'Her husband is German.',
      exampleTranslation: 'Su esposo es alemán.',
      status: 'approved',
    },
    {
      id: 'voc_a1_chinese_001',
      word: 'Chinese',
      translation: 'chino/a',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tʃaɪˈniz/',
      example: 'My neighbor is Chinese.',
      exampleTranslation: 'Mi vecino es chino.',
      status: 'approved',
    },
    {
      id: 'voc_a1_japanese_001',
      word: 'Japanese',
      translation: 'japonés/a',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌdʒæpəˈniz/',
      example: 'This teacher is Japanese.',
      exampleTranslation: 'Esta maestra es japonesa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_mexican_001',
      word: 'Mexican',
      translation: 'mexicano/a',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmɛksəkən/',
      example: 'I am Mexican.',
      exampleTranslation: 'Soy mexicano.',
      status: 'approved',
    },
    {
      id: 'voc_a1_canadian_001',
      word: 'Canadian',
      translation: 'canadiense',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kəˈneɪdiən/',
      example: 'My cousin is Canadian.',
      exampleTranslation: 'Mi primo es canadiense.',
      status: 'approved',
    },
    {
      id: 'voc_a1_brazilian_001',
      word: 'Brazilian',
      translation: 'brasileño/a',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/brəˈzɪljən/',
      example: 'She has a Brazilian friend.',
      exampleTranslation: 'Ella tiene una amiga brasileña.',
      status: 'approved',
    },
    {
      id: 'voc_a1_country_001',
      word: 'country',
      translation: 'país',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkʌntri/',
      example: 'Which country are you from?',
      exampleTranslation: '¿De qué país eres?',
      status: 'approved',
    },
    {
      id: 'voc_a1_nationality_001',
      word: 'nationality',
      translation: 'nacionalidad',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌnæʃəˈnælɪti/',
      example: 'What is your nationality?',
      exampleTranslation: '¿Cuál es tu nacionalidad?',
      status: 'approved',
    },
    {
      id: 'voc_a1_language_001',
      word: 'language',
      translation: 'idioma',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈlæŋgwɪdʒ/',
      example: 'English is a difficult language.',
      exampleTranslation: 'El inglés es un idioma difícil.',
      status: 'approved',
    },
    {
      id: 'voc_a1_introduce_001',
      word: 'introduce',
      translation: 'presentar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌɪntrəˈdus/',
      example: 'Let me introduce my sister.',
      exampleTranslation: 'Déjame presentarte a mi hermana.',
      status: 'approved',
    },
    {
      id: 'voc_a1_meet_001',
      word: 'meet',
      translation: 'conocer/encontrarse',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/mit/',
      example: 'Nice to meet you.',
      exampleTranslation: 'Mucho gusto en conocerte.',
      status: 'approved',
    },
    {
      id: 'voc_a1_relative_001',
      word: 'relative',
      translation: 'pariente',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈrɛlətɪv/',
      example: 'We have relatives in Spain.',
      exampleTranslation: 'Tenemos parientes en España.',
      status: 'approved',
    },
    {
      id: 'voc_a1_only-child_001',
      word: 'only child',
      translation: 'hijo único',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈoʊnli tʃaɪld/',
      example: 'She is an only child.',
      exampleTranslation: 'Ella es hija única.',
      status: 'approved',
    },
    {
      id: 'voc_a1_widow_001',
      word: 'widow',
      translation: 'viuda',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈwɪdoʊ/',
      example: 'My grandmother is a widow.',
      exampleTranslation: 'Mi abuela es viuda.',
      status: 'approved',
    },
    {
      id: 'voc_a1_widower_001',
      word: 'widower',
      translation: 'viudo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈwɪdoʊər/',
      example: 'He became a widower last year.',
      exampleTranslation: 'Él se volvió viudo el año pasado.',
      status: 'approved',
    },
    {
      id: 'voc_a1_engaged_001',
      word: 'engaged',
      translation: 'comprometido',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪnˈgeɪdʒd/',
      example: 'They are engaged now.',
      exampleTranslation: 'Ahora están comprometidos.',
      status: 'approved',
    },
    {
      id: 'voc_a1_wedding_001',
      word: 'wedding',
      translation: 'boda',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈwɛdɪŋ/',
      example: 'The wedding is in June.',
      exampleTranslation: 'La boda es en junio.',
      status: 'approved',
    },
    {
      id: 'voc_a1_love_001',
      word: 'love',
      translation: 'amor',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/lʌv/',
      example: 'I love my family.',
      exampleTranslation: 'Amo a mi familia.',
      status: 'approved',
    },
    {
      id: 'voc_a1_hate_001',
      word: 'hate',
      translation: 'odio',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/heɪt/',
      example: 'She doesn\'t hate anyone.',
      exampleTranslation: 'Ella no odia a nadie.',
      status: 'approved',
    },
    {
      id: 'voc_a1_kiss_001',
      word: 'kiss',
      translation: 'beso',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kɪs/',
      example: 'He gave her a kiss.',
      exampleTranslation: 'Él le dio un beso.',
      status: 'approved',
    },
    {
      id: 'voc_a1_hug_001',
      word: 'hug',
      translation: 'abrazo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/hʌg/',
      example: 'She gave me a big hug.',
      exampleTranslation: 'Ella me dio un gran abrazo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_smile_001',
      word: 'smile',
      translation: 'sonrisa',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/smaɪl/',
      example: 'She has a beautiful smile.',
      exampleTranslation: 'Ella tiene una sonrisa hermosa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_laugh_001',
      word: 'laugh',
      translation: 'risa',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/læf/',
      example: 'We laugh a lot together.',
      exampleTranslation: 'Nos reímos mucho juntos.',
      status: 'approved',
    },
    {
      id: 'voc_a1_cry_001',
      word: 'cry',
      translation: 'llorar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kraɪ/',
      example: 'The baby started to cry.',
      exampleTranslation: 'El bebé empezó a llorar.',
      status: 'approved',
    },
    {
      id: 'voc_a1_care_001',
      word: 'care',
      translation: 'cuidar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kɛr/',
      example: 'She cares about her family.',
      exampleTranslation: 'Ella se preocupa por su familia.',
      status: 'approved',
    },
    {
      id: 'voc_a1_help_001',
      word: 'help',
      translation: 'ayudar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/hɛlp/',
      example: 'Can you help me, please?',
      exampleTranslation: '¿Puedes ayudarme, por favor?',
      status: 'approved',
    },
    {
      id: 'voc_a1_visit_001',
      word: 'visit',
      translation: 'visitar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈvɪzɪt/',
      example: 'We visit our aunt every summer.',
      exampleTranslation: 'Visitamos a nuestra tía cada verano.',
      status: 'approved',
    },
    {
      id: 'voc_a1_call_001',
      word: 'call (phone)',
      translation: 'llamar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kɔl/',
      example: 'I will call you tonight.',
      exampleTranslation: 'Te llamaré esta noche.',
      status: 'approved',
    },
    {
      id: 'voc_a1_invite_001',
      word: 'invite',
      translation: 'invitar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪnˈvaɪt/',
      example: 'We invited our neighbors.',
      exampleTranslation: 'Invitamos a nuestros vecinos.',
      status: 'approved',
    },
    {
      id: 'voc_a1_everyone_001',
      word: 'everyone',
      translation: 'todos',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɛvriˌwʌn/',
      example: 'Everyone is welcome.',
      exampleTranslation: 'Todos son bienvenidos.',
      status: 'approved',
    },
    {
      id: 'voc_a1_someone_001',
      word: 'someone',
      translation: 'alguien',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsʌmˌwʌn/',
      example: 'Someone is at the door.',
      exampleTranslation: 'Alguien está en la puerta.',
      status: 'approved',
    },
    {
      id: 'voc_a1_no-one_001',
      word: 'no one',
      translation: 'nadie',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈnoʊ wʌn/',
      example: 'No one answered the phone.',
      exampleTranslation: 'Nadie contestó el teléfono.',
      status: 'approved',
    },
    {
      id: 'voc_a1_anybody_001',
      word: 'anybody',
      translation: 'alguien/nadie',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɛniˌbɑdi/',
      example: 'Is anybody home?',
      exampleTranslation: '¿Hay alguien en casa?',
      status: 'approved',
    },
    {
      id: 'voc_a1_myself_001',
      word: 'myself',
      translation: 'yo mismo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/maɪˈsɛlf/',
      example: 'I made this cake myself.',
      exampleTranslation: 'Hice este pastel yo mismo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_yourself_001',
      word: 'yourself',
      translation: 'tú mismo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/jɔrˈsɛlf/',
      example: 'Did you do this yourself?',
      exampleTranslation: '¿Hiciste esto tú mismo?',
      status: 'approved',
    },
    {
      id: 'voc_a1_himself_001',
      word: 'himself',
      translation: 'él mismo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/hɪmˈsɛlf/',
      example: 'He introduced himself.',
      exampleTranslation: 'Él se presentó (a sí mismo).',
      status: 'approved',
    },
    {
      id: 'voc_a1_herself_001',
      word: 'herself',
      translation: 'ella misma',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/hərˈsɛlf/',
      example: 'She lives by herself.',
      exampleTranslation: 'Ella vive sola.',
      status: 'approved',
    },
    {
      id: 'voc_a1_ourselves_001',
      word: 'ourselves',
      translation: 'nosotros mismos',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɑrˈsɛlvz/',
      example: 'We did it ourselves.',
      exampleTranslation: 'Lo hicimos nosotros mismos.',
      status: 'approved',
    },
    {
      id: 'voc_a1_themselves_001',
      word: 'themselves',
      translation: 'ellos mismos',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 3,
      topic: 'familia-y-personas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ðɛmˈsɛlvz/',
      example: 'They enjoyed themselves at the party.',
      exampleTranslation: 'Ellos se divirtieron en la fiesta.',
      status: 'approved',
    },
  ],
}
