import type { ContentBlock } from '../types'

/**
 * A1 Level — Week 19
 * Topic: Semana 19 – Verbos irregulares esenciales (base – pasado – participio)
 * Curated from: a.md
 * Total items: 50
 */
export const week19: ContentBlock = {
  level: 'A1',
  week: 19,
  topic: 'Semana 19 – Verbos irregulares esenciales (base – pasado – participio)',
  vocabulary: [
    {
      id: 'voc_a1_go-went-gone_001',
      word: 'go – went – gone',
      translation: 'ir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_see-saw-seen_001',
      word: 'see – saw – seen',
      translation: 'ver',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_eat-ate-eaten_001',
      word: 'eat – ate – eaten',
      translation: 'comer',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_drink-drank-drunk_001',
      word: 'drink – drank – drunk',
      translation: 'beber',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_come-came-come_001',
      word: 'come – came – come',
      translation: 'venir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_take-took-taken_001',
      word: 'take – took – taken',
      translation: 'tomar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_give-gave-given_001',
      word: 'give – gave – given',
      translation: 'dar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_make-made-made_001',
      word: 'make – made – made',
      translation: 'hacer/fabricar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_get-got-gotten_001',
      word: 'get – got – gotten',
      translation: 'obtener',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_say-said-said_001',
      word: 'say – said – said',
      translation: 'decir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_know-knew-known_001',
      word: 'know – knew – known',
      translation: 'saber/conocer',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_think-thought-thought_001',
      word: 'think – thought – thought',
      translation: 'pensar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_find-found-found_001',
      word: 'find – found – found',
      translation: 'encontrar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_tell-told-told_001',
      word: 'tell – told – told',
      translation: 'contar/decir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_become-became-become_001',
      word: 'become – became – become',
      translation: 'convertirse',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_leave-left-left_001',
      word: 'leave – left – left',
      translation: 'irse/dejar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_feel-felt-felt_001',
      word: 'feel – felt – felt',
      translation: 'sentir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_bring-brought-brought_001',
      word: 'bring – brought – brought',
      translation: 'traer',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_begin-began-begun_001',
      word: 'begin – began – begun',
      translation: 'comenzar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_keep-kept-kept_001',
      word: 'keep – kept – kept',
      translation: 'mantener',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_hold-held-held_001',
      word: 'hold – held – held',
      translation: 'sostener',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_write-wrote-written_001',
      word: 'write – wrote – written',
      translation: 'escribir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_stand-stood-stood_001',
      word: 'stand – stood – stood',
      translation: 'pararse',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_hear-heard-heard_001',
      word: 'hear – heard – heard',
      translation: 'oír',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_let-let-let_001',
      word: 'let – let – let',
      translation: 'permitir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_mean-meant-meant_001',
      word: 'mean – meant – meant',
      translation: 'significar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_meet-met-met_001',
      word: 'meet – met – met',
      translation: 'conocer/encontrarse',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_pay-paid-paid_001',
      word: 'pay – paid – paid',
      translation: 'pagar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_run-ran-run_001',
      word: 'run – ran – run',
      translation: 'correr',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_sit-sat-sat_001',
      word: 'sit – sat – sat',
      translation: 'sentarse',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_speak-spoke-spoken_001',
      word: 'speak – spoke – spoken',
      translation: 'hablar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_read-read-read_001',
      word: 'read – read – read',
      translation: 'leer',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_grow-grew-grown_001',
      word: 'grow – grew – grown',
      translation: 'crecer',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_lose-lost-lost_001',
      word: 'lose – lost – lost',
      translation: 'perder',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_fall-fell-fallen_001',
      word: 'fall – fell – fallen',
      translation: 'caer',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_send-sent-sent_001',
      word: 'send – sent – sent',
      translation: 'enviar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_build-built-built_001',
      word: 'build – built – built',
      translation: 'construir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_understand-understood-understood_001',
      word: 'understand – understood – understood',
      translation: 'entender',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_break-broke-broken_001',
      word: 'break – broke – broken',
      translation: 'romper',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_spend-spent-spent_001',
      word: 'spend – spent – spent',
      translation: 'gastar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_drive-drove-driven_001',
      word: 'drive – drove – driven',
      translation: 'conducir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_buy-bought-bought_001',
      word: 'buy – bought – bought',
      translation: 'comprar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_catch-caught-caught_001',
      word: 'catch – caught – caught',
      translation: 'atrapar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_teach-taught-taught_001',
      word: 'teach – taught – taught',
      translation: 'enseñar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_fly-flew-flown_001',
      word: 'fly – flew – flown',
      translation: 'volar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_choose-chose-chosen_001',
      word: 'choose – chose – chosen',
      translation: 'elegir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_wear-wore-worn_001',
      word: 'wear – wore – worn',
      translation: 'llevar puesto',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_sell-sold-sold_001',
      word: 'sell – sold – sold',
      translation: 'vender',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_forget-forgot-forgotten_001',
      word: 'forget – forgot – forgotten',
      translation: 'olvidar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_put-put-put_001',
      word: 'put – put – put',
      translation: 'poner',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 19,
      topic: 'verbos-irregulares-esenciales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
  ],
}
