import type { ContentBlock } from '../types'

/**
 * A1 Level — Week 13
 * Topic: Semana 13 – Emociones y adjetivos adicionales
 * Curated from: a.md
 * Total items: 59
 */
export const week13: ContentBlock = {
  level: 'A1',
  week: 13,
  topic: 'Semana 13 – Emociones y adjetivos adicionales',
  vocabulary: [
    {
      id: 'voc_a1_afraid_001',
      word: 'afraid',
      translation: 'asustado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_scared_001',
      word: 'scared',
      translation: 'asustado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_worried_001',
      word: 'worried',
      translation: 'preocupado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_nervous_001',
      word: 'nervous',
      translation: 'nervioso',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_excited_001',
      word: 'excited',
      translation: 'emocionado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_surprised_001',
      word: 'surprised',
      translation: 'sorprendido',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_bored_001',
      word: 'bored',
      translation: 'aburrido',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_embarrassed_001',
      word: 'embarrassed',
      translation: 'avergonzado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_confused_001',
      word: 'confused',
      translation: 'confundido',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_proud_001',
      word: 'proud',
      translation: 'orgulloso',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_jealous_001',
      word: 'jealous',
      translation: 'celoso',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_lonely_001',
      word: 'lonely',
      translation: 'solitario',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_calm_001',
      word: 'calm',
      translation: 'tranquilo',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_relaxed_001',
      word: 'relaxed',
      translation: 'relajado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_stressed_001',
      word: 'stressed',
      translation: 'estresado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_sick-ill_001',
      word: 'sick / ill',
      translation: 'enfermo',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_healthy_001',
      word: 'healthy',
      translation: 'saludable',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_comfortable_001',
      word: 'comfortable',
      translation: 'cómodo',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_uncomfortable_001',
      word: 'uncomfortable',
      translation: 'incómodo',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_confident_001',
      word: 'confident',
      translation: 'seguro de sí mismo',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_curious_001',
      word: 'curious',
      translation: 'curioso',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_patient_001',
      word: 'patient',
      translation: 'paciente',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_impatient_001',
      word: 'impatient',
      translation: 'impaciente',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_important_001',
      word: 'important',
      translation: 'importante',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_necessary_001',
      word: 'necessary',
      translation: 'necesario',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_possible_001',
      word: 'possible',
      translation: 'posible',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_impossible_001',
      word: 'impossible',
      translation: 'imposible',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_true_001',
      word: 'true',
      translation: 'verdadero',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_false_001',
      word: 'false',
      translation: 'falso',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_real_001',
      word: 'real',
      translation: 'real',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_fake_001',
      word: 'fake',
      translation: 'falso/imitación',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_correct_001',
      word: 'correct',
      translation: 'correcto',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_incorrect_001',
      word: 'incorrect',
      translation: 'incorrecto',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_popular_001',
      word: 'popular',
      translation: 'popular',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_famous_001',
      word: 'famous',
      translation: 'famoso',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_normal_001',
      word: 'normal',
      translation: 'normal',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_strange_001',
      word: 'strange',
      translation: 'extraño',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_weird_001',
      word: 'weird',
      translation: 'raro',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_special_001',
      word: 'special',
      translation: 'especial',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_common_001',
      word: 'common',
      translation: 'común',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_rare_001',
      word: 'rare',
      translation: 'raro/poco común',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_modern_001',
      word: 'modern',
      translation: 'moderno',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_traditional_001',
      word: 'traditional',
      translation: 'tradicional',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_similar_001',
      word: 'similar',
      translation: 'similar',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_simple_001',
      word: 'simple',
      translation: 'simple',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_complicated_001',
      word: 'complicated',
      translation: 'complicado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_careful_001',
      word: 'careful',
      translation: 'cuidadoso',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_careless_001',
      word: 'careless',
      translation: 'descuidado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_honest_001',
      word: 'honest',
      translation: 'honesto',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_polite_001',
      word: 'polite',
      translation: 'cortés',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_rude_001',
      word: 'rude',
      translation: 'grosero',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_generous_001',
      word: 'generous',
      translation: 'generoso',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_selfish_001',
      word: 'selfish',
      translation: 'egoísta',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_hopeful_001',
      word: 'hopeful',
      translation: 'esperanzado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_disappointed_001',
      word: 'disappointed',
      translation: 'decepcionado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_grateful_001',
      word: 'grateful',
      translation: 'agradecido',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_annoyed_001',
      word: 'annoyed',
      translation: 'molesto',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_relieved_001',
      word: 'relieved',
      translation: 'aliviado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_amazed_001',
      word: 'amazed',
      translation: 'asombrado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 13,
      topic: 'emociones-y-adjetivos-adicionales',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
  ],
}
