import type { ContentBlock } from '../types'

/**
 * A1 Level — Week 5
 * Topic: Semana 5 – La casa y los muebles
 * Curated from: a.md
 * Total items: 81
 */
export const week05: ContentBlock = {
  level: 'A1',
  week: 5,
  topic: 'Semana 5 – La casa y los muebles',
  vocabulary: [
    {
      id: 'voc_a1_house_001',
      word: 'house',
      translation: 'casa',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_home_001',
      word: 'home',
      translation: 'hogar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_apartment-flat_001',
      word: 'apartment / flat',
      translation: 'apartamento',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_room_001',
      word: 'room',
      translation: 'habitación',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_bedroom_001',
      word: 'bedroom',
      translation: 'dormitorio',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_bathroom_001',
      word: 'bathroom',
      translation: 'baño',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_kitchen_001',
      word: 'kitchen',
      translation: 'cocina',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_living-room_001',
      word: 'living room',
      translation: 'sala',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_dining-room_001',
      word: 'dining room',
      translation: 'comedor',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_garden_001',
      word: 'garden',
      translation: 'jardín',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_yard_001',
      word: 'yard',
      translation: 'patio',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_garage_001',
      word: 'garage',
      translation: 'garaje',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_roof_001',
      word: 'roof',
      translation: 'techo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_door_001',
      word: 'door',
      translation: 'puerta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_window_001',
      word: 'window',
      translation: 'ventana',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_wall_001',
      word: 'wall',
      translation: 'pared',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_floor_001',
      word: 'floor',
      translation: 'piso',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_ceiling_001',
      word: 'ceiling',
      translation: 'cielo raso',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_stairs_001',
      word: 'stairs',
      translation: 'escaleras',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_table_001',
      word: 'table',
      translation: 'mesa',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_chair_001',
      word: 'chair',
      translation: 'silla',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_sofa-couch_001',
      word: 'sofa / couch',
      translation: 'sofá',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_bed_001',
      word: 'bed',
      translation: 'cama',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_desk_001',
      word: 'desk',
      translation: 'escritorio',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_shelf_001',
      word: 'shelf',
      translation: 'estante',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_wardrobe-closet_001',
      word: 'wardrobe / closet',
      translation: 'armario',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_drawer_001',
      word: 'drawer',
      translation: 'cajón',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_mirror_001',
      word: 'mirror',
      translation: 'espejo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_lamp_001',
      word: 'lamp',
      translation: 'lámpara',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_curtain_001',
      word: 'curtain',
      translation: 'cortina',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_carpet-rug_001',
      word: 'carpet / rug',
      translation: 'alfombra',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_fridge-refrigerator_001',
      word: 'fridge / refrigerator',
      translation: 'refrigerador',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_oven_001',
      word: 'oven',
      translation: 'horno',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_stove_001',
      word: 'stove',
      translation: 'estufa',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_microwave_001',
      word: 'microwave',
      translation: 'microondas',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_washing-machine_001',
      word: 'washing machine',
      translation: 'lavadora',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_dishwasher_001',
      word: 'dishwasher',
      translation: 'lavavajillas',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_television-tv_001',
      word: 'television / TV',
      translation: 'televisor',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_computer_001',
      word: 'computer',
      translation: 'computadora',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_telephone-phone_001',
      word: 'telephone / phone',
      translation: 'teléfono',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_radio_001',
      word: 'radio',
      translation: 'radio',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_clock_001',
      word: 'clock',
      translation: 'reloj',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_fan_001',
      word: 'fan',
      translation: 'ventilador',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_heater_001',
      word: 'heater',
      translation: 'calentador',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_air-conditioner_001',
      word: 'air conditioner',
      translation: 'aire acondicionado',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_plate_001',
      word: 'plate',
      translation: 'plato',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_cup_001',
      word: 'cup',
      translation: 'taza',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_glass_001',
      word: 'glass',
      translation: 'vaso',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_bowl_001',
      word: 'bowl',
      translation: 'tazón',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_spoon_001',
      word: 'spoon',
      translation: 'cuchara',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_fork_001',
      word: 'fork',
      translation: 'tenedor',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_knife_001',
      word: 'knife',
      translation: 'cuchillo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_pan_001',
      word: 'pan',
      translation: 'sartén',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_pot_001',
      word: 'pot',
      translation: 'olla',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_kettle_001',
      word: 'kettle',
      translation: 'tetera',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_key_001',
      word: 'key',
      translation: 'llave',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_lock_001',
      word: 'lock',
      translation: 'cerradura',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_light_002',
      word: 'light (lamp)',
      translation: 'luz',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_switch_001',
      word: 'switch',
      translation: 'interruptor',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_towel_001',
      word: 'towel',
      translation: 'toalla',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_soap_001',
      word: 'soap',
      translation: 'jabón',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_toothbrush_001',
      word: 'toothbrush',
      translation: 'cepillo de dientes',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_pillow_001',
      word: 'pillow',
      translation: 'almohada',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_blanket_001',
      word: 'blanket',
      translation: 'manta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_sheet_001',
      word: 'sheet',
      translation: 'sábana',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_basement_001',
      word: 'basement',
      translation: 'sótano',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_attic_001',
      word: 'attic',
      translation: 'ático',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_balcony_001',
      word: 'balcony',
      translation: 'balcón',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_fence_001',
      word: 'fence',
      translation: 'cerca',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_driveway_001',
      word: 'driveway',
      translation: 'entrada de auto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_mailbox_001',
      word: 'mailbox',
      translation: 'buzón',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_furniture_001',
      word: 'furniture',
      translation: 'muebles',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_address_001',
      word: 'address',
      translation: 'dirección',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_neighborhood_001',
      word: 'neighborhood',
      translation: 'vecindario',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_upstairs_001',
      word: 'upstairs',
      translation: 'arriba',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_downstairs_001',
      word: 'downstairs',
      translation: 'abajo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_move_001',
      word: 'move (house)',
      translation: 'mudarse',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_rent_001',
      word: 'rent',
      translation: 'alquilar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_own_001',
      word: 'own',
      translation: 'poseer',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_decorate_001',
      word: 'decorate',
      translation: 'decorar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_paint_001',
      word: 'paint',
      translation: 'pintar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 5,
      topic: 'la-casa-y-los-muebles',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
  ],
}
