import type { ContentBlock } from '../types'

/**
 * A1 Level — Week 7
 * Topic: Semana 7 – Ropa y cuerpo
 * Curated from: a.md
 * Total items: 77
 */
export const week07: ContentBlock = {
  level: 'A1',
  week: 7,
  topic: 'Semana 7 – Ropa y cuerpo',
  vocabulary: [
    {
      id: 'voc_a1_shirt_001',
      word: 'shirt',
      translation: 'camisa',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ʃɜrt/',
      example: 'He is wearing a blue shirt.',
      exampleTranslation: 'Él lleva una camisa azul.',
      status: 'approved',
    },
    {
      id: 'voc_a1_t-shirt_001',
      word: 't-shirt',
      translation: 'camiseta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtiˌʃɜrt/',
      example: 'I bought a new t-shirt.',
      exampleTranslation: 'Compré una camiseta nueva.',
      status: 'approved',
    },
    {
      id: 'voc_a1_pants-trousers_001',
      word: 'pants / trousers',
      translation: 'pantalones',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pænts/',
      example: 'These pants are too long.',
      exampleTranslation: 'Estos pantalones son muy largos.',
      status: 'approved',
    },
    {
      id: 'voc_a1_jeans_001',
      word: 'jeans',
      translation: 'jeans',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dʒinz/',
      example: 'She wears jeans to work.',
      exampleTranslation: 'Ella usa jeans para trabajar.',
      status: 'approved',
    },
    {
      id: 'voc_a1_dress_001',
      word: 'dress',
      translation: 'vestido',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/drɛs/',
      example: 'She bought a beautiful dress.',
      exampleTranslation: 'Ella compró un vestido hermoso.',
      status: 'approved',
    },
    {
      id: 'voc_a1_skirt_001',
      word: 'skirt',
      translation: 'falda',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/skɜrt/',
      example: 'The skirt matches her shoes.',
      exampleTranslation: 'La falda combina con sus zapatos.',
      status: 'approved',
    },
    {
      id: 'voc_a1_jacket_001',
      word: 'jacket',
      translation: 'chaqueta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdʒækɪt/',
      example: 'Wear a jacket, it\'s cold.',
      exampleTranslation: 'Ponte una chaqueta, hace frío.',
      status: 'approved',
    },
    {
      id: 'voc_a1_coat_001',
      word: 'coat',
      translation: 'abrigo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/koʊt/',
      example: 'Take your coat, it\'s winter.',
      exampleTranslation: 'Lleva tu abrigo, es invierno.',
      status: 'approved',
    },
    {
      id: 'voc_a1_sweater_001',
      word: 'sweater',
      translation: 'suéter',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈswɛtər/',
      example: 'I need a warm sweater.',
      exampleTranslation: 'Necesito un suéter abrigado.',
      status: 'approved',
    },
    {
      id: 'voc_a1_suit_001',
      word: 'suit',
      translation: 'traje',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/sut/',
      example: 'He wore a suit to the interview.',
      exampleTranslation: 'Él usó un traje para la entrevista.',
      status: 'approved',
    },
    {
      id: 'voc_a1_shoes_001',
      word: 'shoes',
      translation: 'zapatos',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ʃuz/',
      example: 'These shoes are very comfortable.',
      exampleTranslation: 'Estos zapatos son muy cómodos.',
      status: 'approved',
    },
    {
      id: 'voc_a1_socks_001',
      word: 'socks',
      translation: 'calcetines',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/sɑks/',
      example: 'I need clean socks.',
      exampleTranslation: 'Necesito calcetines limpios.',
      status: 'approved',
    },
    {
      id: 'voc_a1_hat_001',
      word: 'hat',
      translation: 'sombrero',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/hæt/',
      example: 'She wears a hat in the sun.',
      exampleTranslation: 'Ella usa sombrero bajo el sol.',
      status: 'approved',
    },
    {
      id: 'voc_a1_cap_001',
      word: 'cap',
      translation: 'gorra',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kæp/',
      example: 'He always wears a baseball cap.',
      exampleTranslation: 'Él siempre usa una gorra de béisbol.',
      status: 'approved',
    },
    {
      id: 'voc_a1_gloves_001',
      word: 'gloves',
      translation: 'guantes',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/glʌvz/',
      example: 'Put on your gloves, it\'s cold.',
      exampleTranslation: 'Ponte los guantes, hace frío.',
      status: 'approved',
    },
    {
      id: 'voc_a1_scarf_001',
      word: 'scarf',
      translation: 'bufanda',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/skɑrf/',
      example: 'She wears a scarf in winter.',
      exampleTranslation: 'Ella usa bufanda en invierno.',
      status: 'approved',
    },
    {
      id: 'voc_a1_belt_001',
      word: 'belt',
      translation: 'cinturón',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bɛlt/',
      example: 'This belt is too big for me.',
      exampleTranslation: 'Este cinturón me queda muy grande.',
      status: 'approved',
    },
    {
      id: 'voc_a1_tie_001',
      word: 'tie',
      translation: 'corbata',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/taɪ/',
      example: 'He wears a tie to work.',
      exampleTranslation: 'Él usa corbata para trabajar.',
      status: 'approved',
    },
    {
      id: 'voc_a1_underwear_001',
      word: 'underwear',
      translation: 'ropa interior',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈʌndərˌwɛr/',
      example: 'I need to buy new underwear.',
      exampleTranslation: 'Necesito comprar ropa interior nueva.',
      status: 'approved',
    },
    {
      id: 'voc_a1_pajamas_001',
      word: 'pajamas',
      translation: 'pijama',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pəˈdʒɑməz/',
      example: 'The kids are in their pajamas.',
      exampleTranslation: 'Los niños están en pijama.',
      status: 'approved',
    },
    {
      id: 'voc_a1_shorts_001',
      word: 'shorts',
      translation: 'pantalones cortos',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ʃɔrts/',
      example: 'He wears shorts in summer.',
      exampleTranslation: 'Él usa pantalones cortos en verano.',
      status: 'approved',
    },
    {
      id: 'voc_a1_boots_001',
      word: 'boots',
      translation: 'botas',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/buts/',
      example: 'I bought new boots for winter.',
      exampleTranslation: 'Compré botas nuevas para el invierno.',
      status: 'approved',
    },
    {
      id: 'voc_a1_sandals_001',
      word: 'sandals',
      translation: 'sandalias',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsændəlz/',
      example: 'She wears sandals at the beach.',
      exampleTranslation: 'Ella usa sandalias en la playa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_head_001',
      word: 'head',
      translation: 'cabeza',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/hɛd/',
      example: 'My head hurts a little.',
      exampleTranslation: 'Me duele un poco la cabeza.',
      status: 'approved',
    },
    {
      id: 'voc_a1_hair_001',
      word: 'hair',
      translation: 'cabello',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/hɛr/',
      example: 'She has long black hair.',
      exampleTranslation: 'Ella tiene el cabello largo y negro.',
      status: 'approved',
    },
    {
      id: 'voc_a1_face_001',
      word: 'face',
      translation: 'cara',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/feɪs/',
      example: 'Wash your face before bed.',
      exampleTranslation: 'Lávate la cara antes de dormir.',
      status: 'approved',
    },
    {
      id: 'voc_a1_eye_001',
      word: 'eye',
      translation: 'ojo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/aɪ/',
      example: 'She has beautiful blue eyes.',
      exampleTranslation: 'Ella tiene hermosos ojos azules.',
      status: 'approved',
    },
    {
      id: 'voc_a1_ear_001',
      word: 'ear',
      translation: 'oreja',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪr/',
      example: 'My ear hurts.',
      exampleTranslation: 'Me duele el oído.',
      status: 'approved',
    },
    {
      id: 'voc_a1_nose_001',
      word: 'nose',
      translation: 'nariz',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/noʊz/',
      example: 'His nose is a little red.',
      exampleTranslation: 'Su nariz está un poco roja.',
      status: 'approved',
    },
    {
      id: 'voc_a1_mouth_001',
      word: 'mouth',
      translation: 'boca',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/maʊθ/',
      example: 'Open your mouth, please.',
      exampleTranslation: 'Abre la boca, por favor.',
      status: 'approved',
    },
    {
      id: 'voc_a1_teeth_001',
      word: 'teeth',
      translation: 'dientes',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tiθ/',
      example: 'Brush your teeth every night.',
      exampleTranslation: 'Cepíllate los dientes todas las noches.',
      status: 'approved',
    },
    {
      id: 'voc_a1_tongue_001',
      word: 'tongue',
      translation: 'lengua',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tʌŋ/',
      example: 'The doctor checked her tongue.',
      exampleTranslation: 'El médico revisó su lengua.',
      status: 'approved',
    },
    {
      id: 'voc_a1_neck_001',
      word: 'neck',
      translation: 'cuello',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/nɛk/',
      example: 'My neck hurts from sitting all day.',
      exampleTranslation: 'Me duele el cuello por estar sentado todo el día.',
      status: 'approved',
    },
    {
      id: 'voc_a1_shoulder_001',
      word: 'shoulder',
      translation: 'hombro',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈʃoʊldər/',
      example: 'He carries his bag on one shoulder.',
      exampleTranslation: 'Él lleva su bolsa en un hombro.',
      status: 'approved',
    },
    {
      id: 'voc_a1_arm_001',
      word: 'arm',
      translation: 'brazo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɑrm/',
      example: 'She broke her arm last year.',
      exampleTranslation: 'Ella se rompió el brazo el año pasado.',
      status: 'approved',
    },
    {
      id: 'voc_a1_elbow_001',
      word: 'elbow',
      translation: 'codo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɛlˌboʊ/',
      example: 'I hurt my elbow.',
      exampleTranslation: 'Me lastimé el codo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_hand_001',
      word: 'hand',
      translation: 'mano',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/hænd/',
      example: 'Give me your hand.',
      exampleTranslation: 'Dame tu mano.',
      status: 'approved',
    },
    {
      id: 'voc_a1_finger_001',
      word: 'finger',
      translation: 'dedo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfɪŋgər/',
      example: 'She cut her finger.',
      exampleTranslation: 'Ella se cortó el dedo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_chest_001',
      word: 'chest',
      translation: 'pecho',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tʃɛst/',
      example: 'He has pain in his chest.',
      exampleTranslation: 'Él tiene dolor en el pecho.',
      status: 'approved',
    },
    {
      id: 'voc_a1_back_001',
      word: 'back',
      translation: 'espalda',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bæk/',
      example: 'My back hurts after work.',
      exampleTranslation: 'Me duele la espalda después del trabajo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_stomach_001',
      word: 'stomach',
      translation: 'estómago',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈstʌmək/',
      example: 'My stomach hurts a little.',
      exampleTranslation: 'Me duele un poco el estómago.',
      status: 'approved',
    },
    {
      id: 'voc_a1_leg_001',
      word: 'leg',
      translation: 'pierna',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/lɛg/',
      example: 'She hurt her leg playing soccer.',
      exampleTranslation: 'Ella se lastimó la pierna jugando fútbol.',
      status: 'approved',
    },
    {
      id: 'voc_a1_knee_001',
      word: 'knee',
      translation: 'rodilla',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ni/',
      example: 'He has pain in his knee.',
      exampleTranslation: 'Él tiene dolor en la rodilla.',
      status: 'approved',
    },
    {
      id: 'voc_a1_foot-feet_001',
      word: 'foot / feet',
      translation: 'pie / pies',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fʊt/',
      example: 'My feet hurt from walking.',
      exampleTranslation: 'Me duelen los pies de tanto caminar.',
      status: 'approved',
    },
    {
      id: 'voc_a1_toe_001',
      word: 'toe',
      translation: 'dedo del pie',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/toʊ/',
      example: 'I hurt my toe on the chair.',
      exampleTranslation: 'Me lastimé el dedo del pie con la silla.',
      status: 'approved',
    },
    {
      id: 'voc_a1_skin_001',
      word: 'skin',
      translation: 'piel',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/skɪn/',
      example: 'Her skin is very soft.',
      exampleTranslation: 'Su piel es muy suave.',
      status: 'approved',
    },
    {
      id: 'voc_a1_heart_002',
      word: 'heart (body)',
      translation: 'corazón (órgano)',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/hɑrt/',
      example: 'Exercise is good for your heart.',
      exampleTranslation: 'El ejercicio es bueno para el corazón.',
      status: 'approved',
    },
    {
      id: 'voc_a1_brain_001',
      word: 'brain',
      translation: 'cerebro',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/breɪn/',
      example: 'Reading is good for the brain.',
      exampleTranslation: 'Leer es bueno para el cerebro.',
      status: 'approved',
    },
    {
      id: 'voc_a1_bone_001',
      word: 'bone',
      translation: 'hueso',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/boʊn/',
      example: 'He broke a bone in his hand.',
      exampleTranslation: 'Se rompió un hueso de la mano.',
      status: 'approved',
    },
    {
      id: 'voc_a1_blood_001',
      word: 'blood',
      translation: 'sangre',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/blʌd/',
      example: 'The doctor took a blood sample.',
      exampleTranslation: 'El médico tomó una muestra de sangre.',
      status: 'approved',
    },
    {
      id: 'voc_a1_muscle_001',
      word: 'muscle',
      translation: 'músculo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmʌsəl/',
      example: 'He has strong arm muscles.',
      exampleTranslation: 'Él tiene músculos de brazo fuertes.',
      status: 'approved',
    },
    {
      id: 'voc_a1_nail_001',
      word: 'nail',
      translation: 'uña',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/neɪl/',
      example: 'She painted her nails red.',
      exampleTranslation: 'Ella se pintó las uñas de rojo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_lip_001',
      word: 'lip',
      translation: 'labio',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/lɪp/',
      example: 'Her lip is a little swollen.',
      exampleTranslation: 'Su labio está un poco hinchado.',
      status: 'approved',
    },
    {
      id: 'voc_a1_eyebrow_001',
      word: 'eyebrow',
      translation: 'ceja',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈaɪˌbraʊ/',
      example: 'He raised his eyebrow in surprise.',
      exampleTranslation: 'Él levantó la ceja sorprendido.',
      status: 'approved',
    },
    {
      id: 'voc_a1_eyelash_001',
      word: 'eyelash',
      translation: 'pestaña',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈaɪˌlæʃ/',
      example: 'An eyelash fell into my eye.',
      exampleTranslation: 'Se me cayó una pestaña en el ojo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_chin_001',
      word: 'chin',
      translation: 'mentón',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tʃɪn/',
      example: 'He rested his chin on his hand.',
      exampleTranslation: 'Él apoyó el mentón en su mano.',
      status: 'approved',
    },
    {
      id: 'voc_a1_cheek_001',
      word: 'cheek',
      translation: 'mejilla',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tʃik/',
      example: 'She kissed his cheek.',
      exampleTranslation: 'Ella le besó la mejilla.',
      status: 'approved',
    },
    {
      id: 'voc_a1_forehead_001',
      word: 'forehead',
      translation: 'frente',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfɔrhɛd/',
      example: 'His forehead was sweating.',
      exampleTranslation: 'Su frente estaba sudando.',
      status: 'approved',
    },
    {
      id: 'voc_a1_waist_001',
      word: 'waist',
      translation: 'cintura',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/weɪst/',
      example: 'The belt fits around your waist.',
      exampleTranslation: 'El cinturón se ajusta a tu cintura.',
      status: 'approved',
    },
    {
      id: 'voc_a1_wear_001',
      word: 'wear',
      translation: 'llevar puesto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/wɛr/',
      example: 'What are you going to wear tonight?',
      exampleTranslation: '¿Qué te vas a poner esta noche?',
      status: 'approved',
    },
    {
      id: 'voc_a1_put-on_001',
      word: 'put on',
      translation: 'ponerse',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pʊt ɑn/',
      example: 'Put on your jacket, it\'s cold.',
      exampleTranslation: 'Ponte tu chaqueta, hace frío.',
      status: 'approved',
    },
    {
      id: 'voc_a1_take-off_001',
      word: 'take off',
      translation: 'quitarse',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/teɪk ɔf/',
      example: 'Take off your shoes, please.',
      exampleTranslation: 'Quítate los zapatos, por favor.',
      status: 'approved',
    },
    {
      id: 'voc_a1_dress_002',
      word: 'dress (verb)',
      translation: 'vestirse',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/drɛs/',
      example: 'She dresses very well.',
      exampleTranslation: 'Ella se viste muy bien.',
      status: 'approved',
    },
    {
      id: 'voc_a1_try-on_001',
      word: 'try on',
      translation: 'probarse',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/traɪ ɑn/',
      example: 'Can I try on this shirt?',
      exampleTranslation: '¿Puedo probarme esta camisa?',
      status: 'approved',
    },
    {
      id: 'voc_a1_size_001',
      word: 'size',
      translation: 'talla',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/saɪz/',
      example: 'What size are you?',
      exampleTranslation: '¿Qué talla usas?',
      status: 'approved',
    },
    {
      id: 'voc_a1_fashion_001',
      word: 'fashion',
      translation: 'moda',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfæʃən/',
      example: 'She is interested in fashion.',
      exampleTranslation: 'A ella le interesa la moda.',
      status: 'approved',
    },
    {
      id: 'voc_a1_style_001',
      word: 'style',
      translation: 'estilo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/staɪl/',
      example: 'I like your style.',
      exampleTranslation: 'Me gusta tu estilo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_fabric_001',
      word: 'fabric',
      translation: 'tela',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfæbrɪk/',
      example: 'This fabric feels very soft.',
      exampleTranslation: 'Esta tela se siente muy suave.',
      status: 'approved',
    },
    {
      id: 'voc_a1_cotton_001',
      word: 'cotton',
      translation: 'algodón',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkɑtən/',
      example: 'This shirt is made of cotton.',
      exampleTranslation: 'Esta camisa está hecha de algodón.',
      status: 'approved',
    },
    {
      id: 'voc_a1_wool_001',
      word: 'wool',
      translation: 'lana',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/wʊl/',
      example: 'This sweater is made of wool.',
      exampleTranslation: 'Este suéter está hecho de lana.',
      status: 'approved',
    },
    {
      id: 'voc_a1_leather_001',
      word: 'leather',
      translation: 'cuero',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈlɛðər/',
      example: 'He wears a leather jacket.',
      exampleTranslation: 'Él usa una chaqueta de cuero.',
      status: 'approved',
    },
    {
      id: 'voc_a1_button_001',
      word: 'button',
      translation: 'botón',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbʌtən/',
      example: 'A button fell off my shirt.',
      exampleTranslation: 'Se le cayó un botón a mi camisa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_zipper_001',
      word: 'zipper',
      translation: 'cremallera',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈzɪpər/',
      example: 'The zipper on my jacket is broken.',
      exampleTranslation: 'El cierre de mi chaqueta está roto.',
      status: 'approved',
    },
    {
      id: 'voc_a1_pocket_001',
      word: 'pocket',
      translation: 'bolsillo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpɑkət/',
      example: 'I put my keys in my pocket.',
      exampleTranslation: 'Puse mis llaves en el bolsillo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_sleeve_001',
      word: 'sleeve',
      translation: 'manga',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/sliv/',
      example: 'This shirt has short sleeves.',
      exampleTranslation: 'Esta camisa tiene mangas cortas.',
      status: 'approved',
    },
    {
      id: 'voc_a1_collar_001',
      word: 'collar',
      translation: 'cuello (ropa)',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkɑlər/',
      example: 'His collar is a bit tight.',
      exampleTranslation: 'Su cuello (de la camisa) le queda un poco apretado.',
      status: 'approved',
    },
    {
      id: 'voc_a1_umbrella_001',
      word: 'umbrella',
      translation: 'paraguas',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 7,
      topic: 'ropa-y-cuerpo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ʌmˈbrɛlə/',
      example: 'Take an umbrella, it might rain.',
      exampleTranslation: 'Lleva un paraguas, podría llover.',
      status: 'approved',
    },
  ],
}
