import type { ContentBlock } from '../types'

/**
 * A1 Level — Week 15
 * Topic: Semana 15 – Adverbios comunes y verbos extra (repaso final)
 * Curated from: a.md
 * Total items: 62
 */
export const week15: ContentBlock = {
  level: 'A1',
  week: 15,
  topic: 'Semana 15 – Adverbios comunes y verbos extra (repaso final)',
  vocabulary: [
    {
      id: 'voc_a1_quickly_001',
      word: 'quickly',
      translation: 'rápidamente',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_slowly_001',
      word: 'slowly',
      translation: 'lentamente',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_carefully_001',
      word: 'carefully',
      translation: 'cuidadosamente',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_easily_001',
      word: 'easily',
      translation: 'fácilmente',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_well_001',
      word: 'well',
      translation: 'bien',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_badly_001',
      word: 'badly',
      translation: 'mal',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_loudly_001',
      word: 'loudly',
      translation: 'ruidosamente',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_quietly_001',
      word: 'quietly',
      translation: 'silenciosamente',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_suddenly_001',
      word: 'suddenly',
      translation: 'de repente',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_finally_001',
      word: 'finally',
      translation: 'finalmente',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_immediately_001',
      word: 'immediately',
      translation: 'inmediatamente',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_recently_001',
      word: 'recently',
      translation: 'recientemente',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_yet_001',
      word: 'yet',
      translation: 'todavía/aún',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_again_001',
      word: 'again',
      translation: 'de nuevo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_almost_001',
      word: 'almost',
      translation: 'casi',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_only_001',
      word: 'only',
      translation: 'solo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_just_001',
      word: 'just',
      translation: 'justo/apenas',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_even_001',
      word: 'even',
      translation: 'incluso',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_maybe_001',
      word: 'maybe',
      translation: 'quizás',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_perhaps_001',
      word: 'perhaps',
      translation: 'tal vez',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_probably_001',
      word: 'probably',
      translation: 'probablemente',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_certainly_001',
      word: 'certainly',
      translation: 'ciertamente',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_actually_001',
      word: 'actually',
      translation: 'en realidad',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_exactly_001',
      word: 'exactly',
      translation: 'exactamente',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_especially_001',
      word: 'especially',
      translation: 'especialmente',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_generally_001',
      word: 'generally',
      translation: 'generalmente',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_rarely_001',
      word: 'rarely',
      translation: 'raramente',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_hardly_001',
      word: 'hardly',
      translation: 'apenas',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_enough_001',
      word: 'enough',
      translation: 'suficiente',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_a-lot_001',
      word: 'a lot',
      translation: 'mucho',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_a-little_001',
      word: 'a little',
      translation: 'un poco',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_more_001',
      word: 'more',
      translation: 'más',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_less_001',
      word: 'less',
      translation: 'menos',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_most_001',
      word: 'most',
      translation: 'la mayoría',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_least_001',
      word: 'least',
      translation: 'lo menos',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_agree_001',
      word: 'agree',
      translation: 'estar de acuerdo',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_disagree_001',
      word: 'disagree',
      translation: 'no estar de acuerdo',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_decide_001',
      word: 'decide',
      translation: 'decidir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_choose_001',
      word: 'choose',
      translation: 'elegir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_plan_001',
      word: 'plan',
      translation: 'planear',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_hope_001',
      word: 'hope',
      translation: 'esperar (deseo)',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_wish_001',
      word: 'wish',
      translation: 'desear',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_believe_001',
      word: 'believe',
      translation: 'creer',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_guess_001',
      word: 'guess',
      translation: 'adivinar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_imagine_001',
      word: 'imagine',
      translation: 'imaginar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_dream_001',
      word: 'dream',
      translation: 'soñar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_worry_001',
      word: 'worry',
      translation: 'preocuparse',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_share_001',
      word: 'share',
      translation: 'compartir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_borrow_001',
      word: 'borrow',
      translation: 'pedir prestado',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_lend_001',
      word: 'lend',
      translation: 'prestar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_promise_001',
      word: 'promise',
      translation: 'prometer',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_apologize_001',
      word: 'apologize',
      translation: 'disculparse',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_congratulate_001',
      word: 'congratulate',
      translation: 'felicitar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_celebrate_001',
      word: 'celebrate',
      translation: 'celebrar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_accept_001',
      word: 'accept',
      translation: 'aceptar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_refuse_001',
      word: 'refuse',
      translation: 'rechazar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_allow_001',
      word: 'allow',
      translation: 'permitir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_suggest_001',
      word: 'suggest',
      translation: 'sugerir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_recommend_001',
      word: 'recommend',
      translation: 'recomendar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_explain_001',
      word: 'explain',
      translation: 'explicar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_describe_001',
      word: 'describe',
      translation: 'describir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_depend_001',
      word: 'depend',
      translation: 'depender',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
  ],
}
