import type { ContentBlock } from '../types'

/**
 * A1 Level — Week 2
 * Topic: Semana 2 – Números, días, meses y expresiones de tiempo
 * Curated from: a.md
 * Total items: 88
 */
export const week02: ContentBlock = {
  level: 'A1',
  week: 2,
  topic: 'Semana 2 – Números, días, meses y expresiones de tiempo',
  vocabulary: [
    {
      id: 'voc_a1_twenty-one_001',
      word: 'twenty-one',
      translation: 'veintiuno',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_thirty_001',
      word: 'thirty',
      translation: 'treinta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_forty_001',
      word: 'forty',
      translation: 'cuarenta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_fifty_001',
      word: 'fifty',
      translation: 'cincuenta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_sixty_001',
      word: 'sixty',
      translation: 'sesenta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_seventy_001',
      word: 'seventy',
      translation: 'setenta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_eighty_001',
      word: 'eighty',
      translation: 'ochenta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_ninety_001',
      word: 'ninety',
      translation: 'noventa',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_hundred_001',
      word: 'hundred',
      translation: 'cien',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_thousand_001',
      word: 'thousand',
      translation: 'mil',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_first_001',
      word: 'first',
      translation: 'primero',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_second_001',
      word: 'second',
      translation: 'segundo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_third_001',
      word: 'third',
      translation: 'tercero',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_fourth_001',
      word: 'fourth',
      translation: 'cuarto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_fifth_001',
      word: 'fifth',
      translation: 'quinto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_last_001',
      word: 'last',
      translation: 'último',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_monday_001',
      word: 'Monday',
      translation: 'lunes',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_tuesday_001',
      word: 'Tuesday',
      translation: 'martes',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_wednesday_001',
      word: 'Wednesday',
      translation: 'miércoles',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_thursday_001',
      word: 'Thursday',
      translation: 'jueves',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_friday_001',
      word: 'Friday',
      translation: 'viernes',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_saturday_001',
      word: 'Saturday',
      translation: 'sábado',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_sunday_001',
      word: 'Sunday',
      translation: 'domingo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_day_001',
      word: 'day',
      translation: 'día',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_week_001',
      word: 'week',
      translation: 'semana',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_weekend_001',
      word: 'weekend',
      translation: 'fin de semana',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_january_001',
      word: 'January',
      translation: 'enero',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_february_001',
      word: 'February',
      translation: 'febrero',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_march_001',
      word: 'March',
      translation: 'marzo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_april_001',
      word: 'April',
      translation: 'abril',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_may_001',
      word: 'May',
      translation: 'mayo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_june_001',
      word: 'June',
      translation: 'junio',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_july_001',
      word: 'July',
      translation: 'julio',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_august_001',
      word: 'August',
      translation: 'agosto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_september_001',
      word: 'September',
      translation: 'septiembre',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_october_001',
      word: 'October',
      translation: 'octubre',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_november_001',
      word: 'November',
      translation: 'noviembre',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_december_001',
      word: 'December',
      translation: 'diciembre',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_spring_001',
      word: 'spring',
      translation: 'primavera',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_summer_001',
      word: 'summer',
      translation: 'verano',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_autumn-fall_001',
      word: 'autumn / fall',
      translation: 'otoño',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_winter_001',
      word: 'winter',
      translation: 'invierno',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_season_001',
      word: 'season',
      translation: 'estación',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_today_001',
      word: 'today',
      translation: 'hoy',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_tomorrow_001',
      word: 'tomorrow',
      translation: 'mañana',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_yesterday_001',
      word: 'yesterday',
      translation: 'ayer',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_morning_001',
      word: 'morning',
      translation: 'mañana (parte del día)',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_afternoon_001',
      word: 'afternoon',
      translation: 'tarde',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_evening_001',
      word: 'evening',
      translation: 'noche (temprana)',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_night_001',
      word: 'night',
      translation: 'noche',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_oclock_001',
      word: "o'clock",
      translation: 'en punto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_hour_001',
      word: 'hour',
      translation: 'hora',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_minute_001',
      word: 'minute',
      translation: 'minuto',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_second_002',
      word: 'second (time)',
      translation: 'segundo (tiempo)',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_time_001',
      word: 'time',
      translation: 'tiempo/hora',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_early_001',
      word: 'early',
      translation: 'temprano',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_late_001',
      word: 'late',
      translation: 'tarde',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_always_001',
      word: 'always',
      translation: 'siempre',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_never_001',
      word: 'never',
      translation: 'nunca',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_sometimes_001',
      word: 'sometimes',
      translation: 'a veces',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_often_001',
      word: 'often',
      translation: 'a menudo',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_usually_001',
      word: 'usually',
      translation: 'usualmente',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_half_001',
      word: 'half',
      translation: 'medio/media',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_quarter_001',
      word: 'quarter',
      translation: 'cuarto (fracción)',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_past_001',
      word: 'past',
      translation: 'pasado / y (hora)',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_to_001',
      word: 'to (time)',
      translation: 'menos (hora)',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_date_001',
      word: 'date',
      translation: 'fecha',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_year_001',
      word: 'year',
      translation: 'año',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_month_001',
      word: 'month',
      translation: 'mes',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_calendar_001',
      word: 'calendar',
      translation: 'calendario',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_birthday_001',
      word: 'birthday',
      translation: 'cumpleaños',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_holiday_001',
      word: 'holiday',
      translation: 'día festivo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_vacation_001',
      word: 'vacation',
      translation: 'vacaciones',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_soon_001',
      word: 'soon',
      translation: 'pronto',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_later_001',
      word: 'later',
      translation: 'más tarde',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_before_001',
      word: 'before',
      translation: 'antes',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_after_001',
      word: 'after',
      translation: 'después',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_still_001',
      word: 'still',
      translation: 'todavía',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_already_001',
      word: 'already',
      translation: 'ya',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_ago_001',
      word: 'ago',
      translation: 'hace (tiempo)',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_since_001',
      word: 'since',
      translation: 'desde',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_until_001',
      word: 'until',
      translation: 'hasta',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_while_001',
      word: 'while',
      translation: 'mientras',
      partOfSpeech: 'conjunction',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_noon_001',
      word: 'noon',
      translation: 'mediodía',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_midnight_001',
      word: 'midnight',
      translation: 'medianoche',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_century_001',
      word: 'century',
      translation: 'siglo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_decade_001',
      word: 'decade',
      translation: 'década',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
    {
      id: 'voc_a1_weekday_001',
      word: 'weekday',
      translation: 'día de semana',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 2,
      topic: 'n-meros-d-as-meses-y-expresiones-de-tiempo',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      status: 'approved',
    },
  ],
}
