import type { ContentBlock } from '../types'

/**
 * A1 Level — Week 4
 * Topic: Semana 4 – Colores, formas y adjetivos básicos
 * Curated from: a.md
 * Total items: 89
 */
export const week04: ContentBlock = {
  level: 'A1',
  week: 4,
  topic: 'Semana 4 – Colores, formas y adjetivos básicos',
  vocabulary: [
    {
      id: 'voc_a1_red_001',
      word: 'red',
      translation: 'rojo',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rɛd/',
      example: 'I like your red shirt.',
      exampleTranslation: 'Me gusta tu camisa roja.',
      status: 'approved',
    },
    {
      id: 'voc_a1_blue_001',
      word: 'blue',
      translation: 'azul',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/blu/',
      example: 'The sky is blue today.',
      exampleTranslation: 'El cielo está azul hoy.',
      status: 'approved',
    },
    {
      id: 'voc_a1_green_001',
      word: 'green',
      translation: 'verde',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/grin/',
      example: 'She has green eyes.',
      exampleTranslation: 'Ella tiene ojos verdes.',
      status: 'approved',
    },
    {
      id: 'voc_a1_yellow_001',
      word: 'yellow',
      translation: 'amarillo',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈjɛloʊ/',
      example: 'The banana is yellow.',
      exampleTranslation: 'El plátano es amarillo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_orange_001',
      word: 'orange (color)',
      translation: 'naranja',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɔrɪndʒ/',
      example: 'I bought an orange jacket.',
      exampleTranslation: 'Compré una chaqueta naranja.',
      status: 'approved',
    },
    {
      id: 'voc_a1_purple_001',
      word: 'purple',
      translation: 'morado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈpɜrpəl/',
      example: 'Her dress is purple.',
      exampleTranslation: 'Su vestido es morado.',
      status: 'approved',
    },
    {
      id: 'voc_a1_pink_001',
      word: 'pink',
      translation: 'rosado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pɪŋk/',
      example: 'The flowers are pink.',
      exampleTranslation: 'Las flores son rosadas.',
      status: 'approved',
    },
    {
      id: 'voc_a1_black_001',
      word: 'black',
      translation: 'negro',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/blæk/',
      example: 'He is wearing black shoes.',
      exampleTranslation: 'Él lleva zapatos negros.',
      status: 'approved',
    },
    {
      id: 'voc_a1_white_001',
      word: 'white',
      translation: 'blanco',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/waɪt/',
      example: 'The walls are white.',
      exampleTranslation: 'Las paredes son blancas.',
      status: 'approved',
    },
    {
      id: 'voc_a1_brown_001',
      word: 'brown',
      translation: 'marrón',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/braʊn/',
      example: 'My dog has brown fur.',
      exampleTranslation: 'Mi perro tiene pelaje marrón.',
      status: 'approved',
    },
    {
      id: 'voc_a1_gray-grey_001',
      word: 'gray / grey',
      translation: 'gris',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/greɪ/',
      example: 'The sky is gray before rain.',
      exampleTranslation: 'El cielo está gris antes de la lluvia.',
      status: 'approved',
    },
    {
      id: 'voc_a1_color-colour_001',
      word: 'color / colour',
      translation: 'color',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkʌlər/',
      example: 'What color is your car?',
      exampleTranslation: '¿De qué color es tu carro?',
      status: 'approved',
    },
    {
      id: 'voc_a1_circle_001',
      word: 'circle',
      translation: 'círculo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsɜrkəl/',
      example: 'Draw a circle here.',
      exampleTranslation: 'Dibuja un círculo aquí.',
      status: 'approved',
    },
    {
      id: 'voc_a1_square_001',
      word: 'square',
      translation: 'cuadrado',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/skwɛr/',
      example: 'The box is a square.',
      exampleTranslation: 'La caja tiene forma de cuadrado.',
      status: 'approved',
    },
    {
      id: 'voc_a1_triangle_001',
      word: 'triangle',
      translation: 'triángulo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtraɪˌæŋgəl/',
      example: 'This shape is a triangle.',
      exampleTranslation: 'Esta figura es un triángulo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_rectangle_001',
      word: 'rectangle',
      translation: 'rectángulo',
      partOfSpeech: 'noun',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈrɛktæŋgəl/',
      example: 'The table is a rectangle.',
      exampleTranslation: 'La mesa tiene forma de rectángulo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_star_001',
      word: 'star (shape)',
      translation: 'estrella',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/stɑr/',
      example: 'The children drew a star.',
      exampleTranslation: 'Los niños dibujaron una estrella.',
      status: 'approved',
    },
    {
      id: 'voc_a1_heart_001',
      word: 'heart (shape)',
      translation: 'corazón',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/hɑrt/',
      example: 'She drew a small heart.',
      exampleTranslation: 'Ella dibujó un pequeño corazón.',
      status: 'approved',
    },
    {
      id: 'voc_a1_shape_001',
      word: 'shape',
      translation: 'forma',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ʃeɪp/',
      example: 'What shape is this?',
      exampleTranslation: '¿Qué forma es esta?',
      status: 'approved',
    },
    {
      id: 'voc_a1_big_001',
      word: 'big',
      translation: 'grande',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bɪg/',
      example: 'They live in a big house.',
      exampleTranslation: 'Viven en una casa grande.',
      status: 'approved',
    },
    {
      id: 'voc_a1_small_001',
      word: 'small',
      translation: 'pequeño',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/smɔl/',
      example: 'I have a small dog.',
      exampleTranslation: 'Tengo un perro pequeño.',
      status: 'approved',
    },
    {
      id: 'voc_a1_large_001',
      word: 'large',
      translation: 'grande',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/lɑrdʒ/',
      example: 'We need a large table.',
      exampleTranslation: 'Necesitamos una mesa grande.',
      status: 'approved',
    },
    {
      id: 'voc_a1_tiny_001',
      word: 'tiny',
      translation: 'diminuto',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈtaɪni/',
      example: 'The kitten is tiny.',
      exampleTranslation: 'El gatito es diminuto.',
      status: 'approved',
    },
    {
      id: 'voc_a1_long_001',
      word: 'long',
      translation: 'largo',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/lɔŋ/',
      example: 'She has long hair.',
      exampleTranslation: 'Ella tiene el cabello largo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_short_002',
      word: 'short (length)',
      translation: 'corto',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ʃɔrt/',
      example: 'This is a short movie.',
      exampleTranslation: 'Esta es una película corta.',
      status: 'approved',
    },
    {
      id: 'voc_a1_wide_001',
      word: 'wide',
      translation: 'ancho',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/waɪd/',
      example: 'The street is very wide.',
      exampleTranslation: 'La calle es muy ancha.',
      status: 'approved',
    },
    {
      id: 'voc_a1_narrow_001',
      word: 'narrow',
      translation: 'estrecho',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈnɛroʊ/',
      example: 'This road is narrow.',
      exampleTranslation: 'Este camino es estrecho.',
      status: 'approved',
    },
    {
      id: 'voc_a1_thick_001',
      word: 'thick',
      translation: 'grueso',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/θɪk/',
      example: 'The book is very thick.',
      exampleTranslation: 'El libro es muy grueso.',
      status: 'approved',
    },
    {
      id: 'voc_a1_thin_001',
      word: 'thin',
      translation: 'delgado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/θɪn/',
      example: 'The paper is very thin.',
      exampleTranslation: 'El papel es muy delgado.',
      status: 'approved',
    },
    {
      id: 'voc_a1_heavy_001',
      word: 'heavy',
      translation: 'pesado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈhɛvi/',
      example: 'This bag is heavy.',
      exampleTranslation: 'Esta bolsa es pesada.',
      status: 'approved',
    },
    {
      id: 'voc_a1_light_001',
      word: 'light (weight)',
      translation: 'ligero',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/laɪt/',
      example: 'My backpack is very light.',
      exampleTranslation: 'Mi mochila es muy ligera.',
      status: 'approved',
    },
    {
      id: 'voc_a1_high_001',
      word: 'high',
      translation: 'alto (altura)',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/haɪ/',
      example: 'The mountain is very high.',
      exampleTranslation: 'La montaña es muy alta.',
      status: 'approved',
    },
    {
      id: 'voc_a1_low_001',
      word: 'low',
      translation: 'bajo',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/loʊ/',
      example: 'The table is very low.',
      exampleTranslation: 'La mesa es muy baja.',
      status: 'approved',
    },
    {
      id: 'voc_a1_good_001',
      word: 'good',
      translation: 'bueno',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/gʊd/',
      example: 'This is a good idea.',
      exampleTranslation: 'Esta es una buena idea.',
      status: 'approved',
    },
    {
      id: 'voc_a1_bad_001',
      word: 'bad',
      translation: 'malo',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bæd/',
      example: 'That was a bad day.',
      exampleTranslation: 'Ese fue un mal día.',
      status: 'approved',
    },
    {
      id: 'voc_a1_nice_001',
      word: 'nice',
      translation: 'agradable',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/naɪs/',
      example: 'It was nice to meet you.',
      exampleTranslation: 'Fue agradable conocerte.',
      status: 'approved',
    },
    {
      id: 'voc_a1_beautiful_001',
      word: 'beautiful',
      translation: 'hermoso',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbjutəfəl/',
      example: 'What a beautiful garden!',
      exampleTranslation: '¡Qué jardín tan hermoso!',
      status: 'approved',
    },
    {
      id: 'voc_a1_ugly_001',
      word: 'ugly',
      translation: 'feo',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈʌgli/',
      example: 'I think this color is ugly.',
      exampleTranslation: 'Creo que este color es feo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_pretty_001',
      word: 'pretty',
      translation: 'bonito',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈprɪti/',
      example: 'She has a pretty smile.',
      exampleTranslation: 'Ella tiene una sonrisa bonita.',
      status: 'approved',
    },
    {
      id: 'voc_a1_new_001',
      word: 'new',
      translation: 'nuevo',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/nu/',
      example: 'I bought a new phone.',
      exampleTranslation: 'Compré un teléfono nuevo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_old_002',
      word: 'old (thing)',
      translation: 'viejo/antiguo',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/oʊld/',
      example: 'This is an old car.',
      exampleTranslation: 'Este es un carro viejo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_clean_001',
      word: 'clean',
      translation: 'limpio',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/klin/',
      example: 'The kitchen is clean.',
      exampleTranslation: 'La cocina está limpia.',
      status: 'approved',
    },
    {
      id: 'voc_a1_dirty_001',
      word: 'dirty',
      translation: 'sucio',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdɜrti/',
      example: 'My shoes are dirty.',
      exampleTranslation: 'Mis zapatos están sucios.',
      status: 'approved',
    },
    {
      id: 'voc_a1_easy_001',
      word: 'easy',
      translation: 'fácil',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈizi/',
      example: 'This exercise is easy.',
      exampleTranslation: 'Este ejercicio es fácil.',
      status: 'approved',
    },
    {
      id: 'voc_a1_difficult-hard_001',
      word: 'difficult / hard',
      translation: 'difícil',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdɪfɪkəlt/',
      example: 'English grammar is difficult.',
      exampleTranslation: 'La gramática del inglés es difícil.',
      status: 'approved',
    },
    {
      id: 'voc_a1_hot_001',
      word: 'hot',
      translation: 'caliente',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/hɑt/',
      example: 'The soup is very hot.',
      exampleTranslation: 'La sopa está muy caliente.',
      status: 'approved',
    },
    {
      id: 'voc_a1_cold_001',
      word: 'cold',
      translation: 'frío',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/koʊld/',
      example: 'The water is cold.',
      exampleTranslation: 'El agua está fría.',
      status: 'approved',
    },
    {
      id: 'voc_a1_warm_001',
      word: 'warm',
      translation: 'cálido',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/wɔrm/',
      example: 'Today is warm and sunny.',
      exampleTranslation: 'Hoy está cálido y soleado.',
      status: 'approved',
    },
    {
      id: 'voc_a1_cool_001',
      word: 'cool',
      translation: 'fresco',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kul/',
      example: 'The wind feels cool.',
      exampleTranslation: 'El viento se siente fresco.',
      status: 'approved',
    },
    {
      id: 'voc_a1_fast_001',
      word: 'fast',
      translation: 'rápido',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fæst/',
      example: 'He drives very fast.',
      exampleTranslation: 'Él conduce muy rápido.',
      status: 'approved',
    },
    {
      id: 'voc_a1_slow_001',
      word: 'slow',
      translation: 'lento',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/sloʊ/',
      example: 'The train is slow today.',
      exampleTranslation: 'El tren va lento hoy.',
      status: 'approved',
    },
    {
      id: 'voc_a1_strong_001',
      word: 'strong',
      translation: 'fuerte',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/strɔŋ/',
      example: 'She is very strong.',
      exampleTranslation: 'Ella es muy fuerte.',
      status: 'approved',
    },
    {
      id: 'voc_a1_weak_001',
      word: 'weak',
      translation: 'débil',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/wik/',
      example: 'He feels weak after the flu.',
      exampleTranslation: 'Él se siente débil después de la gripe.',
      status: 'approved',
    },
    {
      id: 'voc_a1_rich_001',
      word: 'rich',
      translation: 'rico',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rɪtʃ/',
      example: 'That family is very rich.',
      exampleTranslation: 'Esa familia es muy rica.',
      status: 'approved',
    },
    {
      id: 'voc_a1_poor_001',
      word: 'poor',
      translation: 'pobre',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pʊr/',
      example: 'Many people here are poor.',
      exampleTranslation: 'Muchas personas aquí son pobres.',
      status: 'approved',
    },
    {
      id: 'voc_a1_happy_001',
      word: 'happy',
      translation: 'feliz',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈhæpi/',
      example: 'I am happy today.',
      exampleTranslation: 'Estoy feliz hoy.',
      status: 'approved',
    },
    {
      id: 'voc_a1_sad_001',
      word: 'sad',
      translation: 'triste',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/sæd/',
      example: 'She looks a little sad.',
      exampleTranslation: 'Ella se ve un poco triste.',
      status: 'approved',
    },
    {
      id: 'voc_a1_angry_001',
      word: 'angry',
      translation: 'enojado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈæŋgri/',
      example: 'My boss is angry with me.',
      exampleTranslation: 'Mi jefe está enojado conmigo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_tired_001',
      word: 'tired',
      translation: 'cansado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/taɪərd/',
      example: 'I am tired after work.',
      exampleTranslation: 'Estoy cansado después del trabajo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_hungry_001',
      word: 'hungry',
      translation: 'hambriento',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈhʌŋgri/',
      example: 'The children are hungry.',
      exampleTranslation: 'Los niños tienen hambre.',
      status: 'approved',
    },
    {
      id: 'voc_a1_thirsty_001',
      word: 'thirsty',
      translation: 'sediento',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈθɜrsti/',
      example: 'I am thirsty, can I have water?',
      exampleTranslation: 'Tengo sed, ¿puedo tomar agua?',
      status: 'approved',
    },
    {
      id: 'voc_a1_full_001',
      word: 'full',
      translation: 'lleno',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fʊl/',
      example: 'The glass is full.',
      exampleTranslation: 'El vaso está lleno.',
      status: 'approved',
    },
    {
      id: 'voc_a1_empty_001',
      word: 'empty',
      translation: 'vacío',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɛmpti/',
      example: 'The fridge is empty.',
      exampleTranslation: 'El refrigerador está vacío.',
      status: 'approved',
    },
    {
      id: 'voc_a1_open_001',
      word: 'open',
      translation: 'abierto',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈoʊpən/',
      example: 'The store is open now.',
      exampleTranslation: 'La tienda está abierta ahora.',
      status: 'approved',
    },
    {
      id: 'voc_a1_closed_001',
      word: 'closed',
      translation: 'cerrado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kloʊzd/',
      example: 'The bank is closed today.',
      exampleTranslation: 'El banco está cerrado hoy.',
      status: 'approved',
    },
    {
      id: 'voc_a1_right_001',
      word: 'right (correct)',
      translation: 'correcto',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/raɪt/',
      example: 'Your answer is right.',
      exampleTranslation: 'Tu respuesta es correcta.',
      status: 'approved',
    },
    {
      id: 'voc_a1_wrong_001',
      word: 'wrong',
      translation: 'incorrecto',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rɔŋ/',
      example: 'Sorry, that number is wrong.',
      exampleTranslation: 'Perdón, ese número está incorrecto.',
      status: 'approved',
    },
    {
      id: 'voc_a1_same_001',
      word: 'same',
      translation: 'mismo',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/seɪm/',
      example: 'We wear the same size.',
      exampleTranslation: 'Usamos la misma talla.',
      status: 'approved',
    },
    {
      id: 'voc_a1_different_001',
      word: 'different',
      translation: 'diferente',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdɪfərənt/',
      example: 'Our opinions are different.',
      exampleTranslation: 'Nuestras opiniones son diferentes.',
      status: 'approved',
    },
    {
      id: 'voc_a1_expensive_001',
      word: 'expensive',
      translation: 'caro',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪkˈspɛnsɪv/',
      example: 'This restaurant is expensive.',
      exampleTranslation: 'Este restaurante es caro.',
      status: 'approved',
    },
    {
      id: 'voc_a1_cheap_001',
      word: 'cheap',
      translation: 'barato',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tʃip/',
      example: 'I found a cheap ticket.',
      exampleTranslation: 'Encontré un boleto barato.',
      status: 'approved',
    },
    {
      id: 'voc_a1_quiet_001',
      word: 'quiet',
      translation: 'silencioso',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkwaɪət/',
      example: 'The library is very quiet.',
      exampleTranslation: 'La biblioteca es muy silenciosa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_noisy_001',
      word: 'noisy',
      translation: 'ruidoso',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈnɔɪzi/',
      example: 'The street is noisy at night.',
      exampleTranslation: 'La calle es ruidosa de noche.',
      status: 'approved',
    },
    {
      id: 'voc_a1_safe_001',
      word: 'safe',
      translation: 'seguro',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/seɪf/',
      example: 'This neighborhood is safe.',
      exampleTranslation: 'Este vecindario es seguro.',
      status: 'approved',
    },
    {
      id: 'voc_a1_dangerous_001',
      word: 'dangerous',
      translation: 'peligroso',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdeɪndʒərəs/',
      example: 'That road is dangerous.',
      exampleTranslation: 'Ese camino es peligroso.',
      status: 'approved',
    },
    {
      id: 'voc_a1_interesting_001',
      word: 'interesting',
      translation: 'interesante',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈɪntrəstɪŋ/',
      example: 'This book is very interesting.',
      exampleTranslation: 'Este libro es muy interesante.',
      status: 'approved',
    },
    {
      id: 'voc_a1_boring_001',
      word: 'boring',
      translation: 'aburrido',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbɔrɪŋ/',
      example: 'The movie was a bit boring.',
      exampleTranslation: 'La película fue un poco aburrida.',
      status: 'approved',
    },
    {
      id: 'voc_a1_funny_001',
      word: 'funny',
      translation: 'gracioso',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfʌni/',
      example: 'My brother is very funny.',
      exampleTranslation: 'Mi hermano es muy gracioso.',
      status: 'approved',
    },
    {
      id: 'voc_a1_serious_001',
      word: 'serious',
      translation: 'serio',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsɪriəs/',
      example: 'This is a serious problem.',
      exampleTranslation: 'Este es un problema serio.',
      status: 'approved',
    },
    {
      id: 'voc_a1_kind_001',
      word: 'kind',
      translation: 'amable',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kaɪnd/',
      example: 'She is always kind to everyone.',
      exampleTranslation: 'Ella siempre es amable con todos.',
      status: 'approved',
    },
    {
      id: 'voc_a1_friendly_001',
      word: 'friendly',
      translation: 'amistoso',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfrɛndli/',
      example: 'Our neighbors are very friendly.',
      exampleTranslation: 'Nuestros vecinos son muy amistosos.',
      status: 'approved',
    },
    {
      id: 'voc_a1_shy_001',
      word: 'shy',
      translation: 'tímido',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ʃaɪ/',
      example: 'My son is a bit shy.',
      exampleTranslation: 'Mi hijo es un poco tímido.',
      status: 'approved',
    },
    {
      id: 'voc_a1_brave_001',
      word: 'brave',
      translation: 'valiente',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/breɪv/',
      example: 'The firefighter was very brave.',
      exampleTranslation: 'El bombero fue muy valiente.',
      status: 'approved',
    },
    {
      id: 'voc_a1_lazy_001',
      word: 'lazy',
      translation: 'perezoso',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈleɪzi/',
      example: 'Don\'t be lazy, help me clean.',
      exampleTranslation: 'No seas perezoso, ayúdame a limpiar.',
      status: 'approved',
    },
    {
      id: 'voc_a1_busy_001',
      word: 'busy',
      translation: 'ocupado',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbɪzi/',
      example: 'I am busy this week.',
      exampleTranslation: 'Estoy ocupado esta semana.',
      status: 'approved',
    },
    {
      id: 'voc_a1_free_001',
      word: 'free (available)',
      translation: 'libre',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/fri/',
      example: 'Are you free tonight?',
      exampleTranslation: '¿Estás libre esta noche?',
      status: 'approved',
    },
    {
      id: 'voc_a1_round_001',
      word: 'round',
      translation: 'redondo',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/raʊnd/',
      example: 'The table is round.',
      exampleTranslation: 'La mesa es redonda.',
      status: 'approved',
    },
    {
      id: 'voc_a1_flat_001',
      word: 'flat',
      translation: 'plano',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/flæt/',
      example: 'The land here is flat.',
      exampleTranslation: 'El terreno aquí es plano.',
      status: 'approved',
    },
    {
      id: 'voc_a1_straight_001',
      word: 'straight',
      translation: 'recto',
      partOfSpeech: 'adjective',
      level: 'A1',
      week: 4,
      topic: 'colores-formas-y-adjetivos-b-sicos',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/streɪt/',
      example: 'Walk straight and turn left.',
      exampleTranslation: 'Camina recto y gira a la izquierda.',
      status: 'approved',
    },
  ],
}
