import type { ContentBlock } from '../types'

/**
 * A1 Level — Week 15
 * Topic: Semana 15 – Adverbios comunes y verbos extra (repaso final)
 * Curated from: a.md
 * Total items: 62
 */
export const week15: ContentBlock = {
  level: 'A1',
  week: 15,
  topic: 'Semana 15 – Adverbios comunes y verbos extra (repaso final)',
  vocabulary: [
    {
      id: 'voc_a1_quickly_001',
      word: 'quickly',
      translation: 'rápidamente',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkwɪkli/',
      example: 'She finished her homework quickly.',
      exampleTranslation: 'Ella terminó su tarea rápidamente.',
      status: 'approved',
    },
    {
      id: 'voc_a1_slowly_001',
      word: 'slowly',
      translation: 'lentamente',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsloʊli/',
      example: 'He walks very slowly.',
      exampleTranslation: 'Él camina muy lentamente.',
      status: 'approved',
    },
    {
      id: 'voc_a1_carefully_001',
      word: 'carefully',
      translation: 'cuidadosamente',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      example: 'Drive carefully, it\'s raining.',
      pronunciation: '/ˈkɛrfəli/',
      example: 'Drive carefully, it\'s raining.',
      exampleTranslation: 'Conduce con cuidado, está lloviendo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_easily_001',
      word: 'easily',
      translation: 'fácilmente',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈizəli/',
      example: 'She learns languages easily.',
      exampleTranslation: 'Ella aprende idiomas fácilmente.',
      status: 'approved',
    },
    {
      id: 'voc_a1_well_001',
      word: 'well',
      translation: 'bien',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/wɛl/',
      example: 'She sings very well.',
      exampleTranslation: 'Ella canta muy bien.',
      status: 'approved',
    },
    {
      id: 'voc_a1_badly_001',
      word: 'badly',
      translation: 'mal',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbædli/',
      example: 'The team played badly today.',
      exampleTranslation: 'El equipo jugó mal hoy.',
      status: 'approved',
    },
    {
      id: 'voc_a1_loudly_001',
      word: 'loudly',
      translation: 'ruidosamente',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈlaʊdli/',
      example: 'The baby cried loudly.',
      exampleTranslation: 'El bebé lloró ruidosamente.',
      status: 'approved',
    },
    {
      id: 'voc_a1_quietly_001',
      word: 'quietly',
      translation: 'silenciosamente',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈkwaɪətli/',
      example: 'Please speak quietly in the library.',
      exampleTranslation: 'Por favor habla en voz baja en la biblioteca.',
      status: 'approved',
    },
    {
      id: 'voc_a1_suddenly_001',
      word: 'suddenly',
      translation: 'de repente',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsʌdənli/',
      example: 'Suddenly, it started to rain.',
      exampleTranslation: 'De repente, empezó a llover.',
      status: 'approved',
    },
    {
      id: 'voc_a1_finally_001',
      word: 'finally',
      translation: 'finalmente',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈfaɪnəli/',
      example: 'We finally arrived home.',
      exampleTranslation: 'Finalmente llegamos a casa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_immediately_001',
      word: 'immediately',
      translation: 'inmediatamente',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪˈmidiətli/',
      example: 'Call the doctor immediately.',
      exampleTranslation: 'Llama al médico inmediatamente.',
      status: 'approved',
    },
    {
      id: 'voc_a1_recently_001',
      word: 'recently',
      translation: 'recientemente',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈrisəntli/',
      example: 'I recently moved to this city.',
      exampleTranslation: 'Recientemente me mudé a esta ciudad.',
      status: 'approved',
    },
    {
      id: 'voc_a1_yet_001',
      word: 'yet',
      translation: 'todavía/aún',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      example: 'I haven\'t finished yet.',
      pronunciation: '/jɛt/',
      example: 'I haven\'t finished yet.',
      exampleTranslation: 'Todavía no he terminado.',
      status: 'approved',
    },
    {
      id: 'voc_a1_again_001',
      word: 'again',
      translation: 'de nuevo',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈgɛn/',
      example: 'Can you say that again?',
      exampleTranslation: '¿Puedes decir eso de nuevo?',
      status: 'approved',
    },
    {
      id: 'voc_a1_almost_001',
      word: 'almost',
      translation: 'casi',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      example: 'It\'s almost time to go.',
      pronunciation: '/ˈɔlmoʊst/',
      example: 'It\'s almost time to go.',
      exampleTranslation: 'Ya casi es hora de irnos.',
      status: 'approved',
    },
    {
      id: 'voc_a1_only_001',
      word: 'only',
      translation: 'solo',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈoʊnli/',
      example: 'I only have five dollars.',
      exampleTranslation: 'Solo tengo cinco dólares.',
      status: 'approved',
    },
    {
      id: 'voc_a1_just_001',
      word: 'just',
      translation: 'justo/apenas',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dʒʌst/',
      example: 'I just arrived home.',
      exampleTranslation: 'Acabo de llegar a casa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_even_001',
      word: 'even',
      translation: 'incluso',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈivən/',
      example: 'Even my mother liked the movie.',
      exampleTranslation: 'Incluso a mi madre le gustó la película.',
      status: 'approved',
    },
    {
      id: 'voc_a1_maybe_001',
      word: 'maybe',
      translation: 'quizás',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈmeɪbi/',
      example: 'Maybe we can go tomorrow.',
      exampleTranslation: 'Quizás podamos ir mañana.',
      status: 'approved',
    },
    {
      id: 'voc_a1_perhaps_001',
      word: 'perhaps',
      translation: 'tal vez',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/pərˈhæps/',
      example: 'Perhaps she forgot the meeting.',
      exampleTranslation: 'Tal vez ella olvidó la reunión.',
      status: 'approved',
    },
    {
      id: 'voc_a1_probably_001',
      word: 'probably',
      translation: 'probablemente',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈprɑbəbli/',
      example: 'It will probably rain tonight.',
      exampleTranslation: 'Probablemente lloverá esta noche.',
      status: 'approved',
    },
    {
      id: 'voc_a1_certainly_001',
      word: 'certainly',
      translation: 'ciertamente',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsɜrtənli/',
      example: 'I will certainly help you.',
      exampleTranslation: 'Ciertamente te ayudaré.',
      status: 'approved',
    },
    {
      id: 'voc_a1_actually_001',
      word: 'actually',
      translation: 'en realidad',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      example: 'Actually, I don\'t like coffee.',
      pronunciation: '/ˈæktʃuəli/',
      example: 'Actually, I don\'t like coffee.',
      exampleTranslation: 'En realidad, no me gusta el café.',
      status: 'approved',
    },
    {
      id: 'voc_a1_exactly_001',
      word: 'exactly',
      translation: 'exactamente',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      example: 'That\'s exactly what I meant.',
      pronunciation: '/ɪgˈzæktli/',
      example: 'That\'s exactly what I meant.',
      exampleTranslation: 'Eso es exactamente lo que quise decir.',
      status: 'approved',
    },
    {
      id: 'voc_a1_especially_001',
      word: 'especially',
      translation: 'especialmente',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪˈspɛʃəli/',
      example: 'I love fruit, especially mangoes.',
      exampleTranslation: 'Me encanta la fruta, especialmente el mango.',
      status: 'approved',
    },
    {
      id: 'voc_a1_generally_001',
      word: 'generally',
      translation: 'generalmente',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈdʒɛnərəli/',
      example: 'I generally wake up at seven.',
      exampleTranslation: 'Generalmente me despierto a las siete.',
      status: 'approved',
    },
    {
      id: 'voc_a1_rarely_001',
      word: 'rarely',
      translation: 'raramente',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈrɛrli/',
      example: 'We rarely eat out.',
      exampleTranslation: 'Rara vez comemos fuera.',
      status: 'approved',
    },
    {
      id: 'voc_a1_hardly_001',
      word: 'hardly',
      translation: 'apenas',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈhɑrdli/',
      example: 'I hardly know him.',
      exampleTranslation: 'Apenas lo conozco.',
      status: 'approved',
    },
    {
      id: 'voc_a1_enough_001',
      word: 'enough',
      translation: 'suficiente',
      partOfSpeech: 'determiner',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      example: 'We don\'t have enough time.',
      pronunciation: '/ɪˈnʌf/',
      example: 'We don\'t have enough time.',
      exampleTranslation: 'No tenemos suficiente tiempo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_a-lot_001',
      word: 'a lot',
      translation: 'mucho',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ə lɑt/',
      example: 'I like this city a lot.',
      exampleTranslation: 'Me gusta mucho esta ciudad.',
      status: 'approved',
    },
    {
      id: 'voc_a1_a-little_001',
      word: 'a little',
      translation: 'un poco',
      partOfSpeech: 'adverb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ə ˈlɪtəl/',
      example: 'I speak a little Spanish.',
      exampleTranslation: 'Hablo un poco de español.',
      status: 'approved',
    },
    {
      id: 'voc_a1_more_001',
      word: 'more',
      translation: 'más',
      partOfSpeech: 'determiner',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/mɔr/',
      example: 'I need more time.',
      exampleTranslation: 'Necesito más tiempo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_less_001',
      word: 'less',
      translation: 'menos',
      partOfSpeech: 'determiner',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/lɛs/',
      example: 'I want less sugar in my coffee.',
      exampleTranslation: 'Quiero menos azúcar en mi café.',
      status: 'approved',
    },
    {
      id: 'voc_a1_most_001',
      word: 'most',
      translation: 'la mayoría',
      partOfSpeech: 'determiner',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/moʊst/',
      example: 'Most students passed the test.',
      exampleTranslation: 'La mayoría de los estudiantes pasaron el examen.',
      status: 'approved',
    },
    {
      id: 'voc_a1_least_001',
      word: 'least',
      translation: 'lo menos',
      partOfSpeech: 'determiner',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/list/',
      example: 'This is the least expensive option.',
      exampleTranslation: 'Esta es la opción menos costosa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_agree_001',
      word: 'agree',
      translation: 'estar de acuerdo',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈgri/',
      example: 'I agree with you.',
      exampleTranslation: 'Estoy de acuerdo contigo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_disagree_001',
      word: 'disagree',
      translation: 'no estar de acuerdo',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌdɪsəˈgri/',
      example: 'I disagree with that idea.',
      exampleTranslation: 'No estoy de acuerdo con esa idea.',
      status: 'approved',
    },
    {
      id: 'voc_a1_decide_001',
      word: 'decide',
      translation: 'decidir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dɪˈsaɪd/',
      example: 'We need to decide today.',
      exampleTranslation: 'Necesitamos decidir hoy.',
      status: 'approved',
    },
    {
      id: 'voc_a1_choose_001',
      word: 'choose',
      translation: 'elegir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/tʃuz/',
      example: 'Choose your favorite color.',
      exampleTranslation: 'Elige tu color favorito.',
      status: 'approved',
    },
    {
      id: 'voc_a1_plan_001',
      word: 'plan',
      translation: 'planear',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/plæn/',
      example: 'We are planning a trip.',
      exampleTranslation: 'Estamos planeando un viaje.',
      status: 'approved',
    },
    {
      id: 'voc_a1_hope_001',
      word: 'hope',
      translation: 'esperar (deseo)',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/hoʊp/',
      example: 'I hope you feel better.',
      exampleTranslation: 'Espero que te sientas mejor.',
      status: 'approved',
    },
    {
      id: 'voc_a1_wish_001',
      word: 'wish',
      translation: 'desear',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/wɪʃ/',
      example: 'I wish you good luck.',
      exampleTranslation: 'Te deseo buena suerte.',
      status: 'approved',
    },
    {
      id: 'voc_a1_believe_001',
      word: 'believe',
      translation: 'creer',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/bɪˈliv/',
      example: 'I believe you.',
      exampleTranslation: 'Te creo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_guess_001',
      word: 'guess',
      translation: 'adivinar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/gɛs/',
      example: 'Guess what happened today!',
      exampleTranslation: '¡Adivina qué pasó hoy!',
      status: 'approved',
    },
    {
      id: 'voc_a1_imagine_001',
      word: 'imagine',
      translation: 'imaginar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪˈmædʒɪn/',
      example: 'Imagine living on the beach.',
      exampleTranslation: 'Imagina vivir en la playa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_dream_001',
      word: 'dream',
      translation: 'soñar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/drim/',
      example: 'I dream about traveling the world.',
      exampleTranslation: 'Sueño con viajar por el mundo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_worry_001',
      word: 'worry',
      translation: 'preocuparse',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      example: 'Don\'t worry about it.',
      pronunciation: '/ˈwɜri/',
      example: 'Don\'t worry about it.',
      exampleTranslation: 'No te preocupes por eso.',
      status: 'approved',
    },
    {
      id: 'voc_a1_share_001',
      word: 'share',
      translation: 'compartir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ʃɛr/',
      example: 'Please share your food.',
      exampleTranslation: 'Por favor comparte tu comida.',
      status: 'approved',
    },
    {
      id: 'voc_a1_borrow_001',
      word: 'borrow',
      translation: 'pedir prestado',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈbɑroʊ/',
      example: 'Can I borrow your pen?',
      exampleTranslation: '¿Puedo pedir prestado tu bolígrafo?',
      status: 'approved',
    },
    {
      id: 'voc_a1_lend_001',
      word: 'lend',
      translation: 'prestar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/lɛnd/',
      example: 'Can you lend me ten dollars?',
      exampleTranslation: '¿Puedes prestarme diez dólares?',
      status: 'approved',
    },
    {
      id: 'voc_a1_promise_001',
      word: 'promise',
      translation: 'prometer',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈprɑməs/',
      example: 'I promise to call you tonight.',
      exampleTranslation: 'Prometo llamarte esta noche.',
      status: 'approved',
    },
    {
      id: 'voc_a1_apologize_001',
      word: 'apologize',
      translation: 'disculparse',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əˈpɑləˌdʒaɪz/',
      example: 'He apologized for being late.',
      exampleTranslation: 'Él se disculpó por llegar tarde.',
      status: 'approved',
    },
    {
      id: 'voc_a1_congratulate_001',
      word: 'congratulate',
      translation: 'felicitar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/kənˈgrætʃəˌleɪt/',
      example: 'We congratulated her on her new job.',
      exampleTranslation: 'La felicitamos por su nuevo trabajo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_celebrate_001',
      word: 'celebrate',
      translation: 'celebrar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˈsɛləˌbreɪt/',
      example: 'We celebrated her birthday together.',
      exampleTranslation: 'Celebramos su cumpleaños juntos.',
      status: 'approved',
    },
    {
      id: 'voc_a1_accept_001',
      word: 'accept',
      translation: 'aceptar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/əkˈsɛpt/',
      example: 'She accepted the job offer.',
      exampleTranslation: 'Ella aceptó la oferta de trabajo.',
      status: 'approved',
    },
    {
      id: 'voc_a1_refuse_001',
      word: 'refuse',
      translation: 'rechazar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/rɪˈfjuz/',
      example: 'He refused to answer the question.',
      exampleTranslation: 'Él se negó a responder la pregunta.',
      status: 'approved',
    },
    {
      id: 'voc_a1_allow_001',
      word: 'allow',
      translation: 'permitir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      example: 'They don\'t allow pets here.',
      pronunciation: '/əˈlaʊ/',
      example: 'They don\'t allow pets here.',
      exampleTranslation: 'No permiten mascotas aquí.',
      status: 'approved',
    },
    {
      id: 'voc_a1_suggest_001',
      word: 'suggest',
      translation: 'sugerir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/səgˈdʒɛst/',
      example: 'I suggest we leave early.',
      exampleTranslation: 'Sugiero que salgamos temprano.',
      status: 'approved',
    },
    {
      id: 'voc_a1_recommend_001',
      word: 'recommend',
      translation: 'recomendar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ˌrɛkəˈmɛnd/',
      example: 'I recommend this restaurant.',
      exampleTranslation: 'Recomiendo este restaurante.',
      status: 'approved',
    },
    {
      id: 'voc_a1_explain_001',
      word: 'explain',
      translation: 'explicar',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/ɪkˈspleɪn/',
      example: 'Can you explain the rules?',
      exampleTranslation: '¿Puedes explicar las reglas?',
      status: 'approved',
    },
    {
      id: 'voc_a1_describe_001',
      word: 'describe',
      translation: 'describir',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dɪˈskraɪb/',
      example: 'Describe your house to me.',
      exampleTranslation: 'Descríbeme tu casa.',
      status: 'approved',
    },
    {
      id: 'voc_a1_depend_001',
      word: 'depend',
      translation: 'depender',
      partOfSpeech: 'verb',
      level: 'A1',
      week: 15,
      topic: 'adverbios-comunes-y-verbos-extra',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'a.md',
      pronunciation: '/dɪˈpɛnd/',
      example: 'It depends on the weather.',
      exampleTranslation: 'Depende del clima.',
      status: 'approved',
    },
  ],
}
