import type { ContentBlock } from '../types'

/**
 * B1 Level Content — Week 2
 * Topic: B1 · Semana 2 – Modismos y expresiones idiomáticas
 * Curated from institutional curriculum (Zero AI)
 */
export const week02: ContentBlock = {
  level: "B1",
  week: 2,
  topic: "B1 · Semana 2 – Modismos y expresiones idiomáticas",
  vocabulary: [
    {
      "id": "voc_b1_once-in-a-blue-moon_037",
      word: "once in a blue moon",
      translation: "muy de vez en cuando",
      partOfSpeech: 'adverb',
      level: "B1",
      week: 2,
      topic: "idioms",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/wʌns ɪn ə blu mun/',
      example: 'I only eat fast food once in a blue moon.',
      exampleTranslation: 'Solo como comida rápida muy de vez en cuando.',
      status: 'approved',
    },
    {
      "id": "voc_b1_break-the-ice_038",
      word: "break the ice",
      translation: "romper el hielo",
      partOfSpeech: 'verb',
      level: "B1",
      week: 2,
      topic: "idioms",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/breɪk ði aɪs/',
      example: 'He told a joke to break the ice.',
      exampleTranslation: 'Él contó un chiste para romper el hielo.',
      status: 'approved',
    },
    {
      "id": "voc_b1_hit-the-books_039",
      word: "hit the books",
      translation: "ponerse a estudiar",
      partOfSpeech: 'verb',
      level: "B1",
      week: 2,
      topic: "idioms",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/hɪt ðə bʊks/',
      example: 'I need to hit the books before the exam.',
      exampleTranslation: 'Necesito ponerme a estudiar antes del examen.',
      status: 'approved',
    },
    {
      "id": "voc_b1_under-the-weather_040",
      word: "under the weather",
      translation: "sentirse mal/indispuesto",
      partOfSpeech: 'adverb',
      level: "B1",
      week: 2,
      topic: "idioms",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈʌndər ðə ˈwɛðər/',
      example: 'I\'m feeling a bit under the weather today.',
      exampleTranslation: 'Me siento un poco mal hoy.',
      status: 'approved',
    },
    {
      "id": "voc_b1_piece-of-cake_041",
      word: "piece of cake",
      translation: "pan comido",
      partOfSpeech: 'adverb',
      level: "B1",
      week: 2,
      topic: "idioms",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/pis əv keɪk/',
      example: 'The test was a piece of cake.',
      exampleTranslation: 'El examen fue pan comido.',
      status: 'approved',
    },
    {
      "id": "voc_b1_cost-an-arm-and-a-leg_042",
      word: "cost an arm and a leg",
      translation: "costar un ojo de la cara",
      partOfSpeech: 'verb',
      level: "B1",
      week: 2,
      topic: "idioms",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/kɔst ən ɑrm ənd ə lɛg/',
      example: 'That car cost an arm and a leg.',
      exampleTranslation: 'Ese carro costó un ojo de la cara.',
      status: 'approved',
    },
    {
      "id": "voc_b1_on-the-ball_043",
      word: "on the ball",
      translation: "atento/competente",
      partOfSpeech: 'adverb',
      level: "B1",
      week: 2,
      topic: "idioms",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ɑn ðə bɔl/',
      example: 'She\'s really on the ball at work.',
      exampleTranslation: 'Ella está muy atenta y competente en el trabajo.',
      status: 'approved',
    },
    {
      "id": "voc_b1_let-the-cat-out-of-the-bag_044",
      word: "let the cat out of the bag",
      translation: "revelar un secreto",
      partOfSpeech: 'verb',
      level: "B1",
      week: 2,
      topic: "idioms",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/lɛt ðə kæt aʊt əv ðə bæg/',
      example: 'He accidentally let the cat out of the bag.',
      exampleTranslation: 'Él sin querer reveló el secreto.',
      status: 'approved',
    },
    {
      "id": "voc_b1_cutting-corners_045",
      word: "cutting corners",
      translation: "hacer las cosas mal por ahorrar",
      partOfSpeech: 'adverb',
      level: "B1",
      week: 2,
      topic: "idioms",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈkʌtɪŋ ˈkɔrnərz/',
      example: 'They finished fast, but they were cutting corners.',
      exampleTranslation: 'Terminaron rápido, pero ahorraron esfuerzo a costa de la calidad.',
      status: 'approved',
    },
    {
      "id": "voc_b1_back-to-square-one_046",
      word: "back to square one",
      translation: "volver al punto de partida",
      partOfSpeech: 'adverb',
      level: "B1",
      week: 2,
      topic: "idioms",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/bæk tu skwɛr wʌn/',
      example: 'The plan failed, so we\'re back to square one.',
      exampleTranslation: 'El plan falló, así que volvemos al punto de partida.',
      status: 'approved',
    },
    {
      "id": "voc_b1_bite-the-bullet_047",
      word: "bite the bullet",
      translation: "aguantar algo difícil",
      partOfSpeech: 'verb',
      level: "B1",
      week: 2,
      topic: "idioms",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/baɪt ðə ˈbʊlɪt/',
      example: 'I decided to bite the bullet and go to the dentist.',
      exampleTranslation: 'Decidí aguantarme y ir al dentista.',
      status: 'approved',
    },
    {
      "id": "voc_b1_call-it-a-day_048",
      word: "call it a day",
      translation: "dar por terminado el día/trabajo",
      partOfSpeech: 'verb',
      level: "B1",
      week: 2,
      topic: "idioms",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/kɔl ɪt ə deɪ/',
      example: 'Let\'s call it a day and go home.',
      exampleTranslation: 'Demos por terminado el día e vámonos a casa.',
      status: 'approved',
    },
    {
      "id": "voc_b1_get-the-ball-rolling_049",
      word: "get the ball rolling",
      translation: "poner algo en marcha",
      partOfSpeech: 'verb',
      level: "B1",
      week: 2,
      topic: "idioms",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/gɛt ðə bɔl ˈroʊlɪŋ/',
      example: 'Let\'s get the ball rolling on this project.',
      exampleTranslation: 'Pongamos en marcha este proyecto.',
      status: 'approved',
    },
    {
      "id": "voc_b1_hang-in-there_050",
      word: "hang in there",
      translation: "aguantar/no rendirse",
      partOfSpeech: 'adverb',
      level: "B1",
      week: 2,
      topic: "idioms",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/hæŋ ɪn ðɛr/',
      example: 'Hang in there, it will get better.',
      exampleTranslation: 'Aguanta, va a mejorar.',
      status: 'approved',
    },
    {
      "id": "voc_b1_in-the-loop_051",
      word: "in the loop",
      translation: "al tanto/informado",
      partOfSpeech: 'adverb',
      level: "B1",
      week: 2,
      topic: "idioms",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ɪn ðə lup/',
      example: 'Please keep me in the loop about this.',
      exampleTranslation: 'Por favor mantenme al tanto de esto.',
      status: 'approved',
    },
    {
      "id": "voc_b1_keep-an-eye-on_052",
      word: "keep an eye on",
      translation: "vigilar",
      partOfSpeech: 'adverb',
      level: "B1",
      week: 2,
      topic: "idioms",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/kip ən aɪ ɑn/',
      example: 'Can you keep an eye on the kids?',
      exampleTranslation: '¿Puedes vigilar a los niños?',
      status: 'approved',
    },
    {
      "id": "voc_b1_the-last-straw_053",
      word: "the last straw",
      translation: "la gota que colma el vaso",
      partOfSpeech: 'adverb',
      level: "B1",
      week: 2,
      topic: "idioms",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ðə læst strɔ/',
      example: 'Losing his keys was the last straw.',
      exampleTranslation: 'Perder sus llaves fue la gota que colmó el vaso.',
      status: 'approved',
    },
    {
      "id": "voc_b1_miss-the-boat_054",
      word: "miss the boat",
      translation: "perder la oportunidad",
      partOfSpeech: 'verb',
      level: "B1",
      week: 2,
      topic: "idioms",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/mɪs ðə boʊt/',
      example: 'If you don\'t apply now, you\'ll miss the boat.',
      exampleTranslation: 'Si no aplicas ahora, perderás la oportunidad.',
      status: 'approved',
    },
    {
      "id": "voc_b1_on-the-same-page_055",
      word: "on the same page",
      translation: "de acuerdo/en sintonía",
      partOfSpeech: 'adverb',
      level: "B1",
      week: 2,
      topic: "idioms",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ɑn ðə seɪm peɪdʒ/',
      example: 'Let\'s make sure we\'re on the same page.',
      exampleTranslation: 'Aseguremos que estamos de acuerdo/en sintonía.',
      status: 'approved',
    },
    {
      "id": "voc_b1_speak-of-the-devil_056",
      word: "speak of the devil",
      translation: "hablando del rey de Roma",
      partOfSpeech: 'adverb',
      level: "B1",
      week: 2,
      topic: "idioms",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/spik əv ðə ˈdɛvəl/',
      example: 'Speak of the devil, here she comes!',
      exampleTranslation: 'Hablando del rey de Roma, ¡ahí viene ella!',
      status: 'approved',
    },
    {
      "id": "voc_b1_the-ball-is-in-your-court_057",
      word: "the ball is in your court",
      translation: "la decisión es tuya ahora",
      partOfSpeech: 'adverb',
      level: "B1",
      week: 2,
      topic: "idioms",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ðə bɔl ɪz ɪn jʊr kɔrt/',
      example: 'I\'ve done my part; the ball is in your court now.',
      exampleTranslation: 'Ya hice mi parte; ahora la decisión es tuya.',
      status: 'approved',
    },
    {
      "id": "voc_b1_time-flies_058",
      word: "time flies",
      translation: "el tiempo vuela",
      partOfSpeech: 'adverb',
      level: "B1",
      week: 2,
      topic: "idioms",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/taɪm flaɪz/',
      example: 'Time flies when you\'re having fun.',
      exampleTranslation: 'El tiempo vuela cuando te diviertes.',
      status: 'approved',
    },
    {
      "id": "voc_b1_up-in-the-air_059",
      word: "up in the air",
      translation: "incierto/sin decidir",
      partOfSpeech: 'adverb',
      level: "B1",
      week: 2,
      topic: "idioms",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ʌp ɪn ði ɛr/',
      example: 'Our vacation plans are still up in the air.',
      exampleTranslation: 'Nuestros planes de vacaciones siguen inciertos.',
      status: 'approved',
    },
    {
      "id": "voc_b1_weather-the-storm_060",
      word: "weather the storm",
      translation: "superar una dificultad",
      partOfSpeech: 'adverb',
      level: "B1",
      week: 2,
      topic: "idioms",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈwɛðər ðə stɔrm/',
      example: 'The company managed to weather the storm.',
      exampleTranslation: 'La empresa logró superar la dificultad.',
      status: 'approved',
    }
  ]
}
