import type { ContentBlock } from '../types'

/**
 * B1 Level Content — Week 5
 * Topic: B1 · Semana 5 – Verbos de argumentación y análisis
 * Curated from institutional curriculum (Zero AI)
 */
export const week05: ContentBlock = {
  level: "B1",
  week: 5,
  topic: "B1 · Semana 5 – Verbos de argumentación y análisis",
  vocabulary: [
    {
      "id": "voc_b1_assume_120",
      word: "assume",
      translation: "suponer",
      partOfSpeech: 'verb',
      level: "B1",
      week: 5,
      topic: "argumentation_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/əˈsum/',
      example: 'I assume you already know the answer.',
      exampleTranslation: 'Supongo que ya sabes la respuesta.',
      status: 'approved',
    },
    {
      "id": "voc_b1_argue-that_121",
      word: "argue (that)",
      translation: "argumentar/sostener que",
      partOfSpeech: 'verb',
      level: "B1",
      week: 5,
      topic: "argumentation_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈɑrgju/',
      example: 'She argues that the plan is too risky.',
      exampleTranslation: 'Ella argumenta que el plan es demasiado arriesgado.',
      status: 'approved',
    },
    {
      "id": "voc_b1_claim_122",
      word: "claim",
      translation: "afirmar/alegar",
      partOfSpeech: 'verb',
      level: "B1",
      week: 5,
      topic: "argumentation_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/kleɪm/',
      example: 'He claims he saw the accident.',
      exampleTranslation: 'Él afirma que vio el accidente.',
      status: 'approved',
    },
    {
      "id": "voc_b1_demonstrate_123",
      word: "demonstrate",
      translation: "demostrar",
      partOfSpeech: 'verb',
      level: "B1",
      week: 5,
      topic: "argumentation_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈdɛmənˌstreɪt/',
      example: 'The study demonstrates a clear pattern.',
      exampleTranslation: 'El estudio demuestra un patrón claro.',
      status: 'approved',
    },
    {
      "id": "voc_b1_emphasize_124",
      word: "emphasize",
      translation: "enfatizar",
      partOfSpeech: 'verb',
      level: "B1",
      week: 5,
      topic: "argumentation_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈɛmfəˌsaɪz/',
      example: 'The teacher emphasized the importance of practice.',
      exampleTranslation: 'El profesor enfatizó la importancia de la práctica.',
      status: 'approved',
    },
    {
      "id": "voc_b1_imply_125",
      word: "imply",
      translation: "insinuar/implicar",
      partOfSpeech: 'verb',
      level: "B1",
      week: 5,
      topic: "argumentation_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ɪmˈplaɪ/',
      example: 'Her tone implied she was upset.',
      exampleTranslation: 'Su tono insinuaba que estaba molesta.',
      status: 'approved',
    },
    {
      "id": "voc_b1_indicate_126",
      word: "indicate",
      translation: "indicar",
      partOfSpeech: 'verb',
      level: "B1",
      week: 5,
      topic: "argumentation_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈɪndəˌkeɪt/',
      example: 'The results indicate a positive trend.',
      exampleTranslation: 'Los resultados indican una tendencia positiva.',
      status: 'approved',
    },
    {
      "id": "voc_b1_justify_127",
      word: "justify",
      translation: "justificar",
      partOfSpeech: 'verb',
      level: "B1",
      week: 5,
      topic: "argumentation_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈdʒʌstəˌfaɪ/',
      example: 'He tried to justify his decision.',
      exampleTranslation: 'Él trató de justificar su decisión.',
      status: 'approved',
    },
    {
      "id": "voc_b1_maintain-an-opinion_128",
      word: "maintain (an opinion)",
      translation: "mantener/sostener una postura",
      partOfSpeech: 'verb',
      level: "B1",
      week: 5,
      topic: "argumentation_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/meɪnˈteɪn/',
      example: 'She maintains that she is innocent.',
      exampleTranslation: 'Ella sostiene que es inocente.',
      status: 'approved',
    },
    {
      "id": "voc_b1_predict_129",
      word: "predict",
      translation: "predecir",
      partOfSpeech: 'verb',
      level: "B1",
      week: 5,
      topic: "argumentation_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/prɪˈdɪkt/',
      example: 'Experts predict a rise in prices.',
      exampleTranslation: 'Los expertos predicen un aumento de precios.',
      status: 'approved',
    },
    {
      "id": "voc_b1_prove_130",
      word: "prove",
      translation: "probar/demostrar",
      partOfSpeech: 'verb',
      level: "B1",
      week: 5,
      topic: "argumentation_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/pruv/',
      example: 'This proves that the theory was correct.',
      exampleTranslation: 'Esto prueba que la teoría era correcta.',
      status: 'approved',
    },
    {
      "id": "voc_b1_reveal_131",
      word: "reveal",
      translation: "revelar",
      partOfSpeech: 'verb',
      level: "B1",
      week: 5,
      topic: "argumentation_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/rɪˈvil/',
      example: 'The report revealed several problems.',
      exampleTranslation: 'El informe reveló varios problemas.',
      status: 'approved',
    },
    {
      "id": "voc_b1_acknowledge_132",
      word: "acknowledge",
      translation: "reconocer",
      partOfSpeech: 'verb',
      level: "B1",
      week: 5,
      topic: "argumentation_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ækˈnɑlɪdʒ/',
      example: 'He acknowledged his mistake.',
      exampleTranslation: 'Él reconoció su error.',
      status: 'approved',
    },
    {
      "id": "voc_b1_analyze_133",
      word: "analyze",
      translation: "analizar",
      partOfSpeech: 'verb',
      level: "B1",
      week: 5,
      topic: "argumentation_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈænəˌlaɪz/',
      example: 'We need to analyze the data carefully.',
      exampleTranslation: 'Necesitamos analizar los datos con cuidado.',
      status: 'approved',
    },
    {
      "id": "voc_b1_assess_134",
      word: "assess",
      translation: "evaluar/valorar",
      partOfSpeech: 'verb',
      level: "B1",
      week: 5,
      topic: "argumentation_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/əˈsɛs/',
      example: 'The teacher will assess our progress.',
      exampleTranslation: 'El profesor evaluará nuestro progreso.',
      status: 'approved',
    },
    {
      "id": "voc_b1_clarify_135",
      word: "clarify",
      translation: "aclarar",
      partOfSpeech: 'verb',
      level: "B1",
      week: 5,
      topic: "argumentation_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈklɛrəˌfaɪ/',
      example: 'Can you clarify your point?',
      exampleTranslation: '¿Puedes aclarar tu punto?',
      status: 'approved',
    },
    {
      "id": "voc_b1_conclude_136",
      word: "conclude",
      translation: "concluir",
      partOfSpeech: 'verb',
      level: "B1",
      week: 5,
      topic: "argumentation_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/kənˈklud/',
      example: 'The study concludes that exercise helps sleep.',
      exampleTranslation: 'El estudio concluye que el ejercicio ayuda a dormir.',
      status: 'approved',
    },
    {
      "id": "voc_b1_contradict_137",
      word: "contradict",
      translation: "contradecir",
      partOfSpeech: 'verb',
      level: "B1",
      week: 5,
      topic: "argumentation_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˌkɑntrəˈdɪkt/',
      example: 'His statement contradicts the evidence.',
      exampleTranslation: 'Su declaración contradice la evidencia.',
      status: 'approved',
    },
    {
      "id": "voc_b1_distinguish_138",
      word: "distinguish",
      translation: "distinguir",
      partOfSpeech: 'verb',
      level: "B1",
      week: 5,
      topic: "argumentation_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/dɪˈstɪŋgwɪʃ/',
      example: 'It\'s hard to distinguish the two versions.',
      exampleTranslation: 'Es difícil distinguir las dos versiones.',
      status: 'approved',
    },
    {
      "id": "voc_b1_elaborate-on_139",
      word: "elaborate (on)",
      translation: "desarrollar/profundizar en",
      partOfSpeech: 'verb',
      level: "B1",
      week: 5,
      topic: "argumentation_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ɪˈlæbəˌreɪt/',
      example: 'Could you elaborate on that point?',
      exampleTranslation: '¿Podrías desarrollar más ese punto?',
      status: 'approved',
    },
    {
      "id": "voc_b1_examine_140",
      word: "examine",
      translation: "examinar",
      partOfSpeech: 'verb',
      level: "B1",
      week: 5,
      topic: "argumentation_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ɪgˈzæmɪn/',
      example: 'The doctor examined the results.',
      exampleTranslation: 'El médico examinó los resultados.',
      status: 'approved',
    },
    {
      "id": "voc_b1_highlight_141",
      word: "highlight",
      translation: "destacar",
      partOfSpeech: 'verb',
      level: "B1",
      week: 5,
      topic: "argumentation_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈhaɪˌlaɪt/',
      example: 'The report highlights the main risks.',
      exampleTranslation: 'El informe destaca los principales riesgos.',
      status: 'approved',
    },
    {
      "id": "voc_b1_illustrate-an-idea_142",
      word: "illustrate (an idea)",
      translation: "ilustrar (una idea)",
      partOfSpeech: 'verb',
      level: "B1",
      week: 5,
      topic: "argumentation_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈɪləˌstreɪt/',
      example: 'This example illustrates the problem well.',
      exampleTranslation: 'Este ejemplo ilustra bien el problema.',
      status: 'approved',
    },
    {
      "id": "voc_b1_interpret_143",
      word: "interpret",
      translation: "interpretar",
      partOfSpeech: 'verb',
      level: "B1",
      week: 5,
      topic: "argumentation_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ɪnˈtɜrprɪt/',
      example: 'She interpreted the data differently.',
      exampleTranslation: 'Ella interpretó los datos de forma diferente.',
      status: 'approved',
    },
    {
      "id": "voc_b1_outline-a-plan_144",
      word: "outline (a plan)",
      translation: "esbozar (un plan)",
      partOfSpeech: 'verb',
      level: "B1",
      week: 5,
      topic: "argumentation_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈaʊtˌlaɪn/',
      example: 'Let me outline the main steps.',
      exampleTranslation: 'Déjame esbozar los pasos principales.',
      status: 'approved',
    },
    {
      "id": "voc_b1_summarize_145",
      word: "summarize",
      translation: "resumir",
      partOfSpeech: 'verb',
      level: "B1",
      week: 5,
      topic: "argumentation_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈsʌməˌraɪz/',
      example: 'Can you summarize the article for me?',
      exampleTranslation: '¿Puedes resumirme el artículo?',
      status: 'approved',
    }
  ]
}
