import type { ContentBlock } from '../types'

/**
 * B1 Level Content — Week 3
 * Topic: Tecnología digital e innovación
 * Curated from institutional curriculum (Zero AI)
 */
export const week03: ContentBlock = {
  level: 'B1',
  week: 3,
  topic: 'Tecnología digital e innovación',
  vocabulary: [
    {
      id: 'voc_b1_artificial-intelligence_073',
      word: 'artificial intelligence',
      translation: 'inteligencia artificial',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 3,
      topic: 'tecnologia-digital',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_algorithm_074',
      word: 'algorithm',
      translation: 'algoritmo',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 3,
      topic: 'tecnologia-digital',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_automation_075',
      word: 'automation',
      translation: 'automatización',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 3,
      topic: 'tecnologia-digital',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_cybersecurity_076',
      word: 'cybersecurity',
      translation: 'ciberseguridad',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 3,
      topic: 'tecnologia-digital',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_privacy_077',
      word: 'privacy',
      translation: 'privacidad / confidencialidad',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 3,
      topic: 'tecnologia-digital',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_database_078',
      word: 'database',
      translation: 'base de datos',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 3,
      topic: 'tecnologia-digital',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_software_079',
      word: 'software',
      translation: 'software / programas informáticos',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 3,
      topic: 'tecnologia-digital',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_hardware_080',
      word: 'hardware',
      translation: 'hardware / componentes físicos',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 3,
      topic: 'tecnologia-digital',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_device_081',
      word: 'device',
      translation: 'dispositivo / aparato electrónico',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 3,
      topic: 'tecnologia-digital',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_digital_082',
      word: 'digital',
      translation: 'digital',
      partOfSpeech: 'adjective',
      level: 'B1',
      week: 3,
      topic: 'tecnologia-digital',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_virtual_083',
      word: 'virtual',
      translation: 'virtual / simulado',
      partOfSpeech: 'adjective',
      level: 'B1',
      week: 3,
      topic: 'tecnologia-digital',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_cloud-computing_084',
      word: 'cloud computing',
      translation: 'computación en la nube',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 3,
      topic: 'tecnologia-digital',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_wireless_085',
      word: 'wireless',
      translation: 'inalámbrico',
      partOfSpeech: 'adjective',
      level: 'B1',
      week: 3,
      topic: 'tecnologia-digital',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_bandwidth_086',
      word: 'bandwidth',
      translation: 'ancho de banda',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 3,
      topic: 'tecnologia-digital',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_download_087',
      word: 'download',
      translation: 'descargar archivos',
      partOfSpeech: 'verb',
      level: 'B1',
      week: 3,
      topic: 'tecnologia-digital',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_upload_088',
      word: 'upload',
      translation: 'subir / cargar archivos',
      partOfSpeech: 'verb',
      level: 'B1',
      week: 3,
      topic: 'tecnologia-digital',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_install_089',
      word: 'install',
      translation: 'instalar',
      partOfSpeech: 'verb',
      level: 'B1',
      week: 3,
      topic: 'tecnologia-digital',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_update_090',
      word: 'update',
      translation: 'actualizar',
      partOfSpeech: 'verb',
      level: 'B1',
      week: 3,
      topic: 'tecnologia-digital',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_browse_091',
      word: 'browse',
      translation: 'navegar (por internet)',
      partOfSpeech: 'verb',
      level: 'B1',
      week: 3,
      topic: 'tecnologia-digital',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_hacker_092',
      word: 'hacker',
      translation: 'hacker / pirata informático',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 3,
      topic: 'tecnologia-digital',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_encryption_093',
      word: 'encryption',
      translation: 'cifrado / encriptación',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 3,
      topic: 'tecnologia-digital',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_platform_094',
      word: 'platform',
      translation: 'plataforma digital',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 3,
      topic: 'tecnologia-digital',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_interface_095',
      word: 'interface',
      translation: 'interfaz de usuario',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 3,
      topic: 'tecnologia-digital',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_user-friendly_096',
      word: 'user-friendly',
      translation: 'fácil de usar / intuitivo',
      partOfSpeech: 'adjective',
      level: 'B1',
      week: 3,
      topic: 'tecnologia-digital',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_server_097',
      word: 'server',
      translation: 'servidor informático',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 3,
      topic: 'tecnologia-digital',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_backup_098',
      word: 'backup',
      translation: 'copia de seguridad / respaldo',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 3,
      topic: 'tecnologia-digital',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_crash_099',
      word: 'crash',
      translation: 'fallar / colapsar un sistema',
      partOfSpeech: 'verb',
      level: 'B1',
      week: 3,
      topic: 'tecnologia-digital',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_stream_100',
      word: 'stream',
      translation: 'transmitir contenido en directo',
      partOfSpeech: 'verb',
      level: 'B1',
      week: 3,
      topic: 'tecnologia-digital',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_innovation_101',
      word: 'innovation',
      translation: 'innovación',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 3,
      topic: 'tecnologia-digital',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_cutting-edge_102',
      word: 'cutting-edge',
      translation: 'de vanguardia / puntero',
      partOfSpeech: 'adjective',
      level: 'B1',
      week: 3,
      topic: 'tecnologia-digital',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_smart_103',
      word: 'smart',
      translation: 'inteligente / tecnológico',
      partOfSpeech: 'adjective',
      level: 'B1',
      week: 3,
      topic: 'tecnologia-digital',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
  ],
}
