import type { ContentBlock } from '../types'

/**
 * B1 Level Content — Week 7
 * Topic: B1 · Semana 7 – Economía y trabajo (nivel intermedio)
 * Curated from institutional curriculum (Zero AI)
 */
export const week07: ContentBlock = {
  "level": "B1",
  "week": 7,
  "topic": "B1 · Semana 7 – Economía y trabajo (nivel intermedio)",
  "vocabulary": [
    {
      "id": "voc_b1_economy_165",
      "word": "economy",
      "translation": "economía",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 7,
      "topic": "economy_work",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_inflation_166",
      "word": "inflation",
      "translation": "inflación",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 7,
      "topic": "economy_work",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_recession_167",
      "word": "recession",
      "translation": "recesión",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 7,
      "topic": "economy_work",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_unemployment_168",
      "word": "unemployment",
      "translation": "desempleo",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 7,
      "topic": "economy_work",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_income_169",
      "word": "income",
      "translation": "ingresos",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 7,
      "topic": "economy_work",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_expense_170",
      "word": "expense",
      "translation": "gasto",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 7,
      "topic": "economy_work",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_investment_171",
      "word": "investment",
      "translation": "inversión",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 7,
      "topic": "economy_work",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_profit_172",
      "word": "profit",
      "translation": "ganancia/beneficio",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 7,
      "topic": "economy_work",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_loss-business_173",
      "word": "loss (business)",
      "translation": "pérdida (negocio)",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 7,
      "topic": "economy_work",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_supply_174",
      "word": "supply",
      "translation": "oferta",
      "partOfSpeech": "adverb",
      "level": "B1",
      "week": 7,
      "topic": "economy_work",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_demand-economy_175",
      "word": "demand (economy)",
      "translation": "demanda (economía)",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 7,
      "topic": "economy_work",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_trade_176",
      "word": "trade",
      "translation": "comercio",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 7,
      "topic": "economy_work",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_export_177",
      "word": "export",
      "translation": "exportar/exportación",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 7,
      "topic": "economy_work",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_import_178",
      "word": "import",
      "translation": "importar/importación",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 7,
      "topic": "economy_work",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_industry_179",
      "word": "industry",
      "translation": "industria",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 7,
      "topic": "economy_work",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_sector_180",
      "word": "sector",
      "translation": "sector",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 7,
      "topic": "economy_work",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_consumer_181",
      "word": "consumer",
      "translation": "consumidor",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 7,
      "topic": "economy_work",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_entrepreneur_182",
      "word": "entrepreneur",
      "translation": "emprendedor",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 7,
      "topic": "economy_work",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_startup_183",
      "word": "startup",
      "translation": "empresa emergente",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 7,
      "topic": "economy_work",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_revenue_184",
      "word": "revenue",
      "translation": "ingresos (empresa)",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 7,
      "topic": "economy_work",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_asset_185",
      "word": "asset",
      "translation": "activo (financiero)",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 7,
      "topic": "economy_work",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_shareholder_186",
      "word": "shareholder",
      "translation": "accionista",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 7,
      "topic": "economy_work",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_stock-finance_187",
      "word": "stock (finance)",
      "translation": "acción (bolsa)",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 7,
      "topic": "economy_work",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    }
  ]
}
