import type { ContentBlock } from '../types'

/**
 * B1 Level Content — Week 3
 * Topic: B1 · Semana 3 – Sustantivos abstractos de uso frecuente
 * Curated from institutional curriculum (Zero AI)
 */
export const week03: ContentBlock = {
  level: "B1",
  week: 3,
  topic: "B1 · Semana 3 – Sustantivos abstractos de uso frecuente",
  vocabulary: [
    {
      "id": "voc_b1_achievement_061",
      word: "achievement",
      translation: "logro",
      partOfSpeech: 'noun',
      level: "B1",
      week: 3,
      topic: "abstract_nouns",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/əˈtʃivmənt/',
      example: 'Finishing the marathon was a great achievement.',
      exampleTranslation: 'Terminar el maratón fue un gran logro.',
      status: 'approved',
    },
    {
      "id": "voc_b1_assumption_062",
      word: "assumption",
      translation: "suposición",
      partOfSpeech: 'noun',
      level: "B1",
      week: 3,
      topic: "abstract_nouns",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/əˈsʌmpʃən/',
      example: 'That\'s just an assumption, not a fact.',
      exampleTranslation: 'Eso es solo una suposición, no un hecho.',
      status: 'approved',
    },
    {
      "id": "voc_b1_attitude_063",
      word: "attitude",
      translation: "actitud",
      partOfSpeech: 'noun',
      level: "B1",
      week: 3,
      topic: "abstract_nouns",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈætɪˌtud/',
      example: 'She has a positive attitude toward work.',
      exampleTranslation: 'Ella tiene una actitud positiva hacia el trabajo.',
      status: 'approved',
    },
    {
      "id": "voc_b1_awareness_064",
      word: "awareness",
      translation: "conciencia (de algo)",
      partOfSpeech: 'noun',
      level: "B1",
      week: 3,
      topic: "abstract_nouns",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/əˈwɛrnəs/',
      example: 'The campaign raised awareness about pollution.',
      exampleTranslation: 'La campaña generó conciencia sobre la contaminación.',
      status: 'approved',
    },
    {
      "id": "voc_b1_behavior_065",
      word: "behavior",
      translation: "comportamiento",
      partOfSpeech: 'noun',
      level: "B1",
      week: 3,
      topic: "abstract_nouns",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/bɪˈheɪvjər/',
      example: 'His behavior surprised everyone.',
      exampleTranslation: 'Su comportamiento sorprendió a todos.',
      status: 'approved',
    },
    {
      "id": "voc_b1_capability_066",
      word: "capability",
      translation: "capacidad",
      partOfSpeech: 'noun',
      level: "B1",
      week: 3,
      topic: "abstract_nouns",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˌkeɪpəˈbɪləti/',
      example: 'She has the capability to lead the team.',
      exampleTranslation: 'Ella tiene la capacidad de liderar el equipo.',
      status: 'approved',
    },
    {
      "id": "voc_b1_circumstance_067",
      word: "circumstance",
      translation: "circunstancia",
      partOfSpeech: 'noun',
      level: "B1",
      week: 3,
      topic: "abstract_nouns",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈsɜrkəmˌstæns/',
      example: 'Under these circumstances, we must wait.',
      exampleTranslation: 'Bajo estas circunstancias, debemos esperar.',
      status: 'approved',
    },
    {
      "id": "voc_b1_consequence_068",
      word: "consequence",
      translation: "consecuencia",
      partOfSpeech: 'noun',
      level: "B1",
      week: 3,
      topic: "abstract_nouns",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈkɑnsəˌkwɛns/',
      example: 'Every action has a consequence.',
      exampleTranslation: 'Toda acción tiene una consecuencia.',
      status: 'approved',
    },
    {
      "id": "voc_b1_consideration_069",
      word: "consideration",
      translation: "consideración",
      partOfSpeech: 'noun',
      level: "B1",
      week: 3,
      topic: "abstract_nouns",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/kənˌsɪdəˈreɪʃən/',
      example: 'Please take this into consideration.',
      exampleTranslation: 'Por favor toma esto en consideración.',
      status: 'approved',
    },
    {
      "id": "voc_b1_contribution_070",
      word: "contribution",
      translation: "contribución",
      partOfSpeech: 'noun',
      level: "B1",
      week: 3,
      topic: "abstract_nouns",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˌkɑntrɪˈbjuʃən/',
      example: 'His contribution to the project was huge.',
      exampleTranslation: 'Su contribución al proyecto fue enorme.',
      status: 'approved',
    },
    {
      "id": "voc_b1_credibility_071",
      word: "credibility",
      translation: "credibilidad",
      partOfSpeech: 'noun',
      level: "B1",
      week: 3,
      topic: "abstract_nouns",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˌkrɛdəˈbɪləti/',
      example: 'The scandal damaged her credibility.',
      exampleTranslation: 'El escándalo dañó su credibilidad.',
      status: 'approved',
    },
    {
      "id": "voc_b1_definition_072",
      word: "definition",
      translation: "definición",
      partOfSpeech: 'noun',
      level: "B1",
      week: 3,
      topic: "abstract_nouns",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˌdɛfəˈnɪʃən/',
      example: 'Look up the definition of this word.',
      exampleTranslation: 'Busca la definición de esta palabra.',
      status: 'approved',
    },
    {
      "id": "voc_b1_dimension_073",
      word: "dimension",
      translation: "dimensión",
      partOfSpeech: 'noun',
      level: "B1",
      week: 3,
      topic: "abstract_nouns",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/dɪˈmɛnʃən/',
      example: 'This adds a new dimension to the debate.',
      exampleTranslation: 'Esto añade una nueva dimensión al debate.',
      status: 'approved',
    },
    {
      "id": "voc_b1_emphasis_074",
      word: "emphasis",
      translation: "énfasis",
      partOfSpeech: 'noun',
      level: "B1",
      week: 3,
      topic: "abstract_nouns",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈɛmfəsɪs/',
      example: 'She put emphasis on teamwork.',
      exampleTranslation: 'Ella puso énfasis en el trabajo en equipo.',
      status: 'approved',
    },
    {
      "id": "voc_b1_evaluation_075",
      word: "evaluation",
      translation: "evaluación",
      partOfSpeech: 'noun',
      level: "B1",
      week: 3,
      topic: "abstract_nouns",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ɪˌvæljuˈeɪʃən/',
      example: 'The teacher\'s evaluation was very fair.',
      exampleTranslation: 'La evaluación del maestro fue muy justa.',
      status: 'approved',
    },
    {
      "id": "voc_b1_factor_076",
      word: "factor",
      translation: "factor",
      partOfSpeech: 'noun',
      level: "B1",
      week: 3,
      topic: "abstract_nouns",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈfæktər/',
      example: 'Price is an important factor for us.',
      exampleTranslation: 'El precio es un factor importante para nosotros.',
      status: 'approved',
    },
    {
      "id": "voc_b1_framework_077",
      word: "framework",
      translation: "marco (de referencia)",
      partOfSpeech: 'noun',
      level: "B1",
      week: 3,
      topic: "abstract_nouns",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈfreɪmˌwɜrk/',
      example: 'We built a new framework for the project.',
      exampleTranslation: 'Construimos un nuevo marco para el proyecto.',
      status: 'approved',
    },
    {
      "id": "voc_b1_function_078",
      word: "function",
      translation: "función",
      partOfSpeech: 'noun',
      level: "B1",
      week: 3,
      topic: "abstract_nouns",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈfʌŋkʃən/',
      example: 'What is the function of this device?',
      exampleTranslation: '¿Cuál es la función de este dispositivo?',
      status: 'approved',
    },
    {
      "id": "voc_b1_impact_079",
      word: "impact",
      translation: "impacto",
      partOfSpeech: 'noun',
      level: "B1",
      week: 3,
      topic: "abstract_nouns",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈɪmˌpækt/',
      example: 'The decision had a big impact on sales.',
      exampleTranslation: 'La decisión tuvo un gran impacto en las ventas.',
      status: 'approved',
    },
    {
      "id": "voc_b1_initiative_080",
      word: "initiative",
      translation: "iniciativa",
      partOfSpeech: 'noun',
      level: "B1",
      week: 3,
      topic: "abstract_nouns",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ɪˈnɪʃətɪv/',
      example: 'She showed great initiative at work.',
      exampleTranslation: 'Ella mostró gran iniciativa en el trabajo.',
      status: 'approved',
    },
    {
      "id": "voc_b1_insight_081",
      word: "insight",
      translation: "percepción profunda",
      partOfSpeech: 'noun',
      level: "B1",
      week: 3,
      topic: "abstract_nouns",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈɪnˌsaɪt/',
      example: 'His insight helped us solve the problem.',
      exampleTranslation: 'Su percepción profunda nos ayudó a resolver el problema.',
      status: 'approved',
    },
    {
      "id": "voc_b1_integrity_082",
      word: "integrity",
      translation: "integridad",
      partOfSpeech: 'noun',
      level: "B1",
      week: 3,
      topic: "abstract_nouns",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ɪnˈtɛgrəti/',
      example: 'He is known for his integrity.',
      exampleTranslation: 'Él es conocido por su integridad.',
      status: 'approved',
    },
    {
      "id": "voc_b1_motivation_083",
      word: "motivation",
      translation: "motivación",
      partOfSpeech: 'noun',
      level: "B1",
      week: 3,
      topic: "abstract_nouns",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˌmoʊtɪˈveɪʃən/',
      example: 'Her motivation to succeed is inspiring.',
      exampleTranslation: 'Su motivación para triunfar es inspiradora.',
      status: 'approved',
    },
    {
      "id": "voc_b1_objective-noun_084",
      word: "objective (noun)",
      translation: "objetivo",
      partOfSpeech: 'noun',
      level: "B1",
      week: 3,
      topic: "abstract_nouns",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/əbˈdʒɛktɪv/',
      example: 'Our main objective is to grow the business.',
      exampleTranslation: 'Nuestro objetivo principal es hacer crecer el negocio.',
      status: 'approved',
    },
    {
      "id": "voc_b1_outcome_085",
      word: "outcome",
      translation: "resultado",
      partOfSpeech: 'noun',
      level: "B1",
      week: 3,
      topic: "abstract_nouns",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈaʊtˌkʌm/',
      example: 'We were happy with the outcome.',
      exampleTranslation: 'Quedamos contentos con el resultado.',
      status: 'approved',
    },
    {
      "id": "voc_b1_perception_086",
      word: "perception",
      translation: "percepción",
      partOfSpeech: 'noun',
      level: "B1",
      week: 3,
      topic: "abstract_nouns",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/pərˈsɛpʃən/',
      example: 'Public perception of the brand improved.',
      exampleTranslation: 'La percepción pública de la marca mejoró.',
      status: 'approved',
    },
    {
      "id": "voc_b1_phenomenon_087",
      word: "phenomenon",
      translation: "fenómeno",
      partOfSpeech: 'noun',
      level: "B1",
      week: 3,
      topic: "abstract_nouns",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/fɪˈnɑməˌnɑn/',
      example: 'This is a common social phenomenon.',
      exampleTranslation: 'Este es un fenómeno social común.',
      status: 'approved',
    },
    {
      "id": "voc_b1_principle_088",
      word: "principle",
      translation: "principio",
      partOfSpeech: 'noun',
      level: "B1",
      week: 3,
      topic: "abstract_nouns",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈprɪnsəpəl/',
      example: 'Honesty is one of her principles.',
      exampleTranslation: 'La honestidad es uno de sus principios.',
      status: 'approved',
    },
    {
      "id": "voc_b1_priority_089",
      word: "priority",
      translation: "prioridad",
      partOfSpeech: 'noun',
      level: "B1",
      week: 3,
      topic: "abstract_nouns",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/praɪˈɔrəti/',
      example: 'Health should always be a priority.',
      exampleTranslation: 'La salud siempre debería ser una prioridad.',
      status: 'approved',
    },
    {
      "id": "voc_b1_procedure_090",
      word: "procedure",
      translation: "procedimiento",
      partOfSpeech: 'noun',
      level: "B1",
      week: 3,
      topic: "abstract_nouns",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/prəˈsidʒər/',
      example: 'Follow the correct procedure.',
      exampleTranslation: 'Sigue el procedimiento correcto.',
      status: 'approved',
    },
    {
      "id": "voc_b1_process_091",
      word: "process",
      translation: "proceso",
      partOfSpeech: 'noun',
      level: "B1",
      week: 3,
      topic: "abstract_nouns",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈprɑˌsɛs/',
      example: 'The hiring process takes two weeks.',
      exampleTranslation: 'El proceso de contratación toma dos semanas.',
      status: 'approved',
    },
    {
      "id": "voc_b1_reputation_092",
      word: "reputation",
      translation: "reputación",
      partOfSpeech: 'noun',
      level: "B1",
      week: 3,
      topic: "abstract_nouns",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˌrɛpjəˈteɪʃən/',
      example: 'The company has a good reputation.',
      exampleTranslation: 'La empresa tiene una buena reputación.',
      status: 'approved',
    },
    {
      "id": "voc_b1_scenario_093",
      word: "scenario",
      translation: "escenario",
      partOfSpeech: 'noun',
      level: "B1",
      week: 3,
      topic: "abstract_nouns",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/sɪˈnɛrioʊ/',
      example: 'Let\'s consider a different scenario.',
      exampleTranslation: 'Consideremos un escenario diferente.',
      status: 'approved',
    },
    {
      "id": "voc_b1_significance_094",
      word: "significance",
      translation: "importancia/relevancia",
      partOfSpeech: 'noun',
      level: "B1",
      week: 3,
      topic: "abstract_nouns",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/sɪgˈnɪfɪkəns/',
      example: 'This event has great historical significance.',
      exampleTranslation: 'Este evento tiene gran importancia histórica.',
      status: 'approved',
    },
    {
      "id": "voc_b1_stability_095",
      word: "stability",
      translation: "estabilidad",
      partOfSpeech: 'noun',
      level: "B1",
      week: 3,
      topic: "abstract_nouns",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/stəˈbɪləti/',
      example: 'The country needs political stability.',
      exampleTranslation: 'El país necesita estabilidad política.',
      status: 'approved',
    },
    {
      "id": "voc_b1_structure_096",
      word: "structure",
      translation: "estructura",
      partOfSpeech: 'noun',
      level: "B1",
      week: 3,
      topic: "abstract_nouns",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈstrʌktʃər/',
      example: 'The report has a clear structure.',
      exampleTranslation: 'El informe tiene una estructura clara.',
      status: 'approved',
    },
    {
      "id": "voc_b1_tendency_097",
      word: "tendency",
      translation: "tendencia",
      partOfSpeech: 'noun',
      level: "B1",
      week: 3,
      topic: "abstract_nouns",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈtɛndənsi/',
      example: 'He has a tendency to arrive late.',
      exampleTranslation: 'Él tiene una tendencia a llegar tarde.',
      status: 'approved',
    },
    {
      "id": "voc_b1_theory_098",
      word: "theory",
      translation: "teoría",
      partOfSpeech: 'noun',
      level: "B1",
      week: 3,
      topic: "abstract_nouns",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈθɪəri/',
      example: 'This is just a theory, not proven yet.',
      exampleTranslation: 'Esto es solo una teoría, aún no comprobada.',
      status: 'approved',
    },
    {
      "id": "voc_b1_transition_099",
      word: "transition",
      translation: "transición",
      partOfSpeech: 'noun',
      level: "B1",
      week: 3,
      topic: "abstract_nouns",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/trænˈzɪʃən/',
      example: 'The transition to remote work was smooth.',
      exampleTranslation: 'La transición al trabajo remoto fue fluida.',
      status: 'approved',
    }
  ]
}
