import type { ContentBlock } from '../types'

/**
 * B1 Level Content — Week 4
 * Topic: Salud pública, bienestar y medicina
 * Curated from institutional curriculum (Zero AI)
 */
export const week04: ContentBlock = {
  level: 'B1',
  week: 4,
  topic: 'Salud pública, bienestar y medicina',
  vocabulary: [
    {
      id: 'voc_b1_healthcare_104',
      word: 'healthcare',
      translation: 'atención médica / sanidad',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 4,
      topic: 'salud-publica-y-bienestar',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_public-health_105',
      word: 'public health',
      translation: 'salud pública',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 4,
      topic: 'salud-publica-y-bienestar',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_mental-health_106',
      word: 'mental health',
      translation: 'salud mental',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 4,
      topic: 'salud-publica-y-bienestar',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_well-being_107',
      word: 'well-being',
      translation: 'bienestar general',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 4,
      topic: 'salud-publica-y-bienestar',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_disease_108',
      word: 'disease',
      translation: 'enfermedad',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 4,
      topic: 'salud-publica-y-bienestar',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_infection_109',
      word: 'infection',
      translation: 'infección',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 4,
      topic: 'salud-publica-y-bienestar',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_epidemic_110',
      word: 'epidemic',
      translation: 'epidemia',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 4,
      topic: 'salud-publica-y-bienestar',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_pandemic_111',
      word: 'pandemic',
      translation: 'pandemia',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 4,
      topic: 'salud-publica-y-bienestar',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_vaccine_112',
      word: 'vaccine',
      translation: 'vacuna',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 4,
      topic: 'salud-publica-y-bienestar',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_vaccinate_113',
      word: 'vaccinate',
      translation: 'vacunar',
      partOfSpeech: 'verb',
      level: 'B1',
      week: 4,
      topic: 'salud-publica-y-bienestar',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_immunity_114',
      word: 'immunity',
      translation: 'inmunidad',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 4,
      topic: 'salud-publica-y-bienestar',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_immune-system_115',
      word: 'immune system',
      translation: 'sistema inmunológico',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 4,
      topic: 'salud-publica-y-bienestar',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_hygiene_116',
      word: 'hygiene',
      translation: 'higiene',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 4,
      topic: 'salud-publica-y-bienestar',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_nutrition_117',
      word: 'nutrition',
      translation: 'nutrición',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 4,
      topic: 'salud-publica-y-bienestar',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_obesity_118',
      word: 'obesity',
      translation: 'obesidad',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 4,
      topic: 'salud-publica-y-bienestar',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_diabetes_119',
      word: 'diabetes',
      translation: 'diabetes',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 4,
      topic: 'salud-publica-y-bienestar',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_allergy_120',
      word: 'allergy',
      translation: 'alergia',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 4,
      topic: 'salud-publica-y-bienestar',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_prescription_121',
      word: 'prescription',
      translation: 'receta médica',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 4,
      topic: 'salud-publica-y-bienestar',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_prescribe_122',
      word: 'prescribe',
      translation: 'recetar medicamentos',
      partOfSpeech: 'verb',
      level: 'B1',
      week: 4,
      topic: 'salud-publica-y-bienestar',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_therapy_123',
      word: 'therapy',
      translation: 'terapia',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 4,
      topic: 'salud-publica-y-bienestar',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_rehabilitation_124',
      word: 'rehabilitation',
      translation: 'rehabilitación',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 4,
      topic: 'salud-publica-y-bienestar',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_recover_125',
      word: 'recover',
      translation: 'recuperarse de una enfermedad',
      partOfSpeech: 'verb',
      level: 'B1',
      week: 4,
      topic: 'salud-publica-y-bienestar',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_treat_126',
      word: 'treat',
      translation: 'tratar médicamente',
      partOfSpeech: 'verb',
      level: 'B1',
      week: 4,
      topic: 'salud-publica-y-bienestar',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_treatment_127',
      word: 'treatment',
      translation: 'tratamiento médico',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 4,
      topic: 'salud-publica-y-bienestar',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_cure_128',
      word: 'cure',
      translation: 'curar / remedio definitivo',
      partOfSpeech: 'verb',
      level: 'B1',
      week: 4,
      topic: 'salud-publica-y-bienestar',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_prevention_129',
      word: 'prevention',
      translation: 'prevención',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 4,
      topic: 'salud-publica-y-bienestar',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_lifestyle_130',
      word: 'lifestyle',
      translation: 'estilo de vida',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 4,
      topic: 'salud-publica-y-bienestar',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_stress_131',
      word: 'stress',
      translation: 'estrés / tensión nerviosa',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 4,
      topic: 'salud-publica-y-bienestar',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_anxiety_132',
      word: 'anxiety',
      translation: 'ansiedad',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 4,
      topic: 'salud-publica-y-bienestar',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_depression_133',
      word: 'depression',
      translation: 'depresión clínica',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 4,
      topic: 'salud-publica-y-bienestar',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_chronic_134',
      word: 'chronic',
      translation: 'crónico / de larga duración',
      partOfSpeech: 'adjective',
      level: 'B1',
      week: 4,
      topic: 'salud-publica-y-bienestar',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
  ],
}
