import type { ContentBlock } from '../types'

/**
 * B1 Level Content — Week 2
 * Topic: B1 · Semana 2 – Modismos y expresiones idiomáticas
 * Curated from institutional curriculum (Zero AI)
 */
export const week02: ContentBlock = {
  "level": "B1",
  "week": 2,
  "topic": "B1 · Semana 2 – Modismos y expresiones idiomáticas",
  "vocabulary": [
    {
      "id": "voc_b1_once-in-a-blue-moon_037",
      "word": "once in a blue moon",
      "translation": "muy de vez en cuando",
      "partOfSpeech": "adverb",
      "level": "B1",
      "week": 2,
      "topic": "idioms",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_break-the-ice_038",
      "word": "break the ice",
      "translation": "romper el hielo",
      "partOfSpeech": "verb",
      "level": "B1",
      "week": 2,
      "topic": "idioms",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_hit-the-books_039",
      "word": "hit the books",
      "translation": "ponerse a estudiar",
      "partOfSpeech": "verb",
      "level": "B1",
      "week": 2,
      "topic": "idioms",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_under-the-weather_040",
      "word": "under the weather",
      "translation": "sentirse mal/indispuesto",
      "partOfSpeech": "adverb",
      "level": "B1",
      "week": 2,
      "topic": "idioms",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_piece-of-cake_041",
      "word": "piece of cake",
      "translation": "pan comido",
      "partOfSpeech": "adverb",
      "level": "B1",
      "week": 2,
      "topic": "idioms",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_cost-an-arm-and-a-leg_042",
      "word": "cost an arm and a leg",
      "translation": "costar un ojo de la cara",
      "partOfSpeech": "verb",
      "level": "B1",
      "week": 2,
      "topic": "idioms",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_on-the-ball_043",
      "word": "on the ball",
      "translation": "atento/competente",
      "partOfSpeech": "adverb",
      "level": "B1",
      "week": 2,
      "topic": "idioms",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_let-the-cat-out-of-the-bag_044",
      "word": "let the cat out of the bag",
      "translation": "revelar un secreto",
      "partOfSpeech": "verb",
      "level": "B1",
      "week": 2,
      "topic": "idioms",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_cutting-corners_045",
      "word": "cutting corners",
      "translation": "hacer las cosas mal por ahorrar",
      "partOfSpeech": "adverb",
      "level": "B1",
      "week": 2,
      "topic": "idioms",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_back-to-square-one_046",
      "word": "back to square one",
      "translation": "volver al punto de partida",
      "partOfSpeech": "adverb",
      "level": "B1",
      "week": 2,
      "topic": "idioms",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_bite-the-bullet_047",
      "word": "bite the bullet",
      "translation": "aguantar algo difícil",
      "partOfSpeech": "verb",
      "level": "B1",
      "week": 2,
      "topic": "idioms",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_call-it-a-day_048",
      "word": "call it a day",
      "translation": "dar por terminado el día/trabajo",
      "partOfSpeech": "verb",
      "level": "B1",
      "week": 2,
      "topic": "idioms",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_get-the-ball-rolling_049",
      "word": "get the ball rolling",
      "translation": "poner algo en marcha",
      "partOfSpeech": "verb",
      "level": "B1",
      "week": 2,
      "topic": "idioms",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_hang-in-there_050",
      "word": "hang in there",
      "translation": "aguantar/no rendirse",
      "partOfSpeech": "adverb",
      "level": "B1",
      "week": 2,
      "topic": "idioms",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_in-the-loop_051",
      "word": "in the loop",
      "translation": "al tanto/informado",
      "partOfSpeech": "adverb",
      "level": "B1",
      "week": 2,
      "topic": "idioms",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_keep-an-eye-on_052",
      "word": "keep an eye on",
      "translation": "vigilar",
      "partOfSpeech": "adverb",
      "level": "B1",
      "week": 2,
      "topic": "idioms",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_the-last-straw_053",
      "word": "the last straw",
      "translation": "la gota que colma el vaso",
      "partOfSpeech": "adverb",
      "level": "B1",
      "week": 2,
      "topic": "idioms",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_miss-the-boat_054",
      "word": "miss the boat",
      "translation": "perder la oportunidad",
      "partOfSpeech": "verb",
      "level": "B1",
      "week": 2,
      "topic": "idioms",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_on-the-same-page_055",
      "word": "on the same page",
      "translation": "de acuerdo/en sintonía",
      "partOfSpeech": "adverb",
      "level": "B1",
      "week": 2,
      "topic": "idioms",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_speak-of-the-devil_056",
      "word": "speak of the devil",
      "translation": "hablando del rey de Roma",
      "partOfSpeech": "adverb",
      "level": "B1",
      "week": 2,
      "topic": "idioms",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_the-ball-is-in-your-court_057",
      "word": "the ball is in your court",
      "translation": "la decisión es tuya ahora",
      "partOfSpeech": "adverb",
      "level": "B1",
      "week": 2,
      "topic": "idioms",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_time-flies_058",
      "word": "time flies",
      "translation": "el tiempo vuela",
      "partOfSpeech": "adverb",
      "level": "B1",
      "week": 2,
      "topic": "idioms",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_up-in-the-air_059",
      "word": "up in the air",
      "translation": "incierto/sin decidir",
      "partOfSpeech": "adverb",
      "level": "B1",
      "week": 2,
      "topic": "idioms",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_weather-the-storm_060",
      "word": "weather the storm",
      "translation": "superar una dificultad",
      "partOfSpeech": "adverb",
      "level": "B1",
      "week": 2,
      "topic": "idioms",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    }
  ]
}
