import type { ContentBlock } from '../types'

/**
 * B1 Level Content — Week 8
 * Topic: B1 · Semana 8 – Relaciones sociales y comunicación
 * Curated from institutional curriculum (Zero AI)
 */
export const week08: ContentBlock = {
  level: "B1",
  week: 8,
  topic: "B1 · Semana 8 – Relaciones sociales y comunicación",
  vocabulary: [
    {
      "id": "voc_b1_cooperate_188",
      word: "cooperate",
      translation: "cooperar",
      partOfSpeech: 'verb',
      level: "B1",
      week: 8,
      topic: "social_communication",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/koʊˈɑpəˌreɪt/',
      example: 'Both teams cooperated to finish on time.',
      exampleTranslation: 'Ambos equipos cooperaron para terminar a tiempo.',
      status: 'approved',
    },
    {
      "id": "voc_b1_collaborate_189",
      word: "collaborate",
      translation: "colaborar",
      partOfSpeech: 'verb',
      level: "B1",
      week: 8,
      topic: "social_communication",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/kəˈlæbəˌreɪt/',
      example: 'We collaborated on this project together.',
      exampleTranslation: 'Colaboramos juntos en este proyecto.',
      status: 'approved',
    },
    {
      "id": "voc_b1_criticize_190",
      word: "criticize",
      translation: "criticar",
      partOfSpeech: 'verb',
      level: "B1",
      week: 8,
      topic: "social_communication",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈkrɪtɪˌsaɪz/',
      example: 'Please don\'t criticize him in public.',
      exampleTranslation: 'Por favor no lo critiques en público.',
      status: 'approved',
    },
    {
      "id": "voc_b1_compliment_191",
      word: "compliment",
      translation: "hacer un cumplido",
      partOfSpeech: 'noun',
      level: "B1",
      week: 8,
      topic: "social_communication",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈkɑmpləmənt/',
      example: 'She gave me a nice compliment.',
      exampleTranslation: 'Ella me hizo un lindo cumplido.',
      status: 'approved',
    },
    {
      "id": "voc_b1_complain_192",
      word: "complain",
      translation: "quejarse",
      partOfSpeech: 'verb',
      level: "B1",
      week: 8,
      topic: "social_communication",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/kəmˈpleɪn/',
      example: 'He always complains about the weather.',
      exampleTranslation: 'Él siempre se queja del clima.',
      status: 'approved',
    },
    {
      "id": "voc_b1_reconcile_193",
      word: "reconcile",
      translation: "reconciliar",
      partOfSpeech: 'verb',
      level: "B1",
      week: 8,
      topic: "social_communication",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈrɛkənˌsaɪl/',
      example: 'They finally reconciled after years apart.',
      exampleTranslation: 'Finalmente se reconciliaron después de años separados.',
      status: 'approved',
    },
    {
      "id": "voc_b1_gossip_194",
      word: "gossip",
      translation: "chisme/chismear",
      partOfSpeech: 'noun',
      level: "B1",
      week: 8,
      topic: "social_communication",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈgɑsəp/',
      example: 'I don\'t like to spread gossip.',
      exampleTranslation: 'No me gusta difundir chismes.',
      status: 'approved',
    },
    {
      "id": "voc_b1_rumor_195",
      word: "rumor",
      translation: "rumor",
      partOfSpeech: 'noun',
      level: "B1",
      week: 8,
      topic: "social_communication",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈrumər/',
      example: 'There\'s a rumor about the merger.',
      exampleTranslation: 'Hay un rumor sobre la fusión.',
      status: 'approved',
    },
    {
      "id": "voc_b1_confront_196",
      word: "confront",
      translation: "confrontar",
      partOfSpeech: 'verb',
      level: "B1",
      week: 8,
      topic: "social_communication",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/kənˈfrʌnt/',
      example: 'She decided to confront him about it.',
      exampleTranslation: 'Ella decidió confrontarlo sobre eso.',
      status: 'approved',
    },
    {
      "id": "voc_b1_mediate_197",
      word: "mediate",
      translation: "mediar",
      partOfSpeech: 'verb',
      level: "B1",
      week: 8,
      topic: "social_communication",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈmidiˌeɪt/',
      example: 'A friend helped mediate the dispute.',
      exampleTranslation: 'Un amigo ayudó a mediar el conflicto.',
      status: 'approved',
    },
    {
      "id": "voc_b1_empathize_198",
      word: "empathize",
      translation: "empatizar",
      partOfSpeech: 'verb',
      level: "B1",
      week: 8,
      topic: "social_communication",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈɛmpəˌθaɪz/',
      example: 'I really empathize with your situation.',
      exampleTranslation: 'Realmente empatizo con tu situación.',
      status: 'approved',
    },
    {
      "id": "voc_b1_tolerate_199",
      word: "tolerate",
      translation: "tolerar",
      partOfSpeech: 'verb',
      level: "B1",
      week: 8,
      topic: "social_communication",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈtɑləˌreɪt/',
      example: 'I won\'t tolerate that behavior.',
      exampleTranslation: 'No voy a tolerar ese comportamiento.',
      status: 'approved',
    },
    {
      "id": "voc_b1_admire_200",
      word: "admire",
      translation: "admirar",
      partOfSpeech: 'verb',
      level: "B1",
      week: 8,
      topic: "social_communication",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ædˈmaɪər/',
      example: 'I admire her dedication.',
      exampleTranslation: 'Admiro su dedicación.',
      status: 'approved',
    },
    {
      "id": "voc_b1_envy_201",
      word: "envy",
      translation: "envidiar/envidia",
      partOfSpeech: 'noun',
      level: "B1",
      week: 8,
      topic: "social_communication",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈɛnvi/',
      example: 'He couldn\'t hide his envy.',
      exampleTranslation: 'Él no pudo ocultar su envidia.',
      status: 'approved',
    },
    {
      "id": "voc_b1_resent_202",
      word: "resent",
      translation: "resentirse por",
      partOfSpeech: 'verb',
      level: "B1",
      week: 8,
      topic: "social_communication",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/rɪˈzɛnt/',
      example: 'She resents being ignored.',
      exampleTranslation: 'Ella se resiente por ser ignorada.',
      status: 'approved',
    }
  ]
}
