import type { ContentBlock } from '../types'

/**
 * B1 Level Content — Week 6
 * Topic: B1 · Semana 6 – Medios de comunicación y actualidad
 * Curated from institutional curriculum (Zero AI)
 */
export const week06: ContentBlock = {
  "level": "B1",
  "week": 6,
  "topic": "B1 · Semana 6 – Medios de comunicación y actualidad",
  "vocabulary": [
    {
      "id": "voc_b1_article_146",
      "word": "article",
      "translation": "artículo",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 6,
      "topic": "media_current_affairs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_column-newspaper_147",
      "word": "column (newspaper)",
      "translation": "columna (periódico)",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 6,
      "topic": "media_current_affairs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_broadcast_148",
      "word": "broadcast",
      "translation": "transmisión/emitir",
      "partOfSpeech": "verb",
      "level": "B1",
      "week": 6,
      "topic": "media_current_affairs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_coverage-news_149",
      "word": "coverage (news)",
      "translation": "cobertura (noticiosa)",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 6,
      "topic": "media_current_affairs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_correspondent_150",
      "word": "correspondent",
      "translation": "corresponsal",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 6,
      "topic": "media_current_affairs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_editor_151",
      "word": "editor",
      "translation": "editor",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 6,
      "topic": "media_current_affairs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_feature-article_152",
      "word": "feature (article)",
      "translation": "reportaje/artículo especial",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 6,
      "topic": "media_current_affairs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_interview-noun_153",
      "word": "interview (noun)",
      "translation": "entrevista",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 6,
      "topic": "media_current_affairs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_investigate_154",
      "word": "investigate",
      "translation": "investigar",
      "partOfSpeech": "verb",
      "level": "B1",
      "week": 6,
      "topic": "media_current_affairs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_source-news_155",
      "word": "source (news)",
      "translation": "fuente (informativa)",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 6,
      "topic": "media_current_affairs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_statement-public_156",
      "word": "statement (public)",
      "translation": "declaración (pública)",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 6,
      "topic": "media_current_affairs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_survey_157",
      "word": "survey",
      "translation": "encuesta",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 6,
      "topic": "media_current_affairs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_poll_158",
      "word": "poll",
      "translation": "sondeo/encuesta",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 6,
      "topic": "media_current_affairs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_censorship_159",
      "word": "censorship",
      "translation": "censura",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 6,
      "topic": "media_current_affairs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_propaganda_160",
      "word": "propaganda",
      "translation": "propaganda",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 6,
      "topic": "media_current_affairs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_bias_161",
      "word": "bias",
      "translation": "sesgo/parcialidad",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 6,
      "topic": "media_current_affairs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_credible_162",
      "word": "credible",
      "translation": "creíble",
      "partOfSpeech": "adjective",
      "level": "B1",
      "week": 6,
      "topic": "media_current_affairs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_misinformation_163",
      "word": "misinformation",
      "translation": "desinformación",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 6,
      "topic": "media_current_affairs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_current-affairs_164",
      "word": "current affairs",
      "translation": "actualidad",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 6,
      "topic": "media_current_affairs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    }
  ]
}
