import type { ContentBlock } from '../types'

/**
 * B1 Level Content — Week 4
 * Topic: B1 · Semana 4 – Conectores avanzados del discurso
 * Curated from institutional curriculum (Zero AI)
 */
export const week04: ContentBlock = {
  "level": "B1",
  "week": 4,
  "topic": "B1 · Semana 4 – Conectores avanzados del discurso",
  "vocabulary": [
    {
      "id": "voc_b1_whereas_100",
      "word": "whereas",
      "translation": "mientras que (contraste)",
      "partOfSpeech": "conjunction",
      "level": "B1",
      "week": 4,
      "topic": "discourse_markers",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_provided-that_101",
      "word": "provided that",
      "translation": "siempre que/con la condición de que",
      "partOfSpeech": "conjunction",
      "level": "B1",
      "week": 4,
      "topic": "discourse_markers",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_unless_102",
      "word": "unless",
      "translation": "a menos que",
      "partOfSpeech": "conjunction",
      "level": "B1",
      "week": 4,
      "topic": "discourse_markers",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_even-though_103",
      "word": "even though",
      "translation": "aunque",
      "partOfSpeech": "conjunction",
      "level": "B1",
      "week": 4,
      "topic": "discourse_markers",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_as-long-as_104",
      "word": "as long as",
      "translation": "mientras (condición)",
      "partOfSpeech": "conjunction",
      "level": "B1",
      "week": 4,
      "topic": "discourse_markers",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_in-spite-of_105",
      "word": "in spite of",
      "translation": "a pesar de",
      "partOfSpeech": "conjunction",
      "level": "B1",
      "week": 4,
      "topic": "discourse_markers",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_despite_106",
      "word": "despite",
      "translation": "a pesar de",
      "partOfSpeech": "conjunction",
      "level": "B1",
      "week": 4,
      "topic": "discourse_markers",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_given-that_107",
      "word": "given that",
      "translation": "dado que",
      "partOfSpeech": "conjunction",
      "level": "B1",
      "week": 4,
      "topic": "discourse_markers",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_assuming-that_108",
      "word": "assuming that",
      "translation": "suponiendo que",
      "partOfSpeech": "conjunction",
      "level": "B1",
      "week": 4,
      "topic": "discourse_markers",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_in-order-to_109",
      "word": "in order to",
      "translation": "con el fin de",
      "partOfSpeech": "conjunction",
      "level": "B1",
      "week": 4,
      "topic": "discourse_markers",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_so-as-to_110",
      "word": "so as to",
      "translation": "para/con el objetivo de",
      "partOfSpeech": "conjunction",
      "level": "B1",
      "week": 4,
      "topic": "discourse_markers",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_rather-than_111",
      "word": "rather than",
      "translation": "en lugar de",
      "partOfSpeech": "conjunction",
      "level": "B1",
      "week": 4,
      "topic": "discourse_markers",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_as-opposed-to_112",
      "word": "as opposed to",
      "translation": "en contraposición a",
      "partOfSpeech": "conjunction",
      "level": "B1",
      "week": 4,
      "topic": "discourse_markers",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_on-the-whole_113",
      "word": "on the whole",
      "translation": "en general/en conjunto",
      "partOfSpeech": "conjunction",
      "level": "B1",
      "week": 4,
      "topic": "discourse_markers",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_by-and-large_114",
      "word": "by and large",
      "translation": "en su mayor parte",
      "partOfSpeech": "conjunction",
      "level": "B1",
      "week": 4,
      "topic": "discourse_markers",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_needless-to-say_115",
      "word": "needless to say",
      "translation": "huelga decir/ni que decir",
      "partOfSpeech": "conjunction",
      "level": "B1",
      "week": 4,
      "topic": "discourse_markers",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_last-but-not-least_116",
      "word": "last but not least",
      "translation": "por último pero no menos importante",
      "partOfSpeech": "conjunction",
      "level": "B1",
      "week": 4,
      "topic": "discourse_markers",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_all-things-considered_117",
      "word": "all things considered",
      "translation": "considerándolo todo",
      "partOfSpeech": "conjunction",
      "level": "B1",
      "week": 4,
      "topic": "discourse_markers",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_in-other-words_118",
      "word": "in other words",
      "translation": "en otras palabras",
      "partOfSpeech": "conjunction",
      "level": "B1",
      "week": 4,
      "topic": "discourse_markers",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_that-being-said_119",
      "word": "that being said",
      "translation": "dicho esto",
      "partOfSpeech": "conjunction",
      "level": "B1",
      "week": 4,
      "topic": "discourse_markers",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    }
  ]
}
