import type { ContentBlock } from '../types'

/**
 * B1 Level Content — Week 9
 * Topic: B1 · Semana 9 – Adjetivos descriptivos avanzados
 * Curated from institutional curriculum (Zero AI)
 */
export const week09: ContentBlock = {
  level: "B1",
  week: 9,
  topic: "B1 · Semana 9 – Adjetivos descriptivos avanzados",
  vocabulary: [
    {
      "id": "voc_b1_ambiguous_203",
      word: "ambiguous",
      translation: "ambiguo",
      partOfSpeech: 'adjective',
      level: "B1",
      week: 9,
      topic: "advanced_adjectives",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/æmˈbɪgjuəs/',
      example: 'His answer was quite ambiguous.',
      exampleTranslation: 'Su respuesta fue bastante ambigua.',
      status: 'approved',
    },
    {
      "id": "voc_b1_controversial_204",
      word: "controversial",
      translation: "controvertido",
      partOfSpeech: 'adjective',
      level: "B1",
      week: 9,
      topic: "advanced_adjectives",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˌkɑntrəˈvɜrʃəl/',
      example: 'It was a controversial decision.',
      exampleTranslation: 'Fue una decisión controvertida.',
      status: 'approved',
    },
    {
      "id": "voc_b1_significant_205",
      word: "significant",
      translation: "significativo",
      partOfSpeech: 'adjective',
      level: "B1",
      week: 9,
      topic: "advanced_adjectives",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/sɪgˈnɪfɪkant/',
      example: 'There was a significant change in sales.',
      exampleTranslation: 'Hubo un cambio significativo en las ventas.',
      status: 'approved',
    },
    {
      "id": "voc_b1_substantial_206",
      word: "substantial",
      translation: "sustancial",
      partOfSpeech: 'adjective',
      level: "B1",
      week: 9,
      topic: "advanced_adjectives",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/səbˈstænʃəl/',
      example: 'We made substantial progress this month.',
      exampleTranslation: 'Hicimos un progreso sustancial este mes.',
      status: 'approved',
    },
    {
      "id": "voc_b1_considerable_207",
      word: "considerable",
      translation: "considerable",
      partOfSpeech: 'adjective',
      level: "B1",
      week: 9,
      topic: "advanced_adjectives",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/kənˈsɪdərəbəl/',
      example: 'It took considerable effort to finish.',
      exampleTranslation: 'Tomó un esfuerzo considerable terminarlo.',
      status: 'approved',
    },
    {
      "id": "voc_b1_remarkable_208",
      word: "remarkable",
      translation: "notable",
      partOfSpeech: 'adjective',
      level: "B1",
      week: 9,
      topic: "advanced_adjectives",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/rɪˈmɑrkəbəl/',
      example: 'She made remarkable progress in English.',
      exampleTranslation: 'Ella hizo un progreso notable en inglés.',
      status: 'approved',
    },
    {
      "id": "voc_b1_noteworthy_209",
      word: "noteworthy",
      translation: "digno de mención",
      partOfSpeech: 'adjective',
      level: "B1",
      week: 9,
      topic: "advanced_adjectives",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈnoʊtˌwɜrði/',
      example: 'This is a noteworthy achievement.',
      exampleTranslation: 'Este es un logro digno de mención.',
      status: 'approved',
    },
    {
      "id": "voc_b1_inevitable_210",
      word: "inevitable",
      translation: "inevitable",
      partOfSpeech: 'adjective',
      level: "B1",
      week: 9,
      topic: "advanced_adjectives",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ɪnˈɛvɪtəbəl/',
      example: 'Change was inevitable.',
      exampleTranslation: 'El cambio era inevitable.',
      status: 'approved',
    },
    {
      "id": "voc_b1_plausible_211",
      word: "plausible",
      translation: "plausible",
      partOfSpeech: 'adjective',
      level: "B1",
      week: 9,
      topic: "advanced_adjectives",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈplɔzəbəl/',
      example: 'That explanation seems plausible.',
      exampleTranslation: 'Esa explicación parece plausible.',
      status: 'approved',
    },
    {
      "id": "voc_b1_feasible_212",
      word: "feasible",
      translation: "factible",
      partOfSpeech: 'adjective',
      level: "B1",
      week: 9,
      topic: "advanced_adjectives",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈfizəbəl/',
      example: 'Is this plan feasible?',
      exampleTranslation: '¿Es factible este plan?',
      status: 'approved',
    },
    {
      "id": "voc_b1_viable_213",
      word: "viable",
      translation: "viable",
      partOfSpeech: 'adjective',
      level: "B1",
      week: 9,
      topic: "advanced_adjectives",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈvaɪəbəl/',
      example: 'We need a viable solution.',
      exampleTranslation: 'Necesitamos una solución viable.',
      status: 'approved',
    },
    {
      "id": "voc_b1_consistent_214",
      word: "consistent",
      translation: "consistente/constante",
      partOfSpeech: 'adjective',
      level: "B1",
      week: 9,
      topic: "advanced_adjectives",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/kənˈsɪstənt/',
      example: 'Her performance has been consistent.',
      exampleTranslation: 'Su desempeño ha sido consistente.',
      status: 'approved',
    },
    {
      "id": "voc_b1_coherent_215",
      word: "coherent",
      translation: "coherente",
      partOfSpeech: 'adjective',
      level: "B1",
      week: 9,
      topic: "advanced_adjectives",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/koʊˈhɪrənt/',
      example: 'The essay wasn\'t very coherent.',
      exampleTranslation: 'El ensayo no fue muy coherente.',
      status: 'approved',
    },
    {
      "id": "voc_b1_comprehensive_216",
      word: "comprehensive",
      translation: "integral/exhaustivo",
      partOfSpeech: 'adjective',
      level: "B1",
      week: 9,
      topic: "advanced_adjectives",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˌkɑmprɪˈhɛnsɪv/',
      example: 'We need a comprehensive plan.',
      exampleTranslation: 'Necesitamos un plan integral.',
      status: 'approved',
    },
    {
      "id": "voc_b1_thorough_217",
      word: "thorough",
      translation: "minucioso",
      partOfSpeech: 'adjective',
      level: "B1",
      week: 9,
      topic: "advanced_adjectives",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈθɜroʊ/',
      example: 'He did a thorough review of the report.',
      exampleTranslation: 'Él hizo una revisión minuciosa del informe.',
      status: 'approved',
    },
    {
      "id": "voc_b1_superficial_218",
      word: "superficial",
      translation: "superficial",
      partOfSpeech: 'adjective',
      level: "B1",
      week: 9,
      topic: "advanced_adjectives",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˌsupərˈfɪʃəl/',
      example: 'His knowledge is quite superficial.',
      exampleTranslation: 'Su conocimiento es bastante superficial.',
      status: 'approved',
    },
    {
      "id": "voc_b1_subtle_219",
      word: "subtle",
      translation: "sutil",
      partOfSpeech: 'adjective',
      level: "B1",
      week: 9,
      topic: "advanced_adjectives",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈsʌtəl/',
      example: 'There was a subtle change in her voice.',
      exampleTranslation: 'Hubo un cambio sutil en su voz.',
      status: 'approved',
    },
    {
      "id": "voc_b1_versatile_220",
      word: "versatile",
      translation: "versátil",
      partOfSpeech: 'adjective',
      level: "B1",
      week: 9,
      topic: "advanced_adjectives",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈvɜrsətəl/',
      example: 'She is a versatile actress.',
      exampleTranslation: 'Ella es una actriz versátil.',
      status: 'approved',
    },
    {
      "id": "voc_b1_adaptable_221",
      word: "adaptable",
      translation: "adaptable",
      partOfSpeech: 'adjective',
      level: "B1",
      week: 9,
      topic: "advanced_adjectives",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/əˈdæptəbəl/',
      example: 'He is very adaptable to new situations.',
      exampleTranslation: 'Él es muy adaptable a nuevas situaciones.',
      status: 'approved',
    },
    {
      "id": "voc_b1_innovative_222",
      word: "innovative",
      translation: "innovador",
      partOfSpeech: 'adjective',
      level: "B1",
      week: 9,
      topic: "advanced_adjectives",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈɪnəˌveɪtɪv/',
      example: 'They came up with an innovative idea.',
      exampleTranslation: 'Ellos idearon una idea innovadora.',
      status: 'approved',
    },
    {
      "id": "voc_b1_conventional_223",
      word: "conventional",
      translation: "convencional",
      partOfSpeech: 'adjective',
      level: "B1",
      week: 9,
      topic: "advanced_adjectives",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/kənˈvɛnʃənəl/',
      example: 'This is a more conventional approach.',
      exampleTranslation: 'Este es un enfoque más convencional.',
      status: 'approved',
    },
    {
      "id": "voc_b1_prevalent_224",
      word: "prevalent",
      translation: "predominante",
      partOfSpeech: 'adjective',
      level: "B1",
      week: 9,
      topic: "advanced_adjectives",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈprɛvələnt/',
      example: 'This problem is prevalent in big cities.',
      exampleTranslation: 'Este problema es predominante en las grandes ciudades.',
      status: 'approved',
    },
    {
      "id": "voc_b1_widespread_225",
      word: "widespread",
      translation: "generalizado",
      partOfSpeech: 'adjective',
      level: "B1",
      week: 9,
      topic: "advanced_adjectives",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈwaɪdˌsprɛd/',
      example: 'The disease caused widespread panic.',
      exampleTranslation: 'La enfermedad causó pánico generalizado.',
      status: 'approved',
    },
    {
      "id": "voc_b1_prominent_226",
      word: "prominent",
      translation: "prominente/destacado",
      partOfSpeech: 'adjective',
      level: "B1",
      week: 9,
      topic: "advanced_adjectives",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈprɑmənənt/',
      example: 'He is a prominent scientist.',
      exampleTranslation: 'Él es un científico prominente.',
      status: 'approved',
    }
  ]
}
