import type { ContentBlock } from '../types'

/**
 * B1 Level Content — Week 1
 * Topic: B1 · Semana 1 – Phrasal verbs esenciales
 * Curated from institutional curriculum (Zero AI)
 */
export const week01: ContentBlock = {
  "level": "B1",
  "week": 1,
  "topic": "B1 · Semana 1 – Phrasal verbs esenciales",
  "vocabulary": [
    {
      "id": "voc_b1_give-up_001",
      "word": "give up",
      "translation": "rendirse/dejar de hacer algo",
      "partOfSpeech": "phrasal-verb",
      "level": "B1",
      "week": 1,
      "topic": "phrasal_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_look-forward-to_002",
      "word": "look forward to",
      "translation": "esperar con ilusión",
      "partOfSpeech": "phrasal-verb",
      "level": "B1",
      "week": 1,
      "topic": "phrasal_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_get-along-with_003",
      "word": "get along with",
      "translation": "llevarse bien con",
      "partOfSpeech": "phrasal-verb",
      "level": "B1",
      "week": 1,
      "topic": "phrasal_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_put-off_004",
      "word": "put off",
      "translation": "posponer",
      "partOfSpeech": "phrasal-verb",
      "level": "B1",
      "week": 1,
      "topic": "phrasal_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_run-into_005",
      "word": "run into",
      "translation": "encontrarse por casualidad con",
      "partOfSpeech": "phrasal-verb",
      "level": "B1",
      "week": 1,
      "topic": "phrasal_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_come-across_006",
      "word": "come across",
      "translation": "encontrarse/toparse con algo",
      "partOfSpeech": "phrasal-verb",
      "level": "B1",
      "week": 1,
      "topic": "phrasal_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_look-after_007",
      "word": "look after",
      "translation": "cuidar de",
      "partOfSpeech": "phrasal-verb",
      "level": "B1",
      "week": 1,
      "topic": "phrasal_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_turn-down_008",
      "word": "turn down",
      "translation": "rechazar",
      "partOfSpeech": "phrasal-verb",
      "level": "B1",
      "week": 1,
      "topic": "phrasal_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_find-out_009",
      "word": "find out",
      "translation": "descubrir/averiguar",
      "partOfSpeech": "phrasal-verb",
      "level": "B1",
      "week": 1,
      "topic": "phrasal_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_work-out_010",
      "word": "work out",
      "translation": "resolver / hacer ejercicio",
      "partOfSpeech": "phrasal-verb",
      "level": "B1",
      "week": 1,
      "topic": "phrasal_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_deal-with_011",
      "word": "deal with",
      "translation": "lidiar con",
      "partOfSpeech": "phrasal-verb",
      "level": "B1",
      "week": 1,
      "topic": "phrasal_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_end-up_012",
      "word": "end up",
      "translation": "terminar (en una situación)",
      "partOfSpeech": "phrasal-verb",
      "level": "B1",
      "week": 1,
      "topic": "phrasal_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_carry-on_013",
      "word": "carry on",
      "translation": "continuar",
      "partOfSpeech": "phrasal-verb",
      "level": "B1",
      "week": 1,
      "topic": "phrasal_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_figure-out_014",
      "word": "figure out",
      "translation": "entender/descifrar",
      "partOfSpeech": "phrasal-verb",
      "level": "B1",
      "week": 1,
      "topic": "phrasal_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_point-out_015",
      "word": "point out",
      "translation": "señalar",
      "partOfSpeech": "phrasal-verb",
      "level": "B1",
      "week": 1,
      "topic": "phrasal_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_break-down_016",
      "word": "break down",
      "translation": "descomponerse / desglosar",
      "partOfSpeech": "phrasal-verb",
      "level": "B1",
      "week": 1,
      "topic": "phrasal_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_bring-up_017",
      "word": "bring up",
      "translation": "criar / sacar un tema",
      "partOfSpeech": "phrasal-verb",
      "level": "B1",
      "week": 1,
      "topic": "phrasal_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_call-off_018",
      "word": "call off",
      "translation": "cancelar",
      "partOfSpeech": "phrasal-verb",
      "level": "B1",
      "week": 1,
      "topic": "phrasal_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_count-on_019",
      "word": "count on",
      "translation": "contar con (confiar)",
      "partOfSpeech": "phrasal-verb",
      "level": "B1",
      "week": 1,
      "topic": "phrasal_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_cut-down-on_020",
      "word": "cut down on",
      "translation": "reducir (consumo)",
      "partOfSpeech": "phrasal-verb",
      "level": "B1",
      "week": 1,
      "topic": "phrasal_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_drop-by_021",
      "word": "drop by",
      "translation": "pasar de visita",
      "partOfSpeech": "phrasal-verb",
      "level": "B1",
      "week": 1,
      "topic": "phrasal_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_fall-apart_022",
      "word": "fall apart",
      "translation": "desmoronarse",
      "partOfSpeech": "phrasal-verb",
      "level": "B1",
      "week": 1,
      "topic": "phrasal_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_get-over_023",
      "word": "get over",
      "translation": "superar",
      "partOfSpeech": "phrasal-verb",
      "level": "B1",
      "week": 1,
      "topic": "phrasal_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_hang-out_024",
      "word": "hang out",
      "translation": "pasar el rato",
      "partOfSpeech": "phrasal-verb",
      "level": "B1",
      "week": 1,
      "topic": "phrasal_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_hold-on_025",
      "word": "hold on",
      "translation": "esperar un momento",
      "partOfSpeech": "phrasal-verb",
      "level": "B1",
      "week": 1,
      "topic": "phrasal_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_let-down_026",
      "word": "let down",
      "translation": "decepcionar",
      "partOfSpeech": "phrasal-verb",
      "level": "B1",
      "week": 1,
      "topic": "phrasal_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_make-up_027",
      "word": "make up",
      "translation": "inventar / reconciliarse",
      "partOfSpeech": "phrasal-verb",
      "level": "B1",
      "week": 1,
      "topic": "phrasal_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_pass-away_028",
      "word": "pass away",
      "translation": "fallecer",
      "partOfSpeech": "phrasal-verb",
      "level": "B1",
      "week": 1,
      "topic": "phrasal_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_pull-off_029",
      "word": "pull off",
      "translation": "lograr algo difícil",
      "partOfSpeech": "phrasal-verb",
      "level": "B1",
      "week": 1,
      "topic": "phrasal_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_put-up-with_030",
      "word": "put up with",
      "translation": "tolerar/aguantar",
      "partOfSpeech": "phrasal-verb",
      "level": "B1",
      "week": 1,
      "topic": "phrasal_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_show-up_031",
      "word": "show up",
      "translation": "aparecer/presentarse",
      "partOfSpeech": "phrasal-verb",
      "level": "B1",
      "week": 1,
      "topic": "phrasal_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_sort-out_032",
      "word": "sort out",
      "translation": "resolver/organizar",
      "partOfSpeech": "phrasal-verb",
      "level": "B1",
      "week": 1,
      "topic": "phrasal_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_stand-for_033",
      "word": "stand for",
      "translation": "representar/significar",
      "partOfSpeech": "phrasal-verb",
      "level": "B1",
      "week": 1,
      "topic": "phrasal_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_take-after_034",
      "word": "take after",
      "translation": "parecerse a (familiar)",
      "partOfSpeech": "phrasal-verb",
      "level": "B1",
      "week": 1,
      "topic": "phrasal_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_throw-away_035",
      "word": "throw away",
      "translation": "desechar",
      "partOfSpeech": "phrasal-verb",
      "level": "B1",
      "week": 1,
      "topic": "phrasal_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_wear-out_036",
      "word": "wear out",
      "translation": "desgastar/agotar",
      "partOfSpeech": "phrasal-verb",
      "level": "B1",
      "week": 1,
      "topic": "phrasal_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    }
  ]
}
