import type { ContentBlock } from '../types'

/**
 * B1 Level Content — Week 5
 * Topic: B1 · Semana 5 – Verbos de argumentación y análisis
 * Curated from institutional curriculum (Zero AI)
 */
export const week05: ContentBlock = {
  "level": "B1",
  "week": 5,
  "topic": "B1 · Semana 5 – Verbos de argumentación y análisis",
  "vocabulary": [
    {
      "id": "voc_b1_assume_120",
      "word": "assume",
      "translation": "suponer",
      "partOfSpeech": "verb",
      "level": "B1",
      "week": 5,
      "topic": "argumentation_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_argue-that_121",
      "word": "argue (that)",
      "translation": "argumentar/sostener que",
      "partOfSpeech": "verb",
      "level": "B1",
      "week": 5,
      "topic": "argumentation_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_claim_122",
      "word": "claim",
      "translation": "afirmar/alegar",
      "partOfSpeech": "verb",
      "level": "B1",
      "week": 5,
      "topic": "argumentation_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_demonstrate_123",
      "word": "demonstrate",
      "translation": "demostrar",
      "partOfSpeech": "verb",
      "level": "B1",
      "week": 5,
      "topic": "argumentation_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_emphasize_124",
      "word": "emphasize",
      "translation": "enfatizar",
      "partOfSpeech": "verb",
      "level": "B1",
      "week": 5,
      "topic": "argumentation_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_imply_125",
      "word": "imply",
      "translation": "insinuar/implicar",
      "partOfSpeech": "verb",
      "level": "B1",
      "week": 5,
      "topic": "argumentation_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_indicate_126",
      "word": "indicate",
      "translation": "indicar",
      "partOfSpeech": "verb",
      "level": "B1",
      "week": 5,
      "topic": "argumentation_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_justify_127",
      "word": "justify",
      "translation": "justificar",
      "partOfSpeech": "verb",
      "level": "B1",
      "week": 5,
      "topic": "argumentation_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_maintain-an-opinion_128",
      "word": "maintain (an opinion)",
      "translation": "mantener/sostener una postura",
      "partOfSpeech": "verb",
      "level": "B1",
      "week": 5,
      "topic": "argumentation_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_predict_129",
      "word": "predict",
      "translation": "predecir",
      "partOfSpeech": "verb",
      "level": "B1",
      "week": 5,
      "topic": "argumentation_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_prove_130",
      "word": "prove",
      "translation": "probar/demostrar",
      "partOfSpeech": "verb",
      "level": "B1",
      "week": 5,
      "topic": "argumentation_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_reveal_131",
      "word": "reveal",
      "translation": "revelar",
      "partOfSpeech": "verb",
      "level": "B1",
      "week": 5,
      "topic": "argumentation_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_acknowledge_132",
      "word": "acknowledge",
      "translation": "reconocer",
      "partOfSpeech": "verb",
      "level": "B1",
      "week": 5,
      "topic": "argumentation_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_analyze_133",
      "word": "analyze",
      "translation": "analizar",
      "partOfSpeech": "verb",
      "level": "B1",
      "week": 5,
      "topic": "argumentation_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_assess_134",
      "word": "assess",
      "translation": "evaluar/valorar",
      "partOfSpeech": "verb",
      "level": "B1",
      "week": 5,
      "topic": "argumentation_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_clarify_135",
      "word": "clarify",
      "translation": "aclarar",
      "partOfSpeech": "verb",
      "level": "B1",
      "week": 5,
      "topic": "argumentation_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_conclude_136",
      "word": "conclude",
      "translation": "concluir",
      "partOfSpeech": "verb",
      "level": "B1",
      "week": 5,
      "topic": "argumentation_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_contradict_137",
      "word": "contradict",
      "translation": "contradecir",
      "partOfSpeech": "verb",
      "level": "B1",
      "week": 5,
      "topic": "argumentation_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_distinguish_138",
      "word": "distinguish",
      "translation": "distinguir",
      "partOfSpeech": "verb",
      "level": "B1",
      "week": 5,
      "topic": "argumentation_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_elaborate-on_139",
      "word": "elaborate (on)",
      "translation": "desarrollar/profundizar en",
      "partOfSpeech": "verb",
      "level": "B1",
      "week": 5,
      "topic": "argumentation_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_examine_140",
      "word": "examine",
      "translation": "examinar",
      "partOfSpeech": "verb",
      "level": "B1",
      "week": 5,
      "topic": "argumentation_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_highlight_141",
      "word": "highlight",
      "translation": "destacar",
      "partOfSpeech": "verb",
      "level": "B1",
      "week": 5,
      "topic": "argumentation_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_illustrate-an-idea_142",
      "word": "illustrate (an idea)",
      "translation": "ilustrar (una idea)",
      "partOfSpeech": "verb",
      "level": "B1",
      "week": 5,
      "topic": "argumentation_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_interpret_143",
      "word": "interpret",
      "translation": "interpretar",
      "partOfSpeech": "verb",
      "level": "B1",
      "week": 5,
      "topic": "argumentation_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_outline-a-plan_144",
      "word": "outline (a plan)",
      "translation": "esbozar (un plan)",
      "partOfSpeech": "verb",
      "level": "B1",
      "week": 5,
      "topic": "argumentation_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_summarize_145",
      "word": "summarize",
      "translation": "resumir",
      "partOfSpeech": "verb",
      "level": "B1",
      "week": 5,
      "topic": "argumentation_verbs",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    }
  ]
}
