import type { ContentBlock } from '../types'

/**
 * B1 Level Content — Week 1
 * Topic: B1 · Semana 1 – Phrasal verbs esenciales
 * Curated from institutional curriculum (Zero AI)
 */
export const week01: ContentBlock = {
  level: "B1",
  week: 1,
  topic: "B1 · Semana 1 – Phrasal verbs esenciales",
  vocabulary: [
    {
      "id": "voc_b1_give-up_001",
      word: "give up",
      translation: "rendirse/dejar de hacer algo",
      partOfSpeech: 'phrasal-verb',
      level: "B1",
      week: 1,
      topic: "phrasal_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/gɪv ʌp/',
      example: 'Don\'t give up on your dreams.',
      exampleTranslation: 'No renuncies a tus sueños.',
      status: 'approved',
    },
    {
      "id": "voc_b1_look-forward-to_002",
      word: "look forward to",
      translation: "esperar con ilusión",
      partOfSpeech: 'phrasal-verb',
      level: "B1",
      week: 1,
      topic: "phrasal_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/lʊk ˈfɔrwərd tu/',
      example: 'I look forward to seeing you soon.',
      exampleTranslation: 'Espero con ilusión verte pronto.',
      status: 'approved',
    },
    {
      "id": "voc_b1_get-along-with_003",
      word: "get along with",
      translation: "llevarse bien con",
      partOfSpeech: 'phrasal-verb',
      level: "B1",
      week: 1,
      topic: "phrasal_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/gɛt əˈlɔŋ wɪð/',
      example: 'I get along with my coworkers.',
      exampleTranslation: 'Me llevo bien con mis compañeros de trabajo.',
      status: 'approved',
    },
    {
      "id": "voc_b1_put-off_004",
      word: "put off",
      translation: "posponer",
      partOfSpeech: 'phrasal-verb',
      level: "B1",
      week: 1,
      topic: "phrasal_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/pʊt ɔf/',
      example: 'Don\'t put off the meeting again.',
      exampleTranslation: 'No pospongas la reunión de nuevo.',
      status: 'approved',
    },
    {
      "id": "voc_b1_run-into_005",
      word: "run into",
      translation: "encontrarse por casualidad con",
      partOfSpeech: 'phrasal-verb',
      level: "B1",
      week: 1,
      topic: "phrasal_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/rʌn ˈɪntu/',
      example: 'I ran into an old friend downtown.',
      exampleTranslation: 'Me encontré por casualidad con un viejo amigo en el centro.',
      status: 'approved',
    },
    {
      "id": "voc_b1_come-across_006",
      word: "come across",
      translation: "encontrarse/toparse con algo",
      partOfSpeech: 'phrasal-verb',
      level: "B1",
      week: 1,
      topic: "phrasal_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/kʌm əˈkrɔs/',
      example: 'I came across an interesting article.',
      exampleTranslation: 'Me topé con un artículo interesante.',
      status: 'approved',
    },
    {
      "id": "voc_b1_look-after_007",
      word: "look after",
      translation: "cuidar de",
      partOfSpeech: 'phrasal-verb',
      level: "B1",
      week: 1,
      topic: "phrasal_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/lʊk ˈæftər/',
      example: 'She looks after her grandmother.',
      exampleTranslation: 'Ella cuida de su abuela.',
      status: 'approved',
    },
    {
      "id": "voc_b1_turn-down_008",
      word: "turn down",
      translation: "rechazar",
      partOfSpeech: 'phrasal-verb',
      level: "B1",
      week: 1,
      topic: "phrasal_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/tɜrn daʊn/',
      example: 'He turned down the job offer.',
      exampleTranslation: 'Él rechazó la oferta de trabajo.',
      status: 'approved',
    },
    {
      "id": "voc_b1_find-out_009",
      word: "find out",
      translation: "descubrir/averiguar",
      partOfSpeech: 'phrasal-verb',
      level: "B1",
      week: 1,
      topic: "phrasal_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/faɪnd aʊt/',
      example: 'I need to find out the truth.',
      exampleTranslation: 'Necesito descubrir la verdad.',
      status: 'approved',
    },
    {
      "id": "voc_b1_work-out_010",
      word: "work out",
      translation: "resolver / hacer ejercicio",
      partOfSpeech: 'phrasal-verb',
      level: "B1",
      week: 1,
      topic: "phrasal_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/wɜrk aʊt/',
      example: 'Everything worked out fine in the end.',
      exampleTranslation: 'Todo se resolvió bien al final.',
      status: 'approved',
    },
    {
      "id": "voc_b1_deal-with_011",
      word: "deal with",
      translation: "lidiar con",
      partOfSpeech: 'phrasal-verb',
      level: "B1",
      week: 1,
      topic: "phrasal_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/dil wɪð/',
      example: 'I have to deal with this problem today.',
      exampleTranslation: 'Tengo que lidiar con este problema hoy.',
      status: 'approved',
    },
    {
      "id": "voc_b1_end-up_012",
      word: "end up",
      translation: "terminar (en una situación)",
      partOfSpeech: 'phrasal-verb',
      level: "B1",
      week: 1,
      topic: "phrasal_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ɛnd ʌp/',
      example: 'We ended up staying home.',
      exampleTranslation: 'Terminamos quedándonos en casa.',
      status: 'approved',
    },
    {
      "id": "voc_b1_carry-on_013",
      word: "carry on",
      translation: "continuar",
      partOfSpeech: 'phrasal-verb',
      level: "B1",
      week: 1,
      topic: "phrasal_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈkæri ɑn/',
      example: 'Please carry on with your presentation.',
      exampleTranslation: 'Por favor continúa con tu presentación.',
      status: 'approved',
    },
    {
      "id": "voc_b1_figure-out_014",
      word: "figure out",
      translation: "entender/descifrar",
      partOfSpeech: 'phrasal-verb',
      level: "B1",
      week: 1,
      topic: "phrasal_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈfɪgjər aʊt/',
      example: 'I can\'t figure out this puzzle.',
      exampleTranslation: 'No logro descifrar este rompecabezas.',
      status: 'approved',
    },
    {
      "id": "voc_b1_point-out_015",
      word: "point out",
      translation: "señalar",
      partOfSpeech: 'phrasal-verb',
      level: "B1",
      week: 1,
      topic: "phrasal_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/pɔɪnt aʊt/',
      example: 'She pointed out a mistake in the report.',
      exampleTranslation: 'Ella señaló un error en el informe.',
      status: 'approved',
    },
    {
      "id": "voc_b1_break-down_016",
      word: "break down",
      translation: "descomponerse / desglosar",
      partOfSpeech: 'phrasal-verb',
      level: "B1",
      week: 1,
      topic: "phrasal_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/breɪk daʊn/',
      example: 'My car broke down on the highway.',
      exampleTranslation: 'Mi carro se descompuso en la autopista.',
      status: 'approved',
    },
    {
      "id": "voc_b1_bring-up_017",
      word: "bring up",
      translation: "criar / sacar un tema",
      partOfSpeech: 'phrasal-verb',
      level: "B1",
      week: 1,
      topic: "phrasal_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/brɪŋ ʌp/',
      example: 'He brought up an important topic.',
      exampleTranslation: 'Él sacó a relucir un tema importante.',
      status: 'approved',
    },
    {
      "id": "voc_b1_call-off_018",
      word: "call off",
      translation: "cancelar",
      partOfSpeech: 'phrasal-verb',
      level: "B1",
      week: 1,
      topic: "phrasal_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/kɔl ɔf/',
      example: 'They called off the wedding.',
      exampleTranslation: 'Cancelaron la boda.',
      status: 'approved',
    },
    {
      "id": "voc_b1_count-on_019",
      word: "count on",
      translation: "contar con (confiar)",
      partOfSpeech: 'phrasal-verb',
      level: "B1",
      week: 1,
      topic: "phrasal_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/kaʊnt ɑn/',
      example: 'You can always count on me.',
      exampleTranslation: 'Siempre puedes contar conmigo.',
      status: 'approved',
    },
    {
      "id": "voc_b1_cut-down-on_020",
      word: "cut down on",
      translation: "reducir (consumo)",
      partOfSpeech: 'phrasal-verb',
      level: "B1",
      week: 1,
      topic: "phrasal_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/kʌt daʊn ɑn/',
      example: 'I need to cut down on sugar.',
      exampleTranslation: 'Necesito reducir el consumo de azúcar.',
      status: 'approved',
    },
    {
      "id": "voc_b1_drop-by_021",
      word: "drop by",
      translation: "pasar de visita",
      partOfSpeech: 'phrasal-verb',
      level: "B1",
      week: 1,
      topic: "phrasal_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/drɑp baɪ/',
      example: 'Feel free to drop by anytime.',
      exampleTranslation: 'Siéntete libre de pasar de visita cuando quieras.',
      status: 'approved',
    },
    {
      "id": "voc_b1_fall-apart_022",
      word: "fall apart",
      translation: "desmoronarse",
      partOfSpeech: 'phrasal-verb',
      level: "B1",
      week: 1,
      topic: "phrasal_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/fɔl əˈpɑrt/',
      example: 'Their plan fell apart quickly.',
      exampleTranslation: 'Su plan se desmoronó rápidamente.',
      status: 'approved',
    },
    {
      "id": "voc_b1_get-over_023",
      word: "get over",
      translation: "superar",
      partOfSpeech: 'phrasal-verb',
      level: "B1",
      week: 1,
      topic: "phrasal_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/gɛt ˈoʊvər/',
      example: 'It took him months to get over the loss.',
      exampleTranslation: 'Le tomó meses superar la pérdida.',
      status: 'approved',
    },
    {
      "id": "voc_b1_hang-out_024",
      word: "hang out",
      translation: "pasar el rato",
      partOfSpeech: 'phrasal-verb',
      level: "B1",
      week: 1,
      topic: "phrasal_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/hæŋ aʊt/',
      example: 'We hung out at the park all afternoon.',
      exampleTranslation: 'Pasamos el rato en el parque toda la tarde.',
      status: 'approved',
    },
    {
      "id": "voc_b1_hold-on_025",
      word: "hold on",
      translation: "esperar un momento",
      partOfSpeech: 'phrasal-verb',
      level: "B1",
      week: 1,
      topic: "phrasal_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/hoʊld ɑn/',
      example: 'Hold on, I\'ll be right there.',
      exampleTranslation: 'Espera un momento, ya voy.',
      status: 'approved',
    },
    {
      "id": "voc_b1_let-down_026",
      word: "let down",
      translation: "decepcionar",
      partOfSpeech: 'phrasal-verb',
      level: "B1",
      week: 1,
      topic: "phrasal_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/lɛt daʊn/',
      example: 'I don\'t want to let you down.',
      exampleTranslation: 'No quiero decepcionarte.',
      status: 'approved',
    },
    {
      "id": "voc_b1_make-up_027",
      word: "make up",
      translation: "inventar / reconciliarse",
      partOfSpeech: 'phrasal-verb',
      level: "B1",
      week: 1,
      topic: "phrasal_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/meɪk ʌp/',
      example: 'They made up after the argument.',
      exampleTranslation: 'Se reconciliaron después de la discusión.',
      status: 'approved',
    },
    {
      "id": "voc_b1_pass-away_028",
      word: "pass away",
      translation: "fallecer",
      partOfSpeech: 'phrasal-verb',
      level: "B1",
      week: 1,
      topic: "phrasal_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/pæs əˈweɪ/',
      example: 'Her grandfather passed away last year.',
      exampleTranslation: 'Su abuelo falleció el año pasado.',
      status: 'approved',
    },
    {
      "id": "voc_b1_pull-off_029",
      word: "pull off",
      translation: "lograr algo difícil",
      partOfSpeech: 'phrasal-verb',
      level: "B1",
      week: 1,
      topic: "phrasal_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/pʊl ɔf/',
      example: 'She managed to pull off the event perfectly.',
      exampleTranslation: 'Ella logró sacar adelante el evento perfectamente.',
      status: 'approved',
    },
    {
      "id": "voc_b1_put-up-with_030",
      word: "put up with",
      translation: "tolerar/aguantar",
      partOfSpeech: 'phrasal-verb',
      level: "B1",
      week: 1,
      topic: "phrasal_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/pʊt ʌp wɪð/',
      example: 'I can\'t put up with this noise anymore.',
      exampleTranslation: 'Ya no puedo tolerar este ruido.',
      status: 'approved',
    },
    {
      "id": "voc_b1_show-up_031",
      word: "show up",
      translation: "aparecer/presentarse",
      partOfSpeech: 'phrasal-verb',
      level: "B1",
      week: 1,
      topic: "phrasal_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ʃoʊ ʌp/',
      example: 'He didn\'t show up to the meeting.',
      exampleTranslation: 'Él no se presentó a la reunión.',
      status: 'approved',
    },
    {
      "id": "voc_b1_sort-out_032",
      word: "sort out",
      translation: "resolver/organizar",
      partOfSpeech: 'phrasal-verb',
      level: "B1",
      week: 1,
      topic: "phrasal_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/sɔrt aʊt/',
      example: 'We need to sort out this issue.',
      exampleTranslation: 'Necesitamos resolver este asunto.',
      status: 'approved',
    },
    {
      "id": "voc_b1_stand-for_033",
      word: "stand for",
      translation: "representar/significar",
      partOfSpeech: 'phrasal-verb',
      level: "B1",
      week: 1,
      topic: "phrasal_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/stænd fɔr/',
      example: 'What does this abbreviation stand for?',
      exampleTranslation: '¿Qué representa esta abreviatura?',
      status: 'approved',
    },
    {
      "id": "voc_b1_take-after_034",
      word: "take after",
      translation: "parecerse a (familiar)",
      partOfSpeech: 'phrasal-verb',
      level: "B1",
      week: 1,
      topic: "phrasal_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/teɪk ˈæftər/',
      example: 'She takes after her mother.',
      exampleTranslation: 'Ella se parece a su madre.',
      status: 'approved',
    },
    {
      "id": "voc_b1_throw-away_035",
      word: "throw away",
      translation: "desechar",
      partOfSpeech: 'phrasal-verb',
      level: "B1",
      week: 1,
      topic: "phrasal_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/θroʊ əˈweɪ/',
      example: 'Don\'t throw away that document.',
      exampleTranslation: 'No deseches ese documento.',
      status: 'approved',
    },
    {
      "id": "voc_b1_wear-out_036",
      word: "wear out",
      translation: "desgastar/agotar",
      partOfSpeech: 'phrasal-verb',
      level: "B1",
      week: 1,
      topic: "phrasal_verbs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/wɛr aʊt/',
      example: 'These shoes wore out fast.',
      exampleTranslation: 'Estos zapatos se desgastaron rápido.',
      status: 'approved',
    }
  ]
}
