import type { ContentBlock } from '../types'

/**
 * B1 Level Content — Week 3
 * Topic: B1 · Semana 3 – Sustantivos abstractos de uso frecuente
 * Curated from institutional curriculum (Zero AI)
 */
export const week03: ContentBlock = {
  "level": "B1",
  "week": 3,
  "topic": "B1 · Semana 3 – Sustantivos abstractos de uso frecuente",
  "vocabulary": [
    {
      "id": "voc_b1_achievement_061",
      "word": "achievement",
      "translation": "logro",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 3,
      "topic": "abstract_nouns",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_assumption_062",
      "word": "assumption",
      "translation": "suposición",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 3,
      "topic": "abstract_nouns",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_attitude_063",
      "word": "attitude",
      "translation": "actitud",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 3,
      "topic": "abstract_nouns",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_awareness_064",
      "word": "awareness",
      "translation": "conciencia (de algo)",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 3,
      "topic": "abstract_nouns",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_behavior_065",
      "word": "behavior",
      "translation": "comportamiento",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 3,
      "topic": "abstract_nouns",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_capability_066",
      "word": "capability",
      "translation": "capacidad",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 3,
      "topic": "abstract_nouns",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_circumstance_067",
      "word": "circumstance",
      "translation": "circunstancia",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 3,
      "topic": "abstract_nouns",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_consequence_068",
      "word": "consequence",
      "translation": "consecuencia",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 3,
      "topic": "abstract_nouns",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_consideration_069",
      "word": "consideration",
      "translation": "consideración",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 3,
      "topic": "abstract_nouns",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_contribution_070",
      "word": "contribution",
      "translation": "contribución",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 3,
      "topic": "abstract_nouns",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_credibility_071",
      "word": "credibility",
      "translation": "credibilidad",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 3,
      "topic": "abstract_nouns",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_definition_072",
      "word": "definition",
      "translation": "definición",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 3,
      "topic": "abstract_nouns",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_dimension_073",
      "word": "dimension",
      "translation": "dimensión",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 3,
      "topic": "abstract_nouns",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_emphasis_074",
      "word": "emphasis",
      "translation": "énfasis",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 3,
      "topic": "abstract_nouns",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_evaluation_075",
      "word": "evaluation",
      "translation": "evaluación",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 3,
      "topic": "abstract_nouns",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_factor_076",
      "word": "factor",
      "translation": "factor",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 3,
      "topic": "abstract_nouns",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_framework_077",
      "word": "framework",
      "translation": "marco (de referencia)",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 3,
      "topic": "abstract_nouns",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_function_078",
      "word": "function",
      "translation": "función",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 3,
      "topic": "abstract_nouns",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_impact_079",
      "word": "impact",
      "translation": "impacto",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 3,
      "topic": "abstract_nouns",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_initiative_080",
      "word": "initiative",
      "translation": "iniciativa",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 3,
      "topic": "abstract_nouns",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_insight_081",
      "word": "insight",
      "translation": "percepción profunda",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 3,
      "topic": "abstract_nouns",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_integrity_082",
      "word": "integrity",
      "translation": "integridad",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 3,
      "topic": "abstract_nouns",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_motivation_083",
      "word": "motivation",
      "translation": "motivación",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 3,
      "topic": "abstract_nouns",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_objective-noun_084",
      "word": "objective (noun)",
      "translation": "objetivo",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 3,
      "topic": "abstract_nouns",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_outcome_085",
      "word": "outcome",
      "translation": "resultado",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 3,
      "topic": "abstract_nouns",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_perception_086",
      "word": "perception",
      "translation": "percepción",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 3,
      "topic": "abstract_nouns",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_phenomenon_087",
      "word": "phenomenon",
      "translation": "fenómeno",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 3,
      "topic": "abstract_nouns",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_principle_088",
      "word": "principle",
      "translation": "principio",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 3,
      "topic": "abstract_nouns",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_priority_089",
      "word": "priority",
      "translation": "prioridad",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 3,
      "topic": "abstract_nouns",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_procedure_090",
      "word": "procedure",
      "translation": "procedimiento",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 3,
      "topic": "abstract_nouns",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_process_091",
      "word": "process",
      "translation": "proceso",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 3,
      "topic": "abstract_nouns",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_reputation_092",
      "word": "reputation",
      "translation": "reputación",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 3,
      "topic": "abstract_nouns",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_scenario_093",
      "word": "scenario",
      "translation": "escenario",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 3,
      "topic": "abstract_nouns",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_significance_094",
      "word": "significance",
      "translation": "importancia/relevancia",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 3,
      "topic": "abstract_nouns",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_stability_095",
      "word": "stability",
      "translation": "estabilidad",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 3,
      "topic": "abstract_nouns",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_structure_096",
      "word": "structure",
      "translation": "estructura",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 3,
      "topic": "abstract_nouns",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_tendency_097",
      "word": "tendency",
      "translation": "tendencia",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 3,
      "topic": "abstract_nouns",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_theory_098",
      "word": "theory",
      "translation": "teoría",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 3,
      "topic": "abstract_nouns",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_transition_099",
      "word": "transition",
      "translation": "transición",
      "partOfSpeech": "noun",
      "level": "B1",
      "week": 3,
      "topic": "abstract_nouns",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    }
  ]
}
