import type { ContentBlock } from '../types'

/**
 * B1 Level Content — Week 4
 * Topic: B1 · Semana 4 – Conectores avanzados del discurso
 * Curated from institutional curriculum (Zero AI)
 */
export const week04: ContentBlock = {
  level: "B1",
  week: 4,
  topic: "B1 · Semana 4 – Conectores avanzados del discurso",
  vocabulary: [
    {
      "id": "voc_b1_whereas_100",
      word: "whereas",
      translation: "mientras que (contraste)",
      partOfSpeech: 'conjunction',
      level: "B1",
      week: 4,
      topic: "discourse_markers",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/wɛrˈæz/',
      example: 'She loves the city, whereas he prefers the countryside.',
      exampleTranslation: 'A ella le encanta la ciudad, mientras que él prefiere el campo.',
      status: 'approved',
    },
    {
      "id": "voc_b1_provided-that_101",
      word: "provided that",
      translation: "siempre que/con la condición de que",
      partOfSpeech: 'conjunction',
      level: "B1",
      week: 4,
      topic: "discourse_markers",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/prəˈvaɪdɪd ðæt/',
      example: 'You can go out, provided that you finish your homework.',
      exampleTranslation: 'Puedes salir, siempre que termines tu tarea.',
      status: 'approved',
    },
    {
      "id": "voc_b1_unless_102",
      word: "unless",
      translation: "a menos que",
      partOfSpeech: 'conjunction',
      level: "B1",
      week: 4,
      topic: "discourse_markers",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ənˈlɛs/',
      example: 'We won\'t leave unless it stops raining.',
      exampleTranslation: 'No saldremos a menos que deje de llover.',
      status: 'approved',
    },
    {
      "id": "voc_b1_even-though_103",
      word: "even though",
      translation: "aunque",
      partOfSpeech: 'conjunction',
      level: "B1",
      week: 4,
      topic: "discourse_markers",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈivən ðoʊ/',
      example: 'Even though he was tired, he kept working.',
      exampleTranslation: 'Aunque estaba cansado, siguió trabajando.',
      status: 'approved',
    },
    {
      "id": "voc_b1_as-long-as_104",
      word: "as long as",
      translation: "mientras (condición)",
      partOfSpeech: 'conjunction',
      level: "B1",
      week: 4,
      topic: "discourse_markers",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/æz lɔŋ æz/',
      example: 'You can stay as long as you like.',
      exampleTranslation: 'Puedes quedarte mientras quieras.',
      status: 'approved',
    },
    {
      "id": "voc_b1_in-spite-of_105",
      word: "in spite of",
      translation: "a pesar de",
      partOfSpeech: 'conjunction',
      level: "B1",
      week: 4,
      topic: "discourse_markers",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ɪn spaɪt əv/',
      example: 'In spite of the rain, we went hiking.',
      exampleTranslation: 'A pesar de la lluvia, fuimos de senderismo.',
      status: 'approved',
    },
    {
      "id": "voc_b1_despite_106",
      word: "despite",
      translation: "a pesar de",
      partOfSpeech: 'conjunction',
      level: "B1",
      week: 4,
      topic: "discourse_markers",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/dɪˈspaɪt/',
      example: 'Despite the traffic, we arrived on time.',
      exampleTranslation: 'A pesar del tráfico, llegamos a tiempo.',
      status: 'approved',
    },
    {
      "id": "voc_b1_given-that_107",
      word: "given that",
      translation: "dado que",
      partOfSpeech: 'conjunction',
      level: "B1",
      week: 4,
      topic: "discourse_markers",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈgɪvən ðæt/',
      example: 'Given that it\'s late, let\'s finish tomorrow.',
      exampleTranslation: 'Dado que es tarde, terminemos mañana.',
      status: 'approved',
    },
    {
      "id": "voc_b1_assuming-that_108",
      word: "assuming that",
      translation: "suponiendo que",
      partOfSpeech: 'conjunction',
      level: "B1",
      week: 4,
      topic: "discourse_markers",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/əˈsumɪŋ ðæt/',
      example: 'Assuming that the plan works, we\'ll save money.',
      exampleTranslation: 'Suponiendo que el plan funcione, ahorraremos dinero.',
      status: 'approved',
    },
    {
      "id": "voc_b1_in-order-to_109",
      word: "in order to",
      translation: "con el fin de",
      partOfSpeech: 'conjunction',
      level: "B1",
      week: 4,
      topic: "discourse_markers",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ɪn ˈɔrdər tu/',
      example: 'She studied hard in order to pass the exam.',
      exampleTranslation: 'Ella estudió mucho con el fin de aprobar el examen.',
      status: 'approved',
    },
    {
      "id": "voc_b1_so-as-to_110",
      word: "so as to",
      translation: "para/con el objetivo de",
      partOfSpeech: 'conjunction',
      level: "B1",
      week: 4,
      topic: "discourse_markers",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/soʊ æz tu/',
      example: 'We left early so as to avoid traffic.',
      exampleTranslation: 'Salimos temprano para evitar el tráfico.',
      status: 'approved',
    },
    {
      "id": "voc_b1_rather-than_111",
      word: "rather than",
      translation: "en lugar de",
      partOfSpeech: 'conjunction',
      level: "B1",
      week: 4,
      topic: "discourse_markers",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈræðər ðæn/',
      example: 'I\'d rather walk rather than take the bus.',
      exampleTranslation: 'Prefiero caminar en lugar de tomar el autobús.',
      status: 'approved',
    },
    {
      "id": "voc_b1_as-opposed-to_112",
      word: "as opposed to",
      translation: "en contraposición a",
      partOfSpeech: 'conjunction',
      level: "B1",
      week: 4,
      topic: "discourse_markers",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/æz əˈpoʊzd tu/',
      example: 'We chose quality as opposed to quantity.',
      exampleTranslation: 'Elegimos calidad en contraposición a cantidad.',
      status: 'approved',
    },
    {
      "id": "voc_b1_on-the-whole_113",
      word: "on the whole",
      translation: "en general/en conjunto",
      partOfSpeech: 'conjunction',
      level: "B1",
      week: 4,
      topic: "discourse_markers",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ɑn ðə hoʊl/',
      example: 'On the whole, the trip was a success.',
      exampleTranslation: 'En general, el viaje fue un éxito.',
      status: 'approved',
    },
    {
      "id": "voc_b1_by-and-large_114",
      word: "by and large",
      translation: "en su mayor parte",
      partOfSpeech: 'conjunction',
      level: "B1",
      week: 4,
      topic: "discourse_markers",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/baɪ ənd lɑrdʒ/',
      example: 'By and large, people were satisfied.',
      exampleTranslation: 'En su mayor parte, la gente quedó satisfecha.',
      status: 'approved',
    },
    {
      "id": "voc_b1_needless-to-say_115",
      word: "needless to say",
      translation: "huelga decir/ni que decir",
      partOfSpeech: 'conjunction',
      level: "B1",
      week: 4,
      topic: "discourse_markers",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈnidləs tu seɪ/',
      example: 'Needless to say, we were very happy.',
      exampleTranslation: 'Huelga decir que estábamos muy felices.',
      status: 'approved',
    },
    {
      "id": "voc_b1_last-but-not-least_116",
      word: "last but not least",
      translation: "por último pero no menos importante",
      partOfSpeech: 'conjunction',
      level: "B1",
      week: 4,
      topic: "discourse_markers",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/læst bʌt nɑt list/',
      example: 'Last but not least, thank you all for coming.',
      exampleTranslation: 'Por último pero no menos importante, gracias a todos por venir.',
      status: 'approved',
    },
    {
      "id": "voc_b1_all-things-considered_117",
      word: "all things considered",
      translation: "considerándolo todo",
      partOfSpeech: 'conjunction',
      level: "B1",
      week: 4,
      topic: "discourse_markers",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ɔl θɪŋz kənˈsɪdərd/',
      example: 'All things considered, it was a good decision.',
      exampleTranslation: 'Considerándolo todo, fue una buena decisión.',
      status: 'approved',
    },
    {
      "id": "voc_b1_in-other-words_118",
      word: "in other words",
      translation: "en otras palabras",
      partOfSpeech: 'conjunction',
      level: "B1",
      week: 4,
      topic: "discourse_markers",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ɪn ˈʌðər wɜrdz/',
      example: 'In other words, we need more time.',
      exampleTranslation: 'En otras palabras, necesitamos más tiempo.',
      status: 'approved',
    },
    {
      "id": "voc_b1_that-being-said_119",
      word: "that being said",
      translation: "dicho esto",
      partOfSpeech: 'conjunction',
      level: "B1",
      week: 4,
      topic: "discourse_markers",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ðæt ˈbiɪŋ sɛd/',
      example: 'That being said, I still support the idea.',
      exampleTranslation: 'Dicho esto, sigo apoyando la idea.',
      status: 'approved',
    }
  ]
}
