import type { ContentBlock } from '../types'

/**
 * B1 Level Content — Week 6
 * Topic: B1 · Semana 6 – Medios de comunicación y actualidad
 * Curated from institutional curriculum (Zero AI)
 */
export const week06: ContentBlock = {
  level: "B1",
  week: 6,
  topic: "B1 · Semana 6 – Medios de comunicación y actualidad",
  vocabulary: [
    {
      "id": "voc_b1_article_146",
      word: "article",
      translation: "artículo",
      partOfSpeech: 'noun',
      level: "B1",
      week: 6,
      topic: "media_current_affairs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈɑrtɪkəl/',
      example: 'I read an interesting article today.',
      exampleTranslation: 'Leí un artículo interesante hoy.',
      status: 'approved',
    },
    {
      "id": "voc_b1_column-newspaper_147",
      word: "column (newspaper)",
      translation: "columna (periódico)",
      partOfSpeech: 'noun',
      level: "B1",
      week: 6,
      topic: "media_current_affairs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈkɑləm/',
      example: 'She writes a weekly column.',
      exampleTranslation: 'Ella escribe una columna semanal.',
      status: 'approved',
    },
    {
      "id": "voc_b1_broadcast_148",
      word: "broadcast",
      translation: "transmisión/emitir",
      partOfSpeech: 'verb',
      level: "B1",
      week: 6,
      topic: "media_current_affairs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈbrɔdˌkæst/',
      example: 'The game will be broadcast live.',
      exampleTranslation: 'El partido se transmitirá en vivo.',
      status: 'approved',
    },
    {
      "id": "voc_b1_coverage-news_149",
      word: "coverage (news)",
      translation: "cobertura (noticiosa)",
      partOfSpeech: 'noun',
      level: "B1",
      week: 6,
      topic: "media_current_affairs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈkʌvərɪdʒ/',
      example: 'The election coverage lasted all night.',
      exampleTranslation: 'La cobertura de las elecciones duró toda la noche.',
      status: 'approved',
    },
    {
      "id": "voc_b1_correspondent_150",
      word: "correspondent",
      translation: "corresponsal",
      partOfSpeech: 'noun',
      level: "B1",
      week: 6,
      topic: "media_current_affairs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˌkɔrəˈspɑndənt/',
      example: 'Our correspondent reported from the capital.',
      exampleTranslation: 'Nuestro corresponsal reportó desde la capital.',
      status: 'approved',
    },
    {
      "id": "voc_b1_editor_151",
      word: "editor",
      translation: "editor",
      partOfSpeech: 'noun',
      level: "B1",
      week: 6,
      topic: "media_current_affairs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈɛdɪtər/',
      example: 'The editor approved the final draft.',
      exampleTranslation: 'El editor aprobó el borrador final.',
      status: 'approved',
    },
    {
      "id": "voc_b1_feature-article_152",
      word: "feature (article)",
      translation: "reportaje/artículo especial",
      partOfSpeech: 'noun',
      level: "B1",
      week: 6,
      topic: "media_current_affairs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈfitʃər/',
      example: 'The magazine published a feature on climate change.',
      exampleTranslation: 'La revista publicó un reportaje sobre el cambio climático.',
      status: 'approved',
    },
    {
      "id": "voc_b1_interview-noun_153",
      word: "interview (noun)",
      translation: "entrevista",
      partOfSpeech: 'noun',
      level: "B1",
      week: 6,
      topic: "media_current_affairs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈɪntərˌvju/',
      example: 'I watched her interview last night.',
      exampleTranslation: 'Vi su entrevista anoche.',
      status: 'approved',
    },
    {
      "id": "voc_b1_investigate_154",
      word: "investigate",
      translation: "investigar",
      partOfSpeech: 'verb',
      level: "B1",
      week: 6,
      topic: "media_current_affairs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ɪnˈvɛstəˌgeɪt/',
      example: 'The journalists investigated the case for months.',
      exampleTranslation: 'Los periodistas investigaron el caso durante meses.',
      status: 'approved',
    },
    {
      "id": "voc_b1_source-news_155",
      word: "source (news)",
      translation: "fuente (informativa)",
      partOfSpeech: 'noun',
      level: "B1",
      week: 6,
      topic: "media_current_affairs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/sɔrs/',
      example: 'The reporter protected her source.',
      exampleTranslation: 'La periodista protegió su fuente.',
      status: 'approved',
    },
    {
      "id": "voc_b1_statement-public_156",
      word: "statement (public)",
      translation: "declaración (pública)",
      partOfSpeech: 'noun',
      level: "B1",
      week: 6,
      topic: "media_current_affairs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈsteɪtmənt/',
      example: 'The company released an official statement.',
      exampleTranslation: 'La empresa emitió una declaración oficial.',
      status: 'approved',
    },
    {
      "id": "voc_b1_survey_157",
      word: "survey",
      translation: "encuesta",
      partOfSpeech: 'noun',
      level: "B1",
      week: 6,
      topic: "media_current_affairs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈsɜrˌveɪ/',
      example: 'The survey showed interesting results.',
      exampleTranslation: 'La encuesta mostró resultados interesantes.',
      status: 'approved',
    },
    {
      "id": "voc_b1_poll_158",
      word: "poll",
      translation: "sondeo/encuesta",
      partOfSpeech: 'noun',
      level: "B1",
      week: 6,
      topic: "media_current_affairs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/poʊl/',
      example: 'The poll suggests a close election.',
      exampleTranslation: 'El sondeo sugiere una elección reñida.',
      status: 'approved',
    },
    {
      "id": "voc_b1_censorship_159",
      word: "censorship",
      translation: "censura",
      partOfSpeech: 'noun',
      level: "B1",
      week: 6,
      topic: "media_current_affairs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈsɛnsərˌʃɪp/',
      example: 'Censorship limits free speech.',
      exampleTranslation: 'La censura limita la libertad de expresión.',
      status: 'approved',
    },
    {
      "id": "voc_b1_propaganda_160",
      word: "propaganda",
      translation: "propaganda",
      partOfSpeech: 'noun',
      level: "B1",
      week: 6,
      topic: "media_current_affairs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˌprɑpəˈgændə/',
      example: 'The posters were pure propaganda.',
      exampleTranslation: 'Los carteles eran pura propaganda.',
      status: 'approved',
    },
    {
      "id": "voc_b1_bias_161",
      word: "bias",
      translation: "sesgo/parcialidad",
      partOfSpeech: 'noun',
      level: "B1",
      week: 6,
      topic: "media_current_affairs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈbaɪəs/',
      example: 'The article showed clear bias.',
      exampleTranslation: 'El artículo mostró un sesgo claro.',
      status: 'approved',
    },
    {
      "id": "voc_b1_credible_162",
      word: "credible",
      translation: "creíble",
      partOfSpeech: 'adjective',
      level: "B1",
      week: 6,
      topic: "media_current_affairs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈkrɛdəbəl/',
      example: 'Is this source credible?',
      exampleTranslation: '¿Es creíble esta fuente?',
      status: 'approved',
    },
    {
      "id": "voc_b1_misinformation_163",
      word: "misinformation",
      translation: "desinformación",
      partOfSpeech: 'noun',
      level: "B1",
      week: 6,
      topic: "media_current_affairs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˌmɪsɪnfərˈmeɪʃən/',
      example: 'Social media spreads misinformation quickly.',
      exampleTranslation: 'Las redes sociales difunden desinformación rápidamente.',
      status: 'approved',
    },
    {
      "id": "voc_b1_current-affairs_164",
      word: "current affairs",
      translation: "actualidad",
      partOfSpeech: 'noun',
      level: "B1",
      week: 6,
      topic: "media_current_affairs",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈkɜrənt əˈfɛrz/',
      example: 'She follows current affairs closely.',
      exampleTranslation: 'Ella sigue de cerca la actualidad.',
      status: 'approved',
    }
  ]
}
