import type { ContentBlock } from '../types'

/**
 * B1 Level Content — Week 7
 * Topic: B1 · Semana 7 – Economía y trabajo (nivel intermedio)
 * Curated from institutional curriculum (Zero AI)
 */
export const week07: ContentBlock = {
  level: "B1",
  week: 7,
  topic: "B1 · Semana 7 – Economía y trabajo (nivel intermedio)",
  vocabulary: [
    {
      "id": "voc_b1_economy_165",
      word: "economy",
      translation: "economía",
      partOfSpeech: 'noun',
      level: "B1",
      week: 7,
      topic: "economy_work",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ɪˈkɑnəmi/',
      example: 'The economy is growing slowly.',
      exampleTranslation: 'La economía está creciendo lentamente.',
      status: 'approved',
    },
    {
      "id": "voc_b1_inflation_166",
      word: "inflation",
      translation: "inflación",
      partOfSpeech: 'noun',
      level: "B1",
      week: 7,
      topic: "economy_work",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ɪnˈfleɪʃən/',
      example: 'Inflation raised the price of food.',
      exampleTranslation: 'La inflación subió el precio de la comida.',
      status: 'approved',
    },
    {
      "id": "voc_b1_recession_167",
      word: "recession",
      translation: "recesión",
      partOfSpeech: 'noun',
      level: "B1",
      week: 7,
      topic: "economy_work",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/rɪˈsɛʃən/',
      example: 'The country entered a recession last year.',
      exampleTranslation: 'El país entró en recesión el año pasado.',
      status: 'approved',
    },
    {
      "id": "voc_b1_unemployment_168",
      word: "unemployment",
      translation: "desempleo",
      partOfSpeech: 'noun',
      level: "B1",
      week: 7,
      topic: "economy_work",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˌʌnɪmˈplɔɪmənt/',
      example: 'Unemployment dropped this quarter.',
      exampleTranslation: 'El desempleo bajó este trimestre.',
      status: 'approved',
    },
    {
      "id": "voc_b1_income_169",
      word: "income",
      translation: "ingresos",
      partOfSpeech: 'noun',
      level: "B1",
      week: 7,
      topic: "economy_work",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈɪnˌkʌm/',
      example: 'Her income increased after the promotion.',
      exampleTranslation: 'Sus ingresos aumentaron después del ascenso.',
      status: 'approved',
    },
    {
      "id": "voc_b1_expense_170",
      word: "expense",
      translation: "gasto",
      partOfSpeech: 'noun',
      level: "B1",
      week: 7,
      topic: "economy_work",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ɪkˈspɛns/',
      example: 'Rent is our biggest expense.',
      exampleTranslation: 'El alquiler es nuestro gasto más grande.',
      status: 'approved',
    },
    {
      "id": "voc_b1_investment_171",
      word: "investment",
      translation: "inversión",
      partOfSpeech: 'noun',
      level: "B1",
      week: 7,
      topic: "economy_work",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ɪnˈvɛstmənt/',
      example: 'This was a smart investment.',
      exampleTranslation: 'Esta fue una inversión inteligente.',
      status: 'approved',
    },
    {
      "id": "voc_b1_profit_172",
      word: "profit",
      translation: "ganancia/beneficio",
      partOfSpeech: 'noun',
      level: "B1",
      week: 7,
      topic: "economy_work",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈprɑfɪt/',
      example: 'The company made a big profit this year.',
      exampleTranslation: 'La empresa tuvo una gran ganancia este año.',
      status: 'approved',
    },
    {
      "id": "voc_b1_loss-business_173",
      word: "loss (business)",
      translation: "pérdida (negocio)",
      partOfSpeech: 'noun',
      level: "B1",
      week: 7,
      topic: "economy_work",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/lɔs/',
      example: 'The business reported a loss last quarter.',
      exampleTranslation: 'El negocio reportó una pérdida el último trimestre.',
      status: 'approved',
    },
    {
      "id": "voc_b1_supply_174",
      word: "supply",
      translation: "oferta",
      partOfSpeech: 'noun',
      level: "B1",
      week: 7,
      topic: "economy_work",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/səˈplaɪ/',
      example: 'Supply and demand affect prices.',
      exampleTranslation: 'La oferta y la demanda afectan los precios.',
      status: 'approved',
    },
    {
      "id": "voc_b1_demand-economy_175",
      word: "demand (economy)",
      translation: "demanda (economía)",
      partOfSpeech: 'noun',
      level: "B1",
      week: 7,
      topic: "economy_work",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/dɪˈmænd/',
      example: 'Demand for the product increased.',
      exampleTranslation: 'La demanda del producto aumentó.',
      status: 'approved',
    },
    {
      "id": "voc_b1_trade_176",
      word: "trade",
      translation: "comercio",
      partOfSpeech: 'noun',
      level: "B1",
      week: 7,
      topic: "economy_work",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/treɪd/',
      example: 'Trade between the two countries grew.',
      exampleTranslation: 'El comercio entre los dos países creció.',
      status: 'approved',
    },
    {
      "id": "voc_b1_export_177",
      word: "export",
      translation: "exportar/exportación",
      partOfSpeech: 'noun',
      level: "B1",
      week: 7,
      topic: "economy_work",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈɛkspɔrt/',
      example: 'Coffee is a major export for this country.',
      exampleTranslation: 'El café es una exportación importante para este país.',
      status: 'approved',
    },
    {
      "id": "voc_b1_import_178",
      word: "import",
      translation: "importar/importación",
      partOfSpeech: 'noun',
      level: "B1",
      week: 7,
      topic: "economy_work",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈɪmpɔrt/',
      example: 'The import of cars increased last year.',
      exampleTranslation: 'La importación de autos aumentó el año pasado.',
      status: 'approved',
    },
    {
      "id": "voc_b1_industry_179",
      word: "industry",
      translation: "industria",
      partOfSpeech: 'noun',
      level: "B1",
      week: 7,
      topic: "economy_work",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈɪndəstri/',
      example: 'The tech industry keeps growing.',
      exampleTranslation: 'La industria tecnológica sigue creciendo.',
      status: 'approved',
    },
    {
      "id": "voc_b1_sector_180",
      word: "sector",
      translation: "sector",
      partOfSpeech: 'noun',
      level: "B1",
      week: 7,
      topic: "economy_work",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈsɛktər/',
      example: 'She works in the healthcare sector.',
      exampleTranslation: 'Ella trabaja en el sector salud.',
      status: 'approved',
    },
    {
      "id": "voc_b1_consumer_181",
      word: "consumer",
      translation: "consumidor",
      partOfSpeech: 'noun',
      level: "B1",
      week: 7,
      topic: "economy_work",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/kənˈsumər/',
      example: 'Consumers want better prices.',
      exampleTranslation: 'Los consumidores quieren mejores precios.',
      status: 'approved',
    },
    {
      "id": "voc_b1_entrepreneur_182",
      word: "entrepreneur",
      translation: "emprendedor",
      partOfSpeech: 'noun',
      level: "B1",
      week: 7,
      topic: "economy_work",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˌɑntrəprəˈnɜr/',
      example: 'She became a successful entrepreneur.',
      exampleTranslation: 'Ella se convirtió en una emprendedora exitosa.',
      status: 'approved',
    },
    {
      "id": "voc_b1_startup_183",
      word: "startup",
      translation: "empresa emergente",
      partOfSpeech: 'noun',
      level: "B1",
      week: 7,
      topic: "economy_work",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈstɑrˌtʌp/',
      example: 'He works for a small startup.',
      exampleTranslation: 'Él trabaja para una pequeña empresa emergente.',
      status: 'approved',
    },
    {
      "id": "voc_b1_revenue_184",
      word: "revenue",
      translation: "ingresos (empresa)",
      partOfSpeech: 'noun',
      level: "B1",
      week: 7,
      topic: "economy_work",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈrɛvəˌnu/',
      example: 'The company\'s revenue doubled.',
      exampleTranslation: 'Los ingresos de la empresa se duplicaron.',
      status: 'approved',
    },
    {
      "id": "voc_b1_asset_185",
      word: "asset",
      translation: "activo (financiero)",
      partOfSpeech: 'noun',
      level: "B1",
      week: 7,
      topic: "economy_work",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈæˌsɛt/',
      example: 'The building is a valuable asset.',
      exampleTranslation: 'El edificio es un activo valioso.',
      status: 'approved',
    },
    {
      "id": "voc_b1_shareholder_186",
      word: "shareholder",
      translation: "accionista",
      partOfSpeech: 'noun',
      level: "B1",
      week: 7,
      topic: "economy_work",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/ˈʃɛrˌhoʊldər/',
      example: 'Shareholders approved the new plan.',
      exampleTranslation: 'Los accionistas aprobaron el nuevo plan.',
      status: 'approved',
    },
    {
      "id": "voc_b1_stock-finance_187",
      word: "stock (finance)",
      translation: "acción (bolsa)",
      partOfSpeech: 'noun',
      level: "B1",
      week: 7,
      topic: "economy_work",
      verifiedBy: "curator_editorial_team",
      verifiedAt: "2026-09-13",
      source: "PLAN DE ESTUDIO.md",
      pronunciation: '/stɑk/',
      example: 'She invested in stock last year.',
      exampleTranslation: 'Ella invirtió en acciones el año pasado.',
      status: 'approved',
    }
  ]
}
