import type { ContentBlock } from '../types'

/**
 * B1 Level Content — Week 1
 * Topic: Medio ambiente y cambio climático
 * Curated from institutional curriculum (Zero AI)
 */
export const week01: ContentBlock = {
  level: 'B1',
  week: 1,
  topic: 'Medio ambiente y cambio climático',
  vocabulary: [
    {
      id: 'voc_b1_environment_001',
      word: 'environment',
      translation: 'medio ambiente / entorno',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 1,
      topic: 'medio-ambiente-y-clima',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_climate-change_002',
      word: 'climate change',
      translation: 'cambio climático',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 1,
      topic: 'medio-ambiente-y-clima',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_global-warming_003',
      word: 'global warming',
      translation: 'calentamiento global',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 1,
      topic: 'medio-ambiente-y-clima',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_pollution_004',
      word: 'pollution',
      translation: 'contaminación',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 1,
      topic: 'medio-ambiente-y-clima',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_renewable-energy_005',
      word: 'renewable energy',
      translation: 'energía renovable',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 1,
      topic: 'medio-ambiente-y-clima',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_solar-power_006',
      word: 'solar power',
      translation: 'energía solar',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 1,
      topic: 'medio-ambiente-y-clima',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_wind-turbine_007',
      word: 'wind turbine',
      translation: 'turbina eólica / aerogenerador',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 1,
      topic: 'medio-ambiente-y-clima',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_carbon-footprint_008',
      word: 'carbon footprint',
      translation: 'huella de carbono',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 1,
      topic: 'medio-ambiente-y-clima',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_greenhouse-effect_009',
      word: 'greenhouse effect',
      translation: 'efecto invernadero',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 1,
      topic: 'medio-ambiente-y-clima',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_fossil-fuel_010',
      word: 'fossil fuel',
      translation: 'combustible fósil',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 1,
      topic: 'medio-ambiente-y-clima',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_recycle_011',
      word: 'recycle',
      translation: 'reciclar',
      partOfSpeech: 'verb',
      level: 'B1',
      week: 1,
      topic: 'medio-ambiente-y-clima',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_reuse_012',
      word: 'reuse',
      translation: 'reutilizar',
      partOfSpeech: 'verb',
      level: 'B1',
      week: 1,
      topic: 'medio-ambiente-y-clima',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_reduce_013',
      word: 'reduce',
      translation: 'reducir / disminuir',
      partOfSpeech: 'verb',
      level: 'B1',
      week: 1,
      topic: 'medio-ambiente-y-clima',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_waste_014',
      word: 'waste',
      translation: 'residuos / desperdicio',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 1,
      topic: 'medio-ambiente-y-clima',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_ecosystem_015',
      word: 'ecosystem',
      translation: 'ecosistema',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 1,
      topic: 'medio-ambiente-y-clima',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_biodiversity_016',
      word: 'biodiversity',
      translation: 'biodiversidad',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 1,
      topic: 'medio-ambiente-y-clima',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_habitat_017',
      word: 'habitat',
      translation: 'hábitat',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 1,
      topic: 'medio-ambiente-y-clima',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_species_018',
      word: 'species',
      translation: 'especie / especies',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 1,
      topic: 'medio-ambiente-y-clima',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_endangered_019',
      word: 'endangered',
      translation: 'en peligro de extinción',
      partOfSpeech: 'adjective',
      level: 'B1',
      week: 1,
      topic: 'medio-ambiente-y-clima',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_extinct_020',
      word: 'extinct',
      translation: 'extinto / desaparecido',
      partOfSpeech: 'adjective',
      level: 'B1',
      week: 1,
      topic: 'medio-ambiente-y-clima',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_deforestation_021',
      word: 'deforestation',
      translation: 'deforestación / tala indiscriminada',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 1,
      topic: 'medio-ambiente-y-clima',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_conservation_022',
      word: 'conservation',
      translation: 'conservación / preservación',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 1,
      topic: 'medio-ambiente-y-clima',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_sustainable_023',
      word: 'sustainable',
      translation: 'sostenible / sustentable',
      partOfSpeech: 'adjective',
      level: 'B1',
      week: 1,
      topic: 'medio-ambiente-y-clima',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_organic_024',
      word: 'organic',
      translation: 'orgánico / ecológico',
      partOfSpeech: 'adjective',
      level: 'B1',
      week: 1,
      topic: 'medio-ambiente-y-clima',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_natural-resource_025',
      word: 'natural resource',
      translation: 'recurso natural',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 1,
      topic: 'medio-ambiente-y-clima',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_drought_026',
      word: 'drought',
      translation: 'sequía',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 1,
      topic: 'medio-ambiente-y-clima',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_flood_027',
      word: 'flood',
      translation: 'inundación',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 1,
      topic: 'medio-ambiente-y-clima',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_emission_028',
      word: 'emission',
      translation: 'emisión (de gases)',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 1,
      topic: 'medio-ambiente-y-clima',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_atmosphere_029',
      word: 'atmosphere',
      translation: 'atmósfera',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 1,
      topic: 'medio-ambiente-y-clima',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_ozone-layer_030',
      word: 'ozone layer',
      translation: 'capa de ozono',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 1,
      topic: 'medio-ambiente-y-clima',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_protect_031',
      word: 'protect',
      translation: 'proteger / resguardar',
      partOfSpeech: 'verb',
      level: 'B1',
      week: 1,
      topic: 'medio-ambiente-y-clima',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_destroy_032',
      word: 'destroy',
      translation: 'destruir',
      partOfSpeech: 'verb',
      level: 'B1',
      week: 1,
      topic: 'medio-ambiente-y-clima',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_preserve_033',
      word: 'preserve',
      translation: 'preservar / conservar',
      partOfSpeech: 'verb',
      level: 'B1',
      week: 1,
      topic: 'medio-ambiente-y-clima',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_threaten_034',
      word: 'threaten',
      translation: 'amenazar',
      partOfSpeech: 'verb',
      level: 'B1',
      week: 1,
      topic: 'medio-ambiente-y-clima',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_survive_035',
      word: 'survive',
      translation: 'sobrevivir',
      partOfSpeech: 'verb',
      level: 'B1',
      week: 1,
      topic: 'medio-ambiente-y-clima',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_ecological_036',
      word: 'ecological',
      translation: 'ecológico',
      partOfSpeech: 'adjective',
      level: 'B1',
      week: 1,
      topic: 'medio-ambiente-y-clima',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_toxic_037',
      word: 'toxic',
      translation: 'tóxico / dañino',
      partOfSpeech: 'adjective',
      level: 'B1',
      week: 1,
      topic: 'medio-ambiente-y-clima',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_wildlife_038',
      word: 'wildlife',
      translation: 'vida silvestre / fauna',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 1,
      topic: 'medio-ambiente-y-clima',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
  ],
}
