import type { ContentBlock } from '../types'

/**
 * B1 Level Content — Week 6
 * Topic: Vocabulario académico general y análisis
 * Curated from institutional curriculum (Zero AI)
 */
export const week06: ContentBlock = {
  level: 'B1',
  week: 6,
  topic: 'Vocabulario académico general y análisis',
  vocabulary: [
    {
      id: 'voc_b1_analyze_169',
      word: 'analyze',
      translation: 'analizar minuciosamente',
      partOfSpeech: 'verb',
      level: 'B1',
      week: 6,
      topic: 'vocabulario-academico',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_summarize_170',
      word: 'summarize',
      translation: 'resumir / sintetizar',
      partOfSpeech: 'verb',
      level: 'B1',
      week: 6,
      topic: 'vocabulario-academico',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_conclude_171',
      word: 'conclude',
      translation: 'concluir / deducir',
      partOfSpeech: 'verb',
      level: 'B1',
      week: 6,
      topic: 'vocabulario-academico',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_evaluate_172',
      word: 'evaluate',
      translation: 'evaluar / valorar',
      partOfSpeech: 'verb',
      level: 'B1',
      week: 6,
      topic: 'vocabulario-academico',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_investigate_173',
      word: 'investigate',
      translation: 'investigar',
      partOfSpeech: 'verb',
      level: 'B1',
      week: 6,
      topic: 'vocabulario-academico',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_demonstrate_174',
      word: 'demonstrate',
      translation: 'demostrar / probar',
      partOfSpeech: 'verb',
      level: 'B1',
      week: 6,
      topic: 'vocabulario-academico',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_illustrate_175',
      word: 'illustrate',
      translation: 'ilustrar / ejemplificar',
      partOfSpeech: 'verb',
      level: 'B1',
      week: 6,
      topic: 'vocabulario-academico',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_hypothesis_176',
      word: 'hypothesis',
      translation: 'hipótesis',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 6,
      topic: 'vocabulario-academico',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_methodology_177',
      word: 'methodology',
      translation: 'metodología',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 6,
      topic: 'vocabulario-academico',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_evidence_178',
      word: 'evidence',
      translation: 'evidencia / pruebas empíricas',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 6,
      topic: 'vocabulario-academico',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_conclusion_179',
      word: 'conclusion',
      translation: 'conclusión',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 6,
      topic: 'vocabulario-academico',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_summary_180',
      word: 'summary',
      translation: 'resumen / sinopsis',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 6,
      topic: 'vocabulario-academico',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_criteria_181',
      word: 'criteria',
      translation: 'criterios de evaluación',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 6,
      topic: 'vocabulario-academico',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_concept_182',
      word: 'concept',
      translation: 'concepto / noción',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 6,
      topic: 'vocabulario-academico',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_definition_183',
      word: 'definition',
      translation: 'definición',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 6,
      topic: 'vocabulario-academico',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_factor_184',
      word: 'factor',
      translation: 'factor / elemento determinante',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 6,
      topic: 'vocabulario-academico',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_proportion_185',
      word: 'proportion',
      translation: 'proporción',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 6,
      topic: 'vocabulario-academico',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_percentage_186',
      word: 'percentage',
      translation: 'porcentaje',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 6,
      topic: 'vocabulario-academico',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_category_187',
      word: 'category',
      translation: 'categoría / clasificación',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 6,
      topic: 'vocabulario-academico',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_variable_188',
      word: 'variable',
      translation: 'variable (de estudio)',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 6,
      topic: 'vocabulario-academico',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_sample_189',
      word: 'sample',
      translation: 'muestra de estudio',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 6,
      topic: 'vocabulario-academico',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_survey_190',
      word: 'survey',
      translation: 'encuesta / sondeo',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 6,
      topic: 'vocabulario-academico',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_questionnaire_191',
      word: 'questionnaire',
      translation: 'cuestionario',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 6,
      topic: 'vocabulario-academico',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_findings_192',
      word: 'findings',
      translation: 'hallazgos / resultados de investigación',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 6,
      topic: 'vocabulario-academico',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_relevant_193',
      word: 'relevant',
      translation: 'relevante / pertinente',
      partOfSpeech: 'adjective',
      level: 'B1',
      week: 6,
      topic: 'vocabulario-academico',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_significant_194',
      word: 'significant',
      translation: 'significativo / notable',
      partOfSpeech: 'adjective',
      level: 'B1',
      week: 6,
      topic: 'vocabulario-academico',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_accurate_195',
      word: 'accurate',
      translation: 'preciso / exacto',
      partOfSpeech: 'adjective',
      level: 'B1',
      week: 6,
      topic: 'vocabulario-academico',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_objective_196',
      word: 'objective',
      translation: 'objetivo / imparcial',
      partOfSpeech: 'adjective',
      level: 'B1',
      week: 6,
      topic: 'vocabulario-academico',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_subjective_197',
      word: 'subjective',
      translation: 'subjetivo',
      partOfSpeech: 'adjective',
      level: 'B1',
      week: 6,
      topic: 'vocabulario-academico',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_primary_198',
      word: 'primary',
      translation: 'primario / principal',
      partOfSpeech: 'adjective',
      level: 'B1',
      week: 6,
      topic: 'vocabulario-academico',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_secondary_199',
      word: 'secondary',
      translation: 'secundario',
      partOfSpeech: 'adjective',
      level: 'B1',
      week: 6,
      topic: 'vocabulario-academico',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_consistent_200',
      word: 'consistent',
      translation: 'consistente / coherente',
      partOfSpeech: 'adjective',
      level: 'B1',
      week: 6,
      topic: 'vocabulario-academico',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_approximately_201',
      word: 'approximately',
      translation: 'aproximadamente',
      partOfSpeech: 'adverb',
      level: 'B1',
      week: 6,
      topic: 'vocabulario-academico',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_initially_202',
      word: 'initially',
      translation: 'inicialmente / en un principio',
      partOfSpeech: 'adverb',
      level: 'B1',
      week: 6,
      topic: 'vocabulario-academico',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_predominantly_203',
      word: 'predominantly',
      translation: 'predominantemente / principalmente',
      partOfSpeech: 'adverb',
      level: 'B1',
      week: 6,
      topic: 'vocabulario-academico',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
  ],
}
