import type { ContentBlock } from '../types'

/**
 * B1 Level Content — Week 2
 * Topic: Economía y finanzas personales
 * Curated from institutional curriculum (Zero AI)
 */
export const week02: ContentBlock = {
  level: 'B1',
  week: 2,
  topic: 'Economía y finanzas personales',
  vocabulary: [
    {
      id: 'voc_b1_economy_039',
      word: 'economy',
      translation: 'economía (sistema)',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 2,
      topic: 'economia-y-finanzas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_finance_040',
      word: 'finance',
      translation: 'finanzas',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 2,
      topic: 'economia-y-finanzas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_investment_041',
      word: 'investment',
      translation: 'inversión',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 2,
      topic: 'economia-y-finanzas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_inflation_042',
      word: 'inflation',
      translation: 'inflación',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 2,
      topic: 'economia-y-finanzas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_interest-rate_043',
      word: 'interest rate',
      translation: 'tasa de interés',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 2,
      topic: 'economia-y-finanzas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_budget_044',
      word: 'budget',
      translation: 'presupuesto',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 2,
      topic: 'economia-y-finanzas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_income_045',
      word: 'income',
      translation: 'ingreso / renta',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 2,
      topic: 'economia-y-finanzas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_expense_046',
      word: 'expense',
      translation: 'gasto / desembolso',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 2,
      topic: 'economia-y-finanzas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_debt_047',
      word: 'debt',
      translation: 'deuda',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 2,
      topic: 'economia-y-finanzas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_loan_048',
      word: 'loan',
      translation: 'préstamo / crédito bancario',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 2,
      topic: 'economia-y-finanzas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_mortgage_049',
      word: 'mortgage',
      translation: 'hipoteca',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 2,
      topic: 'economia-y-finanzas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_tax_050',
      word: 'tax',
      translation: 'impuesto / tributo',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 2,
      topic: 'economia-y-finanzas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_salary_051',
      word: 'salary',
      translation: 'salario / sueldo mensual',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 2,
      topic: 'economia-y-finanzas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_profit_052',
      word: 'profit',
      translation: 'ganancia / utilidad / beneficio',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 2,
      topic: 'economia-y-finanzas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_loss_053',
      word: 'loss',
      translation: 'pérdida económica',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 2,
      topic: 'economia-y-finanzas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_bankruptcy_054',
      word: 'bankruptcy',
      translation: 'bancarrota / quiebra',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 2,
      topic: 'economia-y-finanzas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_currency_055',
      word: 'currency',
      translation: 'moneda / divisa',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 2,
      topic: 'economia-y-finanzas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_exchange-rate_056',
      word: 'exchange rate',
      translation: 'tipo de cambio',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 2,
      topic: 'economia-y-finanzas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_savings_057',
      word: 'savings',
      translation: 'ahorros',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 2,
      topic: 'economia-y-finanzas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_afford_058',
      word: 'afford',
      translation: 'permitirse pagar / costear',
      partOfSpeech: 'verb',
      level: 'B1',
      week: 2,
      topic: 'economia-y-finanzas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_invest_059',
      word: 'invest',
      translation: 'invertir capital',
      partOfSpeech: 'verb',
      level: 'B1',
      week: 2,
      topic: 'economia-y-finanzas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_borrow_060',
      word: 'borrow',
      translation: 'pedir prestado',
      partOfSpeech: 'verb',
      level: 'B1',
      week: 2,
      topic: 'economia-y-finanzas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_lend_061',
      word: 'lend',
      translation: 'prestar dinero',
      partOfSpeech: 'verb',
      level: 'B1',
      week: 2,
      topic: 'economia-y-finanzas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_owe_062',
      word: 'owe',
      translation: 'deber dinero',
      partOfSpeech: 'verb',
      level: 'B1',
      week: 2,
      topic: 'economia-y-finanzas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_pay-off_063',
      word: 'pay off',
      translation: 'liquidar / saldar una deuda',
      partOfSpeech: 'phrasal-verb',
      level: 'B1',
      week: 2,
      topic: 'economia-y-finanzas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_economical_064',
      word: 'economical',
      translation: 'económico / ahorrativo',
      partOfSpeech: 'adjective',
      level: 'B1',
      week: 2,
      topic: 'economia-y-finanzas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_financial_065',
      word: 'financial',
      translation: 'financiero',
      partOfSpeech: 'adjective',
      level: 'B1',
      week: 2,
      topic: 'economia-y-finanzas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_trade_066',
      word: 'trade',
      translation: 'comercio / intercambio comercial',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 2,
      topic: 'economia-y-finanzas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_consumer_067',
      word: 'consumer',
      translation: 'consumidor',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 2,
      topic: 'economia-y-finanzas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_stock_068',
      word: 'stock',
      translation: 'acción bursátil / valor',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 2,
      topic: 'economia-y-finanzas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_wealth_069',
      word: 'wealth',
      translation: 'riqueza / patrimonio',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 2,
      topic: 'economia-y-finanzas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_poverty_070',
      word: 'poverty',
      translation: 'pobreza',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 2,
      topic: 'economia-y-finanzas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_recession_071',
      word: 'recession',
      translation: 'recesión económica',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 2,
      topic: 'economia-y-finanzas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_revenue_072',
      word: 'revenue',
      translation: 'ingresos brutos / recaudación',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 2,
      topic: 'economia-y-finanzas',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
  ],
}
