import type { ContentBlock } from '../types'

/**
 * B1 Level Content — Week 5
 * Topic: Debate, argumentación y conectores lógicos
 * Curated from institutional curriculum (Zero AI)
 */
export const week05: ContentBlock = {
  level: 'B1',
  week: 5,
  topic: 'Debate, argumentación y conectores lógicos',
  vocabulary: [
    {
      id: 'voc_b1_furthermore_135',
      word: 'furthermore',
      translation: 'además / es más',
      partOfSpeech: 'adverb',
      level: 'B1',
      week: 5,
      topic: 'debate-y-argumentacion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_moreover_136',
      word: 'moreover',
      translation: 'por otra parte / además',
      partOfSpeech: 'adverb',
      level: 'B1',
      week: 5,
      topic: 'debate-y-argumentacion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_however_137',
      word: 'however',
      translation: 'sin embargo / no obstante',
      partOfSpeech: 'adverb',
      level: 'B1',
      week: 5,
      topic: 'debate-y-argumentacion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_nevertheless_138',
      word: 'nevertheless',
      translation: 'no obstante / a pesar de todo',
      partOfSpeech: 'adverb',
      level: 'B1',
      week: 5,
      topic: 'debate-y-argumentacion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_although_139',
      word: 'although',
      translation: 'aunque / si bien',
      partOfSpeech: 'conjunction',
      level: 'B1',
      week: 5,
      topic: 'debate-y-argumentacion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_whereas_140',
      word: 'whereas',
      translation: 'mientras que / en tanto que',
      partOfSpeech: 'conjunction',
      level: 'B1',
      week: 5,
      topic: 'debate-y-argumentacion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_therefore_141',
      word: 'therefore',
      translation: 'por lo tanto / por consiguiente',
      partOfSpeech: 'adverb',
      level: 'B1',
      week: 5,
      topic: 'debate-y-argumentacion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_consequently_142',
      word: 'consequently',
      translation: 'en consecuencia / por ende',
      partOfSpeech: 'adverb',
      level: 'B1',
      week: 5,
      topic: 'debate-y-argumentacion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_otherwise_143',
      word: 'otherwise',
      translation: 'de lo contrario / de otro modo',
      partOfSpeech: 'adverb',
      level: 'B1',
      week: 5,
      topic: 'debate-y-argumentacion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_in-contrast_144',
      word: 'in contrast',
      translation: 'en contraste / por el contrario',
      partOfSpeech: 'adverb',
      level: 'B1',
      week: 5,
      topic: 'debate-y-argumentacion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_on-the-one-hand_145',
      word: 'on the one hand',
      translation: 'por un lado',
      partOfSpeech: 'adverb',
      level: 'B1',
      week: 5,
      topic: 'debate-y-argumentacion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_on-the-other-hand_146',
      word: 'on the other hand',
      translation: 'por otro lado',
      partOfSpeech: 'adverb',
      level: 'B1',
      week: 5,
      topic: 'debate-y-argumentacion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_in-addition_147',
      word: 'in addition',
      translation: 'además / adicionalmente',
      partOfSpeech: 'adverb',
      level: 'B1',
      week: 5,
      topic: 'debate-y-argumentacion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_as-a-result_148',
      word: 'as a result',
      translation: 'como resultado / por esa razón',
      partOfSpeech: 'adverb',
      level: 'B1',
      week: 5,
      topic: 'debate-y-argumentacion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_despite_149',
      word: 'despite',
      translation: 'a pesar de',
      partOfSpeech: 'preposition',
      level: 'B1',
      week: 5,
      topic: 'debate-y-argumentacion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_in-spite-of_150',
      word: 'in spite of',
      translation: 'a pesar de / no obstante',
      partOfSpeech: 'preposition',
      level: 'B1',
      week: 5,
      topic: 'debate-y-argumentacion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_perspective_151',
      word: 'perspective',
      translation: 'perspectiva / enfoque',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 5,
      topic: 'debate-y-argumentacion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_viewpoint_152',
      word: 'viewpoint',
      translation: 'punto de vista',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 5,
      topic: 'debate-y-argumentacion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_argue_153',
      word: 'argue',
      translation: 'argumentar / sostener una postura',
      partOfSpeech: 'verb',
      level: 'B1',
      week: 5,
      topic: 'debate-y-argumentacion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_claim_154',
      word: 'claim',
      translation: 'afirmar / sostener / alegar',
      partOfSpeech: 'verb',
      level: 'B1',
      week: 5,
      topic: 'debate-y-argumentacion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_justify_155',
      word: 'justify',
      translation: 'justificar',
      partOfSpeech: 'verb',
      level: 'B1',
      week: 5,
      topic: 'debate-y-argumentacion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_clarify_156',
      word: 'clarify',
      translation: 'aclarar / clarificar',
      partOfSpeech: 'verb',
      level: 'B1',
      week: 5,
      topic: 'debate-y-argumentacion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_emphasize_157',
      word: 'emphasize',
      translation: 'enfatizar / hacer hincapié',
      partOfSpeech: 'verb',
      level: 'B1',
      week: 5,
      topic: 'debate-y-argumentacion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_dispute_158',
      word: 'dispute',
      translation: 'disputar / cuestionar',
      partOfSpeech: 'verb',
      level: 'B1',
      week: 5,
      topic: 'debate-y-argumentacion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_oppose_159',
      word: 'oppose',
      translation: 'oponerse a',
      partOfSpeech: 'verb',
      level: 'B1',
      week: 5,
      topic: 'debate-y-argumentacion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_advocate_160',
      word: 'advocate',
      translation: 'abogar por / defender activamente',
      partOfSpeech: 'verb',
      level: 'B1',
      week: 5,
      topic: 'debate-y-argumentacion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_consensus_161',
      word: 'consensus',
      translation: 'consenso / acuerdo general',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 5,
      topic: 'debate-y-argumentacion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_conflict_162',
      word: 'conflict',
      translation: 'conflicto / desacuerdo',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 5,
      topic: 'debate-y-argumentacion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_dilemma_163',
      word: 'dilemma',
      translation: 'dilema',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 5,
      topic: 'debate-y-argumentacion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_priority_164',
      word: 'priority',
      translation: 'prioridad',
      partOfSpeech: 'noun',
      level: 'B1',
      week: 5,
      topic: 'debate-y-argumentacion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_fundamental_165',
      word: 'fundamental',
      translation: 'fundamental / esencial',
      partOfSpeech: 'adjective',
      level: 'B1',
      week: 5,
      topic: 'debate-y-argumentacion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_controversial_166',
      word: 'controversial',
      translation: 'controvertido / polémico',
      partOfSpeech: 'adjective',
      level: 'B1',
      week: 5,
      topic: 'debate-y-argumentacion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_rational_167',
      word: 'rational',
      translation: 'racional / lógico',
      partOfSpeech: 'adjective',
      level: 'B1',
      week: 5,
      topic: 'debate-y-argumentacion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
    {
      id: 'voc_b1_convincing_168',
      word: 'convincing',
      translation: 'convincente',
      partOfSpeech: 'adjective',
      level: 'B1',
      week: 5,
      topic: 'debate-y-argumentacion',
      verifiedBy: 'curator_editorial_team',
      verifiedAt: '2026-09-10',
      source: 'PLAN DE ESTUDIO.md',
      status: 'approved',
    },
  ],
}
