import type { ContentBlock } from '../types'

/**
 * B1 Level Content — Week 9
 * Topic: B1 · Semana 9 – Adjetivos descriptivos avanzados
 * Curated from institutional curriculum (Zero AI)
 */
export const week09: ContentBlock = {
  "level": "B1",
  "week": 9,
  "topic": "B1 · Semana 9 – Adjetivos descriptivos avanzados",
  "vocabulary": [
    {
      "id": "voc_b1_ambiguous_203",
      "word": "ambiguous",
      "translation": "ambiguo",
      "partOfSpeech": "adjective",
      "level": "B1",
      "week": 9,
      "topic": "advanced_adjectives",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_controversial_204",
      "word": "controversial",
      "translation": "controvertido",
      "partOfSpeech": "adjective",
      "level": "B1",
      "week": 9,
      "topic": "advanced_adjectives",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_significant_205",
      "word": "significant",
      "translation": "significativo",
      "partOfSpeech": "adjective",
      "level": "B1",
      "week": 9,
      "topic": "advanced_adjectives",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_substantial_206",
      "word": "substantial",
      "translation": "sustancial",
      "partOfSpeech": "adjective",
      "level": "B1",
      "week": 9,
      "topic": "advanced_adjectives",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_considerable_207",
      "word": "considerable",
      "translation": "considerable",
      "partOfSpeech": "adjective",
      "level": "B1",
      "week": 9,
      "topic": "advanced_adjectives",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_remarkable_208",
      "word": "remarkable",
      "translation": "notable",
      "partOfSpeech": "adjective",
      "level": "B1",
      "week": 9,
      "topic": "advanced_adjectives",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_noteworthy_209",
      "word": "noteworthy",
      "translation": "digno de mención",
      "partOfSpeech": "adjective",
      "level": "B1",
      "week": 9,
      "topic": "advanced_adjectives",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_inevitable_210",
      "word": "inevitable",
      "translation": "inevitable",
      "partOfSpeech": "adjective",
      "level": "B1",
      "week": 9,
      "topic": "advanced_adjectives",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_plausible_211",
      "word": "plausible",
      "translation": "plausible",
      "partOfSpeech": "adjective",
      "level": "B1",
      "week": 9,
      "topic": "advanced_adjectives",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_feasible_212",
      "word": "feasible",
      "translation": "factible",
      "partOfSpeech": "adjective",
      "level": "B1",
      "week": 9,
      "topic": "advanced_adjectives",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_viable_213",
      "word": "viable",
      "translation": "viable",
      "partOfSpeech": "adjective",
      "level": "B1",
      "week": 9,
      "topic": "advanced_adjectives",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_consistent_214",
      "word": "consistent",
      "translation": "consistente/constante",
      "partOfSpeech": "adjective",
      "level": "B1",
      "week": 9,
      "topic": "advanced_adjectives",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_coherent_215",
      "word": "coherent",
      "translation": "coherente",
      "partOfSpeech": "adjective",
      "level": "B1",
      "week": 9,
      "topic": "advanced_adjectives",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_comprehensive_216",
      "word": "comprehensive",
      "translation": "integral/exhaustivo",
      "partOfSpeech": "adjective",
      "level": "B1",
      "week": 9,
      "topic": "advanced_adjectives",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_thorough_217",
      "word": "thorough",
      "translation": "minucioso",
      "partOfSpeech": "adjective",
      "level": "B1",
      "week": 9,
      "topic": "advanced_adjectives",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_superficial_218",
      "word": "superficial",
      "translation": "superficial",
      "partOfSpeech": "adjective",
      "level": "B1",
      "week": 9,
      "topic": "advanced_adjectives",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_subtle_219",
      "word": "subtle",
      "translation": "sutil",
      "partOfSpeech": "adjective",
      "level": "B1",
      "week": 9,
      "topic": "advanced_adjectives",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_versatile_220",
      "word": "versatile",
      "translation": "versátil",
      "partOfSpeech": "adjective",
      "level": "B1",
      "week": 9,
      "topic": "advanced_adjectives",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_adaptable_221",
      "word": "adaptable",
      "translation": "adaptable",
      "partOfSpeech": "adjective",
      "level": "B1",
      "week": 9,
      "topic": "advanced_adjectives",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_innovative_222",
      "word": "innovative",
      "translation": "innovador",
      "partOfSpeech": "adjective",
      "level": "B1",
      "week": 9,
      "topic": "advanced_adjectives",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_conventional_223",
      "word": "conventional",
      "translation": "convencional",
      "partOfSpeech": "adjective",
      "level": "B1",
      "week": 9,
      "topic": "advanced_adjectives",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_prevalent_224",
      "word": "prevalent",
      "translation": "predominante",
      "partOfSpeech": "adjective",
      "level": "B1",
      "week": 9,
      "topic": "advanced_adjectives",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_widespread_225",
      "word": "widespread",
      "translation": "generalizado",
      "partOfSpeech": "adjective",
      "level": "B1",
      "week": 9,
      "topic": "advanced_adjectives",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    },
    {
      "id": "voc_b1_prominent_226",
      "word": "prominent",
      "translation": "prominente/destacado",
      "partOfSpeech": "adjective",
      "level": "B1",
      "week": 9,
      "topic": "advanced_adjectives",
      "verifiedBy": "curator_editorial_team",
      "verifiedAt": "2026-09-13",
      "source": "PLAN DE ESTUDIO.md",
      "status": "curated"
    }
  ]
}
